SELECT 
	STOCKTRANSACTION.ORDERCODE,
	STOCKTRANSACTION.LOGICALWAREHOUSECODE,
	STOCKTRANSACTION.DECOSUBCODE01,
	STOCKTRANSACTION.DECOSUBCODE02,
	STOCKTRANSACTION.DECOSUBCODE03,
	STOCKTRANSACTION.DECOSUBCODE04,
	STOCKTRANSACTION.DECOSUBCODE05,
	STOCKTRANSACTION.DECOSUBCODE06,
	STOCKTRANSACTION.DECOSUBCODE07,
	STOCKTRANSACTION.DECOSUBCODE08,
	STOCKTRANSACTION.TRANSACTIONDATE,
	STOCKTRANSACTION.LOTCODE,
	STOCKTRANSACTION.CREATIONUSER,
	STOCKTRANSACTION.PROJECTCODE,
	COUNT(STOCKTRANSACTION.BASEPRIMARYQUANTITY) AS QTY_DUS,
	SUM(STOCKTRANSACTION.BASEPRIMARYQUANTITY) AS QTY_KG,
	ITXVIEWKNTORDER.PRODUCTIONDEMANDCODE,
	ITXVIEWKNTORDER.LEGALNAME1,
	FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION,
	ITXVIEWKK.LONGDESCRIPTION,
	ITXVIEWKK.DSUBCODE01, 
	ITXVIEWKK.DSUBCODE02,
	ITXVIEWKK.DSUBCODE03,
	ITXVIEWKK.DSUBCODE04,
	ITXVIEWKK.DSUBCODE05,
	ITXVIEWKK.DSUBCODE06,
	ITXVIEWKK.DSUBCODE07,
	ITXVIEWKK.DSUBCODE08
	FROM DB2ADMIN.STOCKTRANSACTION STOCKTRANSACTION LEFT OUTER JOIN
	(SELECT 
	ITXVIEWKNTORDER.PRODUCTIONORDERCODE,	
	ITXVIEWKNTORDER.INITIALSCHEDULEDACTUALDATE,
	LISTAGG(DISTINCT  TRIM(ITXVIEWKNTORDER.PRODUCTIONDEMANDCODE),', ') AS PRODUCTIONDEMANDCODE,
	ITXVIEWKNTORDER.LEGALNAME1 FROM 
DB2ADMIN.ITXVIEWKNTORDER
GROUP BY ITXVIEWKNTORDER.PRODUCTIONORDERCODE,
ITXVIEWKNTORDER.LEGALNAME1,
ITXVIEWKNTORDER.INITIALSCHEDULEDACTUALDATE) ITXVIEWKNTORDER
	 ON ITXVIEWKNTORDER.PRODUCTIONORDERCODE =STOCKTRANSACTION.ORDERCODE AND 
	 ITXVIEWKNTORDER.INITIALSCHEDULEDACTUALDATE=STOCKTRANSACTION.TRANSACTIONDATE
	LEFT OUTER JOIN DB2ADMIN.FULLITEMKEYDECODER FULLITEMKEYDECODER ON
    STOCKTRANSACTION.FULLITEMIDENTIFIER = FULLITEMKEYDECODER.IDENTIFIER
    LEFT OUTER JOIN ( SELECT ITXVIEWKK.LONGDESCRIPTION,
	ITXVIEWKK.DSUBCODE01, 
	ITXVIEWKK.DSUBCODE02,
	ITXVIEWKK.DSUBCODE03,
	ITXVIEWKK.DSUBCODE04,
	ITXVIEWKK.DSUBCODE05,
	ITXVIEWKK.DSUBCODE06,
	ITXVIEWKK.DSUBCODE07,
	ITXVIEWKK.DSUBCODE08,
	ITXVIEWKK.PRODUCTIONORDERCODE,
	ITXVIEWKK.PROJECTCODE
FROM ITXVIEWKK 
GROUP BY 
ITXVIEWKK.LONGDESCRIPTION,
	ITXVIEWKK.DSUBCODE01, 
	ITXVIEWKK.DSUBCODE02,
	ITXVIEWKK.DSUBCODE03,
	ITXVIEWKK.DSUBCODE04,
	ITXVIEWKK.DSUBCODE05,
	ITXVIEWKK.DSUBCODE06,
	ITXVIEWKK.DSUBCODE07,
	ITXVIEWKK.DSUBCODE08,
	ITXVIEWKK.PRODUCTIONORDERCODE,
	ITXVIEWKK.PROJECTCODE) ITXVIEWKK ON ITXVIEWKK.PRODUCTIONORDERCODE =STOCKTRANSACTION.ORDERCODE AND 
    ITXVIEWKK.PROJECTCODE = STOCKTRANSACTION.PROJECTCODE
WHERE (STOCKTRANSACTION.ITEMTYPECODE ='KGF' OR STOCKTRANSACTION.ITEMTYPECODE ='FKG') and STOCKTRANSACTION.LOGICALWAREHOUSECODE ='M021' AND
STOCKTRANSACTION.ONHANDUPDATE > 1 AND NOT ORDERCODE IS NULL 
GROUP BY
STOCKTRANSACTION.ORDERCODE,
	STOCKTRANSACTION.LOGICALWAREHOUSECODE,
	STOCKTRANSACTION.DECOSUBCODE01,
	STOCKTRANSACTION.DECOSUBCODE02,
	STOCKTRANSACTION.DECOSUBCODE03,
	STOCKTRANSACTION.DECOSUBCODE04,
	STOCKTRANSACTION.DECOSUBCODE05,
	STOCKTRANSACTION.DECOSUBCODE06,
	STOCKTRANSACTION.DECOSUBCODE07,
	STOCKTRANSACTION.DECOSUBCODE08,
	STOCKTRANSACTION.TRANSACTIONDATE,
	STOCKTRANSACTION.LOTCODE,
	STOCKTRANSACTION.CREATIONUSER,
	STOCKTRANSACTION.PROJECTCODE,
	ITXVIEWKNTORDER.LEGALNAME1,
	ITXVIEWKNTORDER.PRODUCTIONDEMANDCODE,
	FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION,
	ITXVIEWKK.LONGDESCRIPTION,
	ITXVIEWKK.DSUBCODE01, 
	ITXVIEWKK.DSUBCODE02,
	ITXVIEWKK.DSUBCODE03,
	ITXVIEWKK.DSUBCODE04,
	ITXVIEWKK.DSUBCODE05,
	ITXVIEWKK.DSUBCODE06,
	ITXVIEWKK.DSUBCODE07,
	ITXVIEWKK.DSUBCODE08