WITH BASEDATA AS (
SELECT
    CASE TRIM(r.ITEMTYPEAFICODE) WHEN 'RFF' THEN r3.RECIPESUBCODE01 ELSE r.RECIPESUBCODE01 END AS RECIPESUBCODE01,
    r.SEQUENCE,
    r.GROUPNUMBER,
    r.GROUPTYPECODE,
    CASE 
        WHEN RIGHT(TRIM(r.RECIPESUBCODE01), 1) = 'D' AND NOT a3.VALUESTRING = 'W' THEN '1'
        WHEN RIGHT(TRIM(r.RECIPESUBCODE01), 1) = 'R' AND NOT a3.VALUESTRING = 'W' THEN '2'
        ELSE 
			COALESCE(a2.VALUESTRING, '3')
    END AS SUFFIXTYPE,  
    CASE TRIM(r.ITEMTYPEAFICODE) WHEN 'RFF' THEN r3.RECIPESUFFIXCODE ELSE r.RECIPESUFFIXCODE END AS RECIPESUFFIXCODE,
    CASE TRIM(r.ITEMTYPEAFICODE) WHEN 'RFF' THEN r3.SUBCODE01 ELSE r.SUBCODE01 END AS SUBCODE01,
    CASE TRIM(r.ITEMTYPEAFICODE) WHEN 'RFF' THEN r3.SUBCODE02 ELSE r.SUBCODE02 END AS SUBCODE02,
    CASE TRIM(r.ITEMTYPEAFICODE) WHEN 'RFF' THEN r3.SUBCODE03 ELSE r.SUBCODE03 END AS SUBCODE03,
    CASE 
	    TRIM(r.ITEMTYPEAFICODE) WHEN 'RFF' THEN CASE WHEN r3.CONSUMPTION = 0 THEN NULL ELSE r3.CONSUMPTION END
	    ELSE CASE WHEN r.CONSUMPTION = 0 THEN NULL ELSE r.CONSUMPTION END 
    END AS CONSUMPTION,
    CASE 
	    TRIM(r.ITEMTYPEAFICODE) WHEN 'RFF' THEN
	    	CASE
		        WHEN r3.GROUPTYPECODE = '100' THEN TRIM(r3.COMMENTLINE)
		        ELSE COALESCE(TRIM(r3.SUBCODE01),'') || '-' || COALESCE(TRIM(r3.SUBCODE02),'') || '-' || COALESCE(TRIM(r3.SUBCODE03),'')
		    END
	    ELSE 
	    	CASE
		        WHEN r.GROUPTYPECODE = '100' THEN TRIM(r.COMMENTLINE)
		        ELSE COALESCE(TRIM(r.SUBCODE01),'') || '-' || COALESCE(TRIM(r.SUBCODE02),'') || '-' || COALESCE(TRIM(r.SUBCODE03),'')
		    END
    END AS KODE,
    CASE 
        WHEN RIGHT(TRIM(r.RECIPESUBCODE01), 1) = 'D' AND NOT a3.VALUESTRING = 'W' THEN 1
        WHEN RIGHT(TRIM(r.RECIPESUBCODE01), 1) = 'R' AND NOT a3.VALUESTRING = 'W' THEN 3
        ELSE 
        	COALESCE(a2.VALUESTRING, '3')
    END AS RECIPE_NUMBER
FROM 
    RECIPECOMPONENT r
LEFT JOIN RECIPE r2 ON r2.SUBCODE01 = r.RECIPESUBCODE01 AND r2.SUFFIXCODE = r.RECIPESUFFIXCODE
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = r2.ABSUNIQUEID AND a.FIELDNAME = 'RCode'
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = r2.ABSUNIQUEID AND a2.FIELDNAME = 'UrutanRecipe'
LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = r2.ABSUNIQUEID AND a3.FIELDNAME = 'Chroma'
LEFT JOIN RECIPECOMPONENT r3 ON r3.RECIPESUBCODE01 = r.SUBCODE01 AND r3.RECIPESUFFIXCODE = r.SUFFIXCODE
WHERE 
    r.RECIPESUBCODE01 IN ('7091/150273M/R', '7091/150273M/R')
    AND r.RECIPESUFFIXCODE IN ('25013127L', 
                            '25013127D-S1','25013127D-S2','25013127D-S3',
                            '25013127D-S4','25013127D-S5','25013127D-S6','25013127D-S7')
    AND (
        (SUBSTR(a.VALUESTRING, 1,2) = 'OB' AND r.GROUPTYPECODE IN ('001', '100', '201'))
        OR (r.ITEMTYPEAFICODE = 'DYC' AND r.GROUPNUMBER < 20)
        )
),
CHECK_EXIST AS (
    SELECT 
        MAX(CASE WHEN RECIPE_NUMBER = 1 THEN 1 ELSE 0 END) AS HAS_1,
        MAX(CASE WHEN RECIPE_NUMBER = 3 THEN 1 ELSE 0 END) AS HAS_3
    FROM BASEDATA
),
BASE AS (
    SELECT * FROM BASEDATA
    UNION ALL
    SELECT 
        '-' AS RECIPESUBCODE01,
    2   AS SEQUENCE,
    NULL AS GROUPNUMBER,
    2   AS GROUPTYPECODE,
    2   AS SUFFIXTYPE, 
    '-' AS RECIPESUFFIXCODE,
    '-' AS SUBCODE01,
    '-' AS SUBCODE02,
    '-' AS SUBCODE03,
    NULL AS CONSUMPTION,
    '-' AS KODE,
    2   AS RECIPE_NUMBER
FROM ITXVIEW_KOSONG, CHECK_EXIST
WHERE HAS_1 = 1 AND HAS_3 = 1  -- hanya masuk kalau 1 & 3 ada
),
PIVOTED AS (
    SELECT
        RECIPESUBCODE01,
        RECIPE_NUMBER,
        KODE,
        SEQUENCE,
        GROUPNUMBER,
        GROUPTYPECODE,
        SUFFIXTYPE,
        MAX(CASE WHEN RECIPESUFFIXCODE = '25013127L' THEN CONSUMPTION END) AS LAB,
	    MAX(CASE WHEN RECIPESUFFIXCODE = '25013127D-S1' THEN CONSUMPTION END) AS ADJ1,
	    MAX(CASE WHEN RECIPESUFFIXCODE = '25013127D-S2' THEN CONSUMPTION END) AS ADJ2,
	    MAX(CASE WHEN RECIPESUFFIXCODE = '25013127D-S3' THEN CONSUMPTION END) AS ADJ3,
	    MAX(CASE WHEN RECIPESUFFIXCODE = '25013127D-S4' THEN CONSUMPTION END) AS ADJ4,
	    MAX(CASE WHEN RECIPESUFFIXCODE = '25013127D-S5' THEN CONSUMPTION END) AS ADJ5,
	    MAX(CASE WHEN RECIPESUFFIXCODE = '25013127D-S6' THEN CONSUMPTION END) AS ADJ6,
	    MAX(CASE WHEN RECIPESUFFIXCODE = '25013127D-S7' THEN CONSUMPTION END) AS ADJ7
    FROM 
        BASE
    GROUP BY 
        RECIPESUBCODE01, RECIPE_NUMBER, KODE, GROUPNUMBER, SEQUENCE, GROUPTYPECODE, SUFFIXTYPE
),
FINALDATA AS (
    SELECT 
        P.RECIPESUBCODE01,
        P.RECIPE_NUMBER,
        ROW_NUMBER() OVER (ORDER BY P.SUFFIXTYPE, P.RECIPE_NUMBER, P.GROUPNUMBER, P.SEQUENCE, P.KODE) AS FLAG,
        P.KODE || 
        CASE 
            WHEN LAB IS NULL AND P.GROUPTYPECODE = '001' THEN ' (NEW)'
        WHEN COALESCE(LAB,ADJ1,ADJ2,ADJ3,ADJ4,ADJ5,ADJ6,ADJ7) IS NULL AND P.GROUPTYPECODE = '001' THEN ' (REMOVED)'
        ELSE ''
    END AS KODE,
    P.SEQUENCE,
    P.GROUPNUMBER,
    P.SUFFIXTYPE,
    P.LAB,
    P.ADJ1,
    P.ADJ2,
    P.ADJ3,
    P.ADJ4,
    P.ADJ5,
    P.ADJ6,
    P.ADJ7,
    CASE 
        WHEN LAB IS NULL AND P.GROUPTYPECODE = '001' THEN 'NEW'
        WHEN COALESCE(LAB,ADJ1,ADJ2,ADJ3,ADJ4,ADJ5,ADJ6,ADJ7) IS NULL AND P.GROUPTYPECODE = '001' THEN 'REMOVED'
        ELSE ''
        END AS STATUSDYC
        FROM 
            PIVOTED P
)
SELECT 
    *
FROM 
    FINALDATA
--WHERE 
--    FLAG = {$flag}
ORDER BY 
    RECIPE_NUMBER,
    FLAG,
    SUFFIXTYPE, 
    SEQUENCE, 
    GROUPNUMBER,
    KODE