WITH FINALDATA AS (
	SELECT
		RECIPESUBCODE01,
		RECIPESUFFIXCODE,
		CASE
			WHEN RIGHT(TRIM(RECIPESUBCODE01), 1) = 'D' THEN 'T-SIDE'
			WHEN RIGHT(TRIM(RECIPESUBCODE01), 1) = 'R' THEN 'C-SIDE'
			ELSE '1'
		END AS SIDE,
		COMMENTLINE
	FROM
		RECIPECOMPONENT r
	WHERE
		RECIPESUBCODE01 IN (
			'19106/240788D/D', '19106/240788D/R'
		)
		AND RECIPESUFFIXCODE IN ('25013280L')
		AND GROUPTYPECODE = '100'
		AND (
			NOT COMMENTLINE LIKE '%RC %'
				AND NOT COMMENTLINE LIKE '%SOAPING%'
				AND NOT COMMENTLINE LIKE '%BLEACHING%'
		)
)
SELECT
	RECIPESUBCODE01,
	RECIPESUFFIXCODE,
	SIDE,
	COMMENTLINE
FROM
	FINALDATA
WHERE
	SIDE = 'T-SIDE'