SELECT
	p.CODE,
	p.DEFAULTASSIGNEDTOUSERID,
	a.VALUESTRING AS USER1,
	a2.VALUESTRING AS DIT1,
	a3.VALUESTRING AS USER2,
	a4.VALUESTRING AS DIT2,
	CASE 
		WHEN p.STATUS = 3 THEN 'Closed'
		WHEN p.STATUS = 2 THEN 'In Progress'
		WHEN p.STATUS = 1 THEN 'Open'
	END AS STATUS	
FROM
	PMBREAKDOWNENTRY p
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p.ABSUNIQUEID AND a.FIELDNAME = 'ApprovalDeptUserCode' AND TRIM(a.NAMEENTITYNAME) = 'PMBreakDownEntry'
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = p.ABSUNIQUEID AND a2.FIELDNAME = 'ApprovalDeptDITCode' AND TRIM(a.NAMEENTITYNAME) = 'PMBreakDownEntry'
LEFT JOIN PMWORKORDER p2 ON p2.PMBREAKDOWNENTRYCODE = p.CODE 
LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = p2.ABSUNIQUEID AND a3.FIELDNAME = 'ApprovalDeptUserCode' AND TRIM(a3.NAMEENTITYNAME) = 'PMWorkOrder'
LEFT JOIN ADSTORAGE a4 ON a4.UNIQUEID = p2.ABSUNIQUEID AND a4.FIELDNAME = 'ApprovalDeptDITCode' AND TRIM(a4.NAMEENTITYNAME) = 'PMWorkOrder'
WHERE
	p.BREAKDOWNTYPE = 'SF'
	AND p.IDENTIFIEDDATE BETWEEN '2025-08-01' AND '2025-08-31'
	AND NOT a.VALUESTRING IS NULL -- JANGAN TAMPILKAN DEPT USER BELUM APPROVE
	AND a2.VALUESTRING IS NULL -- DEPT DIT BELUM APPROVE
ORDER BY 
	p.DEFAULTASSIGNEDTOUSERID ASC