SELECT
	p.CODE,
	p.DEFAULTASSIGNEDTOUSERID,
	a2.VALUESTRING AS USE,
	a3.VALUESTRING AS DIT,
	CASE 
		WHEN p.STATUS = 3 THEN 'Closed'
		WHEN p.STATUS = 2 THEN 'In Progress'
		WHEN p.STATUS = 1 THEN 'Open'
	END AS STATUS	
FROM
	PMBREAKDOWNENTRY p
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p.ABSUNIQUEID AND a.FIELDNAME = 'ApprovalDeptUserCode'
LEFT JOIN PMWORKORDER p2 ON p2.PMBREAKDOWNENTRYCODE = p.CODE 
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = p2.ABSUNIQUEID AND a2.FIELDNAME = 'ApprovalDeptUserCode'
LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = p2.ABSUNIQUEID AND a3.FIELDNAME = 'ApprovalDeptDITCode'
WHERE
	p.BREAKDOWNTYPE = 'SF'
	AND p.IDENTIFIEDDATE BETWEEN '2024-08-01' AND '2024-08-31'
	AND NOT a.VALUESTRING IS NULL
ORDER BY 
	p.DEFAULTASSIGNEDTOUSERID ASC