SELECT
	*
FROM
	TICKET.dbo.TICKET_DETAIL
WHERE
	PRODUCT_CODE IN ('E-1-009')
	AND NOT ACTUAL_WT IS NULL
ORDER BY
	COMP_DATE DESC, COMP_TIME DESC
	
	
SELECT
	*
FROM
	TICKET.dbo.TICKET_DETAIL
WHERE
	PRODUCT_CODE IN ('E-1-002')
	AND NOT ACTUAL_WT IS NULL
ORDER BY
	COMP_DATE DESC, COMP_TIME DESC