-- DAFTAR RIWAYAT MESIN
SELECT
	d.LONGDESCRIPTION AS DEPT_CODE,
	p.CODE,
	TRIM(p.GENERICDATA2) || ', ' || TRIM(p.GENERICDATA3) || ', ' || TRIM(p.GENERICDATA4) AS NAMA_MESIN,
	TRIM(p.LONGDESCRIPTION) AS PENGGUNA,
	p.SHORTDESCRIPTION
	'-' AS IPADDRESS
FROM
	PMBOM p
LEFT JOIN DEPARTMENT d ON d.CODE = p.DEPARTMENTCODE 
WHERE
	(p.CREATIONUSER = 'deden.kurnia' OR p.CREATIONUSER = 'mamik.agung' OR p.CREATIONUSER = 'heriben.harna' OR p.CREATIONUSER = 'sultan.hidayat')

-- KARTU RIWAYAT MESIN DAN PRASARANA BERDASARKAN NO_MESIN
SELECT
	p.CODE,
	p.PMBOMCODE AS NO_MESIN,
	p2.LONGDESCRIPTION AS MESIN,
	p2.GENERICDATA2 AS TYPE,
	d.SHORTDESCRIPTION AS DOCUMENT,
	p.IDENTIFIEDDATE AS TANGGAL,
	p3.REMARKS AS KEGIATAN,
	p4.PRODUCTSHORTDESC || ' ( ' || floor(p4.ACTUALQUANITY) || ' ' || u.LONGDESCRIPTION  || ')' AS SPAREPARTS,
	p3.CODE
FROM
	PMBREAKDOWNENTRY p
LEFT JOIN PMBOM p2 ON p2.CODE = p.PMBOMCODE 
LEFT JOIN DEPARTMENT d ON d.CODE = p2.DEPARTMENTCODE 
LEFT JOIN PMWORKORDER p3 ON p3.PMBREAKDOWNENTRYCODE = p.CODE 
LEFT JOIN PMWORKORDERACTIVITYSPARES p4 ON p4.PMWORKORDDLTPMWORKORDERCODE = p3.CODE 
LEFT JOIN UNITOFMEASURE u ON u.CODE = p4.QUANTITYUOMCODE 
WHERE
	p.PMBOMCODE = 'MKTPK000636'
	
-- HEADER FORM PEMAKAIAN SPARE PART DIT BERDASARKAN NO WORK ORDER
SELECT DISTINCT 
	SUBSTR(p3.CODE, 4, 8) || '/' || SUBSTR(d.LONGDESCRIPTION, 1, 3) AS NO_FORM,
	p3.CODE AS NO_FORMS_WORKORDER,
	p.CODE AS NO_OPENTICKET,
	p.PMBOMCODE AS NO_BARCODE,
	p.SYMPTOM,
	p2.LONGDESCRIPTION AS PENGGUNA,
	d.SHORTDESCRIPTION AS DOCUMENT
FROM
	PMBREAKDOWNENTRY p
LEFT JOIN PMBOM p2 ON p2.CODE = p.PMBOMCODE 
LEFT JOIN DEPARTMENT d ON d.CODE = p2.DEPARTMENTCODE 
LEFT JOIN PMWORKORDER p3 ON p3.PMBREAKDOWNENTRYCODE = p.CODE 
LEFT JOIN PMWORKORDERACTIVITYSPARES p4 ON p4.PMWORKORDDLTPMWORKORDERCODE = p3.CODE 
LEFT JOIN UNITOFMEASURE u ON u.CODE = p4.QUANTITYUOMCODE 
WHERE
	NOT p4.IDINTDOCUMENTPROVISIONALCODE IS NULL
	AND p3.CODE = 'BWO23005685'
	
-- DETAIL SPARE PART FORM PEMAKAIAN SPARE PART DIT BERDASARKAN NO WORK ORDER
SELECT  
	TRIM(p.SUBCODE01) || '-' || TRIM(p.SUBCODE02) || '-' || TRIM(p.SUBCODE03) || '-' || TRIM(p.SUBCODE04) AS KODE_BARANG,
	p.PRODUCTSHORTDESC AS NAMA_SPAREPART,
	p.ACTUALQUANITY AS JUMLAH
FROM 
	PMWORKORDERACTIVITYSPARES p 
WHERE 
	PMWORKORDDLTPMWORKORDERCODE = 'BWO23005685'  