SELECT
	i.GROUPNUMBER,
    v.PICKUPQUANTITY,
    i.PRODUCTIONORDERCODE,
    i.CODE,
    i.SUBCODE,
    i.COMMENTLINE,
    i.LONGDESCRIPTION,
    i.CONSUMPTION,
    i.SUFFIXCODE,
    i.RECIPENUMBERID,
    i.SUBCODE01,
    i.SUBCODE02,
    i.SUBCODE03,
    i.GROUPNUMBER
FROM 
    VIEWPRODUCTIONRESERVATION v 
LEFT JOIN ITXVIEWRESEP i ON i.PRODUCTIONORDERCODE = v.PRODUCTIONORDERCODE 
                        AND i.SUBCODE01_RESERVATION = v.SUBCODE01 
                        AND i.SUFFIXCODE_RESERVATION = v.SUFFIXCODE

WHERE 
    TRIM(i.PRODUCTIONORDERCODE) || '-' || TRIM(i.GROUPLINE) = '00035839-1304' AND NOT i.SUBCODE IS NULL AND NOT i.SUBCODE = ''
ORDER BY 
    i.GROUPLINE ASC
    
    
SELECT RECIPE.RECIPETYPE,
        RECIPE.PICKUPPERCENTAGE,
        RECIPE.RESIDUALBATHVOLUME,
        ITXVIEWRESEP1.RECIPENUMBERID,
        ITXVIEWRESEP1.GROUPNUMBER,
        ITXVIEWRESEP1.CONSUMPTION,
        ITXVIEWRESEP1.CONSUMPTIONTYPE,
        ITXVIEWRESEP1.SUBCODE01,
        ITXVIEWRESEP1.SUBCODE02,
        ITXVIEWRESEP1.SUBCODE03 
FROM 
    RECIPE RECIPE 
LEFT JOIN ITXVIEWRESEP1 ITXVIEWRESEP1 ON RECIPE.NUMBERID = ITXVIEWRESEP1.RECIPENUMBERID
WHERE 
    ITXVIEWRESEP1.RECIPENUMBERID = '$itxviewresep[RECIPENUMBERID]'
    AND ITXVIEWRESEP1.SUBCODE01 = '$itxviewresep[SUBCODE01]' 
    AND ITXVIEWRESEP1.SUBCODE02 = '$itxviewresep[SUBCODE02]' 
    AND ITXVIEWRESEP1.SUBCODE03 = '$itxviewresep[SUBCODE03]' 
    AND ITXVIEWRESEP1.GROUPNUMBER = '$itxviewresep[GROUPNUMBER]'