SELECT 
    i.PROVISIONALCODE,
    'INT/' || LTRIM(SUBSTR(i.PROVISIONALCODE, 8,6), '0') || ',' || SUBSTR(i.PROVISIONALDOCUMENTDATE, 6,2) || '/' || SUBSTR(i.PROVISIONALDOCUMENTDATE, 3,2) AS NO_FORM,
    TRIM(i2.SUBCODE01) || '-' || TRIM(i2.SUBCODE02) || '-' || TRIM(i2.SUBCODE03) || '-' || TRIM(i2.SUBCODE04) || '-' || TRIM(i2.SUBCODE05) || '-' || TRIM(i2.SUBCODE06) AS KODE_BARANG,
    i2.ITEMDESCRIPTION  AS NAMA_SPAREPART,
    floor(i2.USERPRIMARYQUANTITY) AS JUMLAH,
    i.EXTERNALREFERENCE AS CATATAN,
    CASE
    	WHEN a.VALUESTRING = '1' THEN 'Pinjam'
    	WHEN a.VALUESTRING = '2' THEN 'Pakai'
    	ELSE ''
    END AS STATUS    
FROM 
    INTERNALDOCUMENT i 
LEFT JOIN INTERNALDOCUMENTLINE i2 ON i2.INTDOCUMENTPROVISIONALCODE = i.PROVISIONALCODE AND i2.WAREHOUSECODE = 'M231'
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = i.ABSUNIQUEID AND a.FIELDNAME = 'Status'
WHERE
    i.PROVISIONALCODE = 'I1M2025000207'
	AND i.ORDPRNCUSTOMERSUPPLIERCODE = 'M231'