SELECT
	*
FROM
	ABSUIXMLREPORT a
LEFT JOIN ABSREPORTDEF a2 ON a2.CODE = a.REPORTCODE 
WHERE
	a.ABSUIXMLNAME = 'ITXVIEWSALESDOCUMENTSESSION.xml'
	AND a.CONTEXT = '2' -- OBJECT 2, COLLECTION 1
ORDER BY 
	SEQUENCE ASC