SELECT
	p.STEPNUMBER,
	p.OPERATIONCODE,
	p.LONGDESCRIPTION,
	CASE
		WHEN p.PROGRESSSTATUS = 0 THEN 'Entered'
		WHEN p.PROGRESSSTATUS = 1 THEN 'Planned'
		WHEN p.PROGRESSSTATUS = 2 THEN 'Progress'
		WHEN p.PROGRESSSTATUS = 3 THEN 'Closed'
	END AS STATUS_OPERATION,
	TRIM(p2.PROGRESSSTARTPROCESSDATE) || ' ' || TRIM(p2.PROGRESSSTARTPROCESSTIME) AS TANGGAL_JAM  
FROM 
	PRODUCTIONDEMANDSTEP p 
LEFT JOIN PRODUCTIONPROGRESS p2 ON p2.DEMANDCODE = p.PRODUCTIONDEMANDCODE AND p2.OPERATIONCODE = p.OPERATIONCODE AND p2.PROGRESSTEMPLATECODE = 'E01'
WHERE
	p.PRODUCTIONDEMANDCODE LIKE '%00083054%'
ORDER BY p.STEPNUMBER ASC