SELECT * FROM ITTWEEKLYEXCHANGERATE ORDER BY INITIALDATE DESC LIMIT 1

SELECT * FROM ITTWEEKLYEXCHANGERATE WHERE INITIALDATE BETWEEN '2022-10-11' AND NOW() ORDER BY INITIALDATE ASC LIMIT 1

SELECT 
    SUM(PRICE) AS SUM_PRICE
  FROM (SELECT
      SUM(CASE
        WHEN i.CURRENCYCODE = 'IDR' THEN (i.PRICE) / 15357
        ELSE (i.PRICE)
      END) AS PRICE
  FROM
      RECIPECOMPONENT r
  INNER JOIN INTERNALPRICELISTLINE i ON i.SUBCODE01 = r.SUBCODE01 AND i.SUBCODE02 = r.SUBCODE02 AND i.SUBCODE03 = r.SUBCODE03
  WHERE 
    r.RECIPEITEMTYPECODE = 'RFD' AND r.RECIPESUFFIXCODE = '001' AND r.RECIPESUBCODE01 LIKE '%%' AND r.ITEMTYPEAFICODE = 'DYC'
  GROUP BY
      i.CURRENCYCODE)
      
SELECT 
  RECIPE_CODE,
  SUFFIX,
  SUM(PRICE) AS SUM_PRICE
FROM (SELECT
    r.RECIPESUBCODE01 AS RECIPE_CODE,
    r.RECIPESUFFIXCODE AS SUFFIX,
    SUM(CASE
      WHEN i.CURRENCYCODE = 'IDR' THEN (i.PRICE) / 15357
      ELSE (i.PRICE)
    END) AS PRICE
FROM
    RECIPECOMPONENT r
INNER JOIN INTERNALPRICELISTLINE i ON i.SUBCODE01 = r.SUBCODE01 AND i.SUBCODE02 = r.SUBCODE02 AND i.SUBCODE03 = r.SUBCODE03
WHERE 
  r.RECIPEITEMTYPECODE = 'RFD' AND r.RECIPESUFFIXCODE = '001' AND r.RECIPESUBCODE01 LIKE '%%' AND r.ITEMTYPEAFICODE = 'DYC'
GROUP BY
    r.RECIPESUBCODE01,
    r.RECIPESUFFIXCODE, i.CURRENCYCODE)
GROUP BY 
  RECIPE_CODE,
  SUFFIX
    
--DETAIL
SELECT
	  r.RECIPESUBCODE01,
      TRIM(r.SUBCODE01) || '-' || TRIM(r.SUBCODE02) || '-' || TRIM(r.SUBCODE03) AS CODE_DYESTUFF,
      TRIM(p.LONGDESCRIPTION) AS PRODUCT_NAME,
      i.ITEMTYPEAFICODE AS DYESTUFF,
      i.CURRENCYCODE AS CURRENCY,
      (i.PRICE) AS PRICE,
      CASE
        WHEN i.CURRENCYCODE = 'IDR' THEN round((i.PRICE) / 15357, 2)
        ELSE round(i.PRICE, 2)
      END AS PRICE_USD
  FROM
      RECIPECOMPONENT r
  LEFT JOIN INTERNALPRICELISTLINE i ON i.SUBCODE01 = r.SUBCODE01 AND i.SUBCODE02 = r.SUBCODE02 AND i.SUBCODE03 = r.SUBCODE03
  LEFT JOIN PRODUCT p ON p.ITEMTYPECODE = r.ITEMTYPEAFICODE
				    AND p.SUBCODE01 = r.SUBCODE01
				    AND p.SUBCODE02 = r.SUBCODE02
				    AND p.SUBCODE03 = r.SUBCODE03
  WHERE 
    r.RECIPEITEMTYPECODE = 'RFD' AND r.RECIPESUFFIXCODE = '001' AND r.RECIPESUBCODE01 LIKE '%10038/142216D%'  AND r.ITEMTYPEAFICODE = 'DYC'
ORDER BY r.RECIPESUBCODE01