SELECT r.RECIPESUBCODE01,
      TRIM(r.SUBCODE01) || '-' || TRIM(r.SUBCODE02) || '-' || TRIM(r.SUBCODE03) AS CODE_DYESTUFF,
      TRIM(p.LONGDESCRIPTION) AS PRODUCT_NAME,
      i.ITEMTYPEAFICODE AS DYESTUFF,
      i.CURRENCYCODE AS CURRENCY,
      (i.PRICE) AS PRICE,
      r.CONSUMPTION AS CONSUMTION,
      (i.PRICE/100)*r.CONSUMPTION AS HARGA_PEMAKAIAN,
      CASE
        WHEN i.CURRENCYCODE = 'IDR' THEN (i.PRICE/100)*r.CONSUMPTION / 15584
        ELSE (i.PRICE/100)*r.CONSUMPTION
      END AS PRICE_USD
  FROM
      RECIPECOMPONENT r
  LEFT JOIN INTERNALPRICELISTLINE i ON i.SUBCODE01 = r.SUBCODE01 AND i.SUBCODE02 = r.SUBCODE02 AND i.SUBCODE03 = r.SUBCODE03
  LEFT JOIN PRODUCT p ON p.ITEMTYPECODE = r.ITEMTYPEAFICODE
            AND p.SUBCODE01 = r.SUBCODE01
            AND p.SUBCODE02 = r.SUBCODE02
            AND p.SUBCODE03 = r.SUBCODE03
  WHERE 
  r.RECIPEITEMTYPECODE = 'RFD' AND r.RECIPESUFFIXCODE = '001' AND r.RECIPESUBCODE01 = '18157/220331L/R' AND r.ITEMTYPEAFICODE = 'DYC' AND i.VALIDTODATE IS NULL
  ORDER BY r."SEQUENCE" 