SELECT * FROM ITXVIEW_INVOICE_NOINVOICE iin WHERE INVOICE = 'EX23070046'

SELECT * FROM ITXVIEW_INVOICE_NOINVOICE iin WHERE INVOICE = 'EX23110006'

SELECT * FROM ITXVIEW_ALLOCATION_2B WHERE SALESDOCUMENTPROVISIONALCODE = 'ESP2300764'  

SELECT * FROM ITXVIEW_INVOICE_GRANDTOTAL WHERE SALESDOCUMENTPROVISIONALCODE = 'ESP2300519'

SELECT * FROM ITXVIEW_ALLOCATION_CI iac WHERE SALESDOCUMENTPROVISIONALCODE = 'ESP2300764'

