SELECT
	s.TRANSACTIONDATE AS TGL_SJ,
	s.ORDERCODE AS NO_SJ,
	e.ENTRYDOCUMENTNUMBER AS NO_DEMAND,
	p3.LONGDESCRIPTION AS JENISKAIN
	,*
FROM
	PLANTINVOICE p
LEFT JOIN PLANTINVOICETRANSACTION p2 ON p2.PLANTINVOICECODE = p.CODE 
LEFT JOIN STOCKTRANSACTION s ON s.TRANSACTIONNUMBER = p2.STOCKTRNTRANSACTIONNUMBER
LEFT JOIN ELEMENTS e ON e.CODE = s.ITEMELEMENTCODE 
LEFT JOIN PRODUCT p3 ON p3.ITEMTYPECODE = s.ITEMTYPECODE 
					AND p3.SUBCODE01 = s.DECOSUBCODE01
					AND p3.SUBCODE02 = s.DECOSUBCODE02
					AND p3.SUBCODE03 = s.DECOSUBCODE03
					AND p3.SUBCODE04 = s.DECOSUBCODE04
					AND p3.SUBCODE05 = s.DECOSUBCODE05
					AND p3.SUBCODE06 = s.DECOSUBCODE06
					AND p3.SUBCODE07 = s.DECOSUBCODE07
					AND p3.SUBCODE08 = s.DECOSUBCODE08
					AND p3.SUBCODE09 = s.DECOSUBCODE09
					AND p3.SUBCODE10 = s.DECOSUBCODE10
LEFT JOIN PRODUCTIONDEMAND p4 ON p4.CODE = e.ENTRYDOCUMENTNUMBER
LEFT JOIN SALESORDERLINE s2 ON s2.SALESORDERCODE = p4.ORIGDLVSALORDLINESALORDERCODE 
							AND s2.ORDERLINE = p4.ORIGDLVSALORDERLINEORDERLINE 
WHERE 
	p.CODE = 'DMU24060813'