-- DB2ADMIN.ITXVIEW_SURATJALAN_EXIM2 source

--CREATE VIEW ITXVIEW_SURATJALAN_EXIM2 AS
SELECT
    DISTINCT
    PROVISIONALCODE,
    ALLOCATIONCODE ,
    ITEMELEMENTCODE,
    TRANSPORTSTARTDATE,
    JENIS_ORDER,
    TGL_BERANGKAT,
    TANGGAL_BERANGKAT,
    ISSUE_DATE,
    KET_SHIPPING,
    TERMSOFSHIPPINGCODE,
    TERMSOFSHIPPINGDESCRIPTION,
    PAYMENTMETHODCODE,
    PRICE,
    UNIT,
    ITEMTYPEAFICODE,
    terms_shipping,
    terms_shipping_description,
    PROJECTCODE,
    SUBCODE01,
    SUBCODE05,
    EXTERNALREFERENCE,
    EXTERNALITEM,
    DLVSALORDERLINESALESORDERCODE,
    BRAND_NM,
    CUSTOMERSUPPLIERCODE,
    ADDRESSEE,
    COLOR_DESC,
    COUNTRY_NM,
    QUALITYREASONCODE,
    USERPRIMARYUOMCODE,
    QTY_KG,
     CASE
        WHEN USERSECONDARYUOMCODE = 'm' THEN BASESECONDARYQUANTITY
        WHEN USERSECONDARYUOMCODE = 'yd' THEN USERSECONDARYQUANTITY
        ELSE 0
    END QTY_YARDMETER,
    USERSECONDARYUOMCODE,
    CASE
        WHEN USERSECONDARYUOMCODE IN ('un') THEN qty_pcs
        ELSE 0
    END QTY_PCS,
    BASEPRIMARYUOMCODE,
    COUNTROLL,
    COUNTBALL,
    FOC_KG,
    CASE
        WHEN USERSECONDARYUOMCODE = 'm' THEN FOC_METER
        WHEN USERSECONDARYUOMCODE = 'yd' THEN FOC_YD
        ELSE 0
    END FOC_YARDMETER,
    JML_ROLL_FOC,
    COUNTERCODE
FROM
    (
        SELECT
            DISTINCT
    ITXVIEW_SUB_SURATJALAN_EXIM.PROVISIONALCODE,
            ALLOCATION.CODE AS ALLOCATIONCODE,
            ALLOCATION.ITEMELEMENTCODE,
            ITXVIEW_SUB_SURATJALAN_EXIM.TRANSPORTSTARTDATE,
            ITXVIEW_SUB_SURATJALAN_EXIM.JENIS_ORDER,
            ITXVIEW_SUB_SURATJALAN_EXIM.TGL_BERANGKAT,
            ITXVIEW_SUB_SURATJALAN_EXIM.TANGGAL_BERANGKAT,
            ITXVIEW_SUB_SURATJALAN_EXIM.ISSUE_DATE,
            ITXVIEW_SUB_SURATJALAN_EXIM.KET_SHIPPING,
            ITXVIEW_SUB_SURATJALAN_EXIM.TERMSOFSHIPPINGCODE,
            ITXVIEW_SUB_SURATJALAN_EXIM.TERMSOFSHIPPINGDESCRIPTION,
            ITXVIEW_SUB_SURATJALAN_EXIM.PAYMENTMETHODCODE,
            ITXVIEW_SUB_SURATJALAN_EXIM.PRICE,
            ITXVIEW_SUB_SURATJALAN_EXIM.UNIT,
            ITXVIEW_SUB_SURATJALAN_EXIM.ITEMTYPEAFICODE,
            ITXVIEW_SUB_SURATJALAN_EXIM.terms_shipping,
            ITXVIEW_SUB_SURATJALAN_EXIM.terms_shipping_description,
            ITXVIEW_SUB_SURATJALAN_EXIM.PROJECTCODE,
            ITXVIEW_SUB_SURATJALAN_EXIM.SUBCODE01,
            ITXVIEW_SUB_SURATJALAN_EXIM.SUBCODE05,
            ITXVIEW_SUB_SURATJALAN_EXIM.EXTERNALREFERENCE,
            ITXVIEW_SUB_SURATJALAN_EXIM.EXTERNALITEM,
            ITXVIEW_SUB_SURATJALAN_EXIM.DLVSALORDERLINESALESORDERCODE,
            ITXVIEW_SUB_SURATJALAN_EXIM.BRAND_NM,
            ITXVIEW_SUB_SURATJALAN_EXIM.CUSTOMERSUPPLIERCODE,
            ITXVIEW_SUB_SURATJALAN_EXIM.ADDRESSEE,
            ITXVIEW_SUB_SURATJALAN_EXIM.COLOR_DESC,
            ITXVIEW_SUB_SURATJALAN_EXIM.COUNTRY_NM,
            E.QUALITYREASONCODE AS QUALITYREASONCODE,
            CASE
                WHEN E.QUALITYREASONCODE = 'FOC'
                AND ITXVIEW_SUB_SURATJALAN_EXIM.COUNTERCODE = 'DREPROV ' THEN ALLOCATION.USERPRIMARYQUANTITY
                WHEN E.QUALITYREASONCODE = 'FOC'
                AND ITXVIEW_SUB_SURATJALAN_EXIM.COUNTERCODE IN(
                    'EXDPROV', 'EXPPROV', 'PFEPROV'
                ) THEN 0
                ELSE ALLOCATION.USERPRIMARYQUANTITY
            END AS QTY_KG,
            CASE
                WHEN E.QUALITYREASONCODE = 'FOC'
                AND ITXVIEW_SUB_SURATJALAN_EXIM.COUNTERCODE = 'DREPROV ' THEN ALLOCATION.USERSECONDARYQUANTITY
                WHEN E.QUALITYREASONCODE = 'FOC'
                AND ITXVIEW_SUB_SURATJALAN_EXIM.COUNTERCODE IN(
                    'EXDPROV', 'EXPPROV', 'PFEPROV'
                ) THEN 0
                ELSE ALLOCATION.USERSECONDARYQUANTITY
            END AS USERSECONDARYQUANTITY,
            CASE
                WHEN E.QUALITYREASONCODE = 'FOC'
                AND ITXVIEW_SUB_SURATJALAN_EXIM.COUNTERCODE IN(
                    'DREDEF', 'DREPROV', 'DRDDEF', 'DRPPROV'
                ) THEN ROUND(ALLOCATION.BASESECONDARYQUANTITY * 0.9144, 2)
                WHEN E.QUALITYREASONCODE = 'FOC'
                AND ITXVIEW_SUB_SURATJALAN_EXIM.COUNTERCODE IN(
                    'EXDPROV', 'EXPPROV', 'PFEPROV'
                ) THEN 0
                ELSE ROUND(ALLOCATION.BASESECONDARYQUANTITY * 0.9144, 2)
            END BASESECONDARYQUANTITY,
            ALLOCATION.USERPRIMARYUOMCODE AS USERPRIMARYUOMCODE,
            ALLOCATION.USERSECONDARYUOMCODE AS USERSECONDARYUOMCODE,
            CASE
                WHEN E.QUALITYREASONCODE = 'FOC'
                AND ITXVIEW_SUB_SURATJALAN_EXIM.COUNTERCODE IN(
                    'DREDEF', 'DREPROV', 'DRDDEF', 'DRPPROV'
                ) THEN ALLOCATION.USERSECONDARYUSEDQUANTITY
                WHEN E.QUALITYREASONCODE = 'FOC'
                AND ITXVIEW_SUB_SURATJALAN_EXIM.COUNTERCODE IN(
                    'EXDPROV', 'EXPPROV', 'PFEPROV'
                ) THEN 0
                WHEN ALLOCATION.ITEMTYPECODE <> 'CAP' THEN round(ALLOCATION.USERSECONDARYUSEDQUANTITY , 2)
                WHEN ALLOCATION.ITEMTYPECODE = 'CAP'
                AND ALLOCATION.BASEPRIMARYUOMCODE IN (
                    'Lot', 'un'
                ) THEN ALLOCATION.BASEPRIMARYQUANTITY
                ELSE ALLOCATION.BASESECONDARYQUANTITY
            END qty_pcs,
            ALLOCATION.BASEPRIMARYUOMCODE,
            CASE
                WHEN ITXVIEW_SUB_SURATJALAN_EXIM.ITEMTYPEAFICODE = 'KFF' THEN COUNT(ALLOCATION.ITEMELEMENTCODE)
                ELSE 0
            END AS COUNTROLL,
            CASE
                WHEN ITXVIEW_SUB_SURATJALAN_EXIM.ITEMTYPEAFICODE = 'FKF' THEN COUNT(ALLOCATION.ITEMELEMENTCODE)
                ELSE 0
            END AS COUNTBALL,
            CASE
                WHEN E.QUALITYREASONCODE = 'FOC'
                AND ITXVIEW_SUB_SURATJALAN_EXIM.COUNTERCODE IN(
                    'EXDPROV', 'EXPPROV', 'PFEPROV'
                ) THEN ALLOCATION.USERPRIMARYQUANTITY
                ELSE 0
            END AS FOC_KG,
            CASE
                WHEN E.QUALITYREASONCODE = 'FOC'
                AND ITXVIEW_SUB_SURATJALAN_EXIM.COUNTERCODE IN(
                    'EXDPROV', 'EXPPROV', 'PFEPROV'
                ) THEN ALLOCATION.USERSECONDARYQUANTITY
                ELSE 0
            END AS FOC_YD,
            CASE
                WHEN E.QUALITYREASONCODE = 'FOC'
                AND ITXVIEW_SUB_SURATJALAN_EXIM.COUNTERCODE IN(
                    'EXDPROV', 'EXPPROV', 'PFEPROV'
                ) THEN ROUND(ALLOCATION.BASESECONDARYQUANTITY * 0.9144, 2)
                ELSE 0
            END AS FOC_METER,
            CASE
                WHEN E.QUALITYREASONCODE = 'FOC'
                AND ITXVIEW_SUB_SURATJALAN_EXIM.COUNTERCODE IN(
                    'EXDPROV', 'EXPPROV', 'PFEPROV'
                ) THEN COUNT(E.QUALITYREASONCODE)
                ELSE 0
            END AS JML_ROLL_FOC,
            ITXVIEW_SUB_SURATJALAN_EXIM.COUNTERCODE
        FROM
            ITXVIEW_SUB_SURATJALAN_EXIM ITXVIEW_SUB_SURATJALAN_EXIM
        LEFT JOIN (
                SELECT
                    *
                FROM
                    ALLOCATION ALLOCATION
                WHERE
                    ALLOCATION.DETAILTYPE = '0'
            )ALLOCATION ON
            ITXVIEW_SUB_SURATJALAN_EXIM.CODE = ALLOCATION.CODE
        LEFT JOIN ELEMENTS E ON
            ALLOCATION.ITEMELEMENTCODE = E.CODE
        WHERE
            ALLOCATION.ORIGINTRNTRANSACTIONNUMBER IS NULL
                        	AND ITXVIEW_SUB_SURATJALAN_EXIM.PROVISIONALCODE IN('ESP2300743')
            --    	AND ITXVIEW_SUB_SURATJALAN_EXIM.PROVISIONALCODE LIKE '%ESP22003%'
        GROUP BY
            ITXVIEW_SUB_SURATJALAN_EXIM.PROVISIONALCODE,
            ALLOCATION.CODE,
            ALLOCATION.ITEMELEMENTCODE,
            ITXVIEW_SUB_SURATJALAN_EXIM.TRANSPORTSTARTDATE,
            ITXVIEW_SUB_SURATJALAN_EXIM.JENIS_ORDER,
            ITXVIEW_SUB_SURATJALAN_EXIM.TGL_BERANGKAT,
            ITXVIEW_SUB_SURATJALAN_EXIM.TANGGAL_BERANGKAT,
            ITXVIEW_SUB_SURATJALAN_EXIM.ISSUE_DATE,
            ITXVIEW_SUB_SURATJALAN_EXIM.KET_SHIPPING,
            ITXVIEW_SUB_SURATJALAN_EXIM.TERMSOFSHIPPINGCODE,
            ITXVIEW_SUB_SURATJALAN_EXIM.TERMSOFSHIPPINGDESCRIPTION,
            ITXVIEW_SUB_SURATJALAN_EXIM.PAYMENTMETHODCODE,
            ITXVIEW_SUB_SURATJALAN_EXIM.PRICE,
            ITXVIEW_SUB_SURATJALAN_EXIM.UNIT,
            ITXVIEW_SUB_SURATJALAN_EXIM.ITEMTYPEAFICODE,
            ITXVIEW_SUB_SURATJALAN_EXIM.terms_shipping,
            ITXVIEW_SUB_SURATJALAN_EXIM.terms_shipping_description,
            ITXVIEW_SUB_SURATJALAN_EXIM.PROJECTCODE,
            ITXVIEW_SUB_SURATJALAN_EXIM.SUBCODE01,
            ITXVIEW_SUB_SURATJALAN_EXIM.SUBCODE05,
            ITXVIEW_SUB_SURATJALAN_EXIM.EXTERNALREFERENCE,
            ITXVIEW_SUB_SURATJALAN_EXIM.EXTERNALITEM,
            ITXVIEW_SUB_SURATJALAN_EXIM.DLVSALORDERLINESALESORDERCODE,
            ITXVIEW_SUB_SURATJALAN_EXIM.BRAND_NM,
            ITXVIEW_SUB_SURATJALAN_EXIM.CUSTOMERSUPPLIERCODE,
            ITXVIEW_SUB_SURATJALAN_EXIM.ADDRESSEE,
            ITXVIEW_SUB_SURATJALAN_EXIM.COLOR_DESC,
            ITXVIEW_SUB_SURATJALAN_EXIM.COUNTRY_NM,
            ITXVIEW_SUB_SURATJALAN_EXIM.COUNTERCODE,
            ALLOCATION.ITEMELEMENTCODE,
            E.QUALITYREASONCODE,
            ALLOCATION.ITEMTYPECODE,
            ALLOCATION.BASESECONDARYQUANTITY,
            ALLOCATION.USERPRIMARYQUANTITY,
            ALLOCATION.USERPRIMARYUOMCODE,
            ALLOCATION.USERSECONDARYQUANTITY,
            ALLOCATION.USERSECONDARYUOMCODE,
            ALLOCATION.BASEPRIMARYUOMCODE,
            ALLOCATION.BASEPRIMARYQUANTITY,
            ALLOCATION.USERSECONDARYUSEDQUANTITY
    );