DROP VIEW ITXVIEW_SUMSALESORDER;
--CREATE VIEW ITXVIEW_SUMSALESORDER AS
SELECT
    o.LONGDESCRIPTION AS BUYER,
    MONTH(s.ORDERDATE) AS BULAN,
    YEAR(s.ORDERDATE) AS TAHUN,
    SUM(s2.NETTO) AS SUM_NETTO
FROM
    SALESORDER s
LEFT JOIN ORDERPARTNERBRAND o ON o.ORDPRNCUSTOMERSUPPLIERCODE = s.ORDPRNCUSTOMERSUPPLIERCODE
LEFT JOIN (
    SELECT
        s2.SALESORDERCODE,
        COUNT(s2.SALESORDERCODE) AS COUNTLINE,
        SUM(s2.USERPRIMARYQUANTITY) AS NETTO
    FROM
        SALESORDERLINE s2
    GROUP BY
        s2.SALESORDERCODE)s2 ON s2.SALESORDERCODE = s.CODE
GROUP BY 
	o.LONGDESCRIPTION,
	MONTH(s.ORDERDATE),
	YEAR(s.ORDERDATE)
	

SELECT DISTINCT 
	o.LONGDESCRIPTION,
	is1.SUM_NETTO AS NETTO_1,
	is2.SUM_NETTO AS NETTO_2,
	is3.SUM_NETTO AS NETTO_3,
	is4.SUM_NETTO AS NETTO_4,
	is5.SUM_NETTO AS NETTO_5,
	is6.SUM_NETTO AS NETTO_6,
	is7.SUM_NETTO AS NETTO_7,
	is8.SUM_NETTO AS NETTO_8,
	is9.SUM_NETTO AS NETTO_9,
	is10.SUM_NETTO AS NETTO_10,
	is11.SUM_NETTO AS NETTO_11,
	is12.SUM_NETTO AS NETTO_12
FROM 
	ORDERPARTNERBRAND o 
LEFT JOIN ITXVIEW_SUMSALESORDER is1 ON is1.BUYER = o.LONGDESCRIPTION AND is1.BULAN = 1 AND is1.TAHUN = 2023
LEFT JOIN ITXVIEW_SUMSALESORDER is2 ON is2.BUYER = o.LONGDESCRIPTION AND is2.BULAN = 2 AND is2.TAHUN = 2023
LEFT JOIN ITXVIEW_SUMSALESORDER is3 ON is3.BUYER = o.LONGDESCRIPTION AND is3.BULAN = 3 AND is3.TAHUN = 2023
LEFT JOIN ITXVIEW_SUMSALESORDER is4 ON is4.BUYER = o.LONGDESCRIPTION AND is4.BULAN = 4 AND is4.TAHUN = 2023
LEFT JOIN ITXVIEW_SUMSALESORDER is5 ON is5.BUYER = o.LONGDESCRIPTION AND is5.BULAN = 5 AND is5.TAHUN = 2023
LEFT JOIN ITXVIEW_SUMSALESORDER is6 ON is6.BUYER = o.LONGDESCRIPTION AND is6.BULAN = 6 AND is6.TAHUN = 2023
LEFT JOIN ITXVIEW_SUMSALESORDER is7 ON is7.BUYER = o.LONGDESCRIPTION AND is7.BULAN = 7 AND is7.TAHUN = 2023
LEFT JOIN ITXVIEW_SUMSALESORDER is8 ON is8.BUYER = o.LONGDESCRIPTION AND is8.BULAN = 8 AND is8.TAHUN = 2023
LEFT JOIN ITXVIEW_SUMSALESORDER is9 ON is9.BUYER = o.LONGDESCRIPTION AND is9.BULAN = 9 AND is9.TAHUN = 2023
LEFT JOIN ITXVIEW_SUMSALESORDER is10 ON is10.BUYER = o.LONGDESCRIPTION AND is10.BULAN = 10 AND is10.TAHUN = 2023
LEFT JOIN ITXVIEW_SUMSALESORDER is11 ON is11.BUYER = o.LONGDESCRIPTION AND is11.BULAN = 11 AND is11.TAHUN = 2023
LEFT JOIN ITXVIEW_SUMSALESORDER is12 ON is12.BUYER = o.LONGDESCRIPTION AND is12.BULAN = 12 AND is12.TAHUN = 2023
ORDER BY 
	o.LONGDESCRIPTION ASC