DROP VIEW ITXVIEW_PELANGGAN;
--CREATE VIEW ITXVIEW_PELANGGAN AS
SELECT
    s.CODE,
    s.ORDPRNCUSTOMERSUPPLIERCODE,
    trim(b.LEGALNAME1) AS LANGGANAN,
    trim(s.ORDERPARTNERBRANDCODE) AS BUYER
FROM
    SALESORDER s
LEFT JOIN ORDERPARTNER o ON o.CUSTOMERSUPPLIERCODE = s.ORDPRNCUSTOMERSUPPLIERCODE
LEFT JOIN BUSINESSPARTNER b ON b.NUMBERID = o.ORDERBUSINESSPARTNERNUMBERID
LEFT JOIN ORDERPARTNERBRAND o2 ON o2.ORDPRNCUSTOMERSUPPLIERCODE = s.ORDPRNCUSTOMERSUPPLIERCODE
WHERE
	s.CODE = 'EXP2300807'
GROUP BY
    s.CODE,
    s.ORDPRNCUSTOMERSUPPLIERCODE,
    b.LEGALNAME1,
    s.ORDERPARTNERBRANDCODE;