DROP VIEW ITXVIEWGSMLEBKNTINS;
--CREATE VIEW ITXVIEWGSMLEBKNTINS AS
SELECT
	e.DEMANDCODE,
    e.ELEMENTCODE,
    e.WIDTHGROSS,
    a.VALUEDECIMAL
FROM
    ELEMENTSINSPECTION e
LEFT OUTER JOIN ADSTORAGE a ON
    a.UNIQUEID = e.ABSUNIQUEID
    AND a.NAMENAME = 'GSM';