DROP VIEW ITXVIEW_BOOKING; -- BOOKING READY
--CREATE VIEW ITXVIEW_BOOKING AS	
SELECT 
	ALLOCATION_CODE,
	DEMAND_KFF,
	DEMAND_KGF,
	PRODUCTIONORDERCODE,
	ONLY_PROJECTCODE,
	PROJECTCODE,
	DATE(TGLRENCANA) AS TGLRENCANA,
	NULL AS TGLPOGREIGE,
	LISTAGG(SUMMARIZEDDESCRIPTION, ', ') || '-' || TRIM(ONLY_PROJECTCODE)  AS SUMMARIZEDDESCRIPTION
FROM( 
	SELECT
		a.CODE AS ALLOCATION_CODE,
		a.ORDERCODE AS DEMAND_KFF,
		a2.LOTCODE AS DEMAND_KGF,
		p2.PRODUCTIONORDERCODE,
		CASE
			WHEN a2.PROJECTCODE IS NULL THEN TRIM(a2.LOTCODE)
			ELSE TRIM(a2.PROJECTCODE)
		END AS ONLY_PROJECTCODE,
		CASE
			WHEN a2.PROJECTCODE IS NULL THEN TRIM(a2.LOTCODE) || ' - ' || round(TRIM(a2.USERPRIMARYQUANTITY), 2) || ' ' || TRIM(a2.USERPRIMARYUOMCODE)
			ELSE TRIM(a2.LOTCODE) || ' - ' || round(TRIM(a2.USERPRIMARYQUANTITY), 2) || ' ' || TRIM(a2.USERPRIMARYUOMCODE)
		END AS PROJECTCODE,
	--	a3.VALUEDATE AS TGLRENCANA,
--		a4.VALUEDATE AS TGLPOGREIGE,
		NULL AS TGLPOGREIGE,
		a2.CREATIONDATETIME AS TGLRENCANA,
		LISTAGG(TRIM(p4.LONGDESCRIPTION) || '(' || CASE WHEN TRIM(CAST(p4.COMMENTTEXT AS VARCHAR(1000))) IS NULL THEN '()' ELSE TRIM(CAST(p4.COMMENTTEXT AS VARCHAR(1000))) END || ')', ', ') AS SUMMARIZEDDESCRIPTION,
		TRIM(a2.LOTCODE) AS LOTCODE
	FROM 
		PRODUCTIONDEMAND p 
	LEFT JOIN PRODUCTIONRESERVATION p2 ON p2.ORDERCODE = p.CODE 
	LEFT JOIN ALLOCATION a ON a.ORDERCODE = p.CODE AND a.DETAILTYPE = 1
	LEFT JOIN ALLOCATION a2 ON a2.CODE = a.CODE AND a2.DETAILTYPE = 0
	LEFT JOIN PRODUCTIONRESERVATION p3 ON p3.ORDERCODE = a2.LOTCODE
	LEFT JOIN PRODUCT p4 ON p4.ITEMTYPECODE = p3.ITEMTYPEAFICODE AND
							p4.SUBCODE01 = p3.SUBCODE01 AND 
							p4.SUBCODE02 = p3.SUBCODE02 AND
							p4.SUBCODE03 = p3.SUBCODE03 AND 
							p4.SUBCODE04 = p3.SUBCODE04 AND
							p4.SUBCODE05 = p3.SUBCODE05 AND 
							p4.SUBCODE06 = p3.SUBCODE06 AND
							p4.SUBCODE07 = p3.SUBCODE07 
	LEFT JOIN PRODUCTIONRESERVATIONCOMMENT p4 ON p4.PRODUCTIONRESERVATIONORDERCODE = p3.ORDERCODE AND p4.PRORESERVATIONRESERVATIONLINE = p3.RESERVATIONLINE
	LEFT JOIN PRODUCTIONDEMAND p5 ON p5.CODE = a2.LOTCODE  
	LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = p5.ABSUNIQUEID AND a3.FIELDNAME = 'RMPReqDate'
	LEFT JOIN ADSTORAGE a4 ON a4.UNIQUEID = p5.ABSUNIQUEID AND a4.FIELDNAME = 'RMPGreigeReqDateTo'
	WHERE 
		a.ORDERCODE = '00142891' AND 
		p2.ITEMTYPEAFICODE = 'KGF'
	GROUP BY 
		a.CODE,
		a.ORDERCODE,
		a2.LOTCODE,
		p2.PRODUCTIONORDERCODE,
	--	a3.VALUEDATE,
	--	a4.VALUEDATE,
		a2.CREATIONDATETIME,
		a2.PROJECTCODE,
		p3.RESERVATIONLINE,
		a2.USERPRIMARYQUANTITY,
		a2.USERPRIMARYUOMCODE
	ORDER BY p3.RESERVATIONLINE ASC)
GROUP BY 
	ALLOCATION_CODE,
	DEMAND_KFF,
	DEMAND_KGF,
	PRODUCTIONORDERCODE,
	ONLY_PROJECTCODE,
	PROJECTCODE,
	TGLRENCANA,
	TGLPOGREIGE,
	LOTCODE