--DROP VIEW ITXVIEWWEIGHTBONRESEP;
--CREATE VIEW ITXVIEWWEIGHTBONRESEP AS
--SELECT
--    PRODUCTIONORDERCODE,
--    SUM(QTY_BAGIKAIN) AS QTY_BAGIKAIN
--FROM
--    (
--    SELECT
--        ITXVIEWKK.PRODUCTIONORDERCODE AS PRODUCTIONORDERCODE,
--		CASE
--            WHEN ITXVIEW_RESERVATION.USEDUSERPRIMARYQUANTITY IS NULL OR ITXVIEW_RESERVATION.USEDUSERPRIMARYQUANTITY = 0 THEN ITXVIEW_RESERVATION.USERPRIMARYQUANTITY
--            ELSE ITXVIEW_RESERVATION.USEDUSERPRIMARYQUANTITY
--        END AS QTY_BAGIKAIN
--    FROM
--        ITXVIEWKK ITXVIEWKK
--    LEFT JOIN ITXVIEW_RESERVATION ITXVIEW_RESERVATION ON ITXVIEW_RESERVATION.ORDERCODE = ITXVIEWKK.DEAMAND AND ITXVIEW_RESERVATION.PRODUCTIONORDERCODE = ITXVIEWKK.PRODUCTIONORDERCODE 
--    GROUP BY
--        ITXVIEWKK.PRODUCTIONORDERCODE,
--        ITXVIEW_RESERVATION.USEDUSERPRIMARYQUANTITY,
--        ITXVIEW_RESERVATION.USERPRIMARYQUANTITY
--)
--GROUP BY
--    PRODUCTIONORDERCODE;
SELECT
    ITXVIEWKK.PRODUCTIONORDERCODE AS PRODUCTIONORDERCODE,
	CASE
        WHEN ITXVIEW_RESERVATION.USEDUSERPRIMARYQUANTITY IS NULL OR ITXVIEW_RESERVATION.USEDUSERPRIMARYQUANTITY = 0 THEN ITXVIEW_RESERVATION.USERPRIMARYQUANTITY
        ELSE ITXVIEW_RESERVATION.USEDUSERPRIMARYQUANTITY
    END AS QTY_BAGIKAIN
FROM
    ITXVIEWKK ITXVIEWKK
LEFT JOIN ITXVIEW_RESERVATION ITXVIEW_RESERVATION ON ITXVIEW_RESERVATION.ORDERCODE = ITXVIEWKK.DEAMAND AND ITXVIEW_RESERVATION.PRODUCTIONORDERCODE = ITXVIEWKK.PRODUCTIONORDERCODE 
GROUP BY
    ITXVIEWKK.PRODUCTIONORDERCODE,
    ITXVIEW_RESERVATION.USEDUSERPRIMARYQUANTITY,
    ITXVIEW_RESERVATION.USERPRIMARYQUANTITY