DROP VIEW ITXVIEW_MEMOPENTINGPPC;
--CREATE VIEW ITXVIEW_MEMOPENTINGPPC AS
SELECT
    DISTINCT
	i.ITEMTYPEAFICODE,
    i.ITEMTYPEAFICODE_YND,
    i.CREATIONDATETIME_PRODORDER AS ORDERDATE,
    ip.LANGGANAN || '|' || 
    CASE
        WHEN ip.BUYER IS NULL THEN 'Data tidak ditemukan, silahkan periksa kembali'
        ELSE ip.BUYER
    END AS PELANGGAN,
    ip.ORDPRNCUSTOMERSUPPLIERCODE,
    ip.LANGGANAN AS LANGGANAN,
    ip.BUYER AS BUYER,
    i.PROJECTCODE AS NO_ORDER,
    ik.EXTERNALREFERENCE AS NO_PO,
    TRIM(i.SUBCODE02) AS SUBCODE02,
    TRIM(i.SUBCODE03) AS SUBCODE03,
    TRIM(i.SUBCODE01) || '-' || TRIM(i.SUBCODE02) || '-' || TRIM(i.SUBCODE03) || '-' || TRIM(i.SUBCODE04) || '-' ||
    TRIM(i.SUBCODE05) || '-' || TRIM(i.SUBCODE06) || '-' || TRIM(i.SUBCODE07) || '-' || TRIM(i.SUBCODE08) AS KETERANGAN_PRODUCT,
    i.ITEMDESCRIPTION AS JENIS_KAIN,
    i.WARNA AS WARNA,
    i.SUBCODE05 AS NO_WARNA,
    i.DELIVERYDATE AS DELIVERY,
    p.USEDUSERPRIMARYQUANTITY AS QTY_BAGIKAIN,
    p.USEDUSERSECONDARYQUANTITY AS QTY_BAGIKAIN_YD_MTR,
    in2.USERPRIMARYQUANTITY AS NETTO,
    CASE
        WHEN DAYS(now()) - DAYS(Timestamp_Format(i.DELIVERYDATE, 'YYYY-MM-DD')) < 0 THEN 0
        ELSE DAYS(now()) - DAYS(Timestamp_Format(i.DELIVERYDATE, 'YYYY-MM-DD'))
    END AS DELAY,
    i.PRODUCTIONORDERCODE AS NO_KK,
    i.DEAMAND AS DEMAND,
    i.LOT,
    i.ORDERLINE,
    TRIM(i.PROGRESSSTATUS) AS PROGRESSSTATUS,
    CASE
        WHEN u.LONGDESCRIPTION IS NULL THEN ''
        ELSE u.LONGDESCRIPTION
    END || CASE
        WHEN a4.VALUESTRING IS NULL THEN ''
        ELSE a4.VALUESTRING
    END AS KETERANGAN,
    i.ABSUNIQUEID_DEMAND,
    i.REQUIREDDUEDATE,
    a2.VALUESTRING AS OriginalPDCode,
    a3.VALUESTRING AS SplittedFrom,
    i.CREATIONDATETIME_SALESORDER,
    i.PROGRESSSTATUS_DEMAND,
    i.EXTERNALITEM AS NO_ITEM
FROM
--    ITXVIEWKK i
	ITXVIEWKK_UNTUK_MEMOPENTING_PPC i
LEFT JOIN (SELECT ik.CODE, ik.EXTERNALREFERENCE, ik.PROJECTCODE, ik.ORIGDLVSALORDERLINEORDERLINE FROM ITXVIEW_KGBRUTO ik) ik ON ik.PROJECTCODE = i.PROJECTCODE AND ik.ORIGDLVSALORDERLINEORDERLINE = i.ORIGDLVSALORDERLINEORDERLINE AND ik.CODE = i.DEAMAND
LEFT JOIN (SELECT p.ORDERCODE, p.USEDUSERPRIMARYQUANTITY, p.USEDUSERSECONDARYQUANTITY FROM ITXVIEW_RESERVATION_KK p) p ON p.ORDERCODE = i.PRODUCTIONDEMANDCODE
LEFT JOIN (SELECT a.UNIQUEID, a.FIELDNAME, a.VALUESTRING FROM ADSTORAGE a) a ON a.UNIQUEID = i.ABSUNIQUEID_DEMAND AND a.FIELDNAME = 'DefectTypeCode'
LEFT JOIN (SELECT a2.UNIQUEID, a2.FIELDNAME, a2.VALUESTRING FROM ADSTORAGE a2) a2 ON a2.UNIQUEID = i.ABSUNIQUEID_DEMAND AND a2.FIELDNAME = 'OriginalPDCode'
LEFT JOIN (SELECT a3.UNIQUEID, a3.FIELDNAME, a3.VALUESTRING FROM ADSTORAGE a3) a3 ON a3.UNIQUEID = i.ABSUNIQUEID_DEMAND AND a3.FIELDNAME = 'SplittedFrom'
LEFT JOIN (SELECT u.CODE, u.USERGENERICGROUPTYPECODE, u.LONGDESCRIPTION FROM USERGENERICGROUP u) u ON u.CODE = a.VALUESTRING AND u.USERGENERICGROUPTYPECODE = '006'
LEFT JOIN (SELECT a4.UNIQUEID, a4.FIELDNAME, a4.VALUESTRING FROM ADSTORAGE a4) a4 ON a4.UNIQUEID = i.ABSUNIQUEID_DEMAND AND a4.FIELDNAME = 'DefectNote'
LEFT JOIN (SELECT in2.USERPRIMARYQUANTITY, in2.CODE, in2.SALESORDERLINESALESORDERCODE FROM ITXVIEW_NETTO in2) in2 ON in2.CODE = i.DEAMAND AND in2.SALESORDERLINESALESORDERCODE = i.PROJECTCODE
LEFT JOIN (SELECT ip.ORDPRNCUSTOMERSUPPLIERCODE AS ORDPRNCUSTOMERSUPPLIERCODE2, ip.CODE, ip.ORDPRNCUSTOMERSUPPLIERCODE, ip.LANGGANAN, ip.BUYER FROM ITXVIEW_PELANGGAN ip) ip ON ip.ORDPRNCUSTOMERSUPPLIERCODE = i.ORDPRNCUSTOMERSUPPLIERCODE AND ip.CODE = i.BONORDER
WHERE
	NOT i.ITEMTYPEAFICODE = 'KGF'
    --	(p.USEDUSERPRIMARYQUANTITY IS NOT NULL OR NOT p.USEDUSERPRIMARYQUANTITY = 0) 
--	CASE
--        WHEN i.ITEMTYPEAFICODE = 'KFF' THEN (p.USEDUSERPRIMARYQUANTITY IS NOT NULL OR NOT p.USEDUSERPRIMARYQUANTITY = 0)
--        WHEN i.ITEMTYPEAFICODE = 'FKF' THEN i.ITEMTYPEAFICODE = 'FKF'
--    END
    AND 
--    i.PRODUCTIONORDERCODE = '00118771'
--	AND
--	TRIM(i.SUBCODE01) || '-' || TRIM(i.SUBCODE02) || '-' || TRIM(i.SUBCODE03) || '-' || TRIM(i.SUBCODE04) || '-' ||
--    TRIM(i.SUBCODE05) || '-' || TRIM(i.SUBCODE06) || '-' || TRIM(i.SUBCODE07) || '-' || TRIM(i.SUBCODE08) = 'C-SJY-21046-L01-230577L-F106----'
--    i4.WARNA = '15-4101 TCX'
    --	AND ik.EXTERNALREFERENCE = '230412-SS24-FI-00413'
    --	AND i.SUBCODE02 = 'DKI' AND i.SUBCODE03 = '18019'
    --	AND v.OPERATIONCODE = 'DYE2'
--	i.DELIVERYDATE BETWEEN '2024-01-01' AND '2024-12-19' 