DROP VIEW ITXVIEW_POSISIKK_TGL_IN_PRODORDER_CNP1;
--CREATE VIEW ITXVIEW_POSISIKK_TGL_IN_PRODORDER_CNP1 AS
SELECT
	DISTINCT 
    v.PRODUCTIONORDERCODE,
    p2.OPERATIONCODE,
	p.PROPROGRESSPROGRESSNUMBER,
	p.DEMANDSTEPSTEPNUMBER,
	p2.PROGRESSTEMPLATECODE,
	(p2.PROGRESSPARTIALENDTIME || ' ' || p2.PROGRESSPARTIALENDTIME) AS MULAI
FROM
	PRODUCTIONDEMANDSTEP v
LEFT JOIN PRODUCTIONPROGRESSSTEPUPDATED p ON p.DEMANDSTEPPRODUCTIONDEMANDCODE = v.PRODUCTIONDEMANDCODE
RIGHT JOIN PRODUCTIONPROGRESS p2 ON p2.PROGRESSNUMBER = p.PROPROGRESSPROGRESSNUMBER AND p2.PROGRESSTEMPLATECODE = 'P01' AND p2.OPERATIONCODE = 'CNP1'
--WHERE 
--	v.PRODUCTIONORDERCODE = '00076899' 
--		AND p.DEMANDSTEPSTEPNUMBER = '600'	

	

	