DROP VIEW ITXVIEWLAPMASUKGREIGE;
--CREATE VIEW ITXVIEWLAPMASUKGREIGE AS
SELECT
--	STOCKTRANSACTION.TRANSACTIONNUMBER,
    INTERNALDOCUMENT.COMPANYCODE,
    INTERNALDOCUMENT.PROVISIONALCOUNTERCODE,
    INTERNALDOCUMENT.PROVISIONALCODE,
    INTERNALDOCUMENTLINE.RECEIVINGDATE, 
    INTERNALDOCUMENTLINE.ORDERLINE,
    INTERNALDOCUMENTLINE.EXTERNALREFERENCE,
    INTERNALDOCUMENTLINE.INTERNALREFERENCE,
    INTERNALDOCUMENTLINE.ITEMTYPEAFICODE,
    INTERNALDOCUMENTLINE.SUBCODE01,
    INTERNALDOCUMENTLINE.SUBCODE02,
    INTERNALDOCUMENTLINE.SUBCODE03,
    INTERNALDOCUMENTLINE.SUBCODE04,
    INTERNALDOCUMENTLINE.SUBCODE05,
    INTERNALDOCUMENTLINE.SUBCODE06,
    INTERNALDOCUMENTLINE.SUBCODE07,
    INTERNALDOCUMENTLINE.SUBCODE08,
    INTERNALDOCUMENTLINE.SUBCODE09,
    INTERNALDOCUMENTLINE.SUBCODE10,
    INTERNALDOCUMENTLINE.ITEMDESCRIPTION,
    INTERNALDOCUMENTLINE.DESTINATIONWAREHOUSECODE,
    FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION,
    STOCKTRANSACTION.LOTCODE,
    SUM(STOCKTRANSACTION.BASEPRIMARYQUANTITY) AS QTY_KG,
    SUM(STOCKTRANSACTION.USERPRIMARYQUANTITY) AS QTY_USER,
    STOCKTRANSACTION.USERPRIMARYUOMCODE,
    STOCKTRANSACTION.WHSLOCATIONWAREHOUSEZONECODE,
    STOCKTRANSACTION.WAREHOUSELOCATIONCODE
FROM
    INTERNALDOCUMENT INTERNALDOCUMENT
LEFT JOIN INTERNALDOCUMENTLINE INTERNALDOCUMENTLINE ON
    INTERNALDOCUMENT.PROVISIONALCOUNTERCODE = INTERNALDOCUMENTLINE.INTDOCPROVISIONALCOUNTERCODE
    AND INTERNALDOCUMENT.PROVISIONALCODE = INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE
LEFT JOIN STOCKTRANSACTION STOCKTRANSACTION ON
    INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE = STOCKTRANSACTION.ORDERCODE
    AND INTERNALDOCUMENTLINE.ORDERLINE = STOCKTRANSACTION.ORDERLINE
LEFT JOIN FULLITEMKEYDECODER FULLITEMKEYDECODER ON
    STOCKTRANSACTION.FULLITEMIDENTIFIER = FULLITEMKEYDECODER.IDENTIFIER
WHERE
    STOCKTRANSACTION.TEMPLATECODE = '204'
    AND STOCKTRANSACTION.LOGICALWAREHOUSECODE = 'M021'
GROUP BY
--	STOCKTRANSACTION.TRANSACTIONNUMBER,
    INTERNALDOCUMENT.COMPANYCODE,
    INTERNALDOCUMENT.PROVISIONALCOUNTERCODE,
    INTERNALDOCUMENT.PROVISIONALCODE,
    INTERNALDOCUMENTLINE.RECEIVINGDATE,
    INTERNALDOCUMENTLINE.ORDERLINE,
    INTERNALDOCUMENTLINE.EXTERNALREFERENCE,
    INTERNALDOCUMENTLINE.INTERNALREFERENCE,
    INTERNALDOCUMENTLINE.ITEMTYPEAFICODE,
    INTERNALDOCUMENTLINE.SUBCODE01,
    INTERNALDOCUMENTLINE.SUBCODE02,
    INTERNALDOCUMENTLINE.SUBCODE03,
    INTERNALDOCUMENTLINE.SUBCODE04,
    INTERNALDOCUMENTLINE.SUBCODE05,
    INTERNALDOCUMENTLINE.SUBCODE06,
    INTERNALDOCUMENTLINE.SUBCODE07,
    INTERNALDOCUMENTLINE.SUBCODE08,
    INTERNALDOCUMENTLINE.SUBCODE09,
    INTERNALDOCUMENTLINE.SUBCODE10,
    INTERNALDOCUMENTLINE.ITEMDESCRIPTION,
    INTERNALDOCUMENTLINE.DESTINATIONWAREHOUSECODE,
    FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION,
    STOCKTRANSACTION.LOTCODE,
    STOCKTRANSACTION.USERPRIMARYUOMCODE,
    STOCKTRANSACTION.WHSLOCATIONWAREHOUSEZONECODE,
    STOCKTRANSACTION.WAREHOUSELOCATIONCODE;