DROP VIEW ITXVIEW_LB;
--CREATE VIEW ITXVIEW_LB AS
SELECT
    QUALITYDOCPRODUCTIONORDERCODE,
    QUALITYDOCUMENTHEADERNUMBERID AS HEADERNUMBERID,
    trim(CHARACTERISTICCODE) AS CHARACTERISTICCODE,
    VALUEQUANTITY
FROM
     QUALITYDOCLINE 
WHERE 
	QUALITYDOCUMENTHEADERNUMBERID = '839' 
    OR QUALITYDOCUMENTHEADERNUMBERID = '841' 
    OR QUALITYDOCUMENTHEADERNUMBERID = '844' 
    OR QUALITYDOCUMENTHEADERNUMBERID = '845' 
    OR QUALITYDOCUMENTHEADERNUMBERID = '847'
GROUP BY
	QUALITYDOCPRODUCTIONORDERCODE,
    QUALITYDOCUMENTHEADERNUMBERID,
    trim(CHARACTERISTICCODE),
    VALUEQUANTITY
    