DROP VIEW ITXVIEWPROJECTBONORDER;
--CREATE VIEW ITXVIEWPROJECTBONORDER AS  
SELECT  
	PRODUCTIONDEMAND.ABSUNIQUEID,
    PRODUCTIONDEMAND.CODE,
    PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE,
    PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE,
    PRODUCTIONDEMAND.ITEMTYPEAFICODE,
    PRODUCTIONDEMAND.SUBCODE01,
    PRODUCTIONDEMAND.SUBCODE02,
    PRODUCTIONDEMAND.SUBCODE03,
    PRODUCTIONDEMAND.SUBCODE04,
    CASE
    	WHEN A.PRO1 IS NULL THEN '-'
    	ELSE A.PRO1
    END AS PRO1,
    B.PRO2,
    C.PRO3,
    D.PRO4,
    CASE
    	WHEN E.RMPNOTE IS NULL THEN '-'
    	ELSE E.RMPNOTE
    END AS RMPNOTE,
    CASE
    	WHEN Floor(F.RMPQTY) IS NULL THEN 0
    	ELSE Floor(F.RMPQTY)
    END AS QTY,
    CASE
    	WHEN p.ITEMTYPEAFICODE = 'KGF' AND TRIM(p.SUBCODE04) = 'D01' THEN 'Dark' 
    	WHEN p.ITEMTYPEAFICODE = 'KGF' AND TRIM(p.SUBCODE04) = 'L01' THEN 'Light'
    	ELSE '-'
    END AS DL
FROM
    PRODUCTIONDEMAND PRODUCTIONDEMAND
LEFT JOIN (
    SELECT
        ADSTORAGE.UNIQUEID,
        ADSTORAGE.VALUESTRING AS PRO1
    FROM
        ADSTORAGE ADSTORAGE
    WHERE
        ADSTORAGE.NAMENAME = 'ProAllow'
) A ON
    PRODUCTIONDEMAND.ABSUNIQUEID = A.UNIQUEID
LEFT JOIN (
    SELECT
        ADSTORAGE.UNIQUEID,
        ADSTORAGE.VALUESTRING AS PRO2
    FROM
        ADSTORAGE ADSTORAGE
    WHERE
        ADSTORAGE.NAMENAME = 'ProAllow2'
) B ON
    PRODUCTIONDEMAND.ABSUNIQUEID = B.UNIQUEID
LEFT JOIN (
    SELECT
        ADSTORAGE.UNIQUEID,
        ADSTORAGE.VALUESTRING AS PRO3
    FROM
        ADSTORAGE ADSTORAGE
    WHERE
        ADSTORAGE.NAMENAME = 'ProAllow3'
) C ON
    PRODUCTIONDEMAND.ABSUNIQUEID = C.UNIQUEID
LEFT JOIN (
    SELECT
        ADSTORAGE.UNIQUEID,
        ADSTORAGE.VALUESTRING AS PRO4
    FROM
        ADSTORAGE ADSTORAGE
    WHERE
        ADSTORAGE.NAMENAME = 'ProAllow4'
) D ON
    PRODUCTIONDEMAND.ABSUNIQUEID = D.UNIQUEID
LEFT JOIN (
    SELECT
        ADSTORAGE.UNIQUEID,
        ADSTORAGE.VALUESTRING AS RMPNOTE
    FROM
        ADSTORAGE ADSTORAGE
    WHERE
        ADSTORAGE.NAMENAME = 'RMPNote'
) E ON
    PRODUCTIONDEMAND.ABSUNIQUEID = E.UNIQUEID
LEFT JOIN (
    SELECT
        ADSTORAGE.UNIQUEID,
        ADSTORAGE.VALUEDECIMAL AS RMPQTY
    FROM
        ADSTORAGE ADSTORAGE
    WHERE
        ADSTORAGE.NAMENAME = 'ProAllowQty'
) F ON
    PRODUCTIONDEMAND.ABSUNIQUEID = F.UNIQUEID
LEFT JOIN PRODUCTIONDEMAND p ON p.ITEMTYPEAFICODE = 'KGF' 
							AND p.ORIGDLVSALORDLINESALORDERCODE = PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE
							AND p.ORIGDLVSALORDERLINEORDERLINE = PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE 
--WHERE PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE = 'DOM2300392' 
--AND PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE = 120 
GROUP BY
	PRODUCTIONDEMAND.ABSUNIQUEID,
    PRODUCTIONDEMAND.CODE,
    PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE,
    PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE,
    PRODUCTIONDEMAND.ITEMTYPEAFICODE,
    PRODUCTIONDEMAND.SUBCODE01,
    PRODUCTIONDEMAND.SUBCODE02,
    PRODUCTIONDEMAND.SUBCODE03,
    PRODUCTIONDEMAND.SUBCODE04,
    A.PRO1,
    B.PRO2,
    C.PRO3,
    D.PRO4,
    E.RMPNOTE,
    F.RMPQTY,
    p.ITEMTYPEAFICODE,
    p.SUBCODE04