DROP VIEW ITXVIEW_INVOICE_GRANDTOTAL3;
--CREATE VIEW ITXVIEW_INVOICE_GRANDTOTAL3 AS
SELECT
    s.PROVISIONALCODE AS SALESDOCUMENTPROVISIONALCODE,
--    s.COMPANYCODE AS SALESDOCUMENTCOMPANYCODE,
--    s.PROVISIONALCOUNTERCODE AS SALDOCPROVISIONALCOUNTERCODE,
    CASE
        WHEN s.PROVISIONALCOUNTERCODE IN ('EXDPROV', 'EXPPROV', 'DREPROV', 'PFEPROV', 'GSEPROV') THEN E.total_kg
        WHEN s.PROVISIONALCOUNTERCODE NOT IN ('EXDPROV', 'EXPPROV', 'DREPROV', 'PFEPROV', 'GSEPROV') THEN L.total_kg
    END AS total_kg,
    CASE
        WHEN s.PROVISIONALCOUNTERCODE IN ('EXDPROV', 'EXPPROV', 'DREPROV', 'PFEPROV', 'GSEPROV') THEN E.total_yard
        WHEN s.PROVISIONALCOUNTERCODE NOT IN ('EXDPROV', 'EXPPROV', 'DREPROV', 'PFEPROV', 'GSEPROV') THEN L.total_yard
    END AS total_yard,
    CASE
        WHEN s.PROVISIONALCOUNTERCODE IN ('EXDPROV', 'EXPPROV', 'DREPROV', 'PFEPROV', 'GSEPROV') THEN E.total_meter
        WHEN s.PROVISIONALCOUNTERCODE NOT IN ('EXDPROV', 'EXPPROV', 'DREPROV', 'PFEPROV', 'GSEPROV') THEN L.total_meter
    END AS total_meter,
    CASE
        WHEN s.PROVISIONALCOUNTERCODE IN ('EXDPROV', 'EXPPROV', 'DREPROV', 'PFEPROV', 'GSEPROV') THEN E.total_unit
        WHEN s.PROVISIONALCOUNTERCODE NOT IN ('EXDPROV', 'EXPPROV', 'DREPROV', 'PFEPROV', 'GSEPROV') THEN L.total_unit
    END AS total_unit,
    CASE
        WHEN s.PROVISIONALCOUNTERCODE IN ('EXDPROV', 'EXPPROV', 'DREPROV', 'PFEPROV', 'GSEPROV') THEN E.TOTAL_jml_harga_YD
        WHEN s.PROVISIONALCOUNTERCODE NOT IN ('EXDPROV', 'EXPPROV', 'DREPROV', 'PFEPROV', 'GSEPROV') THEN L.TOTAL_jml_harga_YD
    END AS TOTAL_jml_harga_YD,
    CASE
        WHEN s.PROVISIONALCOUNTERCODE IN ('EXDPROV', 'EXPPROV', 'DREPROV', 'PFEPROV', 'GSEPROV') THEN E.TOTAL_jml_harga_kg
        WHEN s.PROVISIONALCOUNTERCODE NOT IN ('EXDPROV', 'EXPPROV', 'DREPROV', 'PFEPROV', 'GSEPROV') THEN L.TOTAL_jml_harga_kg
    END AS TOTAL_jml_harga_kg,
    CASE
        WHEN s.PROVISIONALCOUNTERCODE IN ('EXDPROV', 'EXPPROV', 'DREPROV', 'PFEPROV', 'GSEPROV') THEN E.TOTAL_jml_harga_m
        WHEN s.PROVISIONALCOUNTERCODE NOT IN ('EXDPROV', 'EXPPROV', 'DREPROV', 'PFEPROV', 'GSEPROV') THEN L.TOTAL_jml_harga_m
    END AS TOTAL_jml_harga_m,
    CASE
        WHEN s.PROVISIONALCOUNTERCODE IN ('EXDPROV', 'EXPPROV', 'DREPROV', 'PFEPROV', 'GSEPROV') THEN E.TOTAL_jml_harga_un
        WHEN s.PROVISIONALCOUNTERCODE NOT IN ('EXDPROV', 'EXPPROV', 'DREPROV', 'PFEPROV', 'GSEPROV') THEN L.TOTAL_jml_harga_un
    END AS TOTAL_jml_harga_un
FROM
    SALESDOCUMENT s
LEFT JOIN ITXVIEW_INVOICE_GRANDTOTAL2L L ON L.SALESDOCUMENTPROVISIONALCODE = s.PROVISIONALCODE
LEFT JOIN ITXVIEW_INVOICE_GRANDTOTAL2E E ON E.SALESDOCUMENTPROVISIONALCODE = s.PROVISIONALCODE
WHERE 
    s.PROVISIONALCODE = 'POD2402674'