-- DB2ADMIN.ITXVIEWKK source
DROP VIEW ITXVIEWKK;
--CREATE VIEW ITXVIEWKK AS
SELECT
    DISTINCT
    PRODUCTIONDEMAND.PROGRESSSTATUS AS PROGRESSSTATUS_DEMAND,
    PRODUCTIONDEMAND.COMPANYCODE,
    PRODUCTIONDEMAND.CODE AS DEAMAND,
    PRODUCTIONDEMAND.TEMPLATECODE,
    PRODUCTIONDEMAND.ORDERDATE,
    SALESORDERDELIVERY.DELIVERYDATE,
    PRODUCTIONDEMAND.FINALPLANNEDDATE,
    PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE AS PROJECTCODE,
    dept.LONGDESCRIPTION || a10.VALUESTRING AS DESC_DEMAND,
    PRODUCTIONDEMAND.INTERNALREFERENCE AS DESC_DEMAND_KK,
    PRODUCTIONDEMAND.ITEMTYPEAFICODE AS ITEMTYPEAFICODE_YND,
    PRODUCTIONDEMAND.ABSUNIQUEID AS ABSUNIQUEID_DEMAND,
    TRIM(SALESORDERLINE.SUBCODE01) AS DSUBCODE01,
    TRIM(SALESORDERLINE.SUBCODE02) AS DSUBCODE02,
    TRIM(SALESORDERLINE.SUBCODE03) AS DSUBCODE03,
    TRIM(SALESORDERLINE.SUBCODE04) AS DSUBCODE04,
    TRIM(SALESORDERLINE.SUBCODE05) AS DSUBCODE05,
    TRIM(SALESORDERLINE.SUBCODE06) AS DSUBCODE06,
    TRIM(SALESORDERLINE.SUBCODE07) AS DSUBCODE07,
    TRIM(SALESORDERLINE.SUBCODE08) AS DSUBCODE08,
    TRIM(SALESORDERLINE.SUBCODE09) AS DSUBCODE09,
    TRIM(SALESORDERLINE.SUBCODE10) AS DSUBCODE10,   
    PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE,
    PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE,
    PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE,
    PRODUCTIONDEMAND.DESCRIPTION AS LOT,
    PRODUCTIONDEMAND.ENTEREDUSERPRIMARYQUANTITY AS QTY_PACKING_KG,
    PRODUCTIONDEMAND.ENTEREDBASESECONDARYQUANTITY AS QTY_PACKING_YARD,
    SALESORDER.CODE AS BONORDER,
    SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE,
    SALESORDER.DESCRIPTION,
    SALESORDER.REQUIREDDUEDATE,
    SALESORDER.ABSUNIQUEID AS ABSUNIQUEID_SALESORDER,
    CASE
        WHEN SALESORDER.DELIVERYPOINTCODE IS NOT NULL THEN 
        	TRIM(a.ADDRESSLINE1) || ', ' || 
        	CASE
            WHEN TRIM(a.ADDRESSLINE2) IS NULL THEN '-'
            ELSE TRIM(a.ADDRESSLINE2)
        END || ', ' || 
        	CASE
            WHEN TRIM(a.ADDRESSLINE3) IS NULL THEN '-'
            ELSE TRIM(a.ADDRESSLINE3)
        END || ', ' || 
        	CASE
            WHEN TRIM(a.ADDRESSLINE4) IS NULL THEN '-'
            ELSE TRIM(a.ADDRESSLINE4)
        END
        ELSE BUSINESSPARTNER.ADDRESSLINE1
    END AS ADDRESSLINE1,
    CASE
        WHEN TRIM(o.EXTERNALITEMCODE) IS NULL THEN TRIM(PRODUCTIONDEMAND.SUBCODE02) || '-' || TRIM(PRODUCTIONDEMAND.SUBCODE03)
        ELSE TRIM(o.EXTERNALITEMCODE)
    END AS EXTERNALITEM,    
    PRODUCTIONDEMAND.ITEMTYPEAFICODE,
    PRODUCTIONDEMAND.SUBCODE01,
    PRODUCTIONDEMAND.SUBCODE02,
    PRODUCTIONDEMAND.SUBCODE03,
    PRODUCTIONDEMAND.SUBCODE04,
    p.SUBCODE02 AS RESERVATION_SUBCODE02,
    p.SUBCODE03 AS RESERVATION_SUBCODE03,
    p.SUBCODE04 AS RESERVATION_SUBCODE04,
    PRODUCTIONDEMAND.SUBCODE05,
    PRODUCTIONDEMAND.SUBCODE06,
    PRODUCTIONDEMAND.SUBCODE07,
    PRODUCTIONDEMAND.SUBCODE08,
    PRODUCTIONDEMAND.SUBCODE09,
    PRODUCTIONDEMAND.SUBCODE10,
    i.WARNA,
    i.WARNA_DASAR,
    CASE
        WHEN PRODUCT.LONGDESCRIPTION IS NULL THEN SALESORDERLINE.ITEMDESCRIPTION
        ELSE PRODUCT.LONGDESCRIPTION
    END || ' ' || 
--    CASE
--        WHEN TRIM(SALESORDER.INTERNALREFERENCE) IS NULL THEN 
--	        CASE
--	        	WHEN TRIM(SALESORDERLINE.INTERNALREFERENCE) IS NULL THEN '-'
--	        	ELSE TRIM(SALESORDERLINE.INTERNALREFERENCE)
--        	END
--        ELSE TRIM(SALESORDER.INTERNALREFERENCE)
--    END AS ITEMDESCRIPTION,
    COALESCE(SALESORDER.INTERNALREFERENCE, COALESCE(SALESORDERLINE.INTERNALREFERENCE, '')) AS ITEMDESCRIPTION,
    SALESORDERLINE.USERSECONDARYUOMCODE,
    SALESORDERLINE.PRICEUNITOFMEASURECODE,
    SALESORDERLINE.ABSUNIQUEID AS ABSUNIQUEID_SALESORDERLINE,
    SALESORDERLINE.ORDERLINE,
    PRODUCTIONORDER.CREATIONDATETIME,
    PRODUCTIONORDER.PROGRESSSTATUS,
    'KGF' AS KGF,
    a2.VALUESTRING AS ADDITIONALDATA,
    a21.VALUEDECIMAL AS QTY,
    a3.VALUESTRING AS ADDITIONALDATA2,
    a22.VALUEDECIMAL AS QTY2,
    a4.VALUESTRING AS ADDITIONALDATA3,
    a23.VALUEDECIMAL AS QTY3,
    a5.VALUESTRING AS ADDITIONALDATA4,
    a24.VALUEDECIMAL AS QTY4,
    a6.VALUESTRING AS ADDITIONALDATA5,
    a25.VALUEDECIMAL AS QTY5,
    a26.VALUESTRING AS LEGACYORDER,
    a28.VALUEDECIMAL AS QTY6,
    a7.VALUESTRING AS OriginalPdCode,
    SALESORDER.CREATIONDATETIME AS CREATIONDATETIME_SALESORDER,
    SALESORDER.CREATIONUSER AS CREATIONUSER_SALESORDER,
    CASE
        WHEN a8.VALUESTRING IS NOT NULL THEN 'KK TAS'
        ELSE a8.VALUESTRING
    END AS KARTUKERJA,
    PRODUCTIONDEMAND.RESERVATIONORDERCODE AS DEMAND_KNT_by_YND,
    CASE
        WHEN a11.VALUESTRING = '1' THEN 'BODY'
        WHEN a11.VALUESTRING = '2' THEN 'KRAH'
    END AS UNTUK_PEMAKAIAN,
    a12.VALUESTRING AS KELIPATAN_RAJUT,
    a13.VALUEINT AS QTY_PERMINTAAN_BUYER,
    a14.VALUEDATE AS DATE_AKTUAL,
    a35.VALUEDATE AS DATE_AKTUAL_TO,
    a15.VALUEDATE AS DATE_AKTUAL2,
    a36.VALUEDATE AS DATE_AKTUAL_TO2,
    a16.VALUEDATE AS DATE_AKTUAL3,
    a37.VALUEDATE AS DATE_AKTUAL_TO3,
    a17.VALUEDATE AS DATE_AKTUAL4,
    a38.VALUEDATE AS DATE_AKTUAL_TO4,
    a18.VALUEDATE AS DATE_AKTUAL5,
    a39.VALUEDATE AS DATE_AKTUAL_TO5,
    a28.VALUEDATE AS DATE_AKTUAL6,
	a40.VALUEDATE AS DATE_AKTUAL_TO6,
    CASE
        WHEN a19.VALUESTRING = '1' THEN 'AKJ'
        WHEN a19.VALUESTRING = '2' THEN 'AKW'
        ELSE 'NON AKJ'
    END AS AKJ,
    a20.VALUESTRING AS NoteTas,
    a29.VALUESTRING AS PROD_ORDER_AKJ,
    a30.VALUESTRING AS SALESORDER_AKJ,
    a31.VALUESTRING AS PROD_ORDER_AKJ2,
    a32.VALUESTRING AS SALESORDER_AKJ2,
    a33.VALUESTRING AS PROD_ORDER_AKJ3,
    a34.VALUESTRING AS SALESORDER_AKJ3,
    a41.LONGDESCRIPTION AS AREA,
    a42.VALUESTRING AS PRODUCTIONORDER_AKW,
    a43.VALUEDECIMAL AS LOSS_RMP,
    a44.VALUESTRING AS NO_REGIS_NCP,
    a45.VALUESTRING AS COLORGROUP,
    u2.LONGDESCRIPTION AS NAME_COLORGROUP
FROM
    PRODUCTIONDEMAND PRODUCTIONDEMAND
LEFT JOIN (
        SELECT
            DISTINCT PRODUCTIONDEMANDCODE,
            PRODUCTIONORDERCODE
        FROM
            PRODUCTIONDEMANDSTEP PRODUCTIONDEMANDSTEP
    ) PRODUCTIONDEMANDSTEP ON PRODUCTIONDEMAND.CODE = PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE
LEFT JOIN SALESORDER SALESORDER ON PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE = SALESORDER.CODE
LEFT JOIN ORDERPARTNER ORDERPARTNER ON PRODUCTIONDEMAND.CUSTOMERCODE = ORDERPARTNER.CUSTOMERSUPPLIERCODE
LEFT JOIN BUSINESSPARTNER BUSINESSPARTNER ON BUSINESSPARTNER.NUMBERID = ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID
LEFT JOIN ADDRESS a ON a.CODE = SALESORDER.DELIVERYPOINTCODE AND a.UNIQUEID = SALESORDER.DELIVERYPOINTUNIQUEID
LEFT JOIN SALESORDERLINE SALESORDERLINE ON SALESORDERLINE.SALESORDERCODE = SALESORDER.CODE AND SALESORDERLINE.ORDERLINE = PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE
LEFT JOIN SALESORDERDELIVERY SALESORDERDELIVERY ON SALESORDERDELIVERY.SALESORDERLINESALESORDERCODE = PRODUCTIONDEMAND.DLVSALORDERLINESALESORDERCODE AND SALESORDERDELIVERY.SALESORDERLINEORDERLINE = PRODUCTIONDEMAND.DLVSALESORDERLINEORDERLINE
RIGHT JOIN PRODUCTIONORDER PRODUCTIONORDER ON PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE = PRODUCTIONORDER.CODE
LEFT JOIN PRODUCT PRODUCT ON PRODUCT.ITEMTYPECODE = PRODUCTIONDEMAND.ITEMTYPEAFICODE
    AND PRODUCT.SUBCODE01 = PRODUCTIONDEMAND.SUBCODE01
    AND PRODUCT.SUBCODE02 = PRODUCTIONDEMAND.SUBCODE02
    AND PRODUCT.SUBCODE03 = PRODUCTIONDEMAND.SUBCODE03
    AND PRODUCT.SUBCODE04 = PRODUCTIONDEMAND.SUBCODE04
    AND PRODUCT.SUBCODE05 = PRODUCTIONDEMAND.SUBCODE05
    AND PRODUCT.SUBCODE06 = PRODUCTIONDEMAND.SUBCODE06
    AND PRODUCT.SUBCODE07 = PRODUCTIONDEMAND.SUBCODE07
    AND PRODUCT.SUBCODE08 = PRODUCTIONDEMAND.SUBCODE08
    AND PRODUCT.SUBCODE09 = PRODUCTIONDEMAND.SUBCODE09
    AND PRODUCT.SUBCODE10 = PRODUCTIONDEMAND.SUBCODE10
LEFT JOIN ITXVIEWCOLOR i ON i.ITEMTYPECODE = PRODUCTIONDEMAND.ITEMTYPEAFICODE
    AND i.SUBCODE01 = PRODUCTIONDEMAND.SUBCODE01
    AND i.SUBCODE02 = PRODUCTIONDEMAND.SUBCODE02
    AND i.SUBCODE03 = PRODUCTIONDEMAND.SUBCODE03
    AND i.SUBCODE04 = PRODUCTIONDEMAND.SUBCODE04
    AND i.SUBCODE05 = PRODUCTIONDEMAND.SUBCODE05
    AND i.SUBCODE06 = PRODUCTIONDEMAND.SUBCODE06
    AND i.SUBCODE07 = PRODUCTIONDEMAND.SUBCODE07
    AND i.SUBCODE08 = PRODUCTIONDEMAND.SUBCODE08
    AND i.SUBCODE09 = PRODUCTIONDEMAND.SUBCODE09
    AND i.SUBCODE10 = PRODUCTIONDEMAND.SUBCODE10
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a2.FIELDNAME = 'ProAllow'
LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a3.FIELDNAME = 'ProAllow2'
LEFT JOIN ADSTORAGE a4 ON a4.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a4.FIELDNAME = 'ProAllow3'
LEFT JOIN ADSTORAGE a5 ON a5.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a5.FIELDNAME = 'ProAllow4'
LEFT JOIN ADSTORAGE a6 ON a6.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a6.FIELDNAME = 'ProAllow5'
LEFT JOIN ADSTORAGE a7 ON a7.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a7.FIELDNAME = 'OriginalPDCode'
LEFT JOIN ADSTORAGE a8 ON a8.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a8.FIELDNAME = 'NoTrackingDev'
LEFT JOIN ADSTORAGE a9 ON a9.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a9.FIELDNAME = 'BagianCode'
LEFT JOIN ADSTORAGE a10 ON a10.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a10.FIELDNAME = 'DefectNote'
LEFT JOIN DEPARTMENT dept ON dept.CODE = a9.VALUESTRING 
LEFT JOIN ORDERITEMORDERPARTNERLINK o ON o.INACTIVE = 0
    AND o.ORDPRNCUSTOMERSUPPLIERCODE = SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE
    AND o.ITEMTYPEAFICODE = PRODUCTIONDEMAND.ITEMTYPEAFICODE
    AND o.SUBCODE01 = PRODUCTIONDEMAND.SUBCODE01
    AND o.SUBCODE02 = PRODUCTIONDEMAND.SUBCODE02
    AND o.SUBCODE03 = PRODUCTIONDEMAND.SUBCODE03
    AND o.SUBCODE04 = PRODUCTIONDEMAND.SUBCODE04
    AND o.SUBCODE05 = PRODUCTIONDEMAND.SUBCODE05
    AND o.SUBCODE06 = PRODUCTIONDEMAND.SUBCODE06
    AND o.SUBCODE07 = PRODUCTIONDEMAND.SUBCODE07
    AND o.SUBCODE08 = PRODUCTIONDEMAND.SUBCODE08
    AND o.SUBCODE09 = PRODUCTIONDEMAND.SUBCODE09
    AND o.SUBCODE10 = PRODUCTIONDEMAND.SUBCODE10
LEFT JOIN ADSTORAGE a11 ON a11.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a11.FIELDNAME = 'UntukItem'
LEFT JOIN ADSTORAGE a12 ON a12.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a12.FIELDNAME = 'KelipatanRajut'
LEFT JOIN ADSTORAGE a13 ON a13.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a13.FIELDNAME = 'QTYPermintaanRMP'
LEFT JOIN ADSTORAGE a14 ON a14.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a14.FIELDNAME = 'ProAllowDate'
LEFT JOIN ADSTORAGE a15 ON a15.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a15.FIELDNAME = 'ProAllowDate2'
LEFT JOIN ADSTORAGE a16 ON a16.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a16.FIELDNAME = 'ProAllowDate3'
LEFT JOIN ADSTORAGE a17 ON a17.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a17.FIELDNAME = 'ProAllowDate4'
LEFT JOIN ADSTORAGE a18 ON a18.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a18.FIELDNAME = 'ProAllowDate5'
LEFT JOIN ADSTORAGE a19 ON a19.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND a19.FIELDNAME = 'KainAKJ'
LEFT JOIN ADSTORAGE a20 ON a20.UNIQUEID = PRODUCT.ABSUNIQUEID AND a20.FIELDNAME = 'NoteTas'
LEFT JOIN ADSTORAGE a21 ON a21.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a21.FIELDNAME = 'ProAllowQty'
LEFT JOIN ADSTORAGE a22 ON a22.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a22.FIELDNAME = 'ProAllowQty2'
LEFT JOIN ADSTORAGE a23 ON a23.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a23.FIELDNAME = 'ProAllowQty3'
LEFT JOIN ADSTORAGE a24 ON a24.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a24.FIELDNAME = 'ProAllowQty4'
LEFT JOIN ADSTORAGE a25 ON a25.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a25.FIELDNAME = 'ProAllowQty5'
LEFT JOIN ADSTORAGE a26 ON a26.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a26.FIELDNAME = 'LegacyOrder'
LEFT JOIN ADSTORAGE a27 ON a27.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a27.FIELDNAME = 'ProAllowDate6'
LEFT JOIN ADSTORAGE a28 ON a28.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a28.FIELDNAME = 'ProAllowQty6'
LEFT JOIN PRODUCTIONRESERVATION p ON p.ORDERCODE = PRODUCTIONDEMAND.CODE
    AND (
        p.ITEMTYPEAFICODE = 'KGF'
            OR p.ITEMTYPEAFICODE = 'KFF'
    )
LEFT JOIN ADSTORAGE a29 ON a29.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND a29.FIELDNAME = 'PrevProdOrderCode'
LEFT JOIN ADSTORAGE a30 ON a30.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND a30.FIELDNAME = 'PrevSalesOrderCode'
LEFT JOIN ADSTORAGE a31 ON a31.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND a31.FIELDNAME = 'PrevProdOrder2Code'
LEFT JOIN ADSTORAGE a32 ON a32.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND a32.FIELDNAME = 'PrevSalesOrder2Code'
LEFT JOIN ADSTORAGE a33 ON a33.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND a33.FIELDNAME = 'PrevProdOrder3Code'
LEFT JOIN ADSTORAGE a34 ON a34.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND a34.FIELDNAME = 'PrevSalesOrder3Code'
LEFT JOIN ADSTORAGE a35 ON a35.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a35.FIELDNAME = 'ProAllowDateto'
LEFT JOIN ADSTORAGE a36 ON a36.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a36.FIELDNAME = 'ProAllowDate2to'
LEFT JOIN ADSTORAGE a37 ON a37.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a37.FIELDNAME = 'ProAllowDate3to'
LEFT JOIN ADSTORAGE a38 ON a38.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a38.FIELDNAME = 'ProAllowDate4to'
LEFT JOIN ADSTORAGE a39 ON a39.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a39.FIELDNAME = 'ProAllowDate5to'
LEFT JOIN ADSTORAGE a40 ON a40.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a40.FIELDNAME = 'ProAllowDate6to'
LEFT JOIN AREA a41 ON a41.CODE = SALESORDER.AREACODE 
LEFT JOIN ADSTORAGE a42 ON a42.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND a42.FIELDNAME = 'PrevProdOrderCode'
LEFT JOIN ADSTORAGE a43 ON a43.UNIQUEID = PRODUCT.ABSUNIQUEID AND a43.FIELDNAME = 'WastePercentage'
LEFT JOIN ADSTORAGE a44 ON a44.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a44.FIELDNAME = 'NoRegisNCP'
LEFT JOIN USERGENERICGROUP u ON u.CODE = i.SUBCODE05 AND u.USERGENERICGROUPTYPECODE = 'CL1'
LEFT JOIN ADSTORAGE a45 ON a45.UNIQUEID = u.ABSUNIQUEID AND a45.FIELDNAME = 'ColorGroupCode'
LEFT JOIN USERGENERICGROUP u2 ON u2.CODE = a45.VALUESTRING AND u2.USERGENERICGROUPTYPECODE = 'CLG'
WHERE
    	PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE = '00120799';
--    PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE = '00191042'