DROP VIEW ITXVIEWSTEP_ROUTING;
--CREATE VIEW ITXVIEWSTEP_ROUTING AS 
SELECT 
	CODE,
	LISTAGG(OPERATIONCODE, '-') AS OPERATIONCODE
FROM 
	(SELECT
		p.CODE,
		r.SEQUENCE,
	    TRIM(r.OPERATIONCODE) AS OPERATIONCODE
	--    TRIM(r.LONGDESCRIPTION) AS DESCRIPTION 
	FROM
	    PRODUCTIONDEMAND p
	LEFT JOIN ROUTINGSTEP r ON r.ROUTINGNUMBERID = p.ROUTINGNUMBERID 
	LEFT JOIN OPERATION o ON o.CODE = r.OPERATIONCODE 
	LEFT JOIN ADSTORAGE a ON a.UNIQUEID = o.ABSUNIQUEID AND a.FIELDNAME = 'AlurProses'
	WHERE 
--	    p.CODE = '00185353' 
--	    AND
	    a.VALUESTRING = '2'
	ORDER BY
	    r.SEQUENCE ASC)
GROUP BY
	CODE
    
    
       
       
       
       
       
       
       
       