DROP VIEW ITXVIEW_ALURPROSES;
--CREATE VIEW ITXVIEW_ALURPROSES AS 
SELECT
	PRODUCTIONORDERCODE,
	LISTAGG(STEPOPERATION, ' - ') AS STEPOPERATION
FROM(
	SELECT
		v.PRODUCTIONORDERCODE,
		LISTAGG(DISTINCT
			CASE 
				WHEN TRIM(p2.SUBCODE02) || TRIM(p2.SUBCODE03) = 'DKI22039' AND TRIM(v.OPERATIONCODE) = 'JHP1' THEN TRIM(v.OPERATIONCODE) || '(poly dlm)'
				ELSE TRIM(v.OPERATIONCODE)
			END, ' - ') AS STEPOPERATION
	FROM
		VIEWPRODUCTIONDEMANDSTEP v
	LEFT JOIN PRODUCTIONDEMANDSTEP p ON p.PRODUCTIONORDERCODE = v.PRODUCTIONORDERCODE AND p.GROUPSTEPNUMBER = v.GROUPSTEPNUMBER
	LEFT JOIN PRODUCTIONDEMAND p2 ON p2.CODE = p.PRODUCTIONDEMANDCODE 
--	WHERE
--		v.PRODUCTIONORDERCODE IN ('00197639', '00193972')
--		p2.CREATIONDATETIME > '2025-01-01-00.00.00.000000'
--		AND TRIM(p2.SUBCODE02) || TRIM(p2.SUBCODE03) = 'DKI22039'
	GROUP BY 
		v.PRODUCTIONORDERCODE,
		v.GROUPSTEPNUMBER
	ORDER BY 
		v.GROUPSTEPNUMBER 
	ASC)
GROUP BY
	PRODUCTIONORDERCODE