-- DB2ADMIN.ITXVIEWKK source
DROP VIEW ITXVIEWKK;
--CREATE VIEW ITXVIEWKK AS
SELECT
    DISTINCT
    PRODUCTIONDEMAND.PROGRESSSTATUS AS PROGRESSSTATUS_DEMAND,
    PRODUCTIONDEMAND.COMPANYCODE,
    PRODUCTIONDEMAND.CODE AS DEAMAND,
    PRODUCTIONDEMAND.TEMPLATECODE,
    PRODUCTIONDEMAND.ORDERDATE,
--    SALESORDERDELIVERY.DELIVERYDATE,
    PRODUCTIONDEMAND.FINALPLANNEDDATE,
    PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE AS PROJECTCODE,
--    dept.LONGDESCRIPTION || a10.VALUESTRING AS DESC_DEMAND,
    PRODUCTIONDEMAND.INTERNALREFERENCE AS DESC_DEMAND_KK,
    PRODUCTIONDEMAND.ITEMTYPEAFICODE AS ITEMTYPEAFICODE_YND,
    PRODUCTIONDEMAND.ABSUNIQUEID AS ABSUNIQUEID_DEMAND,
--    TRIM(SALESORDERLINE.SUBCODE01) AS DSUBCODE01,
--    TRIM(SALESORDERLINE.SUBCODE02) AS DSUBCODE02,
--    TRIM(SALESORDERLINE.SUBCODE03) AS DSUBCODE03,
--    TRIM(SALESORDERLINE.SUBCODE04) AS DSUBCODE04,
--    TRIM(SALESORDERLINE.SUBCODE05) AS DSUBCODE05,
--    TRIM(SALESORDERLINE.SUBCODE06) AS DSUBCODE06,
--    TRIM(SALESORDERLINE.SUBCODE07) AS DSUBCODE07,
--    TRIM(SALESORDERLINE.SUBCODE08) AS DSUBCODE08,
--    TRIM(SALESORDERLINE.SUBCODE09) AS DSUBCODE09,
--    TRIM(SALESORDERLINE.SUBCODE10) AS DSUBCODE10,   
    PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE,
    PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE,
    PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE,
    PRODUCTIONDEMAND.DESCRIPTION AS LOT,
    PRODUCTIONDEMAND.ENTEREDUSERPRIMARYQUANTITY AS QTY_PACKING_KG,
    PRODUCTIONDEMAND.ENTEREDBASESECONDARYQUANTITY AS QTY_PACKING_YARD,
--    SALESORDER.CODE AS BONORDER,
--    SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE,
--    SALESORDER.DESCRIPTION,
--    SALESORDER.REQUIREDDUEDATE,
--    SALESORDER.ABSUNIQUEID AS ABSUNIQUEID_SALESORDER,
--    CASE
--        WHEN SALESORDER.DELIVERYPOINTCODE IS NOT NULL THEN 
--        	TRIM(a.ADDRESSLINE1) || ', ' || 
--        	CASE
--        		WHEN TRIM(a.ADDRESSLINE2) IS NULL THEN '-' ELSE TRIM(a.ADDRESSLINE2)
--        	END	|| ', ' || 
--        	CASE
--        		WHEN TRIM(a.ADDRESSLINE3) IS NULL THEN '-' ELSE TRIM(a.ADDRESSLINE3)
--        	END	|| ', ' || 
--        	CASE
--        		WHEN TRIM(a.ADDRESSLINE4) IS NULL THEN '-' ELSE TRIM(a.ADDRESSLINE4)
--        	END        	
--        ELSE BUSINESSPARTNER.ADDRESSLINE1
--    END AS ADDRESSLINE1,
--    CASE
--        WHEN TRIM(o.EXTERNALITEMCODE) IS NULL THEN '-'
--        ELSE TRIM(o.EXTERNALITEMCODE)
--    END AS EXTERNALITEM,    
    PRODUCTIONDEMAND.ITEMTYPEAFICODE,
    PRODUCTIONDEMAND.SUBCODE01,
    PRODUCTIONDEMAND.SUBCODE02,
    PRODUCTIONDEMAND.SUBCODE03,
    PRODUCTIONDEMAND.SUBCODE04,
--    CASE
--    	WHEN TRIM(PRODUCTIONDEMAND.SUBCODE01) = 'T' THEN p.SUBCODE04
--    	WHEN TRIM(PRODUCTIONDEMAND.SUBCODE01) = 'TX' THEN p.SUBCODE04
--    	ELSE PRODUCTIONDEMAND.SUBCODE04
--    END AS RESERVATION_SUBCODE04,
    PRODUCTIONDEMAND.SUBCODE05,
    PRODUCTIONDEMAND.SUBCODE06,
    PRODUCTIONDEMAND.SUBCODE07,
    PRODUCTIONDEMAND.SUBCODE08,
    PRODUCTIONDEMAND.SUBCODE09,
    PRODUCTIONDEMAND.SUBCODE10,
--    i.WARNA,
--    i.WARNA_DASAR,
--    CASE
--        WHEN PRODUCT.LONGDESCRIPTION IS NULL THEN SALESORDERLINE.ITEMDESCRIPTION
--        ELSE PRODUCT.LONGDESCRIPTION
--    END ||' ' || 
--    CASE 
--    	WHEN TRIM(SALESORDER.INTERNALREFERENCE) IS NULL THEN '-'
--    	ELSE TRIM(SALESORDER.INTERNALREFERENCE)
--    END AS ITEMDESCRIPTION,
--    SALESORDERLINE.USERSECONDARYUOMCODE,
--    SALESORDERLINE.PRICEUNITOFMEASURECODE,
--    SALESORDERLINE.ABSUNIQUEID AS ABSUNIQUEID_SALESORDERLINE,
--    SALESORDERLINE.ORDERLINE,
--    PRODUCTIONORDER.CREATIONDATETIME,
--    PRODUCTIONORDER.PROGRESSSTATUS,
--    'KGF' AS KGF,
--    a2.VALUESTRING AS ADDITIONALDATA,
--    a21.VALUEDECIMAL AS QTY,
--    a3.VALUESTRING AS ADDITIONALDATA2,
--    a22.VALUEDECIMAL AS QTY2,
--    a4.VALUESTRING AS ADDITIONALDATA3,
--    a23.VALUEDECIMAL AS QTY3,
--    a5.VALUESTRING AS ADDITIONALDATA4,
--    a24.VALUEDECIMAL AS QTY4,
--    a6.VALUESTRING AS ADDITIONALDATA5,
--    a25.VALUEDECIMAL AS QTY5,
--    a26.VALUESTRING AS LEGACYORDER,
--    a7.VALUESTRING AS OriginalPdCode,
--    SALESORDER.CREATIONDATETIME AS CREATIONDATETIME_SALESORDER,
--    SALESORDER.CREATIONUSER AS CREATIONUSER_SALESORDER,
--    CASE
--        WHEN a8.VALUESTRING IS NOT NULL THEN 'KK TAS'
--        ELSE a8.VALUESTRING
--    END AS KARTUKERJA,
    PRODUCTIONDEMAND.RESERVATIONORDERCODE AS DEMAND_KNT_by_YND
--    CASE
--    	WHEN a11.VALUESTRING = '1' THEN 'BODY'
--    	WHEN a11.VALUESTRING = '2' THEN 'KRAH'
--    END AS UNTUK_PEMAKAIAN,
--    a12.VALUESTRING AS KELIPATAN_RAJUT,
--    a13.VALUEINT AS QTY_PERMINTAAN_BUYER,
--    a14.VALUEDATE AS DATE_AKTUAL,
--    a15.VALUEDATE AS DATE_AKTUAL2,
--    a16.VALUEDATE AS DATE_AKTUAL3,
--    a17.VALUEDATE AS DATE_AKTUAL4,
--    a18.VALUEDATE AS DATE_AKTUAL5,
--    CASE
--        WHEN a19.VALUESTRING = '1' THEN 'AKJ'
--        ELSE 'NON AKJ'
--    END AS AKJ,
--    a20.VALUESTRING AS NoteTas
FROM
    PRODUCTIONDEMAND PRODUCTIONDEMAND
LEFT JOIN (
    SELECT
        DISTINCT PRODUCTIONDEMANDCODE,
        PRODUCTIONORDERCODE
    FROM
        PRODUCTIONDEMANDSTEP PRODUCTIONDEMANDSTEP) PRODUCTIONDEMANDSTEP ON PRODUCTIONDEMAND.CODE = PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE
--LEFT JOIN SALESORDER SALESORDER ON PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE = SALESORDER.CODE
--LEFT JOIN ORDERPARTNER ORDERPARTNER ON PRODUCTIONDEMAND.CUSTOMERCODE = ORDERPARTNER.CUSTOMERSUPPLIERCODE
--LEFT JOIN BUSINESSPARTNER BUSINESSPARTNER ON BUSINESSPARTNER.NUMBERID = ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID
--LEFT JOIN ADDRESS a ON a.CODE = SALESORDER.DELIVERYPOINTCODE AND a.UNIQUEID = SALESORDER.DELIVERYPOINTUNIQUEID
--LEFT JOIN SALESORDERLINE SALESORDERLINE ON SALESORDERLINE.SALESORDERCODE = SALESORDER.CODE AND SALESORDERLINE.ORDERLINE = PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE
--LEFT JOIN SALESORDERDELIVERY SALESORDERDELIVERY ON SALESORDERDELIVERY.SALESORDERLINESALESORDERCODE = PRODUCTIONDEMAND.DLVSALORDERLINESALESORDERCODE
--    AND SALESORDERDELIVERY.SALESORDERLINEORDERLINE = PRODUCTIONDEMAND.DLVSALESORDERLINEORDERLINE
--RIGHT JOIN PRODUCTIONORDER PRODUCTIONORDER ON PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE = PRODUCTIONORDER.CODE
--LEFT JOIN PRODUCT PRODUCT ON PRODUCT.ITEMTYPECODE = PRODUCTIONDEMAND.ITEMTYPEAFICODE
--    AND PRODUCT.SUBCODE01 = PRODUCTIONDEMAND.SUBCODE01
--    AND PRODUCT.SUBCODE02 = PRODUCTIONDEMAND.SUBCODE02
--    AND PRODUCT.SUBCODE03 = PRODUCTIONDEMAND.SUBCODE03
--    AND PRODUCT.SUBCODE04 = PRODUCTIONDEMAND.SUBCODE04
--    AND PRODUCT.SUBCODE05 = PRODUCTIONDEMAND.SUBCODE05
--    AND PRODUCT.SUBCODE06 = PRODUCTIONDEMAND.SUBCODE06
--    AND PRODUCT.SUBCODE07 = PRODUCTIONDEMAND.SUBCODE07
--    AND PRODUCT.SUBCODE08 = PRODUCTIONDEMAND.SUBCODE08
--    AND PRODUCT.SUBCODE09 = PRODUCTIONDEMAND.SUBCODE09
--    AND PRODUCT.SUBCODE10 = PRODUCTIONDEMAND.SUBCODE10
--LEFT JOIN ITXVIEWCOLOR i ON i.ITEMTYPECODE = PRODUCTIONDEMAND.ITEMTYPEAFICODE
--    AND i.SUBCODE01 = PRODUCTIONDEMAND.SUBCODE01
--    AND i.SUBCODE02 = PRODUCTIONDEMAND.SUBCODE02
--    AND i.SUBCODE03 = PRODUCTIONDEMAND.SUBCODE03
--    AND i.SUBCODE04 = PRODUCTIONDEMAND.SUBCODE04
--    AND i.SUBCODE05 = PRODUCTIONDEMAND.SUBCODE05
--    AND i.SUBCODE06 = PRODUCTIONDEMAND.SUBCODE06
--    AND i.SUBCODE07 = PRODUCTIONDEMAND.SUBCODE07
--    AND i.SUBCODE08 = PRODUCTIONDEMAND.SUBCODE08
--    AND i.SUBCODE09 = PRODUCTIONDEMAND.SUBCODE09
--    AND i.SUBCODE10 = PRODUCTIONDEMAND.SUBCODE10
--LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a2.FIELDNAME = 'ProAllow'
--LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a3.FIELDNAME = 'ProAllow2'
--LEFT JOIN ADSTORAGE a4 ON a4.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a4.FIELDNAME = 'ProAllow3'
--LEFT JOIN ADSTORAGE a5 ON a5.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a5.FIELDNAME = 'ProAllow4'
--LEFT JOIN ADSTORAGE a6 ON a6.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a6.FIELDNAME = 'ProAllow5'
--LEFT JOIN ADSTORAGE a7 ON a7.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a7.FIELDNAME = 'OriginalPDCode'
--LEFT JOIN ADSTORAGE a8 ON a8.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a8.FIELDNAME = 'NoTrackingDev'
--LEFT JOIN ADSTORAGE a9 ON a9.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a9.FIELDNAME = 'BagianCode'
--LEFT JOIN ADSTORAGE a10 ON a10.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a10.FIELDNAME = 'DefectNote'
--LEFT JOIN DEPARTMENT dept ON dept.CODE = a9.VALUESTRING
--LEFT JOIN ORDERITEMORDERPARTNERLINK o ON o.INACTIVE = 0
--	AND o.ORDPRNCUSTOMERSUPPLIERCODE = SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE
--    AND o.ITEMTYPEAFICODE = PRODUCTIONDEMAND.ITEMTYPEAFICODE
--    AND o.SUBCODE01 = PRODUCTIONDEMAND.SUBCODE01
--    AND o.SUBCODE02 = PRODUCTIONDEMAND.SUBCODE02
--    AND o.SUBCODE03 = PRODUCTIONDEMAND.SUBCODE03
--    AND o.SUBCODE04 = PRODUCTIONDEMAND.SUBCODE04
--    AND o.SUBCODE05 = PRODUCTIONDEMAND.SUBCODE05
--    AND o.SUBCODE06 = PRODUCTIONDEMAND.SUBCODE06
--    AND o.SUBCODE07 = PRODUCTIONDEMAND.SUBCODE07
--    AND o.SUBCODE08 = PRODUCTIONDEMAND.SUBCODE08
--    AND o.SUBCODE09 = PRODUCTIONDEMAND.SUBCODE09
--    AND o.SUBCODE10 = PRODUCTIONDEMAND.SUBCODE10
--LEFT JOIN ADSTORAGE a11 ON a11.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a11.FIELDNAME = 'UntukItem'
--LEFT JOIN ADSTORAGE a12 ON a12.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a12.FIELDNAME = 'KelipatanRajut'
--LEFT JOIN ADSTORAGE a13 ON a13.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a13.FIELDNAME = 'QTYPermintaanRMP'
--LEFT JOIN ADSTORAGE a14 ON a14.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a14.FIELDNAME = 'ProAllowDate'
--LEFT JOIN ADSTORAGE a15 ON a15.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a15.FIELDNAME = 'ProAllowDate2'
--LEFT JOIN ADSTORAGE a16 ON a16.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a16.FIELDNAME = 'ProAllowDate3'
--LEFT JOIN ADSTORAGE a17 ON a17.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a17.FIELDNAME = 'ProAllowDate4'
--LEFT JOIN ADSTORAGE a18 ON a18.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a18.FIELDNAME = 'ProAllowDate5'
--LEFT JOIN ADSTORAGE a19 ON a19.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND a19.FIELDNAME = 'KainAKJ'
--LEFT JOIN ADSTORAGE a20 ON a20.UNIQUEID = PRODUCT.ABSUNIQUEID AND a20.FIELDNAME = 'NoteTas'
--LEFT JOIN ADSTORAGE a21 ON a21.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a21.FIELDNAME = 'ProAllowQty'
--LEFT JOIN ADSTORAGE a22 ON a22.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a22.FIELDNAME = 'ProAllowQty2'
--LEFT JOIN ADSTORAGE a23 ON a23.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a23.FIELDNAME = 'ProAllowQty3'
--LEFT JOIN ADSTORAGE a24 ON a24.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a24.FIELDNAME = 'ProAllowQty4'
--LEFT JOIN ADSTORAGE a25 ON a25.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a25.FIELDNAME = 'ProAllowQty5'
--LEFT JOIN ADSTORAGE a26 ON a26.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a26.FIELDNAME = 'LegacyOrder'
--LEFT JOIN PRODUCTIONRESERVATION p ON p.ORDERCODE = PRODUCTIONDEMAND.CODE AND (p.ITEMTYPEAFICODE ='KGF' OR p.ITEMTYPEAFICODE = 'KFF')
--WHERE
--	PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE = '00072837'