DROP VIEW ITXVIEW_TERMOFSHIPPING_SM_GKJ;
--CREATE VIEW ITXVIEW_TERMOFSHIPPING_SM_GKJ AS
SELECT
    DISTINCT 
	s.CODE,
    s.COUNTERCODE,
--    s4.DELIVERYPOINTCODE,
    s.DELIVERYPOINTCODE,
    s.DELIVERYPOINTUNIQUEID,
    s.EXTERNALREFERENCE,
    s.INTERNALREFERENCE,
    s.ORDPRNCUSTOMERSUPPLIERCODE,
    s.STATISTICALGROUPCODE,
    s.TERMSOFSHIPPINGCODE AS TERMSOFSHIPPINGCODE_salesorder,
    s3.TERMSOFSHIPPINGCODE AS TERMSOFSHIPPINGCODE_salesrelease
FROM
    SALESORDER s
LEFT JOIN SALESORDERLINE s2 ON
    s.code = s2.SALESORDERCODE
    AND s.COMPANYCODE = s2.SALESORDERCOMPANYCODE
    AND s.COUNTERCODE = s2.SALESORDERCOUNTERCODE
LEFT JOIN SALESRELEASELINE s3 ON
    s2.SALESORDERCODE = s3.DLVSALORDERLINESALESORDERCODE
    AND s3.DLVSALESORDERLINEORDERLINE = s3.DLVSALESORDERLINEORDERLINE
LEFT JOIN SALESDOCUMENT s4 ON s4.PROJECTCODE = s.CODE
WHERE
    s3.TERMSOFSHIPPINGCODE = 'AI';