DROP VIEW ITXVIEW_POSISIKK_TGL_IN_PRODDEMAND;
CREATE VIEW ITXVIEW_POSISIKK_TGL_IN_PRODDEMAND AS
SELECT 
	p.DEMANDSTEPPRODUCTIONDEMANDCODE,
    p.PROPROGRESSPROGRESSNUMBER,
    p.DEMANDSTEPSTEPNUMBER,
    LISTAGG(p2.PROGRESSSTARTPROCESSDATE || ' ' || PROGRESSSTARTPROCESSTIME , ',') AS MULAI
FROM PRODUCTIONPROGRESSSTEPUPDATED p
RIGHT JOIN PRODUCTIONPROGRESS p2 ON p2.PROGRESSNUMBER = p.PROPROGRESSPROGRESSNUMBER AND p2.PROGRESSTEMPLATECODE = 'S01'
--WHERE p.DEMANDSTEPPRODUCTIONDEMANDCODE = '$rowdb2[PRODUCTIONDEMANDCODE]' AND p.DEMANDSTEPSTEPNUMBER = '$rowdb2[STEPNUMBER]'
GROUP BY 
	p.DEMANDSTEPPRODUCTIONDEMANDCODE,
    p.PROPROGRESSPROGRESSNUMBER,
    p.DEMANDSTEPSTEPNUMBER