DROP VIEW ITXVIEW_PPA_DIT_HISTORY;
--CREATE VIEW ITXVIEW_PPA_DIT_HISTORY AS 
SELECT
	p.IDENTIFIEDDATE,
	p.PMBOMCODE,
	p.CREATIONDATETIME AS TGL_BUAT_BD,
	p.CODE AS NO_BD,  
    p2.LONGDESCRIPTION AS NAMA_APLIKASI,
    CASE
        WHEN a2.VALUESTRING = '1' THEN 'Baru'
        WHEN a2.VALUESTRING = '2' THEN 'Penambahan'
        WHEN a2.VALUESTRING = '3' THEN 'Perubahan'
        WHEN a2.VALUESTRING = '4' THEN 'Perbaikan'
    END AS JENIS_PERMOHONAN,
    p.SYMPTOM AS DESKRIPSI_PEMOHON,
    p.CREATIONUSER AS DIBUAT_OLEH,
    a4.MENUDESCR AS JABATAN_DIBUATOLEH,
    SUBSTR(p.CREATIONDATETIME, 1,10)  AS TGL_DIBUATOLEH
FROM
    PMBREAKDOWNENTRY p
LEFT JOIN PMBOM p2 ON p2.CODE = p.PMBOMCODE
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = p.ABSUNIQUEID AND a2.FIELDNAME = 'JenisPermohonan'
LEFT JOIN ABSUIINITIALMENU a3 ON a3.USERUSERID = p.CREATIONUSER
LEFT JOIN ABSUIMENU a4 ON a4.CODE = a3.MENU4CODE
WHERE
    p.BREAKDOWNTYPE = 'SF'
    AND p.PMBOMCODE = 'DITONLINE000204'