DROP VIEW ITXVIEW_PACKINGLIST_PPC;
--CREATE VIEW ITXVIEW_PACKINGLIST_PPC AS
SELECT
    DISTINCT 
    BUSINESSPARTNER.LEGALNAME1,
    ALLOCATION.CODE,
    ALLOCATION.PROJECTCODE,
    SALESDOCUMENTLINE.DLVSALESORDERLINEORDERLINE,
    ALLOCATION.THEORETICISSUEDATE,
    ALLOCATION.DECOSUBCODE01,
    ALLOCATION.DECOSUBCODE02,
    ALLOCATION.DECOSUBCODE03,
    ALLOCATION.DECOSUBCODE04,
    ALLOCATION.DECOSUBCODE05,
    ALLOCATION.DECOSUBCODE06,
    ALLOCATION.DECOSUBCODE07,
    ALLOCATION.DECOSUBCODE08,
    ALLOCATION.DECOSUBCODE09,
    ALLOCATION.DECOSUBCODE10,
    ALLOCATION.LOTCODE,
    ALLOCATION.BASESECONDARYUOMCODE,
    SALESDOCUMENT.PROVISIONALCODE,
    SALESDOCUMENT.PROVISIONALDOCUMENTDATE,
    SALESDOCUMENT.ORDPRNCUSTOMERSUPPLIERCODE,
    SALESDOCUMENT.ORDERPARTNERBRANDCODE,
    SALESDOCUMENT.GOODSISSUEDATE,
    CASE
        WHEN SALESDOCUMENT.EXTERNALREFERENCE IS NULL THEN SALESDOCUMENTLINE.EXTERNALREFERENCE
        ELSE SALESDOCUMENT.EXTERNALREFERENCE
    END AS PO_NUMBER,
    SALESDOCUMENTLINE.ITEMTYPEAFICODE,
    SALESDOCUMENTLINE.SUBCODE01,
    SALESDOCUMENTLINE.SUBCODE02,
    SALESDOCUMENTLINE.SUBCODE03,
    SALESDOCUMENTLINE.SUBCODE04,
    SALESDOCUMENTLINE.SUBCODE05,
    SALESDOCUMENTLINE.SUBCODE06,
    SALESDOCUMENTLINE.SUBCODE07,
    SALESDOCUMENTLINE.SUBCODE08,
    SALESDOCUMENTLINE.SUBCODE09,
    SALESDOCUMENTLINE.SUBCODE10,
    SALESDOCUMENTLINE.ITEMDESCRIPTION,
    SALESDOCUMENTLINE.PREVIOUSCODE,
    SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE,
    ORDERPARTNERBRAND.LONGDESCRIPTION
FROM
    DB2ADMIN.ALLOCATION ALLOCATION
LEFT OUTER JOIN CUSTOMERSUPPLIERDATA CUSTOMERSUPPLIERDATA ON
    CUSTOMERSUPPLIERDATA.CODE = ALLOCATION.CUSTOMERCODE
LEFT OUTER JOIN BUSINESSPARTNER BUSINESSPARTNER ON
    BUSINESSPARTNER.NUMBERID = CUSTOMERSUPPLIERDATA.BUSINESSPARTNERNUMBERID
RIGHT OUTER JOIN DB2ADMIN.WRKDOCUMENTPRINT WRKDOCUMENTPRINT ON
    ALLOCATION.ORDERCODE = WRKDOCUMENTPRINT.SALESDOCUMENTPROVISIONALCODE
LEFT OUTER JOIN DB2ADMIN.SALESDOCUMENT SALESDOCUMENT ON
    ALLOCATION.ORDERCODE = SALESDOCUMENT.PROVISIONALCODE
LEFT OUTER JOIN DB2ADMIN.SALESDOCUMENTLINE SALESDOCUMENTLINE ON
    SALESDOCUMENT.PROVISIONALCODE = SALESDOCUMENTLINE.SALESDOCUMENTPROVISIONALCODE
    AND ALLOCATION.ITEMTYPECODE = SALESDOCUMENTLINE.ITEMTYPEAFICODE
    AND ALLOCATION.DECOSUBCODE01 = SALESDOCUMENTLINE.SUBCODE01
    AND ALLOCATION.DECOSUBCODE02 = SALESDOCUMENTLINE.SUBCODE02
    AND ALLOCATION.DECOSUBCODE03 = SALESDOCUMENTLINE.SUBCODE03
    AND ALLOCATION.DECOSUBCODE04 = SALESDOCUMENTLINE.SUBCODE04
    AND ALLOCATION.DECOSUBCODE05 = SALESDOCUMENTLINE.SUBCODE05
    AND ALLOCATION.DECOSUBCODE06 = SALESDOCUMENTLINE.SUBCODE06
    AND ALLOCATION.DECOSUBCODE07 = SALESDOCUMENTLINE.SUBCODE07
    AND ALLOCATION.DECOSUBCODE08 = SALESDOCUMENTLINE.SUBCODE08
    AND ALLOCATION.DECOSUBCODE09 = SALESDOCUMENTLINE.SUBCODE09
    AND ALLOCATION.DECOSUBCODE10 = SALESDOCUMENTLINE.SUBCODE10
    AND ALLOCATION.ORDERLINE = SALESDOCUMENTLINE.ORDERLINE
LEFT OUTER JOIN DB2ADMIN.ORDERPARTNERBRAND ORDERPARTNERBRAND ON
    SALESDOCUMENT.ORDERPARTNERBRANDCODE = ORDERPARTNERBRAND.CODE
    AND SALESDOCUMENT.ORDPRNCUSTOMERSUPPLIERCODE = ORDERPARTNERBRAND.ORDPRNCUSTOMERSUPPLIERCODE
WHERE
    ALLOCATION.ORIGINTRNTRANSACTIONNUMBER IS NULL;