DROP VIEW ITXVIEWBONORDERYND;
--CREATE VIEW ITXVIEWBONORDERYND AS 
SELECT
    PRODUCTIONDEMAND.CODE,
    PRODUCTIONDEMAND.ITEMTYPEAFICODE,
    PRODUCTIONDEMAND.SUBCODE01,
    PRODUCTIONDEMAND.SUBCODE02,
    PRODUCTIONDEMAND.SUBCODE03,
    PRODUCTIONDEMAND.SUBCODE04,
    PRODUCTIONDEMAND.SUBCODE05,
    PRODUCTIONDEMAND.SUBCODE06,
    PRODUCTIONDEMAND.SUBCODE07,
    PRODUCTIONDEMAND.SUBCODE08,
    PRODUCTIONDEMAND.SUBCODE09,
    PRODUCTIONDEMAND.SUBCODE10,
    PRODUCTIONDEMAND.RESERVATIONORDERCODE,
    PRODUCTIONDEMAND.ORDERDATE,
    PRODUCTIONDEMAND.FINALPLANNEDDATE,
    PRODUCTIONDEMAND.USERPRIMARYQUANTITY,
    PRODUCTIONDEMAND.USERPRIMARYUOMCODE,
    BUSINESSPARTNER.LEGALNAME1 AS LANGGANAN,
    ORDERPARTNERBRAND.LONGDESCRIPTION AS BUYER,
    USERGENERICGROUP.LONGDESCRIPTION,
    SALESORDER.CREATIONUSER,
    A.SUMMARIZEDDESCRIPTION,
    A.USERPRIMARYQUANTITY AS QTY_RESERV
FROM
    PRODUCTIONDEMAND PRODUCTIONDEMAND
LEFT JOIN ORDERPARTNER ORDERPARTNER ON
    PRODUCTIONDEMAND.CUSTOMERCODE = ORDERPARTNER.CUSTOMERSUPPLIERCODE
LEFT JOIN BUSINESSPARTNER BUSINESSPARTNER ON
    ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID = BUSINESSPARTNER.NUMBERID
LEFT JOIN SALESORDER SALESORDER ON
    PRODUCTIONDEMAND.PROJECTCODE = SALESORDER.CODE
LEFT JOIN SALESORDERLINE SALESORDERLINE ON
    SALESORDER.CODE = SALESORDERLINE.SALESORDERCODE
LEFT JOIN ORDERPARTNERBRAND ORDERPARTNERBRAND ON
    SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE = ORDERPARTNERBRAND.ORDPRNCUSTOMERSUPPLIERCODE
    AND 
SALESORDER.ORDERPARTNERBRANDCODE = ORDERPARTNERBRAND.CODE
LEFT JOIN USERGENERICGROUP USERGENERICGROUP ON
    PRODUCTIONDEMAND.SUBCODE08 = USERGENERICGROUP.CODE
LEFT JOIN (
    SELECT
        PRODUCTIONRESERVATION.ORDERCODE,
        PRODUCTIONRESERVATION.ITEMTYPEAFICODE,
        PRODUCTIONRESERVATION.SUBCODE01,
        PRODUCTIONRESERVATION.SUBCODE02,
        PRODUCTIONRESERVATION.SUBCODE03,
        PRODUCTIONRESERVATION.SUBCODE04,
        PRODUCTIONRESERVATION.SUBCODE05,
        PRODUCTIONRESERVATION.USERPRIMARYQUANTITY,
        PRODUCTIONRESERVATION.USERPRIMARYUOMCODE,
        FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION
    FROM
        PRODUCTIONRESERVATION PRODUCTIONRESERVATION
    LEFT JOIN FULLITEMKEYDECODER FULLITEMKEYDECODER ON
        PRODUCTIONRESERVATION.FULLITEMIDENTIFIER = FULLITEMKEYDECODER.IDENTIFIER
    WHERE
        PRODUCTIONRESERVATION.ITEMTYPEAFICODE = 'GYR' OR PRODUCTIONRESERVATION.ITEMTYPEAFICODE = 'DYR'
) A ON
    PRODUCTIONDEMAND.CODE = A.ORDERCODE
GROUP BY
    PRODUCTIONDEMAND.CODE,
    PRODUCTIONDEMAND.ITEMTYPEAFICODE,
    PRODUCTIONDEMAND.SUBCODE01,
    PRODUCTIONDEMAND.SUBCODE02,
    PRODUCTIONDEMAND.SUBCODE03,
    PRODUCTIONDEMAND.SUBCODE04,
    PRODUCTIONDEMAND.SUBCODE05,
    PRODUCTIONDEMAND.SUBCODE06,
    PRODUCTIONDEMAND.SUBCODE07,
    PRODUCTIONDEMAND.SUBCODE08,
    PRODUCTIONDEMAND.SUBCODE09,
    PRODUCTIONDEMAND.SUBCODE10,
    PRODUCTIONDEMAND.RESERVATIONORDERCODE,
    PRODUCTIONDEMAND.ORDERDATE,
    PRODUCTIONDEMAND.FINALPLANNEDDATE,
    PRODUCTIONDEMAND.USERPRIMARYQUANTITY,
    PRODUCTIONDEMAND.USERPRIMARYUOMCODE,
    BUSINESSPARTNER.LEGALNAME1,
    ORDERPARTNERBRAND.LONGDESCRIPTION,
    USERGENERICGROUP.LONGDESCRIPTION,
    A.SUMMARIZEDDESCRIPTION,
    A.USERPRIMARYQUANTITY,
    SALESORDER.CREATIONUSER;