-- DB2ADMIN.ITXVIEW_INVOICE_SURATJALAN3 source
DROP VIEW ITXVIEW_INVOICE_SURATJALAN3;
--CREATE VIEW ITXVIEW_INVOICE_SURATJALAN3 AS
SELECT
    DISTINCT
    ITEMTYPECODE,
--    LOTCODE,
    Invoice,
    NO_SJ,
    tgl_inv,
    issue_date,
    tanggal_inv,
    tgl_create,
    tgl_buat,
    DUE,
    DATEKB,
    DUEKB,
    curr,
    JENIS_ORDER,
    kode_bep,
    id_bep,
    nama_bep,
    kode_cus,
    nama_cus,
    NPWP,
    FAKTUR_PAJAK,
    NO_ORDER,
    NO_PO,
    NO_CI,
    DESC_KAIN,
    PPN,
    code_payment,
    payment_terms,
    unit,
    rate,
    biaya_tambahan,
    price_usd,
    price_idr,
    sum(BERAT) AS BERAT,
    SUM(BERAT_LAIN) AS BERAT_LAIN,
    CASE
        WHEN trim(ORDERCURRENCYCODE) = 'USD' THEN CASE
            WHEN trim(unit) = 'kg' THEN round(SUM(BERAT) * round(PRICE_USD, 2), 2)
            WHEN trim(unit) = 'yd' THEN round(SUM(BERAT_LAIN) * round(PRICE_USD, 2), 2)
            WHEN trim(unit) = 'm' THEN round(SUM(BERAT_LAIN) * round(PRICE_USD, 2), 2)
            WHEN trim(unit) IN (
                'un', 'Lot'
            ) THEN round(SUM(BERAT_LAIN) * round(PRICE_USD, 2), 2)
        END
        WHEN trim(ORDERCURRENCYCODE) = 'IDR' THEN CASE
            WHEN trim(unit) = 'kg' THEN floor(SUM(BERAT) * round(price_idr, 2))
            WHEN trim(unit) = 'yd' THEN floor(SUM(BERAT_LAIN) * round(price_idr, 2))
            WHEN trim(unit) = 'm' THEN floor(SUM(BERAT_LAIN) * round(price_idr, 2))
            WHEN trim(unit) IN (
                'un', 'Lot'
            )
            AND Invoice = 'CA23120001' THEN floor(SUM(BERAT_LAIN) * round(price_idr, 2))
            WHEN trim(unit) IN (
                'un', 'Lot'
            ) THEN floor(SUM(BERAT_LAIN) * round(price_idr, 2))
        END
    END AS JUMLAH_HARGA,
    CASE
        WHEN trim(ORDERCURRENCYCODE) = 'USD' THEN CASE
            WHEN trim(unit) = 'kg' THEN round( SUM(BERAT) * round( PRICE_USD, 2 ), 2 )
            WHEN trim(unit) = 'yd' THEN round( SUM(BERAT_LAIN) * round(PRICE_USD, 2 ), 2 )
            WHEN trim(unit) = 'm' THEN round( SUM(BERAT_LAIN) * round(PRICE_USD, 2 ), 2 )
            WHEN trim(unit) IN (
                'un', 'Lot'
            ) THEN round( SUM(BERAT_LAIN) * round(PRICE_USD, 2 ), 2 )
        END
        ELSE 0
    END AS TOTAL_USD,
    CASE
        WHEN trim(ORDERCURRENCYCODE) = 'IDR' THEN CASE
            WHEN trim(unit) = 'kg' THEN floor(round(SUM(BERAT) * round( price, 2 ), 2))
            WHEN trim(unit) = 'yd' THEN floor(round(SUM(BERAT_LAIN) * round( price, 2 ), 2))
            WHEN trim(unit) = 'm' THEN floor(round(SUM(BERAT_LAIN) * round( price, 2 ), 2))
            WHEN trim(unit) IN (
                'un', 'Lot'
            )
            AND Invoice = 'CA23120001' THEN floor(round(SUM(BERAT_LAIN) * round( price, 2 ), 2))
            WHEN trim(unit) IN (
                'un', 'Lot'
            ) THEN floor(round(SUM(BERAT_LAIN) * round( price, 2 ), 2))
        END
        ELSE CASE
            WHEN trim(unit) = 'kg' THEN floor(round( SUM(BERAT) * round( PRICE_USD, 2 ), 2 )* rate)
            WHEN trim(unit) = 'yd' THEN floor(round( SUM(BERAT_LAIN) * round(PRICE_USD, 2 ), 2 )* rate)
            WHEN trim(unit) = 'm' THEN floor(round( SUM(BERAT_LAIN) * round(PRICE_USD, 2 ), 2 )* rate)
            WHEN trim(unit) IN (
                'un', 'Lot'
            ) THEN floor(round( SUM(BERAT_LAIN) * round(PRICE_USD, 2 ), 2 )* rate)
        END
    END AS TOTAL_IDR,
    harga_satuan,
    KODE_JK,
    ITEMDESCRIPTION,
    WARNA
FROM
    (
        SELECT
            DISTINCT 
            ITXVIEW_ALLOCATION_2.ITEMTYPECODE,
        	ITXVIEW_ALLOCATION_2.LOTCODE,
            ITXVIEW_ALLOCATION_2.DECOSUBCODE04,
            trim(PLANTINVOICE.CODE) AS Invoice,
            SALESDOCUMENTLINE.PREVIOUSCODE AS NO_SJ,
            SALESDOCUMENT2.PROVISIONALDOCUMENTDATE AS tgl_inv,
            SALESDOCUMENT2.GOODSISSUEDATE AS issue_date,
            PLANTINVOICE.INVOICEDATE AS tgl_buat,
            CASE
                WHEN trim(SALESDOCUMENT2.PROVISIONALDOCUMENTDATE) <= DATE('2022-08-15') THEN CASE
                    WHEN trim(SALESDOCUMENT2.GOODSISSUEDATE) IS NOT NULL THEN trim(SALESDOCUMENT2.GOODSISSUEDATE)
                    ELSE trim(SALESDOCUMENT2.PROVISIONALDOCUMENTDATE)
                END
                ELSE trim(SALESDOCUMENT2.GOODSISSUEDATE)
            END AS tanggal_inv,
            PLANTINVOICE.CREATIONDATE AS tgl_create,
            CASE
                WHEN trim(SALESDOCUMENT2.PROVISIONALDOCUMENTDATE) <= DATE('2022-08-15') THEN CASE
                    WHEN trim(SALESDOCUMENT2.GOODSISSUEDATE) IS NOT NULL THEN SALESDOCUMENT2.GOODSISSUEDATE + PAYMENTMETHODIE.NOOFDAYS
                    ELSE SALESDOCUMENT2.PROVISIONALDOCUMENTDATE + PAYMENTMETHODIE.NOOFDAYS
                END
                ELSE SALESDOCUMENT2.GOODSISSUEDATE + PAYMENTMETHODIE.NOOFDAYS
            END AS DUE,
            PLANTINVOICE.CHALLANDATE AS DATEKB,
            PLANTINVOICE.LRDATE AS DUEKB,
            trim(PLANTINVOICE.ORDERCURRENCYCODE) AS curr,
            trim(SALESORDER.COUNTERCODE) AS JENIS_ORDER,
            trim(SALESORDER.FNCORDPRNCUSTOMERSUPPLIERCODE) AS kode_bep,
            BUSINESSPARTNER.NUMBERID AS id_bep,
            BUSINESSPARTNER.LEGALNAME1 AS nama_bep,
            CASE
                WHEN ADDRESS.CODE IS NULL THEN 'Warning! Kolom Address Code Sales Order Kosong. USER: ' || TRIM(SALESORDER.CREATIONUSER)
                ELSE ADDRESS.CODE
            END AS kode_cus,
            CASE
                WHEN trim(ADDRESS.ADDRESSEE) IS NULL THEN 'Warning! Kolom Address Code Sales Order Kosong. USER: ' || TRIM(SALESORDER.CREATIONUSER)
                ELSE trim(ADDRESS.ADDRESSEE)
            END AS nama_cus,
            CASE
                WHEN PLANTINVOICE.BLNUMBER IS NOT NULL THEN CASE
                    WHEN trim(ADDRESS.ADDRESSLINE4) IS NULL THEN 'Warning! Kolom Address Code Sales Order Kosong. USER: ' || TRIM(SALESORDER.CREATIONUSER)
                    ELSE trim(ADDRESS.ADDRESSLINE4)
                END
                ELSE CASE
                    WHEN trim(ADDRESS.ADDRESSLINE4) IS NULL THEN 'Warning! Kolom Address Code Sales Order Kosong. USER: ' || TRIM(SALESORDER.CREATIONUSER)
                    ELSE trim(ADDRESS.ADDRESSLINE4)
                END
            END AS NPWP,
            CASE
                WHEN PLANTINVOICE.BLNUMBER IS NULL THEN 'Warning! Kolom faktur pajak Invoice Kosong. USER : ' || TRIM(PLANTINVOICE.CREATIONUSER)
                ELSE PLANTINVOICE.BLNUMBER
            END AS FAKTUR_PAJAK,
            trim(PLANTINVOICE.CONTRACTNOCODE) AS NO_ORDER,
            PLANTINVOICE.STATUS AS NO_CI,
            REPLACE(ITXVIEW_PO_INVOICE2.NO_PO, '''', ' ') AS NO_PO,
            CASE
                WHEN trim(SALESORDER.TEMPLATECODE) LIKE '%CWD%' THEN trim(SALESORDER.DESCRIPTION)
                ELSE '-'
            END AS DESC_KAIN,
            PLANTINVOICELINE.TAXTEMPLATECODE AS PPN,
            trim(PAYMENTMETHOD.LONGDESCRIPTION) AS code_payment,
            CASE
                WHEN trim(PAYMENTMETHODIE.NOOFDAYS) = 0 THEN trim(PAYMENTMETHOD.LONGDESCRIPTION)
                ELSE trim(PAYMENTMETHODIE.NOOFDAYS)
            END AS payment_terms,
            trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) AS unit,
            PLANTINVOICE.EXCHANGERATEOFCONTRACT AS rate,
            CASE
                WHEN PLANTINVOICE.ORDERCURRENCYCODE = 'USD' THEN ITXVIEW_ALLOCATION_2.price
                ELSE 0
            END AS PRICE_USD,
            CASE
                WHEN PLANTINVOICE.ORDERCURRENCYCODE = 'IDR' THEN ITXVIEW_ALLOCATION_2.price
                ELSE floor( ITXVIEW_ALLOCATION_2.price * PLANTINVOICE.EXCHANGERATEOFCONTRACT )
            END AS PRICE_IDR,
            ITXVIEW_ALLOCATION_2.price AS price,
            CASE
                WHEN (ITXVIEW_INVOICE_BIAYATAMBAHAN2.biaya_tambahan) IS NULL THEN 0
                ELSE (ITXVIEW_INVOICE_BIAYATAMBAHAN2.biaya_tambahan)
            END AS biaya_tambahan,
            round(ITXVIEW_ALLOCATION_2.USERPRIMARYQUANTITY, 2)AS BERAT,
            CASE
                WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'yd' THEN SUM(round(ITXVIEW_ALLOCATION_2.USERSECONDARYQUANTITY, 2))
                WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'm' THEN SUM(round(ITXVIEW_ALLOCATION_2.BASESECONDARYQUANTITY, 2))
                WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) IN (
                    'un', 'Lot'
                ) THEN SUM(round(ITXVIEW_ALLOCATION_2.QTY_PCS, 2))
            END AS BERAT_kg_yd_un,
            CASE
                WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'kg' THEN round(ITXVIEW_ALLOCATION_2.USERSECONDARYQUANTITY, 2)
                WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'yd' THEN round(ITXVIEW_ALLOCATION_2.USERSECONDARYQUANTITY, 2)
                WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'm' THEN round(ITXVIEW_ALLOCATION_2.BASESECONDARYQUANTITY, 2)
                WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) IN (
                    'un', 'Lot'
                ) THEN round(ITXVIEW_ALLOCATION_2.QTY_PCS, 2)
            END AS BERAT_LAIN,
            round(ITXVIEW_ALLOCATION_2.price, 2) AS harga_satuan,
            TRIM(SALESDOCUMENTLINE.EXTERNALITEM) AS KODE_JK,
            trim(PLANTINVOICE.ORDERCURRENCYCODE) AS ORDERCURRENCYCODE,
            CASE
                WHEN PLANTINVOICE.CODE = 'CA23120001' THEN TRIM(SALESDOCUMENTLINE.SUBCODE02) || TRIM(SALESDOCUMENTLINE.SUBCODE03) || ' - ' || PRODUCT.LONGDESCRIPTION || ' ' || RIGHT(SALESORDERLINE.ITEMDESCRIPTION, 12)
                WHEN PRODUCT.LONGDESCRIPTION IS NULL THEN TRIM(SALESDOCUMENTLINE.SUBCODE02) || TRIM(SALESDOCUMENTLINE.SUBCODE03) || ' - ' || SALESDOCUMENTLINE.ITEMDESCRIPTION
                ELSE TRIM(SALESDOCUMENTLINE.SUBCODE02) || TRIM(SALESDOCUMENTLINE.SUBCODE03) || ' - ' || PRODUCT.LONGDESCRIPTION
            END AS ITEMDESCRIPTION,
            i.WARNA
        FROM
            PLANTINVOICE PLANTINVOICE
        LEFT JOIN SALESORDER SALESORDER ON
            PLANTINVOICE.CONTRACTNOCODE = SALESORDER.CODE
        LEFT JOIN SALESDOCUMENT SALESDOCUMENT ON
            PLANTINVOICE.CODE = SALESDOCUMENT.PROVISIONALCODE
        LEFT JOIN PAYMENTMETHOD PAYMENTMETHOD ON
            PLANTINVOICE.TERMSOFPAYMENTCODE = PAYMENTMETHOD.CODE
        LEFT JOIN PAYMENTMETHODIE PAYMENTMETHODIE ON
            PLANTINVOICE.TERMSOFPAYMENTCODE = PAYMENTMETHODIE.CODE
        LEFT JOIN ADDRESS ADDRESS ON
            ADDRESS.UNIQUEID = SALESORDER.PAYMENTCUSTOMERUNIQUEID
            AND ADDRESS.CODE = SALESORDER.PAYMENTCUSTOMERCODE
        LEFT JOIN ORDERPARTNER ORDERPARTNER ON
            ORDERPARTNER.CUSTOMERSUPPLIERCODE = PLANTINVOICE.BUYERIFOTCCUSTOMERSUPPLIERCODE
        LEFT JOIN BUSINESSPARTNER BUSINESSPARTNER ON
            BUSINESSPARTNER.NUMBERID = ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID
        LEFT JOIN SALESDOCUMENTLINE SALESDOCUMENTLINE ON
            SALESDOCUMENTLINE.SALESDOCUMENTPROVISIONALCODE = SALESDOCUMENT.PROVISIONALCODE
        LEFT JOIN PLANTINVOICELINE PLANTINVOICELINE ON
            PLANTINVOICELINE.PLANTINVOICECODE = SALESDOCUMENTLINE.SALESDOCUMENTPROVISIONALCODE
        LEFT JOIN SALESDOCUMENT SALESDOCUMENT2 ON
            SALESDOCUMENT2.PROVISIONALCODE = SALESDOCUMENTLINE.PREVIOUSCODE
        LEFT JOIN SALESORDERLINE SALESORDERLINE ON
            SALESORDERLINE.SALESORDERCODE = SALESORDER.CODE
            AND SALESORDERLINE.ORDERLINE = SALESDOCUMENTLINE.DLVSALESORDERLINEORDERLINE
        LEFT JOIN ITXVIEW_ALLOCATION_2 ITXVIEW_ALLOCATION_2 ON
            SALESDOCUMENTLINE.SUBCODE01 = ITXVIEW_ALLOCATION_2.DECOSUBCODE01
            AND SALESDOCUMENTLINE.SUBCODE02 = ITXVIEW_ALLOCATION_2.DECOSUBCODE02
            AND SALESDOCUMENTLINE.SUBCODE03 = ITXVIEW_ALLOCATION_2.DECOSUBCODE03
            AND SALESDOCUMENTLINE.SUBCODE04 = ITXVIEW_ALLOCATION_2.DECOSUBCODE04
            AND SALESDOCUMENTLINE.SUBCODE05 = ITXVIEW_ALLOCATION_2.DECOSUBCODE05
            AND SALESDOCUMENTLINE.SUBCODE06 = ITXVIEW_ALLOCATION_2.DECOSUBCODE06
            AND SALESDOCUMENTLINE.SUBCODE07 = ITXVIEW_ALLOCATION_2.DECOSUBCODE07
            AND SALESDOCUMENTLINE.SUBCODE08 = ITXVIEW_ALLOCATION_2.DECOSUBCODE08
            AND SALESDOCUMENTLINE.PREVIOUSCODE = ITXVIEW_ALLOCATION_2.SALESDOCUMENTPROVISIONALCODE
        LEFT JOIN ITXVIEW_INVOICE_BIAYATAMBAHAN2 ITXVIEW_INVOICE_BIAYATAMBAHAN2 ON
            PLANTINVOICE.CODE = ITXVIEW_INVOICE_BIAYATAMBAHAN2.no_invoice
        LEFT JOIN PRODUCT PRODUCT ON
            PRODUCT.ITEMTYPECODE = SALESDOCUMENTLINE.ITEMTYPEAFICODE
            AND PRODUCT.SUBCODE01 = SALESDOCUMENTLINE.SUBCODE01
            AND PRODUCT.SUBCODE02 = SALESDOCUMENTLINE.SUBCODE02
            AND PRODUCT.SUBCODE03 = SALESDOCUMENTLINE.SUBCODE03
            AND PRODUCT.SUBCODE04 = SALESDOCUMENTLINE.SUBCODE04
            AND PRODUCT.SUBCODE05 = SALESDOCUMENTLINE.SUBCODE05
            AND PRODUCT.SUBCODE06 = SALESDOCUMENTLINE.SUBCODE06
            AND PRODUCT.SUBCODE07 = SALESDOCUMENTLINE.SUBCODE07
            AND PRODUCT.SUBCODE08 = SALESDOCUMENTLINE.SUBCODE08
            AND PRODUCT.SUBCODE09 = SALESDOCUMENTLINE.SUBCODE09
            AND PRODUCT.SUBCODE10 = SALESDOCUMENTLINE.SUBCODE10
        LEFT JOIN ITXVIEWCOLOR i ON
            i.ITEMTYPECODE = SALESDOCUMENTLINE.ITEMTYPEAFICODE
            AND i.SUBCODE01 = SALESDOCUMENTLINE.SUBCODE01
            AND i.SUBCODE02 = SALESDOCUMENTLINE.SUBCODE02
            AND i.SUBCODE03 = SALESDOCUMENTLINE.SUBCODE03
            AND i.SUBCODE04 = SALESDOCUMENTLINE.SUBCODE04
            AND i.SUBCODE05 = SALESDOCUMENTLINE.SUBCODE05
            AND i.SUBCODE06 = SALESDOCUMENTLINE.SUBCODE06
            AND i.SUBCODE07 = SALESDOCUMENTLINE.SUBCODE07
            AND i.SUBCODE08 = SALESDOCUMENTLINE.SUBCODE08
            AND i.SUBCODE09 = SALESDOCUMENTLINE.SUBCODE09
            AND i.SUBCODE10 = SALESDOCUMENTLINE.SUBCODE10
        LEFT JOIN ITXVIEW_PO_INVOICE2 ITXVIEW_PO_INVOICE2 ON
            ITXVIEW_PO_INVOICE2.NO_INVOICE = PLANTINVOICE.code
        GROUP BY
        	ITXVIEW_ALLOCATION_2.ITEMTYPECODE,
            ITXVIEW_ALLOCATION_2.LOTCODE,
            ITXVIEW_ALLOCATION_2.DECOSUBCODE04,
            PLANTINVOICE.CODE,
            PLANTINVOICE.CHALLANDATE,
            PLANTINVOICE.LRDATE,
            PLANTINVOICE.STATUS,
            SALESORDER.CREATIONUSER,
            PLANTINVOICE.CREATIONUSER,
            SALESDOCUMENTLINE.PREVIOUSCODE,
            SALESDOCUMENTLINE.ITEMTYPEAFICODE,
            SALESDOCUMENT.ORDERPARTNERBRANDCODE,
            SALESORDER.ORDERPARTNERBRANDCODE,
            ITXVIEW_ALLOCATION_2.price,
            ITXVIEW_ALLOCATION_2.ALLOCATIONDATE,
            SALESDOCUMENT2.GOODSISSUEDATE,
            SALESDOCUMENT2.PROVISIONALDOCUMENTDATE,
            SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE,
            PLANTINVOICE.CREATIONDATE,
            PAYMENTMETHOD.LONGDESCRIPTION,
            PAYMENTMETHODIE.CODE,
            PAYMENTMETHODIE.NOOFDAYS,
            PLANTINVOICE.CONTRACTNOCODE,
            ITXVIEW_PO_INVOICE2.NO_PO,
            SALESORDER.FNCORDPRNCUSTOMERSUPPLIERCODE,
            SALESORDER.DESCRIPTION,
            SALESORDER.TEMPLATECODE,
            ADDRESS.ADDRESSEE,
            ADDRESS.TAXREGISTRATIONNUMBER,
            ADDRESS.ADDRESSLINE4,
            PLANTINVOICE.ORDERCURRENCYCODE,
            PLANTINVOICELINE.TAXTEMPLATECODE,
            PLANTINVOICE.EXCHANGERATEOFCONTRACT,
            ITXVIEW_INVOICE_BIAYATAMBAHAN2.biaya_tambahan,
            PLANTINVOICE.BLNUMBER,
            PLANTINVOICE.ORDERCURRENCYCODE,
            PLANTINVOICE.INVOICEDATE,
            SALESORDER.DESCRIPTION,
            SALESORDER.TEMPLATECODE,
            SALESORDER.COUNTERCODE,
            SALESORDERLINE.ITEMDESCRIPTION,
            BUSINESSPARTNER.NUMBERID,
            BUSINESSPARTNER.LEGALNAME1,
            ADDRESS.CODE,
            SALESDOCUMENTLINE.SUBCODE02,
            SALESDOCUMENTLINE.SUBCODE03,
            SALESDOCUMENTLINE.ITEMDESCRIPTION,
            PRODUCT.LONGDESCRIPTION,
            SALESDOCUMENTLINE.EXTERNALITEM,
            i.WARNA,
            ITXVIEW_ALLOCATION_2.USERPRIMARYQUANTITY ,
            ITXVIEW_ALLOCATION_2.USERSECONDARYQUANTITY,
            ITXVIEW_ALLOCATION_2.BASESECONDARYQUANTITY ,
            ITXVIEW_ALLOCATION_2.QTY_PCS
    )
WHERE 
   	NO_SJ = 'PCA2400002'
GROUP BY
	ITEMTYPECODE,
--    LOTCODE,
    DECOSUBCODE04,
    Invoice,
    NO_SJ,
    tgl_inv,
    issue_date,
    tanggal_inv,
    tgl_create,
    tgl_buat,
    DUE,
    DATEKB,
    DUEKB,
    curr,
    JENIS_ORDER,
    kode_bep,
    id_bep,
    nama_bep,
    kode_cus,
    nama_cus,
    NPWP,
    FAKTUR_PAJAK,
    NO_ORDER,
    NO_PO,
    NO_CI,
    DESC_KAIN,
    PPN,
    code_payment,
    payment_terms,
    unit,
    rate,
    price,
    price_usd,
    price_idr,
    biaya_tambahan,
    harga_satuan,
    KODE_JK,
    ITEMDESCRIPTION,
    ORDERCURRENCYCODE,
    WARNA;