DROP VIEW ITXVIEW_DETAIL_QA_DATA;
--CREATE VIEW ITXVIEW_DETAIL_QA_DATA AS
SELECT DISTINCT
	a.VALUEINT,
	PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE,
	PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE,
	PRODUCTIONDEMANDSTEP.WORKCENTERCODE,
	CASE
		WHEN PRODUCTIONDEMANDSTEP.PRODRESERVATIONLINKGROUPCODE IS NULL THEN PRODUCTIONDEMANDSTEP.OPERATIONCODE 
		WHEN TRIM(PRODUCTIONDEMANDSTEP.PRODRESERVATIONLINKGROUPCODE) = '' THEN PRODUCTIONDEMANDSTEP.OPERATIONCODE 
		ELSE PRODUCTIONDEMANDSTEP.PRODRESERVATIONLINKGROUPCODE
	END	AS OPERATIONCODE,
	TRIM(o.LONGDESCRIPTION) AS DESKRIPSI_OPERATION,
	QUALITYDOClINE.LINE,
	QUALITYDOClINE.QUALITYDOCUMENTHEADERNUMBERID,
	QUALITYDOCLINE.QUALITYDOCUMENTHEADERLINE,
	QUALITYDOClINE.CHARACTERISTICCODE,
	QUALITYCHARACTERISTICTYPE.LONGDESCRIPTION,
	CASE
		WHEN QUALITYDOClINE.VALUEQUANTITY IS NULL OR QUALITYDOClINE.VALUEQUANTITY = 0 THEN 0 ELSE 
--		floor ( QUALITYDOClINE.VALUEQUANTITY ) 
		( QUALITYDOClINE.VALUEQUANTITY )
	END AS VALUEQUANTITY
FROM
	QUALITYDOCUMENT QUALITYDOCUMENT
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE ON QUALITYDOCUMENT.HEADERNUMBERID = QUALITYDOCLINE.QUALITYDOCUMENTHEADERNUMBERID 
										AND QUALITYDOCUMENT.HEADERLINE = QUALITYDOCLINE.QUALITYDOCUMENTHEADERLINE
LEFT JOIN QUALITYCHARACTERISTICTYPE QUALITYCHARACTERISTICTYPE ON QUALITYDOClINE.CHARACTERISTICCODE = QUALITYCHARACTERISTICTYPE.CODE 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = QUALITYDOCUMENT.ABSUNIQUEID AND a.FIELDNAME = 'GroupStepNumber'
LEFT JOIN PRODUCTIONDEMANDSTEP PRODUCTIONDEMANDSTEP ON PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE = QUALITYDOCUMENT.PRODUCTIONORDERCODE
--													AND PRODUCTIONDEMANDSTEP.WORKCENTERCODE = QUALITYDOCUMENT.WORKCENTERCODE
													AND PRODUCTIONDEMANDSTEP.OPERATIONCODE = QUALITYDOCUMENT.OPERATIONCODE
													AND 
														CASE
															WHEN TRIM(PRODUCTIONDEMANDSTEP.STEPTYPE) = '0' THEN PRODUCTIONDEMANDSTEP.STEPNUMBER = a.VALUEINT
															ELSE PRODUCTIONDEMANDSTEP.GROUPSTEPNUMBER = a.VALUEINT 
														END
LEFT JOIN OPERATION o ON o.CODE = CASE
									WHEN PRODUCTIONDEMANDSTEP.PRODRESERVATIONLINKGROUPCODE IS NULL THEN PRODUCTIONDEMANDSTEP.OPERATIONCODE 
									WHEN TRIM(PRODUCTIONDEMANDSTEP.PRODRESERVATIONLINKGROUPCODE) = '' THEN PRODUCTIONDEMANDSTEP.OPERATIONCODE 
									ELSE PRODUCTIONDEMANDSTEP.PRODRESERVATIONLINKGROUPCODE
								END	
WHERE
	QUALITYDOCLINE.VALUEQUANTITY IS NOT NULL 
	AND QUALITYDOCLINE.VALUEQUANTITY <> 0 
	AND PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE = '00157044' 
--	AND PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE = '00222903'
	AND PRODUCTIONDEMANDSTEP.OPERATIONCODE = 'BAT2'