--CREATE VIEW ITXVIEWSTOCKKELUARGKIMIA AS
SELECT
	STOCKTRANSACTIONIMPORT.TRANSACTIONNUMBER,
    STOCKTRANSACTIONIMPORT.TRANSACTIONDATE || ' ' || STOCKTRANSACTIONIMPORT.TRANSACTIONTIME AS TRANSACTIONDATE,
    TRIM(PRODUCTIONRESERVATION.PRODUCTIONORDERCODE) || '-' || TRIM(PRODUCTIONRESERVATION.GROUPLINE) AS NO_BONRESEP,
    STOCKTRANSACTIONIMPORT.LOTCODE,
    TRIM(RECIPECOMPONENT.SUBCODE01) || '-' ||
    TRIM(RECIPECOMPONENT.SUBCODE02) || '-' ||
    TRIM(RECIPECOMPONENT.SUBCODE03) AS KODEDYE,
--	ITXVIEWWEIGHTBONRESEP.QTY_BAGIKAIN,
    SUM(STOCKTRANSACTIONIMPORT.USERPRIMARYQUANTITY) AS QTY_AKTUAL
FROM
    PRODUCTIONRESERVATION PRODUCTIONRESERVATION
LEFT JOIN RECIPE RECIPE ON PRODUCTIONRESERVATION.SUBCODE01 = RECIPE.SUBCODE01 AND PRODUCTIONRESERVATION.SUFFIXCODE = RECIPE.SUFFIXCODE
LEFT JOIN RECIPECOMPONENT RECIPECOMPONENT ON RECIPE.NUMBERID = RECIPECOMPONENT.RECIPENUMBERID
LEFT JOIN STOCKTRANSACTIONIMPORT STOCKTRANSACTIONIMPORT ON PRODUCTIONRESERVATION.PRODUCTIONORDERCODE = STOCKTRANSACTIONIMPORT.ORDERCODE
				    AND RECIPECOMPONENT.ITEMTYPEAFICODE = STOCKTRANSACTIONIMPORT.ITEMTYPECODE
				    AND RECIPECOMPONENT.SUBCODE01 = STOCKTRANSACTIONIMPORT.DECOSUBCODE01
				    AND RECIPECOMPONENT.SUBCODE02 = STOCKTRANSACTIONIMPORT.DECOSUBCODE02
				    AND RECIPECOMPONENT.SUBCODE03 = STOCKTRANSACTIONIMPORT.DECOSUBCODE03
--LEFT JOIN ITXVIEWWEIGHTBONRESEP ITXVIEWWEIGHTBONRESEP ON ITXVIEWWEIGHTBONRESEP.PRODUCTIONORDERCODE = PRODUCTIONRESERVATION.PRODUCTIONORDERCODE 
--LEFT JOIN ITXVIEWRESEP1 ITXVIEWRESEP1 ON TRIM(ITXVIEWRESEP1.SUBCODE01) || '-' || TRIM(ITXVIEWRESEP1.SUBCODE02) || '-' || TRIM(ITXVIEWRESEP1.SUBCODE03) = 
--					TRIM(RECIPECOMPONENT.SUBCODE01) || '-' || TRIM(RECIPECOMPONENT.SUBCODE02) || '-' || TRIM(RECIPECOMPONENT.SUBCODE03)
WHERE
    STOCKTRANSACTIONIMPORT.ITEMTYPECODE = 'DYC'
    AND STOCKTRANSACTIONIMPORT.TEMPLATECODE = '120'
    AND STOCKTRANSACTIONIMPORT.IMPORTSTATUS = '2'
GROUP BY
	STOCKTRANSACTIONIMPORT.TRANSACTIONNUMBER,
    PRODUCTIONRESERVATION.PRODUCTIONORDERCODE,
    PRODUCTIONRESERVATION.GROUPLINE,
    RECIPECOMPONENT.SUBCODE01,
    RECIPECOMPONENT.SUBCODE02,
    RECIPECOMPONENT.SUBCODE03,
    STOCKTRANSACTIONIMPORT.TRANSACTIONDATE,
    STOCKTRANSACTIONIMPORT.TRANSACTIONTIME,
    STOCKTRANSACTIONIMPORT.USERPRIMARYUOMCODE,
    STOCKTRANSACTIONIMPORT.LOTCODE,
    RECIPE.RECIPETYPE,
    RECIPE.PICKUPPERCENTAGE
--    
--    ITXVIEWWEIGHTBONRESEP.QTY_BAGIKAIN,
--    RECIPE.RESIDUALBATHVOLUME,
--    ITXVIEWRESEP1.CONSUMPTION,
--    ITXVIEWRESEP1.CONSUMPTIONTYPE,
--    PRODUCTIONRESERVATION.PICKUPQUANTITY