DROP VIEW ITXVIEW_KGBRUTO;
--CREATE VIEW ITXVIEW_KGBRUTO AS
SELECT
    p.ORIGDLVSALORDLINESALORDERCODE AS PROJECTCODE,
    p.CODE,
    p2.PRODUCTIONORDERCODE,
    p.ITEMTYPEAFICODE AS ITEMTYPE_DEMAND,
    p.SUBCODE01,
    p.SUBCODE02,
    p.SUBCODE03,
    p.SUBCODE04,
    p.SUBCODE05,
    p.SUBCODE06,
    p.SUBCODE07,
    p.SUBCODE08,
    p.SUBCODE09,
    p.SUBCODE10,
    p.ORIGDLVSALORDERLINEORDERLINE,
    p2.ITEMTYPEAFICODE AS ITEMTYPE_RESERVATION,
    p2.USERPRIMARYQUANTITY,
    p2.USERPRIMARYUOMCODE,
    p2.USERSECONDARYQUANTITY,
    p2.USERSECONDARYUOMCODE,
    CASE
        WHEN s2.EXTERNALREFERENCE IS NULL THEN s.EXTERNALREFERENCE
        ELSE s2.EXTERNALREFERENCE
    END AS EXTERNALREFERENCE,
    s.INTERNALREFERENCE
FROM
    PRODUCTIONDEMAND p
LEFT JOIN PRODUCTIONRESERVATION p2 ON p2.ORDERCODE = p.CODE
LEFT JOIN SALESORDERLINE s ON s.SALESORDERCODE = p.ORIGDLVSALORDLINESALORDERCODE AND s.ORDERLINE = p.ORIGDLVSALORDERLINEORDERLINE
LEFT JOIN SALESORDER s2 ON s2.CODE = s.SALESORDERCODE
WHERE
    (p2.ITEMTYPEAFICODE = 'KGF' OR p2.ITEMTYPEAFICODE = 'FKG' OR p2.ITEMTYPEAFICODE = 'KFF')
    AND (p.ITEMTYPEAFICODE = 'KFF' OR p.ITEMTYPEAFICODE = 'FKF' OR p.ITEMTYPEAFICODE = 'KGF');