DROP VIEW ITXVIEW_POSISIKK;
--CREATE VIEW ITXVIEW_POSISIKK AS 
SELECT
	* 
FROM (
SELECT
    p.PRODUCTIONORDERCODE,
    p.PRODUCTIONDEMANDCODE,
    p.STEPNUMBER,
    TRIM(p.OPERATIONCODE) AS OPERATIONCODE,
    (iptip.MULAI) AS MULAI,
    (iptop.SELESAI) AS SELESAI
FROM 
    PRODUCTIONDEMANDSTEP p 
LEFT JOIN ITXVIEW_POSISIKK_TGL_IN_PRODORDER iptip ON iptip.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND iptip.DEMANDSTEPSTEPNUMBER = p.STEPNUMBER
LEFT JOIN ITXVIEW_POSISIKK_TGL_OUT_PRODORDER iptop ON iptop.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND iptop.DEMANDSTEPSTEPNUMBER = p.STEPNUMBER
--WHERE
--    p.PRODUCTIONORDERCODE  = '00104332' 
--    AND p.PRODUCTIONDEMANDCODE = '00192213'
ORDER BY p.STEPNUMBER ASC)

