DROP VIEW ITXVIEW_DEMANDBYLOTCODE;
--CREATE VIEW ITXVIEW_DEMANDBYLOTCODE AS 
SELECT DISTINCT 
	LISTAGG(PRODUCTIONDEMANDCODE, ', ') AS PRODUCTIONDEMANDCODE,
	PRODUCTIONORDERCODE,
	DLVSALESORDERLINEORDERLINE 
FROM
	(SELECT DISTINCT 
	--	LISTAGG(TRIM(PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE), ', ')  AS PRODUCTIONDEMANDCODE,
		TRIM(PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE) AS PRODUCTIONDEMANDCODE,
		PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE,
		PRODUCTIONDEMAND.DLVSALESORDERLINEORDERLINE 
	FROM
		PRODUCTIONDEMANDSTEP PRODUCTIONDEMANDSTEP
		LEFT JOIN DB2ADMIN.PRODUCTIONDEMAND PRODUCTIONDEMAND ON PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE = PRODUCTIONDEMAND.CODE )
GROUP BY 
	PRODUCTIONORDERCODE,
	DLVSALESORDERLINEORDERLINE 