DROP VIEW ITXVIEWSCHEDULE_KNITING;
--CREATE VIEW ITXVIEWSCHEDULE_KNITING AS
WITH QTY_PRODUC_YESTERDAY AS (
    SELECT
        PROJECTCODE,
        DECOSUBCODE01,
        DECOSUBCODE02,
        DECOSUBCODE03,
        DECOSUBCODE04,
        SUM(USERPRIMARYQUANTITY) AS QTY_PRODUC_YESTERDAY
    FROM
        STOCKTRANSACTION s
    WHERE
        LOGICALWAREHOUSECODE = 'M502'
        AND TEMPLATECODE = '110'
        AND TRANSACTIONDATE = 
			CAST(
            CURRENT_TIMESTAMP AS DATE
        ) - 1 DAY
    GROUP BY
        PROJECTCODE,
        DECOSUBCODE01,
        DECOSUBCODE02,
        DECOSUBCODE03,
        DECOSUBCODE04
),
QTY_PRODUC_ALL AS(
    SELECT
        PROJECTCODE,
        DECOSUBCODE01,
        DECOSUBCODE02,
        DECOSUBCODE03,
        DECOSUBCODE04,
        SUM(USERPRIMARYQUANTITY) AS QTY_PRODUC_ALL
    FROM
        STOCKTRANSACTION s
    WHERE
        LOGICALWAREHOUSECODE = 'M502'
        AND TEMPLATECODE = '110'
    GROUP BY
        PROJECTCODE,
        DECOSUBCODE01,
        DECOSUBCODE02,
        DECOSUBCODE03,
        DECOSUBCODE04
),
TOTAL_QTY_DEMAND AS (
    SELECT
        DISTINCT 
		p2.SUBCODE01 AS tq_SUBCODE01,
        p2.SUBCODE02 AS tq_SUBCODE02,
        p2.SUBCODE03 AS tq_SUBCODE03,
        p2.SUBCODE04 AS tq_SUBCODE04,
        a4.VALUESTRING AS ORIGINAL_PDCODE,
        p2.ORIGDLVSALORDLINESALORDERCODE,
        SUM(p2.USERPRIMARYQUANTITY) AS TOTAL_QTY
    FROM
        PRODUCTIONDEMAND p2
    LEFT JOIN ADSTORAGE a4 ON
        a4.UNIQUEID = p2.ABSUNIQUEID
        AND a4.FIELDNAME = 'OriginalPDCode'
    WHERE
        p2.ITEMTYPEAFICODE = 'KGF'
        AND a4.VALUESTRING IS NULL
        --		AND p2.ORIGDLVSALORDLINESALORDERCODE = 'DOM2500134'
    GROUP BY
        p2.ORIGDLVSALORDLINESALORDERCODE,
        p2.SUBCODE01,
        p2.SUBCODE02,
        p2.SUBCODE03,
        p2.SUBCODE04,
        a4.VALUESTRING
),
TOTAL_MACHINE AS (
    SELECT
        p3.ORIGDLVSALORDLINESALORDERCODE,
        p3.SUBCODE01 AS tm_SUBCODE01,
        p3.SUBCODE02 AS tm_SUBCODE02,
        p3.SUBCODE03 AS tm_SUBCODE03,
        p3.SUBCODE04 AS tm_SUBCODE04,
        COUNT(SUBSTR(machine.VALUESTRING, 1, 2)) AS JUMLAH_MACHINE
    FROM
        PRODUCTIONDEMAND p3
    LEFT JOIN ADSTORAGE machine ON
        machine.UNIQUEID = p3.ABSUNIQUEID
        AND machine.FIELDNAME = 'MachineNoCode'
        --	WHERE p3.ORIGDLVSALORDLINESALORDERCODE = 'OPN2500113'
    GROUP BY
        p3.ORIGDLVSALORDLINESALORDERCODE,
        p3.SUBCODE01,
        p3.SUBCODE02,
        p3.SUBCODE03,
        p3.SUBCODE04
)
SELECT
    LANGGANAN,
    KATEGORI,
    PROJECT,
    DATAMAIN.ORIGINAL_PDCODE,
    ARTICLE_CODE,
    UKURAN_MESIN,
    tqd.TOTAL_QTY AS TOTAL_QTY,
    MACHINE,
    TM.JUMLAH_MACHINE AS TOTAL_MACHINE,
    STD_QTY_PERMACHINE,
    TM.JUMLAH_MACHINE * STD_QTY_PERMACHINE AS CAPACITY_PERDAY,
    QPY.QTY_PRODUC_YESTERDAY,
    FLOOR(ROUND(CAST(QPY.QTY_PRODUC_YESTERDAY AS DECIMAL(10, 4)) / (TM.JUMLAH_MACHINE * STD_QTY_PERMACHINE), 2) * 100) || '%' AS PERSENTASE_TARGET,
    QPA.QTY_PRODUC_ALL AS PRODUCED,
    tqd.TOTAL_QTY - COALESCE(QPA.QTY_PRODUC_ALL, 0) AS BELUM_RAJUT,
    CASE
        WHEN tqd.TOTAL_QTY = 0 THEN '0'
        ELSE FLOOR(ROUND((CAST(QPA.QTY_PRODUC_ALL AS DECIMAL(10, 4)) / tqd.TOTAL_QTY * 100))) || '%'
    END AS PERSENTASE_SETELAH_PROD,
    CEIL(CAST((tqd.TOTAL_QTY - QPA.QTY_PRODUC_ALL) AS DECIMAL(18, 2)) / CAST((TM.JUMLAH_MACHINE * STD_QTY_PERMACHINE) AS DECIMAL(18, 2))) AS ESTIMATED_COMPLETED,
    CAST(
        (
            tqd.TOTAL_QTY - QPA.QTY_PRODUC_ALL
        ) / (
            TM.JUMLAH_MACHINE * STD_QTY_PERMACHINE
        ) AS INT
    ) DAY + CAST(
        CURRENT_TIMESTAMP AS DATE
    ) - 1 DAY AS ESTIMATED_DELIVERY,
    LISTAGG(
        DISTINCT DELIVERY_ACTUAL,
        ', '
    ) AS DELIVERY_ACTUAL,
    SUBCODE01,
    SUBCODE02,
    SUBCODE03,
    SUBCODE04
FROM
    (
        SELECT
--        	LISTAGG(TRIM(p.ORDERDATE), ', ') AS TERIMAORDER,
            ip.LANGGANAN,
            CASE
                WHEN s.TEMPLATECODE = 'DOM' THEN 'Bulk'
                WHEN s.TEMPLATECODE = 'EXP' THEN 'Bulk'
                WHEN s.TEMPLATECODE = 'OPN' THEN 'Booking'
                WHEN s.TEMPLATECODE = 'MNB' THEN 'Minibulk'
                WHEN s.TEMPLATECODE = 'CMD' THEN 'Cuci Mesin'
                WHEN s.TEMPLATECODE = 'SME' THEN 'Salesment'
                WHEN s.TEMPLATECODE = 'SAM' THEN 'Salesment'
                WHEN s.TEMPLATECODE = 'BP' THEN 'Salesment'
                WHEN s.TEMPLATECODE = 'TS' THEN 'Salesment'
                ELSE 'Salesment'
            END AS KATEGORI,
            p.ORIGDLVSALORDLINESALORDERCODE AS PROJECT,
            TRIM(p.SUBCODE01) || ' ' || TRIM(p.SUBCODE02) || TRIM(p.SUBCODE03) || ' ' || TRIM(p.SUBCODE04) AS ARTICLE_CODE,
            COALESCE(FLOOR(a7.VALUEDECIMAL), '0') || ' X ' || COALESCE(FLOOR(a8.VALUEDECIMAL), '0') AS UKURAN_MESIN,
            SUBSTR(a2.VALUESTRING, 1, 2) AS MACHINE,
            ROUND(a5.VALUEDECIMAL * 24) AS STD_QTY_PERMACHINE,
            a6.VALUEDATE AS DELIVERY_ACTUAL,
            a4.VALUESTRING AS ORIGINAL_PDCODE,
            p.SUBCODE01,
            p.SUBCODE02,
            p.SUBCODE03,
            p.SUBCODE04,
            p.ABSUNIQUEID AS ABSUNIQUEID_DEMAND
        FROM
            PRODUCTIONDEMAND p
        LEFT JOIN SALESORDER s ON s.CODE = p.ORIGDLVSALORDLINESALORDERCODE
        LEFT JOIN ADSTORAGE a1 ON a1.UNIQUEID = p.ABSUNIQUEID AND a1.FIELDNAME = 'StatusOper' AND NOT a1.VALUESTRING = '2'
        LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = p.ABSUNIQUEID AND a2.FIELDNAME = 'MachineNoCode'
        LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = p.ABSUNIQUEID AND a3.FIELDNAME = 'ukuranMC'
        LEFT JOIN ADSTORAGE a4 ON a4.UNIQUEID = p.ABSUNIQUEID AND a4.FIELDNAME = 'OriginalPDCode'
        LEFT JOIN ADSTORAGE a6 ON a6.UNIQUEID = p.ABSUNIQUEID AND a6.FIELDNAME = 'RMPGreigeReqDateTo'
        LEFT JOIN ITXVIEW_PELANGGAN ip ON ip.CODE = p.ORIGDLVSALORDLINESALORDERCODE
        LEFT JOIN PRODUCT p2 ON p2.ITEMTYPECODE = p.ITEMTYPEAFICODE
            AND p2.SUBCODE01 = p.SUBCODE01
            AND p2.SUBCODE02 = p.SUBCODE02
            AND p2.SUBCODE03 = p.SUBCODE03
            AND p2.SUBCODE04 = p.SUBCODE04
        LEFT JOIN ADSTORAGE a5 ON a5.UNIQUEID = p2.ABSUNIQUEID AND a5.FIELDNAME = 'ProductionRate'
        LEFT JOIN ADSTORAGE a7 ON a7.UNIQUEID = p2.ABSUNIQUEID AND a7.FIELDNAME = 'Diameter'
        LEFT JOIN ADSTORAGE a8 ON a8.UNIQUEID = p2.ABSUNIQUEID AND a8.FIELDNAME = 'Gauge'
        WHERE
            p.ITEMTYPEAFICODE = 'KGF'
            AND NOT p.PROGRESSSTATUS = '6'
            AND NOT p.ORIGDLVSALORDLINESALORDERCODE IS NULL
            AND NOT a2.VALUESTRING IS NULL
            AND a4.VALUESTRING IS NULL
            --		AND p.ORIGDLVSALORDLINESALORDERCODE = 'S2500029'
            --		AND p.ORIGDLVSALORDLINESALORDERCODE = 'OPN2500093'
            --		AND p.ORIGDLVSALORDLINESALORDERCODE = 'S2500061'
        ORDER BY
            p.ORIGDLVSALORDLINESALORDERCODE DESC
    ) DATAMAIN
LEFT JOIN QTY_PRODUC_YESTERDAY QPY ON
    QPY.PROJECTCODE = DATAMAIN.PROJECT
    AND QPY.DECOSUBCODE01 = DATAMAIN.SUBCODE01
    AND QPY.DECOSUBCODE02 = DATAMAIN.SUBCODE02
    AND QPY.DECOSUBCODE03 = DATAMAIN.SUBCODE03
    AND QPY.DECOSUBCODE04 = DATAMAIN.SUBCODE04
LEFT JOIN QTY_PRODUC_ALL QPA ON
    QPA.PROJECTCODE = DATAMAIN.PROJECT
    AND QPA.DECOSUBCODE01 = DATAMAIN.SUBCODE01
    AND QPA.DECOSUBCODE02 = DATAMAIN.SUBCODE02
    AND QPA.DECOSUBCODE03 = DATAMAIN.SUBCODE03
    AND QPA.DECOSUBCODE04 = DATAMAIN.SUBCODE04
LEFT JOIN TOTAL_QTY_DEMAND tqd ON
    tqd.ORIGDLVSALORDLINESALORDERCODE = DATAMAIN.PROJECT
    AND tqd.ORIGINAL_PDCODE IS NULL
    AND tqd.tq_SUBCODE01 = DATAMAIN.SUBCODE01
    AND tqd.tq_SUBCODE02 = DATAMAIN.SUBCODE02
    AND tqd.tq_SUBCODE03 = DATAMAIN.SUBCODE03
    AND tqd.tq_SUBCODE04 = DATAMAIN.SUBCODE04
LEFT JOIN TOTAL_MACHINE TM ON
    TM.ORIGDLVSALORDLINESALORDERCODE = DATAMAIN.PROJECT
    AND TM.tm_SUBCODE01 = DATAMAIN.SUBCODE01
    AND TM.tm_SUBCODE02 = DATAMAIN.SUBCODE02
    AND TM.tm_SUBCODE03 = DATAMAIN.SUBCODE03
    AND TM.tm_SUBCODE04 = DATAMAIN.SUBCODE04
GROUP BY
    LANGGANAN,
    KATEGORI,
    PROJECT,
    DATAMAIN.ORIGINAL_PDCODE,
    ARTICLE_CODE,
    UKURAN_MESIN,
    MACHINE,
    STD_QTY_PERMACHINE,
    QPY.QTY_PRODUC_YESTERDAY,
    QPA.QTY_PRODUC_ALL,
    tqd.TOTAL_QTY,
    SUBCODE01,
    SUBCODE02,
    SUBCODE03,
    SUBCODE04,
    TM.JUMLAH_MACHINE
    --	tqd.ORIGDLVSALORDLINESALORDERCODE;