DROP VIEW ITXVIEW_INVOICE_SURATJALAN;
--CREATE VIEW ITXVIEW_INVOICE_SURATJALAN AS
SELECT
    ALLOCATION.CODE AS code_allocation,
    trim(PLANTINVOICE.CODE) AS Invoice,
    ITXVIEW_ALLOCATION_SURATJALAN_PPC.CODE,
    SALESDOCUMENTLINE.PREVIOUSCODE AS NO_SJ,
    SALESDOCUMENT2.PROVISIONALDOCUMENTDATE AS tgl_inv,
    SALESDOCUMENT2.GOODSISSUEDATE AS issue_date,
    CASE
        WHEN trim(SALESDOCUMENT2.PROVISIONALDOCUMENTDATE) <= DATE('2022-08-15') THEN
			CASE
            WHEN trim(SALESDOCUMENT2.GOODSISSUEDATE) IS NOT NULL THEN trim(SALESDOCUMENT2.GOODSISSUEDATE)
            ELSE
        	trim(SALESDOCUMENT2.PROVISIONALDOCUMENTDATE)
        END
        ELSE
    	trim(SALESDOCUMENT2.GOODSISSUEDATE)
    END AS tanggal_inv,
    PLANTINVOICE.CREATIONDATE AS tgl_create,
    CASE
        WHEN trim(SALESDOCUMENT2.PROVISIONALDOCUMENTDATE) <= DATE('2022-08-15') THEN
			CASE
            WHEN trim(SALESDOCUMENT2.GOODSISSUEDATE) IS NOT NULL THEN SALESDOCUMENT2.GOODSISSUEDATE + PAYMENTMETHODIE.NOOFDAYS
            ELSE
        	SALESDOCUMENT2.PROVISIONALDOCUMENTDATE + PAYMENTMETHODIE.NOOFDAYS
        END
        ELSE
    	SALESDOCUMENT2.GOODSISSUEDATE + PAYMENTMETHODIE.NOOFDAYS
    END AS DUE,
    PLANTINVOICE.CHALLANDATE AS DATEKB,
    PLANTINVOICE.LRDATE AS DUEKB,
    trim(PLANTINVOICE.ORDERCURRENCYCODE) AS curr,
    trim(SALESORDER.COUNTERCODE) AS JENIS_ORDER,
    trim(SALESORDER.FNCORDPRNCUSTOMERSUPPLIERCODE) AS kode_bep,
    BUSINESSPARTNER.NUMBERID AS id_bep,
    BUSINESSPARTNER.LEGALNAME1 AS nama_bep,
    CASE
        WHEN ADDRESS.CODE IS NULL THEN 'Warning! Kolom Address Code Sales Order Kosong. USER: ' || TRIM(SALESORDER.CREATIONUSER)
        ELSE ADDRESS.CODE
    END AS kode_cus,
    CASE
        WHEN trim(ADDRESS.ADDRESSEE) IS NULL THEN 'Warning! Kolom Address Code Sales Order Kosong. USER: ' || TRIM(SALESORDER.CREATIONUSER)
        ELSE trim(ADDRESS.ADDRESSEE)
    END AS nama_cus,
    CASE
        WHEN PLANTINVOICE.BLNUMBER IS NOT NULL THEN
        CASE
            WHEN trim(ADDRESS.ADDRESSLINE4) IS NULL THEN 'Warning! Kolom Address Code Sales Order Kosong. USER: ' || TRIM(SALESORDER.CREATIONUSER)
            ELSE trim(ADDRESS.ADDRESSLINE4)
        END
        ELSE
        CASE
            WHEN trim(ADDRESS.ADDRESSLINE4) IS NULL THEN 'Warning! Kolom Address Code Sales Order Kosong. USER: ' || TRIM(SALESORDER.CREATIONUSER)
            ELSE trim(ADDRESS.ADDRESSLINE4)
        END
    END AS NPWP,
    CASE
        WHEN PLANTINVOICE.BLNUMBER IS NULL THEN 'Warning! Kolom faktur pajak Invoice Kosong. USER : ' || TRIM(PLANTINVOICE.CREATIONUSER)
        ELSE PLANTINVOICE.BLNUMBER
    END AS FAKTUR_PAJAK,
    trim(PLANTINVOICE.CONTRACTNOCODE) AS NO_ORDER,
    REPLACE(ITXVIEW_PO_INVOICE.NO_PO, '''', ' ') AS NO_PO,
    PLANTINVOICE.STATUS AS NO_CI,
    CASE
        WHEN trim(SALESORDER.TEMPLATECODE) LIKE '%CWD%' THEN trim(SALESORDER.DESCRIPTION)
        ELSE '-'
    END AS DESC_KAIN,
    PLANTINVOICELINE.TAXTEMPLATECODE AS PPN,
    trim(PAYMENTMETHOD.LONGDESCRIPTION) AS code_payment,
    CASE
    	WHEN trim(PAYMENTMETHODIE.NOOFDAYS) = 0 THEN trim(PAYMENTMETHOD.LONGDESCRIPTION)
    	ELSE trim(PAYMENTMETHODIE.NOOFDAYS)
    END AS payment_terms,
    trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) AS unit,
    PLANTINVOICE.EXCHANGERATEOFCONTRACT AS rate,
    CASE
        WHEN PLANTINVOICE.ORDERCURRENCYCODE = 'USD' THEN SALESDOCUMENTLINE.price
        ELSE 0
    END AS PRICE_USD,
    CASE
        WHEN PLANTINVOICE.ORDERCURRENCYCODE = 'IDR' THEN SALESDOCUMENTLINE.price
        ELSE floor( SALESDOCUMENTLINE.price * PLANTINVOICE.EXCHANGERATEOFCONTRACT )
    END AS PRICE_IDR,
    CASE
        WHEN trim(PLANTINVOICE.ORDERCURRENCYCODE) = 'USD' THEN CASE
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'kg' THEN round( SUM( round( ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASEPRIMARYQUANTITY, 2 )) * round( SALESDOCUMENTLINE.price, 2 ), 2 )
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'yd' THEN round( SUM( round( ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY, 2 )) * round( SALESDOCUMENTLINE.price, 2 ), 2 )
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'm' THEN round( SUM( round( ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY * 0.9144, 2 )) * round( SALESDOCUMENTLINE.price, 2 ), 2 )
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'un' THEN CASE
                WHEN trim(SALESDOCUMENTLINE.ITEMTYPEAFICODE) = 'CAP' THEN round( SUM( round( ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASEPRIMARYQUANTITY, 2 )) * round( SALESDOCUMENTLINE.price, 2 ), 2 )
                ELSE
            	round( SUM( round( ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY, 2 )) * round( SALESDOCUMENTLINE.price, 2 ), 2 )
            END
        END
        ELSE 0
    END AS TOTAL_USD,
    CASE
        WHEN trim(PLANTINVOICE.ORDERCURRENCYCODE) = 'IDR' THEN CASE
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'kg' THEN floor(SUM(round( ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASEPRIMARYQUANTITY, 2 )) * round( SALESDOCUMENTLINE.price, 2 ))
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'yd' THEN floor(SUM(round( ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY, 2 )) * round( SALESDOCUMENTLINE.price, 2 ))
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'm' THEN floor(SUM(round( ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY * 0.9144, 2 )) * round( SALESDOCUMENTLINE.price, 2 ))
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'un' THEN CASE
                WHEN trim(SALESDOCUMENTLINE.ITEMTYPEAFICODE) = 'CAP' THEN floor(SUM(round( ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASEPRIMARYQUANTITY, 2 )) * round( SALESDOCUMENTLINE.price, 2 ))
                ELSE
            	floor(SUM(round( ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY, 2 )) * round( SALESDOCUMENTLINE.price, 2 ))
            END
        END
        ELSE CASE
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'kg' THEN floor(round(SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASEPRIMARYQUANTITY, 2 )) * round( SALESDOCUMENTLINE.price, 2 ), 2 ) * PLANTINVOICE.EXCHANGERATEOFCONTRACT)
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'yd' THEN floor(round(SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY, 2 )) * round( SALESDOCUMENTLINE.price, 2 ), 2 ) * PLANTINVOICE.EXCHANGERATEOFCONTRACT)
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'm' THEN floor(round(SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY * 0.9144, 2 )) * round( SALESDOCUMENTLINE.price, 2 ), 2 ) * PLANTINVOICE.EXCHANGERATEOFCONTRACT)
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'un' THEN CASE
                WHEN trim(SALESDOCUMENTLINE.ITEMTYPEAFICODE) = 'CAP' THEN floor(round(SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASEPRIMARYQUANTITY, 2 )) * round( SALESDOCUMENTLINE.price, 2 ), 2 ) * PLANTINVOICE.EXCHANGERATEOFCONTRACT)
                ELSE
            	floor(round(SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY, 2 )) * round( SALESDOCUMENTLINE.price, 2 ), 2 ) * PLANTINVOICE.EXCHANGERATEOFCONTRACT)
            END
        END
    END AS TOTAL_IDR,
    CASE
        WHEN (ITXVIEW_INVOICE_BIAYATAMBAHAN.biaya_tambahan) IS NULL THEN 0
        ELSE (ITXVIEW_INVOICE_BIAYATAMBAHAN.biaya_tambahan)
    END AS biaya_tambahan,
    CASE
        WHEN (ITXVIEW_FOC_INVOICE.foc_kg) IS NULL THEN 0
        ELSE (ITXVIEW_FOC_INVOICE.foc_kg)
    END AS foc_kg,
    CASE
        WHEN (ITXVIEW_FOC_INVOICE.foc_yard) IS NULL THEN 0
        ELSE (ITXVIEW_FOC_INVOICE.foc_yard)
    END AS foc_yard,
    CASE
        WHEN (ITXVIEW_FOC_INVOICE.QUANTITY_FOC) IS NULL THEN 0
        ELSE (ITXVIEW_FOC_INVOICE.QUANTITY_FOC)
    END AS HARGA_FOC,
    ITXVIEW_INVOICE_NOINVOICE_DETAIL_DPP.DPP_BC AS DPP_BC,
    SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASEPRIMARYQUANTITY, 2))AS BERAT,
    CASE
        WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'kg' THEN SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY, 2))
        WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'yd' THEN SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY, 2))
        WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'm' THEN SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY * 0.9144, 2))
        WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'un' THEN CASE
            WHEN trim(SALESDOCUMENTLINE.ITEMTYPEAFICODE) = 'CAP' THEN SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASEPRIMARYQUANTITY, 2))
            ELSE SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY, 2))
        END
    END AS BERAT_LAIN,
    round(SALESDOCUMENTLINE.price, 2) AS harga_satuan,
    CASE
        WHEN trim(PLANTINVOICE.ORDERCURRENCYCODE) = 'USD' 
        THEN
        CASE
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'kg' THEN round(SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASEPRIMARYQUANTITY, 2)) * round(SALESDOCUMENTLINE.price, 3), 2)
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'yd' THEN round(SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY, 2)) * round(SALESDOCUMENTLINE.price, 3), 2)
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'm' THEN round(SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY * 0.9144, 2)) * round(SALESDOCUMENTLINE.price, 3), 2)
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'un' THEN 
			CASE
                WHEN trim(SALESDOCUMENTLINE.ITEMTYPEAFICODE) = 'CAP' THEN round(SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASEPRIMARYQUANTITY, 2)) * round(SALESDOCUMENTLINE.price, 3), 2)
                ELSE round(SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY, 2)) * round(SALESDOCUMENTLINE.price, 3), 2)
            END
        END
        WHEN trim(PLANTINVOICE.ORDERCURRENCYCODE) = 'IDR'
        THEN
        CASE
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'kg' THEN floor(SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASEPRIMARYQUANTITY, 2)) * round(SALESDOCUMENTLINE.price, 2))
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'yd' THEN floor(SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY, 2)) * round(SALESDOCUMENTLINE.price, 2))
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'm' THEN floor(SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY * 0.9144, 2)) * round(SALESDOCUMENTLINE.price, 2))
            WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'un' THEN 
			CASE
                WHEN trim(SALESDOCUMENTLINE.ITEMTYPEAFICODE) = 'CAP' THEN floor(SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASEPRIMARYQUANTITY, 2)) * round(SALESDOCUMENTLINE.price, 2))
                ELSE floor(SUM(round(ITXVIEW_ALLOCATION_SURATJALAN_PPC.BASESECONDARYQUANTITY, 2)) * round(SALESDOCUMENTLINE.price, 2))
            END
        END
    END AS JUMLAH_HARGA,
    TRIM(SALESDOCUMENTLINE.EXTERNALITEM) AS KODE_JK,
    CASE
        WHEN PRODUCT.LONGDESCRIPTION IS NULL THEN TRIM(SALESDOCUMENTLINE.SUBCODE02) || TRIM(SALESDOCUMENTLINE.SUBCODE03) || ' - ' || SALESDOCUMENTLINE.ITEMDESCRIPTION
        ELSE TRIM(SALESDOCUMENTLINE.SUBCODE02) || TRIM(SALESDOCUMENTLINE.SUBCODE03) || ' - ' || PRODUCT.LONGDESCRIPTION
    END AS ITEMDESCRIPTION,
    i.WARNA
FROM
    PLANTINVOICE PLANTINVOICE
LEFT JOIN ITXVIEW_PO_INVOICE ITXVIEW_PO_INVOICE ON
    PLANTINVOICE.CODE = ITXVIEW_PO_INVOICE.NO_INVOICE
LEFT JOIN SALESORDER SALESORDER ON
    PLANTINVOICE.CONTRACTNOCODE = SALESORDER.CODE
LEFT JOIN SALESDOCUMENT SALESDOCUMENT ON
    PLANTINVOICE.CODE = SALESDOCUMENT.PROVISIONALCODE
LEFT JOIN PAYMENTMETHOD PAYMENTMETHOD ON
    PLANTINVOICE.TERMSOFPAYMENTCODE = PAYMENTMETHOD.CODE
LEFT JOIN PAYMENTMETHODIE PAYMENTMETHODIE ON
    PLANTINVOICE.TERMSOFPAYMENTCODE = PAYMENTMETHODIE.CODE
LEFT JOIN ADDRESS ADDRESS ON
    ADDRESS.UNIQUEID = SALESORDER.PAYMENTCUSTOMERUNIQUEID
    AND ADDRESS.CODE = SALESORDER.PAYMENTCUSTOMERCODE
LEFT JOIN ORDERPARTNER ORDERPARTNER ON
    ORDERPARTNER.CUSTOMERSUPPLIERCODE = PLANTINVOICE.BUYERIFOTCCUSTOMERSUPPLIERCODE
LEFT JOIN BUSINESSPARTNER BUSINESSPARTNER ON
    BUSINESSPARTNER.NUMBERID = ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID
LEFT JOIN SALESDOCUMENTLINE SALESDOCUMENTLINE ON
    SALESDOCUMENTLINE.SALESDOCUMENTPROVISIONALCODE = SALESDOCUMENT.PROVISIONALCODE
LEFT JOIN PLANTINVOICELINE PLANTINVOICELINE ON
    PLANTINVOICELINE.PLANTINVOICECODE = SALESDOCUMENTLINE.SALESDOCUMENTPROVISIONALCODE
    AND PLANTINVOICELINE.INVOICELINENO = CASE
        WHEN LENGTH(RTRIM(PREVIOUSORDERLINE)) = 2 THEN SUBSTR(SALESDOCUMENTLINE.PREVIOUSORDERLINE, 1, 1)
        WHEN LENGTH(RTRIM(PREVIOUSORDERLINE)) = 3 THEN SUBSTR(SALESDOCUMENTLINE.PREVIOUSORDERLINE, 1, 2)
        WHEN LENGTH(RTRIM(PREVIOUSORDERLINE)) = 4 THEN SUBSTR(SALESDOCUMENTLINE.PREVIOUSORDERLINE, 1, 3)
    END
LEFT JOIN SALESDOCUMENT SALESDOCUMENT2 ON
    SALESDOCUMENT2.PROVISIONALCODE = SALESDOCUMENTLINE.PREVIOUSCODE
LEFT JOIN SALESORDERLINE SALESORDERLINE ON
    SALESORDERLINE.SALESORDERCODE = SALESORDER.CODE
    AND SALESORDERLINE.ORDERLINE = SALESDOCUMENTLINE.DLVSALESORDERLINEORDERLINE
LEFT JOIN (
    SELECT
        *
    FROM
        ALLOCATION ALLOCATION
    WHERE
        ALLOCATION.DETAILTYPE = '1'
        AND ALLOCATION.ORIGINTRNTRANSACTIONNUMBER IS NULL)ALLOCATION ON
    SALESDOCUMENTLINE.SUBCODE01 = ALLOCATION.DECOSUBCODE01
    AND SALESDOCUMENTLINE.SUBCODE02 = ALLOCATION.DECOSUBCODE02
    AND SALESDOCUMENTLINE.SUBCODE03 = ALLOCATION.DECOSUBCODE03
    AND SALESDOCUMENTLINE.SUBCODE04 = ALLOCATION.DECOSUBCODE04
    AND SALESDOCUMENTLINE.SUBCODE05 = ALLOCATION.DECOSUBCODE05
    AND SALESDOCUMENTLINE.SUBCODE06 = ALLOCATION.DECOSUBCODE06
    AND SALESDOCUMENTLINE.SUBCODE07 = ALLOCATION.DECOSUBCODE07
    AND SALESDOCUMENTLINE.PREVIOUSCODE = ALLOCATION.ORDERCODE
    AND SALESDOCUMENTLINE.PREVIOUSORDERLINE = ALLOCATION.ORDERLINE
LEFT JOIN ITXVIEW_ALLOCATION_SURATJALAN_PPC ITXVIEW_ALLOCATION_SURATJALAN_PPC ON
    ITXVIEW_ALLOCATION_SURATJALAN_PPC.CODE = ALLOCATION.CODE
LEFT JOIN ITXVIEW_INVOICE_BIAYATAMBAHAN ITXVIEW_INVOICE_BIAYATAMBAHAN ON
    PLANTINVOICE.CODE = ITXVIEW_INVOICE_BIAYATAMBAHAN.no_invoice
    -- UNTUK JENIS FOC
LEFT JOIN ITXVIEW_FOC_INVOICE ITXVIEW_FOC_INVOICE ON
    PLANTINVOICE.CODE = ITXVIEW_FOC_INVOICE.NO_INVOICE
LEFT JOIN ITXVIEW_INVOICE_NOINVOICE_DETAIL_DPP ITXVIEW_INVOICE_NOINVOICE_DETAIL_DPP ON
    PLANTINVOICE.CODE = ITXVIEW_INVOICE_NOINVOICE_DETAIL_DPP.INVOICE
LEFT JOIN PRODUCT PRODUCT ON
    PRODUCT.ITEMTYPECODE = SALESDOCUMENTLINE.ITEMTYPEAFICODE
    AND PRODUCT.SUBCODE01 = SALESDOCUMENTLINE.SUBCODE01
    AND PRODUCT.SUBCODE02 = SALESDOCUMENTLINE.SUBCODE02
    AND PRODUCT.SUBCODE03 = SALESDOCUMENTLINE.SUBCODE03
    AND PRODUCT.SUBCODE04 = SALESDOCUMENTLINE.SUBCODE04
    AND PRODUCT.SUBCODE05 = SALESDOCUMENTLINE.SUBCODE05
    AND PRODUCT.SUBCODE06 = SALESDOCUMENTLINE.SUBCODE06
    AND PRODUCT.SUBCODE07 = SALESDOCUMENTLINE.SUBCODE07
    AND PRODUCT.SUBCODE08 = SALESDOCUMENTLINE.SUBCODE08
    AND PRODUCT.SUBCODE09 = SALESDOCUMENTLINE.SUBCODE09
    AND PRODUCT.SUBCODE10 = SALESDOCUMENTLINE.SUBCODE10
LEFT JOIN ITXVIEWCOLOR i ON
    i.ITEMTYPECODE = SALESDOCUMENTLINE.ITEMTYPEAFICODE
    AND i.SUBCODE01 = SALESDOCUMENTLINE.SUBCODE01
    AND i.SUBCODE02 = SALESDOCUMENTLINE.SUBCODE02
    AND i.SUBCODE03 = SALESDOCUMENTLINE.SUBCODE03
    AND i.SUBCODE04 = SALESDOCUMENTLINE.SUBCODE04
    AND i.SUBCODE05 = SALESDOCUMENTLINE.SUBCODE05
    AND i.SUBCODE06 = SALESDOCUMENTLINE.SUBCODE06
    AND i.SUBCODE07 = SALESDOCUMENTLINE.SUBCODE07
    AND i.SUBCODE08 = SALESDOCUMENTLINE.SUBCODE08
    AND i.SUBCODE09 = SALESDOCUMENTLINE.SUBCODE09
    AND i.SUBCODE10 = SALESDOCUMENTLINE.SUBCODE10
    --LEFT JOIN ITXVIEW_SUB_INV_ITEMJENISKAIN JK ON
    --        SALESDOCUMENT.PROVISIONALCODE = JK.PROVISIONALCODE
    --        AND SALESDOCUMENTLINE.SUBCODE02 = JK.SUBCODE02
    --        AND SALESDOCUMENTLINE.SUBCODE03 = JK.SUBCODE03
    --        AND SALESDOCUMENTLINE.SUBCODE04 = JK.SUBCODE04
    --        AND SALESDOCUMENTLINE.SUBCODE05 = JK.SUBCODE05
    --        AND SALESDOCUMENTLINE.SUBCODE06 = JK.SUBCODE06
    --LEFT JOIN ITXVIEW_ALLOCATION_1 ia ON ia.ORDERLINE = SALESORDERLINE.ORDERLINE 
    --								AND ia.DECOSUBCODE01 = SALESORDERLINE.SUBCODE01 
    --								AND ia.DECOSUBCODE02 = SALESORDERLINE.SUBCODE02 
    --								AND ia.DECOSUBCODE03 = SALESORDERLINE.SUBCODE03 
    --								AND ia.DECOSUBCODE04 = SALESORDERLINE.SUBCODE04 
    --								AND ia.DECOSUBCODE05 = SALESORDERLINE.SUBCODE05 
    --								AND ia.DECOSUBCODE06 = SALESORDERLINE.SUBCODE06
GROUP BY
    ALLOCATION.CODE,
    ITXVIEW_ALLOCATION_SURATJALAN_PPC.CODE,
    PLANTINVOICE.CODE,
    PLANTINVOICE.CHALLANDATE,
    PLANTINVOICE.LRDATE,
    PLANTINVOICE.STATUS,
    SALESORDER.CREATIONUSER,
    PLANTINVOICE.CREATIONUSER,
    SALESDOCUMENTLINE.PREVIOUSCODE,
    SALESDOCUMENTLINE.ITEMTYPEAFICODE,
    ITXVIEW_PO_INVOICE.NO_PO,
    SALESDOCUMENT.ORDERPARTNERBRANDCODE,
    SALESORDER.ORDERPARTNERBRANDCODE,
    ALLOCATION.ALLOCATIONDATE,
    SALESDOCUMENT2.GOODSISSUEDATE,
    SALESDOCUMENT2.PROVISIONALDOCUMENTDATE,
    PLANTINVOICE.CREATIONDATE,
    PAYMENTMETHOD.LONGDESCRIPTION,
    PAYMENTMETHODIE.CODE,
    PAYMENTMETHODIE.NOOFDAYS,
    PLANTINVOICE.CONTRACTNOCODE,
    SALESORDER.FNCORDPRNCUSTOMERSUPPLIERCODE,
    ADDRESS.ADDRESSEE,
    ADDRESS.TAXREGISTRATIONNUMBER,
    ADDRESS.ADDRESSLINE4,
    PLANTINVOICE.ORDERCURRENCYCODE,
    PLANTINVOICE.EXCHANGERATEOFCONTRACT,
    ITXVIEW_INVOICE_BIAYATAMBAHAN.biaya_tambahan,
    ITXVIEW_INVOICE_NOINVOICE_DETAIL_DPP.DPP_BC,
    ITXVIEW_FOC_INVOICE.foc_kg,
    ITXVIEW_FOC_INVOICE.foc_yard,
    ITXVIEW_FOC_INVOICE.QUANTITY_FOC,
    SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE,
    PLANTINVOICELINE.TAXTEMPLATECODE,
    PLANTINVOICE.BLNUMBER,
    PLANTINVOICE.ORDERCURRENCYCODE,
    SALESDOCUMENTLINE.price,
    ALLOCATION.ORIGINTRNTRANSACTIONNUMBER,
    SALESORDER.DESCRIPTION,
    SALESORDER.TEMPLATECODE,
    SALESORDER.COUNTERCODE,
    BUSINESSPARTNER.NUMBERID,
    BUSINESSPARTNER.LEGALNAME1,
    ADDRESS.CODE,
    SALESDOCUMENTLINE.SUBCODE02,
    SALESDOCUMENTLINE.SUBCODE03,
    SALESDOCUMENTLINE.ITEMDESCRIPTION,
    PRODUCT.LONGDESCRIPTION,
    SALESDOCUMENTLINE.EXTERNALITEM,
    i.WARNA;