DROP VIEW ITXVIEWDETAILBAGIKAIN;
--CREATE VIEW ITXVIEWDETAILBAGIKAIN AS 
SELECT
    PRODUCTIONDEMAND.CODE,
    A.PRODUCTIONORDERCODE,
    STOCKTRANSACTION.ITEMTYPECODE,
    STOCKTRANSACTION.ITEMELEMENTCODE,
--    CASE
--        WHEN STOCKTRANSACTION.ITEMELEMENTCODE LIKE '800000%' THEN SUBSTR(B.ELEMENT_ASLI, 1, 8)
--        ELSE SUBSTR(STOCKTRANSACTION.ITEMELEMENTCODE, 1, 8)
--    END AS DEMAND_KGF,
    STOCKTRANSACTION.WHSLOCATIONWAREHOUSEZONECODE,
    STOCKTRANSACTION.WAREHOUSELOCATIONCODE,
    STOCKTRANSACTION.USERPRIMARYQUANTITY,
    STOCKTRANSACTION.USERPRIMARYUOMCODE,
    STOCKTRANSACTION.USERSECONDARYQUANTITY,
    STOCKTRANSACTION.USERSECONDARYUOMCODE,
    C.VALUESTRING AS MESIN_KNT,
    STOCKTRANSACTION.ORDERLINE,
	STOCKTRANSACTION.DECOSUBCODE01,
	STOCKTRANSACTION.DECOSUBCODE02,
	STOCKTRANSACTION.DECOSUBCODE03,
	STOCKTRANSACTION.DECOSUBCODE04
FROM
    PRODUCTIONDEMAND PRODUCTIONDEMAND
LEFT JOIN (
    SELECT
        PRODUCTIONRESERVATION.ORDERCODE,
        PRODUCTIONRESERVATION.PRODUCTIONORDERCODE
    FROM
        PRODUCTIONRESERVATION PRODUCTIONRESERVATION
    WHERE
        (PRODUCTIONRESERVATION.ITEMTYPEAFICODE = 'KGF'
            OR PRODUCTIONRESERVATION.ITEMTYPEAFICODE = 'FKG')
) A ON
    PRODUCTIONDEMAND.CODE = A.ORDERCODE
LEFT JOIN STOCKTRANSACTION STOCKTRANSACTION
ON
    A.PRODUCTIONORDERCODE = STOCKTRANSACTION.ORDERCODE
--LEFT JOIN (
--    SELECT
--        STOCKTRANSACTION.ITEMELEMENTCODE,
--        X.ITEMELEMENTCODE AS ELEMENT_ASLI,
--        STOCKTRANSACTION.CUTORGTRTRANSACTIONNUMBER
--    FROM
--        STOCKTRANSACTION STOCKTRANSACTION
--    LEFT JOIN STOCKTRANSACTION X 
--	ON
--        STOCKTRANSACTION.CUTORGTRTRANSACTIONNUMBER = X.TRANSACTIONNUMBER
--    WHERE
--        STOCKTRANSACTION.TEMPLATECODE = '342'
--    GROUP BY
--        STOCKTRANSACTION.ITEMELEMENTCODE,
--        X.ITEMELEMENTCODE,
--        STOCKTRANSACTION.CUTORGTRTRANSACTIONNUMBER
--) B ON STOCKTRANSACTION.ITEMELEMENTCODE = B.ITEMELEMENTCODE
LEFT JOIN (
    SELECT
        PRODUCTIONDEMAND.CODE,
        PRODUCTIONDEMAND.ABSUNIQUEID,
        ADSTORAGE.VALUESTRING
    FROM
        PRODUCTIONDEMAND PRODUCTIONDEMAND
    LEFT JOIN ADSTORAGE ADSTORAGE ON PRODUCTIONDEMAND.ABSUNIQUEID = ADSTORAGE.UNIQUEID
    WHERE
        ADSTORAGE.NAMENAME = 'MachineNo') C ON C.CODE = SUBSTR(STOCKTRANSACTION.ITEMELEMENTCODE, 1, 8) OR C.CODE = SUBSTR(B.ELEMENT_ASLI, 1, 8)
WHERE
    STOCKTRANSACTION.ONHANDUPDATE > 1
    AND (STOCKTRANSACTION.ITEMTYPECODE = 'KGF'
        OR STOCKTRANSACTION.ITEMTYPECODE = 'FKG');