DROP VIEW ITXVIEWRATAPAKAIBULAN_PR;
--CREATE VIEW ITXVIEWRATAPAKAIBULAN_PR AS  
SELECT
    s.DECOSUBCODE01,
    s.DECOSUBCODE02,
    s.DECOSUBCODE03,
    s.DECOSUBCODE04,
    s.DECOSUBCODE05,
    s.DECOSUBCODE06,
    SUM(s.USERPRIMARYQUANTITY) AS total_pakai,
    MONTH(CURRENT DATE) AS bulan_berjalan,
    CEILING(
        SUM(s.USERPRIMARYQUANTITY) / 
        CASE 
            WHEN MONTH(CURRENT DATE) = 0 THEN 1
            ELSE MONTH(CURRENT DATE)
        END
    ) AS rata_per_bulan
FROM
    STOCKTRANSACTION s
WHERE 
    s.ITEMTYPECODE = 'SPR'
    AND YEAR(s.TRANSACTIONDATE) = YEAR(CURRENT DATE)
    AND (
	        (
	            s.DECOSUBCODE01 = 'KNT'
	            AND s.LOGICALWAREHOUSECODE IN ('M211', 'P211')
	            AND s.TEMPLATECODE = '098'
	        )
	        OR
	        (
	            s.DECOSUBCODE01 = 'MTC'
	            AND s.LOGICALWAREHOUSECODE = 'M201'
	            AND s.TEMPLATECODE = '201'
	        )
	    )
--    AND s.DECOSUBCODE02 = 'TOOTHBELT'
--    AND s.DECOSUBCODE03 = 'LOC'
--    AND s.DECOSUBCODE04 = 'TBE-004A'
--    AND s.DECOSUBCODE05 = 'MEGADYNE'
--    AND s.DECOSUBCODE06 = '8800MM'
GROUP BY
    s.DECOSUBCODE01,
    s.DECOSUBCODE02,
    s.DECOSUBCODE03,
    s.DECOSUBCODE04,
    s.DECOSUBCODE05,
    s.DECOSUBCODE06;