DROP VIEW ITXVIEW_SUB_KK_TAS;
--CREATE VIEW ITXVIEW_SUB_KK_TAS AS
SELECT
    P1.CODE AS NO_DEMAND,
    P2.PRODUCTIONDEMANDCODE,
    P1.USERPRIMARYQUANTITY AS QTY,
    P1.USERSECONDARYQUANTITY AS QTY2,
    P1.USERSECONDARYUOMCODE AS SATUAN,
    P1.CUSTOMERCODE,
    ITXVIEW_JENISBENANG.DESCRIP,
    P1.SUBCODE01,
    P1.SUBCODE02,
    P1.SUBCODE03,
    P1.SUBCODE04,
    P1.SUBCODE05,
    P1.SUBCODE06,
    P1.SUBCODE07,
    P1.ABSUNIQUEID
FROM
    PRODUCTIONDEMAND P1
LEFT JOIN PRODUCTIONDEMANDSTEP P2 ON P2.PRODUCTIONDEMANDCODE = P1.CODE
LEFT JOIN ITXVIEW_JENISBENANG ITXVIEW_JENISBENANG ON P1.SUBCODE01 = ITXVIEW_JENISBENANG.SUBCODE01
											    AND P1.SUBCODE02 = ITXVIEW_JENISBENANG.SUBCODE02
											    AND P1.SUBCODE03 = ITXVIEW_JENISBENANG.SUBCODE03
											    AND P1.SUBCODE04 = ITXVIEW_JENISBENANG.SUBCODE04
GROUP BY
    P1.CODE,
    P2.PRODUCTIONDEMANDCODE,
    P1.USERPRIMARYQUANTITY,
    P1.USERSECONDARYQUANTITY,
    P1.USERSECONDARYUOMCODE,
    P1.CUSTOMERCODE,
    ITXVIEW_JENISBENANG.DESCRIP,
    P1.SUBCODE03,
    P1.SUBCODE01,
    P1.SUBCODE02,
    P1.SUBCODE04,
    P1.SUBCODE05,
    P1.SUBCODE06,
    P1.SUBCODE07,
    P1.ABSUNIQUEID;