DROP VIEW ITXVIEW_POSISIKK_TGL_IN_PRODORDER;
--CREATE VIEW ITXVIEW_POSISIKK_TGL_IN_PRODORDER AS
SELECT
	DISTINCT 
    v.PRODUCTIONORDERCODE,
	p.PROPROGRESSPROGRESSNUMBER,
	p.DEMANDSTEPSTEPNUMBER,
	p2.PROGRESSTEMPLATECODE,
	(p2.PROGRESSSTARTPROCESSDATE || ' ' || p2.PROGRESSSTARTPROCESSTIME) AS MULAI
FROM
	PRODUCTIONDEMANDSTEP v
LEFT JOIN PRODUCTIONPROGRESSSTEPUPDATED p ON p.DEMANDSTEPPRODUCTIONDEMANDCODE = v.PRODUCTIONDEMANDCODE
RIGHT JOIN PRODUCTIONPROGRESS p2 ON p2.PROGRESSNUMBER = p.PROPROGRESSPROGRESSNUMBER AND p2.PROGRESSTEMPLATECODE = 'S01'
WHERE 
	p2.INACTIVE = 1
--	v.PRODUCTIONORDERCODE  = '00079563' 
--		AND p.DEMANDSTEPSTEPNUMBER = '600'