-- DB2ADMIN.ITXVIEWPOGREIGENEW3 source
DROP VIEW ITXVIEWPOGREIGENEW3;
--CREATE VIEW ITXVIEWPOGREIGENEW3 AS   
SELECT 
    SALESORDERLINE.SALESORDERCODE,
    SALESORDERLINE.ORDERLINE,
    SALESORDERLINE.ITEMTYPEAFICODE,
    SALESORDERLINE.SUBCODE01,
    SALESORDERLINE.SUBCODE02,
    SALESORDERLINE.SUBCODE03,
    SALESORDERLINE.SUBCODE04,
    SALESORDERLINE.SUBCODE05,
    SALESORDERLINE.SUBCODE06,
    SALESORDERLINE.SUBCODE07,
    SALESORDERLINE.SUBCODE08,
    SALESORDERLINE.CREATIONDATETIME,
    SALESORDERLINE.ABSUNIQUEID,
    LISTAGG(DISTINCT(TRIM(A.PROJECTCODE)), ',') AS PROJECTCODE,
    LISTAGG(TRIM(A.LOTCODE), ',') AS LOTCODE,
    C.CREMARKS,
    CASE
        WHEN D.KAIN_AKJ = '1' THEN NULL
        WHEN C.CREMARKS LIKE '%AKJ%' THEN NULL
        ELSE B.CODE
    END AS DEMAND_KGF
FROM
    SALESORDERLINE SALESORDERLINE
LEFT JOIN PRODUCTIONDEMAND PRODUCTIONDEMAND ON SALESORDERLINE.SALESORDERCODE = PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE AND SALESORDERLINE.ORDERLINE = PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE
LEFT JOIN ALLOCATION ALLOCATION ON PRODUCTIONDEMAND.CODE = ALLOCATION.ORDERCODE
LEFT JOIN (
    SELECT
        ALLOCATION.CODE,
        ALLOCATION.LOTCODE,
        ALLOCATION.PROJECTCODE
    FROM
        ALLOCATION ALLOCATION
    WHERE
        ALLOCATION.STOCKTYPECODE = 'AFW'
        AND ALLOCATION.ITEMTYPECODE = 'KGF') A ON ALLOCATION.CODE = A.CODE
LEFT JOIN (
    SELECT
        PRODUCTIONDEMAND.CODE,
        PRODUCTIONDEMAND.ITEMTYPEAFICODE,
        PRODUCTIONDEMAND.SUBCODE01,
        PRODUCTIONDEMAND.SUBCODE02,
        PRODUCTIONDEMAND.SUBCODE03,
        PRODUCTIONDEMAND.SUBCODE04,
        PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE,
        PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE
    FROM
        PRODUCTIONDEMAND PRODUCTIONDEMAND
    WHERE
        PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'KGF' ) B ON B.SUBCODE01 = SALESORDERLINE.SUBCODE01 
        											AND B.SUBCODE02 = SALESORDERLINE.SUBCODE02
    												AND B.SUBCODE03 = SALESORDERLINE.SUBCODE03 
    												AND B.ORIGDLVSALORDLINESALORDERCODE = SALESORDERLINE.SALESORDERCODE
    												AND B.ORIGDLVSALORDERLINEORDERLINE = SALESORDERLINE.ORDERLINE 
LEFT JOIN (
    SELECT
        ADSTORAGE.UNIQUEID,
        ADSTORAGE.VALUESTRING AS CREMARKS
    FROM
        ADSTORAGE ADSTORAGE
    WHERE
        ADSTORAGE.NAMENAME = 'ColorRemarks') C ON SALESORDERLINE.ABSUNIQUEID = C.UNIQUEID
LEFT JOIN (
    SELECT
        ADSTORAGE.UNIQUEID,
        ADSTORAGE.VALUESTRING AS KAIN_AKJ
    FROM
        ADSTORAGE ADSTORAGE
    WHERE
        ADSTORAGE.NAMENAME = 'KainAKJ') D ON SALESORDERLINE.ABSUNIQUEID = D.UNIQUEID
WHERE
    A.LOTCODE IS NOT NULL
    OR A.PROJECTCODE IS NOT NULL
    OR B.CODE IS NOT NULL
GROUP BY
    SALESORDERLINE.SALESORDERCODE,
    SALESORDERLINE.ORDERLINE,
    SALESORDERLINE.ITEMTYPEAFICODE,
    SALESORDERLINE.SUBCODE01,
    SALESORDERLINE.SUBCODE02,
    SALESORDERLINE.SUBCODE03,
    SALESORDERLINE.SUBCODE04,
    SALESORDERLINE.SUBCODE05,
    SALESORDERLINE.SUBCODE06,
    SALESORDERLINE.SUBCODE07,
    SALESORDERLINE.SUBCODE08,
    SALESORDERLINE.CREATIONDATETIME,
    SALESORDERLINE.ABSUNIQUEID,
    B.CODE,
    C.CREMARKS,
    D.KAIN_AKJ;