DROP VIEW ITXVIEWMASTERSUHU;
--CREATE VIEW ITXVIEWMASTERSUHU AS
SELECT
	TRIM(p.SUBCODE01) AS SUBCODE01,
	TRIM(p.SUBCODE02) AS SUBCODE02,
	TRIM(p.SUBCODE03) AS SUBCODE03,
	TRIM(p.SUBCODE05) AS SUBCODE05,
	TRIM(p.SUBCODE01) || '-' || TRIM(p.SUBCODE02) || '-' || TRIM(p.SUBCODE03) AS PRODUCT_MASTER,
	TRIM(p.SUBCODE05) AS NO_WARNA,
	u.LONGDESCRIPTION AS NAMA_WARNA,
	LISTAGG(DISTINCT TRIM(r.SUBCODE01), CHR(10)) AS RECIPE_CODE,
	LISTAGG(DISTINCT TRIM(r2.COMMENTLINE), CHR(10)) AS TEMPERATUR
FROM
	PRODUCT p
LEFT JOIN USERGENERICGROUP u ON u.USERGENERICGROUPTYPECODE = 'CL1' AND u.CODE = p.SUBCODE05
LEFT JOIN RECIPE r ON r.SUBCODE01 LIKE '%' || TRIM(p.SUBCODE03) || '/' || TRIM(p.SUBCODE05) || '%'
	AND r.SUFFIXCODE = '001'
LEFT JOIN RECIPECOMPONENT r2 ON r2.RECIPENUMBERID = r.NUMBERID 
	AND r2.RECIPEITEMTYPECODE = 'RFD' 
	AND r2.GROUPNUMBER = '20'
WHERE 
	p.ITEMTYPECODE = 'KFF'
--	AND p.CREATIONDATETIME > '2025-04-01-00.00.00.000000'
--	AND p.SUBCODE01 = 'CVC'
--	AND p.SUBCODE02 = 'F3C'
	AND p.SUBCODE03 = '22006'
	AND p.SUBCODE05 = '250366D'
GROUP BY
	p.SUBCODE01,
	p.SUBCODE02,
	p.SUBCODE03, 
	p.SUBCODE05,
	u.LONGDESCRIPTION