DROP VIEW ITXVIEW_CHECK_ALOKASI_QTYBRUTO; -- CEK QTY ALOKASI DAN QTY BRUTO
--CREATE VIEW ITXVIEW_CHECK_ALOKASI_QTYBRUTO AS
SELECT  
	ibn.SALESORDERCODE,
	ibn.ORDERLINE,
	CASE
		WHEN SUM(ibn.QTY_ALOKASI_BRUTO) = i.USERPRIMARYQUANTITY THEN 'SAMA'
		WHEN SUM(ibn.QTY_ALOKASI_BRUTO) > i.USERPRIMARYQUANTITY THEN 'LEBIH BESAR'
		ELSE 'KURANG DARI'
	END	AS KET_BRUTO
FROM 
	ITXVIEW_BOOKING_NEW ibn 
LEFT JOIN ITXVIEWKGBRUTOBONORDER2 i ON i.ORIGDLVSALORDLINESALORDERCODE = ibn.SALESORDERCODE AND i.ORIGDLVSALORDERLINEORDERLINE = ibn.ORDERLINE 
WHERE 
	ibn.SALESORDERCODE = 'DOM2300726' AND ibn.ORDERLINE = 70
GROUP BY 
	i.USERPRIMARYQUANTITY,
	ibn.SALESORDERCODE,
	ibn.ORDERLINE