DROP VIEW ITXVIEW_DENSITY;
CREATE VIEW ITXVIEW_DENSITY AS
SELECT 
	p2.CODE,
	p2.SUBCODE02 AS SUBCODE02_DEMAND,
	p.SUBCODE02 AS SUBCODE02_SPECS,
	a.VALUEDECIMAL 
FROM 
	PRODUCTIONSPECS p 
LEFT JOIN PRODUCTIONDEMAND p2 ON p2.SUBCODE02 = p.SUBCODE02
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p.ABSUNIQUEID AND a.FIELDNAME = 'Density'
WHERE 
	p.OPERATIONCODE = 'SWN1' AND p.ITEMTYPEAFICODE = 'DYR'