-- DB2ADMIN.ITXVIEWALURPROSESBONORDER source
DROP VIEW ITXVIEWALURPROSESBONORDER;
--CREATE VIEW ITXVIEWALURPROSESBONORDER AS 
SELECT
	PRODUCTIONDEMANDCODE,
	ITEMTYPEAFICODE AS ITEMTYPECODE,
    SUBCODE01,
    SUBCODE02,
    SUBCODE03,
    SUBCODE04,
    SUBCODE05,
    SUBCODE06,
    SUBCODE07,
    SUBCODE08,
    SUBCODE09,
    SUBCODE10,
	LISTAGG(ALUR, '-') AS ALUR
FROM 
	(SELECT
	    TRIM(p.PRODUCTIONDEMANDCODE) AS PRODUCTIONDEMANDCODE,
	    p2.ITEMTYPEAFICODE,
	    p2.SUBCODE01,
	    p2.SUBCODE02,
	    p2.SUBCODE03,
	    p2.SUBCODE04,
	    p2.SUBCODE05,
	    p2.SUBCODE06,
	    p2.SUBCODE07,
	    p2.SUBCODE08,
	    p2.SUBCODE09,
	    p2.SUBCODE10,
	    TRIM(p.OPERATIONCODE) AS ALUR
	FROM
	    PRODUCTIONDEMANDSTEP p 
	LEFT JOIN PRODUCTIONDEMAND p2 ON p2.CODE = p.PRODUCTIONDEMANDCODE
	WHERE 
		p.PRODUCTIONDEMANDCODE = '00191961'  
	ORDER BY
		p.STEPNUMBER ASC)
GROUP BY
	PRODUCTIONDEMANDCODE,
	ITEMTYPEAFICODE,
    SUBCODE01,
    SUBCODE02,
    SUBCODE03,
    SUBCODE04,
    SUBCODE05,
    SUBCODE06,
    SUBCODE07,
    SUBCODE08,
    SUBCODE09,
    SUBCODE10