--CREATE VIEW ITXVIEWPOGREIGE AS
SELECT
    ALLOCATION.LOTCODE,
    ALLOCATION.ITEMTYPECODE,
    ALLOCATION.DECOSUBCODE01,
    ALLOCATION.DECOSUBCODE02,
    ALLOCATION.DECOSUBCODE03,
    ALLOCATION.DECOSUBCODE04,
    ALLOCATION.PROJECTCODE,
    ALLOCATION.THEORETICISSUEDATE 
FROM
    ALLOCATION ALLOCATION
WHERE
    ALLOCATION.ITEMTYPECODE = 'KGF'
    AND ALLOCATION.STOCKTYPECODE = 'AFW'
GROUP BY
    ALLOCATION.LOTCODE,
    ALLOCATION.ITEMTYPECODE,
    ALLOCATION.STOCKTYPECODE,
    ALLOCATION.DECOSUBCODE01,
    ALLOCATION.DECOSUBCODE02,
    ALLOCATION.DECOSUBCODE03,
    ALLOCATION.DECOSUBCODE04,
    ALLOCATION.PROJECTCODE,
    ALLOCATION.THEORETICISSUEDATE 