DROP VIEW ITXVIEW_OPENTICKET_MTC;
--CREATE VIEW ITXVIEW_OPENTICKET_MTC AS
SELECT 
	p.CODE,
	p.CREATIONUSER,
	p.CREATIONDATETIME,
	p.PMBOMCODE,
	p.DEPARTMENTCODE,
	d.LONGDESCRIPTION AS DEPTNAME,
	p.RESPONSIBLEOFSCHEDULINGUSERID,
	p.DEFAULTASSIGNEDTOUSERID,
	CASE
		WHEN p.PRIORITYLEVEL = '0' THEN 'Very High'
		WHEN p.PRIORITYLEVEL = '1' THEN 'High'
		WHEN p.PRIORITYLEVEL = '2' THEN 'Medium'
		WHEN p.PRIORITYLEVEL = '3' THEN 'Normal'
		WHEN p.PRIORITYLEVEL = '4' THEN 'Low'
	END AS PRIORITYLEVEL,	
	CASE
		WHEN p.STATUS = '1' THEN 'Open'
		WHEN p.STATUS = '2' THEN 'In Progress'
		WHEN p.STATUS = '3' THEN 'Closed'
		WHEN p.STATUS = '4' THEN 'Suspended'
	END AS STATUS,
	p.SYMPTOM AS PERMASALAHAN,
	p2.REMARKS AS PERBAIKAN
FROM 
	PMBREAKDOWNENTRY p 
LEFT JOIN PMWORKORDER p2 ON p2.PMBREAKDOWNENTRYCODE  = p.CODE
LEFT JOIN DEPARTMENT d ON d.CODE = p.DEPARTMENTCODE 
WHERE
	TRIM(p.DEPARTMENTCODE) = 'D005' AND p.STATUS = '1'
	
	SELECT * FROM ITXVIEW_OPENTICKET_MTC WHERE TRIM(DEPARTMENTCODE) = 'D005' ORDER BY CODE ASC