DROP VIEW ITXVIEWSALESDOCUMENT;
--CREATE VIEW ITXVIEWSALESDOCUMENT AS
SELECT
    SALESDOCUMENT.PROVISIONALDOCUMENTDATE,
    SALESDOCUMENT.PROVISIONALCODE,
    SALESDOCUMENT.GOODSISSUEDATE,
    CASE
        WHEN SALESDOCUMENT.PROGRESSSTATUS = '0' THEN 'Entered'
        WHEN SALESDOCUMENT.PROGRESSSTATUS = '1' THEN 'Partially shipped'
        WHEN SALESDOCUMENT.PROGRESSSTATUS = '2' THEN 'Shipped'
    END AS PROGRESS,
    SALESDOCUMENT.ORDPRNCUSTOMERSUPPLIERCODE,
    A.LOTCODE
FROM
    SALESDOCUMENT SALESDOCUMENT
LEFT JOIN ALLOCATION ALLOCATION ON
    ALLOCATION.ORDERCODE = SALESDOCUMENT.PROVISIONALCODE
LEFT JOIN (
        SELECT
            ALLOCATION.CODE,
            ALLOCATION.LOTCODE
        FROM
            ALLOCATION ALLOCATION
        WHERE
            ALLOCATION.DETAILTYPE = '0'
    ) A ON
    ALLOCATION.CODE = A.CODE
WHERE
    SALESDOCUMENT.DOCUMENTTYPETYPE = '05'
GROUP BY
    SALESDOCUMENT.PROVISIONALDOCUMENTDATE,
    SALESDOCUMENT.PROVISIONALCODE,
    SALESDOCUMENT.GOODSISSUEDATE,
    SALESDOCUMENT.PROGRESSSTATUS,
    SALESDOCUMENT.ORDPRNCUSTOMERSUPPLIERCODE,
    A.LOTCODE;