DROP VIEW ITXVIEW_ALLOCATION_2;
--CREATE VIEW ITXVIEW_ALLOCATION_2 AS
SELECT
	DISTINCT 
	utama.CODE,
	iasp.LOTCODE,
	utama.USERPRIMARYQUANTITY_NON_FOC,
	utama.USERPRIMARYQUANTITY_NON_FOC - FOC_KG AS USERPRIMARYQUANTITY,
	utama.USERSECONDARYQUANTITY_NON_FOC,
	utama.USERSECONDARYQUANTITY_NON_FOC - FOC_YARD AS USERSECONDARYUSEDQUANTITY,
	utama.QUALITYREASON,
	utama.JML_FOC_KG,
	utama.JML_FOC_YARD,
	utama.ORDERCODE,
	utama.ORDERLINE,
	utama.PROJECTCODE,
	utama.ALLOCATIONDATE,
	utama.DECOSUBCODE01,
	utama.DECOSUBCODE02,
	utama.DECOSUBCODE03,
	utama.DECOSUBCODE04,
	utama.DECOSUBCODE05,
	utama.DECOSUBCODE06,
	utama.JENIS_KAIN,
	utama.NO_ITEM,
	utama.EXTERNALREFERENCE
FROM
	(
		SELECT
			ALLOCATION.CODE AS CODE,
			ALLOCATION.LOTCODE,
			ALLOCATION.USERPRIMARYQUANTITY AS USERPRIMARYQUANTITY_NON_FOC,
			ALLOCATION.USERSECONDARYUSEDQUANTITY AS USERSECONDARYQUANTITY_NON_FOC,
			CASE
				WHEN (ITXVIEW_DETAIL_FOC_INVOICE2.FOC_KG) IS NULL THEN 0
				ELSE (ITXVIEW_DETAIL_FOC_INVOICE2.FOC_KG)
			END AS FOC_KG,
			ITXVIEW_DETAIL_FOC_INVOICE2.FOC_KG AS JML_FOC_KG,
			CASE
				WHEN (ITXVIEW_DETAIL_FOC_INVOICE2.FOC_YARD) IS NULL THEN 0
				ELSE (ITXVIEW_DETAIL_FOC_INVOICE2.FOC_YARD)
			END AS FOC_YARD,
			ITXVIEW_DETAIL_FOC_INVOICE2.FOC_YARD AS JML_FOC_YARD,
			--    ITXVIEW_DETAIL_FOC_INVOICE.UNIT_FOC,
			ITXVIEW_DETAIL_FOC_INVOICE2.QUALITYREASON AS QUALITYREASON,
			ALLOCATION.ORDERCODE AS ORDERCODE,
			ALLOCATION.ORDERLINE AS ORDERLINE,
			ALLOCATION.PROJECTCODE AS PROJECTCODE,
			ALLOCATION.ALLOCATIONDATE AS ALLOCATIONDATE,
			ALLOCATION.DECOSUBCODE01 AS DECOSUBCODE01,
			ALLOCATION.DECOSUBCODE02 AS DECOSUBCODE02,
			ALLOCATION.DECOSUBCODE03 AS DECOSUBCODE03,
			ALLOCATION.DECOSUBCODE04 AS DECOSUBCODE04,
			ALLOCATION.DECOSUBCODE05 AS DECOSUBCODE05,
			ALLOCATION.DECOSUBCODE06 AS DECOSUBCODE06,
			ALLOCATION.CUSTOMERCODE AS CUSTOMERCODE,
			PRODUCT.LONGDESCRIPTION AS JENIS_KAIN,
			a.EXTERNALITEMCODE AS NO_ITEM,
			a.EXTERNALREFERENCE AS EXTERNALREFERENCE
		FROM
			ALLOCATION ALLOCATION
		LEFT JOIN ITXVIEW_DETAIL_FOC_INVOICE2 ITXVIEW_DETAIL_FOC_INVOICE2 ON ALLOCATION.CODE = ITXVIEW_DETAIL_FOC_INVOICE2.CODE
			AND ALLOCATION.ORDERCODE = ITXVIEW_DETAIL_FOC_INVOICE2.NO_SJ
		LEFT JOIN PRODUCT PRODUCT ON ALLOCATION.ITEMTYPECODE = PRODUCT.ITEMTYPECODE
			AND ALLOCATION.DECOSUBCODE01 = PRODUCT.SUBCODE01
			AND ALLOCATION.DECOSUBCODE02 = PRODUCT.SUBCODE02
			AND ALLOCATION.DECOSUBCODE03 = PRODUCT.SUBCODE03
			AND ALLOCATION.DECOSUBCODE04 = PRODUCT.SUBCODE04
			AND ALLOCATION.DECOSUBCODE05 = PRODUCT.SUBCODE05
			AND ALLOCATION.DECOSUBCODE06 = PRODUCT.SUBCODE06
			AND ALLOCATION.DECOSUBCODE07 = PRODUCT.SUBCODE07
			AND ALLOCATION.DECOSUBCODE08 = PRODUCT.SUBCODE08
		LEFT JOIN ITXVIEWORDERPARTNERLINKACTIVE a ON ALLOCATION.CUSTOMERCODE = a.ORDPRNCUSTOMERSUPPLIERCODE
			AND ALLOCATION.ITEMTYPECODE = a.ITEMTYPEAFICODE
			AND ALLOCATION.DECOSUBCODE01 = a.SUBCODE01
			AND ALLOCATION.DECOSUBCODE02 = a.SUBCODE02
			AND ALLOCATION.DECOSUBCODE03 = a.SUBCODE03
			AND ALLOCATION.DECOSUBCODE04 = a.SUBCODE04
			AND ALLOCATION.DECOSUBCODE05 = a.SUBCODE05
			AND ALLOCATION.DECOSUBCODE06 = a.SUBCODE06
			AND ALLOCATION.DECOSUBCODE07 = a.SUBCODE07
		WHERE
			ALLOCATION.DETAILTYPE = '1'
			AND
    		ALLOCATION.ORIGINTRNTRANSACTIONNUMBER IS NULL
			AND
    		ALLOCATION.DESTINATIONTYPE = '7'
			--                                    AND
			--                                    ALLOCATION.ORDERCODE = 'ESP2300431'  
			--                            AND ALLOCATION.CODE IN ('000000396037', '000000396038', '000000396042', '000000396043', '000000396047', '000000396048')
			--    AND NOT ITXVIEW_DETAIL_FOC_INVOICE.QUALITYREASON = 'FOC'
	) utama
LEFT JOIN ITXVIEW_ALLOCATION_SURATJALAN_PPC iasp ON iasp.CODE = utama.CODE
--WHERE
--	utama.ORDERCODE = 'POD2305174'