DROP VIEW ITXVIEW_POSISIKK_TGL_IN_PRODORDER;
--CREATE VIEW ITXVIEW_POSISIKK_TGL_IN_PRODORDER AS
SELECT
	DISTINCT 
    v.PRODUCTIONORDERCODE,
	p.PROPROGRESSPROGRESSNUMBER,
	p.DEMANDSTEPSTEPNUMBER,
	p2.PROGRESSTEMPLATECODE,
	p2.PROGRESSSTARTPROCESSDATE,
	p2.PROGRESSSTARTPROCESSTIME,
	(p2.PROGRESSSTARTPROCESSDATE || ' ' || p2.PROGRESSSTARTPROCESSTIME) AS MULAI,
	p2.MACHINECODE,
	p2.INACTIVE,
	r.LONGDESCRIPTION  
FROM
	PRODUCTIONDEMANDSTEP v
LEFT JOIN PRODUCTIONPROGRESSSTEPUPDATED p ON p.DEMANDSTEPPRODUCTIONDEMANDCODE = v.PRODUCTIONDEMANDCODE
RIGHT JOIN PRODUCTIONPROGRESS p2 ON p2.PROGRESSNUMBER = p.PROPROGRESSPROGRESSNUMBER AND p2.PROGRESSTEMPLATECODE = 'S01'
LEFT JOIN RESOURCES r ON r.CODE = p2.OPERATORCODE
WHERE 
	p2.INACTIVE = 1 
	AND p2.PROGRESSSTARTPROCESSDATE BETWEEN '2024-01-01' AND '2024-01-03'
--	AND v.PRODUCTIONORDERCODE  = '00084354' 
--		AND p.DEMANDSTEPSTEPNUMBER = '600'