DROP VIEW ITXVIEW_RESERVATION;
--CREATE VIEW ITXVIEW_RESERVATION AS
SELECT
	p.PRODUCTIONORDERCODE,
	v2.ORDERCODE,
	p.GROUPLINE,
	p.ITEMTYPEAFICODE,
	p.USERPRIMARYQUANTITY,
	p.PRODRESERVATIONLINKGROUPCODE,
	v.INITIALUSERPRIMARYQUANTITY,
	p.USEDUSERPRIMARYQUANTITY,
	p.USERSECONDARYQUANTITY,
	p.USERSECONDARYUOMCODE,
	p.PICKUPQUANTITY,
	v2.SUBCODE01,
	v2.SUBCODE02,
	v2.SUBCODE03,
	v2.SUBCODE04,
	v2.SUBCODE05,
	v2.SUBCODE06,
	v2.SUBCODE07
FROM
     VIEWPRODUCTIONRESERVATION p 
RIGHT JOIN PRODUCTIONRESERVATION v2 ON v2.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE 
LEFT JOIN VIEWPRODUCTIONDEMANDSTEP v ON v.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND v.PRODRESERVATIONLINKGROUPCODE = p.PRODRESERVATIONLINKGROUPCODE
--WHERE 
--	v2.ORDERCODE = '00045993'  
--p.PRODUCTIONORDERCODE = '00017687'
GROUP BY 
	p.PRODUCTIONORDERCODE,
	v2.ORDERCODE,
	p.GROUPLINE,
	p.ITEMTYPEAFICODE,
	p.USERPRIMARYQUANTITY,
	p.PRODRESERVATIONLINKGROUPCODE,
	v.INITIALUSERPRIMARYQUANTITY,
	p.USEDUSERPRIMARYQUANTITY,
	p.USERSECONDARYQUANTITY,
	p.USERSECONDARYUOMCODE,
	p.PICKUPQUANTITY,
	v2.SUBCODE01,
	v2.SUBCODE02,
	v2.SUBCODE03,
	v2.SUBCODE04,
	v2.SUBCODE05,
	v2.SUBCODE06,
	v2.SUBCODE07