DROP VIEW ITXVIEW_POSISIKK_TGL_OUT_PRODORDER;
CREATE VIEW ITXVIEW_POSISIKK_TGL_OUT_PRODORDER AS
SELECT 
	DISTINCT 
	v.PRODUCTIONORDERCODE,
    p.PROPROGRESSPROGRESSNUMBER,
    p.DEMANDSTEPSTEPNUMBER,
    (p2.PROGRESSENDDATE || ' ' || PROGRESSENDTIME) AS SELESAI
FROM PRODUCTIONDEMANDSTEP v 
LEFT JOIN PRODUCTIONPROGRESSSTEPUPDATED p ON p.DEMANDSTEPPRODUCTIONDEMANDCODE = v.PRODUCTIONDEMANDCODE 
RIGHT JOIN PRODUCTIONPROGRESS p2 ON p2.PROGRESSNUMBER = p.PROPROGRESSPROGRESSNUMBER AND p2.PROGRESSTEMPLATECODE = 'E01'
--WHERE v.PRODUCTIONORDERCODE  = '$rowdb2[PRODUCTIONORDERCODE]' AND p.DEMANDSTEPSTEPNUMBER = '$rowdb2[STEPNUMBER]'