DROP VIEW ITXVIEWLABCOLORQLT_DETAIL;
--CREATE VIEW ITXVIEWLABCOLORQLT_DETAIL AS
SELECT
	DISTINCT 
	QUALITYDOCUMENT.LOTCODE,
	QUALITYDOCLINE.QUALITYDOCUMENTHEADERLINE,
    QUALITYDOCLINE_LABCOLOUR.ANNOTATION AS LABCOLOUR,
    QUALITYDOCLINE_LABCLRNUM.ANNOTATION AS LABCLRNUM,
    QUALITYDOCLINE_LABCAT.ANNOTATION AS LABCAT,
    QUALITYDOCLINE_LABBLEED.ANNOTATION AS LABBLEED,
    QUALITYDOCLINE_LABDYEMIG.ANNOTATION AS LABDYEMIG,
    QUALITYDOCLINE_LABPHEN.ANNOTATION AS LABPHEN,
    QUALITYDOCLINE_LABTRANS.ANNOTATION AS LABTRANS,
    QUALITYDOCLINE_LABPLIGHT.ANNOTATION AS LABPLIGHT,
    QUALITYDOCLINE_LABCHLOR.ANNOTATION AS LABCHLOR,
	QUALITYDOCLINE_LABCOLOUR_QTY.VALUEQUANTITY AS LABCOLOUR_QTY,
    QUALITYDOCLINE_LABCLRNUM_QTY.VALUEQUANTITY AS LABCLRNUM_QTY,
    QUALITYDOCLINE_LABCAT_QTY.VALUEQUANTITY AS LABCAT_QTY,
    QUALITYDOCLINE_LABDIPCLRF_QTY.VALUEQUANTITY AS LABDIPCLRF_QTY,
    QUALITYDOCLINE_LABDIPCLRW_QTY.VALUEQUANTITY AS LABDIPCLRW_QTY,
    QUALITYDOCLINE_LABDIPCLRP_QTY.VALUEQUANTITY AS LABDIPCLRP_QTY,
    QUALITYDOCLINE_LABCLRSWH_QTY.VALUEQUANTITY AS LABCLRSWH_QTY,
    QUALITYDOCLINE_LABCLRSWR_QTY.VALUEQUANTITY AS LABCLRSWR_QTY,
    QUALITYDOCLINE_LABCLRPR_QTY.VALUEQUANTITY AS LABCLRPR_QTY,
    QUALITYDOCLINE_LABCLRSWHN_QTY.VALUEQUANTITY AS LABCLRSWHN_QTY,
    QUALITYDOCLINE_LABCLRSWRN_QTY.VALUEQUANTITY AS LABCLRSWRN_QTY,
    QUALITYDOCLINE_LABCLRPRN_QTY.VALUEQUANTITY AS LABCLRPRN_QTY,
    QUALITYDOCLINE_LABCLRSWHP_QTY.VALUEQUANTITY AS LABCLRSWHP_QTY,
    QUALITYDOCLINE_LABCLRSWRP_QTY.VALUEQUANTITY AS LABCLRSWRP_QTY,
    QUALITYDOCLINE_LABCLRPRP_QTY.VALUEQUANTITY AS LABCLRPRP_QTY,
    QUALITYDOCLINE_LABCRKDRY_QTY.VALUEQUANTITY AS LABCRKDRY_QTY,
    QUALITYDOCLINE_LABCRKWET_QTY.VALUEQUANTITY AS LABCRKWET_QTY,
    QUALITYDOCLINE_LABLIGHT_QTY.ANNOTATION AS LABLIGHT_QTY,
    QUALITYDOCLINE_LABBLEED_QTY.ANNOTATION AS LABBLEED_QTY,
    QUALITYDOCLINE_LABDYEMIG_QTY.ANNOTATION AS LABDYEMIG_QTY,
    QUALITYDOCLINE_LABPHEN_QTY.ANNOTATION AS LABPHEN_QTY,
    QUALITYDOCLINE_LABTRANS_QTY.ANNOTATION AS LABTRANS_QTY,
    QUALITYDOCLINE_LABPLIGHT_QTY.ANNOTATION AS LABPLIGHT_QTY,
    QUALITYDOCLINE_LABCHLOR_QTY.ANNOTATION AS LABCHLOR_QTY
FROM
    QUALITYDOCUMENT QUALITYDOCUMENT
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE ON QUALITYDOCLINE.QUALITYDOCUMENTHEADERLINE  = QUALITYDOCUMENT.HEADERLINE
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCOLOUR ON QUALITYDOCLINE_LABCOLOUR.QUALITYDOCUMENTHEADERLINE  = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCOLOUR.CHARACTERISTICCODE = 'LABCOLOUR'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRNUM ON QUALITYDOCLINE_LABCLRNUM.QUALITYDOCUMENTHEADERLINE  = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCLRNUM.CHARACTERISTICCODE = 'LABCLRNUM'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCAT ON QUALITYDOCLINE_LABCAT.QUALITYDOCUMENTHEADERLINE  = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCAT.CHARACTERISTICCODE = 'LABCAT'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABBLEED ON QUALITYDOCLINE_LABBLEED.QUALITYDOCUMENTHEADERLINE  = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABBLEED.CHARACTERISTICCODE = 'LABBLEED'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABDYEMIG ON QUALITYDOCLINE_LABDYEMIG.QUALITYDOCUMENTHEADERLINE  = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABDYEMIG.CHARACTERISTICCODE = 'LABDYEMIG'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABPHEN ON QUALITYDOCLINE_LABPHEN.QUALITYDOCUMENTHEADERLINE  = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABPHEN.CHARACTERISTICCODE = 'LABPHEN'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABTRANS ON QUALITYDOCLINE_LABTRANS.QUALITYDOCUMENTHEADERLINE  = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABTRANS.CHARACTERISTICCODE = 'LABTRANS'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABPLIGHT ON QUALITYDOCLINE_LABPLIGHT.QUALITYDOCUMENTHEADERLINE  = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABPLIGHT.CHARACTERISTICCODE = 'LABPLIGHT'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCHLOR ON QUALITYDOCLINE_LABCHLOR.QUALITYDOCUMENTHEADERLINE  = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCHLOR.CHARACTERISTICCODE = 'LABCHLOR'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCOLOUR_QTY ON QUALITYDOCLINE_LABCOLOUR_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCOLOUR_QTY.CHARACTERISTICCODE = 'LABCOLOUR'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRNUM_QTY ON QUALITYDOCLINE_LABCLRNUM_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCLRNUM_QTY.CHARACTERISTICCODE = 'LABCLRNUM'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCAT_QTY ON QUALITYDOCLINE_LABCAT_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCAT_QTY.CHARACTERISTICCODE = 'LABCAT'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABDIPCLRF_QTY ON QUALITYDOCLINE_LABDIPCLRF_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABDIPCLRF_QTY.CHARACTERISTICCODE = 'LABDIPCLRF'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABDIPCLRW_QTY ON QUALITYDOCLINE_LABDIPCLRW_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABDIPCLRW_QTY.CHARACTERISTICCODE = 'LABDIPCLRW'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABDIPCLRP_QTY ON QUALITYDOCLINE_LABDIPCLRP_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABDIPCLRP_QTY.CHARACTERISTICCODE = 'LABDIPCLRP'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWH_QTY ON QUALITYDOCLINE_LABCLRSWH_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCLRSWH_QTY.CHARACTERISTICCODE = 'LABCLRSWH'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWR_QTY ON QUALITYDOCLINE_LABCLRSWR_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCLRSWR_QTY.CHARACTERISTICCODE = 'LABCLRSWR'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRPR_QTY ON QUALITYDOCLINE_LABCLRPR_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCLRPR_QTY.CHARACTERISTICCODE = 'LABCLRPR'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWHN_QTY ON QUALITYDOCLINE_LABCLRSWHN_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCLRSWHN_QTY.CHARACTERISTICCODE = 'LABCLRSWHN'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWRN_QTY ON QUALITYDOCLINE_LABCLRSWRN_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCLRSWRN_QTY.CHARACTERISTICCODE = 'LABCLRSWRN'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRPRN_QTY ON QUALITYDOCLINE_LABCLRPRN_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCLRPRN_QTY.CHARACTERISTICCODE = 'LABCLRPRN'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWHP_QTY ON QUALITYDOCLINE_LABCLRSWHP_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCLRSWHP_QTY.CHARACTERISTICCODE = 'LABCLRSWHP'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWRP_QTY ON QUALITYDOCLINE_LABCLRSWRP_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCLRSWRP_QTY.CHARACTERISTICCODE = 'LABCLRSWRP'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRPRP_QTY ON QUALITYDOCLINE_LABCLRPRP_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCLRPRP_QTY.CHARACTERISTICCODE = 'LABCLRPRP'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCRKDRY_QTY ON QUALITYDOCLINE_LABCRKDRY_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCRKDRY_QTY.CHARACTERISTICCODE = 'LABCRKDRY'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCRKWET_QTY ON QUALITYDOCLINE_LABCRKWET_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCRKWET_QTY.CHARACTERISTICCODE = 'LABCRKWET'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABLIGHT_QTY ON QUALITYDOCLINE_LABLIGHT_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABLIGHT_QTY.CHARACTERISTICCODE = 'LABLIGHT'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABBLEED_QTY ON QUALITYDOCLINE_LABBLEED_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABBLEED_QTY.CHARACTERISTICCODE = 'LABBLEED'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABDYEMIG_QTY ON QUALITYDOCLINE_LABDYEMIG_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABDYEMIG_QTY.CHARACTERISTICCODE = 'LABDYEMIG'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABPHEN_QTY ON QUALITYDOCLINE_LABPHEN_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABPHEN_QTY.CHARACTERISTICCODE = 'LABPHEN'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABTRANS_QTY ON QUALITYDOCLINE_LABTRANS_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABTRANS_QTY.CHARACTERISTICCODE = 'LABTRANS'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABPLIGHT_QTY ON QUALITYDOCLINE_LABPLIGHT_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABPLIGHT_QTY.CHARACTERISTICCODE = 'LABPLIGHT'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCHLOR_QTY ON QUALITYDOCLINE_LABCHLOR_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE AND QUALITYDOCLINE_LABCHLOR_QTY.CHARACTERISTICCODE = 'LABCHLOR'
WHERE
    QUALITYDOCLINE_LABCOLOUR.QUALITYDOCUMENTHEADERCODE = 'LABDIP' 
--    AND QUALITYDOCUMENT.LOTCODE LIKE '%LAB2300233%'