DROP VIEW ITXVIEWLEBARGRAMASI_GREIGE;
--CREATE VIEW ITXVIEWLEBARGRAMASI_GREIGE AS
SELECT 
	p.SUBCODE01,
	p.SUBCODE02,
	p.SUBCODE03,
	p.SUBCODE04,
    a.VALUEDECIMAL AS LEBAR,
    a2.VALUEDECIMAL AS GRAMASI
FROM 
    PRODUCT p 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p.ABSUNIQUEID AND a.FIELDNAME = 'Width'
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = p.ABSUNIQUEID AND a2.FIELDNAME = 'GSM'
WHERE 
--    SUBCODE01 = '$d_ITXVIEWKK[SUBCODE01]' 
--    AND SUBCODE02 = '$d_ITXVIEWKK[SUBCODE02]' 
--    AND SUBCODE03 = '$d_ITXVIEWKK[SUBCODE03]'
--    AND SUBCODE04 = '$d_ITXVIEWKK[SUBCODE04]' 
--    AND 
    ITEMTYPECODE = 'KGF'