DROP VIEW ITXVIEWPOGREIGENEW;
--CREATE VIEW ITXVIEWPOGREIGENEW AS   
SELECT
    SALESORDERLINE.SALESORDERCODE,
    SALESORDERLINE.ORDERLINE,
    SALESORDERLINE.ITEMTYPEAFICODE,
    SALESORDERLINE.SUBCODE01,
    SALESORDERLINE.SUBCODE02,
    SALESORDERLINE.SUBCODE03,
    SALESORDERLINE.SUBCODE04,
    SALESORDERLINE.SUBCODE05,
    SALESORDERLINE.SUBCODE06,
    SALESORDERLINE.SUBCODE07,
    SALESORDERLINE.SUBCODE08,
    SALESORDERLINE.CREATIONDATETIME,
--    ALLOCATION.CODE AS ALLOCATION_CODE,
    A.LOTCODE,
    B.CODE AS DEMAND_KGF
FROM
    SALESORDERLINE SALESORDERLINE
LEFT JOIN PRODUCTIONDEMAND PRODUCTIONDEMAND
ON
    SALESORDERLINE.SALESORDERCODE = PRODUCTIONDEMAND.DLVSALORDERLINESALESORDERCODE
    AND 
SALESORDERLINE.ORDERLINE = PRODUCTIONDEMAND.DLVSALESORDERLINEORDERLINE
LEFT JOIN ALLOCATION ALLOCATION 
ON
    SALESORDERLINE.SALESORDERCODE = ALLOCATION.PROJECTCODE
    AND PRODUCTIONDEMAND.CODE = ALLOCATION.ORDERCODE
LEFT JOIN (
    SELECT
        ALLOCATION.CODE,
        ALLOCATION.LOTCODE
    FROM
        ALLOCATION ALLOCATION
    WHERE
        ALLOCATION.STOCKTYPECODE = 'AFW'
) A ON
    ALLOCATION.CODE = A.CODE
LEFT JOIN (
    SELECT
        PRODUCTIONDEMAND.CODE,
        PRODUCTIONDEMAND.ITEMTYPEAFICODE,
        PRODUCTIONDEMAND.SUBCODE01,
        PRODUCTIONDEMAND.SUBCODE02,
        PRODUCTIONDEMAND.SUBCODE03,
        PRODUCTIONDEMAND.SUBCODE04,
        PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE,
        PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE
    FROM
        PRODUCTIONDEMAND PRODUCTIONDEMAND
    WHERE
        PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'KGF'
) B ON
    B.SUBCODE01 = SALESORDERLINE.SUBCODE01
    AND 
B.SUBCODE02 = SALESORDERLINE.SUBCODE02
    AND 
B.SUBCODE03 = SALESORDERLINE.SUBCODE03
    AND 
B.SUBCODE04 = SALESORDERLINE.SUBCODE04
    AND 
B.ORIGDLVSALORDLINESALORDERCODE = SALESORDERLINE.SALESORDERCODE
    AND  
B.ORIGDLVSALORDERLINEORDERLINE = SALESORDERLINE.ORDERLINE
WHERE
    ALLOCATION.CODE IS NOT NULL
GROUP BY
    SALESORDERLINE.SALESORDERCODE,
    SALESORDERLINE.ORDERLINE,
    SALESORDERLINE.ITEMTYPEAFICODE,
    SALESORDERLINE.SUBCODE01,
    SALESORDERLINE.SUBCODE02,
    SALESORDERLINE.SUBCODE03,
    SALESORDERLINE.SUBCODE04,
    SALESORDERLINE.SUBCODE05,
    SALESORDERLINE.SUBCODE06,
    SALESORDERLINE.SUBCODE07,
    SALESORDERLINE.SUBCODE08,
    SALESORDERLINE.CREATIONDATETIME,
--    ALLOCATION.CODE,
    A.LOTCODE,
    B.CODE;