DROP VIEW ITXVIEWKGBRUTOBONORDER2;
--CREATE VIEW ITXVIEWKGBRUTOBONORDER2 AS 
SELECT
    ORIGDLVSALORDLINESALORDERCODE,
    ORIGDLVSALORDERLINEORDERLINE,
    CODE,
    ITEMTYPE_DEMAND,
    SUBCODE01,
    SUBCODE02,
    SUBCODE03,
    SUBCODE04,
    ITEMTYPE_RESERV,
    USERPRIMARYUOMCODE,
    USERPRIMARYQUANTITY,
    KGperPCS,
    CASE
        WHEN KGperPCS IS NULL
        OR ITEMTYPE_DEMAND = 'KFF' THEN 0
        WHEN KGperPCS IS NOT NULL THEN round(qty_pcs_fkf * KGperPCS, 2)
    END AS USERSECONDARYQUANTITY,
    VALUESTRING,
    LINESTATUS
FROM
    (
        SELECT
            --	DISTINCT 
            PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE,
            PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE,
            PRODUCTIONDEMAND.CODE,
            PRODUCTIONDEMAND.ITEMTYPEAFICODE AS ITEMTYPE_DEMAND,
            PRODUCTIONDEMAND.SUBCODE01,
            PRODUCTIONDEMAND.SUBCODE02,
            PRODUCTIONDEMAND.SUBCODE03,
            PRODUCTIONDEMAND.SUBCODE04,
            PRODUCTIONRESERVATION.ITEMTYPEAFICODE AS ITEMTYPE_RESERV,
            PRODUCTIONRESERVATION.USERPRIMARYUOMCODE,
            CASE
                WHEN PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'KFF' THEN PRODUCTIONRESERVATION.USERPRIMARYQUANTITY
                ELSE 0
            END AS USERPRIMARYQUANTITY ,
            CASE
                WHEN PRODUCTIONDEMAND.ITEMTYPEAFICODE <> 'KFF' THEN s.USERSECONDARYQUANTITY
                ELSE 0
            END AS USERSECONDARYQUANTITY,
            a.VALUESTRING,
            s.LINESTATUS,
            CASE
                WHEN (PRODUCT.ITEMTYPECODE = 'FKG') THEN a3.VALUEDECIMAL
                ELSE 0
            END AS KGperPCS,
            CASE
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKY' AND s.USERSECONDARYQUANTITY >= 5 AND s.USERSECONDARYQUANTITY <= 20 THEN s.USERSECONDARYQUANTITY + 6
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKY' AND s.USERSECONDARYQUANTITY >= 26 AND s.USERSECONDARYQUANTITY <= 200 THEN s.USERSECONDARYQUANTITY + 7
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKY' AND s.USERSECONDARYQUANTITY >= 201 AND s.USERSECONDARYQUANTITY <= 400 THEN s.USERSECONDARYQUANTITY + 8
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKY' AND s.USERSECONDARYQUANTITY >= 401 AND s.USERSECONDARYQUANTITY <= 500 THEN s.USERSECONDARYQUANTITY + 10
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKY' AND s.USERSECONDARYQUANTITY >= 501 AND s.USERSECONDARYQUANTITY <= 600 THEN s.USERSECONDARYQUANTITY + 11
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKY' AND s.USERSECONDARYQUANTITY >= 601 AND s.USERSECONDARYQUANTITY <= 700 THEN s.USERSECONDARYQUANTITY + 13
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKY' AND s.USERSECONDARYQUANTITY >= 701 AND s.USERSECONDARYQUANTITY <= 800 THEN s.USERSECONDARYQUANTITY + 15
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKY' AND s.USERSECONDARYQUANTITY >= 801 AND s.USERSECONDARYQUANTITY <= 900 THEN s.USERSECONDARYQUANTITY + 17
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKY' AND s.USERSECONDARYQUANTITY >= 901 AND s.USERSECONDARYQUANTITY <= 1000 THEN s.USERSECONDARYQUANTITY + 19
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKY' AND s.USERSECONDARYQUANTITY >= 1001 AND s.USERSECONDARYQUANTITY <= 1100 THEN s.USERSECONDARYQUANTITY + 21
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKY' AND s.USERSECONDARYQUANTITY >= 1101 AND s.USERSECONDARYQUANTITY <= 1200 THEN s.USERSECONDARYQUANTITY + 23
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKY' AND s.USERSECONDARYQUANTITY >= 1201 AND s.USERSECONDARYQUANTITY <= 1300 THEN s.USERSECONDARYQUANTITY + 25
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKY' AND s.USERSECONDARYQUANTITY >= 1301 AND s.USERSECONDARYQUANTITY <= 1400 THEN s.USERSECONDARYQUANTITY + 27
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKY' AND s.USERSECONDARYQUANTITY >= 1401 AND s.USERSECONDARYQUANTITY <= 1500 THEN s.USERSECONDARYQUANTITY + 29
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKY' AND s.USERSECONDARYQUANTITY >= 1501 AND s.USERSECONDARYQUANTITY <= 2000 THEN s.USERSECONDARYQUANTITY + 30
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKY' AND s.USERSECONDARYQUANTITY >= 2001 THEN s.USERSECONDARYQUANTITY + (s.USERSECONDARYQUANTITY * 0.015)
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKP' AND s.USERSECONDARYQUANTITY >= 1 AND s.USERSECONDARYQUANTITY <= 50 THEN s.USERSECONDARYQUANTITY + 8
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKP' AND s.USERSECONDARYQUANTITY >= 51 AND s.USERSECONDARYQUANTITY <= 200 THEN s.USERSECONDARYQUANTITY + 10
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKP' AND s.USERSECONDARYQUANTITY >= 201 AND s.USERSECONDARYQUANTITY <= 400 THEN s.USERSECONDARYQUANTITY + 13
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKP' AND s.USERSECONDARYQUANTITY >= 401 AND s.USERSECONDARYQUANTITY <= 500 THEN s.USERSECONDARYQUANTITY + 15
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKP' AND s.USERSECONDARYQUANTITY >= 501 AND s.USERSECONDARYQUANTITY <= 600 THEN s.USERSECONDARYQUANTITY + 18
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKP' AND s.USERSECONDARYQUANTITY >= 601 AND s.USERSECONDARYQUANTITY <= 700 THEN s.USERSECONDARYQUANTITY + 20
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKP' AND s.USERSECONDARYQUANTITY >= 701 AND s.USERSECONDARYQUANTITY <= 800 THEN s.USERSECONDARYQUANTITY + 22
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKP' AND s.USERSECONDARYQUANTITY >= 801 AND s.USERSECONDARYQUANTITY <= 900 THEN s.USERSECONDARYQUANTITY + 25
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKP' AND s.USERSECONDARYQUANTITY >= 901 AND s.USERSECONDARYQUANTITY <= 1000 THEN s.USERSECONDARYQUANTITY + 28
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKP' AND s.USERSECONDARYQUANTITY >= 1001 AND s.USERSECONDARYQUANTITY <= 1100 THEN s.USERSECONDARYQUANTITY + 30
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKP' AND s.USERSECONDARYQUANTITY >= 1101 AND s.USERSECONDARYQUANTITY <= 1500 THEN s.USERSECONDARYQUANTITY + 33
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKP' AND s.USERSECONDARYQUANTITY >= 1501 AND s.USERSECONDARYQUANTITY <= 2000 THEN s.USERSECONDARYQUANTITY + 35
                WHEN (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG') AND PRODUCTIONDEMAND.SUBCODE02 = 'FKP' AND s.USERSECONDARYQUANTITY >= 2001 THEN s.USERSECONDARYQUANTITY + (s.USERSECONDARYQUANTITY * 0.02)
            END AS qty_pcs_fkf
        FROM
            PRODUCTIONDEMAND PRODUCTIONDEMAND
        LEFT OUTER JOIN PRODUCTIONRESERVATION PRODUCTIONRESERVATION ON PRODUCTIONDEMAND.CODE = PRODUCTIONRESERVATION.ORDERCODE
        LEFT OUTER JOIN ADSTORAGE a ON a.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a.FIELDNAME = 'OriginalPDCode'
        LEFT JOIN SALESORDERLINE s ON s.SALESORDERCODE = PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE AND s.ORDERLINE = PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE
        LEFT JOIN PRODUCT PRODUCT ON PRODUCTIONRESERVATION.SUBCODE01 = PRODUCT.SUBCODE01
					            AND PRODUCTIONRESERVATION.SUBCODE02 = PRODUCT.SUBCODE02
					            AND PRODUCTIONRESERVATION.SUBCODE03 = PRODUCT.SUBCODE03
					            AND PRODUCTIONRESERVATION.SUBCODE04 = PRODUCT.SUBCODE04
					            AND PRODUCTIONRESERVATION.ITEMTYPEAFICODE = PRODUCT.ITEMTYPECODE
        LEFT OUTER JOIN ADSTORAGE a3 ON PRODUCT.ABSUNIQUEID = a3.UNIQUEID AND a3.FIELDNAME = 'KGperPCS'
        WHERE
            (PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'KFF' OR PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'FKG')
            AND (PRODUCTIONRESERVATION.ITEMTYPEAFICODE = 'KGF' OR PRODUCTIONRESERVATION.ITEMTYPEAFICODE = 'FKG')
            AND a.VALUESTRING IS NULL AND s.LINESTATUS = 1
    );