DROP VIEW ITXVIEWPROJECTBONORDER2;
--CREATE VIEW ITXVIEWPROJECTBONORDER2 AS 
SELECT
	i.CODE,
    i.ORIGDLVSALORDLINESALORDERCODE,
    i.PRO1,
    i.SUBCODE01,
    i.SUBCODE02,
    i.SUBCODE03,
    i.SUBCODE04,
    i1.SUMMARIZEDDESCRIPTION,
    i1.COMMENTTEXT
FROM
    ITXVIEWPROJECTBONORDER i
LEFT JOIN ITXVIEWJENISBENANGRMP i1 ON
    i1.ORIGDLVSALORDLINESALORDERCODE = i.PRO1
WHERE
    i.PRO1 IS NOT NULL
    AND i.ORIGDLVSALORDLINESALORDERCODE = 'OPN2200309' 
--    AND i.SUBCODE01 = 'CVCX' 
--    AND i.SUBCODE02 = 'DKI' 
--    AND i.SUBCODE03 = '22047' 
--    AND i.SUBCODE04 = 'D01'
GROUP BY
	i.CODE,
    i.ORIGDLVSALORDLINESALORDERCODE,
    i.PRO1,
    i.SUBCODE01,
    i.SUBCODE02,
    i.SUBCODE03,
    i.SUBCODE04,
    i1.SUMMARIZEDDESCRIPTION,
    i1.COMMENTTEXT;