DROP VIEW ITXVIEW_QTYPACKING_WITH_DATE;
--CREATE VIEW ITXVIEW_QTYPACKING_WITH_DATE AS
SELECT
	SUBSTR(TIMESTAMP(e.INSPECTIONSTARTDATETIME), 1,10) AS TGL_PACKING,
	e.DEMANDCODE,
    CASE
        WHEN sum(b.BASEPRIMARYQUANTITYUNIT) IS NULL THEN 0
        ELSE sum(b.BASEPRIMARYQUANTITYUNIT)
    END +
    CASE
        WHEN sum(b2.BASEPRIMARYQUANTITYUNIT) IS NULL THEN 0
        ELSE sum(b2.BASEPRIMARYQUANTITYUNIT)
    END +
    CASE
        WHEN SUM(b3.BASEPRIMARYQUANTITYUNIT) IS NULL THEN 0
        ELSE SUM(b3.BASEPRIMARYQUANTITYUNIT)
    END +
    CASE
        WHEN SUM(s.BASEPRIMARYQUANTITY) IS NULL THEN 0
        ELSE SUM(s.BASEPRIMARYQUANTITY)
    END +
    CASE
        WHEN sum(s2.BASEPRIMARYQUANTITY) IS NULL THEN 0
        ELSE sum(s2.BASEPRIMARYQUANTITY)
    END AS QTY_PACKING,
    CASE
        WHEN sum(b.BASESECONDARYQUANTITYUNIT) IS NULL THEN 0
        ELSE sum(b.BASESECONDARYQUANTITYUNIT)
    END +
    CASE
        WHEN sum(b2.BASESECONDARYQUANTITYUNIT) IS NULL THEN 0
        ELSE sum(b2.BASESECONDARYQUANTITYUNIT)
    END +
    CASE
        WHEN SUM(b3.BASESECONDARYQUANTITYUNIT) IS NULL THEN 0
        ELSE SUM(b3.BASESECONDARYQUANTITYUNIT)
    END +
    CASE
        WHEN SUM(s.BASESECONDARYQUANTITY) IS NULL THEN 0
        ELSE SUM(s.BASESECONDARYQUANTITY)
    END +
    CASE
        WHEN sum(s2.BASESECONDARYQUANTITY) IS NULL THEN 0
        ELSE sum(s2.BASESECONDARYQUANTITY)
    END AS QTY_PACKING_YARD
FROM ELEMENTSINSPECTION e 
LEFT JOIN BALANCE b ON b.ELEMENTSCODE = e.ELEMENTCODE AND b.LOGICALWAREHOUSECODE = 'M039'
LEFT JOIN BALANCE b2 ON b2.ELEMENTSCODE = e.ELEMENTCODE AND b2.LOGICALWAREHOUSECODE = 'M031'
LEFT JOIN BALANCE b3 ON b3.ELEMENTSCODE = e.ELEMENTCODE AND b3.LOGICALWAREHOUSECODE = 'M504'
LEFT JOIN STOCKTRANSACTION s ON s.ITEMELEMENTCODE = e.ELEMENTCODE AND s.LOGICALWAREHOUSECODE='M031' AND s.TEMPLATECODE ='S02'
LEFT JOIN STOCKTRANSACTION s2 ON s2.TEMPLATECODE = '098' AND s2.ITEMELEMENTCODE = e.ELEMENTCODE 
WHERE LENGTH(TRIM(e.ELEMENTCODE))= 13 
--AND e.DEMANDCODE = '00282049'
GROUP BY SUBSTR(e.INSPECTIONSTARTDATETIME, 1,10), e.DEMANDCODE