DROP VIEW ITXVIEWSPECS_KKPRINTING;
CREATE VIEW ITXVIEWSPECS_KKPRINTING AS
SELECT 
	p.CODE,
	a.VALUEDECIMAL AS LEBAR_SCREEN,
	a2.VALUESTRING AS REPEAT_SCREEN,
	a3.VALUESTRING AS REPEAT_BUYER
FROM 
	PRODUCTIONDEMAND p
LEFT JOIN PRODUCTIONSPECS p2 ON p2.ITEMTYPEAFICODE = p.ITEMTYPEAFICODE 
--							AND p2.SUBCODE01 = p.SUBCODE01 
--							AND p2.SUBCODE02 = p.SUBCODE02 
--							AND p2.SUBCODE03 = p.SUBCODE03 
--							AND p2.SUBCODE04 = p.SUBCODE04 
--							AND p2.SUBCODE05 = p.SUBCODE05 
--							AND p2.SUBCODE06 = p.SUBCODE06 
							AND p2.SUBCODE07 = p.SUBCODE07
							AND p2.SUBCODE08 = p.SUBCODE08
							AND (p2.OPERATIONCODE = 'ROT1' OR p2.OPERATIONCODE = 'FLT1')
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p2.ABSUNIQUEID AND a.FIELDNAME = 'LebarScreen' 
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = p2.ABSUNIQUEID AND a2.FIELDNAME = 'RepeatScreen'
LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = p2.ABSUNIQUEID AND a3.FIELDNAME = 'RepeatBuyer'