DROP VIEW ITXVIEW_SHIPPING_MARK;
--CREATE VIEW ITXVIEW_SHIPPING_MARK AS 
SELECT
    CODE,
    DELIVERYPOINTCODE,
    LEGALNAME1,
    SP#,
    ST#,
    CASE
        WHEN LEGALNAME1 = 'INQUBE' THEN 'INQUBE'
        WHEN LEGALNAME1 = 'MAS' THEN 'MAS'
        ELSE KODE_SM
    END AS KODE_SM,
    PIC,
    ext
FROM
    (
        SELECT
            DISTINCT 
            s.CODE,
            TRIM(s.DELIVERYPOINTCODE) AS DELIVERYPOINTCODE,
            CASE
                WHEN BUSINESSPARTNER.LEGALNAME1 LIKE '%MAS%' THEN LEFT(BUSINESSPARTNER.LEGALNAME1, 3)
                WHEN BUSINESSPARTNER.LEGALNAME1 LIKE '%CLASSIC%' THEN LEFT(BUSINESSPARTNER.LEGALNAME1, 7)
                WHEN BUSINESSPARTNER.LEGALNAME1 LIKE '%INQUBE%' THEN LEFT(BUSINESSPARTNER.LEGALNAME1, 6)
                ELSE BUSINESSPARTNER.LEGALNAME1
            END AS LEGALNAME1,
            LISTAGG(
                DISTINCT(
                    TRIM(s2.EXTERNALREFERENCE)
                ),
                ', '
            ) AS SP#,
            LISTAGG(
                DISTINCT(
                    TRIM(s2.INTERNALREFERENCE)
                ),
                ', '
            ) AS ST#,
            a.UNIQUEID,
            a.VALUESTRING AS KODE_SM,
            a2.VALUESTRING AS PIC,
            a3.VALUESTRING AS ext
        FROM
            SALESORDER s
        LEFT OUTER JOIN ORDERPARTNER ORDERPARTNER ON
            s.COMPANYCODE = ORDERPARTNER.CUSTOMERSUPPLIERCOMPANYCODE
            AND s.ORDERTYPE = ORDERPARTNER.CUSTOMERSUPPLIERTYPE
            AND s.ORDPRNCUSTOMERSUPPLIERCODE = ORDERPARTNER.CUSTOMERSUPPLIERCODE
        LEFT OUTER JOIN BUSINESSPARTNER BUSINESSPARTNER ON
            ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID = BUSINESSPARTNER.NUMBERID
        LEFT JOIN ADSTORAGE a ON
            s.ABSUNIQUEID = a.UNIQUEID
            AND a.FIELDNAME = 'KodeSM'
        LEFT JOIN ADSTORAGE a2 ON
            s.ABSUNIQUEID = a2.UNIQUEID
            AND a2.FIELDNAME = 'PICEXT'
        LEFT JOIN ADSTORAGE a3 ON
            s.ABSUNIQUEID = a3.UNIQUEID
            AND a3.FIELDNAME = 'EXT'
        LEFT JOIN SALESORDERLINE s2 ON
            s.CODE = s2.SALESORDERCODE
        GROUP BY
            s.CODE,
            s.DELIVERYPOINTCODE,
            a.UNIQUEID,
            a.VALUESTRING,
            a2.VALUESTRING,
            a3.VALUESTRING,
            BUSINESSPARTNER.LEGALNAME1
    );