DROP VIEW ITXVIEW_QTYPACKING;
--CREATE VIEW ITXVIEW_QTYPACKING AS
SELECT 	
	e.DEMANDCODE,
    CASE
        WHEN sum(b.BASEPRIMARYQUANTITYUNIT) IS NULL THEN 0
        ELSE sum(b.BASEPRIMARYQUANTITYUNIT)
    END +
    CASE
        WHEN sum(b2.BASEPRIMARYQUANTITYUNIT) IS NULL THEN 0
        ELSE sum(b2.BASEPRIMARYQUANTITYUNIT)
    END +
    CASE
        WHEN SUM(b3.BASEPRIMARYQUANTITYUNIT) IS NULL THEN 0
        ELSE SUM(b3.BASEPRIMARYQUANTITYUNIT)
    END +
    CASE
        WHEN SUM(s.BASEPRIMARYQUANTITY) IS NULL THEN 0
        ELSE SUM(s.BASEPRIMARYQUANTITY)
    END +
    CASE
        WHEN sum(s2.BASEPRIMARYQUANTITY) IS NULL THEN 0
        ELSE sum(s2.BASEPRIMARYQUANTITY)
    END AS QTY_PACKING
FROM ELEMENTSINSPECTION e 
LEFT JOIN BALANCE b ON b.ELEMENTSCODE = e.ELEMENTCODE AND b.LOGICALWAREHOUSECODE = 'M039'
LEFT JOIN BALANCE b2 ON b2.ELEMENTSCODE = e.ELEMENTCODE AND b2.LOGICALWAREHOUSECODE = 'M031'
LEFT JOIN BALANCE b3 ON b3.ELEMENTSCODE = e.ELEMENTCODE AND b3.LOGICALWAREHOUSECODE = 'M504'
LEFT JOIN STOCKTRANSACTION s ON s.ITEMELEMENTCODE = e.ELEMENTCODE AND s.LOGICALWAREHOUSECODE='M031' AND s.TEMPLATECODE ='S02'
LEFT JOIN STOCKTRANSACTION s2 ON s2.TEMPLATECODE = '098' AND s2.ITEMELEMENTCODE = e.ELEMENTCODE 
WHERE LENGTH(TRIM(e.ELEMENTCODE))= 13 
AND e.DEMANDCODE = '00122230'
GROUP BY e.DEMANDCODE