DROP VIEW ITXVIEW_ALLOCATION_INVOICE_NEW;
--CREATE VIEW ITXVIEW_ALLOCATION_INVOICE_NEW AS
SELECT
    TIPE,
    COMPANYCODE,
    DIVISIONCODE,
    INVOICE,
    SALESDOCUMENTPROVISIONALCODE,
    DLVSALORDERLINESALESORDERCODE,
    CODE,
    LOTCODE,
    SUM(USERPRIMARYQUANTITY) AS USERPRIMARYQUANTITY,
    SUM(USERSECONDARYQUANTITY) AS USERSECONDARYQUANTITY,
    SUM(BASESECONDARYQUANTITY) AS BASESECONDARYQUANTITY,
    SUM(qty_pcs) AS qty_pcs,
    PRICE,
    ORDERCODE,
    ORDERLINE,
    DLVSALESORDERLINEORDERLINE,
    PRICEUNITOFMEASURECODE,
    PREVIOUSCODE,
    SALDOCPROVISIONALCOUNTERCODE,
    ITEMTYPECODE,
    CURR,
    ALLOCATIONDATE,
    DECOSUBCODE01,
    DECOSUBCODE02,
    DECOSUBCODE03,
    DECOSUBCODE04,
    DECOSUBCODE05,
    DECOSUBCODE06,
    DECOSUBCODE07,
    DECOSUBCODE08,
    CUSTOMERCODE,
    JENIS_KAIN,
    NO_ITEM,
    EXTERNALREFERENCE,
    NO_SAP_CODE,
    CUSTOMER_CODE
FROM
    (
        SELECT
            DISTINCT SUBSTR(s.DLVSALORDERLINESALESORDERCODE, 1, 3) AS TIPE,
            p.COMPANYCODE,
            p.DIVISIONCODE,
            P.CODE AS INVOICE,
            s.SALESDOCUMENTPROVISIONALCODE,
            s.DLVSALORDERLINESALESORDERCODE,
            s.DLVSALESORDERLINEORDERLINE,
            ALLOCATION.CODE AS CODE,
            iasp.itemelementcode,
            iasp.LOTCODE,
            p.ORDERCURRENCYCODE AS CURR,
            CASE
                WHEN e.QUALITYREASONCODE = 'FOC'
                AND s.SALDOCPROVISIONALCOUNTERCODE IN(
                    'DREDEF', 'DREPROV', 'DRDDEF', 'DRPPROV'
                ) THEN iasp.USERSECONDARYUSEDQUANTITY
                WHEN e.QUALITYREASONCODE = 'FOC'
                AND s.SALDOCPROVISIONALCOUNTERCODE IN(
                    'EXDPROV', 'EXPPROV', 'PFEPROV'
                ) THEN 0
                WHEN ALLOCATION.CODE IN (
                    '000000396037', '000000396038', '000000396042', '000000396043', '000000396047', '000000396048'
                ) THEN 0
                ELSE iasp.USERSECONDARYUSEDQUANTITY
            END USERSECONDARYQUANTITY,
            CASE
                WHEN e.QUALITYREASONCODE = 'FOC'
                AND s.SALDOCPROVISIONALCOUNTERCODE IN(
                    'DREDEF', 'DREPROV', 'DRDDEF', 'DRPPROV'
                ) THEN iasp.USERPRIMARYQUANTITY
                WHEN e.QUALITYREASONCODE = 'FOC'
                AND s.SALDOCPROVISIONALCOUNTERCODE IN(
                    'EXDPROV', 'EXPPROV', 'PFEPROV'
                ) THEN 0
                WHEN ALLOCATION.CODE IN (
                    '000000396037', '000000396038', '000000396042', '000000396043', '000000396047', '000000396048'
                ) THEN 0
                ELSE iasp.USERPRIMARYQUANTITY
            END USERPRIMARYQUANTITY,
            CASE
                WHEN e.QUALITYREASONCODE = 'FOC'
                AND s.SALDOCPROVISIONALCOUNTERCODE IN(
                    'DREDEF', 'DREPROV', 'DRDDEF', 'DRPPROV'
                ) THEN iasp.BASESECONDARYQUANTITY
                WHEN e.QUALITYREASONCODE = 'FOC'
                AND s.SALDOCPROVISIONALCOUNTERCODE IN(
                    'EXDPROV', 'EXPPROV', 'PFEPROV'
                ) THEN 0
                WHEN ALLOCATION.ITEMTYPECODE <> 'CAP'
                AND iasp.BASESECONDARYUOMCODE IN(
                    'Lot', 'un', 'Set'
                ) THEN iasp.BASESECONDARYQUANTITY
                WHEN iasp.ITEMTYPECODE = 'CAP'
                AND iasp.BASEPRIMARYUOMCODE IN(
                    'Lot', 'un', 'Set'
                ) THEN iasp.BASEPRIMARYQUANTITY
                WHEN ALLOCATION.CODE IN (
                    '000000396037', '000000396038', '000000396042', '000000396043', '000000396047', '000000396048'
                ) THEN 0
                ELSE 0
            END qty_pcs,
            CASE
                WHEN e.QUALITYREASONCODE = 'FOC'
                AND s.SALDOCPROVISIONALCOUNTERCODE IN(
                    'DREDEF', 'DREPROV', 'DRDDEF', 'DRPPROV'
                ) THEN round(iasp.BASESECONDARYQUANTITY * 0.9144, 2)
                WHEN e.QUALITYREASONCODE = 'FOC'
                AND s.SALDOCPROVISIONALCOUNTERCODE IN(
                    'EXDPROV', 'EXPPROV', 'PFEPROV'
                ) THEN 0
                WHEN ALLOCATION.CODE IN (
                    '000000396037', '000000396038', '000000396042', '000000396043', '000000396047', '000000396048'
                ) THEN 0
                ELSE round(iasp.BASESECONDARYQUANTITY * 0.9144, 2)
            END BASESECONDARYQUANTITY,
            CASE
                WHEN e.QUALITYREASONCODE = 'FOC' THEN iasp.USERPRIMARYQUANTITY
                ELSE 0
            END AS FOC_KG,
            CASE
                WHEN e.QUALITYREASONCODE = 'FOC' THEN iasp.USERSECONDARYQUANTITY
                ELSE 0
            END AS FOC_YARD,
            CASE
                WHEN ALLOCATION.CODE IN (
                    '000000396037', '000000396038', '000000396042', '000000396043', '000000396047', '000000396048'
                ) THEN 0
                ELSE s.PRICE
            END AS PRICE,
            s.PRICEUNITOFMEASURECODE,
            e.QUALITYREASONCODE,
            s.PREVIOUSCODE,
            s.SALDOCPROVISIONALCOUNTERCODE,
            ALLOCATION.ORDERCODE AS ORDERCODE,
            ALLOCATION.ORDERLINE AS ORDERLINE,
            ALLOCATION.ITEMTYPECODE,
            ALLOCATION.ALLOCATIONDATE AS ALLOCATIONDATE,
            ALLOCATION.DECOSUBCODE01 AS DECOSUBCODE01,
            ALLOCATION.DECOSUBCODE02 AS DECOSUBCODE02,
            ALLOCATION.DECOSUBCODE03 AS DECOSUBCODE03,
            ALLOCATION.DECOSUBCODE04 AS DECOSUBCODE04,
            ALLOCATION.DECOSUBCODE05 AS DECOSUBCODE05,
            ALLOCATION.DECOSUBCODE06 AS DECOSUBCODE06,
            ALLOCATION.DECOSUBCODE07 AS DECOSUBCODE07,
            ALLOCATION.DECOSUBCODE08 AS DECOSUBCODE08,
            ALLOCATION.CUSTOMERCODE AS CUSTOMERCODE,
            CASE
                WHEN ALLOCATION.ITEMTYPECODE = 'GYR' THEN s.ITEMDESCRIPTION
                ELSE PRODUCT.LONGDESCRIPTION
            END AS JENIS_KAIN,
            s2.EXTERNALITEM AS NO_ITEM,
            a.EXTERNALREFERENCE AS EXTERNALREFERENCE,
            a.EXTERNALDRAWINGNUMBER AS NO_SAP_CODE,
            p.CONSIGNEECUSTOMERSUPPLIERCODE AS CUSTOMER_CODE
        FROM
            PLANTINVOICE p
        LEFT JOIN SALESDOCUMENTLINE s3 ON
            p.CODE = s3.SALESDOCUMENTPROVISIONALCODE
            AND p.COMPANYCODE = s3.SALESDOCUMENTCOMPANYCODE
        LEFT JOIN SALESDOCUMENTLINE s ON
            s.ITEMTYPEAFICODE = s3.ITEMTYPEAFICODE
            AND s.SALESDOCUMENTPROVISIONALCODE = s3.PREVIOUSCODE
            AND s.ORDERLINE = s3.PREVIOUSORDERLINE
            AND s.SUBCODE01 = s3.SUBCODE01
            AND s.SUBCODE02 = s3.SUBCODE02
            AND s.SUBCODE03 = s3.SUBCODE03
            AND s.SUBCODE04 = s3.SUBCODE04
            AND s.SUBCODE05 = s3.SUBCODE05
            AND s.SUBCODE06 = s3.SUBCODE06
            AND s.SUBCODE07 = s3.SUBCODE07
            AND s.SUBCODE08 = s3.SUBCODE08
            AND s.SUBCODE09 = s3.SUBCODE09
            AND s.SUBCODE10 = s3.SUBCODE10
            AND s.SALESDOCUMENTCOMPANYCODE = s3.SALESDOCUMENTCOMPANYCODE
        LEFT JOIN ALLOCATION ALLOCATION ON
            ALLOCATION.ITEMTYPECODE = s.ITEMTYPEAFICODE
            AND ALLOCATION.ORDERCODE = s.SALESDOCUMENTPROVISIONALCODE
            AND ALLOCATION.ORDERLINE = s.ORDERLINE
            AND ALLOCATION.DECOSUBCODE01 = s.SUBCODE01
            AND ALLOCATION.DECOSUBCODE02 = s.SUBCODE02
            AND ALLOCATION.DECOSUBCODE03 = s.SUBCODE03
            AND ALLOCATION.DECOSUBCODE04 = s.SUBCODE04
            AND ALLOCATION.DECOSUBCODE05 = s.SUBCODE05
            AND ALLOCATION.DECOSUBCODE06 = s.SUBCODE06
            AND ALLOCATION.DECOSUBCODE07 = s.SUBCODE07
            AND ALLOCATION.DECOSUBCODE08 = s.SUBCODE08
            AND ALLOCATION.DECOSUBCODE09 = s.SUBCODE09
            AND ALLOCATION.DECOSUBCODE10 = s.SUBCODE10
            AND ALLOCATION.COMPANYCODE = s.SALESDOCUMENTCOMPANYCODE
        LEFT JOIN PRODUCT PRODUCT ON
            ALLOCATION.ITEMTYPECODE = PRODUCT.ITEMTYPECODE
            AND ALLOCATION.DECOSUBCODE01 = PRODUCT.SUBCODE01
            AND ALLOCATION.DECOSUBCODE02 = PRODUCT.SUBCODE02
            AND ALLOCATION.DECOSUBCODE03 = PRODUCT.SUBCODE03
            AND ALLOCATION.DECOSUBCODE04 = PRODUCT.SUBCODE04
            AND ALLOCATION.DECOSUBCODE05 = PRODUCT.SUBCODE05
            AND ALLOCATION.DECOSUBCODE06 = PRODUCT.SUBCODE06
            AND ALLOCATION.DECOSUBCODE07 = PRODUCT.SUBCODE07
            AND ALLOCATION.DECOSUBCODE08 = PRODUCT.SUBCODE08
            AND ALLOCATION.DECOSUBCODE09 = PRODUCT.SUBCODE09
            AND ALLOCATION.DECOSUBCODE10 = PRODUCT.SUBCODE10
            AND ALLOCATION.COMPANYCODE = p.COMPANYCODE
        LEFT JOIN SALESORDERLINE s2 ON
            s.DLVSALORDERLINESALESORDERCODE = s2.SALESORDERCODE
            AND s.DLVSALESORDERLINEORDERLINE = s2.ORDERLINE
            AND s.ITEMTYPEAFICODE = s2.ITEMTYPEAFICODE
            AND s.SUBCODE01 = s2.SUBCODE01
            AND s.SUBCODE02 = s2.SUBCODE02
            AND s.SUBCODE03 = s2.SUBCODE03
            AND s.SUBCODE04 = s2.SUBCODE04
            AND s.SUBCODE05 = s2.SUBCODE05
            AND s.SUBCODE06 = s2.SUBCODE06
            AND s.SUBCODE07 = s2.SUBCODE07
            AND s.SALESDOCUMENTCOMPANYCODE = s2.SALESORDERCOMPANYCODE
        LEFT JOIN ITXVIEWORDERPARTNERLINKACTIVE a ON
            ALLOCATION.CUSTOMERCODE = a.ORDPRNCUSTOMERSUPPLIERCODE
            AND ALLOCATION.ITEMTYPECODE = a.ITEMTYPEAFICODE
            AND ALLOCATION.DECOSUBCODE01 = a.SUBCODE01
            AND ALLOCATION.DECOSUBCODE02 = a.SUBCODE02
            AND ALLOCATION.DECOSUBCODE03 = a.SUBCODE03
            AND ALLOCATION.DECOSUBCODE04 = a.SUBCODE04
            AND ALLOCATION.DECOSUBCODE05 = a.SUBCODE05
            AND ALLOCATION.DECOSUBCODE06 = a.SUBCODE06
            AND ALLOCATION.DECOSUBCODE07 = a.SUBCODE07
            AND ALLOCATION.COMPANYCODE = a.COMPANYCODE
        LEFT JOIN ITXVIEW_ALLOCATION_SURATJALAN_PPC iasp ON
            iasp.CODE = ALLOCATION.CODE
            AND iasp.DECOSUBCODE01 = ALLOCATION.DECOSUBCODE01
            AND iasp.DECOSUBCODE02 = ALLOCATION.DECOSUBCODE02
            AND iasp.DECOSUBCODE03 = ALLOCATION.DECOSUBCODE03
            AND iasp.DECOSUBCODE04 = ALLOCATION.DECOSUBCODE04
            AND iasp.DECOSUBCODE05 = ALLOCATION.DECOSUBCODE05
            AND iasp.DECOSUBCODE06 = ALLOCATION.DECOSUBCODE06
            AND iasp.DECOSUBCODE07 = ALLOCATION.DECOSUBCODE07
            AND iasp.COMPANYCODE = ALLOCATION.COMPANYCODE
        LEFT JOIN ELEMENTS e ON
            iasp.itemelementcode = e.CODE
        WHERE
            ALLOCATION.DETAILTYPE = '1'
            AND ALLOCATION.ORIGINTRNTRANSACTIONNUMBER IS NULL
            AND ALLOCATION.DESTINATIONTYPE = '7'
    )
WHERE
    USERPRIMARYQUANTITY <> 0
--    AND INVOICE = 'CA24120001'
GROUP BY
    TIPE,
    COMPANYCODE,
    DIVISIONCODE,
    INVOICE,
    SALESDOCUMENTPROVISIONALCODE,
    DLVSALORDERLINESALESORDERCODE,
    CODE,
    LOTCODE,
    ORDERCODE,
    ORDERLINE,
    DLVSALESORDERLINEORDERLINE,
    PRICE,
    PRICEUNITOFMEASURECODE,
    PREVIOUSCODE,
    ALLOCATIONDATE,
    ITEMTYPECODE,
    SALDOCPROVISIONALCOUNTERCODE,
    DECOSUBCODE01,
    DECOSUBCODE02,
    DECOSUBCODE03,
    DECOSUBCODE04,
    DECOSUBCODE05,
    DECOSUBCODE06,
    DECOSUBCODE07,
    DECOSUBCODE08,
    CUSTOMERCODE,
    JENIS_KAIN,
    NO_ITEM,
    CURR,
    EXTERNALREFERENCE,
    NO_SAP_CODE,
    CUSTOMER_CODE;