DROP VIEW ITXVIEW_SUMMARY_QTY_DELIVERY;
--CREATE VIEW ITXVIEW_SUMMARY_QTY_DELIVERY AS 
SELECT DISTINCT 
	s4.SALESDOCUMENTPROVISIONALCODE,
	s5.GOODSISSUEDATE,
	a2.CODE,
	iasp.LOTCODE,
	s.ORDERLINE,
	ip.LANGGANAN AS PELANGGAN,
	s.SALESORDERCODE AS NO_ORDER,
	s.EXTERNALREFERENCE AS NO_PO,
	TRIM(s.SUBCODE02) || '-' || TRIM(s.SUBCODE03) AS KET_PRODUCT,
	s.INTERNALREFERENCE AS STYLE,
	il.LEBAR,
	CASE
		WHEN i.GRAMASI_KFF IS NULL THEN i.GRAMASI_FKF
		ELSE i.GRAMASI_KFF 
	END AS GRAMASI,
	i2.WARNA,
	TRIM(s.SUBCODE05) AS NO_WARNA,
	s.USERPRIMARYQUANTITY AS NETTO,
	TRIM(s.USERPRIMARYUOMCODE) AS SATUAN_NETTO,
	s.USERSECONDARYQUANTITY AS NETTO_2,
	TRIM(s.USERSECONDARYUOMCODE) AS SATUAN_NETTO_2,
	p.SECONDARYUNSTEADYCVSFACTOR AS KONVERSI,
	COALESCE(s3.CONFIRMEDDELIVERYDATE, s2.CONFIRMEDDUEDATE) AS ACTUAL_DELIVERY,
	a2.LINENUMBER,
	(a2.USERPRIMARYQUANTITY) AS QTY_SUDAH_KIRIM,
	(a2.USERSECONDARYQUANTITY) AS QTY_SUDAH_KIRIM_2,
	CASE
		WHEN e.QUALITYREASONCODE IS NULL THEN '1'
		ELSE e.QUALITYREASONCODE
	END AS QUALITYREASONCODE	
FROM
	SALESORDERLINE s
LEFT JOIN SALESORDER s2 ON s2.CODE = s.SALESORDERCODE 
LEFT JOIN ITXVIEW_PELANGGAN ip ON ip.ORDPRNCUSTOMERSUPPLIERCODE = s2.ORDPRNCUSTOMERSUPPLIERCODE AND ip.CODE = s.SALESORDERCODE 
LEFT JOIN ITXVIEW_KGBRUTO ik ON ik.PROJECTCODE = s.SALESORDERCODE AND ik.ORIGDLVSALORDERLINEORDERLINE = s.ORDERLINE 
LEFT JOIN ITXVIEWLEBAR il ON il.SALESORDERCODE = s.SALESORDERCODE AND il.ORDERLINE = s.ORDERLINE 
LEFT JOIN ITXVIEWGRAMASI i ON i.SALESORDERCODE = s.SALESORDERCODE AND i.ORDERLINE = s.ORDERLINE
LEFT JOIN ITXVIEWCOLOR i2 ON i2.ITEMTYPECODE = s.ITEMTYPEAFICODE 
						  AND i2.SUBCODE01 = s.SUBCODE01 AND i2.SUBCODE02 = s.SUBCODE02 
						  AND i2.SUBCODE03 = s.SUBCODE03 AND i2.SUBCODE04 = s.SUBCODE04 
						  AND i2.SUBCODE05 = s.SUBCODE05 AND i2.SUBCODE06 = s.SUBCODE06 
						  AND i2.SUBCODE07 = s.SUBCODE07 AND i2.SUBCODE08 = s.SUBCODE08 
						  AND i2.SUBCODE09 = s.SUBCODE09 AND i2.SUBCODE10 = s.SUBCODE10
LEFT JOIN PRODUCT p ON p.ITEMTYPECODE = s.ITEMTYPEAFICODE 
					AND p.SUBCODE01 = s.SUBCODE01 AND p.SUBCODE02 = s.SUBCODE02 
					AND p.SUBCODE03 = s.SUBCODE03 AND p.SUBCODE04 = s.SUBCODE04 
					AND p.SUBCODE05 = s.SUBCODE05 AND p.SUBCODE06 = s.SUBCODE06 
					AND p.SUBCODE07 = s.SUBCODE07 AND p.SUBCODE08 = s.SUBCODE08 
					AND p.SUBCODE09 = s.SUBCODE09 AND p.SUBCODE10 = s.SUBCODE10
LEFT JOIN SALESORDERDELIVERY s3 ON s3.SALESORDERLINESALESORDERCODE = s.SALESORDERCODE AND s3.SALESORDERLINEORDERLINE = s.ORDERLINE
LEFT JOIN SALESDOCUMENTLINE s4 ON s4.DLVSALORDERLINESALESORDERCODE = s.SALESORDERCODE AND s4.DLVSALESORDERLINEORDERLINE = s.ORDERLINE AND s4.DOCUMENTTYPETYPE = 05 AND NOT s4.PROGRESSSTATUS = 0
LEFT JOIN ALLOCATION a ON a.ORDERCODE = s4.SALESDOCUMENTPROVISIONALCODE AND a.ORDERLINE = s4.ORDERLINE 
LEFT JOIN ITXVIEW_ALLOCATION_SURATJALAN_PPC iasp ON iasp.CODE = a.CODE
LEFT JOIN ALLOCATION a2 ON a2.CODE = a.CODE AND a2.LOTCODE = iasp.LOTCODE AND NOT a2.PICKINGCODE IS NULL
LEFT JOIN SALESDOCUMENT s5 ON s5.PROVISIONALCODE = s4.SALESDOCUMENTPROVISIONALCODE
LEFT JOIN ELEMENTS e ON e.CODE = a2.ITEMELEMENTCODE 
WHERE 
	s.LINESTATUS = '1'
	AND s.SALESORDERCODE = 'EXP2400330' 
--	AND NOT e.QUALITYREASONCODE = 'FOC' 
--	AND e.QUALITYREASONCODE IS NULL
--	AND s.ORDERLINE = 70
--	AND iasp.LOTCODE = '00143138'
GROUP BY
	s4.SALESDOCUMENTPROVISIONALCODE,
	s5.GOODSISSUEDATE,
	a2.CODE,
	iasp.LOTCODE,
	s.ORDERLINE,
	ip.LANGGANAN,
	s.SALESORDERCODE,
	s.EXTERNALREFERENCE,
	s.SUBCODE02,
	s.SUBCODE03,
	s.INTERNALREFERENCE,
	il.LEBAR,
	i.GRAMASI_KFF,
	i.GRAMASI_FKF,
	i2.WARNA,
	s.SUBCODE05,
	s.USERPRIMARYQUANTITY,
	s.USERPRIMARYUOMCODE,
	s.USERSECONDARYQUANTITY,
	s.USERSECONDARYUOMCODE,
	p.SECONDARYUNSTEADYCVSFACTOR,
	s3.CONFIRMEDDELIVERYDATE, 
	s2.CONFIRMEDDUEDATE,
	a2.LINENUMBER,
	a2.USERPRIMARYQUANTITY,
	a2.USERSECONDARYQUANTITY,
	e.QUALITYREASONCODE
	
-- QUERY INI UNTUK HEADERNYA	
SELECT
    ORDERLINE,
    PELANGGAN,
    NO_ORDER,
    NO_PO,
    KET_PRODUCT,
    STYLE,
    LEBAR,
    GRAMASI,
    WARNA,
    NO_WARNA,
    NETTO,
    NETTO_2,
    KONVERSI,
    ACTUAL_DELIVERY,
    SUM(QTY_SUDAH_KIRIM) AS QTY_SUDAH_KIRIM,
    SUM(QTY_SUDAH_KIRIM_2) AS QTY_SUDAH_KIRIM_2,
--    (QTY_READY) AS QTY_READY,
--    (QTY_READY2) AS QTY_READY2,
    CASE
        WHEN DAYS(now()) - DAYS(Timestamp_Format(ACTUAL_DELIVERY, 'YYYY-MM-DD')) < 0 THEN 0
        ELSE DAYS(now()) - DAYS(Timestamp_Format(ACTUAL_DELIVERY, 'YYYY-MM-DD'))
    END	AS DELAY
FROM
    ITXVIEW_SUMMARY_QTY_DELIVERY isqd
WHERE
    isqd.NO_ORDER = 'EXP2400214'
--    NO_PO = '24100044IR-01'
GROUP BY
    ORDERLINE,
    PELANGGAN,
    NO_ORDER,
    NO_PO,
    KET_PRODUCT,
    STYLE,
    LEBAR,
    GRAMASI,
    WARNA,
    NO_WARNA,
    NETTO,
    NETTO_2,
    KONVERSI,
    ACTUAL_DELIVERY
ORDER BY
	ORDERLINE ASC
	
-- QUERY INI UNTUK DETAILNYA
SELECT DISTINCT
    SALESDOCUMENTPROVISIONALCODE,
    GOODSISSUEDATE,
    LOTCODE,
    ORDERLINE,
    PELANGGAN,
    NO_ORDER,
    NO_PO,
    KET_PRODUCT,
    STYLE,
    LEBAR,
    GRAMASI,
    WARNA,
    NO_WARNA,
    NETTO,
    SATUAN_NETTO,
    NETTO_2,
    SATUAN_NETTO_2,
    KONVERSI,
    ACTUAL_DELIVERY,
    SUM(QTY_SUDAH_KIRIM) AS QTY_SUDAH_KIRIM,
    SUM(QTY_SUDAH_KIRIM_2) AS QTY_SUDAH_KIRIM_2
FROM 
    ITXVIEW_SUMMARY_QTY_DELIVERY 
WHERE 
    NO_ORDER = 'EXP2400214' 
AND ORDERLINE = '80' 
GROUP BY
	SALESDOCUMENTPROVISIONALCODE,
    GOODSISSUEDATE,
    LOTCODE,
    ORDERLINE,
    PELANGGAN,
    NO_ORDER,
    NO_PO,
    KET_PRODUCT,
    STYLE,
    LEBAR,
    GRAMASI,
    WARNA,
    NO_WARNA,
    NETTO,
    SATUAN_NETTO,
    NETTO_2,
    SATUAN_NETTO_2,
    KONVERSI,
    ACTUAL_DELIVERY
ORDER BY 
    LOTCODE 
    ASC
    
    
-- QTY READY DAPETIN LOTNYA
SELECT
	 LISTAGG(DISTINCT ''''|| TRIM(LOTCODE) ||'''', ', ')  AS LOTCODE
FROM 
    ITXVIEW_SUMMARY_QTY_DELIVERY 
WHERE 
    NO_ORDER = 'EXP2400214' 
    AND ORDERLINE = '30'
    
-- QTY READY DAPETIN LOTNYA JIKA KK MASIH READY
SELECT
    LISTAGG(DISTINCT ''''|| TRIM(PRODUCTIONORDERCODE) ||'''', ', ')  AS LOTCODE
--    PRODUCTIONORDERCODE,*
FROM 
    ITXVIEWKK i 
WHERE 
    PROJECTCODE = 'EXP2400214' 
    AND ORIGDLVSALORDERLINEORDERLINE = '30'
    AND PROGRESSSTATUS_DEMAND = 6
    AND NOT DELIVERYDATE IS NULL
    
    
-- QTY READY
SELECT
	PROJECTCODE,
	LOTCODE,
	SUBSTR(ELEMENTSCODE, 1,8) AS PRODUCTIONDEMAND,
 	TRIM(DECOSUBCODE02) || '-' || TRIM(DECOSUBCODE03) KET_PRODUCT,
 	COUNT(ELEMENTSCODE) AS ROLL, 
	SUM(BASEPRIMARYQUANTITYUNIT) AS QTY_READY,
	SUM(BASESECONDARYQUANTITYUNIT) AS QTY_READY_2
FROM
	BALANCE b
WHERE
	PROJECTCODE = 'EXP2400214'
	AND TRIM(DECOSUBCODE02) || '-' || TRIM(DECOSUBCODE03) = 'DKF-19106' 
	AND LOGICALWAREHOUSECODE = 'M031'
GROUP BY
	PROJECTCODE,
	LOTCODE,
	SUBSTR(ELEMENTSCODE, 1,8),
	DECOSUBCODE02,
	DECOSUBCODE03