-- DB2ADMIN.ITXVIEWBONORDER source
DROP VIEW ITXVIEWBONORDER;
--CREATE VIEW ITXVIEWBONORDER AS 
SELECT
    *,
    '' AS ADA_REVISI
--    MAX(
--	    CASE 
--	        WHEN COALESCE(REVISI1_LINE, REVISI2_LINE, REVISI3_LINE, REVISI4_LINE, REVISI5_LINE) IS NOT NULL
--	             AND COALESCE(REVISI1_LINE, REVISI2_LINE, REVISI3_LINE, REVISI4_LINE, REVISI5_LINE) <> '- |  | '
--	        THEN 1 ELSE 0 
--	    END
--	) OVER () AS ADA_REVISI
FROM
    (
        SELECT
            DISTINCT
    		SALESORDER.CREATIONDATETIME AS CREATIONDATETIME_SALESORDER,
            SALESORDERLINE.LINESTATUS,
            a33.VALUESTRING AS PRODUCTIONORDER_AKW,
            PRODUCTIONDEMAND.CODE AS DEMAND,
            SALESORDER.CODE AS SALESORDERCODE,
            SALESORDERLINE.ORDERLINE,
            BUSINESSPARTNER.POSTALCODE AS ORDERPARTNERPOSTALCODE,
            BUSINESSPARTNER.TOWN AS ORDERPARTNERTOWN,
            BUSINESSPARTNER.DISTRICT AS ORDERPARTNERDISTRICT,
            TERMSOFSHIPPING.LONGDESCRIPTION AS TERMSOFSHPLONGDESCRIPTION,
            PAYMENTMETHOD.LONGDESCRIPTION AS PAYMENTMETHODLONGDESCRIPTION,
            SALESORDERLINE.EXTERNALREFERENCE,
            SALESORDERLINE.INTERNALREFERENCE AS INTERNALREFERENCE_SALESORDERLINE,
            SALESORDERLINE.ITEMTYPEAFICODE,
            SALESORDERLINE.SUBCODE01,
            SALESORDERLINE.SUBCODE02,
            SALESORDERLINE.SUBCODE03,
            SALESORDERLINE.SUBCODE04,
            COALESCE(p.SUBCODE02, SALESORDERLINE.SUBCODE02) AS RESERVATION_SUBCODE02,
            COALESCE(p.SUBCODE03, SALESORDERLINE.SUBCODE03) AS RESERVATION_SUBCODE03,
            COALESCE(p.SUBCODE04, SALESORDERLINE.SUBCODE04) AS RESERVATION_SUBCODE04,
            SALESORDERLINE.SUBCODE05,
            SALESORDERLINE.SUBCODE06,
            SALESORDERLINE.SUBCODE07,
            SALESORDERLINE.SUBCODE08,
            SALESORDERLINE.SUBCODE09,
            SALESORDERLINE.SUBCODE10,
            SALESORDERLINE.USERPRIMARYUOMCODE,
            SALESORDERLINE.USERPRIMARYQUANTITY,
            SALESORDERLINE.USERSECONDARYUOMCODE,
            SALESORDERLINE.USERSECONDARYQUANTITY,
            SALESORDERLINE.BASESECONDARYQUANTITY,
            SALESORDERLINE.BASEPRIMARYQUANTITY,
            SALESORDERLINE.NETVALUE,
            i.WARNA,
            SALESORDERLINE.ABSUNIQUEID AS ABSUNIQUEID_SALESORDERLINE,
            SALESORDER.CODE,
            SALESORDER.ORDERDATE,
            SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE,
            SALESORDER.ORDERPARTNERBRANDCODE,
            SALESORDER.DESCRIPTION,
            SALESORDER.INTERNALREFERENCE AS INTERNALREFERENCE_SALESORDER,
            SALESORDER.STATISTICALGROUPCODE,
            SALESORDER.CREATIONUSER,
            SALESORDER.ABSUNIQUEID AS ABSUNIQUEID_SALESORDER,
            ORDERPARTNER.ABSUNIQUEID AS ABSUNIQUEID_ORDERPARTNER,
            BUSINESSPARTNER.LEGALNAME1,
            BUSINESSPARTNER.PERSON,
            BUSINESSPARTNER.PHONENUMBER,
            BUSINESSPARTNER.FAXNUMBER,
            ADDRESS.ADDRESSEE,
            ADDRESS.ADDRESSLINE1,
            ADDRESS.ADDRESSLINE2,
            ADDRESS.TOWN,
            ADDRESS.DISTRICT,
            ADDRESS.ADDRESSPHONENUMBER,
            ADDRESS.ADDRESSFAXNUMBER,
            COUNTRY.LONGDESCRIPTION,
            COUNTRY_1.LONGDESCRIPTION AS LONGDESCRIPTION_1,
            BUSINESSPARTNER.TAXREGISTRATIONNUMBER,
            BUSINESSPARTNER.FISCALCODE,
            PRODUCTIONDEMAND.ABSUNIQUEID,
            a2.VALUESTRING AS ADDITIONALDATA,
            a7.VALUEDECIMAL AS QTY,
            a3.VALUESTRING AS ADDITIONALDATA2,
            a8.VALUEDECIMAL AS QTY2,
            a4.VALUESTRING AS ADDITIONALDATA3,
            a9.VALUEDECIMAL AS QTY3,
            a5.VALUESTRING AS ADDITIONALDATA4,
            a10.VALUEDECIMAL AS QTY4,
            a6.VALUESTRING AS ADDITIONALDATA5,
            a11.VALUEDECIMAL AS QTY5,
            a35.VALUESTRING AS ADDITIONALDATA6,
            a38.VALUEDECIMAL AS QTY7,
            a18.VALUESTRING AS LEGACYORDER,
            a19.VALUEDECIMAL AS QTY6,
            a12.VALUEDATE AS DATE_AKTUAL,
            a27.VALUEDATE AS DATE_AKTUAL_TO,
            a13.VALUEDATE AS DATE_AKTUAL2,
            a28.VALUEDATE AS DATE_AKTUAL_TO2,
            a14.VALUEDATE AS DATE_AKTUAL3,
            a29.VALUEDATE AS DATE_AKTUAL_TO3,
            a15.VALUEDATE AS DATE_AKTUAL4,
            a30.VALUEDATE AS DATE_AKTUAL_TO4,
            a16.VALUEDATE AS DATE_AKTUAL5,
            a31.VALUEDATE AS DATE_AKTUAL_TO5,
            a20.VALUEDATE AS DATE_AKTUAL6,
            a32.VALUEDATE AS DATE_AKTUAL_TO6,
            a39.VALUEDATE AS DATE_AKTUAL7,
            a40.VALUEDATE AS DATE_AKTUAL_TO7,
            CASE
                WHEN a17.VALUESTRING = '1' THEN 'AKJ'
                WHEN a17.VALUESTRING = '2' THEN 'AKW'
                ELSE 'NON AKJ'
            END AS AKJ,
            CASE
                WHEN a41.VALUESTRING = '1' THEN 'With Shipping'
                ELSE 'Without Shipping'
            END AS shipping_mark,
            a21.VALUESTRING AS PROD_ORDER_AKJ,
            a22.VALUESTRING AS SALESORDER_AKJ,
            a23.VALUESTRING AS PROD_ORDER_AKJ2,
            a24.VALUESTRING AS SALESORDER_AKJ2,
            a25.VALUESTRING AS PROD_ORDER_AKJ3,
            a26.VALUESTRING AS SALESORDER_AKJ3,
            a46.VALUESTRING AS PROD_ORDER_AKJ4,
            a47.VALUESTRING AS SALESORDER_AKJ4,
            a48.VALUESTRING AS PROD_ORDER_AKJ5,
            a49.VALUESTRING AS SALESORDER_AKJ5,
            a34.VALUESTRING AS NOTETAS,
            a42.VALUESTRING AS COLORGROUP,
            SALESORDER.TEMPLATECODE,
            COALESCE(SUBSTRING(
		        a.OPTIONS, 
		        POSITION(';' || a43.VALUESTRING || '=' IN a.OPTIONS) + LENGTH(a43.VALUESTRING) + 2,
		        POSITION(';' IN SUBSTRING(a.OPTIONS, POSITION(';' || a43.VALUESTRING || '=' IN a.OPTIONS) + LENGTH(a43.VALUESTRING) + 2)) - 1
		    ), '-') || ' | ' ||
		    COALESCE(SUBSTRING(
		        a2.OPTIONS, 
		        POSITION(';' || a44.VALUESTRING || '=' IN a2.OPTIONS) + LENGTH(a44.VALUESTRING) + 2,
		        POSITION(';' IN SUBSTRING(a2.OPTIONS, POSITION(';' || a44.VALUESTRING || '=' IN a2.OPTIONS) + LENGTH(a44.VALUESTRING) + 2)) - 1
		    ), '-')AS KET_AKJ,
            p3.ITEMTYPECODE AS ITEMKGF,
            COALESCE(a45.VALUESTRING, '-') AS NOTETAS_KGF,
            a50.VALUESTRING AS ADDITIONALDATA6A,
            a51.VALUEDECIMAL AS QTY6A,
            a52.VALUEDATE AS DATE_AKTUAL6A,
            a53.VALUEDATE AS DATE_AKTUAL_TO6A,
--            REVISI HEADER
            COALESCE(SUBSTRING(
		        ad.OPTIONS, 
		        POSITION(';' || ra.VALUESTRING || '=' IN ad.OPTIONS) + LENGTH(ra.VALUESTRING) + 2,
		        POSITION(';' IN SUBSTRING(ad.OPTIONS, POSITION(';' || ra.VALUESTRING || '=' IN ad.OPTIONS) + LENGTH(ra.VALUESTRING) + 2)) - 1
		    ), '-') || ' | ' || rd.VALUEDATE || ' | ' || dr.VALUESTRING  AS REVISI_HEADER1,
		    COALESCE(SUBSTRING(
		        ad2.OPTIONS, 
		        POSITION(';' || ra2.VALUESTRING || '=' IN ad2.OPTIONS) + LENGTH(ra2.VALUESTRING) + 2,
		        POSITION(';' IN SUBSTRING(ad2.OPTIONS, POSITION(';' || ra2.VALUESTRING || '=' IN ad2.OPTIONS) + LENGTH(ra2.VALUESTRING) + 2)) - 1
		    ), '-') || ' | ' || rd2.VALUEDATE || ' | ' || dr2.VALUESTRING AS REVISI_HEADER2,
		    COALESCE(SUBSTRING(
		        ad3.OPTIONS, 
		        POSITION(';' || ra3.VALUESTRING || '=' IN ad3.OPTIONS) + LENGTH(ra3.VALUESTRING) + 2,
		        POSITION(';' IN SUBSTRING(ad3.OPTIONS, POSITION(';' || ra3.VALUESTRING || '=' IN ad3.OPTIONS) + LENGTH(ra3.VALUESTRING) + 2)) - 1
		    ), '-') || ' | ' || rd3.VALUEDATE || ' | ' || dr3.VALUESTRING AS REVISI_HEADER3,
		    COALESCE(SUBSTRING(
		        ad2.OPTIONS, 
		        POSITION(';' || ra4.VALUESTRING || '=' IN ad4.OPTIONS) + LENGTH(ra4.VALUESTRING) + 2,
		        POSITION(';' IN SUBSTRING(ad4.OPTIONS, POSITION(';' || ra4.VALUESTRING || '=' IN ad4.OPTIONS) + LENGTH(ra4.VALUESTRING) + 2)) - 1
		    ), '-') || ' | ' || rd4.VALUEDATE || ' | ' || dr4.VALUESTRING AS REVISI_HEADER4,
		    COALESCE(SUBSTRING(
		        ad2.OPTIONS, 
		        POSITION(';' || ra5.VALUESTRING || '=' IN ad5.OPTIONS) + LENGTH(ra5.VALUESTRING) + 2,
		        POSITION(';' IN SUBSTRING(ad5.OPTIONS, POSITION(';' || ra5.VALUESTRING || '=' IN ad5.OPTIONS) + LENGTH(ra5.VALUESTRING) + 2)) - 1
		    ), '-') || ' | ' || rd5.VALUEDATE || ' | ' || dr5.VALUESTRING AS REVISI_HEADER5,
		--    REVISI LINE
		    COALESCE(SUBSTRING(
		        l_ad.OPTIONS, 
		        POSITION(';' || aa.VALUESTRING || '=' IN l_ad.OPTIONS) + LENGTH(aa.VALUESTRING) + 2,
		        POSITION(';' IN SUBSTRING(l_ad.OPTIONS, POSITION(';' || aa.VALUESTRING || '=' IN l_ad.OPTIONS) + LENGTH(aa.VALUESTRING) + 2)) - 1
		    ), '-') || ' | ' || l_rd.VALUEDATE || ' | ' || l_dr.VALUESTRING AS REVISI1_LINE,
		    COALESCE(SUBSTRING(
		        l_ad2.OPTIONS, 
		        POSITION(';' || aa1.VALUESTRING || '=' IN l_ad2.OPTIONS) + LENGTH(aa1.VALUESTRING) + 2,
		        POSITION(';' IN SUBSTRING(l_ad2.OPTIONS, POSITION(';' || aa1.VALUESTRING || '=' IN l_ad2.OPTIONS) + LENGTH(aa1.VALUESTRING) + 2)) - 1
		    ), '-') || ' | ' || l_rd2.VALUEDATE || ' | ' || l_dr2.VALUESTRING AS REVISI2_LINE,
		    COALESCE(SUBSTRING(
		        l_ad3.OPTIONS, 
		        POSITION(';' || aa2.VALUESTRING || '=' IN l_ad3.OPTIONS) + LENGTH(aa2.VALUESTRING) + 2,
		        POSITION(';' IN SUBSTRING(l_ad3.OPTIONS, POSITION(';' || aa2.VALUESTRING || '=' IN l_ad3.OPTIONS) + LENGTH(aa2.VALUESTRING) + 2)) - 1
		    ), '-') || ' | ' || l_rd3.VALUEDATE || ' | ' || l_dr3.VALUESTRING AS REVISI3_LINE,
		    COALESCE(SUBSTRING(
		        l_ad2.OPTIONS, 
		        POSITION(';' || aa3.VALUESTRING || '=' IN l_ad4.OPTIONS) + LENGTH(aa3.VALUESTRING) + 2,
		        POSITION(';' IN SUBSTRING(l_ad4.OPTIONS, POSITION(';' || aa3.VALUESTRING || '=' IN l_ad4.OPTIONS) + LENGTH(aa3.VALUESTRING) + 2)) - 1
		    ), '-') || ' | ' || l_rd4.VALUEDATE || ' | ' || l_dr4.VALUESTRING AS REVISI4_LINE,
		    COALESCE(SUBSTRING(
		        l_ad2.OPTIONS, 
		        POSITION(';' || aa4.VALUESTRING || '=' IN l_ad5.OPTIONS) + LENGTH(aa4.VALUESTRING) + 2,
		        POSITION(';' IN SUBSTRING(l_ad5.OPTIONS, POSITION(';' || aa4.VALUESTRING || '=' IN l_ad5.OPTIONS) + LENGTH(aa4.VALUESTRING) + 2)) - 1
		    ), '-') || ' | ' || l_rd5.VALUEDATE || ' | ' || l_dr5.VALUESTRING AS REVISI5_LINE,
		   	CASE
			   	-- HEADER
			    WHEN ra.VALUESTRING <> '0' OR rd.VALUEDATE IS NOT NULL OR dr.VALUESTRING IS NOT NULL THEN 'REVISI'
			    WHEN ra2.VALUESTRING <> '0' OR rd2.VALUEDATE IS NOT NULL OR dr2.VALUESTRING IS NOT NULL THEN 'REVISI'
			    WHEN ra3.VALUESTRING <> '0' OR rd3.VALUEDATE IS NOT NULL OR dr3.VALUESTRING IS NOT NULL THEN 'REVISI'
			    WHEN ra4.VALUESTRING <> '0' OR rd4.VALUEDATE IS NOT NULL OR dr4.VALUESTRING IS NOT NULL THEN 'REVISI'
			    WHEN ra5.VALUESTRING <> '0' OR rd5.VALUEDATE IS NOT NULL OR dr5.VALUESTRING IS NOT NULL THEN 'REVISI'
			    -- LINE
				WHEN aa.VALUESTRING <> '0' OR l_rd.VALUEDATE IS NOT NULL OR l_dr.VALUESTRING IS NOT NULL THEN 'REVISI'
				WHEN aa1.VALUESTRING <> '0' OR l_rd2.VALUEDATE IS NOT NULL OR l_dr2.VALUESTRING IS NOT NULL THEN 'REVISI'
				WHEN aa2.VALUESTRING <> '0' OR l_rd3.VALUEDATE IS NOT NULL OR l_dr3.VALUESTRING IS NOT NULL THEN 'REVISI'
				WHEN aa3.VALUESTRING <> '0' OR l_rd4.VALUEDATE IS NOT NULL OR l_dr4.VALUESTRING IS NOT NULL THEN 'REVISI'
				WHEN aa4.VALUESTRING <> '0' OR l_rd5.VALUEDATE IS NOT NULL OR l_dr5.VALUESTRING IS NOT NULL THEN 'REVISI'
			    ELSE NULL
			END AS REVISI
        FROM
            SALESORDER SALESORDER
        LEFT OUTER JOIN SALESORDERLINE SALESORDERLINE ON SALESORDERLINE.SALESORDERCODE = SALESORDER.CODE AND SALESORDERLINE.LINESTATUS = 1
        LEFT OUTER JOIN PAYMENTMETHOD PAYMENTMETHOD ON PAYMENTMETHOD.CODE = SALESORDERLINE.PAYMENTMETHODCODE
        LEFT OUTER JOIN TERMSOFSHIPPING TERMSOFSHIPPING ON TERMSOFSHIPPING.CODE = SALESORDER.TERMSOFSHIPPINGCODE
        LEFT OUTER JOIN ORDERPARTNERBANK ORDERPARTNERBANK ON SALESORDER.COMPANYCODE = ORDERPARTNERBANK.ORDPRNCSMSUPPLIERCOMPANYCODE AND SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE = ORDERPARTNERBANK.ORDPRNCUSTOMERSUPPLIERCODE
            AND SALESORDER.ORDERPARTNERBANKIDENTIFIER = ORDERPARTNERBANK.IDENTIFIER
        LEFT OUTER JOIN BANK BANK ON ORDERPARTNERBANK.BANKBRANCHCODE = BANK.BRANCHCODE AND ORDERPARTNERBANK.BANKCODE = BANK.CODE
        LEFT OUTER JOIN ORDERPARTNER ORDERPARTNER ON SALESORDER.COMPANYCODE = ORDERPARTNER.CUSTOMERSUPPLIERCOMPANYCODE AND SALESORDER.ORDERTYPE = ORDERPARTNER.CUSTOMERSUPPLIERTYPE AND SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE = ORDERPARTNER.CUSTOMERSUPPLIERCODE
        LEFT OUTER JOIN BUSINESSPARTNER BUSINESSPARTNER ON ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID = BUSINESSPARTNER.NUMBERID
        LEFT OUTER JOIN SALESORDERTEMPLATE SALESORDERTEMPLATE ON SALESORDER.TEMPLATECODE = SALESORDERTEMPLATE.CODE AND SALESORDER.COMPANYCODE = SALESORDERTEMPLATE.COMPANYCODE
        LEFT OUTER JOIN AGENT AGENT ON SALESORDER.COMPANYCODE = AGENT.COMPANYCODE AND SALESORDER.AGENT1CODE = AGENT.CODE
        LEFT OUTER JOIN ADDRESS ADDRESS ON SALESORDER.DELIVERYPOINTUNIQUEID = ADDRESS.UNIQUEID AND SALESORDER.DELIVERYPOINTCODE = ADDRESS.CODE
        LEFT OUTER JOIN COUNTRY COUNTRY ON ADDRESS.COUNTRYCODE = COUNTRY.CODE
        LEFT OUTER JOIN COUNTRY COUNTRY_1 ON BUSINESSPARTNER.COUNTRYCODE = COUNTRY_1.CODE
        LEFT OUTER JOIN PRODUCTIONDEMAND ON PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE = SALESORDERLINE.SALESORDERCODE AND PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE = SALESORDERLINE.ORDERLINE
        LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a2.FIELDNAME = 'ProAllow'
        LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a3.FIELDNAME = 'ProAllow2'
        LEFT JOIN ADSTORAGE a4 ON a4.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a4.FIELDNAME = 'ProAllow3'
        LEFT JOIN ADSTORAGE a5 ON a5.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a5.FIELDNAME = 'ProAllow4'
        LEFT JOIN ADSTORAGE a6 ON a6.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a6.FIELDNAME = 'ProAllow5'
        LEFT JOIN ADSTORAGE a35 ON a35.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a35.FIELDNAME = 'ProAllow7'
        LEFT JOIN ADSTORAGE a7 ON a7.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a7.FIELDNAME = 'ProAllowQty'
        LEFT JOIN ADSTORAGE a8 ON
            a8.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a8.FIELDNAME = 'ProAllowQty2'
        LEFT JOIN ADSTORAGE a9 ON
            a9.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a9.FIELDNAME = 'ProAllowQty3'
        LEFT JOIN ADSTORAGE a10 ON
            a10.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a10.FIELDNAME = 'ProAllowQty4'
        LEFT JOIN ADSTORAGE a11 ON
            a11.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a11.FIELDNAME = 'ProAllowQty5'
        LEFT JOIN ADSTORAGE a38 ON
            a38.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a38.FIELDNAME = 'ProAllowQty7'
        LEFT JOIN ADSTORAGE a12 ON
            a12.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a12.FIELDNAME = 'ProAllowDate'
        LEFT JOIN ADSTORAGE a13 ON
            a13.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a13.FIELDNAME = 'ProAllowDate2'
        LEFT JOIN ADSTORAGE a14 ON
            a14.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a14.FIELDNAME = 'ProAllowDate3'
        LEFT JOIN ADSTORAGE a15 ON
            a15.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a15.FIELDNAME = 'ProAllowDate4'
        LEFT JOIN ADSTORAGE a16 ON
            a16.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a16.FIELDNAME = 'ProAllowDate5'
        LEFT JOIN ADSTORAGE a39 ON
            a39.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a39.FIELDNAME = 'ProAllowDate7'
        LEFT JOIN ADSTORAGE a17 ON
            a17.UNIQUEID = SALESORDERLINE.ABSUNIQUEID
            AND a17.FIELDNAME = 'KainAKJ'
        LEFT JOIN ADSTORAGE a18 ON
            a18.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a18.FIELDNAME = 'LegacyOrder'
        LEFT JOIN ADSTORAGE a19 ON
            a19.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a19.FIELDNAME = 'ProAllowQty6'
        LEFT JOIN ADSTORAGE a20 ON
            a20.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a20.FIELDNAME = 'ProAllowDate6'
        LEFT JOIN ITXVIEWCOLOR i ON
            i.ITEMTYPECODE = SALESORDERLINE.ITEMTYPEAFICODE
            AND i.SUBCODE01 = SALESORDERLINE.SUBCODE01
            AND i.SUBCODE02 = SALESORDERLINE.SUBCODE02
            AND i.SUBCODE03 = SALESORDERLINE.SUBCODE03
            AND i.SUBCODE04 = SALESORDERLINE.SUBCODE04
            AND i.SUBCODE05 = SALESORDERLINE.SUBCODE05
            AND i.SUBCODE06 = SALESORDERLINE.SUBCODE06
            AND i.SUBCODE07 = SALESORDERLINE.SUBCODE07
            AND i.SUBCODE08 = SALESORDERLINE.SUBCODE08
            AND i.SUBCODE09 = SALESORDERLINE.SUBCODE09
            AND i.SUBCODE10 = SALESORDERLINE.SUBCODE10
        LEFT JOIN PRODUCTIONRESERVATION p ON
            p.ORDERCODE = PRODUCTIONDEMAND.CODE
            AND (
                p.ITEMTYPEAFICODE = 'KGF'
                    OR p.ITEMTYPEAFICODE = 'KFF'
            )
        LEFT JOIN ADSTORAGE a21 ON
            a21.UNIQUEID = SALESORDERLINE.ABSUNIQUEID
            AND a21.FIELDNAME = 'PrevProdOrderCode'
        LEFT JOIN ADSTORAGE a22 ON
            a22.UNIQUEID = SALESORDERLINE.ABSUNIQUEID
            AND a22.FIELDNAME = 'PrevSalesOrderCode'
        LEFT JOIN ADSTORAGE a23 ON
            a23.UNIQUEID = SALESORDERLINE.ABSUNIQUEID
            AND a23.FIELDNAME = 'PrevProdOrder2Code'
        LEFT JOIN ADSTORAGE a24 ON
            a24.UNIQUEID = SALESORDERLINE.ABSUNIQUEID
            AND a24.FIELDNAME = 'PrevSalesOrder2Code'
        LEFT JOIN ADSTORAGE a25 ON
            a25.UNIQUEID = SALESORDERLINE.ABSUNIQUEID
            AND a25.FIELDNAME = 'PrevProdOrder3Code'
        LEFT JOIN ADSTORAGE a26 ON
            a26.UNIQUEID = SALESORDERLINE.ABSUNIQUEID
            AND a26.FIELDNAME = 'PrevSalesOrder3Code'
        LEFT JOIN ADSTORAGE a46 ON
            a46.UNIQUEID = SALESORDERLINE.ABSUNIQUEID
            AND a46.FIELDNAME = 'PrevProdOrder4Code'
        LEFT JOIN ADSTORAGE a47 ON
            a47.UNIQUEID = SALESORDERLINE.ABSUNIQUEID
            AND a47.FIELDNAME = 'PrevSalesOrder4Code'
        LEFT JOIN ADSTORAGE a48 ON
            a48.UNIQUEID = SALESORDERLINE.ABSUNIQUEID
            AND a48.FIELDNAME = 'PrevProdOrder5Code'
        LEFT JOIN ADSTORAGE a49 ON
            a49.UNIQUEID = SALESORDERLINE.ABSUNIQUEID
            AND a49.FIELDNAME = 'PrevSalesOrder5Code'
        LEFT JOIN ADSTORAGE a27 ON
            a27.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a27.FIELDNAME = 'ProAllowDateto'
        LEFT JOIN ADSTORAGE a28 ON
            a28.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a28.FIELDNAME = 'ProAllowDate2to'
        LEFT JOIN ADSTORAGE a29 ON
            a29.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a29.FIELDNAME = 'ProAllowDate3to'
        LEFT JOIN ADSTORAGE a30 ON
            a30.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a30.FIELDNAME = 'ProAllowDate4to'
        LEFT JOIN ADSTORAGE a31 ON
            a31.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a31.FIELDNAME = 'ProAllowDate5to'
        LEFT JOIN ADSTORAGE a32 ON
            a32.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a32.FIELDNAME = 'ProAllowDate6to'
        LEFT JOIN ADSTORAGE a40 ON
            a40.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a40.FIELDNAME = 'ProAllowDate7to'
        LEFT JOIN ADSTORAGE a33 ON
            a33.UNIQUEID = SALESORDERLINE.ABSUNIQUEID
            AND a33.FIELDNAME = 'PrevProdOrderCode'
        LEFT JOIN PRODUCT PRODUCT ON
            PRODUCT.ITEMTYPECODE = PRODUCTIONDEMAND.ITEMTYPEAFICODE
            AND PRODUCT.SUBCODE01 = PRODUCTIONDEMAND.SUBCODE01
            AND PRODUCT.SUBCODE02 = PRODUCTIONDEMAND.SUBCODE02
            AND PRODUCT.SUBCODE03 = PRODUCTIONDEMAND.SUBCODE03
            AND PRODUCT.SUBCODE04 = PRODUCTIONDEMAND.SUBCODE04
            AND PRODUCT.SUBCODE05 = PRODUCTIONDEMAND.SUBCODE05
            AND PRODUCT.SUBCODE06 = PRODUCTIONDEMAND.SUBCODE06
            AND PRODUCT.SUBCODE07 = PRODUCTIONDEMAND.SUBCODE07
            AND PRODUCT.SUBCODE08 = PRODUCTIONDEMAND.SUBCODE08
            AND PRODUCT.SUBCODE09 = PRODUCTIONDEMAND.SUBCODE09
            AND PRODUCT.SUBCODE10 = PRODUCTIONDEMAND.SUBCODE10
        LEFT JOIN ADSTORAGE a34 ON
            a34.UNIQUEID = PRODUCT.ABSUNIQUEID
            AND a34.FIELDNAME = 'NoteTas'
        LEFT JOIN ADSTORAGE a41 ON
            a41.UNIQUEID = BUSINESSPARTNER.ABSUNIQUEID
            AND a41.FIELDNAME = 'ShippingMark'
        LEFT JOIN USERGENERICGROUP u2 ON
            u2.CODE = SALESORDERLINE.SUBCODE05
            AND u2.USERGENERICGROUPTYPECODE = 'CL1'
        LEFT JOIN ADSTORAGE a42 ON
            a42.UNIQUEID = u2.ABSUNIQUEID
            AND a42.FIELDNAME = 'ColorGroupCode'
        LEFT JOIN ADSTORAGE a43 ON
            a43.UNIQUEID = SALESORDERLINE.ABSUNIQUEID
            AND a43.FIELDNAME = 'cocokwarna'
        LEFT JOIN ADADDITIONALDATA a ON
            a.NAME = a43.FIELDNAME
        LEFT JOIN ADSTORAGE a44 ON
            a44.UNIQUEID = SALESORDERLINE.ABSUNIQUEID
            AND a44.FIELDNAME = 'Colorist'
        LEFT JOIN ADADDITIONALDATA a2 ON
            a2.NAME = a44.FIELDNAME
        LEFT JOIN PRODUCT p3 ON
            p3.ITEMTYPECODE = 'KGF'
            AND p3.SUBCODE01 = PRODUCTIONDEMAND.SUBCODE01
            AND p3.SUBCODE02 = PRODUCTIONDEMAND.SUBCODE02
            AND p3.SUBCODE03 = PRODUCTIONDEMAND.SUBCODE03
            AND p3.SUBCODE04 = PRODUCTIONDEMAND.SUBCODE04
        LEFT JOIN ADSTORAGE a45 ON
            a45.UNIQUEID = p3.ABSUNIQUEID
            AND a45.FIELDNAME = 'NoteTas'
        LEFT JOIN ADSTORAGE a50 ON
            a50.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a50.FIELDNAME = 'ProAllow6'
        LEFT JOIN ADSTORAGE a51 ON
            a51.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a51.FIELDNAME = 'ProAllowQty6a'
        LEFT JOIN ADSTORAGE a52 ON
            a52.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a52.FIELDNAME = 'ProAllowDate6a'
        LEFT JOIN ADSTORAGE a53 ON
            a53.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID
            AND a53.FIELDNAME = 'ProAllowDate6ato'
        -- REVISI HEADER NAME
		LEFT JOIN ADSTORAGE ra ON ra.UNIQUEID = SALESORDER.ABSUNIQUEID AND ra.FIELDNAME = 'RevisiC'
		LEFT JOIN ADSTORAGE ra2 ON ra2.UNIQUEID = SALESORDER.ABSUNIQUEID AND ra2.FIELDNAME = 'Revisi2'
		LEFT JOIN ADSTORAGE ra3 ON ra3.UNIQUEID = SALESORDER.ABSUNIQUEID AND ra3.FIELDNAME = 'Revisi3'
		LEFT JOIN ADSTORAGE ra4 ON ra4.UNIQUEID = SALESORDER.ABSUNIQUEID AND ra4.FIELDNAME = 'Revisi4'
		LEFT JOIN ADSTORAGE ra5 ON ra5.UNIQUEID = SALESORDER.ABSUNIQUEID AND ra5.FIELDNAME = 'Revisi5'
		-- WHO REVISI HEADER NAME
		LEFT JOIN ADADDITIONALDATA ad ON ad.ENTITYNAME = 'SalesOrder' AND ad.NAME = 'RevisiC'
		LEFT JOIN ADADDITIONALDATA ad2 ON ad2.ENTITYNAME = 'SalesOrder' AND ad2.NAME = 'Revisi2'
		LEFT JOIN ADADDITIONALDATA ad3 ON ad3.ENTITYNAME = 'SalesOrder' AND ad3.NAME = 'Revisi3'
		LEFT JOIN ADADDITIONALDATA ad4 ON ad4.ENTITYNAME = 'SalesOrder' AND ad4.NAME = 'Revisi4'
		LEFT JOIN ADADDITIONALDATA ad5 ON ad5.ENTITYNAME = 'SalesOrder' AND ad5.NAME = 'Revisi5'
		-- REVISI HEADER DATE
		LEFT JOIN ADSTORAGE rd ON rd.UNIQUEID = SALESORDER.ABSUNIQUEID AND rd.FIELDNAME = 'Revisi1Date'
		LEFT JOIN ADSTORAGE rd2 ON rd2.UNIQUEID = SALESORDER.ABSUNIQUEID AND rd2.FIELDNAME = 'Revisi2Date'
		LEFT JOIN ADSTORAGE rd3 ON rd3.UNIQUEID = SALESORDER.ABSUNIQUEID AND rd3.FIELDNAME = 'Revisi3Date'
		LEFT JOIN ADSTORAGE rd4 ON rd4.UNIQUEID = SALESORDER.ABSUNIQUEID AND rd4.FIELDNAME = 'Revisi4Date'
		LEFT JOIN ADSTORAGE rd5 ON rd5.UNIQUEID = SALESORDER.ABSUNIQUEID AND rd5.FIELDNAME = 'Revisi5Date'
		-- REVISI HEADER DETAIL
		LEFT JOIN ADSTORAGE dr ON dr.UNIQUEID = SALESORDER.ABSUNIQUEID AND dr.FIELDNAME = 'RevisiN'
		LEFT JOIN ADSTORAGE dr2 ON dr2.UNIQUEID = SALESORDER.ABSUNIQUEID AND dr2.FIELDNAME = 'DRevisi2'
		LEFT JOIN ADSTORAGE dr3 ON dr3.UNIQUEID = SALESORDER.ABSUNIQUEID AND dr3.FIELDNAME = 'DRevisi3'
		LEFT JOIN ADSTORAGE dr4 ON dr4.UNIQUEID = SALESORDER.ABSUNIQUEID AND dr4.FIELDNAME = 'DRevisi4'
		LEFT JOIN ADSTORAGE dr5 ON dr5.UNIQUEID = SALESORDER.ABSUNIQUEID AND dr5.FIELDNAME = 'DRevisi5'
		--------------------------------------------------------------------------------------------------
		-- REVISI LINE NAME
		LEFT JOIN ADSTORAGE aa ON aa.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND aa.FIELDNAME = 'salesorderRevisiC'
		LEFT JOIN ADSTORAGE aa1 ON aa1.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND aa1.FIELDNAME = 'RevisiC1'
		LEFT JOIN ADSTORAGE aa2 ON aa2.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND aa2.FIELDNAME = 'RevisiC2'
		LEFT JOIN ADSTORAGE aa3 ON aa3.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND aa3.FIELDNAME = 'RevisiC3'
		LEFT JOIN ADSTORAGE aa4 ON aa4.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND aa4.FIELDNAME = 'RevisiC4'
		-- WHO REVISI HEADER NAME
		LEFT JOIN ADADDITIONALDATA l_ad ON l_ad.ENTITYNAME = 'SalesOrderLine' AND l_ad.NAME = 'RevisiC'
		LEFT JOIN ADADDITIONALDATA l_ad2 ON l_ad2.ENTITYNAME = 'SalesOrderLine' AND l_ad2.NAME = 'RevisiC1'
		LEFT JOIN ADADDITIONALDATA l_ad3 ON l_ad3.ENTITYNAME = 'SalesOrderLine' AND l_ad3.NAME = 'RevisiC2'
		LEFT JOIN ADADDITIONALDATA l_ad4 ON l_ad4.ENTITYNAME = 'SalesOrderLine' AND l_ad4.NAME = 'RevisiC3'
		LEFT JOIN ADADDITIONALDATA l_ad5 ON l_ad5.ENTITYNAME = 'SalesOrderLine' AND l_ad5.NAME = 'RevisiC4'
		-- REVISI LINE DATE
		LEFT JOIN ADSTORAGE l_rd ON l_rd.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND l_rd.FIELDNAME = 'Revisi1Date'
		LEFT JOIN ADSTORAGE l_rd2 ON l_rd2.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND l_rd2.FIELDNAME = 'Revisi2Date'
		LEFT JOIN ADSTORAGE l_rd3 ON l_rd3.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND l_rd3.FIELDNAME = 'Revisi3Date'
		LEFT JOIN ADSTORAGE l_rd4 ON l_rd4.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND l_rd4.FIELDNAME = 'Revisi4Date'
		LEFT JOIN ADSTORAGE l_rd5 ON l_rd5.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND l_rd5.FIELDNAME = 'Revisi5Date'
		-- REVISI LINE DETAIL
		LEFT JOIN ADSTORAGE l_dr ON l_dr.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND l_dr.FIELDNAME = 'Revisid'
		LEFT JOIN ADSTORAGE l_dr2 ON l_dr2.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND l_dr2.FIELDNAME = 'Revisi2'
		LEFT JOIN ADSTORAGE l_dr3 ON l_dr3.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND l_dr3.FIELDNAME = 'Revisi3'
		LEFT JOIN ADSTORAGE l_dr4 ON l_dr4.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND l_dr4.FIELDNAME = 'Revisi4'
		LEFT JOIN ADSTORAGE l_dr5 ON l_dr5.UNIQUEID = SALESORDERLINE.ABSUNIQUEID AND l_dr5.FIELDNAME = 'Revisi5'
        WHERE
                                        SALESORDER.CODE = 'DOM2500780' AND
            --    PRODUCTIONDEMAND.CODE ='00368906' AND 
            --            SALESORDERLINE.SUBCODE03 = '19106' AND
--                        SALESORDERLINE.ORDERLINE='10' AND 
            SALESORDERLINE.LINESTATUS = 1
            AND SALESORDER.CODE IS NOT NULL
        ORDER BY
            PRODUCTIONDEMAND.CODE ASC
    );