DROP VIEW ITXVIEW_KGBRUTO_SALES;
--CREATE VIEW ITXVIEW_KGBRUTO_SALES AS
SELECT
    p.ORIGDLVSALORDLINESALORDERCODE AS PROJECTCODE,
    p.CODE,
    p2.PRODUCTIONORDERCODE,
    p.ITEMTYPEAFICODE AS ITEMTYPE_DEMAND,
    p.SUBCODE01,
    p.SUBCODE02,
    p.SUBCODE03,
    p.SUBCODE04,
    p.SUBCODE05,
    p.SUBCODE06,
    p.SUBCODE07,
    p.SUBCODE08,
    p.SUBCODE09,
    p.SUBCODE10,
    p.ORIGDLVSALORDERLINEORDERLINE,
    p2.ITEMTYPEAFICODE AS ITEMTYPE_RESERVATION,
    p2.USERPRIMARYUOMCODE,
    p2.USERPRIMARYQUANTITY,
    CASE
        WHEN s2.EXTERNALREFERENCE IS NULL THEN s.EXTERNALREFERENCE
        ELSE s2.EXTERNALREFERENCE
    END AS EXTERNALREFERENCE
FROM
    PRODUCTIONDEMAND p
LEFT JOIN PRODUCTIONRESERVATION p2 ON p2.ORDERCODE = p.CODE
LEFT JOIN SALESORDERLINE s ON s.SALESORDERCODE = p.ORIGDLVSALORDLINESALORDERCODE AND s.ORDERLINE = p.ORIGDLVSALORDERLINEORDERLINE
LEFT JOIN SALESORDER s2 ON s2.CODE = s.SALESORDERCODE
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p.ABSUNIQUEID 
WHERE
    (p2.ITEMTYPEAFICODE = 'KGF')
    AND (p.ITEMTYPEAFICODE = 'KFF')
    AND a.NAMENAME = 'DefectNote'