DROP VIEW ITXVIEWLABCOLORQLT_DETAIL;
--CREATE VIEW ITXVIEWLABCOLORQLT_DETAIL AS
SELECT
    DISTINCT 
	QUALITYDOCUMENT.LOTCODE,
    QUALITYDOCLINE.QUALITYDOCUMENTHEADERLINE,
    QUALITYDOCLINE_LABCOLOUR.ANNOTATION AS LABCOLOUR,
    QUALITYDOCLINE_LABCLRNUM.ANNOTATION AS LABCLRNUM,
    QUALITYDOCLINE_LABCAT.ANNOTATION AS LABCAT,
    QUALITYDOCLINE_LABBLEED.ANNOTATION AS LABBLEED,
    QUALITYDOCLINE_LABDYEMIG.ANNOTATION AS LABDYEMIG,
    QUALITYDOCLINE_LABPHEN.ANNOTATION AS LABPHEN,
    QUALITYDOCLINE_LABTRANS.ANNOTATION AS LABTRANS,
    QUALITYDOCLINE_LABPLIGHT.ANNOTATION AS LABPLIGHT,
    QUALITYDOCLINE_LABCHLOR.ANNOTATION AS LABCHLOR,
    QUALITYDOCLINE_LABCOLOUR_QTY.VALUEQUANTITY AS LABCOLOUR_QTY,
    QUALITYDOCLINE_LABCLRNUM_QTY.VALUEQUANTITY AS LABCLRNUM_QTY,
    QUALITYDOCLINE_LABCAT_QTY.VALUEQUANTITY AS LABCAT_QTY,
    QUALITYDOCLINE_LABDIPCLRF_QTY.VALUEQUANTITY AS LABDIPCLRF_QTY,
    QUALITYDOCLINE_LABDIPCLRW_QTY.VALUEQUANTITY AS LABDIPCLRW_QTY,
    QUALITYDOCLINE_LABDIPCLRP_QTY.VALUEQUANTITY AS LABDIPCLRP_QTY,
    QUALITYDOCLINE_LABCLRSWH_QTY.VALUEQUANTITY AS LABCLRSWH_QTY,
    QUALITYDOCLINE_LABCLRSWR_QTY.VALUEQUANTITY AS LABCLRSWR_QTY,
    QUALITYDOCLINE_LABCLRPR_QTY.VALUEQUANTITY AS LABCLRPR_QTY,
    QUALITYDOCLINE_LABCLRSWHN_QTY.VALUEQUANTITY AS LABCLRSWHN_QTY,
    QUALITYDOCLINE_LABCLRSWRN_QTY.VALUEQUANTITY AS LABCLRSWRN_QTY,
    QUALITYDOCLINE_LABCLRPRN_QTY.VALUEQUANTITY AS LABCLRPRN_QTY,
    QUALITYDOCLINE_LABCLRSWHP_QTY.VALUEQUANTITY AS LABCLRSWHP_QTY,
    QUALITYDOCLINE_LABCLRSWRP_QTY.VALUEQUANTITY AS LABCLRSWRP_QTY,
    QUALITYDOCLINE_LABCLRPRP_QTY.VALUEQUANTITY AS LABCLRPRP_QTY,
    QUALITYDOCLINE_LABCRKDRY_QTY.VALUEQUANTITY AS LABCRKDRY_QTY,
    QUALITYDOCLINE_LABCRKWET_QTY.VALUEQUANTITY AS LABCRKWET_QTY,
    QUALITYDOCLINE_LABLIGHT_QTY.ANNOTATION AS LABLIGHT_QTY,
    QUALITYDOCLINE_LABBLEED_QTY.ANNOTATION AS LABBLEED_QTY,
    QUALITYDOCLINE_LABDYEMIG_QTY.ANNOTATION AS LABDYEMIG_QTY,
    QUALITYDOCLINE_LABPHEN_QTY.ANNOTATION AS LABPHEN_QTY,
    QUALITYDOCLINE_LABTRANS_QTY.ANNOTATION AS LABTRANS_QTY,
    QUALITYDOCLINE_LABPLIGHT_QTY.ANNOTATION AS LABPLIGHT_QTY,
    QUALITYDOCLINE_LABCHLOR_QTY.ANNOTATION AS LABCHLOR_QTY,
    QUALITYDOCLINE_LABNCHLOR_QTY.ANNOTATION AS LABNCHLOR_QTY,
    QUALITYDOCLINE_LABCSSTN_QTY.ANNOTATION AS LABCSSTN_QTY,
    QUALITYDOCLINE_LABCLRSWHA_QTY.VALUEQUANTITY AS LABCLRSWHA_QTY,
    QUALITYDOCLINE_LABCLRSWHC_QTY.VALUEQUANTITY AS LABCLRSWHC_QTY,
    QUALITYDOCLINE_LABCLRSWHW_QTY.VALUEQUANTITY AS LABCLRSWHW_QTY,
    QUALITYDOCLINE_LABCLRSWRA_QTY.VALUEQUANTITY AS LABCLRSWRA_QTY,
    QUALITYDOCLINE_LABCLRSWRC_QTY.VALUEQUANTITY AS LABCLRSWRC_QTY,
    QUALITYDOCLINE_LABCLRSWRW_QTY.VALUEQUANTITY AS LABCLRSWRW_QTY,
    QUALITYDOCLINE_LABCLRPRT_QTY.VALUEQUANTITY AS LABCLRPRT_QTY,
    QUALITYDOCLINE_LABCLRPRC_QTY.VALUEQUANTITY AS LABCLRPRC_QTY,
    QUALITYDOCLINE_LABCLRPRW_QTY.VALUEQUANTITY AS LABCLRPRW_QTY,
    COALESCE(QUALITYDOCLINE_LABBLEEDR_QTY.ANNOTATION, 'N/A') AS LABBLEEDR_QTY,
    COALESCE(QUALITYDOCLINE_LABBLEEDW_QTY.ANNOTATION, 'N/A') AS LABBLEEDW_QTY,
    COALESCE(QUALITYDOCLINE_LABAAW_QTY.ANNOTATION, 'N/A') AS LABAAW_QTY,
    COALESCE(QUALITYDOCLINE_LABSALIVA_QTY.ANNOTATION, 'N/A') AS LABSALIVA_QTY,
    COALESCE(QUALITYDOCLINE_LABCOLORB_QTY.ANNOTATION, 'N/A') AS LABCOLORB_QTY
FROM
    QUALITYDOCUMENT QUALITYDOCUMENT
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE ON
    QUALITYDOCLINE.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCOLOUR ON
    QUALITYDOCLINE_LABCOLOUR.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCOLOUR.CHARACTERISTICCODE = 'LABCOLOUR'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRNUM ON
    QUALITYDOCLINE_LABCLRNUM.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRNUM.CHARACTERISTICCODE = 'LABCLRNUM'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCAT ON
    QUALITYDOCLINE_LABCAT.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCAT.CHARACTERISTICCODE = 'LABCAT'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABBLEED ON
    QUALITYDOCLINE_LABBLEED.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABBLEED.CHARACTERISTICCODE = 'LABBLEED'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABDYEMIG ON
    QUALITYDOCLINE_LABDYEMIG.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABDYEMIG.CHARACTERISTICCODE = 'LABDYEMIG'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABPHEN ON
    QUALITYDOCLINE_LABPHEN.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABPHEN.CHARACTERISTICCODE = 'LABPHEN'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABTRANS ON
    QUALITYDOCLINE_LABTRANS.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABTRANS.CHARACTERISTICCODE = 'LABTRANS'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABPLIGHT ON
    QUALITYDOCLINE_LABPLIGHT.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABPLIGHT.CHARACTERISTICCODE = 'LABPLIGHT'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCHLOR ON
    QUALITYDOCLINE_LABCHLOR.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCHLOR.CHARACTERISTICCODE = 'LABCHLOR'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCOLOUR_QTY ON
    QUALITYDOCLINE_LABCOLOUR_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCOLOUR_QTY.CHARACTERISTICCODE = 'LABCOLOUR'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRNUM_QTY ON
    QUALITYDOCLINE_LABCLRNUM_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRNUM_QTY.CHARACTERISTICCODE = 'LABCLRNUM'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCAT_QTY ON
    QUALITYDOCLINE_LABCAT_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCAT_QTY.CHARACTERISTICCODE = 'LABCAT'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABDIPCLRF_QTY ON
    QUALITYDOCLINE_LABDIPCLRF_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABDIPCLRF_QTY.CHARACTERISTICCODE = 'LABDIPCLRF'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABDIPCLRW_QTY ON
    QUALITYDOCLINE_LABDIPCLRW_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABDIPCLRW_QTY.CHARACTERISTICCODE = 'LABDIPCLRW'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABDIPCLRP_QTY ON
    QUALITYDOCLINE_LABDIPCLRP_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABDIPCLRP_QTY.CHARACTERISTICCODE = 'LABDIPCLRP'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWH_QTY ON
    QUALITYDOCLINE_LABCLRSWH_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRSWH_QTY.CHARACTERISTICCODE = 'LABCLRSWH'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWR_QTY ON
    QUALITYDOCLINE_LABCLRSWR_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRSWR_QTY.CHARACTERISTICCODE = 'LABCLRSWR'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRPR_QTY ON
    QUALITYDOCLINE_LABCLRPR_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRPR_QTY.CHARACTERISTICCODE = 'LABCLRPR'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWHN_QTY ON
    QUALITYDOCLINE_LABCLRSWHN_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRSWHN_QTY.CHARACTERISTICCODE = 'LABCLRSWHN'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWRN_QTY ON
    QUALITYDOCLINE_LABCLRSWRN_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRSWRN_QTY.CHARACTERISTICCODE = 'LABCLRSWRN'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRPRN_QTY ON
    QUALITYDOCLINE_LABCLRPRN_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRPRN_QTY.CHARACTERISTICCODE = 'LABCLRPRN'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWHP_QTY ON
    QUALITYDOCLINE_LABCLRSWHP_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRSWHP_QTY.CHARACTERISTICCODE = 'LABCLRSWHP'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWRP_QTY ON
    QUALITYDOCLINE_LABCLRSWRP_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRSWRP_QTY.CHARACTERISTICCODE = 'LABCLRSWRP'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRPRP_QTY ON
    QUALITYDOCLINE_LABCLRPRP_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRPRP_QTY.CHARACTERISTICCODE = 'LABCLRPRP'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCRKDRY_QTY ON
    QUALITYDOCLINE_LABCRKDRY_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCRKDRY_QTY.CHARACTERISTICCODE = 'LABCRKDRY'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCRKWET_QTY ON
    QUALITYDOCLINE_LABCRKWET_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCRKWET_QTY.CHARACTERISTICCODE = 'LABCRKWET'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABLIGHT_QTY ON
    QUALITYDOCLINE_LABLIGHT_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABLIGHT_QTY.CHARACTERISTICCODE = 'LABLIGHT'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABBLEED_QTY ON
    QUALITYDOCLINE_LABBLEED_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABBLEED_QTY.CHARACTERISTICCODE = 'LABBLEED'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABDYEMIG_QTY ON
    QUALITYDOCLINE_LABDYEMIG_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABDYEMIG_QTY.CHARACTERISTICCODE = 'LABDYEMIG'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABPHEN_QTY ON
    QUALITYDOCLINE_LABPHEN_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABPHEN_QTY.CHARACTERISTICCODE = 'LABPHEN'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABTRANS_QTY ON
    QUALITYDOCLINE_LABTRANS_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABTRANS_QTY.CHARACTERISTICCODE = 'LABTRANS'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABPLIGHT_QTY ON
    QUALITYDOCLINE_LABPLIGHT_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABPLIGHT_QTY.CHARACTERISTICCODE = 'LABPLIGHT'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCHLOR_QTY ON
    QUALITYDOCLINE_LABCHLOR_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCHLOR_QTY.CHARACTERISTICCODE = 'LABCHLOR'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABNCHLOR_QTY ON
    QUALITYDOCLINE_LABNCHLOR_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABNCHLOR_QTY.CHARACTERISTICCODE = 'LABNCHLOR'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCSSTN_QTY ON
    QUALITYDOCLINE_LABCSSTN_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCSSTN_QTY.CHARACTERISTICCODE = 'LABCSSTN'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWHA_QTY ON
    QUALITYDOCLINE_LABCLRSWHA_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRSWHA_QTY.CHARACTERISTICCODE = 'LABCLRSWHA'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWHC_QTY ON
    QUALITYDOCLINE_LABCLRSWHC_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRSWHC_QTY.CHARACTERISTICCODE = 'LABCLRSWHC'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWHW_QTY ON
    QUALITYDOCLINE_LABCLRSWHW_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRSWHW_QTY.CHARACTERISTICCODE = 'LABCLRSWHW'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWRA_QTY ON
    QUALITYDOCLINE_LABCLRSWRA_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRSWRA_QTY.CHARACTERISTICCODE = 'LABCLRSWRA'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWRC_QTY ON
    QUALITYDOCLINE_LABCLRSWRC_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRSWRC_QTY.CHARACTERISTICCODE = 'LABCLRSWRC'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRSWRW_QTY ON
    QUALITYDOCLINE_LABCLRSWRW_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRSWRW_QTY.CHARACTERISTICCODE = 'LABCLRSWRW'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRPRT_QTY ON
    QUALITYDOCLINE_LABCLRPRT_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRPRT_QTY.CHARACTERISTICCODE = 'LABCLRPRT'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRPRC_QTY ON
    QUALITYDOCLINE_LABCLRPRC_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRPRC_QTY.CHARACTERISTICCODE = 'LABCLRPRC'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCLRPRW_QTY ON
    QUALITYDOCLINE_LABCLRPRW_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCLRPRW_QTY.CHARACTERISTICCODE = 'LABCLRPRW'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABBLEEDR_QTY ON
    QUALITYDOCLINE_LABBLEEDR_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABBLEEDR_QTY.CHARACTERISTICCODE = 'LABBLEEDR'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABBLEEDW_QTY ON
    QUALITYDOCLINE_LABBLEEDW_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABBLEEDW_QTY.CHARACTERISTICCODE = 'LABBLEEDW'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABAAW_QTY ON
    QUALITYDOCLINE_LABAAW_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABAAW_QTY.CHARACTERISTICCODE = 'LABAAW'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABSALIVA_QTY ON
    QUALITYDOCLINE_LABSALIVA_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABSALIVA_QTY.CHARACTERISTICCODE = 'LABSALIVA'
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE_LABCOLORB_QTY ON
    QUALITYDOCLINE_LABCOLORB_QTY.QUALITYDOCUMENTHEADERLINE = QUALITYDOCUMENT.HEADERLINE
    AND QUALITYDOCLINE_LABCOLORB_QTY.CHARACTERISTICCODE = 'LABCOLORB'
WHERE
    QUALITYDOCLINE_LABCOLOUR.QUALITYDOCUMENTHEADERCODE = 'LABDIP'
            AND QUALITYDOCUMENT.LOTCODE LIKE '%LAB2600144%';