DROP VIEW ITXVIEW_NETTO;
--CREATE VIEW ITXVIEW_NETTO AS
SELECT
    p.CODE,
    s.SALESORDERLINESALESORDERCODE,
    s2.PRICEUNITOFMEASURECODE,
    s2.USERPRIMARYQUANTITY,
    s2.USERPRIMARYUOMCODE,
    s2.USERSECONDARYQUANTITY,
    s2.USERSECONDARYUOMCODE,
    s2.BASESECONDARYQUANTITY,
    s2.BASESECONDARYUOMCODE,
    p2.SECONDARYUNSTEADYCVSFACTOR
FROM
    PRODUCTIONDEMAND p
LEFT JOIN SALESORDERDELIVERY s ON s.SALORDLINESALORDERCOMPANYCODE = p.COMPANYCODE
								AND s.SALORDLINESALORDERCOUNTERCODE = p.DLVSALORDLINESALORDCNTCODE
							    AND s.SALESORDERLINESALESORDERCODE = p.DLVSALORDERLINESALESORDERCODE
							    AND s.SALESORDERLINEORDERLINE = p.DLVSALESORDERLINEORDERLINE
							    AND s.SALESORDERLINEORDERSUBLINE = p.DLVSALESORDERLINEORDERSUBLINE
							    AND s.SALORDLINECOMPONENTORDERLINE = p.DLVSALORDLINECMPORDERLINE
							    AND s.DELIVERYLINE = p.DELIVERYDELIVERYLINE
LEFT JOIN SALESORDERLINE s2 ON s2.SALESORDERCODE = s.SALESORDERLINESALESORDERCODE AND s2.ORDERLINE = s.SALESORDERLINEORDERLINE
LEFT JOIN PRODUCT p2 ON p2.SUBCODE01 = s.SUBCODE01
				    AND p2.SUBCODE02 = s.SUBCODE02
				    AND p2.SUBCODE03 = s.SUBCODE03
				    AND p2.SUBCODE04 = s.SUBCODE04
				    AND p2.SUBCODE05 = s.SUBCODE05
				    AND p2.SUBCODE06 = s.SUBCODE06
				    AND p2.SUBCODE07 = s.SUBCODE07
				    AND p2.SUBCODE08 = s.SUBCODE08
				    AND p2.SUBCODE09 = s.SUBCODE09
				    AND p2.SUBCODE10 = s.SUBCODE10;