DROP VIEW ITXVIEW_INVOICE_NOINVOICE_NILO;
--CREATE VIEW ITXVIEW_INVOICE_NOINVOICE_NILO AS
SELECT
    '' AS TEST,
    COMPANYCODE,
    DIVISIONCODE,
    Invoice,
    NO_SJ,
    tgl_inv,
    issue_date,
    tanggal_inv,
    tgl_create,
    due,
    DUEKB,
    DATEKB,
    jenis_order,
    kode_bep,
    id_bep,
    nama_bep,
    kode_cus,
    nama_cus,
    CASE
        WHEN jenis_order = 'EXPORT'
        AND id_bep <> 989 THEN '0'
        WHEN jenis_order = 'SAMPLE'
        AND id_bep <> 888
        AND id_bep <> 813
        OR kode_cus = 'BIHQSS' THEN '0'
        WHEN jenis_order = 'REPLCEXP'
        AND id_bep <> 888 THEN '0'
        ELSE NPWP
    END AS NPWP,
    FAKTUR_PAJAK,
    NO_ORDER,
    CASE
        WHEN NO_PO IS NULL THEN 'Nomor PO Header dan Line Kosong'
        ELSE NO_PO
    END AS NO_PO,
    NO_CI,
    desc_kain,
    code_payment,
    curr,
    CASE
        WHEN ppn = 'S03' THEN 0.11
        WHEN ppn = 'S01' THEN 0.11
        WHEN ppn = 'S13' THEN 0.11
        WHEN ppn = 'N01' THEN 0
        ELSE 0
    END AS ppn,
    payment_terms,
    unit,
    rate,
    biaya_tambahan,
--    BERAT
--    BERAT_LAIN,
--    CASE
--        WHEN curr = 'IDR' THEN 0
--        ELSE (JUMLAH_HARGA) + (biaya_tambahan)
--    END AS DPP,
--    floor((JUMLAH_HARGA + biaya_tambahan) * rate) AS DPP_BC,
--    CASE
--        WHEN curr = 'IDR' THEN 0
--        ELSE round(CASE WHEN PPN = 'S01' THEN (JUMLAH_HARGA + biaya_tambahan) * 0.11 WHEN PPN = 'S03' THEN (JUMLAH_HARGA + biaya_tambahan) * 0.11 WHEN PPN = 'S13' THEN (JUMLAH_HARGA + biaya_tambahan) * 0.11 ELSE 0 END, 2)
--    END AS VAT,
--    CASE
--        WHEN PPN = 'S01' THEN floor(floor((JUMLAH_HARGA + biaya_tambahan) * rate) * 0.11)
--        WHEN PPN = 'S03' THEN floor(floor((JUMLAH_HARGA + biaya_tambahan) * rate) * 0.11)
--        WHEN PPN = 'S13' THEN floor(floor((JUMLAH_HARGA + biaya_tambahan) * rate) * 0.11)
--        ELSE 0
--    END AS VAT_BC,
--    CASE
--        WHEN curr = 'IDR' THEN 0
--        ELSE round(JUMLAH_HARGA + biaya_tambahan + CASE WHEN PPN = 'S01' THEN (JUMLAH_HARGA + biaya_tambahan) * 0.11 WHEN PPN = 'S03' THEN (JUMLAH_HARGA + biaya_tambahan) * 0.11 WHEN PPN = 'S13' THEN (JUMLAH_HARGA + biaya_tambahan) * 0.11 ELSE 0 END, 2)
--    END AS TOTAL,
--    floor((JUMLAH_HARGA + biaya_tambahan) * rate) + CASE
--        WHEN PPN = 'S01' THEN floor(FLOOR((JUMLAH_HARGA + biaya_tambahan) * rate) * 0.11)
--        WHEN PPN = 'S03' THEN floor(FLOOR((JUMLAH_HARGA + biaya_tambahan) * rate) * 0.11)
--        WHEN PPN = 'S13' THEN floor(FLOOR((JUMLAH_HARGA + biaya_tambahan) * rate) * 0.11)
--        ELSE 0
--    END AS TOTAL_BC,
    PAYMENTCUSTOMERUNIQUEID,
    TAXTEMPLATECODE,
    PAYMENTCUSTOMERCODE
FROM
    (
        SELECT
            DISTINCT 
            PLANTINVOICE.COMPANYCODE,
            PLANTINVOICE.DIVISIONCODE,
            trim(PLANTINVOICE.CODE) AS Invoice,
            SALESDOCUMENT2.PROVISIONALCODE AS NO_SJ,
            SALESDOCUMENT2.PROVISIONALDOCUMENTDATE AS tgl_inv,
            SALESDOCUMENT2.GOODSISSUEDATE AS issue_date,
            CASE
                WHEN trim(SALESDOCUMENT2.PROVISIONALDOCUMENTDATE) <= DATE('2022-08-15') THEN CASE
                    WHEN trim(SALESDOCUMENT2.GOODSISSUEDATE) IS NOT NULL THEN trim(SALESDOCUMENT2.GOODSISSUEDATE)
                    ELSE trim(SALESDOCUMENT2.PROVISIONALDOCUMENTDATE)
                END
                ELSE trim(SALESDOCUMENT2.GOODSISSUEDATE)
            END AS tanggal_inv,
            PLANTINVOICE.CREATIONDATE AS tgl_create,
            CASE
                WHEN trim(SALESDOCUMENT2.PROVISIONALDOCUMENTDATE) <= DATE('2022-08-15') THEN CASE
                    WHEN trim(SALESDOCUMENT2.GOODSISSUEDATE) IS NOT NULL THEN SALESDOCUMENT2.GOODSISSUEDATE + PAYMENTMETHODIE.NOOFDAYS
                    ELSE SALESDOCUMENT2.PROVISIONALDOCUMENTDATE + PAYMENTMETHODIE.NOOFDAYS
                END
                ELSE SALESDOCUMENT2.GOODSISSUEDATE + PAYMENTMETHODIE.NOOFDAYS
            END AS DUE,
            PLANTINVOICE.CHALLANDATE AS DATEKB,
            PLANTINVOICE.LRDATE AS DUEKB,
            trim(PLANTINVOICE.ORDERCURRENCYCODE) AS curr,
            trim(SALESORDER.COUNTERCODE) AS JENIS_ORDER,
            trim(SALESORDER.FNCORDPRNCUSTOMERSUPPLIERCODE) AS kode_bep,
            SALESORDER.PAYMENTCUSTOMERUNIQUEID,
            SALESORDER.PAYMENTCUSTOMERCODE,
            BUSINESSPARTNER.NUMBERID AS id_bep,
            BUSINESSPARTNER.LEGALNAME1 AS nama_bep,
            CASE
                WHEN ADDRESS.CODE IS NULL THEN 'Warning! Kolom Address Code Sales Order Kosong. USER: ' || TRIM(SALESORDER.CREATIONUSER)
                ELSE ADDRESS.CODE
            END AS kode_cus,
            CASE
                WHEN trim(ADDRESS.ADDRESSEE) IS NULL THEN 'Warning! Kolom Address Code Sales Order Kosong. USER: ' || TRIM(SALESORDER.CREATIONUSER)
                ELSE trim(ADDRESS.ADDRESSEE)
            END AS nama_cus,
            CASE
                WHEN PLANTINVOICE.BLNUMBER IS NOT NULL THEN CASE
                    WHEN trim(ADDRESS.ADDRESSLINE4) IS NULL THEN 'Warning! Kolom Address Code Sales Order Kosong. USER: ' || TRIM(SALESORDER.CREATIONUSER)
                    ELSE trim(ADDRESS.ADDRESSLINE4)
                END
                ELSE CASE
                    WHEN trim(ADDRESS.ADDRESSLINE4) IS NULL THEN 'Warning! Kolom Address Code Sales Order Kosong. USER: ' || TRIM(SALESORDER.CREATIONUSER)
                    ELSE trim(ADDRESS.ADDRESSLINE4)
                END
            END AS NPWP,
            CASE
                WHEN PLANTINVOICE.BLNUMBER IS NULL THEN 'Warning! Kolom faktur pajak Invoice Kosong. USER : ' || TRIM(PLANTINVOICE.CREATIONUSER)
                ELSE PLANTINVOICE.BLNUMBER
            END AS FAKTUR_PAJAK,
            trim(PLANTINVOICE.CONTRACTNOCODE) AS NO_ORDER,
            REPLACE(ITXVIEW_PO_INVOICE.NO_PO, '''', ' ') AS NO_PO,
            PLANTINVOICE.STATUS AS NO_CI,
            CASE
                WHEN trim(SALESORDER.TEMPLATECODE) LIKE '%CWD%' THEN trim(SALESORDER.DESCRIPTION)
                ELSE '-'
            END AS DESC_KAIN,
            PLANTINVOICELINE.TAXTEMPLATECODE AS PPN,
            PLANTINVOICELINE.TAXTEMPLATECODE,
            trim(PAYMENTMETHOD.LONGDESCRIPTION) AS code_payment,
            trim(PAYMENTMETHODIE.NOOFDAYS) AS payment_terms,
            trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) AS unit,
            PLANTINVOICE.EXCHANGERATEOFCONTRACT AS rate,
            CASE
                WHEN (ITXVIEW_INVOICE_BIAYATAMBAHAN.biaya_tambahan) IS NULL THEN 0
                ELSE (ITXVIEW_INVOICE_BIAYATAMBAHAN.biaya_tambahan)
            END AS biaya_tambahan,
            round(SALESDOCUMENTLINE.price, 2) AS harga_satuan,
--            GRANDTOTAL.TOTAL_KG AS BERAT,
--            CASE
--                WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'kg' THEN GRANDTOTAL.TOTAL_YARD
--                WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'yd' THEN GRANDTOTAL.TOTAL_YARD
--                WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'm' THEN GRANDTOTAL.TOTAL_METER
--                WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) IN('un', 'Lot') THEN GRANDTOTAL.TOTAL_UNIT
--            END AS BERAT_LAIN,
--            CASE
--                WHEN trim(PLANTINVOICE.ORDERCURRENCYCODE) = 'USD' THEN CASE
--                    WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'kg' THEN GRANDTOTAL.TOTAL_JML_HARGA_KG
--                    WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'yd' THEN GRANDTOTAL.TOTAL_JML_HARGA_YD
--                    WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'm' THEN GRANDTOTAL.TOTAL_JML_HARGA_M
--                    WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) IN('un', 'Lot') THEN GRANDTOTAL.TOTAL_JML_HARGA_UN
--                END
--                WHEN trim(PLANTINVOICE.ORDERCURRENCYCODE) = 'IDR' THEN CASE
--                    WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'kg' THEN GRANDTOTAL.TOTAL_JML_HARGA_KG
--                    WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'yd' THEN GRANDTOTAL.TOTAL_JML_HARGA_YD
--                    WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) = 'm' THEN GRANDTOTAL.TOTAL_JML_HARGA_M
--                    WHEN trim(SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE) IN('un', 'Lot') THEN GRANDTOTAL.TOTAL_JML_HARGA_UN
--                END
--            END AS JUMLAH_HARGA,
            PLANTINVOICE.ORDERCURRENCYCODE
        FROM
            PLANTINVOICE PLANTINVOICE
        LEFT JOIN SALESORDER SALESORDER ON
            PLANTINVOICE.CONTRACTNOCODE = SALESORDER.CODE
            AND PLANTINVOICE.COMPANYCODE = SALESORDER.COMPANYCODE
            AND PLANTINVOICE.CONTRACTNOCOUNTERCODE = SALESORDER.COUNTERCODE
            AND PLANTINVOICE.DIVISIONCODE = SALESORDER.DIVISIONCODE
        LEFT JOIN SALESDOCUMENT SALESDOCUMENT ON
            PLANTINVOICE.CODE = SALESDOCUMENT.PROVISIONALCODE
            AND PLANTINVOICE.COMPANYCODE = SALESDOCUMENT.COMPANYCODE
            AND PLANTINVOICE.SALINVOICEPRVCOUNTERCODE = SALESDOCUMENT.PROVISIONALCOUNTERCODE
            AND PLANTINVOICE.DIVISIONCODE = SALESDOCUMENT.DIVISIONCODE
        LEFT JOIN PAYMENTMETHOD PAYMENTMETHOD ON
            PLANTINVOICE.TERMSOFPAYMENTCODE = PAYMENTMETHOD.CODE
            AND PLANTINVOICE.COMPANYCODE = PAYMENTMETHOD.COMPANYCODE
            AND PLANTINVOICE.DIVISIONCODE = PAYMENTMETHOD.DIVISIONCODE
        LEFT JOIN PAYMENTMETHODIE PAYMENTMETHODIE ON
            PLANTINVOICE.TERMSOFPAYMENTCODE = PAYMENTMETHODIE.CODE
            AND PLANTINVOICE.COMPANYCODE = PAYMENTMETHODIE.COMPANYCODE
        LEFT JOIN ADDRESS ADDRESS ON
            ADDRESS.UNIQUEID = SALESORDER.PAYMENTCUSTOMERUNIQUEID
            AND ADDRESS.CODE = SALESORDER.PAYMENTCUSTOMERCODE
        LEFT JOIN ORDERPARTNER ORDERPARTNER ON
            ORDERPARTNER.CUSTOMERSUPPLIERCODE = PLANTINVOICE.BUYERIFOTCCUSTOMERSUPPLIERCODE
            AND ORDERPARTNER.CUSTOMERSUPPLIERCOMPANYCODE = PLANTINVOICE.COMPANYCODE
        LEFT JOIN BUSINESSPARTNER BUSINESSPARTNER ON
            BUSINESSPARTNER.NUMBERID = ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID
        LEFT JOIN SALESDOCUMENTLINE SALESDOCUMENTLINE ON
            SALESDOCUMENTLINE.SALESDOCUMENTPROVISIONALCODE = SALESDOCUMENT.PROVISIONALCODE
            AND SALESDOCUMENTLINE.SALESDOCUMENTCOMPANYCODE = SALESDOCUMENT.COMPANYCODE
        LEFT JOIN PLANTINVOICELINE PLANTINVOICELINE ON
            PLANTINVOICELINE.PLANTINVOICECODE = SALESDOCUMENTLINE.SALESDOCUMENTPROVISIONALCODE
        LEFT JOIN SALESDOCUMENT SALESDOCUMENT2 ON
            SALESDOCUMENT2.PROVISIONALCODE = SALESDOCUMENTLINE.PREVIOUSCODE
            AND SALESDOCUMENT2.COMPANYCODE = SALESDOCUMENTLINE.SALESDOCUMENTCOMPANYCODE
        LEFT JOIN ITXVIEW_INVOICE_GRANDTOTAL3 GRANDTOTAL ON GRANDTOTAL.SALESDOCUMENTPROVISIONALCODE = SALESDOCUMENT2.PROVISIONALCODE
        LEFT JOIN ITXVIEW_INVOICE_BIAYATAMBAHAN ITXVIEW_INVOICE_BIAYATAMBAHAN ON
            PLANTINVOICE.CODE = ITXVIEW_INVOICE_BIAYATAMBAHAN.no_invoice
            AND PLANTINVOICE.COMPANYCODE = ITXVIEW_INVOICE_BIAYATAMBAHAN.COMPANYCODE
            AND PLANTINVOICE.DIVISIONCODE = ITXVIEW_INVOICE_BIAYATAMBAHAN.DIVISIONCODE
        LEFT JOIN ITXVIEW_PO_INVOICE ITXVIEW_PO_INVOICE ON
            PLANTINVOICE.CODE = ITXVIEW_PO_INVOICE.NO_INVOICE
            AND PLANTINVOICE.COMPANYCODE = ITXVIEW_PO_INVOICE.COMPANYCODE
            AND PLANTINVOICE.DIVISIONCODE = ITXVIEW_PO_INVOICE.DIVISIONCODE
		WHERE
			PLANTINVOICE.CODE = 'DM24040017'
        GROUP BY
            PLANTINVOICE.COMPANYCODE,
            PLANTINVOICE.DIVISIONCODE,
            PLANTINVOICE.CODE,
            SALESDOCUMENT2.PROVISIONALCODE,
            SALESDOCUMENT2.PROVISIONALDOCUMENTDATE,
            SALESDOCUMENT2.GOODSISSUEDATE,
            PLANTINVOICE.CHALLANDATE,
            PLANTINVOICE.LRDATE,
            PLANTINVOICE.STATUS,
            SALESORDER.CREATIONUSER,
            SALESORDER.PAYMENTCUSTOMERUNIQUEID,
            SALESORDER.PAYMENTCUSTOMERCODE,
            PLANTINVOICE.CREATIONUSER,
            SALESDOCUMENTLINE.PREVIOUSCODE,
            ITXVIEW_PO_INVOICE.NO_PO,
            SALESDOCUMENT.ORDERPARTNERBRANDCODE,
            SALESORDER.ORDERPARTNERBRANDCODE,
            PLANTINVOICE.CREATIONDATE,
            PAYMENTMETHOD.LONGDESCRIPTION,
            PAYMENTMETHODIE.NOOFDAYS,
            PLANTINVOICE.CONTRACTNOCODE,
            SALESORDER.FNCORDPRNCUSTOMERSUPPLIERCODE,
            ADDRESS.ADDRESSEE,
            ADDRESS.TAXREGISTRATIONNUMBER,
            ADDRESS.ADDRESSLINE4,
            PLANTINVOICE.ORDERCURRENCYCODE,
            PLANTINVOICE.EXCHANGERATEOFCONTRACT,
            ITXVIEW_INVOICE_BIAYATAMBAHAN.biaya_tambahan,
--            GRANDTOTAL.TOTAL_KG,
--            GRANDTOTAL.TOTAL_JML_HARGA_KG,
--            GRANDTOTAL.TOTAL_JML_HARGA_YD,
--            GRANDTOTAL.TOTAL_JML_HARGA_M,
--            GRANDTOTAL.TOTAL_JML_HARGA_UN,
--            GRANDTOTAL.TOTAL_YARD ,
--            GRANDTOTAL.TOTAL_METER ,
--            GRANDTOTAL.TOTAL_UNIT,
            SALESDOCUMENTLINE.PRICEUNITOFMEASURECODE,
            PLANTINVOICELINE.TAXTEMPLATECODE,
            PLANTINVOICE.BLNUMBER,
            PLANTINVOICE.ORDERCURRENCYCODE,
            SALESDOCUMENTLINE.price,
            SALESORDER.DESCRIPTION,
            SALESORDER.TEMPLATECODE,
            SALESORDER.COUNTERCODE,
            BUSINESSPARTNER.NUMBERID,
            BUSINESSPARTNER.LEGALNAME1,
            ADDRESS.CODE
    )
GROUP BY
    COMPANYCODE,
    DIVISIONCODE,
    Invoice,
    NO_SJ,
    tgl_inv,
    issue_date,
    tanggal_inv,
    tgl_create,
    jenis_order,
    kode_bep,
    due,
    DUEKB,
    DATEKB,
    nama_cus,
    NPWP,
    FAKTUR_PAJAK,
    NO_ORDER,
    NO_PO,
    NO_CI,
    code_payment,
    payment_terms,
    unit,
    biaya_tambahan,
--    JUMLAH_HARGA,
--    BERAT_LAIN,
--    BERAT,
    rate,
    curr,
    desc_kain,
    ppn,
    id_bep,
    nama_bep,
    kode_cus,
    PAYMENTCUSTOMERUNIQUEID,
    TAXTEMPLATECODE,
    PAYMENTCUSTOMERCODE;