DROP VIEW ITXVIEW_DEFECT_TYPE;
--CREATE VIEW ITXVIEW_DEFECT_TYPE AS
SELECT
	DISTINCT 
	SUBSTR(e.ELEMENTSINSPECTIONELEMENTCODE, 1,8) AS DEMANDNO,
	e.CODEEVENTCODE,
	i.LONGDESCRIPTION 
FROM
	ELEMENTSINSPECTIONEVENT e
LEFT JOIN INSPECTIONEVENTTEMPLATE i ON i.EVENTCODE = e.CODEEVENTCODE 
WHERE
	NOT e.CODEEVENTCODE = '001'
--	AND SUBSTR(e.ELEMENTSINSPECTIONELEMENTCODE, 1,8) = '00000505'