DROP VIEW ITXVIEW_POSISIKK_TGL_OUT_PRODORDER;
--CREATE VIEW ITXVIEW_POSISIKK_TGL_OUT_PRODORDER AS
SELECT 
	DISTINCT
	v.PRODUCTIONORDERCODE,
    p.PROPROGRESSPROGRESSNUMBER,
    p.DEMANDSTEPSTEPNUMBER,
    p2.PROGRESSTEMPLATECODE,
--    p2.PROGRESSENDDATE,
--    p2.PROGRESSENDTIME,
    (p2.PROGRESSENDDATE || ' ' || PROGRESSENDTIME) AS SELESAI,
	p2.MACHINECODE,
	r.LONGDESCRIPTION  
FROM PRODUCTIONDEMANDSTEP v 
LEFT JOIN PRODUCTIONPROGRESSSTEPUPDATED p ON p.DEMANDSTEPPRODUCTIONDEMANDCODE = v.PRODUCTIONDEMANDCODE 
RIGHT JOIN PRODUCTIONPROGRESS p2 ON p2.PROGRESSNUMBER = p.PROPROGRESSPROGRESSNUMBER AND p2.PROGRESSTEMPLATECODE = 'E01'
LEFT JOIN RESOURCES r ON r.CODE = p2.OPERATORCODE
WHERE 
	p2.INACTIVE = 1
--AND v.PRODUCTIONORDERCODE  = '00083822' 
--		AND p.DEMANDSTEPSTEPNUMBER = '600'