-- DB2ADMIN.ITXVIEWJENISBENANGBONORDERMAINPRO source

CREATE VIEW ITXVIEWJENISBENANGBONORDERMAINPRO AS 
SELECT
    i.CODE,
    i.ORIGDLVSALORDLINESALORDERCODE,
    i.ORIGDLVSALORDERLINEORDERLINE,
    i.PRO1,
    i.SUBCODE01,
    i.SUBCODE02,
    i.SUBCODE03,
    i.SUBCODE04,
    i1.SUMMARIZEDDESCRIPTION,
    i1.COMMENTTEXT
FROM
    ITXVIEWPROJECTBONORDER i
LEFT JOIN ITXVIEWJENISBENANGRMP i1 ON
    i1.ORIGDLVSALORDLINESALORDERCODE = i.ORIGDLVSALORDLINESALORDERCODE
    AND i1.ORIGDLVSALORDERLINEORDERLINE = i.ORIGDLVSALORDERLINEORDERLINE
    AND i1.SUBCODE01 = i.SUBCODE01
    AND i1.SUBCODE02 = i.SUBCODE02
    AND i1.SUBCODE03 = i.SUBCODE03
GROUP BY
    i.CODE,
    i.ORIGDLVSALORDLINESALORDERCODE,
    i.ORIGDLVSALORDERLINEORDERLINE,
    i.PRO1,
    i.SUBCODE01,
    i.SUBCODE02,
    i.SUBCODE03,
    i.SUBCODE04,
    i1.SUMMARIZEDDESCRIPTION,
    i1.COMMENTTEXT;