-- DB2ADMIN.ITXVIEWKK source
DROP VIEW ITXVIEWKK;
--CREATE VIEW ITXVIEWKK AS
SELECT
    DISTINCT
    PRODUCTIONDEMAND.COMPANYCODE,
    PRODUCTIONDEMAND.CODE AS DEAMAND,
    PRODUCTIONDEMAND.TEMPLATECODE,
    PRODUCTIONDEMAND.ORDERDATE,
    SALESORDERDELIVERY.DELIVERYDATE,
    PRODUCTIONDEMAND.FINALPLANNEDDATE,
    PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE AS PROJECTCODE,
    dept.LONGDESCRIPTION || a10.VALUESTRING AS DESC_DEMAND,
    PRODUCTIONDEMAND.INTERNALREFERENCE AS DESC_DEMAND_KK,
    PRODUCTIONDEMAND.ITEMTYPEAFICODE AS ITEMTYPEAFICODE_YND,
    PRODUCTIONDEMAND.ABSUNIQUEID AS ABSUNIQUEID_DEMAND,
    TRIM(SALESORDERLINE.SUBCODE01) AS DSUBCODE01,
    TRIM(SALESORDERLINE.SUBCODE02) AS DSUBCODE02,
    TRIM(SALESORDERLINE.SUBCODE03) AS DSUBCODE03,
    TRIM(SALESORDERLINE.SUBCODE04) AS DSUBCODE04,
    TRIM(SALESORDERLINE.SUBCODE05) AS DSUBCODE05,
    TRIM(SALESORDERLINE.SUBCODE06) AS DSUBCODE06,
    TRIM(SALESORDERLINE.SUBCODE07) AS DSUBCODE07,
    TRIM(SALESORDERLINE.SUBCODE08) AS DSUBCODE08,
    TRIM(SALESORDERLINE.SUBCODE09) AS DSUBCODE09,
    TRIM(SALESORDERLINE.SUBCODE10) AS DSUBCODE10,   
    PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE,
    PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE,
    PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE,
    SALESORDER.CODE AS BONORDER,
    SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE,
    SALESORDER.DESCRIPTION,
    SALESORDER.REQUIREDDUEDATE,
    SALESORDER.ABSUNIQUEID AS ABSUNIQUEID_SALESORDER,
    CASE
        WHEN SALESORDER.DELIVERYPOINTCODE IS NOT NULL THEN 
        	TRIM(a.ADDRESSLINE1) || ', ' || 
        	CASE
        		WHEN TRIM(a.ADDRESSLINE2) IS NULL THEN '-' ELSE TRIM(a.ADDRESSLINE2)
        	END	|| ', ' || 
        	CASE
        		WHEN TRIM(a.ADDRESSLINE3) IS NULL THEN '-' ELSE TRIM(a.ADDRESSLINE3)
        	END	|| ', ' || 
        	CASE
        		WHEN TRIM(a.ADDRESSLINE4) IS NULL THEN '-' ELSE TRIM(a.ADDRESSLINE4)
        	END        	
        ELSE BUSINESSPARTNER.ADDRESSLINE1
    END AS ADDRESSLINE1,
    CASE
        WHEN TRIM(o.EXTERNALITEMCODE) IS NULL THEN '-'
        ELSE TRIM(o.EXTERNALITEMCODE)
    END AS EXTERNALITEM,    
    PRODUCTIONDEMAND.ITEMTYPEAFICODE,
    PRODUCTIONDEMAND.SUBCODE01,
    PRODUCTIONDEMAND.SUBCODE02,
    PRODUCTIONDEMAND.SUBCODE03,
    PRODUCTIONDEMAND.SUBCODE04,
    PRODUCTIONDEMAND.SUBCODE05,
    PRODUCTIONDEMAND.SUBCODE06,
    PRODUCTIONDEMAND.SUBCODE07,
    PRODUCTIONDEMAND.SUBCODE08,
    PRODUCTIONDEMAND.SUBCODE09,
    PRODUCTIONDEMAND.SUBCODE10,
    i.WARNA,
    CASE
        WHEN PRODUCT.LONGDESCRIPTION IS NULL THEN SALESORDERLINE.ITEMDESCRIPTION
        ELSE PRODUCT.LONGDESCRIPTION
    END ||' ' || 
    CASE 
    	WHEN TRIM(SALESORDER.INTERNALREFERENCE) IS NULL THEN '-'
    	ELSE TRIM(SALESORDER.INTERNALREFERENCE)
    END AS ITEMDESCRIPTION,
    SALESORDERLINE.USERSECONDARYUOMCODE,
    SALESORDERLINE.PRICEUNITOFMEASURECODE,
    SALESORDERLINE.ABSUNIQUEID AS ABSUNIQUEID_SALESORDERLINE,
    SALESORDERLINE.ORDERLINE,
    PRODUCTIONORDER.CREATIONDATETIME,
    PRODUCTIONORDER.PROGRESSSTATUS,
    'KGF' AS KGF,
    a2.VALUESTRING AS ADDITIONALDATA,
    a3.VALUESTRING AS ADDITIONALDATA2,
    a4.VALUESTRING AS ADDITIONALDATA3,
    a5.VALUESTRING AS ADDITIONALDATA4,
    a6.VALUESTRING AS ADDITIONALDATA5,
    a7.VALUESTRING AS OriginalPdCode,
    SALESORDER.CREATIONDATETIME AS CREATIONDATETIME_SALESORDER,
    CASE
        WHEN a8.VALUESTRING IS NOT NULL THEN 'KK TAS'
        ELSE a8.VALUESTRING
    END AS KARTUKERJA
FROM
    PRODUCTIONDEMAND PRODUCTIONDEMAND
LEFT JOIN (
    SELECT
        DISTINCT PRODUCTIONDEMANDCODE,
        PRODUCTIONORDERCODE
    FROM
        PRODUCTIONDEMANDSTEP PRODUCTIONDEMANDSTEP) PRODUCTIONDEMANDSTEP ON
    PRODUCTIONDEMAND.CODE = PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE
LEFT JOIN SALESORDER SALESORDER ON
    PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE = SALESORDER.CODE
LEFT JOIN ORDERPARTNER ORDERPARTNER ON
    PRODUCTIONDEMAND.CUSTOMERCODE = ORDERPARTNER.CUSTOMERSUPPLIERCODE
LEFT JOIN BUSINESSPARTNER BUSINESSPARTNER ON
    BUSINESSPARTNER.NUMBERID = ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID
LEFT JOIN ADDRESS a ON
    a.CODE = SALESORDER.DELIVERYPOINTCODE
    AND a.UNIQUEID = SALESORDER.DELIVERYPOINTUNIQUEID
LEFT JOIN SALESORDERLINE SALESORDERLINE ON
    SALESORDERLINE.SALESORDERCODE = SALESORDER.CODE
    AND SALESORDERLINE.ORDERLINE = PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE
LEFT JOIN SALESORDERDELIVERY SALESORDERDELIVERY ON
    SALESORDERDELIVERY.SALESORDERLINESALESORDERCODE = PRODUCTIONDEMAND.DLVSALORDERLINESALESORDERCODE
    AND SALESORDERDELIVERY.SALESORDERLINEORDERLINE = PRODUCTIONDEMAND.DLVSALESORDERLINEORDERLINE
RIGHT JOIN PRODUCTIONORDER PRODUCTIONORDER ON
    PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE = PRODUCTIONORDER.CODE
LEFT JOIN PRODUCT PRODUCT ON
    PRODUCT.ITEMTYPECODE = PRODUCTIONDEMAND.ITEMTYPEAFICODE
    AND PRODUCT.SUBCODE01 = PRODUCTIONDEMAND.SUBCODE01
    AND PRODUCT.SUBCODE02 = PRODUCTIONDEMAND.SUBCODE02
    AND PRODUCT.SUBCODE03 = PRODUCTIONDEMAND.SUBCODE03
    AND PRODUCT.SUBCODE04 = PRODUCTIONDEMAND.SUBCODE04
    AND PRODUCT.SUBCODE05 = PRODUCTIONDEMAND.SUBCODE05
    AND PRODUCT.SUBCODE06 = PRODUCTIONDEMAND.SUBCODE06
    AND PRODUCT.SUBCODE07 = PRODUCTIONDEMAND.SUBCODE07
    AND PRODUCT.SUBCODE08 = PRODUCTIONDEMAND.SUBCODE08
    AND PRODUCT.SUBCODE09 = PRODUCTIONDEMAND.SUBCODE09
    AND PRODUCT.SUBCODE10 = PRODUCTIONDEMAND.SUBCODE10
LEFT JOIN ITXVIEWCOLOR i ON
    i.ITEMTYPECODE = PRODUCTIONDEMAND.ITEMTYPEAFICODE
    AND i.SUBCODE01 = PRODUCTIONDEMAND.SUBCODE01
    AND i.SUBCODE02 = PRODUCTIONDEMAND.SUBCODE02
    AND i.SUBCODE03 = PRODUCTIONDEMAND.SUBCODE03
    AND i.SUBCODE04 = PRODUCTIONDEMAND.SUBCODE04
    AND i.SUBCODE05 = PRODUCTIONDEMAND.SUBCODE05
    AND i.SUBCODE06 = PRODUCTIONDEMAND.SUBCODE06
    AND i.SUBCODE07 = PRODUCTIONDEMAND.SUBCODE07
    AND i.SUBCODE08 = PRODUCTIONDEMAND.SUBCODE08
    AND i.SUBCODE09 = PRODUCTIONDEMAND.SUBCODE09
    AND i.SUBCODE10 = PRODUCTIONDEMAND.SUBCODE10
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a2.FIELDNAME = 'ProAllow'
LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a3.FIELDNAME = 'ProAllow2'
LEFT JOIN ADSTORAGE a4 ON a4.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a4.FIELDNAME = 'ProAllow3'
LEFT JOIN ADSTORAGE a5 ON a5.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a5.FIELDNAME = 'ProAllow4'
LEFT JOIN ADSTORAGE a6 ON a6.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a6.FIELDNAME = 'ProAllow5'
LEFT JOIN ADSTORAGE a7 ON a7.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a7.FIELDNAME = 'OriginalPDCode'
LEFT JOIN ADSTORAGE a8 ON a8.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a8.FIELDNAME = 'NoTrackingDev'
LEFT JOIN ADSTORAGE a9 ON a9.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a9.FIELDNAME = 'BagianCode'
LEFT JOIN DEPARTMENT dept ON dept.CODE = a9.VALUESTRING
LEFT JOIN ADSTORAGE a10 ON a10.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a10.FIELDNAME = 'DefectNote'
LEFT JOIN ORDERITEMORDERPARTNERLINK o ON o.ORDPRNCUSTOMERSUPPLIERCODE = SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE
    AND o.ITEMTYPEAFICODE = PRODUCTIONDEMAND.ITEMTYPEAFICODE
    AND o.SUBCODE01 = PRODUCTIONDEMAND.SUBCODE01
    AND o.SUBCODE02 = PRODUCTIONDEMAND.SUBCODE02
    AND o.SUBCODE03 = PRODUCTIONDEMAND.SUBCODE03
    AND o.SUBCODE04 = PRODUCTIONDEMAND.SUBCODE04
    AND o.SUBCODE05 = PRODUCTIONDEMAND.SUBCODE05
    AND o.SUBCODE06 = PRODUCTIONDEMAND.SUBCODE06
    AND o.SUBCODE07 = PRODUCTIONDEMAND.SUBCODE07
    AND o.SUBCODE08 = PRODUCTIONDEMAND.SUBCODE08
    AND o.SUBCODE09 = PRODUCTIONDEMAND.SUBCODE09
    AND o.SUBCODE10 = PRODUCTIONDEMAND.SUBCODE10;