DROP VIEW ITXVIEWPROJECTBONORDER3;
--CREATE VIEW ITXVIEWPROJECTBONORDER3 AS 
SELECT 	
	i.CODE,
	i.ORIGDLVSALORDLINESALORDERCODE,
	i.PRO2,
	i.SUBCODE01,
	i.SUBCODE02,
	i.SUBCODE03,
	i.SUBCODE04,
	i1.SUMMARIZEDDESCRIPTION,
	i1.COMMENTTEXT
FROM ITXVIEWPROJECTBONORDER i 
LEFT JOIN ITXVIEWJENISBENANGRMP i1 ON i1.ORIGDLVSALORDLINESALORDERCODE = i.PRO2
WHERE 
	i.PRO2 IS NOT NULL
--AND i.ORIGDLVSALORDLINESALORDERCODE = 'DOM2300065' 
--AND i.SUBCODE01 = 'T' 
--AND i.SUBCODE02 = 'DKF' 
--AND i.SUBCODE03 = '22035' 
--AND i.SUBCODE04 = 'D01'
GROUP BY 
	i.CODE,
	i.ORIGDLVSALORDLINESALORDERCODE,
	i.PRO2,
	i.SUBCODE01,
	i.SUBCODE02,
	i.SUBCODE03,
	i.SUBCODE04,
	i1.SUMMARIZEDDESCRIPTION,
	i1.COMMENTTEXT