DROP VIEW ITXVIEW_MACHINE;
--CREATE VIEW ITXVIEW_MACHINE AS
SELECT
    p.PRODUCTIONORDERCODE,
    p.PROGRESSTEMPLATECODE,
    p.OPERATIONCODE,
    p.MACHINECODE,
    p.OPERATORCODE,
    r2.LONGDESCRIPTION AS NAMA_MESIN,
    r.LONGDESCRIPTION AS NAMA_OPERATOR,
    r2.BATHVOLUME,
    p.PROGRESSSTARTPROCESSDATE,
    p.PROGRESSSTARTPROCESSTIME,
    p.PROGRESSENDDATE,
    p.PROGRESSENDTIME,
    v.FINALUSERPRIMARYQUANTITY
FROM
    PRODUCTIONPROGRESS p
LEFT JOIN RESOURCES r ON r.CODE = p.OPERATIONCODE  
LEFT JOIN RESOURCES r2 ON r2.CODE = p.MACHINECODE
LEFT JOIN VIEWPRODUCTIONDEMANDSTEP v ON v.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE 
WHERE
    p.OPERATIONCODE IN ('DYE1', 'DYE2', 'DYE3', 'DYE4', 'DYE5', 'DYE6', 'DYE7', 'DYE8')
GROUP BY 
	p.PRODUCTIONORDERCODE,
    p.PROGRESSTEMPLATECODE,
    p.OPERATIONCODE,
    p.MACHINECODE,
    p.OPERATORCODE,
    r2.LONGDESCRIPTION,
    r.LONGDESCRIPTION,
    r2.BATHVOLUME,
    p.PROGRESSSTARTPROCESSDATE,
    p.PROGRESSSTARTPROCESSTIME,
    p.PROGRESSENDDATE,
    p.PROGRESSENDTIME,
    v.FINALUSERPRIMARYQUANTITY