DROP VIEW ITXVIEWINSPECTPACKING;
--CREATE VIEW ITXVIEWINSPECTPACKING AS
SELECT
--	DISTINCT 
	ELEMENTSINSPECTION.ABSUNIQUEID,
	SUBSTR(ELEMENTSINSPECTION.INSPECTIONSTARTDATETIME, 1,10) AS INSPECTIONSTARTDATETIME,
	i.LONGDESCRIPTION AS OPERATOR,
	ADSTORAGE.VALUESTRING AS NOMESIN,
	ELEMENTSINSPECTION.QUALITYREASONCODE,
	ADSTORAGE2.VALUEDECIMAL AS GRM,
	TRIM(PRODUCTIONDEMAND.SUBCODE02) || '-' || TRIM(PRODUCTIONDEMAND.SUBCODE03) AS NO_HANGER,
	TRIM(PRODUCTIONDEMAND.SUBCODE04) AS LD,
    ELEMENTSINSPECTION.ELEMENTCODE AS ELEMENTSINSPECTIONELEMENTCODE,
    ELEMENTSINSPECTION.LENGTHUOMCODE,
    ELEMENTSINSPECTIONEVENT.ELEMENTSINSINSPECTIONINDEX,
    A.VALUEDECIMAL,
    ELEMENTSINSPECTION.LENGTHGROSS,
    ELEMENTSINSPECTION.WEIGHTNET,
    ELEMENTSINSPECTION.WIDTHNET,
    ELEMENTSINSPECTION.QUALITYCODE,
    CASE
    	WHEN ELEMENTSINSPECTION.QUALITYCODE = 1 THEN 'A'
    	WHEN ELEMENTSINSPECTION.QUALITYCODE = 2 THEN 'B'
    	WHEN ELEMENTSINSPECTION.QUALITYCODE = 3 THEN 'C'
    	ELSE '-'
    END AS GRADE_QUALITYCODE,
    LISTAGG(CONCAT(CONCAT(ELEMENTSINSPECTIONEVENT."SEQUENCE", ':'), ELEMENTSINSPECTIONEVENT.CODEEVENTCODE), ',' ) WITHIN GROUP(ORDER BY ELEMENTSINSPECTIONEVENT."SEQUENCE" ASC) AS DEFECT,
    LISTAGG(CONCAT(CONCAT(ELEMENTSINSPECTIONEVENT."SEQUENCE", ':'), ELEMENTSINSPECTIONEVENT.STARTPOSITION), ',' ) WITHIN GROUP(ORDER BY ELEMENTSINSPECTIONEVENT."SEQUENCE" ASC) AS POSITIONL,
    LISTAGG(CONCAT(CONCAT(ELEMENTSINSPECTIONEVENT."SEQUENCE", ':'), ELEMENTSINSPECTIONEVENT.WIDTHPOSITION), ',' ) WITHIN GROUP(ORDER BY ELEMENTSINSPECTIONEVENT."SEQUENCE" ASC) AS POSITIONW,
    LISTAGG(CONCAT(CONCAT(ELEMENTSINSPECTIONEVENT."SEQUENCE", ':'), ELEMENTSINSPECTIONEVENT.POINTS), ',' ) WITHIN GROUP(ORDER BY ELEMENTSINSPECTIONEVENT."SEQUENCE" ASC) AS POINT, 
    SUM(ELEMENTSINSPECTIONEVENT.CREDITS) AS CREDIT
FROM
    ELEMENTSINSPECTIONEVENT ELEMENTSINSPECTIONEVENT
RIGHT JOIN ELEMENTSINSPECTION ON ELEMENTSINSPECTIONEVENT.ELEMENTSINSPECTIONELEMENTCODE = ELEMENTSINSPECTION.ELEMENTCODE
LEFT JOIN ELEMENTS ON ELEMENTSINSPECTION.ELEMENTCODE = ELEMENTS.CODE
LEFT JOIN (
        SELECT
            ADSTORAGE.UNIQUEID,
            ADSTORAGE.VALUEDECIMAL
        FROM
            ADSTORAGE ADSTORAGE
        WHERE
            ADSTORAGE.NAMENAME = 'CalculatedLength'
	    ) A ON ELEMENTSINSPECTION.ABSUNIQUEID = A.UNIQUEID
LEFT JOIN INITIALS i ON i.CODE =  ELEMENTSINSPECTION.OPERATORCODE 
LEFT JOIN PRODUCTIONDEMAND PRODUCTIONDEMAND ON PRODUCTIONDEMAND.CODE = SUBSTR(ELEMENTSINSPECTION.ELEMENTCODE, 1,8)
LEFT JOIN ADSTORAGE ADSTORAGE ON ADSTORAGE.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND ADSTORAGE.FIELDNAME = 'MachineNoCode'
LEFT JOIN ADSTORAGE ADSTORAGE2 ON ADSTORAGE2.UNIQUEID = ELEMENTSINSPECTION.ABSUNIQUEID AND ADSTORAGE2.FIELDNAME = 'GSM'
WHERE 
	ELEMENTSINSPECTION.ELEMENTCODE = '00252686003'
--	AND	ELEMENTSINSPECTIONEVENT.ELEMENTSINSINSPECTIONINDEX = '0'
GROUP BY
	ELEMENTSINSPECTION.ABSUNIQUEID,
	ELEMENTSINSPECTION.INSPECTIONSTARTDATETIME,
	i.LONGDESCRIPTION,
	ADSTORAGE.VALUESTRING,
	ADSTORAGE2.VALUEDECIMAL,
	ELEMENTSINSPECTION.QUALITYREASONCODE,
	PRODUCTIONDEMAND.SUBCODE02,
	PRODUCTIONDEMAND.SUBCODE03,
	PRODUCTIONDEMAND.SUBCODE04,
--    ELEMENTSINSPECTIONEVENT.ELEMENTSINSPECTIONELEMENTCODE,
	ELEMENTSINSPECTION.ELEMENTCODE,
	ELEMENTSINSPECTION.LENGTHUOMCODE,
    ELEMENTSINSPECTIONEVENT.ELEMENTSINSINSPECTIONINDEX,
    A.VALUEDECIMAL,
    ELEMENTSINSPECTION.LENGTHGROSS,
    ELEMENTSINSPECTION.WEIGHTNET,
    ELEMENTSINSPECTION.WIDTHNET,
    ELEMENTSINSPECTION.QUALITYCODE