DROP VIEW ITXVIEWGRAMASI;
--CREATE VIEW ITXVIEWGRAMASI AS
SELECT 
	s.SALESORDERCODE,
	s.ORDERLINE,
	REGEXP_SUBSTR(s.SUBCODE04, '([^-]*)-?', 1, 2, '', 1) AS GRAMASI_FKF,
    a.VALUEDECIMAL AS GRAMASI_KFF
FROM 
	SALESORDERLINE s 
LEFT JOIN PRODUCT p ON p.SUBCODE01 = s.SUBCODE01
			    AND p.SUBCODE02 = s.SUBCODE02
			    AND p.SUBCODE03 = s.SUBCODE03
			    AND p.SUBCODE04 = s.SUBCODE04
			    AND p.SUBCODE05 = s.SUBCODE05
			    AND p.SUBCODE06 = s.SUBCODE06
			    AND p.SUBCODE07 = s.SUBCODE07
			    AND p.SUBCODE08 = s.SUBCODE08
			    AND p.SUBCODE09 = s.SUBCODE09
			    AND p.SUBCODE10 = s.SUBCODE10
			    AND p.ITEMTYPECODE = s.ITEMTYPEAFICODE
			    AND p.ITEMTYPECODE = 'KFF'
LEFT JOIN ADSTORAGE a  ON a.UNIQUEID = p.ABSUNIQUEID AND a.NAMENAME = 'GSM'
--WHERE s.SALESORDERCODE = 'OPN2200395' AND s.ORDERLINE = 20