DROP VIEW ITXVIEW_PERSEDIAANKAINJADI_XLS;
--CREATE VIEW ITXVIEW_PERSEDIAANKAINJADI_XLS AS 
SELECT * FROM (SELECT
	BALANCE.NUMBERID,
	BALANCE.ITEMTYPECODE,
	BALANCE.DECOSUBCODE01,
	BALANCE.DECOSUBCODE02,
	BALANCE.DECOSUBCODE03,
	BALANCE.DECOSUBCODE04,
	BALANCE.DECOSUBCODE05,
	BALANCE.DECOSUBCODE06,
	BALANCE.DECOSUBCODE07,
	BALANCE.DECOSUBCODE08,
	BALANCE.DECOSUBCODE09,
	BALANCE.DECOSUBCODE10,
	BALANCE.WHSLOCATIONWAREHOUSEZONECODE,
	BALANCE.WAREHOUSELOCATIONCODE,
	BALANCE.QUALITYLEVELCODE,
	BALANCE.LOTCODE,
	BALANCE.ELEMENTSCODE,
	BALANCE.PROJECTCODE,
	BALANCE.BASEPRIMARYQUANTITYUNIT,
	BALANCE.BASESECONDARYUNITCODE,
	BALANCE.BASESECONDARYQUANTITYUNIT,
	BALANCE.CREATIONDATETIME,
	SALESORDER.CODE,
	SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE,
	SALESORDER.EXTERNALREFERENCE,
	SALESORDER.CONFIRMEDDUEDATE,
	ELEMENTS.ENTRYDOCUMENTNUMBER,
	PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE,
	PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE,
	SALESORDERDELIVERY.CONFIRMEDDELIVERYDATE,
	ITXVIEWMUTASIQCF_GKJ.TRANSACTIONDATE,
	ITXVIEWKK.EXTERNALITEM,
	ITXVIEWKK.ITEMDESCRIPTION
FROM
	BALANCE BALANCE
LEFT JOIN SALESORDER SALESORDER ON BALANCE.PROJECTCODE = SALESORDER.CODE AND BALANCE.COMPANYCODE = SALESORDER.COMPANYCODE
LEFT JOIN ELEMENTS ELEMENTS ON BALANCE.ELEMENTSCODE = ELEMENTS.CODE AND BALANCE.COMPANYCODE = ELEMENTS.COMPANYCODE
LEFT JOIN PRODUCTIONDEMAND PRODUCTIONDEMAND ON ELEMENTS.ENTRYDOCUMENTNUMBER = PRODUCTIONDEMAND.CODE AND ELEMENTS.COMPANYCODE = PRODUCTIONDEMAND.COMPANYCODE
LEFT JOIN SALESORDERDELIVERY SALESORDERDELIVERY ON PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE = SALESORDERDELIVERY.SALESORDERLINESALESORDERCODE AND PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE = SALESORDERDELIVERY.SALESORDERLINEORDERLINE
LEFT JOIN ITXVIEWMUTASIQCF_GKJ ITXVIEWMUTASIQCF_GKJ ON BALANCE.ELEMENTSCODE = ITXVIEWMUTASIQCF_GKJ.ITEMELEMENTCODE AND BALANCE.COMPANYCODE = ITXVIEWMUTASIQCF_GKJ.COMPANYCODE
LEFT JOIN ITXVIEWKK ITXVIEWKK ON  ITXVIEWKK.PROJECTCODE = BALANCE.PROJECTCODE AND BALANCE.LOTCODE = ITXVIEWKK.PRODUCTIONORDERCODE
--	CASE
--		WHEN ELEMENTS.ENTRYDOCUMENTNUMBER IS NULL OR ELEMENTS.ENTRYDOCUMENTNUMBER = '' THEN 
--		ELSE ELEMENTS.ENTRYDOCUMENTNUMBER = ITXVIEWKK.DEAMAND
--	END	
WHERE
	BALANCE.PROJECTCODE = 'SAM2400269'
ORDER BY
	BALANCE.ELEMENTSCODE)