DROP VIEW ITXVIEW_SHIPPING_MARK;
--CREATE VIEW ITXVIEW_SHIPPING_MARK AS 
SELECT
    DISTINCT 
	s.CODE,
    TRIM(s.DELIVERYPOINTCODE) AS DELIVERYPOINTCODE,
    LISTAGG(
        DISTINCT(
            TRIM(s2.EXTERNALREFERENCE)
        ),
        ', '
    ) AS SP#,
    LISTAGG(
        DISTINCT(
            TRIM(s2.INTERNALREFERENCE)
        ),
        ', '
    ) AS ST#,
    a.UNIQUEID,
    a.VALUESTRING AS KODE_SM,
    a2.VALUESTRING AS PIC,
    a3.VALUESTRING AS ext
FROM
    SALESORDER s
LEFT JOIN ADSTORAGE a ON s.ABSUNIQUEID = a.UNIQUEID AND a.FIELDNAME = 'KodeSM'
LEFT JOIN ADSTORAGE a2 ON s.ABSUNIQUEID = a2.UNIQUEID AND a2.FIELDNAME = 'PICEXT'
LEFT JOIN ADSTORAGE a3 ON s.ABSUNIQUEID = a3.UNIQUEID AND a3.FIELDNAME = 'EXT'
LEFT JOIN SALESORDERLINE s2 ON s.CODE = s2.SALESORDERCODE
        WHERE
--        a.UNIQUEID IS NOT NULL
        s.CODE ='EXP2400071'
GROUP BY
    s.CODE,
    s.DELIVERYPOINTCODE,
    a.UNIQUEID,
    a.VALUESTRING,
    a2.VALUESTRING,
    a3.VALUESTRING;