DROP VIEW ITXVIEW_DESIGN_SCREENS;
CREATE VIEW ITXVIEW_DESIGN_SCREENS AS
SELECT
    DISTINCT 
    r.NUMBERID,
--    r.SUBCODE01,
	d3.DESIGNSUBCODE01,
    d3.DESIGNCOMPONENTVARIANTCODE,
    t.LONGDESCRIPTION AS MESH,
    r.LONGDESCRIPTION AS RECIPEDESCRIPTION
FROM
    DESIGN d
LEFT JOIN DESIGNCOMPONENT d2 ON d2.DESIGNNUMBERID = d.NUMBERID
LEFT JOIN DESIGNSCREENS d3 ON  d3.DESIGNCOMPONENTDESIGNNUMBERID = d2.DESIGNNUMBERID AND d3.DESIGNSUBCODE01 = d2.DESIGNSUBCODE01
LEFT JOIN RECIPE r ON r.SUBCODE01 = d3.RECIPEDESCRIPTION
LEFT JOIN TOOL t ON t.SUBCODE01 = SUBSTR(r.SUBCODE01, 1, 5) || '/' ||SUBSTR(r.SUBCODE01, 12)
--WHERE 
--	d3.DESIGNSUBCODE01 = 'R1173' AND d3.DESIGNCOMPONENTVARIANTCODE = 'PI0F'
--ORDER BY
--	r.NUMBERID ASC