--DROP VIEW ITXVIEWNILO;
--CREATE VIEW ITXVIEWNILO AS
SELECT *
	FROM 
	(SELECT 
		CASE  
			WHEN (IDS = '2 ,0' OR
					IDS = '0 ,2' OR 
					IDS = '2 ,2' OR
					IDS = '2 ,3' OR
					IDS = '3 ,2' OR
					IDS = '2 ,0 ,0' OR 
					IDS = '2 ,2 ,0' OR
					IDS = '2 ,2 ,3' OR 
					IDS = '0 ,0 ,2' OR
					IDS = '0 ,2 ,0' OR
					IDS = '0 ,2 ,2' OR
					IDS = '0 ,2 ,0 ,0' OR
					IDS = '2 ,2 ,0 ,0' OR
					IDS = '2 ,2 ,0 ,2' OR 
					IDS = '3 ,2 ,0 ,2' OR 
					IDS = '2 ,3 ,0 ,3' OR
					IDS = '2 ,2 ,3 ,0 ,2' OR 
					AD7.VALUESTRING = '1') AND STSMC.STEPNUMBER IS NULL THEN 1
			WHEN STSMC.STEPNUMBER >= 2 AND STSMC.STEPNUMBER <= 7  THEN 2
			WHEN STSMC.STEPNUMBER = 1 THEN 4
			ELSE 3
		END AS URUT,
		STSMC1.IDS,
		PRODUCTIONDEMAND.CODE,
		PRODUCTIONDEMAND.PROGRESSSTATUS,
		SCHEDULESOFSTEPSPLITS.SCHEDULEDRESOURCECODE,
		STSMC.STEPNUMBER,
		STSMC.LONGDESCRIPTION,
		STSMC.PLANNEDOPERATIONCODE,
		CASE  
			WHEN AD3.VALUESTRING = 0 OR AD3.VALUESTRING IS NULL  THEN 'Normal'
			WHEN AD3.VALUESTRING = 1  THEN 'Urgent'
		END AS STSDEMAND, 
		AD8.VALUEDATE AS RMPREQDATETO,
		AD4.VALUEDECIMAL AS QTYSALIN,
		AD5.VALUEDECIMAL AS QTYOPIN,
		AD6.VALUEDECIMAL AS QTYOPOUT,
		AD7.VALUESTRING AS STSOPR,
		PM.JML
	FROM 
		PRODUCTIONDEMAND 
	LEFT JOIN SCHEDULESOFSTEPSPLITS SCHEDULESOFSTEPSPLITS ON PRODUCTIONDEMAND.CODE = SCHEDULESOFSTEPSPLITS.CODE
	LEFT JOIN ADSTORAGE ON ADSTORAGE.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND ADSTORAGE.NAMENAME ='MachineNo'
	LEFT JOIN ADSTORAGE AD1 ON AD1.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD1.NAMENAME ='TglRencana'
	LEFT JOIN ADSTORAGE AD2 ON AD2.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD2.NAMENAME ='RMPReqDate' 
	LEFT JOIN ADSTORAGE AD3 ON AD3.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD3.NAMENAME ='StatusDemand'
	LEFT JOIN ADSTORAGE AD4 ON AD4.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD4.NAMENAME ='QtySalin'
	LEFT JOIN ADSTORAGE AD5 ON AD5.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD5.NAMENAME ='QtyOperIn'
	LEFT JOIN ADSTORAGE AD6 ON AD6.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD6.NAMENAME ='QtyOperOut'
	LEFT JOIN ADSTORAGE AD7 ON AD7.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD7.NAMENAME ='StatusOper'
	LEFT JOIN ADSTORAGE AD8 ON AD8.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD8.NAMENAME ='RMPGreigeReqDateTo'
	LEFT JOIN 
		(SELECT 
			STEPNUMBER,
			PLANNEDOPERATIONCODE,
			PROGRESSSTATUS,
			LONGDESCRIPTION,
			PRODUCTIONDEMANDCODE
		FROM 
			PRODUCTIONDEMANDSTEP 
		WHERE 
			PROGRESSSTATUS ='2' AND NOT (PLANNEDOPERATIONCODE='KNT1' OR PLANNEDOPERATIONCODE='INS1')
		ORDER BY STEPNUMBER DESC) STSMC ON STSMC.PRODUCTIONDEMANDCODE = PRODUCTIONDEMAND.CODE
	LEFT JOIN 
		(SELECT 
			trim(LISTAGG (PROGRESSSTATUS , ',') WITHIN GROUP(ORDER BY PRODUCTIONDEMANDCODE ASC)) as IDS	,
			PRODUCTIONDEMANDCODE
		FROM 
			PRODUCTIONDEMANDSTEP 
		WHERE 
			(OPERATIONCODE='INS1' OR OPERATIONCODE='KNT1')
		GROUP BY 
			PRODUCTIONDEMANDCODE) STSMC1 ON STSMC1.PRODUCTIONDEMANDCODE=PRODUCTIONDEMAND.CODE
	LEFT JOIN 
		(SELECT 
			COUNT(WEIGHTREALNET ) AS JML,
			INSPECTIONENDDATETIME, 
			DEMANDCODE
		FROM 
			ELEMENTSINSPECTION 
		WHERE 
			ELEMENTITEMTYPECODE='KGF' AND QUALITYREASONCODE='PM'
		GROUP BY 
			INSPECTIONENDDATETIME, DEMANDCODE) PM ON PM.DEMANDCODE=PRODUCTIONDEMAND.CODE
	WHERE 
		PRODUCTIONDEMAND.ITEMTYPEAFICODE  ='KGF' AND 
--		(ADSTORAGE.VALUESTRING='$mc' OR SCHEDULESOFSTEPSPLITS.SCHEDULEDRESOURCECODE='$mc') AND 
		(PRODUCTIONDEMAND.PROGRESSSTATUS='2' OR AD7.VALUESTRING='1')
	ORDER BY STSMC.STEPNUMBER DESC ) STSLAYAR
--ORDER BY STSLAYAR.URUT ASC