SELECT
	p.CODE,
	REPLACE(p.SYMPTOM, CHR(10), '') AS TASK,
	p3.LONGDESCRIPTION AS PROJECT,
	SUBSTR(a2.VALUESTRING, 1,3) AS DEPT,
	TRIM(p.RESPONSIBLEOFSCHEDULINGUSERID) AS PIC,
	CASE
		WHEN p.PRIORITYLEVEL = 2 THEN 'Medium'
		WHEN p.PRIORITYLEVEL = 1 THEN 'High'
		WHEN p.PRIORITYLEVEL = 0 THEN 'High'
		ELSE ''
	END	AS PRIORITY,
	VARCHAR_FORMAT(p2.STARTDATE, 'mm/dd/YYYY') AS START,
	VARCHAR_FORMAT(p2.ENDDATE, 'mm/dd/YYYY') AS STOP,
	'' AS WORKDAYS,
	'In Progress'
--	,p.REMARKS
--	,p2.REMARKS 
FROM
	PMBREAKDOWNENTRY p 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p.ABSUNIQUEID AND a.FIELDNAME = 'ApprovalDeptUserCode'
LEFT JOIN PMWORKORDER p2 ON p2.PMBREAKDOWNENTRYCODE = p.CODE 
LEFT JOIN PMBOM p3 ON p3.CODE = p.PMBOMCODE 
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = p.ABSUNIQUEID AND a2.FIELDNAME = 'ApprovalDeptUserCode'
WHERE 
	p.COUNTERCODE = 'PBD003'
	AND p.BREAKDOWNTYPE = 'SF'
ORDER BY 
	p.IDENTIFIEDDATE ASC