WITH QTY_BRUTO AS (
SELECT
	i.CODE,
	i.ORIGDLVSALORDLINESALORDERCODE,
	i.ORIGDLVSALORDERLINEORDERLINE,
	SUM(i.USERPRIMARYQUANTITY) AS KFF
FROM
    ITXVIEWKGBRUTOBONORDER2 i
GROUP BY 
  	i.CODE,
    i.ORIGDLVSALORDLINESALORDERCODE,
    i.ORIGDLVSALORDERLINEORDERLINE
)
SELECT DISTINCT 
	i.SALESORDERCODE,
	i.ORDERLINE,
	TRIM(i.SUBCODE02) || '-' || TRIM(i.SUBCODE03) AS ITEM,
	i.WARNA,
	ROUND(i.BASEPRIMARYQUANTITY) AS NETTO,
	SUM(qb.KFF) AS BRUTO,
	SUM(p2.USEDUSERPRIMARYQUANTITY) AS SUDAH_BAGI_KAIN,
	SUM(qb.KFF) - SUM(p2.USEDUSERPRIMARYQUANTITY) AS BALANCE_BELUM_BAGI_KAIN
FROM
	ITXVIEWBONORDER i 
LEFT JOIN PRODUCTIONDEMAND p ON p.CODE = i.DEMAND 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p.ABSUNIQUEID AND a.FIELDNAME = 'OriginalPDCode'
LEFT JOIN ITXVIEWCOLOR i2 ON i2.ITEMTYPECODE = i.ITEMTYPEAFICODE 
						 AND i2.SUBCODE01 = i.SUBCODE01
						 AND i2.SUBCODE02 = i.SUBCODE02 
						 AND i2.SUBCODE03 = i.SUBCODE03 
						 AND i2.SUBCODE04 = i.SUBCODE04 
						 AND i2.SUBCODE05 = i.SUBCODE05 
						 AND i2.SUBCODE06 = i.SUBCODE06 
						 AND i2.SUBCODE07 = i.SUBCODE07 
						 AND i2.SUBCODE08 = i.SUBCODE08 
						 AND i2.SUBCODE09 = i.SUBCODE09 
						 AND i2.SUBCODE10 = i.SUBCODE10
LEFT JOIN QTY_BRUTO qb ON qb.ORIGDLVSALORDLINESALORDERCODE = i.SALESORDERCODE AND qb.ORIGDLVSALORDERLINEORDERLINE = i.ORDERLINE AND qb.CODE = p.CODE
LEFT JOIN PRODUCTIONRESERVATION p2 ON p2.ORDERCODE = i.DEMAND AND p2.ITEMTYPEAFICODE = 'KGF'
WHERE 
	i.SALESORDERCODE = 'DOM2500444'
	AND a.VALUESTRING IS NULL
GROUP BY
	i.SALESORDERCODE,
	i.ORDERLINE,
	i.SUBCODE02,
	i.SUBCODE03,
	i.WARNA,
	i.BASEPRIMARYQUANTITY
ORDER BY 
	i.ORDERLINE
ASC