SELECT  
	p.CODE,
	REPLACE(p.SYMPTOM, CHR(10), '') AS TASK,
	p3.SEARCHDESCRIPTION AS JENIS_PROGRAM,
	SUBSTR(a2.VALUESTRING, 1,3) AS DEPT,
	TRIM(p.DEFAULTASSIGNEDTOUSERID) AS PIC,
	CASE
		WHEN a3.VALUESTRING = 1 THEN 'Medium'
		WHEN a3.VALUESTRING = 2 THEN 'High'
		ELSE ''
	END	AS PRIORITY,
	VARCHAR_FORMAT(p2.STARTDATE, 'mm/dd/YYYY') AS START,
	CASE
		WHEN p2.ENDDATE IS NULL THEN 
			CASE
				WHEN DAYOFWEEK_ISO(p2.STARTDATE) = 1 THEN VARCHAR_FORMAT(SUBSTR(p2.STARTDATE  + 3 DAYS, 1,10), 'mm/dd/YYYY')
		        WHEN DAYOFWEEK_ISO(p2.STARTDATE) = 2 THEN VARCHAR_FORMAT(SUBSTR(p2.STARTDATE  + 3 DAYS, 1,10), 'mm/dd/YYYY')
		        WHEN DAYOFWEEK_ISO(p2.STARTDATE) = 3 THEN VARCHAR_FORMAT(SUBSTR(p2.STARTDATE  + 5 DAYS, 1,10), 'mm/dd/YYYY')
		        WHEN DAYOFWEEK_ISO(p2.STARTDATE) = 4 THEN VARCHAR_FORMAT(SUBSTR(p2.STARTDATE  + 5 DAYS, 1,10), 'mm/dd/YYYY')
		        WHEN DAYOFWEEK_ISO(p2.STARTDATE) = 5 THEN VARCHAR_FORMAT(SUBSTR(p2.STARTDATE  + 5 DAYS, 1,10), 'mm/dd/YYYY')
			END			
		ELSE
		VARCHAR_FORMAT(p2.ENDDATE, 'mm/dd/YYYY')
	END AS STOP,
	'' AS WORKDAYS,
	CASE
		WHEN p2.STARTDATE IS NOT NULL AND p2.ENDDATE IS NULL THEN 'In Progress'
		WHEN p2.STARTDATE IS NOT NULL AND p2.ENDDATE IS NOT NULL THEN 'Complete'
		WHEN p2.STARTDATE IS NULL AND p2.ENDDATE IS NULL THEN 'Not Started'
		ELSE 'Pending'
	END
--	,am.LINK	
--	,p.REMARKS
--	,p2.REMARKS 
	,CASE WHEN a4.VALUESTRING = 1 THEN 'Mayor' ELSE 'Minor' END
FROM
	PMBREAKDOWNENTRY p 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p.ABSUNIQUEID AND a.FIELDNAME = 'ApprovalDeptUserCode'
LEFT JOIN PMWORKORDER p2 ON p2.PMBREAKDOWNENTRYCODE = p.CODE 
LEFT JOIN PMBOM p3 ON p3.CODE = p.PMBOMCODE 
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = p.ABSUNIQUEID AND a2.FIELDNAME = 'ApprovalDeptUserCode'
LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = p.ABSUNIQUEID AND a3.FIELDNAME = 'PrioritasTicket'
--LEFT JOIN ABSMULTIMEDIADEPENDENT am ON am.FATHERID = p2.ABSUNIQUEID 
LEFT JOIN ADSTORAGE a4 ON a4.UNIQUEID = p2.ABSUNIQUEID AND a4.FIELDNAME = 'JenisKerusakan'
WHERE 
	p.BREAKDOWNTYPE = 'SF'
	AND NOT a2.VALUESTRING IS NULL
	AND SUBSTR(p.CODE, 1,4) = 'BDIT' 
	AND p.IDENTIFIEDDATE BETWEEN '2025-02-01' AND '2025-02-28'
ORDER BY 
	p.IDENTIFIEDDATE ASC