SELECT DISTINCT
    i.PROVISIONALCODE,
    i.SALESORDERCOUNTERCODE,
    i.DEFINITIVEDOCUMENTDATE,
    i.ORDERPARTNERBRANDCODE,
    i.PO_NUMBER,
    i.PROJECTCODE,
    DAY(i.GOODSISSUEDATE) ||'-'|| MONTHNAME(i.GOODSISSUEDATE) ||'-'|| YEAR(i.GOODSISSUEDATE) AS GOODSISSUEDATE,
    i.ORDPRNCUSTOMERSUPPLIERCODE,
    i.PAYMENTMETHODCODE,
    i.PO_NUMBER,    
    i.ITEMTYPEAFICODE,
    i.DLVSALORDERLINESALESORDERCODE,
    CASE
    	WHEN TRIM(i.SALESORDERCOUNTERCODE) = 'EXPORT' THEN 0 ELSE i.DLVSALESORDERLINEORDERLINE
	END AS DLVSALESORDERLINEORDERLINE,
    CASE
    	WHEN TRIM(i.SALESORDERCOUNTERCODE) = 'EXPORT' THEN '' ELSE i.ITEMDESCRIPTION
	END AS ITEMDESCRIPTION,
 	CASE
    	WHEN TRIM(i.SALESORDERCOUNTERCODE) = 'EXPORT' THEN '' ELSE iasp.LOTCODE
	END AS LOTCODE,
    CASE
    	WHEN TRIM(i.SALESORDERCOUNTERCODE) = 'EXPORT' THEN '' ELSE i2.WARNA
	END AS WARNA,
    i.LEGALNAME1,
    CASE
    	WHEN TRIM(i.SALESORDERCOUNTERCODE) = 'EXPORT' THEN '0' ELSE i.CODE
	END AS CODE
FROM 
    ITXVIEW_SURATJALAN_PPC_FOR_POSELESAI i
LEFT JOIN ITXVIEW_ALLOCATION_SURATJALAN_PPC iasp ON iasp.CODE = i.CODE
LEFT JOIN ITXVIEWCOLOR i2 ON i2.ITEMTYPECODE =  i.ITEMTYPEAFICODE
                        AND i2.SUBCODE01 = i.SUBCODE01 AND i2.SUBCODE02 = i.SUBCODE02
                        AND i2.SUBCODE03 = i.SUBCODE03 AND i2.SUBCODE04 = i.SUBCODE04
                        AND i2.SUBCODE05 = i.SUBCODE05 AND i2.SUBCODE06 = i.SUBCODE06
                        AND i2.SUBCODE07 = i.SUBCODE07 AND i2.SUBCODE08 = i.SUBCODE08
                        AND i2.SUBCODE09 = i.SUBCODE09 AND i2.SUBCODE10 = i.SUBCODE10
WHERE 
--    i.DLVSALORDERLINESALESORDERCODE = 'SAM2300253'
	i.GOODSISSUEDATE = '2023-07-25'
    AND i.DOCUMENTTYPETYPE = 05
GROUP BY
	i.PROVISIONALCODE,
    i.DEFINITIVEDOCUMENTDATE,
    i.ORDERPARTNERBRANDCODE,
    i.PO_NUMBER,
    i.PROJECTCODE,
    i.GOODSISSUEDATE,
    i.ORDPRNCUSTOMERSUPPLIERCODE,
    i.PAYMENTMETHODCODE,
    i.PO_NUMBER,    
    i.ITEMTYPEAFICODE,
    i.DLVSALORDERLINESALESORDERCODE,
    i.DLVSALESORDERLINEORDERLINE,
    i.ITEMDESCRIPTION,
    iasp.LOTCODE,
    i.SALESORDERCOUNTERCODE,
    i2.WARNA,
    i.LEGALNAME1,
    i.CODE
ORDER BY 
    i.PROVISIONALCODE ASC