SELECT
	NO_BD,
	NAMA_APLIKASI AS NAMA_PROGRAM,
	DEPT, 
	PROGRAMMER AS STAFF,
	CASE
		WHEN NAMA_APLIKASI LIKE '%.rpt%' THEN 'Report NOW'
		ELSE 'Web Base'
	END	AS JENIS_PROGRAM,
	JENIS_KERUSAKAN AS TYPE,
	DESKRIPSI_PEMOHON,
	TGL_DITERIMA_DIT AS TGL_MULAI,
	TGL_SELESAI,
	CASE 
		WHEN TGL_TARGET < TGL_SELESAI THEN 'finish, delay'
		WHEN TGL_SELESAI IS NULL THEN 'In Progress'
		ELSE 'finish, ontime'
	END AS STS,
	TGL_TARGET,
	CASE
		WHEN 
			(DAYS(TGL_SELESAI) - DAYS(TGL_TARGET)) - (CASE WHEN DAYOFWEEK(TGL_TARGET) > 4 THEN 2 ELSE 0 END) - (CASE WHEN DAYOFWEEK(TGL_SELESAI) > 4 THEN 2 ELSE 0 END) < 0 THEN 0
		ELSE
			(DAYS(TGL_SELESAI) - DAYS(TGL_TARGET)) - (CASE WHEN DAYOFWEEK(TGL_TARGET) > 4 THEN 2 ELSE 0 END) - (CASE WHEN DAYOFWEEK(TGL_SELESAI) > 4 THEN 2 ELSE 0 END)
	END AS SELISIHHARIKERJA
FROM
	ITXVIEW_PPA_DIT ipd
WHERE 
	SUBSTR(IDENTIFIEDDATE, 1, 10) BETWEEN '2024-12-01' AND '2024-12-31'
--	TGL_MULAI >= '2024-07-01' AND TGL_SELESAI IS NULL