SELECT 
	TRIM(d.SHORTDESCRIPTION) AS DEPT,
    TRIM(p.CODE) AS KODE_PRASARANA,
    RIGHT(TRIM(p.CODE), 6) AS TAG,
    TRIM(p.LONGDESCRIPTION) AS USER,
    TRIM(p.FIRSTUSERGRPCODE) AS JENIS_PRASARANA,
    TRIM(p.GENERICDATA1) AS RAM,
    TRIM(p.GENERICDATA2) AS HD,
    TRIM(p.GENERICDATA3) AS OS
FROM
    PMBOM p
LEFT JOIN DEPARTMENT d ON d.CODE = p.DEPARTMENTCODE
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p.ABSUNIQUEID AND a.FIELDNAME = 'IPADDRESS'
WHERE 
    (p.FIRSTUSERGRPCODE = 'CPU' OR
    p.FIRSTUSERGRPCODE = 'DESKTOP' OR
    p.FIRSTUSERGRPCODE = 'LAPTOP' OR
    p.FIRSTUSERGRPCODE = 'NOTEBOOK' OR
    p.FIRSTUSERGRPCODE = 'PRINTER' OR
    p.FIRSTUSERGRPCODE = 'SCANNER' OR
    p.FIRSTUSERGRPCODE = 'TELEPON' OR
    p.FIRSTUSERGRPCODE = 'BARCODE'OR 
    p.FIRSTUSERGRPCODE = 'TABLET')
--    AND TRIM(d.CODE) = 'D003'
    AND p.STATUS = '1'
ORDER BY 
	p.FIRSTUSERGRPCODE ASC