SELECT
	p.ITEMTYPEAFICODE, 
    p.SUBCODE01,p.SUBCODE02,
    p.SUBCODE03,p.SUBCODE04,
    p.SUBCODE05,p.SUBCODE06,
    p.SUBCODE07,p.SUBCODE08,
    s2.ORDERDATE AS TGLTERIMAORDER,
    b.LEGALNAME1 AS PELANGGAN,
    s.PROJECTCODE AS NO_ORDER,
    s.EXTERNALREFERENCE AS NO_PO,
    trim( s.ITEMDESCRIPTION ) || ' | ' ||
    trim( s.SUBCODE01 ) || '  ' ||
    trim( s.SUBCODE02 ) || '  ' ||
    trim( s.SUBCODE03 ) || '  ' ||
    trim( s.SUBCODE04 ) || '  ' ||
    trim( s.SUBCODE05 ) || '  ' ||
    trim( s.SUBCODE06 ) || '  ' ||
    trim( s.SUBCODE07 ) || '  ' ||
    trim( s.SUBCODE08 ) AS KETERANGAN_PRODUCT,
    a.VALUEDECIMAL AS LEBAR,
    a2.VALUEDECIMAL AS GRAMASI,
    trim( i.WARNA ) AS WARNA,
    trim( s.SUBCODE05 ) AS NO_WARNA,
    s3.DELIVERYDATE AS DELIVERY,
    trim( p2.SCHEDULEDISSUEDATE ) AS BAGIKAIN,
    QTY_DUS,
    (p2.USEDUSERPRIMARYQUANTITY) AS KG_BRUTO,
    (in2.USERPRIMARYQUANTITY) AS NETTO,
    CASE
        WHEN trim(s.PRICEUNITOFMEASURECODE) = 'm' THEN in3.BASESECONDARYQUANTITY
    END AS QTY_METER,
    in3.USERSECONDARYQUANTITY AS QTY_YARDKG,
    trim(s.PRICEUNITOFMEASURECODE) AS sample,
    CASE
        WHEN Days(now()) - Days(Timestamp_Format(s3.DELIVERYDATE, 'YYYY-MM-DD')) < 0 THEN 0
        ELSE Days(now()) - Days(Timestamp_Format(s3.DELIVERYDATE, 'YYYY-MM-DD'))
    END	AS DELAY,    
    trim( p.CODE ) AS DEMAND,
    trim( p2.PRODUCTIONORDERCODE) AS NO_KK
FROM 
    SALESORDERLINE s 
    LEFT JOIN SALESORDER s2 ON s2.CODE = s.PROJECTCODE
    LEFT JOIN SALESORDERDELIVERY s3 ON s3.SALESORDERLINESALESORDERCODE = s.SALESORDERCODE AND s3.SALESORDERLINEORDERLINE = s.ORDERLINE
    RIGHT JOIN ORDERPARTNER o ON o.CUSTOMERSUPPLIERCODE = s2.FNCORDPRNCUSTOMERSUPPLIERCODE
    RIGHT JOIN BUSINESSPARTNER b ON b.NUMBERID = o.ORDERBUSINESSPARTNERNUMBERID
    LEFT JOIN ITXVIEWCOLOR i ON i.ITEMTYPECODE = s.ITEMTYPEAFICODE
                                        AND i.SUBCODE01 = s.SUBCODE01
                                        AND i.SUBCODE02 = s.SUBCODE02
                                        AND i.SUBCODE03 = s.SUBCODE03
                                        AND i.SUBCODE04 = s.SUBCODE04
                                        AND i.SUBCODE05 = s.SUBCODE05
                                        AND i.SUBCODE06 = s.SUBCODE06
                                        AND i.SUBCODE07 = s.SUBCODE07
                                        AND i.SUBCODE08 = s.SUBCODE08
    LEFT JOIN PRODUCTIONDEMAND p ON p.PROJECTCODE = s.PROJECTCODE AND p.ITEMTYPEAFICODE = s.ITEMTYPEAFICODE 
                                AND p.SUBCODE01 =  s.SUBCODE01 AND p.SUBCODE02 =  s.SUBCODE02
                                AND p.SUBCODE03 =  s.SUBCODE03 AND p.SUBCODE04 =  s.SUBCODE04
                                AND p.SUBCODE05 =  s.SUBCODE05 AND p.SUBCODE06 =  s.SUBCODE06
                                AND p.SUBCODE07 =  s.SUBCODE07 AND p.SUBCODE08 =  s.SUBCODE08
                                AND p.DLVSALESORDERLINEORDERLINE = s.ORDERLINE
    LEFT JOIN PRODUCTIONRESERVATION p2 ON p2.ITEMTYPEAFICODE = 'KGF' AND p2.ORDERCODE = p.CODE
    LEFT JOIN PRODUCT p3 ON p3.SUBCODE01 = s.SUBCODE01
                        AND p3.SUBCODE02 = s.SUBCODE02
                        AND p3.SUBCODE03 = s.SUBCODE03
                        AND p3.SUBCODE04 = s.SUBCODE04
                        AND p3.SUBCODE05 = s.SUBCODE05
                        AND p3.SUBCODE06 = s.SUBCODE06
                        AND p3.SUBCODE07 = s.SUBCODE07
                        AND p3.SUBCODE08 = s.SUBCODE08
                        AND p3.ITEMTYPECODE = s.ITEMTYPEAFICODE 
    LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p3.ABSUNIQUEID AND a.NAMENAME = 'Width'
    LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = p3.ABSUNIQUEID AND a2.NAMENAME = 'GSM'
    LEFT JOIN ITXVIEW_NETTO in2 ON in2.CODE = p.CODE AND in2.SALESORDERLINESALESORDERCODE = s.SALESORDERCODE 
    LEFT JOIN ITXVIEW_NETTO in3 ON in3.CODE = p.CODE AND in3.SALESORDERLINESALESORDERCODE = s.SALESORDERCODE
    LEFT JOIN (SELECT COUNT(s3.BASEPRIMARYQUANTITY) AS QTY_DUS, s3.ORDERCODE, s3.PRODUCTIONORDERCODE FROM STOCKTRANSACTION s3 GROUP BY s3.PRODUCTIONORDERCODE, s3.ORDERCODE)s3 
    												ON s3.PRODUCTIONORDERCODE = p2.PRODUCTIONORDERCODE AND s3.ORDERCODE = p.CODE
    LEFT JOIN STOCKTRANSACTION s4 ON s4.PRODUCTIONORDERCODE = p2.PRODUCTIONORDERCODE 
    
WHERE
    s.PROJECTCODE = 'REP2201037' AND NOT p.CODE ISNULL
    												
WHERE
    s2.REQUIREDDUEDATE BETWEEN '2022-10-01' AND '2022-10-20' AND NOT p.CODE ISNULL
    
SELECT COUNT(s3.BASEPRIMARYQUANTITY) AS QTY_DUS, s3.ORDERCODE , s3.PRODUCTIONORDERCODE FROM STOCKTRANSACTION s3 GROUP BY s3.PRODUCTIONORDERCODE, s3.ORDERCODE 

SELECT 
	p.PRODUCTIONORDERCODE, p.PRODUCTIONDEMANDCODE, p.GROUPSTEPNUMBER, p.OPERATIONCODE, p.LONGDESCRIPTION, p.PROGRESSSTATUS, wc.LONGDESCRIPTION AS DEPT, p.WORKCENTERCODE
FROM PRODUCTIONDEMANDSTEP p
LEFT JOIN WORKCENTER wc ON wc.CODE = p.WORKCENTERCODE
WHERE p.PRODUCTIONORDERCODE = '00032850' AND (p.PROGRESSSTATUS = '2' OR p.PROGRESSSTATUS = '3') 
AND p.GROUPSTEPNUMBER = ( SELECT MAX(GROUPSTEPNUMBER) FROM PRODUCTIONDEMANDSTEP WHERE PRODUCTIONORDERCODE = '00032850' AND (PROGRESSSTATUS = '2' OR PROGRESSSTATUS = '3') )
ORDER BY p.GROUPSTEPNUMBER ASC 