SELECT 
	i3.SALESORDERCODE,
	i3.ORDERLINE,
	LISTAGG(TRIM(i3.LOTCODE), ', ') AS LOTCODE,
	LISTAGG(TRIM(i3.DEMAND_KGF), ', ') AS DEMAND_KGF
FROM 
	ITXVIEWPOGREIGENEW i3 
WHERE i3.SALESORDERCODE = 'DOM2202020' AND i3.ORDERLINE = '10'
GROUP BY 
	i3.SALESORDERCODE,
	i3.ORDERLINE
	
SELECT
	 PRODUCTIONORDERCODE, 
	 PRODUCTIONDEMANDCODE,
	 SUBSTR(LONGDESCRIPTION, 1, LOCATE(',', LONGDESCRIPTION)-1) AS LONGDESCRIPTION,
	 CASE
        WHEN SUBSTR(STATUS_OPERATION, 1, LOCATE(',', STATUS_OPERATION)-1) = 0 THEN 'Entered'
        WHEN SUBSTR(STATUS_OPERATION, 1, LOCATE(',', STATUS_OPERATION)-1) = 1 THEN 'Planned'
        WHEN SUBSTR(STATUS_OPERATION, 1, LOCATE(',', STATUS_OPERATION)-1) = 2 THEN 'Progress'
        WHEN SUBSTR(STATUS_OPERATION, 1, LOCATE(',', STATUS_OPERATION)-1) = 3 THEN 'Closed'
    END AS STATUS_OPERATION,
    SUBSTR(DEPT, 1, LOCATE(',', DEPT)-1) AS DEPT
    FROM (
		SELECT 
			p.PRODUCTIONORDERCODE, 
			p.PRODUCTIONDEMANDCODE,
			p.PROGRESSSTATUS,
		    LISTAGG(p.LONGDESCRIPTION, ', ') WITHIN GROUP(ORDER BY p.GROUPSTEPNUMBER ASC) AS LONGDESCRIPTION,
		    LISTAGG(p.PROGRESSSTATUS, ', ') WITHIN GROUP(ORDER BY p.GROUPSTEPNUMBER ASC) AS STATUS_OPERATION,
			LISTAGG(wc.LONGDESCRIPTION, ', ') WITHIN GROUP(ORDER BY p.GROUPSTEPNUMBER ASC) AS DEPT
		FROM 
		    PRODUCTIONDEMANDSTEP p
		LEFT JOIN WORKCENTER wc ON wc.CODE = p.WORKCENTERCODE
		WHERE 
			p.PRODUCTIONORDERCODE = '00039420' AND p.PRODUCTIONDEMANDCODE = '00089575' AND (p.PROGRESSSTATUS = '0' OR p.PROGRESSSTATUS = '1' OR p.PROGRESSSTATUS ='2')
		GROUP BY 
			p.PRODUCTIONORDERCODE, 
			p.PRODUCTIONDEMANDCODE,p.PROGRESSSTATUS)

SELECT 
    p.PRODUCTIONORDERCODE, p.PRODUCTIONDEMANDCODE, 
    p.GROUPSTEPNUMBER, p.OPERATIONCODE, 
    p.LONGDESCRIPTION, 
    CASE
        WHEN p.PROGRESSSTATUS = 0 THEN 'Entered'
        WHEN p.PROGRESSSTATUS = 1 THEN 'Planned'
        WHEN p.PROGRESSSTATUS = 2 THEN 'Progress'
        WHEN p.PROGRESSSTATUS = 3 THEN 'Closed'
    END AS STATUS_OPERATION,
    wc.LONGDESCRIPTION AS DEPT, p.WORKCENTERCODE
FROM 
    PRODUCTIONDEMANDSTEP p
LEFT JOIN WORKCENTER wc ON wc.CODE = p.WORKCENTERCODE
WHERE 
p.PRODUCTIONORDERCODE = '00039420' AND p.PRODUCTIONDEMANDCODE = '00089575' AND (p.PROGRESSSTATUS = '0' OR p.PROGRESSSTATUS = '1' OR p.PROGRESSSTATUS ='2')
ORDER BY p.GROUPSTEPNUMBER ASC LIMIT 1