SELECT
	CODE AS MESIN_CODE,
	u.SHORTDESCRIPTION AS MESIN_STORAGE,
	u.LONGDESCRIPTION AS NAMA_MESIN,
	CASE
		WHEN SUBSTRING(TRIM(CODE), 1,2) = 'DO' THEN 'Double Knit'
		WHEN SUBSTRING(TRIM(CODE), 1,2) = 'RI' THEN 'Rib'
		WHEN SUBSTRING(TRIM(CODE), 1,2) = 'SO' THEN 'Single Knit'
		WHEN SUBSTRING(TRIM(CODE), 1,2) = 'ST' THEN 'Single Knit'
		WHEN SUBSTRING(TRIM(CODE), 1,2) = 'TF' THEN 'Fleece'
		WHEN SUBSTRING(TRIM(CODE), 1,2) = 'TT' THEN 'Fleece'
	END AS JENIS	
FROM
	USERGENERICGROUP u
WHERE 	
	u.USERGENERICGROUPTYPECODE  = 'MCK'