SELECT 
	CASE
		WHEN ic.VALUESTRING = '1' THEN 'Labdip - ' || ic2.VALUESTRING
		WHEN ic.VALUESTRING = '2' THEN 'First Lot - ' || ic2.VALUESTRING
		WHEN ic.VALUESTRING = '3' THEN 'Original - ' || ic2.VALUESTRING
		WHEN ic.VALUESTRING = '4' THEN 'Previous Order - ' || ic2.VALUESTRING
		WHEN ic.VALUESTRING = '5' THEN 'Master Color - ' || ic2.VALUESTRING
		WHEN ic.VALUESTRING = '6' THEN 'Lampiran Buyer - ' || ic2.VALUESTRING
		WHEN ic.VALUESTRING = '7' THEN 'Body - ' || ic2.VALUESTRING
	END AS STANDART_COCOK_WARNA
FROM 
	SALESORDERLINE s 
LEFT JOIN ITXVIEW_COLORSTANDARD ic ON ic.UNIQUEID = s.ABSUNIQUEID 
LEFT JOIN ITXVIEW_COLORREMARKS ic2 ON ic2.UNIQUEID = s.ABSUNIQUEID 
WHERE 
	s.SALESORDERCODE = '' AND ORDERLINE = ''