SELECT
    SUBSTR(NOW() + 14 MINUTES + 30 SECOND, 1, 19) AS WAKTUSEKARANG,
    STMT_TEXT AS QUERY,
    APPL_ID AS IPADDRESS,
    CLIENT_WRKSTNNAME,
    *
FROM
    TABLE(MON_GET_ACTIVITY(NULL,-2)) AS ACTIVITY
WHERE 
    SUBSTR(LOCAL_START_TIME, 1, 19)  = SUBSTR(NOW(), 1,19) 
ORDER BY
    LOCAL_START_TIME DESC