SELECT 
	p.CODE AS NO_PC_LAPTOP,
	p.GENERICDATA1 AS RAM,
	p.GENERICDATA2 AS HD,
	p.GENERICDATA3 AS OS,
	p.LONGDESCRIPTION AS USER,
	d.CODE AS CODE_DEPT,
	d.SHORTDESCRIPTION AS DEPT 
FROM
	PMBOM p
LEFT JOIN DEPARTMENT d ON d.CODE = p.DEPARTMENTCODE 
WHERE 
	(p.FIRSTUSERGRPCODE = 'CPU' OR
	p.FIRSTUSERGRPCODE = 'DESKTOP' OR
	p.FIRSTUSERGRPCODE = 'LAPTOP' OR
	p.FIRSTUSERGRPCODE = 'NOTEBOOK' OR
	p.FIRSTUSERGRPCODE = 'PRINTER' OR
	p.FIRSTUSERGRPCODE = 'SCANNER')
	AND d.SHORTDESCRIPTION = 'DYE'