SELECT
	a.SUBCODE02,
	a.SUBCODE03,
	a.SUBCODE04,
	SUM(a.BASEPRIMARYQUANTITY) AS BASEPRIMARYQUANTITY,
	SUM(a3.VALUEDECIMAL) AS QTYSALIN,
	CURRENT_TIMESTAMP AS TGLS
FROM
	ITXVIEWHEADERKNTORDER a
LEFT OUTER JOIN PRODUCTIONDEMAND p ON p.CODE = a.PRODUCTIONDEMANDCODE
LEFT OUTER JOIN ADSTORAGE a2 ON	p.ABSUNIQUEID = a2.UNIQUEID	AND a2.NAMENAME = 'StatusRMP'
LEFT OUTER JOIN ADSTORAGE a3 ON	p.ABSUNIQUEID = a3.UNIQUEID	AND a3.NAMENAME = 'QtySalin'
WHERE
	a.ITEMTYPEAFICODE = 'KGF'
	AND TRIM(a.SUBCODE02) = 'MTR'
	AND TRIM(a.SUBCODE03) = '21120'
	AND TRIM(a.SUBCODE04) = 'L02'
	AND (a.PROGRESSSTATUS = '2'	OR a.PROGRESSSTATUS = '6')
	AND (NOT a2.VALUESTRING = '3' OR a2.VALUESTRING IS NULL)
GROUP BY
	a.SUBCODE02,
	a.SUBCODE03,
	a.SUBCODE04,
	CURRENT_TIMESTAMP