-- TRUNCATE table
TRUNCATE TABLE DB2ADMIN.ITXTEMP_SCHEDULE_KNT_STAGING IMMEDIATE;

INSERT INTO DB2ADMIN.ITXTEMP_SCHEDULE_KNT_STAGING (
    KDMC,
    PRODUCTIONDEMANDCODE,
    STATUSMESIN,
    ESTIMASI_SELESAI,
    SUBCODE01,
    SUBCODE02,
    SUBCODE03,
    SUBCODE04,
    QTY_ORDER,
    QTY_SISA,
    STANDAR_RAJUT,
    TGL_START,
    TGLDELIVERY,
    TGLMULAI,
    STSMC
)WITH 
STDR AS (
    SELECT DISTINCT
        PRODUCT.SUBCODE02,
        PRODUCT.SUBCODE03,
        PRODUCT.SUBCODE04,
        (ADSTORAGE.VALUEDECIMAL * 24) AS STDRAJUT
    FROM PRODUCT PRODUCT
    LEFT JOIN ADSTORAGE ADSTORAGE ON PRODUCT.ABSUNIQUEID = ADSTORAGE.UNIQUEID
    WHERE 
        ADSTORAGE.NAMENAME = 'ProductionRate'
        AND PRODUCT.ITEMTYPECODE = 'KGF'
        AND PRODUCT.COMPANYCODE = '100'
),
JML251 AS (
    SELECT
        COUNT(WEIGHTREALNET ) AS JML,
        DEMANDCODE
    FROM 
    	ELEMENTSINSPECTION
    WHERE 
    	ELEMENTITEMTYPECODE='KGF' AND COMPANYCODE = '100'
    GROUP BY 
    	DEMANDCODE
),
J2 AS (
    SELECT DISTINCT
        DEMANDCODE,
        DATE(MIN(INSPECTIONSTARTDATETIME)) AS TGLMULAI,
        COUNT(WEIGHTREALNET) AS JML,
        SUM(WEIGHTREALNET) AS JQTY
    FROM ELEMENTSINSPECTION
    WHERE ELEMENTITEMTYPECODE = 'KGF' AND COMPANYCODE = '100'
    GROUP BY DEMANDCODE
)
SELECT
	a.VALUESTRING AS KDMC,
	p.CODE AS PRODUCTIONDEMANDCODE,
	CASE
		WHEN (p.PROGRESSSTATUS = '6' AND a4.VALUESTRING = '1' AND COALESCE(JML251.JML, 0) > 0) THEN 'Sedang Jalan Oper PO'
		WHEN (p.PROGRESSSTATUS = '2' OR a4.VALUESTRING = '1') AND TRIM(a2.VALUESTRING) IN ('0', '1') AND COALESCE(JML251.JML, 0) > 0 THEN 'Sedang Jalan'
		ELSE 
			SUBSTRING(
		        ad.OPTIONS, 
		        POSITION(';' || a2.VALUESTRING || '=' IN ad.OPTIONS) + LENGTH(a2.VALUESTRING) + 2,
		        POSITION(';' IN SUBSTRING(ad.OPTIONS, POSITION(';' || a2.VALUESTRING || '=' IN ad.OPTIONS) + LENGTH(a2.VALUESTRING) + 2)) - 1
		    )
	END AS STATUSMESIN,
    VARCHAR_FORMAT(
		DATE(a5.VALUEDATE) + 
			CEILING(
				CAST((COALESCE(p.BASEPRIMARYQUANTITY, 0.00) + COALESCE(a3.VALUEDECIMAL, 0.00)) AS DECIMAL) / NULLIF(ROUND(STDR.STDRAJUT, 0), 0)) DAYS - 1 DAYS, 'YYYY-MM-DD' 
	) AS ESTIMASI_SELESAI,
	TRIM(p.SUBCODE01) AS SUBCODE01,
	TRIM(p.SUBCODE02) AS SUBCODE02,
	TRIM(p.SUBCODE03) AS SUBCODE03,
	TRIM(p.SUBCODE04) AS SUBCODE04,
	COALESCE(p.BASEPRIMARYQUANTITY, 0.00) + COALESCE(a3.VALUEDECIMAL, 0.00) AS QTY_ORDER,
	CAST(
		(COALESCE(p.BASEPRIMARYQUANTITY, 0.00) + COALESCE(a3.VALUEDECIMAL, 0.00)) -
		(COALESCE(a7.VALUEDECIMAL, 0.00) + COALESCE(a8.VALUEDECIMAL, 0.00)) -
		COALESCE(J2.JQTY, 0.00)
	AS DECIMAL) AS QTY_SISA,
	ROUND(STDR.STDRAJUT, 0) AS STANDAR_RAJUT,
	a5.VALUEDATE AS TGL_START,
	a6.VALUEDATE AS TGLDELIVERY,
	J2.TGLMULAI,	
	a2.VALUESTRING AS STSMC
FROM
	PRODUCTIONDEMAND p 
LEFT JOIN (
        SELECT
            DISTINCT PRODUCTIONDEMANDCODE,
            PRODUCTIONORDERCODE
        FROM
            PRODUCTIONDEMANDSTEP PRODUCTIONDEMANDSTEP
    ) PRODUCTIONDEMANDSTEP ON p.CODE = PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p.ABSUNIQUEID AND a.FIELDNAME = 'MachineNoCode'
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = p.ABSUNIQUEID AND a2.FIELDNAME = 'StatusMesin'
LEFT JOIN ADADDITIONALDATA ad ON ad.NAME = a2.FIELDNAME AND ad.ENTITYNAME = 'ProductionDemand'
LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = p.ABSUNIQUEID AND a3.FIELDNAME = 'QtyOperOut'
LEFT JOIN ADSTORAGE a4 ON a4.UNIQUEID = p.ABSUNIQUEID AND a4.FIELDNAME = 'StatusOper'
LEFT JOIN STDR ON STDR.SUBCODE02 = p.SUBCODE02 
			   AND STDR.SUBCODE03 = p.SUBCODE03 
			   AND STDR.SUBCODE04 = p.SUBCODE04
LEFT JOIN JML251 ON JML251.DEMANDCODE = p.CODE
LEFT JOIN ADSTORAGE a5 ON a5.UNIQUEID = p.ABSUNIQUEID AND a5.FIELDNAME = 'TglRencana'
LEFT JOIN ADSTORAGE a6 ON a6.UNIQUEID = p.ABSUNIQUEID AND a6.FIELDNAME = 'RMPGreigeReqDateTo'
LEFT JOIN J2 ON J2.DEMANDCODE = p.CODE
LEFT JOIN ADSTORAGE a7 ON a7.UNIQUEID = p.ABSUNIQUEID AND a7.FIELDNAME = 'QtySalin'
LEFT JOIN ADSTORAGE a8 ON a8.UNIQUEID = p.ABSUNIQUEID AND a8.FIELDNAME = 'QtyOperIn'
WHERE 
	p.PROGRESSSTATUS <> '6'
	AND NOT a.VALUESTRING IS NULL
	AND NOT a2.VALUESTRING = '0'
    AND a5.VALUEDATE > CURRENT_DATE;
   
	CALL DB2ADMIN.SP_REFRESH_ITXTEMP_SCHEDULE_KNT();