-- TRUNCATE table
TRUNCATE TABLE DB2ADMIN.ITXTEMP_SCHEDULE_KNT_STAGING IMMEDIATE;

INSERT INTO DB2ADMIN.ITXTEMP_SCHEDULE_KNT_STAGING (
    KDMC,
    PRODUCTIONDEMANDCODE,
    STATUSMESIN,
    ESTIMASI_SELESAI,
    SUBCODE01,
    SUBCODE02,
    SUBCODE03,
    SUBCODE04,
    QTY_ORDER,
    QTY_SISA,
    STANDAR_RAJUT,
    TGL_START,
    TGLDELIVERY,
    TGLMULAI,
    STSMC
)WITH 
    DMN AS (
        SELECT 
            ADSTORAGE.VALUESTRING,
            AD3.VALUEDECIMAL AS QTYSALIN,
            AD4.VALUEDECIMAL AS QTYOPIN,
            AD5.VALUEDECIMAL AS QTYOPOUT,
            AD6.VALUESTRING AS STSOPR,
--            CURRENT_DATE AS TGLS,
            AD1.VALUEDATE AS TGLS,
            AD8.VALUESTRING AS STSMC,
            ITX.COMPANYCODE,
            ITX.CODE,
            ITX.ITEMTYPEAFICODE,
            ITX.SUBCODE01,
            ITX.SUBCODE02,
            ITX.SUBCODE03,
            ITX.SUBCODE04,
            ITX.BASEPRIMARYQUANTITY,
            ITX.PRODUCTIONDEMANDCODE,
            ITX.PRODUCTIONORDERCODE,
            ITX.PROGRESSSTATUS,
            PD.CODE AS DEMANDCODE,
            AD1.VALUEDATE AS TGL_START,
	    	AD7.VALUEDATE AS TGLDELIVERY
        FROM DB2ADMIN.ITXVIEWKNTORDER ITX
            LEFT JOIN DB2ADMIN.PRODUCTIONDEMAND PD ON PD.CODE = ITX.PRODUCTIONDEMANDCODE
            LEFT JOIN DB2ADMIN.ADSTORAGE  ON ADSTORAGE.UNIQUEID = PD.ABSUNIQUEID AND ADSTORAGE.NAMENAME = 'MachineNo'
            LEFT JOIN DB2ADMIN.ADSTORAGE AD1 ON AD1.UNIQUEID = PD.ABSUNIQUEID AND AD1.FIELDNAME = 'TglRencana'
            LEFT JOIN DB2ADMIN.ADSTORAGE AD2 ON AD2.UNIQUEID = PD.ABSUNIQUEID AND AD2.FIELDNAME = 'RMPReqDate'
            LEFT JOIN DB2ADMIN.ADSTORAGE AD3 ON AD3.UNIQUEID = PD.ABSUNIQUEID AND AD3.FIELDNAME = 'QtySalin'
            LEFT JOIN DB2ADMIN.ADSTORAGE AD4 ON AD4.UNIQUEID = PD.ABSUNIQUEID AND AD4.FIELDNAME = 'QtyOperIn'
            LEFT JOIN DB2ADMIN.ADSTORAGE AD5 ON AD5.UNIQUEID = PD.ABSUNIQUEID AND AD5.FIELDNAME = 'QtyOperOut'
            LEFT JOIN DB2ADMIN.ADSTORAGE AD6 ON AD6.UNIQUEID = PD.ABSUNIQUEID AND AD6.FIELDNAME = 'StatusOper'
            LEFT JOIN DB2ADMIN.ADSTORAGE AD7 ON AD7.UNIQUEID = PD.ABSUNIQUEID AND AD7.FIELDNAME = 'RMPGreigeReqDateTo'
            LEFT JOIN DB2ADMIN.ADSTORAGE AD8 ON AD8.UNIQUEID = PD.ABSUNIQUEID AND AD8.FIELDNAME = 'StatusMesin'
        WHERE 
            PD.ITEMTYPEAFICODE = 'KGF'
            AND (PD.PROGRESSSTATUS IN ('0', '1', '2') OR AD6.VALUESTRING = '1')
    ),
    J1 AS (
        SELECT 
            DEMANDCODE,
            COUNT(BASEPRIMARYQUANTITY) AS JML,
            SUM(BASEPRIMARYQUANTITY) AS JQTY
        FROM DB2ADMIN.VIEWPRODDEMANDELEMENTS
        WHERE PROGRESSSTATUS = '0' AND COMPANYCODE = '100'
        GROUP BY DEMANDCODE
    ),
    J2 AS (
        SELECT DISTINCT
            DEMANDCODE,
            DATE(MIN(INSPECTIONSTARTDATETIME)) AS TGLMULAI,
            COUNT(WEIGHTREALNET) AS JML,
            SUM(WEIGHTREALNET) AS JQTY
        FROM DB2ADMIN.ELEMENTSINSPECTION
        WHERE ELEMENTITEMTYPECODE = 'KGF' AND COMPANYCODE = '100'
        GROUP BY DEMANDCODE
    ),
    STDR AS (
        SELECT DISTINCT
            PRODUCT.SUBCODE02,
            PRODUCT.SUBCODE03,
            PRODUCT.SUBCODE04,
            (ADSTORAGE.VALUEDECIMAL * 24) AS STDRAJUT
        FROM DB2ADMIN.PRODUCT PRODUCT
        LEFT JOIN DB2ADMIN.ADSTORAGE ADSTORAGE ON PRODUCT.ABSUNIQUEID = ADSTORAGE.UNIQUEID
        WHERE 
            ADSTORAGE.NAMENAME = 'ProductionRate'
            AND PRODUCT.ITEMTYPECODE = 'KGF'
            AND PRODUCT.COMPANYCODE = '100'
    ),
    JML251 AS (
        SELECT
            COUNT(WEIGHTREALNET ) AS JML,
            DEMANDCODE
        FROM ELEMENTSINSPECTION
        WHERE ELEMENTITEMTYPECODE='KGF' AND COMPANYCODE='100'
        GROUP BY DEMANDCODE
    ),
    KGPAKAI AS (
        SELECT 
            PRODUCTIONRESERVATION.PRODUCTIONORDERCODE,
            SUM(PRODUCTIONRESERVATION.USEDBASEPRIMARYQUANTITY) AS KGPAKAI
        FROM DB2ADMIN.PRODUCTIONRESERVATION
        LEFT JOIN DB2ADMIN.FULLITEMKEYDECODER 
            ON PRODUCTIONRESERVATION.FULLITEMIDENTIFIER = FULLITEMKEYDECODER.IDENTIFIER
        GROUP BY PRODUCTIONRESERVATION.PRODUCTIONORDERCODE
    ),
    JML25PM AS (
        SELECT 
            DEMANDCODE,
            COUNT(WEIGHTREALNET) AS JML,
            MAX(INSPECTIONENDDATETIME) AS INSPECTIONENDDATETIME
        FROM DB2ADMIN.ELEMENTSINSPECTION
        WHERE 
            ELEMENTITEMTYPECODE = 'KGF' 
            AND QUALITYREASONCODE = 'PM'
            AND COMPANYCODE = '100'
        GROUP BY DEMANDCODE
    ),
    STSJ AS (
		SELECT 
			DMN.CODE AS DEMANDCODE,
			CASE 
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND COALESCE(JML25PM.JML, 0) > 0 THEN 'tidak'
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND TRIM(DMN.STSMC) = '2' THEN 'tidak'
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND TRIM(DMN.STSMC) = '4' THEN 'tidak'
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND TRIM(DMN.STSMC) = '5' THEN 'tidak'
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND TRIM(DMN.STSMC) = '3' THEN 'tidak'
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND TRIM(DMN.STSMC) = '1' AND COALESCE(ROUND(KGPAKAI.KGPAKAI), 0) = 0 THEN 'tidak'
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND TRIM(DMN.STSMC) = '1' AND COALESCE(ROUND(KGPAKAI.KGPAKAI), 0) > 0 AND COALESCE(JML251.JML, 0) = 0 THEN 'tidak'
				WHEN (DMN.PROGRESSSTATUS = '6' AND DMN.STSOPR = '1' AND COALESCE(JML251.JML, 0) > 0) THEN 'ya'
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND TRIM(DMN.STSMC) IN ('0', '1') AND COALESCE(JML251.JML, 0) > 0 THEN 'ya'
				WHEN (DMN.PRODUCTIONORDERCODE = '' AND DMN.CODE = '') THEN 'tidak'
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND TRIM(DMN.STSMC) = '0' AND COALESCE(ROUND(KGPAKAI.KGPAKAI), 0) = 0 THEN 'tidak'
				ELSE 'tidak'
			END AS STSJALAN
		FROM DMN
		LEFT JOIN JML25PM ON JML25PM.DEMANDCODE = DMN.CODE
		LEFT JOIN JML251 ON JML251.DEMANDCODE = DMN.CODE
		LEFT JOIN KGPAKAI ON KGPAKAI.PRODUCTIONORDERCODE = DMN.PRODUCTIONORDERCODE
    ),
    STSSTATUS AS (
		SELECT 
			DMN.CODE AS DEMANDCODE,
			CASE 
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND COALESCE(JML25PM.JML, 0) > 0 -- progress status demand 2, status oper 1, ELEMENT inspection 0
					THEN 'Perbaikan Mesin'
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND TRIM(DMN.STSMC) = '2' 
					THEN 'Antri Mesin'
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND TRIM(DMN.STSMC) = '4' 
					THEN 'Habis Benang'
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND TRIM(DMN.STSMC) = '5' 
					THEN 'Tunggu Tes Quality'
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND TRIM(DMN.STSMC) = '3' 
					THEN 'Hold'
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND TRIM(DMN.STSMC) = '1' AND COALESCE(ROUND(KGPAKAI.KGPAKAI), 0) = 0 
					THEN 'Tunggu Pasang Benang'
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND TRIM(DMN.STSMC) = '1' AND COALESCE(ROUND(KGPAKAI.KGPAKAI), 0) > 0 AND COALESCE(JML251.JML, 0) = 0
					THEN 'Tunggu Setting'
				WHEN (DMN.PROGRESSSTATUS = '6' AND DMN.STSOPR = '1' AND COALESCE(JML251.JML, 0) > 0)
					THEN 'Sedang Jalan Oper PO'
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND TRIM(DMN.STSMC) IN ('0', '1') AND COALESCE(JML251.JML, 0) > 0
					THEN 'Sedang Jalan'
				WHEN DMN.PRODUCTIONORDERCODE = '' AND DMN.CODE <> ''
					THEN 'Planned'
				WHEN (DMN.PROGRESSSTATUS = '2' OR DMN.STSOPR = '1') AND TRIM(DMN.STSMC) = '0' AND COALESCE(ROUND(KGPAKAI.KGPAKAI), 0) = 0
					THEN 'ProdOrdCreate'
				ELSE 'Tidak Ada PO'
			END AS STATUSMESIN
		FROM DMN
		LEFT JOIN JML25PM ON JML25PM.DEMANDCODE = DMN.CODE
		LEFT JOIN JML251 ON JML251.DEMANDCODE = DMN.CODE
		LEFT JOIN KGPAKAI ON KGPAKAI.PRODUCTIONORDERCODE = DMN.PRODUCTIONORDERCODE
    )
    -- FINAL SELECT dibungkus dan difilter
    SELECT 
		*
    FROM (
        SELECT
            TRIM(UG.CODE) AS KDMC,
            TRIM(DMN.PRODUCTIONDEMANDCODE) AS PRODUCTIONDEMANDCODE,
            TRIM(STSSTATUS.STATUSMESIN) AS STATUSMESIN,
--			VARCHAR_FORMAT(
--			DATE(DMN.TGLS) + 
--				ROUND(
--					CAST(
--						(COALESCE(DMN.BASEPRIMARYQUANTITY, 0.00) + COALESCE(DMN.QTYOPOUT, 0.00)) -
--						(COALESCE(DMN.QTYSALIN, 0.00) + COALESCE(DMN.QTYOPIN, 0.00)) -
--						COALESCE(J2.JQTY, 0.00)
--					AS DECIMAL) / NULLIF(ROUND(STDR.STDRAJUT, 0), 0)) DAYS, 'YYYY-MM-DD' ) AS ESTIMASI_SELESAI,
            VARCHAR_FORMAT(
			DATE(DMN.TGLS) + 
				CEILING(
					CAST((COALESCE(DMN.BASEPRIMARYQUANTITY, 0.00) + COALESCE(DMN.QTYOPOUT, 0.00)) AS DECIMAL) / NULLIF(ROUND(STDR.STDRAJUT, 0), 0)) DAYS - 1 DAYS, 'YYYY-MM-DD' ) AS ESTIMASI_SELESAI,
--			CAST( (COALESCE(DMN.BASEPRIMARYQUANTITY, 0.00) + COALESCE(DMN.QTYOPOUT, 0.00)) AS DECIMAL ),
--			NULLIF(ROUND(STDR.STDRAJUT, 0), 0),
            TRIM(DMN.SUBCODE01) AS SUBCODE01,
		    TRIM(DMN.SUBCODE02) AS SUBCODE02,
		    TRIM(DMN.SUBCODE03) AS SUBCODE03,
		    TRIM(DMN.SUBCODE04) AS SUBCODE04,
		    COALESCE(DMN.BASEPRIMARYQUANTITY, 0.00) + COALESCE(DMN.QTYOPOUT, 0.00) AS QTY_ORDER,
		    CAST(
				(COALESCE(DMN.BASEPRIMARYQUANTITY, 0.00) + COALESCE(DMN.QTYOPOUT, 0.00)) -
				(COALESCE(DMN.QTYSALIN, 0.00) + COALESCE(DMN.QTYOPIN, 0.00)) -
				COALESCE(J2.JQTY, 0.00)
			AS DECIMAL) AS QTY_SISA,
			ROUND(STDR.STDRAJUT, 0) AS STANDAR_RAJUT,
			TGL_START,
		    TGLDELIVERY,
			TGLMULAI,
			TRIM(DMN.STSMC) AS STSMC
        FROM 
        	DB2ADMIN.USERGENERICGROUP UG
        LEFT JOIN DMN ON DMN.VALUESTRING = UG.CODE
        LEFT JOIN J1 ON J1.DEMANDCODE = DMN.CODE
        LEFT JOIN J2 ON J2.DEMANDCODE = DMN.CODE
        LEFT JOIN STDR ON STDR.SUBCODE02 = DMN.SUBCODE02 AND STDR.SUBCODE03 = DMN.SUBCODE03 AND STDR.SUBCODE04 = DMN.SUBCODE04
        LEFT JOIN JML251 ON JML251.DEMANDCODE = DMN.CODE
        LEFT JOIN KGPAKAI ON KGPAKAI.PRODUCTIONORDERCODE = DMN.PRODUCTIONORDERCODE
        LEFT JOIN JML25PM ON JML25PM.DEMANDCODE = DMN.CODE
        LEFT JOIN STSJ ON STSJ.DEMANDCODE = DMN.CODE
        LEFT JOIN STSSTATUS ON STSSTATUS.DEMANDCODE = DMN.CODE 
        WHERE 
            UG.USERGENERICGROUPTYPECODE = 'MCK'
            AND UG.USERGENGROUPTYPECOMPANYCODE = '100'
            AND UG.OWNINGCOMPANYCODE = '100'
        ORDER BY UG.CODE, TGLDELIVERY ASC
    ) AS FINALQ
WHERE 
	FINALQ.STATUSMESIN = 'Sedang Jalan' OR
	FINALQ.STATUSMESIN = 'Sedang Jalan Oper PO' OR
    FINALQ.STSMC IN ('1','2','3','4','5');
   
	CALL DB2ADMIN.SP_REFRESH_ITXTEMP_SCHEDULE_KNT();