SELECT DISTINCT
	p.ORDERDATE
FROM
    PRODUCTIONDEMAND p
LEFT JOIN ADSTORAGE a4 ON a4.UNIQUEID = p.ABSUNIQUEID AND a4.FIELDNAME = 'MachineNoCode'
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p.ABSUNIQUEID AND a.FIELDNAME = 'StatusRMP'
WHERE
    p.ITEMTYPEAFICODE = 'KGF'
    AND p.PROGRESSSTATUS != '6'
--    AND p.SUBCODE02 = 'MTR'
--    AND p.SUBCODE03 = '21120'
--    AND p.SUBCODE03 = 'L02'
    AND a4.VALUESTRING IS NULL
	AND a.VALUESTRING IN ('1', '4')
    
    
SELECT
	p.CODE,
	a4.VALUESTRING AS NO_MESIN,
	p.ORDERDATE,
	a.VALUESTRING AS STATUSRMP,
    TRIM(p.SUBCODE02) AS SUBCODE02,
    TRIM(p.SUBCODE03) AS SUBCODE03,
    TRIM(p.SUBCODE04) AS SUBCODE04,
    SUM(p.BASEPRIMARYQUANTITY) AS QTY_TOTAL,
    SUM(a3.VALUEDECIMAL) AS QTYSALIN
FROM
    PRODUCTIONDEMAND p
LEFT JOIN ADSTORAGE a4 ON a4.UNIQUEID = p.ABSUNIQUEID AND a4.FIELDNAME = 'MachineNoCode'
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p.ABSUNIQUEID AND a.FIELDNAME = 'StatusRMP'
LEFT JOIN ADSTORAGE a3 ON p.ABSUNIQUEID = a3.UNIQUEID AND a3.NAMENAME = 'QtySalin'
WHERE
    p.ITEMTYPEAFICODE = 'KGF'
    AND p.PROGRESSSTATUS != '6'
--    AND p.SUBCODE02 = 'MTR'
--    AND p.SUBCODE03 = '21120'
--    AND p.SUBCODE03 = 'L02'
    AND a4.VALUESTRING IS NULL
	AND a.VALUESTRING IN ('1', '4')
GROUP BY
	p.CODE,
	a4.VALUESTRING,
	a.VALUESTRING,
	p.ORDERDATE,
    p.SUBCODE02,
    p.SUBCODE03,
    p.SUBCODE04