-- yang ini minta perhari dikirim datanya 
SELECT
    p.PRODUCTIONORDERCODE,
    iptip.MULAI,
    iptop.SELESAI,
    p2.SUBCODE02,
    p2.SUBCODE03,
    TRIM(p.OPERATIONCODE) AS OPERATIONCODE,
    p4.MACHINECODE,
    TRIM(o.OPERATIONGROUPCODE) AS DEPT,
    TIMESTAMPDIFF(2, CHAR(TIMESTAMP(iptop.SELESAI) - TIMESTAMP(iptip.MULAI))) / 3600 AS JAM,
    MOD((TIMESTAMPDIFF(2, CHAR(TIMESTAMP(iptop.SELESAI) - TIMESTAMP(iptip.MULAI))) / 60), 60) AS MENIT,
    MOD(TIMESTAMPDIFF(2, CHAR(TIMESTAMP(iptop.SELESAI) - TIMESTAMP(iptip.MULAI))), 60) AS DETIK,
    p3.PRIMARYQTY 
FROM 
    PRODUCTIONDEMANDSTEP p 
LEFT JOIN OPERATION o ON o.CODE = p.OPERATIONCODE 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = o.ABSUNIQUEID AND a.FIELDNAME = 'Gerobak'
LEFT JOIN ITXVIEW_POSISIKK_TGL_IN_PRODORDER iptip ON iptip.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND iptip.DEMANDSTEPSTEPNUMBER = p.STEPNUMBER
LEFT JOIN ITXVIEW_POSISIKK_TGL_OUT_PRODORDER iptop ON iptop.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND iptop.DEMANDSTEPSTEPNUMBER = p.STEPNUMBER
LEFT JOIN PRODUCTIONDEMAND p2 ON p2.CODE = p.PRODUCTIONDEMANDCODE
LEFT JOIN PRODUCTIONPROGRESSSTEPUPDATED p3 ON p3.PROPROGRESSPROGRESSNUMBER = iptop.PROPROGRESSPROGRESSNUMBER 
LEFT JOIN PRODUCTIONPROGRESS p4 ON p4.PROGRESSNUMBER = p3.PROPROGRESSPROGRESSNUMBER 
WHERE
--    p.PRODUCTIONORDERCODE  = '00116612' AND p.PRODUCTIONDEMANDCODE = '00211988'
	iptip.MULAI BETWEEN '2024-02-01' AND '2024-02-02'
    AND o.OPERATIONGROUPCODE = 'BRS'
    AND p2.SUBCODE02 IN ('MTR', 'F3C','DKF')
    AND p2.SUBCODE03 IN ('21120','11381','17109','20033','9050','20069','19106','14271','20069')
GROUP BY
    p.PRODUCTIONORDERCODE,
    p2.SUBCODE02,
    p2.SUBCODE03,
    p.STEPNUMBER,
    p.OPERATIONCODE,
    p4.MACHINECODE,
    o.OPERATIONGROUPCODE,
    iptip.MULAI,
    iptop.SELESAI,
    p3.PRIMARYQTY 
ORDER BY 
	p.STEPNUMBER 
ASC


-- cek kk yang mau ke brushing
SELECT
    p.PRODUCTIONORDERCODE,
    iptip.MULAI,
    iptop.SELESAI,
    p2.SUBCODE02,
    p2.SUBCODE03,
    TRIM(p.OPERATIONCODE) AS OPERATIONCODE,
    p4.MACHINECODE,
    TRIM(o.OPERATIONGROUPCODE) AS DEPT,
    TIMESTAMPDIFF(2, CHAR(TIMESTAMP(iptop.SELESAI) - TIMESTAMP(iptip.MULAI))) / 3600 AS JAM,
    MOD((TIMESTAMPDIFF(2, CHAR(TIMESTAMP(iptop.SELESAI) - TIMESTAMP(iptip.MULAI))) / 60), 60) AS MENIT,
    MOD(TIMESTAMPDIFF(2, CHAR(TIMESTAMP(iptop.SELESAI) - TIMESTAMP(iptip.MULAI))), 60) AS DETIK,
    p3.PRIMARYQTY,
    SUBSTR(p2.SUBCODE06, 1,1)
FROM 
    PRODUCTIONDEMANDSTEP p 
LEFT JOIN OPERATION o ON o.CODE = p.OPERATIONCODE 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = o.ABSUNIQUEID AND a.FIELDNAME = 'Gerobak'
LEFT JOIN ITXVIEW_POSISIKK_TGL_IN_PRODORDER iptip ON iptip.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND iptip.DEMANDSTEPSTEPNUMBER = p.STEPNUMBER
LEFT JOIN ITXVIEW_POSISIKK_TGL_OUT_PRODORDER iptop ON iptop.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND iptop.DEMANDSTEPSTEPNUMBER = p.STEPNUMBER
LEFT JOIN PRODUCTIONDEMAND p2 ON p2.CODE = p.PRODUCTIONDEMANDCODE
LEFT JOIN PRODUCTIONPROGRESSSTEPUPDATED p3 ON p3.PROPROGRESSPROGRESSNUMBER = iptop.PROPROGRESSPROGRESSNUMBER 
LEFT JOIN PRODUCTIONPROGRESS p4 ON p4.PROGRESSNUMBER = p3.PROPROGRESSPROGRESSNUMBER 
WHERE
--    p.PRODUCTIONORDERCODE  = '00121498' AND p.PRODUCTIONDEMANDCODE IN ('00213426','00220033')
	iptip.MULAI BETWEEN '2024-02-28' AND '2024-02-29'
    AND o.OPERATIONGROUPCODE = 'QC'
    AND iptop.SELESAI IS NULL
    AND p2.SUBCODE02 IN ('MTR', 'F3C','DKF')
    AND p2.SUBCODE03 IN ('21120','11381','17109','20033','9050','20069','19106','14271','20069')
    AND SUBSTR(p2.SUBCODE06, 1,1) = 'B'
GROUP BY
    p.PRODUCTIONORDERCODE,
    p2.SUBCODE02,
    p2.SUBCODE03,
    p2.SUBCODE06,
    p.STEPNUMBER,
    p.OPERATIONCODE,
    p4.MACHINECODE,
    o.OPERATIONGROUPCODE,
    iptip.MULAI,
    iptop.SELESAI,
    p3.PRIMARYQTY 
ORDER BY p.STEPNUMBER ASC

