SELECT
	p.WAREHOUSECODE,
	l.LONGDESCRIPTION,
	CASE
		WHEN p.WAREHOUSECODE = 'M031' THEN 'GKJ'
		WHEN p.WAREHOUSECODE = 'M039' THEN 'QCF/PRT'
		WHEN p.WAREHOUSECODE = 'M021' THEN 'GKG'
	END AS DEPT
FROM
	PRODUCTIONRESERVATION p 
LEFT JOIN LOGICALWAREHOUSE l ON l.CODE = p.WAREHOUSECODE 
WHERE
	TRIM( p.PRODUCTIONORDERCODE ) = '00032770' 
	AND (
	p.ITEMTYPEAFICODE = 'KGF' 
	OR p.ITEMTYPEAFICODE = 'KFF')