-- TRUNCATE table
TRUNCATE TABLE DB2ADMIN.SCHEDULE_KNITING_ALL_STAGING IMMEDIATE;

INSERT INTO DB2ADMIN.SCHEDULE_KNITING_ALL_STAGING (
    LANGGANAN,
	KATEGORI,
	PROJECT,
	ORIGINAL_PDCODE,
	ARTICLE_CODE,
	UKURAN_MESIN,
	TOTAL_QTY,
	MACHINE,
	TOTAL_MACHINE,
	STD_QTY_PERMACHINE,
	CAPACITY_PERDAY,
	QTY_PRODUC_YESTERDAY,
	PERSENTASE_TARGET,
	PRODUCED,
	BELUM_RAJUT,
	PERSENTASE_SETELAH_PROD,
	ESTIMATED_COMPLETED,
	ESTIMATED_DELIVERY,
	DELIVERY_ACTUAL,
	SUBCODE01,
	SUBCODE02,
	SUBCODE03,
	SUBCODE04
)
SELECT
	*
FROM
	ITXVIEWSCHEDULE_KNITING_ALL;
   
CALL DB2ADMIN.SP_REFRESH_SCHEDULE_KNT_ALL();