SELECT 
	p.STEPNUMBER,
	ip.LANGGANAN,
	TRIM(p.OPERATIONCODE) AS OPERATIONCODE,
	p2.DESCRIPTION AS LOT,
	p.PRODUCTIONORDERCODE,
	p.PRODUCTIONDEMANDCODE,
	p2.ORIGDLVSALORDLINESALORDERCODE,
	p2.SUBCODE05 AS NO_WARNA,
	i.WARNA,
	iptip.MULAI,
	CASE
		WHEN TRIM(o.EXTERNALITEMCODE) IS NULL THEN '-'
		ELSE TRIM(o.EXTERNALITEMCODE)
	END || ' / '|| 
	TRIM(p2.SUBCODE01) || '-' || TRIM(p2.SUBCODE02) || '-' || 
	TRIM(p2.SUBCODE03) || '-' || TRIM(p2.SUBCODE04) || '-' ||
	TRIM(p2.SUBCODE05) || '-' || TRIM(p2.SUBCODE06) || '-' || 
	TRIM(p2.SUBCODE07) || '-' || TRIM(p2.SUBCODE08) AS PRODUCT_NUMBER,
	CASE
		WHEN PRODUCT.LONGDESCRIPTION IS NULL THEN s2.ITEMDESCRIPTION
		ELSE PRODUCT.LONGDESCRIPTION
	END || ' ' || 
	CASE
		WHEN TRIM(s.INTERNALREFERENCE) IS NULL THEN '-'
		ELSE TRIM(s.INTERNALREFERENCE)
	END AS ITEMDESCRIPTION
FROM 
	ITXVIEW_POSISIKK_TGL_IN_PRODORDER iptip
LEFT JOIN PRODUCTIONDEMANDSTEP p ON p.PRODUCTIONORDERCODE = iptip.PRODUCTIONORDERCODE AND p.STEPNUMBER = iptip.DEMANDSTEPSTEPNUMBER
LEFT JOIN OPERATION o ON o.CODE = p.OPERATIONCODE
LEFT JOIN PRODUCTIONDEMAND p2 ON p2.CODE = p.PRODUCTIONDEMANDCODE 
LEFT JOIN ITXVIEWCOLOR i ON i.ITEMTYPECODE = p2.ITEMTYPEAFICODE
	AND i.SUBCODE01 = p2.SUBCODE01
	AND i.SUBCODE02 = p2.SUBCODE02
	AND i.SUBCODE03 = p2.SUBCODE03
	AND i.SUBCODE04 = p2.SUBCODE04
	AND i.SUBCODE05 = p2.SUBCODE05
	AND i.SUBCODE06 = p2.SUBCODE06
	AND i.SUBCODE07 = p2.SUBCODE07
	AND i.SUBCODE08 = p2.SUBCODE08
	AND i.SUBCODE09 = p2.SUBCODE09
	AND i.SUBCODE10 = p2.SUBCODE10
LEFT JOIN SALESORDER s ON s.CODE = p2.ORIGDLVSALORDLINESALORDERCODE 
LEFT JOIN SALESORDERLINE s2 ON s2.SALESORDERCODE = p2.ORIGDLVSALORDLINESALORDERCODE AND s2.ORDERLINE = p2.ORIGDLVSALORDERLINEORDERLINE
LEFT JOIN ORDERITEMORDERPARTNERLINK o ON o.INACTIVE = 0
	AND o.ORDPRNCUSTOMERSUPPLIERCODE = s.ORDPRNCUSTOMERSUPPLIERCODE
	AND o.ITEMTYPEAFICODE = p2.ITEMTYPEAFICODE
	AND o.SUBCODE01 = p2.SUBCODE01
	AND o.SUBCODE02 = p2.SUBCODE02
	AND o.SUBCODE03 = p2.SUBCODE03
	AND o.SUBCODE04 = p2.SUBCODE04
	AND o.SUBCODE05 = p2.SUBCODE05
	AND o.SUBCODE06 = p2.SUBCODE06
	AND o.SUBCODE07 = p2.SUBCODE07
	AND o.SUBCODE08 = p2.SUBCODE08
	AND o.SUBCODE09 = p2.SUBCODE09
	AND o.SUBCODE10 = p2.SUBCODE10
LEFT JOIN PRODUCT PRODUCT ON PRODUCT.ITEMTYPECODE = p2.ITEMTYPEAFICODE
	AND PRODUCT.SUBCODE01 = p2.SUBCODE01
	AND PRODUCT.SUBCODE02 = p2.SUBCODE02
	AND PRODUCT.SUBCODE03 = p2.SUBCODE03
	AND PRODUCT.SUBCODE04 = p2.SUBCODE04
	AND PRODUCT.SUBCODE05 = p2.SUBCODE05
	AND PRODUCT.SUBCODE06 = p2.SUBCODE06
	AND PRODUCT.SUBCODE07 = p2.SUBCODE07
	AND PRODUCT.SUBCODE08 = p2.SUBCODE08
	AND PRODUCT.SUBCODE09 = p2.SUBCODE09
	AND PRODUCT.SUBCODE10 = p2.SUBCODE10
LEFT JOIN ITXVIEW_PELANGGAN ip ON ip.ORDPRNCUSTOMERSUPPLIERCODE = s.ORDPRNCUSTOMERSUPPLIERCODE 
								AND ip.CODE = s.CODE 
WHERE
	o.OPERATIONGROUPCODE = 'FIN' 
	AND	iptip.PROGRESSSTARTPROCESSDATE BETWEEN '2023-03-03' AND '2023-03-03'
	
	
SELECT 
	p.PRODUCTIONORDERCODE AS PRODUCTIONORDERCODE, 
	p.STEPNUMBER AS GROUPSTEPNUMBER,
	TRIM(p.PROGRESSSTATUS) AS PROGRESSSTATUS
FROM 
	PRODUCTIONDEMANDSTEP p
WHERE
	p.PRODUCTIONORDERCODE  = '00055465' 
 	AND p.PRODUCTIONDEMANDCODE = '00116321' 
	AND p.STEPNUMBER = '551'
ORDER BY p.STEPNUMBER DESC
LIMIT 1

SELECT 
	STEPNUMBER,
	TRIM(OPERATIONCODE) AS OPERATIONCODE,
	o.LONGDESCRIPTION AS LONGDESCRIPTION,
	PROGRESSSTATUS,
	CASE
		WHEN PROGRESSSTATUS = 0 THEN 'Entered'
		WHEN PROGRESSSTATUS = 1 THEN 'Planned'
		WHEN PROGRESSSTATUS = 2 THEN 'Progress'
		WHEN PROGRESSSTATUS = 3 THEN 'Closed'
	END AS STATUS_OPERATION
FROM 
	PRODUCTIONDEMANDSTEP p
LEFT JOIN OPERATION o ON o.CODE = p.OPERATIONCODE
WHERE 
	p.PRODUCTIONORDERCODE  = '00055465' 
 	AND p.PRODUCTIONDEMANDCODE = '00116321' 
	AND p.STEPNUMBER > '551'
ORDER BY 
	STEPNUMBER ASC 
LIMIT 1