-- AMBIL DATA RFDNYA DULU 
SELECT
--	DISTINCT 
	LISTAGG(DISTINCT '''' || TRIM(VIEWPRODUCTIONRESERVATION.GROUPLINE) || '''', ',') AS GROUPLINE
FROM
	VIEWPRODUCTIONRESERVATION VIEWPRODUCTIONRESERVATION
LEFT JOIN ITXVIEWKK i ON i.PRODUCTIONORDERCODE = VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE
LEFT JOIN ITXVIEW_RESERVATION ir ON ir.PRODRESERVATIONLINKGROUPCODE = VIEWPRODUCTIONRESERVATION.PRODRESERVATIONLINKGROUPCODE 
								AND ir.PRODUCTIONORDERCODE = VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE 
WHERE
	VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE = '00170680'
--	AND VIEWPRODUCTIONRESERVATION.GROUPLINE IN ('200')
	AND VIEWPRODUCTIONRESERVATION.ITEMTYPEAFICODE IN ('RFD')
	
	
-- HEADER 
SELECT
    DISTINCT 
    TRIM(VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE) AS DYELOT,
    VIEWPRODUCTIONRESERVATION.GROUPLINE AS REDYE,
    '1409' AS MACHINE,
    0 AS TYPEOFPROCEDURE,
    0 AS PROCEDURENO,
    0 AS COLOR,
    TRIM(VIEWPRODUCTIONRESERVATION.SUBCODE01) || '-' || TRIM(VIEWPRODUCTIONRESERVATION.SUFFIXCODE) AS RECIPENO,
    i.PROJECTCODE AS ORDERNO,
    i.ORDPRNCUSTOMERSUPPLIERCODE AS CUSTOMER,
    '' AS ARTICLE,
    TRIM(i.SUBCODE05) AS COLORNO,
    SUBSTR(TRIM(i.WARNA),1,20) AS WARNA,
    ir.INITIALUSERPRIMARYQUANTITY AS WEIGHT,
    0 AS LENGTH,
    VIEWPRODUCTIONRESERVATION.PICKUPQUANTITY AS LIQUORATIO,
    0 AS LIQUORQUANTITY,
    0 AS PUMPSPEED,
    0 AS REELSPEED,
    0 AS ABSORPTION
FROM
    VIEWPRODUCTIONRESERVATION
LEFT JOIN ITXVIEWKK i ON i.PRODUCTIONORDERCODE = VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE
LEFT JOIN ITXVIEW_RESERVATION ir ON ir.PRODRESERVATIONLINKGROUPCODE = VIEWPRODUCTIONRESERVATION.PRODRESERVATIONLINKGROUPCODE 
                                AND ir.PRODUCTIONORDERCODE = VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE 
WHERE
    VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE = '00175338'
    AND VIEWPRODUCTIONRESERVATION.GROUPLINE = '101'
	
-- DETAIL DYSTUFF	
SELECT
	ITXVIEWRESEP.RECIPENUMBERID,
	ITXVIEWRESEP.SUFFIXCODE,
	ITXVIEWRESEP.SUBCODE01,
	ITXVIEWRESEP.SUBCODE02,
	ITXVIEWRESEP.SUBCODE03,
	COALESCE(ITXVIEWRESEP2.GROUPNUMBER, ITXVIEWRESEP.GROUPNUMBER) AS GROUPNUMBER,
	CASE
		WHEN ITXVIEWRESEP.CODE = '' THEN COALESCE(ITXVIEWRESEP2.CODE, ITXVIEWRESEP.SUBCODE01_RESERVATION)
		ELSE ITXVIEWRESEP.CODE
	END	AS CODE,
	CASE
		WHEN ITXVIEWRESEP.SUBCODE = '' THEN ITXVIEWRESEP2.SUBCODE
		ELSE ITXVIEWRESEP.SUBCODE
	END	AS SUBCODE,
	CASE
		WHEN ITXVIEWRESEP.COMMENTLINE IS NULL OR ITXVIEWRESEP.COMMENTLINE = '' THEN ITXVIEWRESEP2.COMMENTLINE
		ELSE ITXVIEWRESEP.COMMENTLINE
	END	AS COMMENTLINE,
	CASE
		WHEN ITXVIEWRESEP.LONGDESCRIPTION IS NULL OR ITXVIEWRESEP.LONGDESCRIPTION = '' THEN ITXVIEWRESEP2.LONGDESCRIPTION
		ELSE ITXVIEWRESEP.LONGDESCRIPTION
	END	AS LONGDESCRIPTION,
	CASE
		WHEN ITXVIEWRESEP.CONSUMPTION IS NULL OR ITXVIEWRESEP.CONSUMPTION = 0 THEN ITXVIEWRESEP2.CONSUMPTION
		ELSE ITXVIEWRESEP.CONSUMPTION
	END	AS CONSUMPTION,
	CASE
		WHEN 
			CASE
				WHEN ITXVIEWRESEP.CONSUMPTIONTYPE IS NULL OR ITXVIEWRESEP.CONSUMPTIONTYPE = '' THEN ITXVIEWRESEP2.CONSUMPTIONTYPE
				ELSE ITXVIEWRESEP.CONSUMPTIONTYPE
			END = '1' THEN 'g/l'
		WHEN
			CASE
				WHEN ITXVIEWRESEP.CONSUMPTIONTYPE IS NULL OR ITXVIEWRESEP.CONSUMPTIONTYPE = '' THEN ITXVIEWRESEP2.CONSUMPTIONTYPE
				ELSE ITXVIEWRESEP.CONSUMPTIONTYPE
			END = '2' THEN '%'
	END	AS CONSUMPTIONTYPE,
	CASE
        WHEN ITXVIEWRESEP.RECIPETYPE = '1' THEN CAST( ((ITXVIEWRESEP.PICKUPPERCENTAGE/100 * 1000) + ITXVIEWRESEP.RESIDUALBATHVOLUME) * ITXVIEWRESEP2.CONSUMPTION AS DECIMAL(18, 7))
        ELSE 
            CASE
                WHEN ITXVIEWRESEP2.CONSUMPTIONTYPE = '1' THEN CAST( ((1000 * VIEWPRODUCTIONRESERVATION.PICKUPQUANTITY) * ITXVIEWRESEP2.CONSUMPTION) / 1000 AS DECIMAL(18, 7))
                WHEN ITXVIEWRESEP2.CONSUMPTIONTYPE = '2' THEN CAST( (1000 * (ITXVIEWRESEP2.CONSUMPTION/100)) * 1000 AS DECIMAL(18, 7))
            END
    END AS QTY,
--	CASE
--        WHEN RECIPE.RECIPETYPE = '1' THEN 
--            CAST( (CAST(RECIPE.PICKUPPERCENTAGE AS DECIMAL(18,2))/100 * $dataMain[WEIGHT] + CAST(RECIPE.RESIDUALBATHVOLUME AS DECIMAL(18,2)) * ITXVIEWRESEP1.CONSUMPTION) / 1000 AS DECIMAL(18, 7))
--        ELSE 
--            CASE
--                WHEN TRIM(ITXVIEWRESEP1.CONSUMPTIONTYPE) = '1' THEN CAST( $dataMain[WEIGHT] * $dataMain[LIQUORATIO] * CAST(ITXVIEWRESEP1.CONSUMPTION AS DECIMAL(18,4)) / 1000 AS DECIMAL(18, 7))
--                WHEN TRIM(ITXVIEWRESEP1.CONSUMPTIONTYPE) = '2' THEN CAST( (($dataMain[WEIGHT] * (CAST(ITXVIEWRESEP1.CONSUMPTION AS DECIMAL(18,4)) / 100)) * 1000 )/ 1000 AS DECIMAL(18, 7))
--            END
--    END AS QTY,
	CASE 
		WHEN ITXVIEWRESEP2.CONSUMPTIONTYPE = '1' THEN 'Kg'
		WHEN ITXVIEWRESEP2.CONSUMPTIONTYPE = '2' THEN 'g'
	END AS UOM 
FROM
	VIEWPRODUCTIONRESERVATION VIEWPRODUCTIONRESERVATION
LEFT JOIN ITXVIEWRESEP ITXVIEWRESEP ON VIEWPRODUCTIONRESERVATION.SUFFIXCODE = ITXVIEWRESEP.SUFFIXCODE_RESERVATION
	AND VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE = ITXVIEWRESEP.PRODUCTIONORDERCODE
	AND VIEWPRODUCTIONRESERVATION.SUBCODE01 = ITXVIEWRESEP.SUBCODE01_RESERVATION
	AND VIEWPRODUCTIONRESERVATION.COMPANYCODE = ITXVIEWRESEP.COMPANYCODE
LEFT JOIN ITXVIEWRESEP2 ITXVIEWRESEP2 ON ITXVIEWRESEP2.RECIPESUBCODE01 = ITXVIEWRESEP.CODE AND ITXVIEWRESEP2.RECIPESUFFIXCODE = ITXVIEWRESEP.SUFFIXCODE
WHERE 
	VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE = '00175338'
	AND VIEWPRODUCTIONRESERVATION.GROUPLINE IN('101','200')
--	AND NOT 
--		CASE
--			WHEN 
--				CASE
--					WHEN ITXVIEWRESEP.CONSUMPTIONTYPE IS NULL OR ITXVIEWRESEP.CONSUMPTIONTYPE = '' THEN ITXVIEWRESEP2.CONSUMPTIONTYPE
--					ELSE ITXVIEWRESEP.CONSUMPTIONTYPE
--				END = '1' THEN 'g/l'
--			WHEN
--				CASE
--					WHEN ITXVIEWRESEP.CONSUMPTIONTYPE IS NULL OR ITXVIEWRESEP.CONSUMPTIONTYPE = '' THEN ITXVIEWRESEP2.CONSUMPTIONTYPE
--					ELSE ITXVIEWRESEP.CONSUMPTIONTYPE
--				END = '2' THEN '%'
--		END IS NULL 
ORDER BY
	ITXVIEWRESEP.RECIPENUMBERID,
	ITXVIEWRESEP.GROUPNUMBER,
	ITXVIEWRESEP.SEQUENCE,
	ITXVIEWRESEP2.GROUPNUMBER,
	ITXVIEWRESEP2.SEQUENCE ASC
	
	
-- DETAIL QTY PER-DYESTUFF
SELECT
	RECIPE.RECIPETYPE,
	RECIPE.PICKUPPERCENTAGE,
	RECIPE.RESIDUALBATHVOLUME,
	ITXVIEWRESEP1.RECIPENUMBERID,
	ITXVIEWRESEP1.GROUPNUMBER,
	ITXVIEWRESEP1.CONSUMPTION,
	ITXVIEWRESEP1.CONSUMPTIONTYPE,
	ITXVIEWRESEP1.SUBCODE01,
	ITXVIEWRESEP1.SUBCODE02,
	ITXVIEWRESEP1.SUBCODE03,
	CASE
	    WHEN RECIPE.RECIPETYPE = '1' THEN 
	       CAST( (CAST(RECIPE.PICKUPPERCENTAGE AS DECIMAL(18,2))/100 * 393.80 + 
	        CAST(RECIPE.RESIDUALBATHVOLUME AS DECIMAL(18,2)) * ITXVIEWRESEP1.CONSUMPTION) / 1000 AS DECIMAL(18, 4))
	    ELSE 
	        CASE
	            WHEN TRIM(ITXVIEWRESEP1.CONSUMPTIONTYPE) = '1' THEN CAST( 393.80 * 5.5 * CAST(ITXVIEWRESEP1.CONSUMPTION AS DECIMAL(18,4)) / 1000 AS DECIMAL(18,4))
	            WHEN TRIM(ITXVIEWRESEP1.CONSUMPTIONTYPE) = '2' THEN CAST( (393.80 * (CAST(ITXVIEWRESEP1.CONSUMPTION AS DECIMAL(18,4)) / 100)) * 1000 AS DECIMAL(18, 4))
	        END
	END AS QTY,
	CASE 
		WHEN ITXVIEWRESEP1.CONSUMPTIONTYPE = '1' THEN 'Kg'
		WHEN ITXVIEWRESEP1.CONSUMPTIONTYPE = '2' THEN 'g'
	END AS UOM 	
FROM
	RECIPE RECIPE
LEFT JOIN ITXVIEWRESEP1 ITXVIEWRESEP1 ON RECIPE.NUMBERID = ITXVIEWRESEP1.RECIPENUMBERID
WHERE 
	ITXVIEWRESEP1.RECIPENUMBERID = '156375'
	AND ITXVIEWRESEP1.SUBCODE01 = 'E'
	AND ITXVIEWRESEP1.SUBCODE02 = '1'
	AND ITXVIEWRESEP1.SUBCODE03 = '010'
	AND ITXVIEWRESEP1.GROUPNUMBER = '10'
	
-- DETAIL TOPPING/COMMENTLINT
SELECT 
    DISTINCT 
    * 
    FROM (SELECT
            ITXVIEWRESEP.RECIPENUMBERID, 
            ITXVIEWRESEP.GROUPNUMBER, 
            CASE
                WHEN CAST( LENGTH(ITXVIEWRESEP.SUBCODE01) AS VARCHAR(5)) = '1' THEN ITXVIEWRESEP.SUBCODE01_RESERVATION
                ELSE ITXVIEWRESEP.SUBCODE01
            END AS SUBCODE01,
            CASE
                WHEN CAST( LENGTH(ITXVIEWRESEP.SUBCODE01) AS VARCHAR(5)) = '1' THEN ITXVIEWRESEP.SUFFIXCODE_RESERVATION
                ELSE ITXVIEWRESEP.SUFFIXCODE
            END AS SUFFIXCODE
        FROM
            VIEWPRODUCTIONRESERVATION
        LEFT JOIN ITXVIEWRESEP ON VIEWPRODUCTIONRESERVATION.SUFFIXCODE = ITXVIEWRESEP.SUFFIXCODE_RESERVATION
            AND VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE = ITXVIEWRESEP.PRODUCTIONORDERCODE
            AND VIEWPRODUCTIONRESERVATION.SUBCODE01 = ITXVIEWRESEP.SUBCODE01_RESERVATION
            AND VIEWPRODUCTIONRESERVATION.COMPANYCODE = ITXVIEWRESEP.COMPANYCODE
        LEFT JOIN ITXVIEWRESEP2 ITXVIEWRESEP2 ON ITXVIEWRESEP2.RECIPESUBCODE01 = ITXVIEWRESEP.CODE AND ITXVIEWRESEP2.RECIPESUFFIXCODE = ITXVIEWRESEP.SUFFIXCODE
        WHERE 
            VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE = '00175338'
            AND VIEWPRODUCTIONRESERVATION.GROUPLINE IN ('101','200') 
            -- AND NOT 
            --     CASE
            --         WHEN 
            --             CASE
            --                 WHEN ITXVIEWRESEP.CONSUMPTIONTYPE IS NULL OR ITXVIEWRESEP.CONSUMPTIONTYPE = '' THEN ITXVIEWRESEP2.CONSUMPTIONTYPE
            --                 ELSE ITXVIEWRESEP.CONSUMPTIONTYPE
            --             END = '1' THEN 'g/l'
            --         WHEN
            --             CASE
            --                 WHEN ITXVIEWRESEP.CONSUMPTIONTYPE IS NULL OR ITXVIEWRESEP.CONSUMPTIONTYPE = '' THEN ITXVIEWRESEP2.CONSUMPTIONTYPE
            --                 ELSE ITXVIEWRESEP.CONSUMPTIONTYPE
            --             END = '2' THEN '%'
            --     END IS NULL 
        GROUP BY 
            ITXVIEWRESEP.RECIPENUMBERID,
            ITXVIEWRESEP.SUBCODE01,
            ITXVIEWRESEP.SUFFIXCODE,
            ITXVIEWRESEP.GROUPNUMBER,
            ITXVIEWRESEP.SUBCODE01_RESERVATION,
            ITXVIEWRESEP.SUFFIXCODE_RESERVATION 
        ORDER BY
            ITXVIEWRESEP.RECIPENUMBERID,
            ITXVIEWRESEP.GROUPNUMBER)	

-- DETAIL TREATMENT	
SELECT
	r.SUBCODE01,
	CAST(a.VALUEDECIMAL AS DECIMAL(4)) AS MAINPROGRAM
FROM
	RECIPE r 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = r.ABSUNIQUEID AND a.FIELDNAME = 'MainProgram1'
WHERE
	SUBCODE01 = 'SC3303' AND SUFFIXCODE = '001/SPD-+' AND NOT a.VALUEDECIMAL IS NULL
UNION ALL
SELECT
	r.SUBCODE01,
	CAST(a2.VALUEDECIMAL AS DECIMAL(4)) AS MAINPROGRAM
FROM
	RECIPE r 
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = r.ABSUNIQUEID AND a2.FIELDNAME = 'CoolingProgram1'
WHERE
	SUBCODE01 = 'SC3303' AND SUFFIXCODE = '001/SPD-+' AND NOT a2.VALUEDECIMAL IS NULL