SELECT 
    PRODUCTIONORDERCODE,
    REPLACE(LISTAGG( '`'|| PRODUCTIONDEMANDCODE || '`', ', '), '`', '''')  AS PRODUCTIONDEMANDCODE2,
    LISTAGG(PRODUCTIONDEMANDCODE, ', ')  AS PRODUCTIONDEMANDCODE,
    LISTAGG(TRIM(ORIGDLVSALORDLINESALORDERCODE), ', ')  AS ORIGDLVSALORDLINESALORDERCODE,
    LANGGANAN,
    STEPNUMBER,
    OPERATIONCODE,
    STATUS_OPERATION,
    HANGER,
    SUBCODE06,
    B,
    OPERATIONGROUPCODE
FROM
    (SELECT	
        TRIM(p.PRODUCTIONORDERCODE) AS PRODUCTIONORDERCODE,
        TRIM(p.PRODUCTIONDEMANDCODE) AS PRODUCTIONDEMANDCODE,
        p.STEPNUMBER,
        TRIM(p.OPERATIONCODE) AS OPERATIONCODE,
        CASE
            WHEN p.PROGRESSSTATUS = 0 THEN 'Entered'
            WHEN p.PROGRESSSTATUS = 1 THEN 'Planned'
            WHEN p.PROGRESSSTATUS = 2 THEN 'Progress'
            WHEN p.PROGRESSSTATUS = 3 THEN 'Closed'
        END AS STATUS_OPERATION,
        TRIM(o.OPERATIONGROUPCODE) AS OPERATIONGROUPCODE,
        TRIM(p2.SUBCODE02) || '-' || TRIM(p2.SUBCODE03) AS HANGER,
        TRIM(p2.SUBCODE06) AS SUBCODE06,
        SUBSTR(TRIM(p2.SUBCODE06), 1,1) AS B, 
        p2.ORIGDLVSALORDLINESALORDERCODE,
        ip.LANGGANAN || '(' || ip.BUYER || ')' AS LANGGANAN,
        ROW_NUMBER() OVER (PARTITION BY p.PRODUCTIONORDERCODE, p.PRODUCTIONDEMANDCODE ORDER BY p.STEPNUMBER) AS RN
    FROM
        PRODUCTIONDEMANDSTEP p
    LEFT JOIN OPERATION o ON o.CODE = p.OPERATIONCODE 
    LEFT JOIN PRODUCTIONDEMAND p2 ON p2.CODE = p.PRODUCTIONDEMANDCODE
    LEFT JOIN ITXVIEW_PELANGGAN ip ON ip.CODE = p2.ORIGDLVSALORDLINESALORDERCODE
    LEFT JOIN PRODUCTIONORDER p3 ON p3.CODE = p.PRODUCTIONORDERCODE
    WHERE 
        TRIM(p.PROGRESSSTATUS) IN ('2', '0')
        AND TRIM(o.OPERATIONGROUPCODE) = 'BRS'
        AND p.CREATIONDATETIME >= '2024-01-01'
        AND NOT p.PRODUCTIONORDERCODE IS NULL
        AND TRIM(DESTINATIONORDER) = '1'
        AND NOT p3.PROGRESSSTATUS = 6)
WHERE
    RN = 1
    AND NOT OPERATIONCODE = 'BAT1'
    AND B = 'B'
GROUP BY 
    PRODUCTIONORDERCODE,
    LANGGANAN,
    STEPNUMBER,
    OPERATIONCODE,
    STATUS_OPERATION,
    HANGER,
    SUBCODE06,
    B,
    OPERATIONGROUPCODE
    
    
    
 SELECT
    p.STEPNUMBER AS STEPNUMBER,
    TRIM(p.OPERATIONCODE) AS OPERATIONCODE,
    TRIM(o.OPERATIONGROUPCODE) AS DEPT,
    o.LONGDESCRIPTION,
    CASE
        WHEN p.PROGRESSSTATUS = 0 THEN 'Entered'
        WHEN p.PROGRESSSTATUS = 1 THEN 'Planned'
        WHEN p.PROGRESSSTATUS = 2 THEN 'Progress'
        WHEN p.PROGRESSSTATUS = 3 THEN 'Closed'
    END AS STATUS_OPERATION,
    iptip.MULAI,
    iptop.SELESAI,
    p.PRODUCTIONORDERCODE,
    p.PRODUCTIONDEMANDCODE,
    iptip.LONGDESCRIPTION AS OP1,
    iptop.LONGDESCRIPTION AS OP2,
    LISTAGG(FLOOR(idqd.VALUEQUANTITY), ', ') AS GEROBAK
FROM 
    PRODUCTIONDEMANDSTEP p 
LEFT JOIN OPERATION o ON o.CODE = p.OPERATIONCODE 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = o.ABSUNIQUEID AND a.FIELDNAME = 'Gerobak'
LEFT JOIN ITXVIEW_POSISIKK_TGL_IN_PRODORDER iptip ON iptip.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND iptip.DEMANDSTEPSTEPNUMBER = p.STEPNUMBER
LEFT JOIN ITXVIEW_POSISIKK_TGL_OUT_PRODORDER iptop ON iptop.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND iptop.DEMANDSTEPSTEPNUMBER = p.STEPNUMBER
LEFT JOIN ITXVIEW_DETAIL_QA_DATA idqd ON idqd.PRODUCTIONDEMANDCODE = p.PRODUCTIONDEMANDCODE AND idqd.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE
                                    AND idqd.OPERATIONCODE = p.OPERATIONCODE 
                                    AND (idqd.CHARACTERISTICCODE = 'GRB1' OR
                                        idqd.CHARACTERISTICCODE = 'GRB2' OR
                                        idqd.CHARACTERISTICCODE = 'GRB3' OR
                                        idqd.CHARACTERISTICCODE = 'GRB4' OR
                                        idqd.CHARACTERISTICCODE = 'GRB5' OR
                                        idqd.CHARACTERISTICCODE = 'GRB6' OR
                                        idqd.CHARACTERISTICCODE = 'GRB7' OR
                                        idqd.CHARACTERISTICCODE = 'GRB8')
                                    AND NOT (idqd.VALUEQUANTITY = 9 OR idqd.VALUEQUANTITY = 999 OR idqd.VALUEQUANTITY = 1 OR idqd.VALUEQUANTITY = 9999 OR idqd.VALUEQUANTITY = 99999 OR idqd.VALUEQUANTITY = 99 OR idqd.VALUEQUANTITY = 91)
WHERE
    p.PRODUCTIONORDERCODE  = '00120113' 
    AND p.PRODUCTIONDEMANDCODE IN ('00216472')
    AND p.STEPNUMBER < '150'
    -- AND a.VALUEBOOLEAN IS NULL
    AND (p.PROGRESSSTATUS = 1 OR p.PROGRESSSTATUS = 2 OR p.PROGRESSSTATUS = 3)
GROUP BY
    p.PRODUCTIONORDERCODE,
    p.STEPNUMBER,
    p.OPERATIONCODE,
    o.LONGDESCRIPTION,
    o.OPERATIONGROUPCODE,
    p.PROGRESSSTATUS,
    iptip.MULAI,
    iptop.SELESAI,
    p.PRODUCTIONORDERCODE,
    p.PRODUCTIONDEMANDCODE,
    iptip.LONGDESCRIPTION,
    iptop.LONGDESCRIPTION
ORDER BY 
    p.STEPNUMBER
DESC
LIMIT 1