SELECT
--    p.PRODUCTIONORDERCODE,
    p.STEPNUMBER AS STEPNUMBER,
    TRIM(p.OPERATIONCODE) AS OPERATIONCODE,
    TRIM(o.OPERATIONGROUPCODE) AS DEPT,
    o.LONGDESCRIPTION,
    CASE
        WHEN p.PROGRESSSTATUS = 0 THEN 'Entered'
        WHEN p.PROGRESSSTATUS = 1 THEN 'Planned'
        WHEN p.PROGRESSSTATUS = 2 THEN 'Progress'
        WHEN p.PROGRESSSTATUS = 3 THEN 'Closed'
    END AS STATUS_OPERATION,
    iptip.MULAI,
    iptop.SELESAI,
    p.PRODUCTIONORDERCODE,
    p.PRODUCTIONDEMANDCODE,
    iptip.LONGDESCRIPTION AS OP1,
    iptop.LONGDESCRIPTION AS OP2,
    LISTAGG(FLOOR(idqd.VALUEQUANTITY), ', ') AS GEROBAK
FROM 
    PRODUCTIONDEMANDSTEP p 
LEFT JOIN OPERATION o ON o.CODE = p.OPERATIONCODE 
LEFT JOIN ITXVIEW_POSISIKK_TGL_IN_PRODORDER iptip ON iptip.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND iptip.DEMANDSTEPSTEPNUMBER = p.STEPNUMBER
LEFT JOIN ITXVIEW_POSISIKK_TGL_OUT_PRODORDER iptop ON iptop.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND iptop.DEMANDSTEPSTEPNUMBER = p.STEPNUMBER
LEFT JOIN ITXVIEW_DETAIL_QA_DATA idqd ON idqd.PRODUCTIONDEMANDCODE = p.PRODUCTIONDEMANDCODE AND idqd.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE
									AND idqd.OPERATIONCODE = p.OPERATIONCODE 
									AND (idqd.CHARACTERISTICCODE = 'GRB1' OR
										idqd.CHARACTERISTICCODE = 'GRB2' OR
										idqd.CHARACTERISTICCODE = 'GRB3' OR
										idqd.CHARACTERISTICCODE = 'GRB4' OR
										idqd.CHARACTERISTICCODE = 'GRB5' OR
										idqd.CHARACTERISTICCODE = 'GRB6' OR
										idqd.CHARACTERISTICCODE = 'GRB7' OR
										idqd.CHARACTERISTICCODE = 'GRB8')
									AND NOT (idqd.VALUEQUANTITY = 9 OR idqd.VALUEQUANTITY = 999 OR idqd.VALUEQUANTITY = 1 OR idqd.VALUEQUANTITY = 9999 OR idqd.VALUEQUANTITY = 99999)
WHERE
    p.PRODUCTIONORDERCODE  = '00123776' AND p.PRODUCTIONDEMANDCODE = '00223511'
--    AND o.OPERATIONGROUPCODE = 'DYE'
--    AND p.OPERATIONCODE = 'DYE2'
    AND NOT idqd.VALUEQUANTITY IS NULL
GROUP BY
	p.PRODUCTIONORDERCODE,
    p.STEPNUMBER,
    p.OPERATIONCODE,
    o.LONGDESCRIPTION,
    o.OPERATIONGROUPCODE,
    p.PROGRESSSTATUS,
    iptip.MULAI,
    iptop.SELESAI,
    p.PRODUCTIONORDERCODE,
    p.PRODUCTIONDEMANDCODE,
    iptip.LONGDESCRIPTION,
    iptop.LONGDESCRIPTION
ORDER BY 
	p.STEPNUMBER
DESC
LIMIT 1

SELECT
	iptip.PROGRESSSTARTPROCESSDATE,
	p.PRODUCTIONORDERCODE,
	p.PRODUCTIONDEMANDCODE,
	p.OPERATIONCODE,
	p.PROGRESSSTATUS,
	o.OPERATIONGROUPCODE 
FROM
	ITXVIEW_POSISIKK_TGL_IN_PRODORDER iptip 
LEFT JOIN PRODUCTIONDEMANDSTEP p ON p.PRODUCTIONORDERCODE = iptip.PRODUCTIONORDERCODE AND p.STEPNUMBER = iptip.DEMANDSTEPSTEPNUMBER
LEFT JOIN OPERATION o ON o.CODE = p.OPERATIONCODE 
WHERE 
	PROGRESSSTARTPROCESSDATE BETWEEN '2024-02-17' AND '2024-02-19'
	AND PROGRESSSTATUS  ='2' 
--	AND OPERATIONGROUPCODE = 'DYE'