SELECT * FROM 
(SELECT DISTINCT
    PRODUCTIONORDERCODE,
    REPLACE(LISTAGG( '`'|| PRODUCTIONDEMANDCODE || '`', ', '), '`', '''')  AS PRODUCTIONDEMANDCODE2,
    LISTAGG(PRODUCTIONDEMANDCODE, ', ')  AS PRODUCTIONDEMANDCODE,
    STEPNUMBER,
    OPERATIONCODE,
    STATUS_OPERATION,
    HANGER,
    NO_WARNA,
    WARNA,
    SUBCODE06,
    OPERATIONGROUPCODE,
    ABSUNIQUEID_OPERATION,
    CREATIONDATETIME
FROM
    (SELECT	
        TRIM(p.PRODUCTIONORDERCODE) AS PRODUCTIONORDERCODE,
        TRIM(p.PRODUCTIONDEMANDCODE) AS PRODUCTIONDEMANDCODE,
        p.STEPNUMBER,
        TRIM(p.OPERATIONCODE) AS OPERATIONCODE,
        CASE
            WHEN p.PROGRESSSTATUS = 0 THEN 'Entered'
            WHEN p.PROGRESSSTATUS = 1 THEN 'Planned'
            WHEN p.PROGRESSSTATUS = 2 THEN 'Progress'
            WHEN p.PROGRESSSTATUS = 3 THEN 'Closed'
        END AS STATUS_OPERATION,
        TRIM(o.OPERATIONGROUPCODE) AS OPERATIONGROUPCODE,
        TRIM(p2.SUBCODE02) || '-' || TRIM(p2.SUBCODE03) AS HANGER,
        TRIM(p2.SUBCODE06) AS SUBCODE06,
        i.SUBCODE05 AS NO_WARNA,
        i.WARNA,
        ROW_NUMBER() OVER (PARTITION BY p.PRODUCTIONORDERCODE, p.PRODUCTIONDEMANDCODE ORDER BY p.STEPNUMBER) AS RN,
        o.ABSUNIQUEID AS ABSUNIQUEID_OPERATION,
        p2.CREATIONDATETIME
    FROM
        PRODUCTIONDEMANDSTEP p
    LEFT JOIN OPERATION o ON o.CODE = p.OPERATIONCODE 
    LEFT JOIN PRODUCTIONDEMAND p2 ON p2.CODE = p.PRODUCTIONDEMANDCODE
    LEFT JOIN ITXVIEWCOLOR i ON i.ITEMTYPECODE = p2.ITEMTYPEAFICODE
                            AND i.SUBCODE01 = p2.SUBCODE01
                            AND i.SUBCODE02 = p2.SUBCODE02
                            AND i.SUBCODE03 = p2.SUBCODE03
                            AND i.SUBCODE04 = p2.SUBCODE04
                            AND i.SUBCODE05 = p2.SUBCODE05
                            AND i.SUBCODE06 = p2.SUBCODE06
                            AND i.SUBCODE07 = p2.SUBCODE07
                            AND i.SUBCODE08 = p2.SUBCODE08
                            AND i.SUBCODE09 = p2.SUBCODE09
                            AND i.SUBCODE10 = p2.SUBCODE10
    WHERE 
        TRIM(p.PROGRESSSTATUS) IN ('0', '2')
        AND p.PRODUCTIONDEMANDCODE = '00284799'
        AND p2.CREATIONDATETIME >= '2023-11-01'
        AND NOT p.PRODUCTIONORDERCODE IS NULL
        AND (TRIM(p2.DESTINATIONORDER) = '1' OR NOT p2.PROJECTCODE IS NULL)
        )
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = ABSUNIQUEID_OPERATION AND a.FIELDNAME = 'Gerobak'
WHERE
    RN = 1
    AND NOT OPERATIONCODE = 'BAT1'
    AND TRIM(OPERATIONGROUPCODE) = 'DYE'
    AND STATUS_OPERATION IN ('Entered', 'Progress')
GROUP BY 
    PRODUCTIONORDERCODE,
    STEPNUMBER,
    OPERATIONCODE,
    STATUS_OPERATION,
    HANGER,
    NO_WARNA,
    WARNA,
    SUBCODE06,
    OPERATIONGROUPCODE,
    ABSUNIQUEID_OPERATION,
    CREATIONDATETIME
ORDER BY 
    OPERATIONGROUPCODE ASC)
WHERE NOT (OPERATIONCODE IN ('DYE1', 'DYE2', 'DYE4', 'SOA1', 'RDC1', 'LVL1', 'NEU1', 'CBL1', 'RLX1', 'FEW1', 'FIX1', 'HEW1', 'HOT1', 'SCO1', 'SCO2', 'SOF1', 'STR1') AND STATUS_OPERATION = 'Progress')




SELECT DISTINCT
    p.STEPNUMBER AS STEPNUMBER,
    CASE
        WHEN TRIM(p.PRODRESERVATIONLINKGROUPCODE) IS NULL OR TRIM(p.PRODRESERVATIONLINKGROUPCODE) = '' THEN TRIM(p.OPERATIONCODE)
        ELSE TRIM(p.PRODRESERVATIONLINKGROUPCODE)
    END AS OPERATIONCODE,
    TRIM(o.OPERATIONGROUPCODE) AS DEPT,
    o.LONGDESCRIPTION,
    CASE
        WHEN p.PROGRESSSTATUS = 0 THEN 'Entered'
        WHEN p.PROGRESSSTATUS = 1 THEN 'Planned'
        WHEN p.PROGRESSSTATUS = 2 THEN 'Progress'
        WHEN p.PROGRESSSTATUS = 3 THEN 'Closed'
    END AS STATUS_OPERATION,
    iptip.MULAI,
    CASE
        WHEN p.PROGRESSSTATUS = 3 THEN COALESCE(iptop.SELESAI, SUBSTRING(p.LASTUPDATEDATETIME, 1, 19) || '(Run Manual Closures)')
        ELSE iptop.SELESAI
    END AS SELESAI,
    p.PRODUCTIONORDERCODE,
    p.PRODUCTIONDEMANDCODE,
    iptip.LONGDESCRIPTION AS OP1,
    iptop.LONGDESCRIPTION AS OP2,
--    CASE
--    	WHEN LISTAGG(DISTINCT FLOOR(idqd.VALUEQUANTITY), ', ')= '1' THEN 'PLASTIK'
--    	WHEN LISTAGG(DISTINCT FLOOR(idqd.VALUEQUANTITY), ', ') = '2' THEN 'TONG'
--    	WHEN LISTAGG(DISTINCT FLOOR(idqd.VALUEQUANTITY), ', ') = '3' THEN 'DALAM MESIN'
--    	ELSE LISTAGG(DISTINCT FLOOR(idqd.VALUEQUANTITY), ', ')
--    END AS GEROBAK
FROM 
    PRODUCTIONDEMANDSTEP p 
LEFT JOIN OPERATION o ON o.CODE = p.OPERATIONCODE 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = o.ABSUNIQUEID AND a.FIELDNAME = 'Gerobak'
LEFT JOIN ITXVIEW_POSISIKK_TGL_IN_PRODORDER iptip ON iptip.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND iptip.DEMANDSTEPSTEPNUMBER = p.STEPNUMBER
LEFT JOIN ITXVIEW_POSISIKK_TGL_OUT_PRODORDER iptop ON iptop.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND iptop.DEMANDSTEPSTEPNUMBER = p.STEPNUMBER
LEFT JOIN ITXVIEW_DETAIL_QA_DATA idqd ON idqd.PRODUCTIONDEMANDCODE = p.PRODUCTIONDEMANDCODE AND idqd.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE
                                    AND idqd.OPERATIONCODE = CASE
                                                                WHEN TRIM(p.PRODRESERVATIONLINKGROUPCODE) IS NULL OR TRIM(p.PRODRESERVATIONLINKGROUPCODE) = '' THEN TRIM(p.OPERATIONCODE)
                                                                ELSE TRIM(p.PRODRESERVATIONLINKGROUPCODE)
                                                            END
                                    AND (idqd.VALUEINT = p.STEPNUMBER OR idqd.VALUEINT = p.GROUPSTEPNUMBER) 
                                    AND (idqd.CHARACTERISTICCODE = 'GRB1' OR
                                        idqd.CHARACTERISTICCODE = 'GRB2' OR
                                        idqd.CHARACTERISTICCODE = 'GRB3' OR
                                        idqd.CHARACTERISTICCODE = 'GRB4' OR
                                        idqd.CHARACTERISTICCODE = 'GRB5' OR
                                        idqd.CHARACTERISTICCODE = 'GRB6' OR
                                        idqd.CHARACTERISTICCODE = 'GRB7' OR
                                        idqd.CHARACTERISTICCODE = 'GRB8' OR
                                        idqd.CHARACTERISTICCODE = 'GRB9' OR
                                        idqd.CHARACTERISTICCODE = 'GRB10' OR
                                        idqd.CHARACTERISTICCODE = 'AREA')
                                    AND NOT (idqd.VALUEQUANTITY = 999 OR idqd.VALUEQUANTITY = 9999 OR idqd.VALUEQUANTITY = 99999 OR idqd.VALUEQUANTITY = 91)
WHERE
    p.PRODUCTIONORDERCODE  = '00163606' 
    AND p.PRODUCTIONDEMANDCODE IN ('00284799')
    AND p.STEPNUMBER < '232'
    AND NOT idqd.VALUEQUANTITY IS NULL
    AND (a.VALUEBOOLEAN IS NULL OR a.VALUEBOOLEAN = 0)
GROUP BY
    p.PRODUCTIONORDERCODE,
    p.STEPNUMBER,
    p.OPERATIONCODE,
    p.PRODRESERVATIONLINKGROUPCODE,
    o.OPERATIONGROUPCODE,
    o.LONGDESCRIPTION,
    p.PROGRESSSTATUS,
    iptip.MULAI,
    iptop.SELESAI,
    p.LASTUPDATEDATETIME,
    p.PRODUCTIONORDERCODE,
    p.PRODUCTIONDEMANDCODE,
    iptip.LONGDESCRIPTION,
    iptop.LONGDESCRIPTION
ORDER BY 
    p.STEPNUMBER
DESC
LIMIT 1