SELECT
	NO_BD,
	KEPALA_DEPT_PEMOHON,
	DIKETAHUI_OLEH_DIT,
	KEPALA_DEPT_USER_SELESAI,
	KEPALA_DEPT_DIT_SELESAI,
	DITERIMA_OLEH_DIT
FROM
	ITXVIEW_PPA_DIT
WHERE
	TGL_BUAT_BD >= '2024-06-01'
ORDER BY 
	TGL_BUAT_BD,
	KEPALA_DEPT_USER_SELESAI
ASC