SELECT
	b.LOTCODE,
	p.ORIGDLVSALORDLINESALORDERCODE,
	s.STATISTICALGROUPCODE,
	p.EXTERNALREFERENCE,
	b.LOGICALWAREHOUSECODE,
	SUM(BASEPRIMARYQUANTITYUNIT) AS Stock
FROM
	BALANCE b
LEFT JOIN PRODUCTIONDEMAND p ON p.CODE = b.LOTCODE 
LEFT JOIN SALESORDER s ON s.CODE = p.ORIGDLVSALORDLINESALORDERCODE 
WHERE
	b.DECOSUBCODE02 = 'F3C'
	AND b.DECOSUBCODE03 = '21001'
	AND b.LOGICALWAREHOUSECODE IN ('M021', 'M502')
GROUP BY
	b.LOTCODE,
	p.ORIGDLVSALORDLINESALORDERCODE,
	s.STATISTICALGROUPCODE,
	p.EXTERNALREFERENCE,
	b.LOGICALWAREHOUSECODE