-- RECIPE BEAN
	INSERT INTO RECIPEBEAN (
	    COMPANYCODE,
	    IMPORTAUTOCOUNTER,
	    DIVISIONCODE,
	    ALLOWEDDIVISIONS,
	    NUMBERID,
	    RECIPETEMPLATECODE,
	    ITEMTYPECODE,
	    RECIPETYPE,
	    SUBCODE01,
	    SUBCODE02,
	    SUBCODE03,
	    SUBCODE04,
	    SUBCODE05,
	    SUBCODE06,
	    SUBCODE07,
	    SUBCODE08,
	    SUBCODE09,
	    SUBCODE10,
	    SUFFIXCODE,
	    GENERICRECIPE,
	    LONGDESCRIPTION,
	    SHORTDESCRIPTION,
	    SEARCHDESCRIPTION,
	    REFSUBCODE01,
	    REFSUBCODE02,
	    REFSUBCODE03,
	    REFSUBCODE04,
	    REFSUBCODE05,
	    REFSUBCODE06,
	    REFSUBCODE07,
	    REFSUBCODE08,
	    REFSUBCODE09,
	    REFSUBCODE10,
	    REFRECIPESUFFIXCODE,
	    REFRECIPENUMBERID,
	    GENERICREFERENCE,
	    VALIDFROMDATE,
	    VALIDTODATE,
	    LIMITINPOBYNUMBEROFUSES,
	    MAXNUMBEROFUSES,
	    NUMBEROFUSES,
	    SOLUTIONPASTEUMCODE,
	    SOLUTIONPASTEWEIGHT,
	    RECIPEINCIDENCE,
	    SOLUTIONPASTEUMWEIGHTUMCODE,
	    PRODUCTIONUMCODE,
	    PRODUCTIONUMWEIGHT,
	    PRODUCTIONUMWEIGHTUMCODE,
	    BATCHSTANDARDSIZE,
	    AVERAGELENGTH,
	    BATCHAVERAGEUMCODE,
	    DILUITIONPERCENTAGE,
	    PICKUPPERCENTAGE,
	    DRYRESIDUALPERCENTAGE,
	    DRYRESIDUALQUANTITY,
	    GLOBALWASTEPERCENTAGE,
	    BATHVOLUME,
	    RESIDUALBATHVOLUME,
	    VOLUMEUMCODE,
	    COMPOSITIONCODE,
	    LIQUORRATIO,
	    MIXVOLUME,
	    PRODUCTIONRESERVATIONGROUPCODE,
	    COSTGROUPCODE,
	    USESUBRECIPEHEADERVALUES,
	    BINDERFLUIDSRATIO,
	    BINDERMINPERCENTAGE,
	    BINDERITEMTYPECODE,
	    BSUBCODE01,
	    BSUBCODE02,
	    BSUBCODE03,
	    BSUBCODE04,
	    BSUBCODE05,
	    BSUBCODE06,
	    BSUBCODE07,
	    BSUBCODE08,
	    BSUBCODE09,
	    BSUBCODE10,
	    FILLERITEMTYPECODE,
	    FSUBCODE01,
	    FSUBCODE02,
	    FSUBCODE03,
	    FSUBCODE04,
	    FSUBCODE05,
	    FSUBCODE06,
	    FSUBCODE07,
	    FSUBCODE08,
	    FSUBCODE09,
	    FSUBCODE10,
	    BINDERGROUPNUMBER,
	    BINDERGROUPTYPECODE,
	    FILLERGROUPNUMBER,
	    FILLERGROUPTYPECODE,
	    TRANSLATEDLONGDESCRIPTION,
	    TRANSLATEDLANGUAGECODE,
	    TRANSLATEDSHORTDESCRIPTION,
	    STATUS,
	    APPROVALDATE,
	    APPROVALUSER,
	    CREATEHEADER,
	    WSOPERATION,
	    IMPOPERATIONUSER,
	    IMPORTSTATUS,
	    IMPCREATIONDATETIME,
	    IMPCREATIONUSER,
	    IMPLASTUPDATEDATETIME,
	    IMPLASTUPDATEUSER,
	    IMPORTDATETIME,
	    RETRYNR,
	    NEXTRETRY,
	    IMPORTID,
	    RELATEDDEPENDENTID,
	    FATHERID,
	    OWNEDCOMPONENT,
	    RECIPEITEMTYPECODE,
	    RECIPESUBCODE01,
	    RECIPESUBCODE02,
	    RECIPESUBCODE03,
	    RECIPESUBCODE04,
	    RECIPESUBCODE05,
	    RECIPESUBCODE06,
	    RECIPESUBCODE07,
	    RECIPESUBCODE08,
	    RECIPESUBCODE09,
	    RECIPESUBCODE10,
	    RECIPESUFFIXCODE,
	    GROUPNUMBER,
	    GROUPTYPECODE,
	    LINETYPE,
	    SEQUENCE,
	    ALTERNATIVE,
	    SUBSEQUENCE,
	    COMPONENTINCIDENCE,
	    REFRECIPEGROUPNUMBER,
	    REFRECIPESEQUENCE,
	    REFRECIPEALTERNATIVE,
	    REFRECIPESUBSEQUENCE,
	    REFRECIPESTATUS,
	    ITEMTYPEAFICODE,
	    COMMENTLINE,
	    CONSUMPTIONTYPE,
	    ASSEMBLYUOMCODE,
	    COMPONENTUOMCODE,
	    COMPONENTUOMTYPE,
	    CONSUMPTION,
	    COMPOSITIONCOMPONENTCODE,
	    CONSFORMIXLABEL,
	    CONSPERBATCHLABEL,
	    CONSPERLABEL,
	    WATERMANAGEMENT,
	    BINDERFILLERCOMPONENT,
	    PRODUCED,
	    PRICELISTCODE,
	    COSTINGPLANTCODE,
	    INITIALENGINEERINGCHANGE,
	    FINALENGINEERINGCHANGE,
	    INITIALDATE,
	    FINALDATE,
	    UNITARYBATCHSTANDARDSIZE,
	    ALLOWDELETEBINDERFILLER,
	    TOTALCOSTTEXT
	) VALUES (
	    '100', -- COMPANYCODE
	    '28092', -- IMPORTAUTOCOUNTER
	    '', -- DIVISIONCODE
	    NULL, -- ALLOWEDDIVISIONS
	    '28092', -- NUMBERID
	    'FD', -- RECIPETEMPLATECODE
	    'RFD', -- ITEMTYPECODE
	    '2', -- RECIPETYPE
	    '15233/230888L/R', -- SUBCODE01
	    '', -- SUBCODE02
	    '', -- SUBCODE03
	    '', -- SUBCODE04
	    '', -- SUBCODE05
	    '', -- SUBCODE06
	    '', -- SUBCODE07
	    '', -- SUBCODE08
	    '', -- SUBCODE09
	    '', -- SUBCODE10
	    '25011644L', -- SUFFIXCODE
	    '0', -- GENERICRECIPE
	    'LIGHT IVORY', -- LONGDESCRIPTION
	    'LIGHT IVORY', -- SHORTDESCRIPTION
	    'LIGHT IVORY', -- SEARCHDESCRIPTION
	    '', -- REFSUBCODE01
	    '', -- REFSUBCODE02
	    '', -- REFSUBCODE03
	    '', -- REFSUBCODE04
	    '', -- REFSUBCODE05
	    '', -- REFSUBCODE06
	    '', -- REFSUBCODE07
	    '', -- REFSUBCODE08
	    '', -- REFSUBCODE09
	    '', -- REFSUBCODE10
	    '', -- REFRECIPESUFFIXCODE
	    '0', -- REFRECIPENUMBERID
	    '', -- GENERICREFERENCE
	    '1970-01-01', -- VALIDFROMDATE
	    '2100-12-31', -- VALIDTODATE
	    '0', -- LIMITINPOBYNUMBEROFUSES
	    '0', -- MAXNUMBEROFUSES
	    '0', -- NUMBEROFUSES
	    'l', -- SOLUTIONPASTEUMCODE
	    '1', -- SOLUTIONPASTEWEIGHT
	    '100', -- RECIPEINCIDENCE
	    'kg', -- SOLUTIONPASTEUMWEIGHTUMCODE
	    'kg', -- PRODUCTIONUMCODE
	    '1', -- PRODUCTIONUMWEIGHT
	    'kg', -- PRODUCTIONUMWEIGHTUMCODE
	    '1000', -- BATCHSTANDARDSIZE
	    '0', -- AVERAGELENGTH
	    'kg', -- BATCHAVERAGEUMCODE
	    '0', -- DILUITIONPERCENTAGE
	    '0', -- PICKUPPERCENTAGE
	    '0', -- DRYRESIDUALPERCENTAGE
	    '0', -- DRYRESIDUALQUANTITY
	    '0', -- GLOBALWASTEPERCENTAGE
	    '1000', -- BATHVOLUME
	    '0', -- RESIDUALBATHVOLUME
	    'l', -- VOLUMEUMCODE
	    '', -- COMPOSITIONCODE
	    '12', -- LIQUORRATIO
	    '0', -- MIXVOLUME
	    '001', -- PRODUCTIONRESERVATIONGROUPCODE
	    '', -- COSTGROUPCODE
	    '0', -- USESUBRECIPEHEADERVALUES
	    '0', -- BINDERFLUIDSRATIO
	    '0', -- BINDERMINPERCENTAGE
	    '0', -- BINDERITEMTYPECODE
	    '', -- BSUBCODE01
	    '', -- BSUBCODE02
	    '', -- BSUBCODE03
	    '', -- BSUBCODE04
	    '', -- BSUBCODE05
	    '', -- BSUBCODE06
	    '', -- BSUBCODE07
	    '', -- BSUBCODE08
	    '', -- BSUBCODE09
	    '', -- BSUBCODE10
	    '', -- FILLERITEMTYPECODE
	    '', -- FSUBCODE01
	    '', -- FSUBCODE02
	    '', -- FSUBCODE03
	    '', -- FSUBCODE04
	    '', -- FSUBCODE05
	    '', -- FSUBCODE06
	    '', -- FSUBCODE07
	    '', -- FSUBCODE08
	    '', -- FSUBCODE09
	    '', -- FSUBCODE10
	    '0', -- BINDERGROUPNUMBER
	    '', -- BINDERGROUPTYPECODE
	    '0', -- FILLERGROUPNUMBER
	    '0', -- FILLERGROUPTYPECODE
	    NULL, -- TRANSLATEDLONGDESCRIPTION
	    NULL, -- TRANSLATEDLANGUAGECODE
	    NULL, -- TRANSLATEDSHORTDESCRIPTION
	    '2', -- STATUS
	    NULL, -- APPROVALDATE
	    '', -- APPROVALUSER
	    '1', -- CREATEHEADER
	    '5', -- WSOPERATION
	    'dit', -- IMPOPERATIONUSER
	    '0', -- IMPORTSTATUS
	    NULL, -- IMPCREATIONDATETIME
	    NULL, -- IMPCREATIONUSER
	    NULL, -- IMPLASTUPDATEDATETIME
	    NULL, -- IMPLASTUPDATEUSER
	    '2025-04-28 08:42:06', -- IMPORTDATETIME
	    '0', -- RETRYNR
	    '0', -- NEXTRETRY
	    '0', -- IMPORTID
	    '28092', -- RELATEDDEPENDENTID
	    NULL, -- FATHERID
	    NULL, -- OWNEDCOMPONENT
	    NULL, -- RECIPEITEMTYPECODE
	    NULL, -- RECIPESUBCODE01
	    NULL, -- RECIPESUBCODE02
	    NULL, -- RECIPESUBCODE03
	    NULL, -- RECIPESUBCODE04
	    NULL, -- RECIPESUBCODE05
	    NULL, -- RECIPESUBCODE06
	    NULL, -- RECIPESUBCODE07
	    NULL, -- RECIPESUBCODE08
	    NULL, -- RECIPESUBCODE09
	    NULL, -- RECIPESUBCODE10
	    NULL, -- RECIPESUFFIXCODE
	    NULL, -- GROUPNUMBER
	    NULL, -- GROUPTYPECODE
	    NULL, -- LINETYPE
	    NULL, -- SEQUENCE
	    NULL, -- ALTERNATIVE
	    NULL, -- SUBSEQUENCE
	    NULL, -- COMPONENTINCIDENCE
	    NULL, -- REFRECIPEGROUPNUMBER
	    NULL, -- REFRECIPESEQUENCE
	    NULL, -- REFRECIPEALTERNATIVE
	    NULL, -- REFRECIPESUBSEQUENCE
	    NULL, -- REFRECIPESTATUS
	    NULL, -- ITEMTYPEAFICODE
	    NULL, -- COMMENTLINE
	    NULL, -- CONSUMPTIONTYPE
	    NULL, -- ASSEMBLYUOMCODE
	    NULL, -- COMPONENTUOMCODE
	    NULL, -- COMPONENTUOMTYPE
	    NULL, -- CONSUMPTION
	    NULL, -- COMPOSITIONCOMPONENTCODE
	    NULL, -- CONSFORMIXLABEL
	    NULL, -- CONSPERBATCHLABEL
	    NULL, -- CONSPERLABEL
	    NULL, -- WATERMANAGEMENT
	    NULL, -- BINDERFILLERCOMPONENT
	    NULL, -- PRODUCED
	    NULL, -- PRICELISTCODE
	    NULL, -- COSTINGPLANTCODE
	    NULL, -- INITIALENGINEERINGCHANGE
	    NULL, -- FINALENGINEERINGCHANGE
	    NULL, -- INITIALDATE
	    NULL, -- FINALDATE
	    NULL, -- UNITARYBATCHSTANDARDSIZE
	    NULL, -- ALLOWDELETEBINDERFILLER
	    NULL -- TOTALCOSTTEXT
	)

--	RECIPE COMPONENT BEAN
