UPDATE 
	PRODUCTIONORDER 
SET 
	PROGRESSSTATUS = '1',
	LASTUPDATEUSER = ''
WHERE 
	CODE = '00195601'

--CURRENT_TIMESTAMP = NGAMBIL JAM DARI KOMPUTER CLIENT AJA, KALO DIDATABASE JAMNYA BEDA 10 MENIT
--	3 closed, 2 progress, 1 planned, 0 entered
UPDATE 
	PRODUCTIONDEMANDSTEP 
SET 
	PROGRESSSTATUS = '0',
	LASTUPDATEDATETIME = '2025-05-06 21:17:11'
WHERE 
	PRODUCTIONORDERCODE = '00195601'
	AND OPERATIONCODE = 'PPC4'