SELECT
    TRIM(PRODUCTIONORDERCODE) AS PRODUCTIONORDERCODE,
    LISTAGG(TRIM(DEAMAND), ', ') AS DEMAND,
    SUBSTRING(LISTAGG(ORIGDLVSALORDERLINEORDERLINE, ','), 1,3) AS ORDERLINE,
    TRIM(PROJECTCODE) AS PROJECTCODE,
    ORDPRNCUSTOMERSUPPLIERCODE,
    TRIM(SUBCODE01) AS SUBCODE01, 
    TRIM(SUBCODE02) AS SUBCODE02,
    TRIM(SUBCODE03) AS SUBCODE03, 
    TRIM(SUBCODE04) AS SUBCODE04,
    TRIM(SUBCODE05) AS SUBCODE05, 
    TRIM(SUBCODE06) AS SUBCODE06,
    TRIM(SUBCODE07) AS SUBCODE07, 
    TRIM(SUBCODE08) AS SUBCODE08,
    TRIM(SUBCODE09) AS SUBCODE09, 
    TRIM(SUBCODE10) AS SUBCODE10,
    TRIM(ITEMTYPEAFICODE) AS ITEMTYPEAFICODE,
    DSUBCODE05 AS NO_WARNA,
    TRIM(DSUBCODE02) || '-' || TRIM(DSUBCODE03) AS NO_HANGER,
    TRIM(ITEMDESCRIPTION) AS ITEMDESCRIPTION    
FROM 
    ITXVIEWKK 
WHERE 
    PRODUCTIONORDERCODE LIKE '%51517%'
GROUP BY 
	PRODUCTIONORDERCODE,
    PROJECTCODE,
    ORDPRNCUSTOMERSUPPLIERCODE,
    SUBCODE01, 
    SUBCODE02,
    SUBCODE03, 
    SUBCODE04,
    SUBCODE05, 
    SUBCODE06,
    SUBCODE07, 
    SUBCODE08,
    SUBCODE09, 
    SUBCODE10,
    ITEMTYPEAFICODE,
    DSUBCODE05,
    DSUBCODE02,
    DSUBCODE03,
   ITEMDESCRIPTION
    
SELECT 
	i.LEBAR,
	CASE
        WHEN i2.GRAMASI_KFF IS NULL THEN i2.GRAMASI_FKF
        ELSE
            i2.GRAMASI_KFF
    END AS GRAMASI
FROM 
	ITXVIEWLEBAR i 
LEFT JOIN ITXVIEWGRAMASI i2 ON i2.SALESORDERCODE = 'EXP2201302' AND i2.ORDERLINE = '20'
WHERE 
	i.SALESORDERCODE = 'EXP2201280' AND i.ORDERLINE = '30'
	
SELECT 
    DELIVERYDATE
FROM 
    SALESORDERDELIVERY 
WHERE 
    SALESORDERLINESALESORDERCODE = 'EXP2201280' AND SALESORDERLINEORDERLINE = '30'
    
 SELECT 
    TRIM(LANGGANAN) AS PELANGGAN,
    TRIM(BUYER) AS BUYER
FROM 
    ITXVIEW_PELANGGAN 
WHERE 
    ORDPRNCUSTOMERSUPPLIERCODE = 'C0001117' AND CODE = 'EXP2201280'
    
SELECT 
    TRIM(WARNA) AS WARNA
FROM 
    ITXVIEWCOLOR 
WHERE 
    ITEMTYPECODE = 'KFF' 
    AND SUBCODE01 = 'T' AND SUBCODE02 = 'DKI'
    AND SUBCODE03 = '22050' AND SUBCODE04 = 'L01'
    AND SUBCODE05 = '130117S' AND SUBCODE06 = 'F004'
    AND SUBCODE07 = '-' AND SUBCODE08 = '-'
    AND SUBCODE09 = '' AND SUBCODE10 = ''
    
SELECT 
    CASE
    	WHEN USEDUSERPRIMARYQUANTITY IS NULL THEN 0
    	ELSE USEDUSERPRIMARYQUANTITY
    END AS USEDUSERPRIMARYQUANTITY,
    CASE
    	WHEN USERSECONDARYQUANTITY IS NULL THEN 0
    	ELSE USERSECONDARYQUANTITY
    END AS USERSECONDARYQUANTITY,
    CASE
    	WHEN USERSECONDARYUOMCODE IS NULL THEN 0
    	ELSE USERSECONDARYUOMCODE
    END AS USERSECONDARYUOMCODE
FROM 
    ITXVIEW_RESERVATION 
WHERE 
    PRODUCTIONORDERCODE = '00051284' AND ITEMTYPEAFICODE = 'KGF'