DROP VIEW ITXVIEW_APPROVE_PO;
--CREATE VIEW ITXVIEW_APPROVE_PO AS 
SELECT
	ACT_HI_PROCINST.BUSINESS_KEY_,
	SUBSTR(SUBSTR(ACT_HI_PROCINST.BUSINESS_KEY_, LOCATE('|', ACT_HI_PROCINST.BUSINESS_KEY_)+ 1), LOCATE('|', SUBSTR(ACT_HI_PROCINST.BUSINESS_KEY_, LOCATE('|', ACT_HI_PROCINST.BUSINESS_KEY_)+ 1))+ 1) AS no_order,
	ACT_HI_TASKINST.ID_,
	WFMLINKEDENTITY.REASONCODE,
	ACT_HI_TASKINST.ASSIGNEE_
FROM
    ACT_HI_PROCINST ACT_HI_PROCINST
LEFT OUTER JOIN ACT_HI_TASKINST ACT_HI_TASKINST ON ACT_HI_PROCINST.PROC_INST_ID_ = ACT_HI_TASKINST.PROC_INST_ID_
LEFT OUTER JOIN WFMLINKEDENTITY WFMLINKEDENTITY ON ACT_HI_TASKINST.PROC_INST_ID_ = WFMLINKEDENTITY.WFMPROCESSID
WHERE
    WFMLINKEDENTITY.REASONCODE IS NOT NULL;