WITH QTY_BRUTO AS (
	SELECT
		i.CODE,
		i.ORIGDLVSALORDLINESALORDERCODE,
		i.ORIGDLVSALORDERLINEORDERLINE,
		SUM(i.USERPRIMARYQUANTITY) AS KFF,
		SUM(i.USERSECONDARYQUANTITY) AS FKF
	FROM
		ITXVIEWKGBRUTOBONORDER2 i
	GROUP BY
		i.CODE,
		i.ORIGDLVSALORDLINESALORDERCODE,
		i.ORIGDLVSALORDERLINEORDERLINE
)
SELECT
	SUM(QTY) AS QTY
FROM
	(SELECT
		(COALESCE(qb.KFF, 0)) AS QTY,
		s.CODE,
		s2.ORDERLINE
	FROM
		SALESORDER s
	LEFT JOIN SALESORDERLINE s2 ON s2.SALESORDERCODE = s.CODE AND s2.LINESTATUS = 1	AND s2.ITEMTYPEAFICODE IN ('KFF', 'FKF'	)
	LEFT JOIN SALESORDERDELIVERY s3 ON s3.SALESORDERLINESALESORDERCODE = s2.SALESORDERCODE AND s3.SALESORDERLINEORDERLINE = s2.ORDERLINE AND s3.ITEMTYPEAFICODE = s2.ITEMTYPEAFICODE
	LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = s.ABSUNIQUEID AND a2.FIELDNAME = 'ApprovalRMP'
	LEFT JOIN PRODUCTIONDEMAND p ON	p.ORIGDLVSALORDLINESALORDERCODE = s2.SALESORDERCODE	AND p.ORIGDLVSALORDERLINEORDERLINE = s2.ORDERLINE AND p.ITEMTYPEAFICODE IN ('KFF', 'FKF')
	LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p.ABSUNIQUEID	AND a.FIELDNAME = 'DefectNote'
	LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = p.ABSUNIQUEID AND a3.FIELDNAME = 'OriginalPDCode'
	LEFT JOIN QTY_BRUTO qb ON qb.ORIGDLVSALORDLINESALORDERCODE = s2.SALESORDERCODE AND qb.ORIGDLVSALORDERLINEORDERLINE = s2.ORDERLINE AND qb.CODE = p.CODE
	WHERE
		CAST(s.CREATIONDATETIME AS DATE) < '2025-04-20'
		AND s.TEMPLATECODE IN ('RFD', 'RFE')
		AND s3.DELIVERYDATE BETWEEN '2025-04-01' AND '2025-04-30'
		AND a.VALUESTRING LIKE '%GI%'
		AND NOT a2.VALUESTRING IS NULL
		AND a3.VALUESTRING IS NULL
	GROUP BY
		qb.KFF,
		s.CODE,
		s2.ORDERLINE
)