SELECT DISTINCT 
	p.PRODUCTIONORDERCODE,
	p.PRODUCTIONDEMANDCODE,
	isp.CODE,
	isp.PROVISIONALCODE
FROM 
 	PRODUCTIONDEMANDSTEP p
 LEFT JOIN PRODUCTIONDEMAND p2 ON p2.CODE = p.PRODUCTIONDEMANDCODE

 LEFT JOIN ITXVIEW_ALLOCATION_SURATJALAN_PPC iasp ON iasp.LOTCODE = p.PRODUCTIONORDERCODE 
 RIGHT JOIN ITXVIEW_SURATJALAN_PPC isp ON isp.CODE = iasp.CODE 
 WHERE
 	p.PRODUCTIONDEMANDCODE = '00140432'

SELECT 
	p.CODE,
	SUBSTR(a.VALUESTRING, 5) AS OriginalPdCode
FROM
	PRODUCTIONDEMAND p
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p2.ABSUNIQUEID AND a.FIELDNAME = 'OriginalPDCode'
WHERE
 	p.CODE = '00140432'
	
	
SELECT 
	isp.CODE,
	isp.GOODSISSUEDATE AS TGL_KIRIM,
	CASE
		WHEN isp.PAYMENTMETHODCODE = 'FOC' THEN isp.PAYMENTMETHODCODE
		ELSE ''
	END AS FOC,	
	COUNT(iasp.LOTCODE) AS ROLL,
	SUM(iasp.BASEPRIMARYQUANTITY) AS QTY_KIRIM_KG,
	CASE
		WHEN isp.PRICEUNITOFMEASURECODE = 'yd' THEN SUM(iasp.BASESECONDARYQUANTITY) 
		WHEN isp.PRICEUNITOFMEASURECODE = 'kg' THEN SUM(iasp.BASESECONDARYQUANTITY)
		WHEN isp.PRICEUNITOFMEASURECODE = 'm' THEN SUM(round(iasp.BASESECONDARYQUANTITY * 0.9144, 2))
	END AS QTY_KIRIM_YARD_MTR
FROM 
	ITXVIEW_SURATJALAN_PPC isp 
LEFT JOIN ITXVIEW_ALLOCATION_SURATJALAN_PPC iasp ON iasp.CODE = isp.CODE 
WHERE 
	isp.CODE = '000000447460'
GROUP BY
	isp.CODE,
	isp.GOODSISSUEDATE,
	isp.PAYMENTMETHODCODE,
	isp.PRICEUNITOFMEASURECODE