SELECT
    TRIM(p.SUBCODE01) SUBCODE01,
    TRIM(p.SUBCODE02) SUBCODE02,
    TRIM(p.SUBCODE03) SUBCODE03,
    TRIM(p.SUBCODE04) SUBCODE04,
    TRIM(p.SUBCODE05) SUBCODE05,
    TRIM(p.SUBCODE06) SUBCODE06,
    TRIM(p.SUBCODE01) || '-' ||
    TRIM(p.SUBCODE02) || '-' ||
    TRIM(p.SUBCODE03) || '-' ||
    TRIM(p.SUBCODE04) || '-' ||
    TRIM(p.SUBCODE05) || '-' ||
    TRIM(p.SUBCODE06) AS KODE_BARANG,
    p.LONGDESCRIPTION,
    i.SAFETYSTOCK,
    b.BASEPRIMARYQUANTITYUNIT,
    b.BASEPRIMARYUNITCODE B_BASEPRIMARYUNITCODE,
    b.WHSLOCATIONWAREHOUSEZONECODE AS ZONE,
    b.WAREHOUSELOCATIONCODE AS LOCATION,
    u.LONGDESCRIPTION BASEPRIMARYUNITCODE
FROM
    PRODUCT p
RIGHT JOIN BALANCE b ON b.ITEMTYPECODE = p.ITEMTYPECODE
    AND b.DECOSUBCODE01 = p.SUBCODE01 
    AND b.DECOSUBCODE02 = p.SUBCODE02 
    AND b.DECOSUBCODE03 = p.SUBCODE03 
    AND b.DECOSUBCODE04 = p.SUBCODE04 
    AND b.DECOSUBCODE05 = p.SUBCODE05 
    AND b.DECOSUBCODE06 = p.SUBCODE06
LEFT JOIN ITEMWAREHOUSELINK i ON i.ITEMTYPECODE = p.ITEMTYPECODE
    AND i.SUBCODE01 = p.SUBCODE01 
    AND i.SUBCODE02 = p.SUBCODE02 
    AND i.SUBCODE03 = p.SUBCODE03 
    AND i.SUBCODE04 = p.SUBCODE04 
    AND i.SUBCODE05 = p.SUBCODE05 
    AND i.SUBCODE06 = p.SUBCODE06
    AND i.LOGICALWAREHOUSECODE = b.LOGICALWAREHOUSECODE
LEFT JOIN UNITOFMEASURE u ON u.CODE = b.BASEPRIMARYUNITCODE
WHERE
    p.ITEMTYPECODE = 'SPR'
    AND p.SUBCODE01 = 'MTC'
    AND b.LOGICALWAREHOUSECODE = 'M201'
    AND b.STOCKTYPECODE= '001'