SELECT
	RTRIM(CODE) AS code,
	LANGGANAN AS langganan,
	BUYER AS buyer,
	PO_NUMBER AS po_number,
	QTY_BRUTO AS qty_bruto,
	SALESORDERCODE AS salesordercode,
	NO_ITEM AS no_item,
	SUBCODE02 AS subcode02,
	SUBCODE03 AS subcode03,
	ITEMDESCRIPTION AS itemdescription,
	LEBAR AS lebar,
	GRAMASI AS gramasi,
	PRODUCTIONORDERCODE AS productionordercode,
	WARNA AS warna,
	NO_WARNA AS no_warna
FROM
	ITXVIEWLAPORANAFTERSALESHEADER
WHERE
	RTRIM(CODE) IN (?)
GROUP BY
	CODE,
	NO_WARNA,
	WARNA,
	LANGGANAN,
	BUYER,
	PO_NUMBER,
	SALESORDERCODE,
	NO_ITEM,
	SUBCODE02,
	SUBCODE03,
	ITEMDESCRIPTION,
	LEBAR,
	GRAMASI,
	PRODUCTIONORDERCODE,
	QTY_BRUTO