SELECT
    TRIM( p.CODE ) AS PRODUCTIONDEMANDCODE,
    RIGHT ( a.VALUESTRING, 8 ) AS ORIGINALPDCODE 
FROM
    PRODUCTIONDEMAND p
    LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p.ABSUNIQUEID 
    AND a.FIELDNAME = 'LastProductDemandCode' 
WHERE
    p.CODE = '00281023'