-- DB2ADMIN.ITXVIEWRESEP3 source

CREATE VIEW ITXVIEWRESEP3 AS
SELECT
    a.MYROW,
    b.PRODUCTIONORDERCODE,
    a.RECIPESUBCODE01,
    a.RECIPESUFFIXCODE,
    a.GROUPNUMBER,
    a.ITEMTYPEAFICODE,
    a.CODE,
    a.SUBCODE,
    a.COMMENTLINE,
    a.LONGDESCRIPTION,
    a.CONSUMPTION,
    b.USERPRIMARYQUANTITY,
    b.USERPRIMARYUOMCODE
FROM
    (
        SELECT
            ROW_NUMBER() OVER() AS MYROW,
            *
        FROM
            ITXVIEWRESEP2
    ) a
LEFT JOIN VIEWPRODUCTIONRESERVATION b ON
    b.SUBCODE01 = a.SUBCODE01
    AND b.SUBCODE02 = a.SUBCODE02
    AND b.SUBCODE03 = a.SUBCODE03;