SELECT * FROM ITXVIEW_SUMMARY_QTY_DELIVERY WHERE NO_ORDER = 'EXP2400214' AND ORDERLINE = '80' ORDER BY ORDERLINE ASC


SELECT 
    PRODUCTIONDEMANDCODE
FROM 
    ITXVIEW_DEMANDBYLOTCODE 
WHERE 
    PRODUCTIONORDERCODE = '00143136'
    AND DLVSALESORDERLINEORDERLINE = '80'
    
    
SELECT
    *
FROM
    ITXVIEW_MEMOPENTINGPPC
WHERE
    NO_ORDER = 'EXP2400214'
    AND ORDERLINE = '80'