SELECT
    DISTINCT 
    VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE AS DYELOT,
    VIEWPRODUCTIONRESERVATION.GROUPLINE AS REDYE,
    '1410' AS MACHINE,
    0 AS TYPEOFPROCEDURE,
    0 AS PROCEDURENO,
    0 AS COLOR,
    TRIM(VIEWPRODUCTIONRESERVATION.SUBCODE01) || '-' || TRIM(VIEWPRODUCTIONRESERVATION.SUFFIXCODE) AS RECIPENO,
    i.PROJECTCODE AS ORDERNO,
    i.ORDPRNCUSTOMERSUPPLIERCODE AS CUSTOMER,
    '' AS ARTICLE,
    SUBSTR(TRIM(VIEWPRODUCTIONRESERVATION.SUBCODE01), 7, 7) AS COLORNO,
    ir.INITIALUSERPRIMARYQUANTITY AS WEIGHT,
    0 AS LENGTH,
    VIEWPRODUCTIONRESERVATION.PICKUPQUANTITY AS LIQUORATIO,
    0 AS LIQUORQUANTITY,
    0 AS PUMPSPEED,
    0 AS REELSPEED,
    0 AS ABSORPTION
FROM
    VIEWPRODUCTIONRESERVATION
LEFT JOIN ITXVIEWKK i ON i.PRODUCTIONORDERCODE = VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE
LEFT JOIN ITXVIEW_RESERVATION ir ON ir.PRODRESERVATIONLINKGROUPCODE = VIEWPRODUCTIONRESERVATION.PRODRESERVATIONLINKGROUPCODE 
                                AND ir.PRODUCTIONORDERCODE = VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE 
WHERE
    VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE = '00025866'
    AND VIEWPRODUCTIONRESERVATION.GROUPLINE = '200'