SELECT
    im.ORDERDATE,
    im.LANGGANAN,
    im.BUYER,
    im.NO_ITEM,
    im.NO_ORDER,
    im.NO_PO,
    im.SUBCODE02,
    im.SUBCODE03,
    im.JENIS_KAIN,
    im.WARNA,
    im.NO_WARNA,
    im.DELIVERY,
    ipm.PROGRESSSTARTPROCESSDATE,
    im.QTY_BAGIKAIN,
    im.NETTO,
    im.DELAY,
    im.NO_KK,
    im.DEMAND,
    im.LOT,
    im.ORDERLINE,
    im.PROGRESSSTATUS,
    im.PROGRESSSTATUS_DEMAND,
    im.KETERANGAN
FROM
    ITXVIEW_MEMOPENTINGPPC im 
LEFT JOIN ITXVIEW_POSISIKK_MUTASI ipm ON ipm.PRODUCTIONORDERCODE = im.NO_KK AND ipm.DEMANDSTEPPRODUCTIONDEMANDCODE = im.DEMAND 
WHERE
    ipm.PROGRESSSTARTPROCESSDATE BETWEEN '2024-08-12' AND '2024-08-12'