SELECT
    TRIM(x.PRODUCTIONORDERCODE) AS PRODUCTIONORDERCODE,
    x.OPERATIONCODE, 
    x.OPERATORCODE,
    x.PROGRESSSTARTPROCESSDATE, 
    x.PROGRESSSTARTPROCESSTIME ,
    x.MACHINECODE ,
    x.CREATIONDATETIME,
    r.LONGDESCRIPTION,  
    i.SUBCODE01,
    i.SUBCODE02,
    i.SUBCODE03,
    i.SUBCODE04,
    i.SUBCODE05,
    i.SUBCODE06,
    i.SUBCODE07,
    i.SUBCODE08,
    i.SUBCODE09,
    i.SUBCODE10,
    i.ITEMNO,
    LISTAGG(TRIM(i.PRO_ORDER), ', ') PRO_ORDER,
    LISTAGG(TRIM(i.PRODUCTIONDEMANDCODE), ', ') PRODUCTIONDEMANDCODE,
    LISTAGG(i.LANGGANAN, ', ') AS LANGGANAN,
    i.WARNA,
    i.NO_WARNA,
    i.JENISKAIN,
    i.LOT
FROM
    PRODUCTIONPROGRESS x
LEFT OUTER JOIN (
        SELECT
            p.SUBCODE01,
            p.SUBCODE02,
            p.SUBCODE03,
            p.SUBCODE04,
            p.SUBCODE05,
            p.SUBCODE06,
            p.SUBCODE07,
            p.SUBCODE08,
            p.SUBCODE09,
            p.SUBCODE10,
            CONCAT(TRIM(p.SUBCODE02), TRIM(p.SUBCODE03)) AS ITEMNO,
            p.ORIGDLVSALORDLINESALORDERCODE AS PRO_ORDER,
            ps.PRODUCTIONORDERCODE,
            ps.PRODUCTIONDEMANDCODE,
            E.LEGALNAME1 AS LANGGANAN,
            TRIM(f.LONGDESCRIPTION) AS WARNA,
            TRIM(f.CODE) AS NO_WARNA,
            PRODUCT.LONGDESCRIPTION AS JENISKAIN,
            p.DESCRIPTION AS LOT
        FROM
            PRODUCTIONDEMAND p
        LEFT JOIN PRODUCT PRODUCT ON PRODUCT.ITEMTYPECODE = p.ITEMTYPEAFICODE
                                AND PRODUCT.SUBCODE01 = p.SUBCODE01
                                AND PRODUCT.SUBCODE02 = p.SUBCODE02
                                AND PRODUCT.SUBCODE03 = p.SUBCODE03
                                AND PRODUCT.SUBCODE04 = p.SUBCODE04
                                AND PRODUCT.SUBCODE05 = p.SUBCODE05
                                AND PRODUCT.SUBCODE06 = p.SUBCODE06
                                AND PRODUCT.SUBCODE07 = p.SUBCODE07
                                AND PRODUCT.SUBCODE08 = p.SUBCODE08
                                AND PRODUCT.SUBCODE09 = p.SUBCODE09
                                AND PRODUCT.SUBCODE10 = p.SUBCODE10
        LEFT OUTER JOIN 
                (
                SELECT
                    PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE,
                    PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE
                FROM
                    PRODUCTIONDEMANDSTEP PRODUCTIONDEMANDSTEP
                GROUP BY
                    PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE,
                    PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE
            ) ps ON p.CODE = ps.PRODUCTIONDEMANDCODE
        LEFT OUTER JOIN
                (
                SELECT
                    BUSINESSPARTNER.LEGALNAME1,
                    ORDERPARTNER.CUSTOMERSUPPLIERCODE
                FROM
                    BUSINESSPARTNER BUSINESSPARTNER
                LEFT JOIN ORDERPARTNER ORDERPARTNER ON
                    BUSINESSPARTNER.NUMBERID = ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID
            ) E ON p.CUSTOMERCODE = E.CUSTOMERSUPPLIERCODE
        LEFT OUTER JOIN USERGENERICGROUP f ON p.SUBCODE05 = f.CODE AND f.USERGENERICGROUPTYPECODE = 'CL1'
        LEFT OUTER JOIN PRODUCTIONDEMAND h ON p.ORIGDLVSALORDLINESALORDERCODE = h.ORIGDLVSALORDLINESALORDERCODE
            AND p.SUBCODE01 = h.SUBCODE01
            AND p.SUBCODE02 = h.SUBCODE02
            AND p.SUBCODE03 = h.SUBCODE03
            AND p.SUBCODE04 = h.SUBCODE04
            AND h.ITEMTYPEAFICODE = 'KFF'
        GROUP BY
            p.SUBCODE01,
            p.SUBCODE02,
            p.SUBCODE03,
            p.SUBCODE04,
            p.SUBCODE05,
            p.SUBCODE06,
            p.SUBCODE07,
            p.SUBCODE08,
            p.SUBCODE09,
            p.SUBCODE10,
            p.ORIGDLVSALORDLINESALORDERCODE,
            ps.PRODUCTIONORDERCODE,
            ps.PRODUCTIONDEMANDCODE,
            E.LEGALNAME1,
            f.LONGDESCRIPTION,
            f.CODE,
            PRODUCT.LONGDESCRIPTION,
            p.DESCRIPTION
    ) i ON i.PRODUCTIONORDERCODE = x.PRODUCTIONORDERCODE
LEFT OUTER JOIN RESOURCES r ON r.CODE = x.OPERATORCODE
WHERE
    (x.OPERATIONCODE = 'BAT2' OR x.OPERATIONCODE = 'BKN1' OR x.OPERATIONCODE = 'BEL1')
    AND x.PROGRESSTEMPLATECODE = 'S01'
    AND TIMESTAMP(TRIM(x.PROGRESSSTARTPROCESSDATE), TRIM(x.PROGRESSSTARTPROCESSTIME)) BETWEEN '2024-07-10 23:00:00' AND '2024-07-13 23:00:00'
    AND x.PRODUCTIONORDERCODE = '00150834'
GROUP BY 
    x.PRODUCTIONORDERCODE,
    x.OPERATIONCODE, 
    x.OPERATORCODE,
    x.PROGRESSSTARTPROCESSDATE, 
    x.PROGRESSSTARTPROCESSTIME ,
    x.MACHINECODE ,
    x.CREATIONDATETIME,
    r.LONGDESCRIPTION,
    i.SUBCODE01,
    i.SUBCODE02,
    i.SUBCODE03,
    i.SUBCODE04,
    i.SUBCODE05,
    i.SUBCODE06,
    i.SUBCODE07,
    i.SUBCODE08,
    i.SUBCODE09,
    i.SUBCODE10,
    i.ITEMNO,
    i.WARNA,
    i.NO_WARNA,
    i.JENISKAIN,
    i.LOT
    
SELECT
p.PRODUCTIONORDERCODE,
p.STEPNUMBER AS STEPNUMBER,
CASE
    WHEN TRIM(p.PRODRESERVATIONLINKGROUPCODE) IS NULL OR TRIM(p.PRODRESERVATIONLINKGROUPCODE) = '' THEN TRIM(p.OPERATIONCODE)
    ELSE TRIM(p.PRODRESERVATIONLINKGROUPCODE)
END AS OPERATIONCODE,
TRIM(o.OPERATIONGROUPCODE) AS DEPT,
o.LONGDESCRIPTION,
CASE
    WHEN p.PROGRESSSTATUS = 0 THEN 'Entered'
    WHEN p.PROGRESSSTATUS = 1 THEN 'Planned'
    WHEN p.PROGRESSSTATUS = 2 THEN 'Progress'
    WHEN p.PROGRESSSTATUS = 3 THEN 'Closed'
END AS STATUS_OPERATION,
iptip.MULAI,
CASE
    WHEN p.PROGRESSSTATUS = 3 THEN COALESCE(iptop.SELESAI, SUBSTRING(p.LASTUPDATEDATETIME, 1, 19) || '(Run Manual Closures)')
    ELSE iptop.SELESAI
END AS SELESAI,
p.PRODUCTIONORDERCODE,
p.PRODUCTIONDEMANDCODE,
iptip.LONGDESCRIPTION AS OP1,
iptop.LONGDESCRIPTION AS OP2,
CASE
    WHEN a.VALUEBOOLEAN = 1 THEN 'Tidak Perlu Gerobak'
    ELSE LISTAGG(DISTINCT FLOOR(idqd.VALUEQUANTITY), ', ')
    END AS GEROBAK,
    idqd.WORKCENTERCODE 
FROM 
    PRODUCTIONDEMANDSTEP p 
LEFT JOIN OPERATION o ON o.CODE = p.OPERATIONCODE 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = o.ABSUNIQUEID AND a.FIELDNAME = 'Gerobak'
LEFT JOIN ITXVIEW_POSISIKK_TGL_IN_PRODORDER iptip ON iptip.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND iptip.DEMANDSTEPSTEPNUMBER = p.STEPNUMBER
LEFT JOIN ITXVIEW_POSISIKK_TGL_OUT_PRODORDER iptop ON iptop.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND iptop.DEMANDSTEPSTEPNUMBER = p.STEPNUMBER
LEFT JOIN ITXVIEW_DETAIL_QA_DATA idqd ON idqd.PRODUCTIONDEMANDCODE = p.PRODUCTIONDEMANDCODE AND idqd.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE
                                    -- AND idqd.OPERATIONCODE = COALESCE(p.PRODRESERVATIONLINKGROUPCODE, p.OPERATIONCODE)
                                AND idqd.OPERATIONCODE = CASE
                                                            WHEN TRIM(p.PRODRESERVATIONLINKGROUPCODE) IS NULL OR TRIM(p.PRODRESERVATIONLINKGROUPCODE) = '' THEN TRIM(p.OPERATIONCODE)
                                                            ELSE TRIM(p.PRODRESERVATIONLINKGROUPCODE)
                                                        END
                                AND (idqd.VALUEINT = p.STEPNUMBER OR idqd.VALUEINT = p.GROUPSTEPNUMBER) 
                                AND (idqd.CHARACTERISTICCODE = 'GRB1' OR
                                    idqd.CHARACTERISTICCODE = 'GRB2' OR
                                    idqd.CHARACTERISTICCODE = 'GRB3' OR
                                    idqd.CHARACTERISTICCODE = 'GRB4' OR
                                    idqd.CHARACTERISTICCODE = 'GRB5' OR
                                    idqd.CHARACTERISTICCODE = 'GRB6' OR
                                    idqd.CHARACTERISTICCODE = 'GRB7' OR
                                    idqd.CHARACTERISTICCODE = 'GRB8')
                                    AND NOT (idqd.VALUEQUANTITY = 999 OR idqd.VALUEQUANTITY = 1 OR idqd.VALUEQUANTITY = 9999 OR idqd.VALUEQUANTITY = 99999 OR idqd.VALUEQUANTITY = 99 OR idqd.VALUEQUANTITY = 91)
WHERE
    p.PRODUCTIONORDERCODE  = '00150834' 
    AND p.OPERATIONCODE = 'BKN1'
GROUP BY
    p.PRODUCTIONORDERCODE,
    p.STEPNUMBER,
    p.OPERATIONCODE,
    p.PRODRESERVATIONLINKGROUPCODE,
    o.OPERATIONGROUPCODE,
    o.LONGDESCRIPTION,
    p.PROGRESSSTATUS,
    iptip.MULAI,
    iptop.SELESAI,
    p.LASTUPDATEDATETIME,
    p.PRODUCTIONORDERCODE,
    p.PRODUCTIONDEMANDCODE,
    iptip.LONGDESCRIPTION,
    iptop.LONGDESCRIPTION,
    a.VALUEBOOLEAN,
    idqd.WORKCENTERCODE 
ORDER BY p.STEPNUMBER ASC