SELECT
	SUBSTR(STMT_TEXT, 1, 4000) AS STMT_TEXT,
	--  TOTAL_ACT_TIME AS TOTAL_EXECUTION_TIME_MS,
	--  DECIMAL(TOTAL_ACT_TIME / 1000.0, 10, 3) AS TOTAL_EXECUTION_SEC,
  RIGHT('0' || CAST(INT(TOTAL_ACT_TIME / (1000 * 60 * 60)) AS VARCHAR(2)), 2) || ':' ||
  RIGHT('0' || CAST(INT(MOD(TOTAL_ACT_TIME / (1000 * 60), 60)) AS VARCHAR(2)), 2) || ':' ||
  RIGHT('0' || CAST(INT(MOD(TOTAL_ACT_TIME / 1000, 60)) AS VARCHAR(2)), 2) AS TOTAL_EXECUTION_TIME_HMS,
	TOTAL_CPU_TIME,
	NUM_EXECUTIONS,
	STMT_TYPE_ID
FROM
	TABLE(
		MON_GET_PKG_CACHE_STMT(
			NULL,
			NULL,
			NULL,
			-2
		)
	) AS S
WHERE
	STMT_TEXT LIKE '%WITH STDR AS (%'
ORDER BY
	TOTAL_ACT_TIME DESC
FETCH FIRST 100 ROWS ONLY