SELECT 	 
	STOCKTRANSACTION.ORDERCODE,
	STOCKTRANSACTION.LOGICALWAREHOUSECODE,
	STOCKTRANSACTION.DECOSUBCODE01,
	STOCKTRANSACTION.DECOSUBCODE02,
	STOCKTRANSACTION.DECOSUBCODE03,
	STOCKTRANSACTION.DECOSUBCODE04,
	STOCKTRANSACTION.DECOSUBCODE05,
	STOCKTRANSACTION.DECOSUBCODE06,
	STOCKTRANSACTION.DECOSUBCODE07,
	STOCKTRANSACTION.DECOSUBCODE08,
	STOCKTRANSACTION.TRANSACTIONDATE,
	STOCKTRANSACTION.LOTCODE,
	STOCKTRANSACTION.CREATIONUSER,
	prj.PROJECTCODE AS PROJAWAL,
	prj1.PROJECTCODE AS PROJAWAL1,
	COUNT(STOCKTRANSACTION.BASEPRIMARYQUANTITY) AS QTY_DUS,
	SUM(STOCKTRANSACTION.BASEPRIMARYQUANTITY) AS QTY_KG,
	ITXVIEWHEADERKNTORDER.ORIGDLVSALORDLINESALORDERCODE,
	ITXVIEWHEADERKNTORDER.PROJECTCODE,
	ITXVIEWHEADERKNTORDER.PRODUCTIONDEMANDCODE,
	ITXVIEWHEADERKNTORDER.LEGALNAME1,  
	FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION
FROM
	DB2ADMIN.STOCKTRANSACTION STOCKTRANSACTION
LEFT OUTER JOIN
	(
		SELECT
			ITXVIEWHEADERKNTORDER.PRODUCTIONORDERCODE,
			LISTAGG(
				DISTINCT TRIM(ITXVIEWHEADERKNTORDER.ORIGDLVSALORDLINESALORDERCODE),
				', '
			) AS ORIGDLVSALORDLINESALORDERCODE,
			LISTAGG(
				DISTINCT TRIM(ITXVIEWHEADERKNTORDER.PRODUCTIONDEMANDCODE),
				', '
			) AS PRODUCTIONDEMANDCODE,
			LISTAGG(
				DISTINCT TRIM(ITXVIEWHEADERKNTORDER.PROJECTCODE),
				', '
			) AS PROJECTCODE,
			LISTAGG(
				DISTINCT TRIM(ITXVIEWHEADERKNTORDER.LEGALNAME1),
				', '
			) AS LEGALNAME1
		FROM
			DB2ADMIN.ITXVIEWHEADERKNTORDER
		GROUP BY
			ITXVIEWHEADERKNTORDER.PRODUCTIONORDERCODE
	) ITXVIEWHEADERKNTORDER
	 ON
	ITXVIEWHEADERKNTORDER.PRODUCTIONORDERCODE = STOCKTRANSACTION.ORDERCODE
LEFT OUTER JOIN DB2ADMIN.FULLITEMKEYDECODER FULLITEMKEYDECODER ON
	STOCKTRANSACTION.FULLITEMIDENTIFIER = FULLITEMKEYDECODER.IDENTIFIER
LEFT OUTER JOIN (
		SELECT
			STOCKTRANSACTION.ORDERCODE,
			STOCKTRANSACTION.ORDERLINE,
			STOCKTRANSACTION.ITEMELEMENTCODE,
			ITXVIEWBUKMUTGKGKNT.PROJECTCODE
		FROM
			STOCKTRANSACTION STOCKTRANSACTION
		LEFT JOIN INTERNALDOCUMENTLINE INTERNALDOCUMENTLINE 
ON
			STOCKTRANSACTION.ORDERCODE = INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE
			AND 
STOCKTRANSACTION.ORDERLINE = INTERNALDOCUMENTLINE.ORDERLINE
		LEFT JOIN ITXVIEWBUKMUTGKGKNT ITXVIEWBUKMUTGKGKNT 
ON
			INTERNALDOCUMENTLINE.INTDOCUMENTPROVISIONALCODE = ITXVIEWBUKMUTGKGKNT.INTDOCUMENTPROVISIONALCODE
			AND 
INTERNALDOCUMENTLINE.ORDERLINE = ITXVIEWBUKMUTGKGKNT.ORDERLINE
		WHERE
			STOCKTRANSACTION.ORDERCOUNTERCODE = 'I02M50'
		GROUP BY
			STOCKTRANSACTION.ORDERCODE,
			STOCKTRANSACTION.ORDERLINE,
			STOCKTRANSACTION.ITEMELEMENTCODE,
			ITXVIEWBUKMUTGKGKNT.PROJECTCODE
	) prj ON
	prj.ITEMELEMENTCODE = STOCKTRANSACTION.ITEMELEMENTCODE
LEFT OUTER JOIN (
		SELECT
			STOCKTRANSACTION.PROJECTCODE ,
			STOCKTRANSACTION.ITEMELEMENTCODE
		FROM
			STOCKTRANSACTION STOCKTRANSACTION
		WHERE
			STOCKTRANSACTION.TEMPLATECODE = 'OPN'
		GROUP BY
			STOCKTRANSACTION.PROJECTCODE,
			STOCKTRANSACTION.ITEMELEMENTCODE
	) prj1 ON
	prj1.ITEMELEMENTCODE = STOCKTRANSACTION.ITEMELEMENTCODE
WHERE
	(
		STOCKTRANSACTION.ITEMTYPECODE = 'KGF'
			OR STOCKTRANSACTION.ITEMTYPECODE = 'FKG'
	)
	AND STOCKTRANSACTION.LOGICALWAREHOUSECODE = 'M021'
	AND
STOCKTRANSACTION.ONHANDUPDATE > 1
	AND TRANSACTIONDATE BETWEEN '2024-07-16' AND '2024-07-16'
	AND NOT STOCKTRANSACTION.ORDERCODE IS NULL
GROUP BY
	STOCKTRANSACTION.ORDERCODE,
	STOCKTRANSACTION.LOGICALWAREHOUSECODE,
	STOCKTRANSACTION.DECOSUBCODE01,
	STOCKTRANSACTION.DECOSUBCODE02,
	STOCKTRANSACTION.DECOSUBCODE03,
	STOCKTRANSACTION.DECOSUBCODE04,
	STOCKTRANSACTION.DECOSUBCODE05,
	STOCKTRANSACTION.DECOSUBCODE06,
	STOCKTRANSACTION.DECOSUBCODE07,
	STOCKTRANSACTION.DECOSUBCODE08,
	STOCKTRANSACTION.TRANSACTIONDATE,
	STOCKTRANSACTION.LOTCODE,
	STOCKTRANSACTION.CREATIONUSER,
	prj.PROJECTCODE,
	prj1.PROJECTCODE,
	ITXVIEWHEADERKNTORDER.ORIGDLVSALORDLINESALORDERCODE,
	ITXVIEWHEADERKNTORDER.PROJECTCODE,
	ITXVIEWHEADERKNTORDER.PRODUCTIONDEMANDCODE,
	ITXVIEWHEADERKNTORDER.LEGALNAME1,
	FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION