SELECT 
	QUALITYDOCUMENT.PRODUCTIONORDERCODE,
	QUALITYDOCUMENT.ITEMTYPEAFICODE,
	QUALITYDOCUMENT.SUBCODE01,
	QUALITYDOCUMENT.SUBCODE02,
	QUALITYDOCUMENT.SUBCODE03,
	QUALITYDOCUMENT.SUBCODE04,
	QUALITYDOCUMENT.SUBCODE05,
	QUALITYDOCUMENT.SUBCODE06,
	QUALITYDOCUMENT.SUBCODE07,
	QUALITYDOCUMENT.SUBCODE08,
	QUALITYDOCUMENT.SUBCODE09,
	QUALITYDOCUMENT.SUBCODE10,
	QUALITYDOCUMENT.WORKCENTERCODE,
	QUALITYDOCUMENT.OPERATIONCODE,
	QUALITYDOCLINE.CHARACTERISTICCODE,
	QUALITYDOCLINE.VALUEQUANTITY,
	PRODUCT.LONGDESCRIPTION AS JENIS_KAIN,
	ITXVIEWCOLOR.WARNA,
	A.PROJECTCODE, 
	ORDERPARTNERBRAND.LONGDESCRIPTION AS BUYER, 
	QUALITYDOCUMENTBEAN.IMPORTDATETIME
FROM QUALITYDOCUMENT QUALITYDOCUMENT 
LEFT JOIN QUALITYDOCLINE QUALITYDOCLINE ON QUALITYDOCUMENT.PRODUCTIONORDERCODE = QUALITYDOCLINE.QUALITYDOCPRODUCTIONORDERCODE AND 
                        QUALITYDOCUMENT.HEADERLINE = QUALITYDOCLINE.QUALITYDOCUMENTHEADERLINE
LEFT JOIN PRODUCT PRODUCT ON 
                    QUALITYDOCUMENT.ITEMTYPEAFICODE = PRODUCT.ITEMTYPECODE AND 
                    QUALITYDOCUMENT.SUBCODE01 = PRODUCT.SUBCODE01 AND 
                    QUALITYDOCUMENT.SUBCODE02 = PRODUCT.SUBCODE02 AND 
                    QUALITYDOCUMENT.SUBCODE03 = PRODUCT.SUBCODE03 AND 
                    QUALITYDOCUMENT.SUBCODE04 = PRODUCT.SUBCODE04 AND 
                    QUALITYDOCUMENT.SUBCODE05 = PRODUCT.SUBCODE05 AND 
                    QUALITYDOCUMENT.SUBCODE06 = PRODUCT.SUBCODE06 AND 
                    QUALITYDOCUMENT.SUBCODE07 = PRODUCT.SUBCODE07 AND 
                    QUALITYDOCUMENT.SUBCODE08 = PRODUCT.SUBCODE08 AND 
                    QUALITYDOCUMENT.SUBCODE09 = PRODUCT.SUBCODE09 AND 
                    QUALITYDOCUMENT.SUBCODE10 = PRODUCT.SUBCODE10
LEFT JOIN ITXVIEWCOLOR ITXVIEWCOLOR ON 
                    QUALITYDOCUMENT.ITEMTYPEAFICODE = ITXVIEWCOLOR.ITEMTYPECODE AND 
                    QUALITYDOCUMENT.SUBCODE01 = ITXVIEWCOLOR.SUBCODE01 AND 
                    QUALITYDOCUMENT.SUBCODE02 = ITXVIEWCOLOR.SUBCODE02 AND 
                    QUALITYDOCUMENT.SUBCODE03 = ITXVIEWCOLOR.SUBCODE03 AND 
                    QUALITYDOCUMENT.SUBCODE04 = ITXVIEWCOLOR.SUBCODE04 AND 
                    QUALITYDOCUMENT.SUBCODE05 = ITXVIEWCOLOR.SUBCODE05 AND 
                    QUALITYDOCUMENT.SUBCODE06 = ITXVIEWCOLOR.SUBCODE06 AND 
                    QUALITYDOCUMENT.SUBCODE07 = ITXVIEWCOLOR.SUBCODE07 AND 
                    QUALITYDOCUMENT.SUBCODE08 = ITXVIEWCOLOR.SUBCODE08 AND 
                    QUALITYDOCUMENT.SUBCODE09 = ITXVIEWCOLOR.SUBCODE09 AND 
                    QUALITYDOCUMENT.SUBCODE10 = ITXVIEWCOLOR.SUBCODE10
LEFT JOIN ITXVIEWKK A ON A.PRODUCTIONORDERCODE = QUALITYDOCUMENT.PRODUCTIONORDERCODE
LEFT JOIN SALESORDER SALESORDER ON SALESORDER.CODE = A.PROJECTCODE 
LEFT JOIN ORDERPARTNERBRAND ORDERPARTNERBRAND ON SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE = ORDERPARTNERBRAND.ORDPRNCUSTOMERSUPPLIERCODE 
                                AND SALESORDER.ORDERPARTNERBRANDCODE = ORDERPARTNERBRAND.CODE 
LEFT JOIN QUALITYDOCUMENTBEAN QUALITYDOCUMENTBEAN ON QUALITYDOCUMENT.PRODUCTIONORDERCODE = QUALITYDOCUMENTBEAN.PRODUCTIONORDERCODE AND 
                                                      QUALITYDOCUMENT.HEADERNUMBERID = QUALITYDOCUMENTBEAN.HEADERNUMBERID AND 
                                                      QUALITYDOCUMENT.HEADERLINE = QUALITYDOCUMENTBEAN.HEADERLINE
WHERE 
  	QUALITYDOCLINE.CHARACTERISTICCODE LIKE 'GRB%'  
  	AND QUALITYDOCLINE.VALUEQUANTITY IS NOT NULL  
  	AND QUALITYDOCLINE.VALUEQUANTITY <> 0
--  $tanggal 
	AND QUALITYDOCLINE.VALUEQUANTITY = '$Gerobak' 
	AND QUALITYDOCUMENTBEAN.IMPORTDATETIME IS NOT NULL
  	AND QUALITYDOCLINE.VALUEQUANTITY = '130' 
	AND QUALITYDOCUMENT.PRODUCTIONORDERCODE = '00080712'
GROUP BY 
  QUALITYDOCUMENT.PRODUCTIONORDERCODE,
  QUALITYDOCUMENT.ITEMTYPEAFICODE,
  QUALITYDOCUMENT.SUBCODE01,
  QUALITYDOCUMENT.SUBCODE02,
  QUALITYDOCUMENT.SUBCODE03,
  QUALITYDOCUMENT.SUBCODE04,
  QUALITYDOCUMENT.SUBCODE05,
  QUALITYDOCUMENT.SUBCODE06,
  QUALITYDOCUMENT.SUBCODE07,
  QUALITYDOCUMENT.SUBCODE08,
  QUALITYDOCUMENT.SUBCODE09,
  QUALITYDOCUMENT.SUBCODE10,
  QUALITYDOCUMENT.WORKCENTERCODE,
  QUALITYDOCUMENT.OPERATIONCODE,
  QUALITYDOCLINE.CHARACTERISTICCODE,
  QUALITYDOCLINE.VALUEQUANTITY,
  PRODUCT.LONGDESCRIPTION,
  ITXVIEWCOLOR.WARNA,
  A.PROJECTCODE, 
  ORDERPARTNERBRAND.LONGDESCRIPTION,
  QUALITYDOCUMENTBEAN.IMPORTDATETIME
ORDER BY 
	QUALITYDOCUMENTBEAN.IMPORTDATETIME DESC