SELECT
	CASE 
		WHEN s.TEMPLATECODE = '303' THEN 'Finishing/Printing'
	END AS KETERANGAN,	
    CASE
        WHEN s.PRODUCTIONORDERCODE IS NULL THEN s.ORDERCODE 
        ELSE s.PRODUCTIONORDERCODE 
    END AS PRODUCTIONORDERCODE,
    s.DECOSUBCODE01,
    s.DECOSUBCODE02,
    s.DECOSUBCODE03,
    CASE
        WHEN s.TEMPLATECODE = '120' THEN TRIM(s.DECOSUBCODE01) || '-' || TRIM(s.DECOSUBCODE02) || '-' || TRIM(s.DECOSUBCODE03) 
        ELSE s.TEMPLATECODE 
    END	AS KODE_OBAT,
    s.USERPRIMARYQUANTITY AS AKTUAL_QTY,
    p.LONGDESCRIPTION 
FROM
    STOCKTRANSACTION s
LEFT JOIN PRODUCT p ON p.ITEMTYPECODE = s.ITEMTYPECODE 
                    AND p.SUBCODE01 = s.DECOSUBCODE01 
                    AND p.SUBCODE02 = s.DECOSUBCODE02 
                    AND p.SUBCODE03 = s.DECOSUBCODE03
WHERE 
    s.ITEMTYPECODE = 'DYC'
    AND s.LOGICALWAREHOUSECODE = 'M510'
    AND s.TRANSACTIONDATE = '2024-01-04'
    AND s.PRODUCTIONORDERCODE = '00113867'
ORDER BY 
    s.PRODUCTIONORDERCODE ASC
    
    
SELECT 
    TRIM(p.PRODUCTIONORDERCODE) || '-' || TRIM(p.GROUPLINE) AS NO_RESEP,
    SUM(p.USERPRIMARYQUANTITY) AS USERPRIMARYQUANTITY,
    p2.CODE,
    CASE
        WHEN p2.CODE LIKE '%T1%' OR p2.CODE LIKE '%T2%' OR p2.CODE LIKE '%T3%' OR p2.CODE LIKE '%T4%' OR p2.CODE LIKE '%T5%' OR p2.CODE LIKE '%T6%' OR p2.CODE LIKE '%T7%' THEN 'Tambah Obat'
        WHEN p2.CODE LIKE '%R1%' OR p2.CODE LIKE '%R2%' OR p2.CODE LIKE '%R3%' OR p2.CODE LIKE '%R4%' OR p2.CODE LIKE '%R5%' OR p2.CODE LIKE '%R6%' OR p2.CODE LIKE '%R7%' THEN 'Perbaikan'
        ELSE 'Normal'
    END AS KETERANGAN
FROM
    PRODUCTIONRESERVATION p
LEFT JOIN PRODRESERVATIONLINKGROUP p2 ON p2.CODE = p.PRODRESERVATIONLINKGROUPCODE 
WHERE 
    p.PRODUCTIONORDERCODE = '00113867' 
    AND p.SUBCODE01 = 'E' 
    AND p.SUBCODE02 = '1' 
    AND p.SUBCODE03 = '001'
GROUP BY
    p.PRODUCTIONORDERCODE,
    p.GROUPLINE,
    p2.CODE