SELECT
    DISTINCT 
    TRIM(VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE) AS DYELOT,
    VIEWPRODUCTIONRESERVATION.GROUPLINE AS REDYE,
    '1409' AS MACHINE,
    0 AS TYPEOFPROCEDURE,
    0 AS PROCEDURENO,
    0 AS COLOR,
    TRIM(VIEWPRODUCTIONRESERVATION.SUBCODE01) || '-' || TRIM(VIEWPRODUCTIONRESERVATION.SUFFIXCODE) AS RECIPENO,
    i.PROJECTCODE AS ORDERNO,
    i.ORDPRNCUSTOMERSUPPLIERCODE AS CUSTOMER,
    '' AS ARTICLE,
    TRIM(i.SUBCODE05) AS COLORNO,
    SUBSTR(TRIM(i.WARNA),1,20) AS WARNA,
    ir.INITIALUSERPRIMARYQUANTITY AS WEIGHT,
    0 AS LENGTH,
    VIEWPRODUCTIONRESERVATION.PICKUPQUANTITY AS LIQUORATIO,
    CAST((CAST(ir.INITIALUSERPRIMARYQUANTITY * VIEWPRODUCTIONRESERVATION.PICKUPQUANTITY AS DECIMAL(18, 2))) - ir.INITIALUSERPRIMARYQUANTITY * (a.VALUEDECIMAL/100) AS DECIMAL(18,2)) AS LIQUORQUANTITY,
    0 AS PUMPSPEED,
    0 AS REELSPEED,
    0 AS ABSORPTION
FROM
    VIEWPRODUCTIONRESERVATION
LEFT JOIN ITXVIEWKK i ON i.PRODUCTIONORDERCODE = VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE
LEFT JOIN ITXVIEW_RESERVATION ir ON ir.PRODRESERVATIONLINKGROUPCODE = VIEWPRODUCTIONRESERVATION.PRODRESERVATIONLINKGROUPCODE 
                                AND ir.PRODUCTIONORDERCODE = VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE
LEFT JOIN RECIPE r ON r.SUBCODE01 = VIEWPRODUCTIONRESERVATION.SUBCODE01 AND r.SUFFIXCODE = VIEWPRODUCTIONRESERVATION.SUFFIXCODE 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = r.ABSUNIQUEID AND a.NAMENAME = 'CarryOver'
WHERE
    VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE = '00190456'
    AND VIEWPRODUCTIONRESERVATION.GROUPLINE = '303'