SELECT
	SUM(DISTINCT v.QTY_BAGI_KAIN) AS TOTAL_QTY_BAGI_KAIN
FROM
    PRODUCTIONPROGRESS x
LEFT OUTER JOIN (
        SELECT
            p.SUBCODE01,
            p.SUBCODE02,
            p.SUBCODE03,
            p.SUBCODE04,
            p.SUBCODE05,
            p.SUBCODE06,
            p.SUBCODE07,
            p.SUBCODE08,
            p.SUBCODE09,
            p.SUBCODE10,
            CONCAT(TRIM(p.SUBCODE02), TRIM(p.SUBCODE03)) AS ITEMNO,
            p.ORIGDLVSALORDLINESALORDERCODE AS PRO_ORDER,
            ps.PRODUCTIONORDERCODE,
            ps.PRODUCTIONDEMANDCODE,
            E.LEGALNAME1 AS LANGGANAN,
            TRIM(f.LONGDESCRIPTION) AS WARNA,
            TRIM(f.CODE) AS NO_WARNA
        FROM
            PRODUCTIONDEMAND p
        LEFT OUTER JOIN 
                (
                SELECT
                    PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE,
                    PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE
                FROM
                    PRODUCTIONDEMANDSTEP PRODUCTIONDEMANDSTEP
                GROUP BY
                    PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE,
                    PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE
            ) ps
            ON
            p.CODE = ps.PRODUCTIONDEMANDCODE
        LEFT OUTER JOIN
                (
                SELECT
                    BUSINESSPARTNER.LEGALNAME1,
                    ORDERPARTNER.CUSTOMERSUPPLIERCODE
                FROM
                    BUSINESSPARTNER BUSINESSPARTNER
                LEFT JOIN ORDERPARTNER ORDERPARTNER ON
                    BUSINESSPARTNER.NUMBERID = ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID
            ) E
            ON
            p.CUSTOMERCODE = E.CUSTOMERSUPPLIERCODE
        LEFT OUTER JOIN USERGENERICGROUP f
                ON
            p.SUBCODE05 = f.CODE
            AND f.USERGENERICGROUPTYPECODE = 'CL1'
        LEFT OUTER JOIN PRODUCTIONDEMAND h
            ON
            p.ORIGDLVSALORDLINESALORDERCODE = h.ORIGDLVSALORDLINESALORDERCODE
            AND 
            p.SUBCODE01 = h.SUBCODE01
            AND 
            p.SUBCODE02 = h.SUBCODE02
            AND
            p.SUBCODE03 = h.SUBCODE03
            AND
            p.SUBCODE04 = h.SUBCODE04
            AND 
            h.ITEMTYPEAFICODE = 'KFF'
        GROUP BY
            p.SUBCODE01,
            p.SUBCODE02,
            p.SUBCODE03,
            p.SUBCODE04,
            p.SUBCODE05,
            p.SUBCODE06,
            p.SUBCODE07,
            p.SUBCODE08,
            p.SUBCODE09,
            p.SUBCODE10,
            p.ORIGDLVSALORDLINESALORDERCODE,
            ps.PRODUCTIONORDERCODE,
            ps.PRODUCTIONDEMANDCODE,
            E.LEGALNAME1,
            f.LONGDESCRIPTION,
            f.CODE
    ) i ON
    i.PRODUCTIONORDERCODE = x.PRODUCTIONORDERCODE
LEFT OUTER JOIN RESOURCES r ON
    r.CODE = x.OPERATORCODE
LEFT OUTER JOIN (
    SELECT 
        PRODUCTIONORDERCODE, 
        SUM(INITIALUSERPRIMARYQUANTITY) AS QTY_BAGI_KAIN,
        OPERATIONCODE
    FROM 
        VIEWPRODUCTIONDEMANDSTEP 
    GROUP BY 
        PRODUCTIONORDERCODE,
        OPERATIONCODE --Perlu di grup berdasarkan operation karena ada sum
) v ON v.PRODUCTIONORDERCODE = x.PRODUCTIONORDERCODE 
AND v.OPERATIONCODE = x.OPERATIONCODE
WHERE
    (
        x.OPERATIONCODE = 'BAT2' 
        OR x.OPERATIONCODE = 'BKN1' 
--        OR x.OPERATIONCODE = 'BEL1' 
        OR x.OPERATIONCODE = 'BAT3' 
        OR x.OPERATIONCODE = 'BBS1' 
        OR x.OPERATIONCODE = 'JHP1' 
        OR x.OPERATIONCODE = 'WAIT36'
    )
    AND x.PROGRESSTEMPLATECODE = 'S01'
    AND TIMESTAMP(TRIM(x.PROGRESSSTARTPROCESSDATE), TRIM(x.PROGRESSSTARTPROCESSTIME)) BETWEEN '2024-08-14 07:00:00' AND '2024-08-14 15:00:00'
AND x.INACTIVE = 1