SELECT 
    PRODUCTIONORDERCODE,
    REPLACE(LISTAGG( '`'|| PRODUCTIONDEMANDCODE || '`', ', '), '`', '''')  AS PRODUCTIONDEMANDCODE2,
    LISTAGG(PRODUCTIONDEMANDCODE, ', ')  AS PRODUCTIONDEMANDCODE,
    STEPNUMBER,
    OPERATIONCODE,
    STATUS_OPERATION,
    OPERATIONGROUPCODE
FROM
    (SELECT	
        TRIM(p.PRODUCTIONORDERCODE) AS PRODUCTIONORDERCODE,
        TRIM(p.PRODUCTIONDEMANDCODE) AS PRODUCTIONDEMANDCODE,
        p.STEPNUMBER,
        TRIM(p.OPERATIONCODE) AS OPERATIONCODE,
        CASE
            WHEN p.PROGRESSSTATUS = 0 THEN 'Entered'
            WHEN p.PROGRESSSTATUS = 1 THEN 'Planned'
            WHEN p.PROGRESSSTATUS = 2 THEN 'Progress'
            WHEN p.PROGRESSSTATUS = 3 THEN 'Closed'
        END AS STATUS_OPERATION,
        TRIM(o.OPERATIONGROUPCODE) AS OPERATIONGROUPCODE,
        ROW_NUMBER() OVER (PARTITION BY p.PRODUCTIONORDERCODE, p.PRODUCTIONDEMANDCODE ORDER BY p.STEPNUMBER) AS RN
    FROM
        PRODUCTIONDEMANDSTEP p
    LEFT JOIN OPERATION o ON o.CODE = p.OPERATIONCODE 
    WHERE 
        TRIM(p.PROGRESSSTATUS) IN ('2')
--        TRIM(p.PROGRESSSTATUS) IN ('2','0') -- KHUSUS DYE
        AND TRIM(o.OPERATIONGROUPCODE) = 'BRS'
        AND p.CREATIONDATETIME >= '2023-11-01'
        AND NOT p.PRODUCTIONORDERCODE IS NULL)
WHERE
    RN = 1
    AND NOT OPERATIONCODE = 'BAT1'
GROUP BY 
    PRODUCTIONORDERCODE,
    STEPNUMBER,
    OPERATIONCODE,
    STATUS_OPERATION,
    OPERATIONGROUPCODE