SELECT
    DISTINCT 
    p.STEPNUMBER,
--	p.GROUPSTEPNUMBER,
    TRIM(o.OPERATIONGROUPCODE) AS DEPT,
    CASE
        WHEN TRIM(w.PRODRESERVATIONLINKGROUPCODE) IS NOT NULL THEN TRIM(w.PRODRESERVATIONLINKGROUPCODE)
        ELSE TRIM(w.OPERATIONCODE)
    END AS OPERATIONCODE,	
    p.LONGDESCRIPTION
FROM
    WORKCENTERANDOPERATTRIBUTES w
LEFT JOIN OPERATION o ON o.CODE = w.OPERATIONCODE 
LEFT JOIN PRODUCTIONDEMANDSTEP p ON p.OPERATIONCODE = o.CODE 
WHERE
    NOT w.LONGDESCRIPTION = 'JANGAN DIPAKE'
    AND TRIM(o.OPERATIONGROUPCODE) = 'FIN'
    AND p.PRODUCTIONORDERCODE  = '00134557' 
    AND p.PRODUCTIONDEMANDCODE = '00239971'
ORDER BY 
    p.STEPNUMBER ASC
    
    
SELECT
	DISTINCT 
	TRIM(p.WORKCENTERCODE) AS WORKCENTERCODE,
	SUBSTR(TRIM(p.WORKCENTERCODE), 1,4) AS WORKCENTERCODE_CODE, 
	w2.LONGDESCRIPTION 
FROM
	WORKCENTERANDOPERATTRIBUTES w
LEFT JOIN OPERATION o ON o.CODE = w.OPERATIONCODE 
LEFT JOIN PRODUCTIONDEMANDSTEP p ON p.OPERATIONCODE = o.CODE 
LEFT JOIN WORKCENTER w2 ON w2.CODE = p.WORKCENTERCODE 
WHERE
	NOT w.LONGDESCRIPTION = 'JANGAN DIPAKE'
	AND TRIM(o.OPERATIONGROUPCODE) = 'FIN'
	AND p.PRODUCTIONORDERCODE  = '00134557' 
    AND p.PRODUCTIONDEMANDCODE = '00239971'
    AND w.OPERATIONCODE = 'NCP5'
    

SELECT
	*
FROM
	RESOURCES r
WHERE
--	SUBSTR(CODE, 1,4) = 'P3ST' -- STENTER
--	OR SUBSTR(CODE, 1,4) = 'P3CP' -- COMPACT
--	OR SUBSTR(CODE, 1,4) = 'P3BC' OR CODE = 'P3IN350' -- BELAH LIPAT
--	OR SUBSTR(CODE, 1,4) = 'P3ST' OR SUBSTR(CODE, 1,4) = 'P3DR' -- OVEN
--	OR SUBSTR(CODE, 1,4) = 'P3SM' -- STEAMER
--	OR 
	SUBSTR(CODE, 1,4) = 'P3NC' -- STEAMER
ORDER BY 
  	SUBSTR(CODE, 6,2) 
ASC