SELECT
	s.ABSUNIQUEID 
FROM
	PRODUCTIONDEMAND p 
LEFT JOIN SALESORDERLINE s ON s.SALESORDERCODE = p.ORIGDLVSALORDLINESALORDERCODE 
							AND s.ORDERLINE = p.ORIGDLVSALORDERLINEORDERLINE 
WHERE
	p.CODE = '00279097'


SELECT
	UNIQUEID,
	SUBSTR(ROLL, 1,2) AS ROLL
FROM (SELECT
		UNIQUEID,
		CASE 
	        WHEN LOCATE('(', VALUESTRING) > 0 AND LOCATE(')', VALUESTRING) > 0 THEN
	            SUBSTRING(VALUESTRING, LOCATE('(', VALUESTRING) + 1, LOCATE(')', VALUESTRING) - LOCATE('(', VALUESTRING) - 1)
	    END AS ROLL
	FROM
		ADSTORAGE
	WHERE
		NAMENAME = 'ColorRemarks'
		AND VALUESTRING LIKE '%ROLL%'
		AND UNIQUEID = '89827468'
		AND NOT CASE 
	        WHEN LOCATE('(', VALUESTRING) > 0 AND LOCATE(')', VALUESTRING) > 0 THEN
	            SUBSTRING(VALUESTRING, LOCATE('(', VALUESTRING) + 1, LOCATE(')', VALUESTRING) - LOCATE('(', VALUESTRING) - 1)
    	END IS NULL)