SELECT
    SUBSTRING(p.LASTUPDATEDATETIME, 1, 19)
FROM 
    PRODUCTIONDEMANDSTEP p 
WHERE
    p.PRODUCTIONORDERCODE  = '00195601' AND p.PRODUCTIONDEMANDCODE = '00337119'  
    AND p.OPERATIONCODE = 'PPC4'