SELECT
	ORDERLINE,
	PELANGGAN,
	NO_ORDER,
	NO_PO,
	KET_PRODUCT,
	STYLE,
	LEBAR,
	GRAMASI,
	WARNA,
	NO_WARNA,
	NETTO,
	NETTO_2,
	KONVERSI,
	ACTUAL_DELIVERY,
	SUM(QTY_SUDAH_KIRIM) AS QTY_SUDAH_KIRIM,
	SUM(QTY_SUDAH_KIRIM_2) AS QTY_SUDAH_KIRIM_2,
	CASE
		WHEN DAYS(now()) - DAYS(Timestamp_Format(ACTUAL_DELIVERY, 'YYYY-MM-DD')) < 0 THEN 0
		ELSE DAYS(now()) - DAYS(Timestamp_Format(ACTUAL_DELIVERY, 'YYYY-MM-DD'))
	END AS DELAY
FROM
	ITXVIEW_SUMMARY_QTY_DELIVERY isqd
WHERE
	NO_PO = '24100044IR-01'
GROUP BY
	ORDERLINE,
	PELANGGAN,
	NO_ORDER,
	NO_PO,
	KET_PRODUCT,
	STYLE,
	LEBAR,
	GRAMASI,
	WARNA,
	NO_WARNA,
	NETTO,
	NETTO_2,
	KONVERSI,
	ACTUAL_DELIVERY
ORDER BY
	ORDERLINE ASC