SELECT DISTINCT 
	p.GROUPLINE,
	p.GROUPSTEPNUMBER,
	p.PRODRESERVATIONLINKGROUPCODE,
	w.WHITENESS,
	TRIM(p.SUBCODE01) || '-' ||TRIM(p.SUFFIXCODE) AS SUFFIX,
	p.PICKUPQUANTITY AS LR
FROM 
	PRODUCTIONRESERVATION p 
LEFT JOIN 
	(SELECT
		a.VALUEINT,
		v.PRODUCTIONORDERCODE,
		v.CHARACTERISTICCODE,
		v.VALUEQUANTITY AS WHITENESS
	FROM
		VIEWQUALITYDOCHEADERLINE v 
	LEFT JOIN ADSTORAGE a ON a.UNIQUEID = v.ABSUNIQUEID ) w ON w.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND w.CHARACTERISTICCODE = 'WHITENESS' AND w.VALUEINT = p.GROUPSTEPNUMBER 
LEFT JOIN 
	(SELECT
		a.VALUEINT,
		v.PRODUCTIONORDERCODE,
		v.CHARACTERISTICCODE,
		v.VALUEQUANTITY AS WHITENESS
	FROM
		VIEWQUALITYDOCHEADERLINE v 
	LEFT JOIN ADSTORAGE a ON a.UNIQUEID = v.ABSUNIQUEID ) w ON w.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND w.CHARACTERISTICCODE = 'YELLOWNESS' AND w.VALUEINT = p.GROUPSTEPNUMBER 
WHERE 
	(SUBSTR(p.SUBCODE01, 1, 2) = 'SC' OR 
	SUBSTR(p.SUBCODE01, 1, 2) = 'TC' OR 
	SUBSTR(p.SUBCODE01, 1, 2) = 'CB' OR 
	SUBSTR(p.SUFFIXCODE, 1, 2) = 'SC' OR
	SUBSTR(p.SUFFIXCODE, 1, 2) = 'TC')
	AND p.PRODUCTIONORDERCODE = '00084598'
ORDER BY
	p.GROUPLINE ASC