SELECT
	r2.GROUPNUMBER,
	r2.GROUPTYPECODE,
	r2.LINETYPE,
	r2.SEQUENCE,
	r2.SUBSEQUENCE,
	r2.ITEMTYPEAFICODE,
	r2.SUBCODE01,
	r2.SUFFIXCODE
FROM
	RECIPE r
LEFT JOIN RECIPECOMPONENT r2 ON	r2.RECIPENUMBERID = r.NUMBERID
LEFT JOIN RECIPE r3 ON r3.SUBCODE01 = r2.SUBCODE01 AND r3.SUFFIXCODE = r2.SUFFIXCODE
WHERE
	r.SUBCODE01 = '00001/00000'
	AND r.SUFFIXCODE = '001'