-- STOCK AKHIR & STOCK YG DIPAKAI FINISHING
WITH QTY_BALANCE AS (
	SELECT
		b.ITEMTYPECODE,
		b.DECOSUBCODE01,
		b.DECOSUBCODE02,
		b.DECOSUBCODE03,
		SUM(b.BASEPRIMARYQUANTITYUNIT) AS QTY,
		b.BASEPRIMARYUNITCODE AS SATUAN
	FROM
		BALANCE b
	WHERE 
		TRIM(b.LOGICALWAREHOUSECODE) = 'M512'
	GROUP BY	
		b.ITEMTYPECODE,
		b.DECOSUBCODE01,
		b.DECOSUBCODE02,
		b.DECOSUBCODE03,
		b.BASEPRIMARYUNITCODE
)
SELECT DISTINCT 
	s.ITEMTYPECODE,
	CASE
		WHEN s.ITEMTYPECODE = 'PST' THEN TRIM(s.DECOSUBCODE01) 
		WHEN s.ITEMTYPECODE = 'DYC' THEN TRIM(s.DECOSUBCODE01) || '-' || TRIM(s.DECOSUBCODE02) || '-' || TRIM(s.DECOSUBCODE03)
	END	AS OBAT_FIN,
	p.LONGDESCRIPTION,
	qb.QTY,
	qb.SATUAN
FROM
	STOCKTRANSACTION s
LEFT JOIN PRODUCT p ON p.ITEMTYPECODE = s.ITEMTYPECODE 
					AND p.SUBCODE01 = s.DECOSUBCODE01 
					AND p.SUBCODE02 = s.DECOSUBCODE02 
					AND p.SUBCODE03 = s.DECOSUBCODE03
LEFT JOIN QTY_BALANCE qb ON qb.ITEMTYPECODE = s.ITEMTYPECODE 
					AND qb.DECOSUBCODE01 = s.DECOSUBCODE01 
					AND qb.DECOSUBCODE02 = s.DECOSUBCODE02 
					AND qb.DECOSUBCODE03 = s.DECOSUBCODE03
WHERE 
	s.LOGICALWAREHOUSECODE = 'M512'
	AND s.ITEMTYPECODE IN ('PST', 'DYC')
	AND NOT qb.QTY IS NULL
	AND s.DECOSUBCODE01 = 'E-2-008'
--	AND s.DECOSUBCODE02 = '2'
--	AND s.DECOSUBCODE03 = '008'
	
	
-- TRANSAKSI KELUAR
SELECT
	s.TRANSACTIONDATE,
	s.TRANSACTIONTIME,
	s.ITEMTYPECODE,
	CASE
		WHEN s.ITEMTYPECODE = 'PST' THEN TRIM(s.DECOSUBCODE01) 
		WHEN s.ITEMTYPECODE = 'DYC' THEN TRIM(s.DECOSUBCODE01) || '-' || TRIM(s.DECOSUBCODE02) || '-' || TRIM(s.DECOSUBCODE03)
	END	AS OBAT_FIN,
	s.BASEPRIMARYQUANTITY,
	s.BASEPRIMARYUOMCODE,
	s.PRODUCTIONORDERCODE
FROM
	STOCKTRANSACTION s
WHERE 
	s.TEMPLATECODE IN ('120', '098') -- ini DEFAULT kode transaksi masuk
	AND s.LOGICALWAREHOUSECODE = 'M512' -- ini DEFAULT kode gudang, biarin aja
	AND s.DECOSUBCODE01 = 'E-2-008' -- yg ini dari DECOSUBCODE01 query yg dipilih tapi kalau jenis ITEMTYPECODE nya itu bukan DYC, maka yg ini adalah kode lengkapnya E-6-043
--	AND s.DECOSUBCODE02 = '6' -- yg ini dari DECOSUBCODE02 query yg dipilih tapi kalau jenis ITEMTYPECODE nya itu bukan DYC, maka yg ini adalah kode lengkapnya E-6-043
--	AND s.DECOSUBCODE03 = '065' -- yg ini dari DECOSUBCODE03 query yg dipilih tapi kalau jenis ITEMTYPECODE nya itu bukan DYC, maka yg ini adalah kode lengkapnya E-6-043
	AND s.TRANSACTIONDATE >= '2026-04-29' -- ini adalah Tanggal Awal yg dipilih di inputan
ORDER BY
	s.TRANSACTIONDATE DESC, s.TRANSACTIONTIME DESC
	
	
-- TRANSAKSI MASUK
SELECT
	s.TRANSACTIONDATE,
	s.TRANSACTIONTIME,
	s.ITEMTYPECODE,
	CASE
		WHEN s.ITEMTYPECODE = 'PST' THEN TRIM(s.DECOSUBCODE01) 
		WHEN s.ITEMTYPECODE = 'DYC' THEN TRIM(s.DECOSUBCODE01) || '-' || TRIM(s.DECOSUBCODE02) || '-' || TRIM(s.DECOSUBCODE03)
	END	AS OBAT_FIN,
	s.BASEPRIMARYQUANTITY,
	s.BASEPRIMARYUOMCODE,
	s.PRODUCTIONORDERCODE 
FROM
	STOCKTRANSACTION s
WHERE 
	s.TEMPLATECODE IN ('304') -- ini DEFAULT kode transaksi masuk
	AND s.LOGICALWAREHOUSECODE = 'M512' -- ini DEFAULT kode gudang, biarin aja
	AND s.DECOSUBCODE01 = 'E' -- yg ini dari DECOSUBCODE01 query yg dipilih tapi kalau jenis ITEMTYPECODE nya itu bukan DYC, maka yg ini adalah kode lengkapnya E-6-043
	AND s.DECOSUBCODE02 = '6' -- yg ini dari DECOSUBCODE02 query yg dipilih tapi kalau jenis ITEMTYPECODE nya itu bukan DYC, maka yg ini adalah kode lengkapnya E-6-043
	AND s.DECOSUBCODE03 = '043' -- yg ini dari DECOSUBCODE03 query yg dipilih tapi kalau jenis ITEMTYPECODE nya itu bukan DYC, maka yg ini adalah kode lengkapnya E-6-043
	AND s.TRANSACTIONDATE >= '2026-04-27' -- ini adalah Tanggal Awal yg dipilih di inputan