SELECT
	USERGENERICGROUP.CODE AS KDMC,
	USERGENERICGROUP.LONGDESCRIPTION,
	USERGENERICGROUP.SHORTDESCRIPTION,
	USERGENERICGROUP.SEARCHDESCRIPTION,
	DMN.*,
	J1.JML AS JML_J1,
	J1.JQTY AS JQTY_J1,
	J2.JML AS JML_J2,
	J2.JQTY AS JQTY_J2,
	S1.IDS
FROM
	DB2ADMIN.USERGENERICGROUP
LEFT JOIN
(
		SELECT
			ADSTORAGE.VALUESTRING,
			AD1.VALUEDATE,
			AD2.VALUEDATE AS RMPREQDATE,
			AD7.VALUEDATE AS RMPREQDATETO,
			AD3.VALUEDECIMAL AS QTYSALIN,
			AD4.VALUEDECIMAL AS QTYOPIN ,
			AD5.VALUEDECIMAL AS QTYOPOUT,
			AD6.VALUESTRING AS STSOPR,
			ITXVIEWKNTORDER.*,
			CURRENT_TIMESTAMP AS TGLS,
			PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE
		FROM
			ITXVIEWKNTORDER
		LEFT OUTER JOIN DB2ADMIN.PRODUCTIONDEMAND ON PRODUCTIONDEMAND.CODE = ITXVIEWKNTORDER.PRODUCTIONDEMANDCODE
		LEFT OUTER JOIN DB2ADMIN.ADSTORAGE ON ADSTORAGE.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID	AND ADSTORAGE.NAMENAME = 'MachineNo'
		LEFT OUTER JOIN DB2ADMIN.ADSTORAGE AD1 ON AD1.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD1.NAMENAME = 'TglRencana'
		LEFT OUTER JOIN DB2ADMIN.ADSTORAGE AD2 ON AD2.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD2.NAMENAME = 'RMPReqDate'
		LEFT OUTER JOIN DB2ADMIN.ADSTORAGE AD3 ON AD3.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD3.NAMENAME = 'QtySalin'
		LEFT OUTER JOIN DB2ADMIN.ADSTORAGE AD4 ON AD4.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD4.NAMENAME = 'QtyOperIn'
		LEFT OUTER JOIN DB2ADMIN.ADSTORAGE AD5 ON AD5.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD5.NAMENAME = 'QtyOperOut'
		LEFT OUTER JOIN DB2ADMIN.ADSTORAGE AD6 ON AD6.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD6.NAMENAME = 'StatusOper'
		LEFT OUTER JOIN DB2ADMIN.ADSTORAGE AD7 ON AD7.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD7.NAMENAME = 'RMPGreigeReqDateTo'
		WHERE
			ITXVIEWKNTORDER.ITEMTYPEAFICODE = 'KGF'
			AND (PRODUCTIONDEMAND.PROGRESSSTATUS = '2' OR AD6.VALUESTRING = '1'	)
		ORDER BY
			ITXVIEWKNTORDER.INITIALSCHEDULEDACTUALDATE,
			AD1.VALUEDATE ASC ) DMN ON (DMN.VALUESTRING = USERGENERICGROUP.CODE	OR DMN.SCHEDULEDRESOURCECODE = USERGENERICGROUP.CODE)
LEFT OUTER JOIN (
		SELECT
			DEMANDCODE,
			COUNT(BASEPRIMARYQUANTITY) AS JML,
			SUM(BASEPRIMARYQUANTITY) AS JQTY
		FROM
			VIEWPRODDEMANDELEMENTS
		WHERE
			PROGRESSSTATUS = '0'
			AND COMPANYCODE = '100'
		GROUP BY
			DEMANDCODE) J1 ON J1.DEMANDCODE = DMN.CODE
LEFT OUTER JOIN (
		SELECT
			DEMANDCODE,
			COUNT(WEIGHTREALNET) AS JML,
			SUM(WEIGHTREALNET) AS JQTY
		FROM
			ELEMENTSINSPECTION
		WHERE
			ELEMENTITEMTYPECODE = 'KGF'
			AND COMPANYCODE = '100'
		GROUP BY
			DEMANDCODE) J2 ON J2.DEMANDCODE = DMN.CODE
LEFT OUTER JOIN (
		SELECT
			DEMANDCODE,
			COUNT(WEIGHTREALNET) AS JML,
			SUM(WEIGHTREALNET) AS JQTY
		FROM 
									ELEMENTSINSPECTION
		WHERE
			ELEMENTITEMTYPECODE = 'KGF'
			AND COMPANYCODE = '100'
			AND SUBSTR(INSPECTIONSTARTDATETIME, 1, 10)= '$Awal'
		GROUP BY
			DEMANDCODE) J3 ON	J3.DEMANDCODE = DMN.CODE
LEFT OUTER JOIN (
		SELECT
			PRODUCTIONDEMANDCODE,
			trim(LISTAGG (PROGRESSSTATUS , ',') WITHIN GROUP(ORDER BY PRODUCTIONDEMANDCODE ASC)) AS IDS
		FROM
			PRODUCTIONDEMANDSTEP
		WHERE
			(OPERATIONCODE = 'INS1'	OR OPERATIONCODE = 'KNT1')AND ITEMTYPEAFICOMPANYCODE = '100'
		GROUP BY
			PRODUCTIONDEMANDCODE) S1 ON S1.PRODUCTIONDEMANDCODE = DMN.CODE
WHERE
	USERGENERICGROUP.USERGENERICGROUPTYPECODE = 'MCK' AND 
	USERGENERICGROUP.USERGENGROUPTYPECOMPANYCODE = '100' AND 
	USERGENERICGROUP.OWNINGCOMPANYCODE = '100'