SELECT
    DISTINCT STEPNUMBER, 
FROM
    ITXVIEW_POSISI_KARTU_KERJA
WHERE
    PRODUCTIONORDERCODE = '00248040'
    AND PRODUCTIONDEMANDCODE = '00419133'
    AND NOT STATUS_OPERATION IN ('Entered', 'Progress')
    AND (OPERATIONCODE = 'BKR1' OR OPERATIONCODE = 'MAT1' OR OPERATIONCODE = 'BKN1' OR OPERATIONCODE = 'BAT1' OR OPERATIONCODE = 'BAT2' OR
        OPERATIONCODE = 'WAIT35' OR OPERATIONCODE = 'WAIT40' OR OPERATIONCODE = 'WAIT37' OR OPERATIONCODE = 'PRE1' OR OPERATIONCODE = 'SUE1' 
        OR OPERATIONCODE = 'WAIT33' OR OPERATIONCODE = 'WAIT36')
ORDER BY
    STEPNUMBER DESC 
FETCH FIRST 1 ROWS ONLY