SELECT
	i.SALESORDERCODE,
	i.LEGALNAME1,
	p.LONGDESCRIPTION AS JENIS_KAIN,
	i.NOTETAS_KGF || '/' || TRIM(i.SUBCODE01) || '-' || TRIM(i.SUBCODE02) || '-' || TRIM(i.SUBCODE03) || '-' || TRIM(i.SUBCODE04) AS ITEMCODE,
	i.NOTETAS,
	i.EXTERNALREFERENCE AS NO_PO,
	COALESCE(i2.GRAMASI_KFF, i2.GRAMASI_FKF) AS GRAMASI,
	i3.LEBAR,
	CASE
		a.VALUESTRING WHEN '1' THEN 'L/D'
		WHEN '2' THEN 'First Lot'
		WHEN '3' THEN 'Original'
		WHEN '4' THEN 'Previous Order'
		WHEN '5' THEN 'Master Color'
		WHEN '6' THEN 'Lampiran Buyer'
		WHEN '7' THEN 'Body'
		ELSE ''
	END AS COLOR_STANDARD,
	TRIM(i.SUBCODE01) AS SUBCODE01,
	TRIM(i.SUBCODE02) AS SUBCODE02,
	TRIM(i.SUBCODE03) AS SUBCODE03,
	TRIM(i.SUBCODE04) AS SUBCODE04,
	TRIM(i.SUBCODE05) AS SUBCODE05,
	TRIM(i.SUBCODE06) AS SUBCODE06,
	TRIM(i.SUBCODE07) AS SUBCODE07,
	TRIM(i.SUBCODE08) AS SUBCODE08,
	TRIM(i.SUBCODE09) AS SUBCODE09,
	TRIM(i.SUBCODE10) AS SUBCODE10
FROM
	ITXVIEWBONORDER i
LEFT JOIN PRODUCT p ON p.ITEMTYPECODE = i.ITEMTYPEAFICODE
	AND p.SUBCODE01 = i.SUBCODE01
	AND p.SUBCODE02 = i.SUBCODE02
	AND p.SUBCODE03 = i.SUBCODE03
	AND p.SUBCODE04 = i.SUBCODE04
	AND p.SUBCODE05 = i.SUBCODE05
	AND p.SUBCODE06 = i.SUBCODE06
	AND p.SUBCODE07 = i.SUBCODE07
	AND p.SUBCODE08 = i.SUBCODE08
	AND p.SUBCODE09 = i.SUBCODE09
	AND p.SUBCODE10 = i.SUBCODE10
LEFT JOIN ITXVIEWGRAMASI i2 ON i2.SALESORDERCODE = i.SALESORDERCODE	AND i2.ORDERLINE = i.ORDERLINE
LEFT JOIN ITXVIEWLEBAR i3 ON i3.SALESORDERCODE = i.SALESORDERCODE AND i3.ORDERLINE = i.ORDERLINE
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = i.ABSUNIQUEID_SALESORDERLINE AND a.FIELDNAME = 'ColorStandard'
WHERE
	i.SALESORDERCODE = 'EXP2500348'