SELECT
	*
FROM
	ITXVIEW_SHIPPING_MARK
WHERE 
 	CODE = 'EXP2400499'
 	
 	
 SELECT SHIPPING_MARK,* FROM ITXVIEWBONORDER i WHERE SALESORDERCODE = 'EXP2400499'
 
 
 SELECT SALESORDER.CODE,ITXVIEWBONORDER.SALESORDERCODE,
       ITXVIEWBONORDER.TERMSOFSHPLONGDESCRIPTION,
       ITXVIEWBONORDER.PAYMENTMETHODLONGDESCRIPTION,ITXVIEWBONORDER.ORDERLINE,ITXVIEWBONORDER.EXTERNALREFERENCE,
       ITXVIEWBONORDER.INTERNALREFERENCE_SALESORDERLINE,
       ITXVIEWBONORDER.ITEMTYPEAFICODE,ITXVIEWBONORDER.SUBCODE01,
       ITXVIEWBONORDER.SUBCODE02,ITXVIEWBONORDER.SUBCODE03,ITXVIEWBONORDER.SUBCODE04,
       ITXVIEWBONORDER.SUBCODE05,ITXVIEWBONORDER.SUBCODE06,
       ITXVIEWBONORDER.SUBCODE07,ITXVIEWBONORDER.SUBCODE08,ITXVIEWBONORDER.SUBCODE09,
       ITXVIEWBONORDER.SUBCODE10,ITXVIEWBONORDER.USERPRIMARYUOMCODE,
       ITXVIEWBONORDER.USERPRIMARYQUANTITY,
       ITXVIEWBONORDER.USERSECONDARYUOMCODE,ITXVIEWBONORDER.USERSECONDARYQUANTITY,
       ITXVIEWBONORDER.ABSUNIQUEID_SALESORDERLINE,ITXVIEWBONORDER.ORDERDATE,
       ITXVIEWBONORDER.ORDPRNCUSTOMERSUPPLIERCODE,
       ITXVIEWBONORDER.ORDERPARTNERBRANDCODE,ITXVIEWBONORDER.DESCRIPTION,
       ITXVIEWBONORDER.INTERNALREFERENCE_SALESORDER,ITXVIEWBONORDER.STATISTICALGROUPCODE,
       ITXVIEWBONORDER.CREATIONUSER,ITXVIEWBONORDER.ABSUNIQUEID_SALESORDER,
       ITXVIEWBONORDER.ABSUNIQUEID_ORDERPARTNER,ITXVIEWBONORDER.LEGALNAME1,
       ITXVIEWBONORDER.ADDRESSEE,ITXVIEWBONORDER.LONGDESCRIPTION,
       ITXVIEWBONORDER.DEMAND,ITXVIEWBONORDER.ADDITIONALDATA,
       ITXVIEWBONORDER.ADDITIONALDATA2,ITXVIEWBONORDER.ADDITIONALDATA3,
       ITXVIEWBONORDER.ADDITIONALDATA4,ITXVIEWBONORDER.ADDITIONALDATA5,
       ITXVIEWBONORDER.QTY,ITXVIEWBONORDER.QTY2,ITXVIEWBONORDER.QTY3,
       ITXVIEWBONORDER.QTY4,ITXVIEWBONORDER.QTY5,ITXVIEWBONORDER.DATE_AKTUAL,
       ITXVIEWBONORDER.DATE_AKTUAL2,ITXVIEWBONORDER.DATE_AKTUAL3,
       ITXVIEWBONORDER.DATE_AKTUAL4,ITXVIEWBONORDER.DATE_AKTUAL5,ITXVIEWBONORDER.AKJ,
       ITXVIEWBONORDER.LEGACYORDER,
       ITXVIEWBONORDER.RESERVATION_SUBCODE04,ITXVIEWBONORDER.SHIPPING_MARK,ITXVIEWBONORDER.QTY6,
       ITXVIEWBONORDER.DATE_AKTUAL6,ITXVIEWBONORDER.PROD_ORDER_AKJ,
       ITXVIEWBONORDER.SALESORDER_AKJ,ITXVIEWBONORDER.RESERVATION_SUBCODE02,
       ITXVIEWBONORDER.RESERVATION_SUBCODE03,ITXVIEWBONORDER.PROD_ORDER_AKJ2,
       ITXVIEWBONORDER.SALESORDER_AKJ2,ITXVIEWBONORDER.PROD_ORDER_AKJ3,
       ITXVIEWBONORDER.SALESORDER_AKJ3,ITXVIEWBONORDER.DATE_AKTUAL_TO,
       ITXVIEWBONORDER.DATE_AKTUAL_TO2,ITXVIEWBONORDER.DATE_AKTUAL_TO3,
       ITXVIEWBONORDER.DATE_AKTUAL_TO4,ITXVIEWBONORDER.DATE_AKTUAL_TO5,
       ITXVIEWBONORDER.DATE_AKTUAL_TO6,
       ITXVIEWBONORDER.PRODUCTIONORDER_AKW,ITXVIEWBONORDER.NOTETAS,ITXVIEWBONORDER.ADDITIONALDATA6,
       ITXVIEWBONORDER.QTY7,ITXVIEWBONORDER.DATE_AKTUAL7,
       ITXVIEWBONORDER.DATE_AKTUAL_TO7 
FROM DB2ADMIN.SALESORDER SALESORDER LEFT OUTER JOIN 
       DB2ADMIN.ITXVIEWBONORDER ITXVIEWBONORDER ON 
       SALESORDER.CODE=ITXVIEWBONORDER.SALESORDERCODE 
WHERE
	SALESORDER.CODE = 'EXP2400499'
ORDER BY SALESORDER.CODE, ITXVIEWBONORDER.SUBCODE03, 
       ITXVIEWBONORDER.ORDERLINE