-- DB2ADMIN.ITXVIEWRESEP source
DROP VIEW ITXVIEWRESEP;
--CREATE VIEW ITXVIEWRESEP AS   
SELECT
    	VIEWPRODUCTIONRESERVATION.COMPANYCODE,
       VIEWPRODUCTIONRESERVATION.GROUPLINE,
       VIEWPRODUCTIONRESERVATION.PRODRESERVATIONLINKGROUPCODE,
       VIEWPRODUCTIONRESERVATION.SUBCODE01 AS SUBCODE01_RESERVATION,
       VIEWPRODUCTIONRESERVATION.PICKUPQUANTITY,
       VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE,
       VIEWPRODUCTIONRESERVATION.SUFFIXCODE AS SUFFIXCODE_RESERVATION,
       ITXVIEWRESEP1.RECIPENUMBERID,
       ITXVIEWRESEP1.SUFFIXCODE,
       ITXVIEWRESEP1.GROUPNUMBER,
       ITXVIEWRESEP1.SEQUENCE,
       ITXVIEWRESEP1.CODE,
       ITXVIEWRESEP1.SUBCODE,
       ITXVIEWRESEP1.CONSUMPTION,
       ITXVIEWRESEP1.COMMENTLINE,
       ITXVIEWRESEP1.LONGDESCRIPTION,
       ITXVIEWRESEP1.RECIPESUBCODE01,
       ITXVIEWRESEP1.SUBCODE01,
       ITXVIEWRESEP1.SUBCODE02,
       ITXVIEWRESEP1.SUBCODE03,
       ITXVIEWRESEP1.CONSUMPTIONTYPE,
       RECIPE.RECIPETYPE,
       RECIPE.PICKUPPERCENTAGE,
       RECIPE.RESIDUALBATHVOLUME
FROM
    VIEWPRODUCTIONRESERVATION VIEWPRODUCTIONRESERVATION
LEFT JOIN RECIPE RECIPE ON
    VIEWPRODUCTIONRESERVATION.SUFFIXCODE = RECIPE.SUFFIXCODE
    AND VIEWPRODUCTIONRESERVATION.SUBCODE01 = RECIPE.SUBCODE01
LEFT JOIN ITXVIEWRESEP1 ON
    RECIPE.NUMBERID = ITXVIEWRESEP1.RECIPENUMBERID;