SELECT
	ITXVIEW_SUBPACKINGLIST_EXIM3.DESC_OF_GOODS,
	ITXVIEW_SUBPACKINGLIST_EXIM3.PROVISIONALCODE,
	ITXVIEW_SUBPACKINGLIST_EXIM3.PROVISIONALCOUNTERCODE,
	ITXVIEW_SUBPACKINGLIST_EXIM3.COMPANYCODE,
	ITXVIEW_SUBPACKINGLIST_EXIM3.PROVISIONALDOCUMENTDATE,
	ITXVIEW_SUBPACKINGLIST_EXIM3.EXTERNALREFERENCE,
	ITXVIEW_SUBPACKINGLIST_EXIM3.EXTERNALITEM,
	ITXVIEW_SUBPACKINGLIST_EXIM3.LOTCODE,
	ITXVIEW_SUBPACKINGLIST_EXIM3.NO_ORDER,
	ITXVIEW_SUBPACKINGLIST_EXIM3.DECOSUBCODE02,
	ITXVIEW_SUBPACKINGLIST_EXIM3.DECOSUBCODE03,
	ITXVIEW_SUBPACKINGLIST_EXIM3.ITEMDESCRIPTION
FROM
	(
		DB2ADMIN.WRKDOCUMENTPRINT WRKDOCUMENTPRINT
	LEFT OUTER JOIN DB2ADMIN.SALESDOCUMENT SALESDOCUMENT ON
		WRKDOCUMENTPRINT.SALDOCPROVISIONALCOUNTERCODE = SALESDOCUMENT.PROVISIONALCOUNTERCODE
		AND WRKDOCUMENTPRINT.SALESDOCUMENTPROVISIONALCODE = SALESDOCUMENT.PROVISIONALCODE
	)
LEFT OUTER JOIN DB2ADMIN.ITXVIEW_SUBPACKINGLIST_EXIM3 ITXVIEW_SUBPACKINGLIST_EXIM3 ON
	SALESDOCUMENT.COMPANYCODE = ITXVIEW_SUBPACKINGLIST_EXIM3.COMPANYCODE
	AND SALESDOCUMENT.PROVISIONALCODE = ITXVIEW_SUBPACKINGLIST_EXIM3.PROVISIONALCODE
	AND SALESDOCUMENT.PROVISIONALCOUNTERCODE = ITXVIEW_SUBPACKINGLIST_EXIM3.PROVISIONALCOUNTERCODE
WHERE
	(
		(
			WRKDOCUMENTPRINT.SALESDOCUMENTCOMPANYCODE = '100'
		)
	)
	AND (
		(
			WRKDOCUMENTPRINT.CREATIONTIMESTAMP = 368810
		)
	)
ORDER BY
	ITXVIEW_SUBPACKINGLIST_EXIM3.DESC_OF_GOODS