SELECT
	SALESORDER.CODE,
	SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE,
	SALESORDERLINE.ITEMTYPEAFICODE,
	SALESORDERLINE.SUBCODE01,
	SALESORDERLINE.SUBCODE02,
	SALESORDERLINE.SUBCODE03,
	SALESORDERLINE.SUBCODE04,
	SALESORDERLINE.SUBCODE05,
	SALESORDERLINE.SUBCODE06,
	SALESORDERLINE.SUBCODE07,
	SALESORDERLINE.SUBCODE08,
	SALESORDERLINE.SUBCODE09,
	SALESORDERLINE.SUBCODE10,
	SALESORDERLINE.EXTERNALITEM
FROM
	DB2ADMIN.SALESORDER SALESORDER
LEFT OUTER JOIN DB2ADMIN.SALESORDERLINE 
       SALESORDERLINE ON
	SALESORDER.CODE = SALESORDERLINE.SALESORDERCODE
	AND 
       SALESORDER.COUNTERCODE = SALESORDERLINE.SALESORDERCOUNTERCODE
WHERE
	SALESORDER.CODE = 'SAM2400091'
--	AND SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE = 'C0001118'
--	AND SALESORDERLINE.ITEMTYPEAFICODE = 'KFF'
--	AND SALESORDERLINE.SUBCODE01 = 'C'
--	AND SALESORDERLINE.SUBCODE02 = 'SJY'
--	AND SALESORDERLINE.SUBCODE03 = '11256'
--	AND SALESORDERLINE.SUBCODE04 = 'L01'
--	AND SALESORDERLINE.SUBCODE05 = '190789L'