SELECT
    p.OPERATIONCODE,
    p.STEPNUMBER,
    p.OPSTEPGROUPCODE
FROM
    (
    SELECT
        STEPNUMBER,
        PRODUCTIONORDERCODE
    FROM
        PRODUCTIONDEMANDSTEP
    WHERE
        PRODUCTIONORDERCODE = '00157631'
        AND (OPERATIONCODE = 'BAT2'
            OR OPERATIONCODE = 'BKN1'
            OR OPERATIONCODE = 'JHP1'
            OR OPERATIONCODE = 'BAT2'
            OR OPERATIONCODE = 'BEL1'
            OR OPERATIONCODE = 'BAT3'
            OR OPERATIONCODE = 'BBS1'
            OR OPERATIONCODE = 'WAIT36') ORDER BY STEPNUMBER DESC LIMIT 1 ) s
LEFT OUTER JOIN PRODUCTIONDEMANDSTEP p ON p.PRODUCTIONORDERCODE = s.PRODUCTIONORDERCODE
    									AND p.STEPNUMBER > s.STEPNUMBER
ORDER BY
	p.STEPNUMBER ASC