DROP VIEW ITXVIEW_PO_SHIPPING_MARK_ELEMENT;
--CREATE VIEW ITXVIEW_PO_SHIPPING_MARK_ELEMENT AS 
SELECT
    --   p.CODE,
    p.DLVSALORDERLINESALESORDERCODE,
    P.ORIGDLVSALORDLINESALORDERCODE,
    p.ORIGDLVSALORDERLINEORDERLINE,
    e.ELEMENTCODE,
    CASE
        WHEN s2.EXTERNALREFERENCE = NULL OR s2.EXTERNALREFERENCE = '' THEN s.EXTERNALREFERENCE
        ELSE s2.EXTERNALREFERENCE
    END AS EXTERNALREFERENCE,
    CASE
        WHEN s2.INTERNALREFERENCE = NULL OR s2.INTERNALREFERENCE = '' THEN s.INTERNALREFERENCE
        ELSE s2.INTERNALREFERENCE
    END AS INTERNALREFERENCE
FROM
    PRODUCTIONDEMAND p
LEFT JOIN ELEMENTSINSPECTION e ON e.DEMANDCODE = p.CODE
LEFT JOIN SALESORDERLINE s ON s.SALESORDERCODE = p.ORIGDLVSALORDLINESALORDERCODE
    AND s.ORDERLINE = p.ORIGDLVSALORDERLINEORDERLINE
--    AND s.SUBCODE01 = p.SUBCODE01
--    AND s.SUBCODE02 = p.SUBCODE02
--    AND s.SUBCODE03 = p.SUBCODE03
--    AND s.SUBCODE04 = p.SUBCODE04
--    AND s.SUBCODE05 = p.SUBCODE05
--    AND s.SUBCODE06 = p.SUBCODE06
--    AND s.SUBCODE07 = p.SUBCODE07
--    AND s.SUBCODE08 = p.SUBCODE08
--    AND s.SUBCODE09 = p.SUBCODE09
--    AND s.SUBCODE10 = p.SUBCODE10
LEFT JOIN SALESORDER s2 ON s2.CODE = p.ORIGDLVSALORDLINESALORDERCODE
WHERE
    e.ELEMENTCODE IS NOT NULL
    --   AND p.DLVSALORDERLINESALESORDERCODE ='EXP2400161'
       AND e.ELEMENTCODE ='00263953001';