SELECT
	ITXVIEWRESEP.RECIPENUMBERID,
	ITXVIEWRESEP.SUFFIXCODE,
	ITXVIEWRESEP.SUBCODE01,
	ITXVIEWRESEP.SUBCODE02,
	ITXVIEWRESEP.SUBCODE03,
	COALESCE(ITXVIEWRESEP2.GROUPNUMBER, ITXVIEWRESEP.GROUPNUMBER) AS GROUPNUMBER,
	CASE
		WHEN ITXVIEWRESEP.CODE = '' THEN ITXVIEWRESEP2.CODE
		ELSE ITXVIEWRESEP.CODE
	END	AS CODE,
	CASE
		WHEN ITXVIEWRESEP.SUBCODE = '' THEN ITXVIEWRESEP2.SUBCODE
		ELSE ITXVIEWRESEP.SUBCODE
	END	AS SUBCODE,
	CASE
		WHEN ITXVIEWRESEP.COMMENTLINE IS NULL OR ITXVIEWRESEP.COMMENTLINE = '' THEN ITXVIEWRESEP2.COMMENTLINE
		ELSE ITXVIEWRESEP.COMMENTLINE
	END	AS COMMENTLINE,
	CASE
		WHEN ITXVIEWRESEP.LONGDESCRIPTION IS NULL OR ITXVIEWRESEP.LONGDESCRIPTION = '' THEN ITXVIEWRESEP2.LONGDESCRIPTION
		ELSE ITXVIEWRESEP.LONGDESCRIPTION
	END	AS LONGDESCRIPTION,
	CASE
		WHEN ITXVIEWRESEP.CONSUMPTION IS NULL OR ITXVIEWRESEP.CONSUMPTION = 0 THEN ITXVIEWRESEP2.CONSUMPTION
		ELSE ITXVIEWRESEP.CONSUMPTION
	END	AS CONSUMPTION,
	CASE
		WHEN 
			CASE
				WHEN ITXVIEWRESEP.CONSUMPTIONTYPE IS NULL OR ITXVIEWRESEP.CONSUMPTIONTYPE = '' THEN ITXVIEWRESEP2.CONSUMPTIONTYPE
				ELSE ITXVIEWRESEP.CONSUMPTIONTYPE
			END = '1' THEN 'g/l'
		WHEN
			CASE
				WHEN ITXVIEWRESEP.CONSUMPTIONTYPE IS NULL OR ITXVIEWRESEP.CONSUMPTIONTYPE = '' THEN ITXVIEWRESEP2.CONSUMPTIONTYPE
				ELSE ITXVIEWRESEP.CONSUMPTIONTYPE
			END = '2' THEN '%'
	END	AS CONSUMPTIONTYPE,
	CASE
		WHEN ITXVIEWRESEP.RECIPETYPE = '1' THEN CAST( ((ITXVIEWRESEP.PICKUPPERCENTAGE/100 * 1000) + ITXVIEWRESEP.RESIDUALBATHVOLUME) * ITXVIEWRESEP2.CONSUMPTION AS DECIMAL(18, 4))
		ELSE 
			CASE
				WHEN ITXVIEWRESEP2.CONSUMPTIONTYPE = '1' THEN CAST( ((1000 * VIEWPRODUCTIONRESERVATION.PICKUPQUANTITY) * ITXVIEWRESEP2.CONSUMPTION) / 1000 AS DECIMAL(18, 4))
				WHEN ITXVIEWRESEP2.CONSUMPTIONTYPE = '2' THEN CAST( (1000 * (ITXVIEWRESEP2.CONSUMPTION/100)) * 1000 AS DECIMAL(18, 4))
			END
	END AS QTY,
	CASE 
		WHEN ITXVIEWRESEP2.CONSUMPTIONTYPE = '1' THEN 'Kg'
		WHEN ITXVIEWRESEP2.CONSUMPTIONTYPE = '2' THEN 'g'
	END AS UOM 
FROM
	VIEWPRODUCTIONRESERVATION VIEWPRODUCTIONRESERVATION
LEFT JOIN ITXVIEWRESEP ITXVIEWRESEP ON VIEWPRODUCTIONRESERVATION.SUFFIXCODE = ITXVIEWRESEP.SUFFIXCODE_RESERVATION
	AND VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE = ITXVIEWRESEP.PRODUCTIONORDERCODE
	AND VIEWPRODUCTIONRESERVATION.SUBCODE01 = ITXVIEWRESEP.SUBCODE01_RESERVATION
	AND VIEWPRODUCTIONRESERVATION.COMPANYCODE = ITXVIEWRESEP.COMPANYCODE
LEFT JOIN ITXVIEWRESEP2 ITXVIEWRESEP2 ON ITXVIEWRESEP2.RECIPESUBCODE01 = ITXVIEWRESEP.CODE AND ITXVIEWRESEP2.RECIPESUFFIXCODE = ITXVIEWRESEP.SUFFIXCODE
WHERE 
	VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE = '00173537'
	AND VIEWPRODUCTIONRESERVATION.GROUPLINE = '403'
	AND NOT 
		CASE
			WHEN 
				CASE
					WHEN ITXVIEWRESEP.CONSUMPTIONTYPE IS NULL OR ITXVIEWRESEP.CONSUMPTIONTYPE = '' THEN ITXVIEWRESEP2.CONSUMPTIONTYPE
					ELSE ITXVIEWRESEP.CONSUMPTIONTYPE
				END = '1' THEN 'g/l'
			WHEN
				CASE
					WHEN ITXVIEWRESEP.CONSUMPTIONTYPE IS NULL OR ITXVIEWRESEP.CONSUMPTIONTYPE = '' THEN ITXVIEWRESEP2.CONSUMPTIONTYPE
					ELSE ITXVIEWRESEP.CONSUMPTIONTYPE
				END = '2' THEN '%'
		END IS NULL 
ORDER BY
	ITXVIEWRESEP.GROUPNUMBER,
	ITXVIEWRESEP.SEQUENCE,
	ITXVIEWRESEP2.GROUPNUMBER,
	ITXVIEWRESEP2.SEQUENCE ASC