SELECT
	SALESDOCUMENT.COMPANYCODE,
	SALESDOCUMENT.PROVISIONALCOUNTERCODE,
	SALESDOCUMENT.PROVISIONALCODE,
	ITXVIEW_SUBPACKINGLIST_EXIM2.DESC_OF_GOODS,
	ITXVIEW_SUBPACKINGLIST_EXIM2.PROVISIONALCODE,
	ITXVIEW_SUBPACKINGLIST_EXIM2.PROVISIONALDOCUMENTDATE,
	ITXVIEW_SUBPACKINGLIST_EXIM2.EXTERNALREFERENCE,
	ITXVIEW_SUBPACKINGLIST_EXIM2.EXTERNALITEM,
	ITXVIEW_SUBPACKINGLIST_EXIM2.LOTCODE,
	ITXVIEW_SUBPACKINGLIST_EXIM2.NO_ORDER,
	ITXVIEW_SUBPACKINGLIST_EXIM2.DECOSUBCODE02,
	ITXVIEW_SUBPACKINGLIST_EXIM2.DECOSUBCODE03,
	ITXVIEW_SUBPACKINGLIST_EXIM2.ITEMDESCRIPTION,
	ITXVIEW_SUBPACKINGLIST_EXIM2.COMPANYCODE,
	ITXVIEW_SUBPACKINGLIST_EXIM2.WIDTH
FROM
	DB2ADMIN.SALESDOCUMENT SALESDOCUMENT
LEFT OUTER JOIN 
       DB2ADMIN.ITXVIEW_SUBPACKINGLIST_EXIM2 ITXVIEW_SUBPACKINGLIST_EXIM2 ON
	SALESDOCUMENT.PROVISIONALCODE = ITXVIEW_SUBPACKINGLIST_EXIM2.PROVISIONALCODE
	AND 
       SALESDOCUMENT.COMPANYCODE = ITXVIEW_SUBPACKINGLIST_EXIM2.COMPANYCODE
WHERE
	SALESDOCUMENT.PROVISIONALCODE = 'GSP2400016'
ORDER BY
	ITXVIEW_SUBPACKINGLIST_EXIM2.DESC_OF_GOODS