SELECT 
	 SALESORDERCODE,
	 ORDERLINE,
	 ITEM,
	 WARNA,
	 NETTO,
	 SUM(BRUTO) AS BRUTO,
	 SUM(SUDAH_BAGI_KAIN) AS SUDAH_BAGI_KAIN,
	 SUM(BALANCE_BELUM_BAGI_KAIN) AS BALANCE_BELUM_BAGI_KAIN
FROM (
	WITH QTY_BRUTO AS (
	SELECT
	    i.CODE,
	    i.ORIGDLVSALORDLINESALORDERCODE,
	    i.ORIGDLVSALORDERLINEORDERLINE,
	    SUM(i.USERPRIMARYQUANTITY) AS KFF
	FROM
	    ITXVIEWKGBRUTOBONORDER2 i
	GROUP BY 
	    i.CODE,
	    i.ORIGDLVSALORDLINESALORDERCODE,
	    i.ORIGDLVSALORDERLINEORDERLINE
	)
	SELECT DISTINCT 
		p.code,
		a.VALUESTRING,
		p.CREATIONUSER,
	    i.SALESORDERCODE,
	    i.ORDERLINE,
	    TRIM(i.SUBCODE02) || '-' || TRIM(i.SUBCODE03) AS ITEM,
	    i.WARNA,
	    ROUND(i.BASEPRIMARYQUANTITY) AS NETTO,
	    SUM(COALESCE(a2.VALUEDECIMAL, COALESCE(qb.KFF, p.USERPRIMARYQUANTITY))) AS BRUTO,
	    SUM(p2.USEDUSERPRIMARYQUANTITY) AS SUDAH_BAGI_KAIN,
	    SUM(COALESCE(a2.VALUEDECIMAL, qb.KFF)) - SUM(p2.USEDUSERPRIMARYQUANTITY) AS BALANCE_BELUM_BAGI_KAIN
	FROM
	    ITXVIEWBONORDER i 
	LEFT JOIN PRODUCTIONDEMAND p ON p.CODE = i.DEMAND 
	LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p.ABSUNIQUEID AND a.FIELDNAME = 'OriginalPDCode'
	LEFT JOIN ITXVIEWCOLOR i2 ON i2.ITEMTYPECODE = i.ITEMTYPEAFICODE 
	                        AND i2.SUBCODE01 = i.SUBCODE01
	                        AND i2.SUBCODE02 = i.SUBCODE02 
	                        AND i2.SUBCODE03 = i.SUBCODE03 
	                        AND i2.SUBCODE04 = i.SUBCODE04 
	                        AND i2.SUBCODE05 = i.SUBCODE05 
	                        AND i2.SUBCODE06 = i.SUBCODE06 
	                        AND i2.SUBCODE07 = i.SUBCODE07 
	                        AND i2.SUBCODE08 = i.SUBCODE08 
	                        AND i2.SUBCODE09 = i.SUBCODE09 
	                        AND i2.SUBCODE10 = i.SUBCODE10
	LEFT JOIN QTY_BRUTO qb ON qb.ORIGDLVSALORDLINESALORDERCODE = i.SALESORDERCODE AND qb.ORIGDLVSALORDERLINEORDERLINE = i.ORDERLINE AND qb.CODE = p.CODE
	LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = p.ABSUNIQUEID AND a2.FIELDNAME = 'OriginalBruto'
	LEFT JOIN PRODUCTIONRESERVATION p2 ON p2.ORDERCODE = i.DEMAND AND p2.ITEMTYPEAFICODE = 'KGF'
	WHERE 
	    i.SALESORDERCODE = ''
		AND (
			a.VALUESTRING IS NULL-- asli (bukan salinan)
	        OR p.CREATIONUSER IN ('kukuh.bayu','yogi.rahmansyah')-- salinan tapi hanya 2 user ini
	    	)
	GROUP BY
		p.code,
		a.VALUESTRING,
		p.CREATIONUSER,
	    i.SALESORDERCODE,
	    i.ORDERLINE,
	    i.SUBCODE02,
	    i.SUBCODE03,
	    i.WARNA,
	    i.BASEPRIMARYQUANTITY
	ORDER BY 
	    i.ORDERLINE
	ASC)
GROUP BY
	SALESORDERCODE,
	 ORDERLINE,
	 ITEM,
	 WARNA,
	 NETTO