SELECT SUBCODE01,SUBCODE02,SUBCODE03,SUBCODE04,SUBCODE05,SUBCODE06,SUBCODE07,SUBCODE08 FROM SALESORDERLINE WHERE SALESORDERCODE = 'EXP2400588' AND ORDERLINE = '30'

SELECT  
    LISTAGG(DISTINCT '''' || TRIM(s.TRANSACTIONNUMBER) || '''', ', ') AS TRANSACTIONNUMBER
--    *
FROM
    STOCKTRANSACTION s
WHERE
    s.LOGICALWAREHOUSECODE = 'M031'
    AND s.PROJECTCODE = 'EXP2400588'
    AND (s.TEMPLATECODE = '313' OR s.TEMPLATECODE = '098')
    AND s.DECOSUBCODE01 = 'C                   '
    AND s.DECOSUBCODE02 = 'HJY' 
    AND s.DECOSUBCODE03 = '18402     '
    AND s.DECOSUBCODE04 = 'L01'
    AND s.DECOSUBCODE05 = '210648L   '
    AND s.DECOSUBCODE06 = 'B510      '
    AND s.DECOSUBCODE07 = '-'
    AND s.DECOSUBCODE08 = '-'
    
    
SELECT DISTINCT 
    s.PROJECTCODE,
    s.LOTCODE,
    SUM(s.USERPRIMARYQUANTITY) AS QTY_KG,
    SUM(s.USERSECONDARYQUANTITY) AS QTY_YD_MTR
FROM
    STOCKTRANSACTION s
WHERE
    s.TRANSACTIONNUMBER IN ('000008679827', '000008682748')  
    AND (s.TEMPLATECODE = '314' OR s.TEMPLATECODE = '098')
GROUP BY
    s.PROJECTCODE,
    s.LOTCODE