SELECT
	TRIM(PRODUCTIONORDERCODE) AS PRODUCTIONORDERCODE,
	TRIM(DEAMAND) AS DEMAND,
	ORIGDLVSALORDERLINEORDERLINE,
	PROJECTCODE,
	ORDPRNCUSTOMERSUPPLIERCODE,
	TRIM(SUBCODE01) AS SUBCODE01, TRIM(SUBCODE02) AS SUBCODE02, TRIM(SUBCODE03) AS SUBCODE03, TRIM(SUBCODE04) AS SUBCODE04,
	TRIM(SUBCODE05) AS SUBCODE05, TRIM(SUBCODE06) AS SUBCODE06, TRIM(SUBCODE07) AS SUBCODE07, TRIM(SUBCODE08) AS SUBCODE08,
	TRIM(SUBCODE09) AS SUBCODE09, TRIM(SUBCODE10) AS SUBCODE10, 
	TRIM(ITEMTYPEAFICODE) AS ITEMTYPEAFICODE,
	TRIM(SUBCODE05) AS NO_WARNA,
	TRIM(SUBCODE02) || '-' || TRIM(SUBCODE03)  AS NO_HANGER,
	TRIM(ITEMDESCRIPTION) AS ITEMDESCRIPTION,
	DELIVERYDATE,
	LOT
FROM 
	ITXVIEWKK 
WHERE 
	PRODUCTIONORDERCODE = '00197329'
ORDER BY
	DELIVERYDATE ASC