SELECT
	s.ITEMELEMENTCODE,
	s.TRANSACTIONDATE,
	s.ITEMTYPECODE,
	s.DECOSUBCODE01,
	s.DECOSUBCODE02,
	s.DECOSUBCODE03,
	s.DECOSUBCODE04,
	s.DECOSUBCODE05,
	s.DECOSUBCODE06,
	s.DECOSUBCODE07,
	s.DECOSUBCODE08,
	COUNT(s.BASEPRIMARYQUANTITY) AS ROL,
	SUM(s.BASEPRIMARYQUANTITY) AS KGS,
	s.LOTCODE,
	s.PROJECTCODE,
	LISTAGG(DISTINCT TRIM(s.WHSLOCATIONWAREHOUSEZONECODE), ',') AS ZN,
	LISTAGG(DISTINCT TRIM(s.WAREHOUSELOCATIONCODE),	',') AS LK,
	s.QUALITYREASONCODE,
	COUNT(b.BASEPRIMARYQUANTITYUNIT) AS ROL_BALANCE,
	SUM(b.BASEPRIMARYQUANTITYUNIT) AS KGS_BALANCE,
	LISTAGG(DISTINCT TRIM(b.WHSLOCATIONWAREHOUSEZONECODE), ',') AS ZN_BALANCE,
	LISTAGG(DISTINCT TRIM(b.WAREHOUSELOCATIONCODE),	',') AS LK_BALANCE
--	STS.QUALITYREASONCODE AS KET
FROM
	STOCKTRANSACTION s
LEFT OUTER JOIN BALANCE b ON b.ELEMENTSCODE = s.ITEMELEMENTCODE
LEFT OUTER JOIN (SELECT ITEMELEMENTCODE,QUALITYREASONCODE, CREATIONDATETIME
					FROM STOCKTRANSACTION
					WHERE (ITEMTYPECODE = 'FKF'	OR ITEMTYPECODE = 'KFF')
					AND LOGICALWAREHOUSECODE = 'M031') STS	ON STS.ITEMELEMENTCODE = s.ITEMELEMENTCODE
WHERE
--	CONCAT(TRIM(s.TRANSACTIONDATE), CONCAT(' ', TRIM(s.TRANSACTIONTIME))) BETWEEN '2024-01-01 07:00:00' AND '2024-02-01 07:00:00'
	s.TRANSACTIONDATE BETWEEN '2024-01-01' AND '2024-01-02'
	AND s.TEMPLATECODE = '304'
	AND (s.ITEMTYPECODE = 'FKF' OR s.ITEMTYPECODE = 'KFF')
	AND s.LOGICALWAREHOUSECODE = 'M031'
	AND NOT s.WAREHOUSELOCATIONCODE = 'DOK'
	AND NOT s.WAREHOUSELOCATIONCODE LIKE 'BBS%'
	AND NOT s.WAREHOUSELOCATIONCODE LIKE 'ZER%'
	AND s.LOTCODE LIKE '00%'
GROUP BY
	s.ITEMELEMENTCODE,
	s.LOTCODE,
	s.TRANSACTIONDATE,
	s.ITEMTYPECODE,
	s.DECOSUBCODE01,
	s.DECOSUBCODE02,
	s.DECOSUBCODE03,
	s.DECOSUBCODE04,
	s.DECOSUBCODE05,
	s.DECOSUBCODE06,
	s.DECOSUBCODE07,
	s.DECOSUBCODE08,
	s.PROJECTCODE,
	s.WHSLOCATIONWAREHOUSEZONECODE,
	s.WAREHOUSELOCATIONCODE,
	s.QUALITYREASONCODE
--	STS.QUALITYREASONCODE