WITH
s302_last_ts AS (
    SELECT
        ITEMELEMENTCODE,
        MAX(TIMESTAMP(TRANSACTIONDATE, TRANSACTIONTIME)) AS max_ts
    FROM STOCKTRANSACTION
    WHERE TEMPLATECODE = '302'
    AND ITEMTYPECODE = 'KGF'
    AND LOGICALWAREHOUSECODE = 'M021'
    AND TIMESTAMP(TRANSACTIONDATE, TRANSACTIONTIME)
        BETWEEN CAST('2026-06-18 07:00:00' AS TIMESTAMP) AND CAST('2026-06-19 06:59:59' AS TIMESTAMP)
    GROUP BY ITEMELEMENTCODE
),
s302_pick AS (
    SELECT s.*
    FROM STOCKTRANSACTION s
    INNER JOIN s302_last_ts t
        ON t.ITEMELEMENTCODE = s.ITEMELEMENTCODE
        AND t.max_ts = TIMESTAMP(s.TRANSACTIONDATE, s.TRANSACTIONTIME)
    WHERE s.TEMPLATECODE = '302'
    AND s.ITEMTYPECODE = 'KGF'
    AND s.LOGICALWAREHOUSECODE = 'M021'
),
s301_last_ts AS (
    SELECT
        ITEMELEMENTCODE,
        MAX(TIMESTAMP(TRANSACTIONDATE, TRANSACTIONTIME)) AS max_ts
    FROM STOCKTRANSACTION
    WHERE TEMPLATECODE = '301'
    AND ITEMTYPECODE = 'KGF'
    AND LOGICALWAREHOUSECODE = 'M021'
    AND TIMESTAMP(TRANSACTIONDATE, TRANSACTIONTIME)
        BETWEEN CAST('2026-06-18 07:00:00' AS TIMESTAMP) AND CAST('2026-06-19 06:59:59' AS TIMESTAMP)
    GROUP BY ITEMELEMENTCODE
),
s301_pick AS (
    SELECT
        s.ITEMELEMENTCODE,
        s.TRANSACTIONNUMBER,
        s.TRANSACTIONTIME,
        s.WAREHOUSELOCATIONCODE
    FROM STOCKTRANSACTION s
    INNER JOIN s301_last_ts t
        ON t.ITEMELEMENTCODE = s.ITEMELEMENTCODE
        AND t.max_ts = TIMESTAMP(s.TRANSACTIONDATE, s.TRANSACTIONTIME)
    WHERE s.TEMPLATECODE = '301'
    AND s.ITEMTYPECODE = 'KGF'
    AND s.LOGICALWAREHOUSECODE = 'M021'
)
SELECT
    s302.DECOSUBCODE02         AS decosubcode02,
    s302.DECOSUBCODE03         AS decosubcode03,
    s302.DECOSUBCODE04         AS decosubcode04,
    s302.LOGICALWAREHOUSECODE  AS logicalwarehousecode,
    s302.PHYSICALWAREHOUSECODE AS physicalwarehousecode,
    s302.PROJECTCODE           AS projectcode,
    (s302.TRANSACTIONDATE || ' ' || s302.TRANSACTIONTIME) AS tanggal_waktu,
    s302.CREATIONUSER          AS creationuser,
    s301.WAREHOUSELOCATIONCODE AS sebelum,
    s302.WAREHOUSELOCATIONCODE AS sesudah,
    s302.LOTCODE                AS lotcode,
    s302.ITEMELEMENTCODE       AS itemelementcode,
    s302.BASEPRIMARYQUANTITY   AS baseprimaryquantity
FROM s302_pick s302
LEFT JOIN s301_pick s301
    ON s301.ITEMELEMENTCODE = s302.ITEMELEMENTCODE
WHERE 
--	s302.ITEMELEMENTCODE = '0041424703401'
	s302.ITEMELEMENTCODE = '0044639900101'