-- DB2ADMIN.ITXVIEWRESEP2 source

CREATE VIEW ITXVIEWRESEP2 AS
SELECT
    r.RECIPESUBCODE01,
    r.RECIPESUFFIXCODE,
    r.GROUPNUMBER,
    r."SEQUENCE",
    TRIM(r.ITEMTYPEAFICODE) AS ITEMTYPEAFICODE,
    CASE
        WHEN TRIM(r.ITEMTYPEAFICODE) = 'RFF' THEN TRIM(r.SUBCODE01)
        WHEN TRIM(r.ITEMTYPEAFICODE) = 'RFD' THEN TRIM(r.SUBCODE01)
        ELSE ''
    END AS CODE,
    CASE
        WHEN TRIM(r.ITEMTYPEAFICODE) = 'DYC' THEN TRIM(r.SUBCODE01) || '-' || TRIM(r.SUBCODE02) || '-' || TRIM(r.SUBCODE03)
        WHEN TRIM(r.ITEMTYPEAFICODE) = 'PST' THEN TRIM(r.SUBCODE01) || '-' || TRIM(r.SUBCODE02) || '-' || TRIM(r.SUBCODE03)
        ELSE ''
    END AS SUBCODE,
    TRIM(r.COMMENTLINE) AS COMMENTLINE,
    TRIM(p.LONGDESCRIPTION) AS LONGDESCRIPTION,
    r.CONSUMPTION,
    r.COMPONENTUOMCODE,
    r.CONSUMPTIONTYPE,
    TRIM(r.SUBCODE01) AS SUBCODE01,
    TRIM(r.SUBCODE02) AS SUBCODE02,
    TRIM(r.SUBCODE03) AS SUBCODE03
FROM
    RECIPECOMPONENT r
LEFT JOIN PRODUCT p ON
    p.ITEMTYPECODE = r.ITEMTYPEAFICODE
    AND p.SUBCODE01 = r.SUBCODE01
    AND p.SUBCODE02 = r.SUBCODE02
    AND p.SUBCODE03 = r.SUBCODE03
    --ORDER BY r.GROUPNUMBER
    --WHERE r.RECIPESUBCODE01 = 'SC0001++';