SELECT 
DISTINCT 
* 
FROM (SELECT
        VIEWPRODUCTIONRESERVATION.GROUPLINE,
        ITXVIEWRESEP.RECIPENUMBERID, 
        ITXVIEWRESEP.GROUPNUMBER, 
        CASE
            WHEN CAST( LENGTH(ITXVIEWRESEP.SUBCODE01) AS VARCHAR(5)) = '1' THEN ITXVIEWRESEP.SUBCODE01_RESERVATION
            ELSE ITXVIEWRESEP.SUBCODE01
        END AS SUBCODE01,
        CASE
            WHEN CAST( LENGTH(ITXVIEWRESEP.SUBCODE01) AS VARCHAR(5)) = '1' THEN ITXVIEWRESEP.SUFFIXCODE_RESERVATION
            ELSE ITXVIEWRESEP.SUFFIXCODE
        END AS SUFFIXCODE
    FROM
        VIEWPRODUCTIONRESERVATION
    LEFT JOIN ITXVIEWRESEP ON VIEWPRODUCTIONRESERVATION.SUFFIXCODE = ITXVIEWRESEP.SUFFIXCODE_RESERVATION
        AND VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE = ITXVIEWRESEP.PRODUCTIONORDERCODE
        AND VIEWPRODUCTIONRESERVATION.SUBCODE01 = ITXVIEWRESEP.SUBCODE01_RESERVATION
        AND VIEWPRODUCTIONRESERVATION.COMPANYCODE = ITXVIEWRESEP.COMPANYCODE
    LEFT JOIN ITXVIEWRESEP2 ITXVIEWRESEP2 ON ITXVIEWRESEP2.RECIPESUBCODE01 = ITXVIEWRESEP.CODE AND ITXVIEWRESEP2.RECIPESUFFIXCODE = ITXVIEWRESEP.SUFFIXCODE
    WHERE 
        VIEWPRODUCTIONRESERVATION.PRODUCTIONORDERCODE = '00181658'
    	AND VIEWPRODUCTIONRESERVATION.GROUPLINE IN ('305') 
    	AND NOT ITXVIEWRESEP.SUFFIXCODE IS NULL
    GROUP BY
        VIEWPRODUCTIONRESERVATION.GROUPLINE,
        ITXVIEWRESEP.RECIPENUMBERID,
        ITXVIEWRESEP.SUBCODE01,
        ITXVIEWRESEP.SUFFIXCODE,
        ITXVIEWRESEP.GROUPNUMBER,
        ITXVIEWRESEP.SUBCODE01_RESERVATION,
        ITXVIEWRESEP.SUFFIXCODE_RESERVATION 
    ORDER BY
        VIEWPRODUCTIONRESERVATION.GROUPLINE,
        ITXVIEWRESEP.RECIPENUMBERID,
        ITXVIEWRESEP.GROUPNUMBER)
        
        
SELECT
    CAST(a.VALUEDECIMAL AS DECIMAL(4)) AS MAINPROGRAM
FROM
    RECIPE r 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = r.ABSUNIQUEID AND a.FIELDNAME IN ('CoolingProgram1','CoolingProgram')
WHERE
    r.SUBCODE01 = '18157/230714L' AND r.SUFFIXCODE = '24003383D-S2'
    AND NOT a.VALUEDECIMAL IS NULL
UNION ALL 
SELECT
    CAST(a2.VALUEDECIMAL AS DECIMAL(4)) AS MAINPROGRAM
FROM
    RECIPE r 
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = r.ABSUNIQUEID AND a2.FIELDNAME IN ('MainProgram1','MainProgram')
WHERE
    r.SUBCODE01 = '18157/230714L' AND r.SUFFIXCODE = '24003383D-S2'
    AND NOT a2.VALUEDECIMAL IS NULL