SELECT 
    LISTAGG(TRIM(PRODRESERVATIONLINKGROUPCODE) || ' = ' || DECIMAL(LR, 5,2), ', ') AS LR,
    LISTAGG(TRIM(PRODRESERVATIONLINKGROUPCODE) || ' = ' || TRIM(SUBCODE01) || '-' || TRIM(SUFFIXCODE), ', ') AS SUFFIX,
    LISTAGG(TRIM(PRODRESERVATIONLINKGROUPCODE) || ' = ' || TRIM(LONGDESCRIPTION), ', ') AS LONGDESCRIPTION,
    LISTAGG(TRIM(PRODRESERVATIONLINKGROUPCODE) || ' = ' || TRIM(SHORTDESCRIPTION), ', ') AS SHORTDESCRIPTION,
    LISTAGG(TRIM(PRODRESERVATIONLINKGROUPCODE) || ' = ' || TRIM(SEARCHDESCRIPTION), ', ') AS SEARCHDESCRIPTION
  FROM (
    SELECT 
      DISTINCT 
      p.PRODRESERVATIONLINKGROUPCODE,
      p.PICKUPQUANTITY AS LR,
      p.SUBCODE01,
      p.SUFFIXCODE,
      r.LONGDESCRIPTION,
      r.SHORTDESCRIPTION,
      r.SEARCHDESCRIPTION,
      CASE
      	WHEN i.LONGDESCRIPTION = '' OR i.LONGDESCRIPTION IS NULL THEN i.COMMENTLINE
      	ELSE i.LONGDESCRIPTION || '(' || i.CONSUMPTION || ')'
      END AS CONS_AGENT
    FROM 
      PRODUCTIONRESERVATION p 
    LEFT JOIN RECIPE r ON r.SUBCODE01 = p.SUBCODE01 AND r.SUFFIXCODE = p.SUFFIXCODE 
    LEFT JOIN VIEWPRODUCTIONDEMANDSTEP v ON v.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND v.GROUPSTEPNUMBER = p.GROUPSTEPNUMBER
    LEFT JOIN ITXVIEWRESEP i ON i.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND i.SUBCODE01_RESERVATION = p.SUBCODE01 AND i.SUFFIXCODE_RESERVATION = p.SUFFIXCODE
    WHERE	
      p.PRODUCTIONORDERCODE = '00135578'  
      AND 
      CASE 
        WHEN v.STEPTYPE = 3 THEN p.GROUPSTEPNUMBER IN ('230')
        ELSE p.STEPNUMBER IN ('230')
      END 
      AND p.ITEMNATURE = 9
      AND SUBSTR(p.SUBCODE01, 1,2) = 'SC' 
    GROUP BY
      p.PRODRESERVATIONLINKGROUPCODE,
      p.PICKUPQUANTITY,
      p.SUBCODE01,
      p.SUFFIXCODE,
      r.LONGDESCRIPTION,
      r.SHORTDESCRIPTION,
      r.SEARCHDESCRIPTION)
      
 SELECT
	*
FROM
	ITXVIEWRESEP i
WHERE
	PRODUCTIONORDERCODE = '00135578'
	AND SUBCODE01_RESERVATION = 'SC3301'
	AND SUFFIXCODE_RESERVATION = '001/SPD'