SELECT 
	a.VALUESTRING AS RCODE,
	r.ABSUNIQUEID,
	r.SUBCODE01,r.SUFFIXCODE
FROM
	PRODUCTIONRESERVATION p
LEFT JOIN RECIPE r ON r.SUBCODE01 = p.SUBCODE01 AND r.SUFFIXCODE = p.SUFFIXCODE 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = r.ABSUNIQUEID AND a.FIELDNAME = 'RCode'
WHERE 
	p.PRODUCTIONORDERCODE = '00156771' AND GROUPLINE = '605'