SELECT PRODUCTIONDEMAND.COMPANYCODE,PRODUCTIONDEMAND.COUNTERCODE,
       PRODUCTIONDEMAND.CODE,PRODUCTIONDEMAND.PROJECTCODE,
       PRODUCTIONDEMAND.ITEMTYPEAFICODE,PRODUCTIONDEMAND.SUBCODE01,
       PRODUCTIONDEMAND.SUBCODE02,PRODUCTIONDEMAND.SUBCODE03,PRODUCTIONDEMAND.SUBCODE04,
       PRODUCTIONDEMAND.SUBCODE05,PRODUCTIONDEMAND.SUBCODE06,
       PRODUCTIONDEMAND.SUBCODE07,PRODUCTIONDEMAND.SUBCODE08,
       PRODUCTIONDEMAND.SUBCODE09,PRODUCTIONDEMAND.SUBCODE10,
       PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE,PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE,
       BUSINESSPARTNER.LEGALNAME1,ELEMENTSINSPECTION.ELEMENTCODE,
       ELEMENTSINSPECTION.DEMANDCODE,ELEMENTSINSPECTION.LENGTHGROSS,
       ELEMENTSINSPECTION.INSPECTIONSTARTDATETIME,ELEMENTSINSPECTION.ABSUNIQUEID,
       FULLITEMKEYDECODER.SUMMARIZEDDESCRIPTION,
       ITXVIEWORDERITEMLINKACTIVE.SHORTDESCRIPTION,
       ELEMENTSINSPECTION.CREATIONDATETIME  
FROM  (  (  (  (  ( DB2ADMIN.PRODUCTIONDEMAND PRODUCTIONDEMAND LEFT OUTER 
       JOIN DB2ADMIN.ORDERPARTNER ORDERPARTNER ON 
       PRODUCTIONDEMAND.CUSTOMERCODE=ORDERPARTNER.CUSTOMERSUPPLIERCODE )  LEFT OUTER JOIN 
       DB2ADMIN.BUSINESSPARTNER BUSINESSPARTNER ON 
       ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID=BUSINESSPARTNER.NUMBERID )  LEFT OUTER 
       JOIN DB2ADMIN.ELEMENTSINSPECTION ELEMENTSINSPECTION ON 
       PRODUCTIONDEMAND.CODE=ELEMENTSINSPECTION.DEMANDCODE AND 
       PRODUCTIONDEMAND.COUNTERCODE=ELEMENTSINSPECTION.DEMANDCOUNTERCODE )  LEFT OUTER 
       JOIN DB2ADMIN.INITIALS INITIALS ON 
       ELEMENTSINSPECTION.OPERATORCODE=INITIALS.CODE )  LEFT OUTER JOIN 
       DB2ADMIN.FULLITEMKEYDECODER FULLITEMKEYDECODER ON 
       PRODUCTIONDEMAND.FULLITEMIDENTIFIER=FULLITEMKEYDECODER.IDENTIFIER )  LEFT OUTER JOIN 
       DB2ADMIN.ITXVIEWORDERITEMLINKACTIVE ITXVIEWORDERITEMLINKACTIVE ON 
       PRODUCTIONDEMAND.CUSTOMERCODE=ITXVIEWORDERITEMLINKACTIVE.ORDPRNCUSTOMERSUPPLIERCODE AND 
       PRODUCTIONDEMAND.ITEMTYPEAFICODE=ITXVIEWORDERITEMLINKACTIVE.ITEMTYPEAFICODE AND 
       PRODUCTIONDEMAND.SUBCODE01=ITXVIEWORDERITEMLINKACTIVE.SUBCODE01 AND 
       PRODUCTIONDEMAND.SUBCODE02=ITXVIEWORDERITEMLINKACTIVE.SUBCODE02 AND 
       PRODUCTIONDEMAND.SUBCODE03=ITXVIEWORDERITEMLINKACTIVE.SUBCODE03 AND 
       PRODUCTIONDEMAND.SUBCODE04=ITXVIEWORDERITEMLINKACTIVE.SUBCODE04 AND 
       PRODUCTIONDEMAND.SUBCODE05=ITXVIEWORDERITEMLINKACTIVE.SUBCODE05 AND 
       PRODUCTIONDEMAND.SUBCODE06=ITXVIEWORDERITEMLINKACTIVE.SUBCODE06 AND 
       PRODUCTIONDEMAND.SUBCODE07=ITXVIEWORDERITEMLINKACTIVE.SUBCODE07 AND 
       PRODUCTIONDEMAND.SUBCODE08=ITXVIEWORDERITEMLINKACTIVE.SUBCODE08 
       AND PRODUCTIONDEMAND.SUBCODE09=ITXVIEWORDERITEMLINKACTIVE.SUBCODE09 
       AND 
       PRODUCTIONDEMAND.SUBCODE10=ITXVIEWORDERITEMLINKACTIVE.SUBCODE10 
WHERE 
	ELEMENTSINSPECTION.ELEMENTCODE = '00140772022'
ORDER BY ELEMENTSINSPECTION.ELEMENTCODE, ELEMENTSINSPECTION.CREATIONDATETIME DESC LIMIT 1