SELECT 
    p.PRODUCTIONORDERCODE AS PRODUCTIONORDERCODE, 
    p.GROUPSTEPNUMBER AS GROUPSTEPNUMBER,
    iptop.SELESAI,
    DAYS(CURRENT DATE) - DAYS(iptop.SELESAI) AS DELAY,
    p.PROGRESSSTATUS AS PROGRESSSTATUS
FROM 
    VIEWPRODUCTIONDEMANDSTEP p
LEFT JOIN ITXVIEW_POSISIKK_TGL_IN_PRODORDER iptip ON iptip.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND iptip.DEMANDSTEPSTEPNUMBER = p.GROUPSTEPNUMBER
LEFT JOIN ITXVIEW_POSISIKK_TGL_OUT_PRODORDER iptop ON iptop.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND iptop.DEMANDSTEPSTEPNUMBER = p.GROUPSTEPNUMBER
WHERE
    p.PRODUCTIONORDERCODE = '00085709' AND
    (p.PROGRESSSTATUS = '3' OR p.PROGRESSSTATUS = '2') ORDER BY p.GROUPSTEPNUMBER DESC LIMIT 1

SELECT COUNT(*) AS TOTALSTEP FROM VIEWPRODUCTIONDEMANDSTEP WHERE PRODUCTIONORDERCODE = '00085709'

SELECT COUNT(*) AS TOTALCLOSE FROM VIEWPRODUCTIONDEMANDSTEP WHERE PRODUCTIONORDERCODE = '00085709' AND PROGRESSSTATUS = 3
    
SELECT 
    GROUPSTEPNUMBER,
    TRIM(OPERATIONCODE) AS OPERATIONCODE,
    o.LONGDESCRIPTION AS LONGDESCRIPTION,
    PROGRESSSTATUS,
    CASE
        WHEN PROGRESSSTATUS = 0 THEN 'Entered'
        WHEN PROGRESSSTATUS = 1 THEN 'Planned'
        WHEN PROGRESSSTATUS = 2 THEN 'Progress'
        WHEN PROGRESSSTATUS = 3 THEN 'Closed'
    END AS STATUS_OPERATION,
    iptop.SELESAI,
    DAYS(CURRENT DATE) - DAYS(iptop.MULAI) AS DELAY
FROM 
    VIEWPRODUCTIONDEMANDSTEP v
LEFT JOIN OPERATION o ON o.CODE = v.OPERATIONCODE
LEFT JOIN ITXVIEW_POSISIKK_TGL_IN_PRODORDER iptip ON iptip.PRODUCTIONORDERCODE = v.PRODUCTIONORDERCODE AND iptip.DEMANDSTEPSTEPNUMBER = v.GROUPSTEPNUMBER
LEFT JOIN ITXVIEW_POSISIKK_TGL_OUT_PRODORDER iptop ON iptop.PRODUCTIONORDERCODE = v.PRODUCTIONORDERCODE AND iptop.DEMANDSTEPSTEPNUMBER = v.GROUPSTEPNUMBER
WHERE 
    v.PRODUCTIONORDERCODE = '00085709' AND 
    v.GROUPSTEPNUMBER > 42
ORDER BY 
    GROUPSTEPNUMBER ASC LIMIT 1