SELECT BALANCE.ITEMTYPECODE,BALANCE.DECOSUBCODE01,BALANCE.DECOSUBCODE02,
       BALANCE.DECOSUBCODE03,BALANCE.DECOSUBCODE04,BALANCE.DECOSUBCODE05,
       BALANCE.DECOSUBCODE06,BALANCE.DECOSUBCODE07,
       BALANCE.DECOSUBCODE08,BALANCE.WHSLOCATIONWAREHOUSEZONECODE,
       BALANCE.WAREHOUSELOCATIONCODE,BALANCE.QUALITYLEVELCODE,BALANCE.LOTCODE,
       BALANCE.ELEMENTSCODE,BALANCE.PROJECTCODE,BALANCE.BASEPRIMARYQUANTITYUNIT,
       BALANCE.BASESECONDARYUNITCODE,BALANCE.BASESECONDARYQUANTITYUNIT,
       BALANCE.CREATIONDATETIME,SALESORDER.CODE,
       SALESORDER.CONFIRMEDDUEDATE,PRODUCTIONDEMAND.SUBCODE01,PRODUCTIONDEMAND.SUBCODE02,
       PRODUCTIONDEMAND.SUBCODE03,PRODUCTIONDEMAND.SUBCODE04,
       PRODUCTIONDEMAND.SUBCODE05,PRODUCTIONDEMAND.SUBCODE06,
       PRODUCTIONDEMAND.SUBCODE07,PRODUCTIONDEMAND.SUBCODE08,PRODUCTIONDEMAND.SUBCODE09,
       PRODUCTIONDEMAND.SUBCODE10,
       PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE,SALESORDERDELIVERY.CONFIRMEDDELIVERYDATE 
FROM  (  (  ( DB2ADMIN.BALANCE BALANCE FULL OUTER JOIN DB2ADMIN.SALESORDER 
       SALESORDER ON BALANCE.PROJECTCODE=SALESORDER.CODE AND 
       BALANCE.COMPANYCODE=SALESORDER.COMPANYCODE )  LEFT OUTER JOIN 
       DB2ADMIN.ELEMENTS ELEMENTS ON BALANCE.ELEMENTSCODE=ELEMENTS.CODE AND 
       BALANCE.COMPANYCODE=ELEMENTS.COMPANYCODE )  LEFT OUTER JOIN 
       DB2ADMIN.PRODUCTIONDEMAND PRODUCTIONDEMAND ON 
       ELEMENTS.ENTRYDOCUMENTNUMBER=PRODUCTIONDEMAND.CODE AND 
       ELEMENTS.COMPANYCODE=PRODUCTIONDEMAND.COMPANYCODE )  LEFT OUTER JOIN 
       DB2ADMIN.SALESORDERDELIVERY SALESORDERDELIVERY ON 
       PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE=SALESORDERDELIVERY.SALESORDERLINESALESORDERCODE AND 
       PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE=SALESORDERDELIVERY.SALESORDERLINEORDERLINE 
WHERE
	BALANCE.ELEMENTSCODE = '1711010235969'
ORDER BY BALANCE.ELEMENTSCODE
LIMIT 100