SELECT
	x.PRODUCTIONORDERCODE,
	x.OPERATIONCODE, 
	x.OPERATORCODE,
	x.PROGRESSSTARTPROCESSDATE, 
	x.PROGRESSSTARTPROCESSTIME ,
	x.MACHINECODE ,
	x.CREATIONDATETIME,
	r.LONGDESCRIPTION,  
	i.SUBCODE01,
	i.SUBCODE02,
		i.SUBCODE03,
	i.SUBCODE04,
	i.SUBCODE05,
	i.SUBCODE06,
	i.SUBCODE07,
	i.SUBCODE08,
	i.SUBCODE09,
	i.SUBCODE10,
	i.ITEMNO,
	LISTAGG(
		TRIM(i.PRO_ORDER),
		','
	) PRO_ORDER,
	LISTAGG(
		TRIM(i.PRODUCTIONDEMANDCODE),
		','
	) PRODUCTIONDEMANDCODE,
	i.LANGGANAN,
	i.WARNA,
	i.NO_WARNA
FROM
	PRODUCTIONPROGRESS x
LEFT OUTER JOIN (
		SELECT
			p.SUBCODE01,
			p.SUBCODE02,
			p.SUBCODE03,
			p.SUBCODE04,
			p.SUBCODE05,
			p.SUBCODE06,
			p.SUBCODE07,
			p.SUBCODE08,
			p.SUBCODE09,
			p.SUBCODE10,
			CONCAT(TRIM(p.SUBCODE02), TRIM(p.SUBCODE03)) AS ITEMNO,
			p.ORIGDLVSALORDLINESALORDERCODE AS PRO_ORDER,
			ps.PRODUCTIONORDERCODE,
			ps.PRODUCTIONDEMANDCODE,
			E.LEGALNAME1 AS LANGGANAN,
			TRIM(f.LONGDESCRIPTION) AS WARNA,
			TRIM(f.CODE) AS NO_WARNA
		FROM
			PRODUCTIONDEMAND p
		LEFT OUTER JOIN 
				(
				SELECT
					PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE,
					PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE
				FROM
					PRODUCTIONDEMANDSTEP PRODUCTIONDEMANDSTEP
				GROUP BY
					PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE,
					PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE
			) ps
			ON
			p.CODE = ps.PRODUCTIONDEMANDCODE
		LEFT OUTER JOIN
				(
				SELECT
					BUSINESSPARTNER.LEGALNAME1,
					ORDERPARTNER.CUSTOMERSUPPLIERCODE
				FROM
					BUSINESSPARTNER BUSINESSPARTNER
				LEFT JOIN ORDERPARTNER ORDERPARTNER ON
					BUSINESSPARTNER.NUMBERID = ORDERPARTNER.ORDERBUSINESSPARTNERNUMBERID
			) E
			ON
			p.CUSTOMERCODE = E.CUSTOMERSUPPLIERCODE
		LEFT OUTER JOIN USERGENERICGROUP f
				ON
			p.SUBCODE05 = f.CODE
			AND f.USERGENERICGROUPTYPECODE = 'CL1'
		LEFT OUTER JOIN PRODUCTIONDEMAND h
			ON
			p.ORIGDLVSALORDLINESALORDERCODE = h.ORIGDLVSALORDLINESALORDERCODE
			AND 
			p.SUBCODE01 = h.SUBCODE01
			AND 
			p.SUBCODE02 = h.SUBCODE02
			AND
			p.SUBCODE03 = h.SUBCODE03
			AND
			p.SUBCODE04 = h.SUBCODE04
			AND 
			h.ITEMTYPEAFICODE = 'KFF'
		GROUP BY
			p.SUBCODE01,
			p.SUBCODE02,
			p.SUBCODE03,
			p.SUBCODE04,
			p.SUBCODE05,
			p.SUBCODE06,
			p.SUBCODE07,
			p.SUBCODE08,
			p.SUBCODE09,
			p.SUBCODE10,
			p.ORIGDLVSALORDLINESALORDERCODE,
			ps.PRODUCTIONORDERCODE,
			ps.PRODUCTIONDEMANDCODE,
			E.LEGALNAME1,
			f.LONGDESCRIPTION,
			f.CODE
	) i ON
	i.PRODUCTIONORDERCODE = x.PRODUCTIONORDERCODE
LEFT OUTER JOIN RESOURCES r ON
	r.CODE = x.OPERATORCODE
WHERE
	(
		x.OPERATIONCODE = 'BAT2'
			OR x.OPERATIONCODE = 'BKN1'
	)
	AND x.PROGRESSTEMPLATECODE = 'S01'
	AND TIMESTAMP(
		TRIM(x.PROGRESSSTARTPROCESSDATE),
		TRIM(x.PROGRESSSTARTPROCESSTIME)
	) BETWEEN '$date_s 23:00:00' AND '$date_e 23:00:00'
GROUP BY 
	x.PRODUCTIONORDERCODE,
	x.OPERATIONCODE, 
	x.OPERATORCODE,
	x.PROGRESSSTARTPROCESSDATE, 
	x.PROGRESSSTARTPROCESSTIME ,
	x.MACHINECODE ,
	x.CREATIONDATETIME,
	r.LONGDESCRIPTION,
	i.SUBCODE01,
	i.SUBCODE02,
	i.SUBCODE03,
	i.SUBCODE04,
	i.SUBCODE05,
	i.SUBCODE06,
	i.SUBCODE07,
	i.SUBCODE08,
	i.SUBCODE09,
	i.SUBCODE10,
	i.ITEMNO,
	i.LANGGANAN,
	i.WARNA,
	i.NO_WARNA