SELECT 
    PRODUCTIONORDERCODE,
    REPLACE(LISTAGG( '`'|| PRODUCTIONDEMANDCODE || '`', ', '), '`', '''')  AS PRODUCTIONDEMANDCODE2,
    LISTAGG(PRODUCTIONDEMANDCODE, ', ')  AS PRODUCTIONDEMANDCODE,
    STEPNUMBER,
    OPERATIONCODE,
    STATUS_OPERATION,
    HANGER,
    SUBCODE06,
    OPERATIONGROUPCODE,
    VALUEBOOLEAN
FROM
    (SELECT	
        TRIM(p.PRODUCTIONORDERCODE) AS PRODUCTIONORDERCODE,
        TRIM(p.PRODUCTIONDEMANDCODE) AS PRODUCTIONDEMANDCODE,
        p.STEPNUMBER,
        TRIM(p.OPERATIONCODE) AS OPERATIONCODE,
        CASE
            WHEN p.PROGRESSSTATUS = 0 THEN 'Entered'
            WHEN p.PROGRESSSTATUS = 1 THEN 'Planned'
            WHEN p.PROGRESSSTATUS = 2 THEN 'Progress'
            WHEN p.PROGRESSSTATUS = 3 THEN 'Closed'
        END AS STATUS_OPERATION,
        TRIM(o.OPERATIONGROUPCODE) AS OPERATIONGROUPCODE,
        TRIM(p2.SUBCODE02) || '-' || TRIM(p2.SUBCODE03) AS HANGER,
        TRIM(p2.SUBCODE06) AS SUBCODE06,
        ROW_NUMBER() OVER (PARTITION BY p.PRODUCTIONORDERCODE, p.PRODUCTIONDEMANDCODE ORDER BY p.STEPNUMBER) AS RN,
        o.ABSUNIQUEID AS ABSUNIQUEID_OPERATION
    FROM
        PRODUCTIONDEMANDSTEP p
    LEFT JOIN OPERATION o ON o.CODE = p.OPERATIONCODE 
    LEFT JOIN PRODUCTIONDEMAND p2 ON p2.CODE = p.PRODUCTIONDEMANDCODE
    WHERE 
        TRIM(p.PROGRESSSTATUS) IN ('2', '0')
        AND TRIM(o.OPERATIONGROUPCODE) = 'DYE'
        AND p.PRODUCTIONDEMANDCODE = '00229875'
        AND p.CREATIONDATETIME >= '2023-11-01'
        AND NOT p.PRODUCTIONORDERCODE IS NULL
        AND (TRIM(p2.DESTINATIONORDER) = '1' OR NOT p2.PROJECTCODE IS NULL)
        )
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = o.ABSUNIQUEID AND a.FIELDNAME = 'Gerobak'
WHERE
    RN = 1
    AND NOT OPERATIONCODE = 'BAT1'
    AND a.VALUEBOOLEAN IS NULL
GROUP BY 
    PRODUCTIONORDERCODE,
    STEPNUMBER,
    OPERATIONCODE,
    STATUS_OPERATION,
    HANGER,
    SUBCODE06,
    OPERATIONGROUPCODE,
    VALUEBOOLEAN