SELECT
	ITXVIEW_SURATJALAN_EXIM2A.PROVISIONALCODE,
	ITXVIEW_SURATJALAN_EXIM2A.TGL_BERANGKAT,
	ITXVIEW_SURATJALAN_EXIM2A.ISSUE_DATE,
	ITXVIEW_SURATJALAN_EXIM2A.ITEMTYPEAFICODE,
	ITXVIEW_SURATJALAN_EXIM2A.TERMS_SHIPPING,
	ITXVIEW_SURATJALAN_EXIM2A.TERMS_SHIPPING_DESCRIPTION,
	ITXVIEW_SURATJALAN_EXIM2A.PROJECTCODE,
	ITXVIEW_SURATJALAN_EXIM2A.SUBCODE05,
	ITXVIEW_SURATJALAN_EXIM2A.DLVSALORDERLINESALESORDERCODE,
	ITXVIEW_SURATJALAN_EXIM2A.BRAND_NM,
	ITXVIEW_SURATJALAN_EXIM2A.ADDRESSEE,
	ITXVIEW_SURATJALAN_EXIM2A.COUNTRY_NM,
	ITXVIEW_SURATJALAN_EXIM2A.USERPRIMARYUOMCODE,
	ITXVIEW_SURATJALAN_EXIM2A.QTY_KG,
	ITXVIEW_SURATJALAN_EXIM2A.QTY_YARDMETER,
	ITXVIEW_SURATJALAN_EXIM2A.USERSECONDARYUOMCODE,
	ITXVIEW_SURATJALAN_EXIM2A.QTY_PCS,
	ITXVIEW_SURATJALAN_EXIM2A.COUNTROLL,
	ITXVIEW_SURATJALAN_EXIM2A.COUNTBALL,
	ITXVIEW_SURATJALAN_EXIM2A.FOC_KG,
	ITXVIEW_SURATJALAN_EXIM2A.FOC_YARDMETER,
	ITXVIEW_SURATJALAN_EXIM2A.JML_ROLL_FOC,
	SALESDOCUMENT.PROVISIONALCOUNTERCODE,
	SALESDOCUMENT.PROVISIONALCODE,
	SALESDOCUMENT.TERMSOFSHIPPINGCODE,
	SALESDOCUMENT.TERMSOFSHIPPINGDESCRIPTION,
	SALESDOCUMENT.TRUCKDRIVERCODE,
	SALESDOCUMENT.PAYMENTMETHODCODE
FROM
	DB2ADMIN.ITXVIEW_SURATJALAN_EXIM2A ITXVIEW_SURATJALAN_EXIM2A
LEFT 
       OUTER JOIN DB2ADMIN.SALESDOCUMENT SALESDOCUMENT ON
	ITXVIEW_SURATJALAN_EXIM2A.PROVISIONALCODE = SALESDOCUMENT.PROVISIONALCODE
WHERE
	ITXVIEW_SURATJALAN_EXIM2A.PROVISIONALCODE = 'ESP2400600'
ORDER BY
	ITXVIEW_SURATJALAN_EXIM2A.PROVISIONALCODE