SELECT
	ELEMENTSINSPECTION.WINDINGMACHINE,
	BALANCE.ITEMTYPECODE,
	BALANCE.DECOSUBCODE01,
	BALANCE.DECOSUBCODE02,
	BALANCE.DECOSUBCODE03,
	BALANCE.DECOSUBCODE04,
	BALANCE.DECOSUBCODE05,
	BALANCE.DECOSUBCODE06,
	BALANCE.DECOSUBCODE07,
	BALANCE.DECOSUBCODE08,
	BALANCE.DECOSUBCODE09,
	BALANCE.DECOSUBCODE10,
	BALANCE.QUALITYLEVELCODE,
	BALANCE.LOTCODE,
	BALANCE.ELEMENTSCODE,
	BALANCE.PROJECTCODE,
	BALANCE.BASEPRIMARYUNITCODE,
	BALANCE.BASEPRIMARYQUANTITYUNIT,
	BALANCE.BASESECONDARYUNITCODE,
	BALANCE.BASESECONDARYQUANTITYUNIT,
	BALANCE.CREATIONDATETIME,
	SALESORDER.CODE,
	SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE,
	SALESORDER.EXTERNALREFERENCE,
	SALESORDER.INTERNALREFERENCE
FROM
	(
		DB2ADMIN.BALANCE BALANCE
	LEFT OUTER JOIN DB2ADMIN.SALESORDER 
       SALESORDER ON
		BALANCE.PROJECTCODE = SALESORDER.CODE
	)
LEFT OUTER JOIN DB2ADMIN.ELEMENTSINSPECTION ELEMENTSINSPECTION ON BALANCE.ELEMENTSCODE = ELEMENTSINSPECTION.IMPORTCODE
WHERE
	BALANCE.ELEMENTSCODE = '0021395200101'