SELECT
  i.PROJECTCODE,
  i.COMPANYCODE,
  i.COUNTERCODE,
  i.CODE,
  i.ITEMTYPEAFICODE,
  i.SUBCODE01,
  i.SUBCODE02,
  i.SUBCODE03,
  i.SUBCODE04,
  i.BASEPRIMARYUOMCODE,
  i.BASEPRIMARYQUANTITY,
  i.FINALPLANNEDDATE,
  i.FINALEFFECTIVEDATE,
  i.ORIGDLVSALORDLINESALORDERCODE,
  i.SUMMARIZEDDESCRIPTION,
  i.LEGALNAME1,
  i.PRODUCTIONDEMANDCODE,
  i.PRODUCTIONORDERCODE,
  i.SCHEDULEDRESOURCECODE,
  i.INITIALSCHEDULEDACTUALDATE,
  i.FINALSCHEDULEDACTUALDATE,
  i.PROGRESSSTATUS,
  AD5.VALUEDECIMAL AS QTYOPIN,
  AD6.VALUEDECIMAL AS QTYOPOUT,
  ADSTORAGE.VALUESTRING AS MC,
  CURRENT_TIMESTAMP AS TGLS,
  VARCHAR_FORMAT(i.FINALEFFECTIVEDATE, 'YYYY-MM-DD') AS TGLTUTUP,
  e.JML,
  e.JQTY,
  M502.M502_KG,
  TR11.TR11_KG,
  M021.M021_KG,
  CASE
  	WHEN i.PROGRESSSTATUS = '2' AND IDS.IDS = '0 ,0' THEN 'ProdOrdCreate'
  	WHEN i.PROGRESSSTATUS = '2' AND IDS.IDS = '2 ,0' THEN 'Sedang Jalan'
  	WHEN i.PROGRESSSTATUS = '2' AND IDS.IDS = '0 ,2' THEN 'Sedang Jalan'
  	WHEN i.PROGRESSSTATUS = '2' AND IDS.IDS = '2 ,2' THEN 'Sedang Jalan'
  	WHEN i.PROGRESSSTATUS = '6' THEN 'Selsai'
  	ELSE 'Tidak Ada PO'
  END AS status
FROM
  ITXVIEWKNTORDER i
LEFT OUTER JOIN DB2ADMIN.PRODUCTIONDEMAND ON PRODUCTIONDEMAND.CODE = i.PRODUCTIONDEMANDCODE
LEFT OUTER JOIN DB2ADMIN.ADSTORAGE ON ADSTORAGE.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND ADSTORAGE.NAMENAME = 'MachineNo' 
LEFT OUTER JOIN DB2ADMIN.ADSTORAGE AD5 ON AD5.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD5.NAMENAME = 'QtyOperIn'
LEFT OUTER JOIN DB2ADMIN.ADSTORAGE AD6 ON AD6.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD6.NAMENAME = 'QtyOperOut'
LEFT JOIN 
    (SELECT
      e.DEMANDCODE,
        COUNT(e.WEIGHTREALNET) AS JML,
        SUM(e.WEIGHTREALNET) AS JQTY
    FROM
        ELEMENTSINSPECTION e
    WHERE 
      e.ELEMENTITEMTYPECODE = 'KGF'
    GROUP BY 
      e.DEMANDCODE)e ON e.DEMANDCODE = i.PRODUCTIONDEMANDCODE
LEFT JOIN 
	(SELECT
			b.LOTCODE,
	      	sum(b.BASEPRIMARYQUANTITYUNIT) AS M502_KG
		FROM
	      	BALANCE b
		WHERE
	      	b.LOGICALWAREHOUSECODE = 'M502'
		GROUP BY
	      	b.LOTCODE)M502 ON M502.LOTCODE = i.PRODUCTIONDEMANDCODE
LEFT JOIN 
	(SELECT
			b.LOTCODE,
			sum(b.BASEPRIMARYQUANTITYUNIT) AS TR11_KG
        FROM
          	BALANCE b
        WHERE
          	b.LOGICALWAREHOUSECODE = 'TR11'
        GROUP BY
          	b.LOTCODE)TR11 ON TR11.LOTCODE = i.PRODUCTIONDEMANDCODE
LEFT JOIN
	(SELECT
			b.LOTCODE,
          	sum(b.BASEPRIMARYQUANTITYUNIT) AS M021_KG
        FROM
          	BALANCE b
        WHERE
          	b.LOGICALWAREHOUSECODE = 'M021'
        GROUP BY
          b.LOTCODE)M021 ON M021.LOTCODE = i.PRODUCTIONDEMANDCODE
LEFT JOIN 
	(SELECT
			PRODUCTIONDEMANDCODE,
		  	trim(LISTAGG (PROGRESSSTATUS , ',') WITHIN GROUP(ORDER BY PRODUCTIONDEMANDCODE ASC)) AS IDS
		FROM
		  	PRODUCTIONDEMANDSTEP
		WHERE
		  	 (OPERATIONCODE = 'INS1' OR OPERATIONCODE = 'KNT1' )
		GROUP BY
		  	PRODUCTIONDEMANDCODE)IDS ON IDS.PRODUCTIONDEMANDCODE = i.PRODUCTIONDEMANDCODE
LEFT JOIN
	(SELECT
	      	COUNT(WEIGHTREALNET) AS JML,
	      	INSPECTIONENDDATETIME
	    FROM
	      	ELEMENTSINSPECTION
	    WHERE
	      	ELEMENTITEMTYPECODE = 'KGF'
	      	AND QUALITYREASONCODE = 'PM'
	    GROUP BY
	      	INSPECTIONENDDATETIME)PM ON PM.DEMANDCODE = i.PRODUCTIONDEMANDCODE 
WHERE
  i.ITEMTYPEAFICODE = 'KGF'
  AND (i.PROGRESSSTATUS = '2'OR i.PROGRESSSTATUS = '6')
  AND ADD_DAYS(CASE 
          WHEN VARCHAR_FORMAT(i.FINALEFFECTIVEDATE, 'YYYY-MM-DD') IS NULL THEN VARCHAR_FORMAT(CURRENT_TIMESTAMP, 'YYYY-MM-DD') 
          ELSE VARCHAR_FORMAT(i.FINALEFFECTIVEDATE, 'YYYY-MM-DD') 
        END, 7) > CURRENT_TIMESTAMP