SELECT
	ELEMENTSINSPECTION.ELEMENTCODE,
	ELEMENTSINSPECTION.LENGTHUOMCODE,
	ELEMENTSINSPECTION.LENGTHGROSS,
	ELEMENTSINSPECTION.WEIGHTUOMCODE,
	ELEMENTSINSPECTION.WEIGHTGROSS,
	ELEMENTSINSPECTION.WEIGHTNET,
	ELEMENTSINSPECTION.WIDTHGROSS,
	ELEMENTSINSPECTION.WIDTHNET,
	PRODUCTIONDEMAND.COMPANYCODE,
	PRODUCTIONDEMAND.COUNTERCODE,
	PRODUCTIONDEMAND.CODE,
	PRODUCTIONDEMAND.ITEMTYPEAFICODE,
	PRODUCTIONDEMAND.SUBCODE01,
	PRODUCTIONDEMAND.SUBCODE02,
	PRODUCTIONDEMAND.SUBCODE03,
	PRODUCTIONDEMAND.SUBCODE04,
	PRODUCTIONDEMAND.SUBCODE05,
	PRODUCTIONDEMAND.SUBCODE06,
	PRODUCTIONDEMAND.SUBCODE07,
	PRODUCTIONDEMAND.SUBCODE08,
	PRODUCTIONDEMAND.SUBCODE09,
	PRODUCTIONDEMAND.SUBCODE10,
	PRODUCTIONDEMAND.DLVSALORDERLINESALESORDERCODE,
	PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE,
	PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE,
	ITXVIEW_DEMAND_KONDISI.SALESORDERCODE,
	ITXVIEW_DEMAND_KONDISI.SALESORDERLINE,
	ITXVIEW_DEMAND_KONDISI.ITEMTYPEAFICODE,
	ITXVIEW_DEMAND_KONDISI.SUBCODE01,
	ITXVIEW_DEMAND_KONDISI.SUBCODE02,
	ITXVIEW_DEMAND_KONDISI.SUBCODE03,
	ITXVIEW_DEMAND_KONDISI.SUBCODE04,
	ITXVIEW_DEMAND_KONDISI.SUBCODE05,
	ITXVIEW_DEMAND_KONDISI.SUBCODE06,
	ITXVIEW_DEMAND_KONDISI.SUBCODE07,
	ITXVIEW_DEMAND_KONDISI.SUBCODE08,
	ITXVIEW_DEMAND_KONDISI.SUBCODE09,
	ITXVIEW_DEMAND_KONDISI.SUBCODE10,
	SALESORDER.COUNTERCODE,
	SALESORDER.CODE,
	SALESORDER.DELIVERYPOINTUNIQUEID,
	SALESORDER.DELIVERYPOINTCODE,
	SALESORDER.STATISTICALGROUPCODE
FROM
	(
		(
			DB2ADMIN.ELEMENTSINSPECTION ELEMENTSINSPECTION
		LEFT OUTER JOIN 
       DB2ADMIN.PRODUCTIONDEMAND PRODUCTIONDEMAND ON
			ELEMENTSINSPECTION.DEMANDCODE = PRODUCTIONDEMAND.CODE
		)
	LEFT OUTER JOIN 
       DB2ADMIN.ITXVIEW_DEMAND_KONDISI ITXVIEW_DEMAND_KONDISI ON
		ELEMENTSINSPECTION.DEMANDCODE = ITXVIEW_DEMAND_KONDISI.DEMAND
	)
LEFT OUTER JOIN 
       DB2ADMIN.SALESORDER SALESORDER ON
	ITXVIEW_DEMAND_KONDISI.SALESORDERCODE = SALESORDER.CODE
WHERE
	ELEMENTSINSPECTION.ELEMENTCODE = '0026849090001'