SELECT DISTINCT 
    p.CODE AS BREAKDOWN,
    p3.CODE AS WORKORDER,
    LISTAGG(TRIM(p4.IDINTDOCUMENTPROVISIONALCODE), ', ') AS INTERNAL_DOC,
    SUBSTR(TRIM(d.LONGDESCRIPTION), 1,3)  || '/' || LTRIM(SUBSTR(p3.CODE, 6,6), '0') || ',' || SUBSTR(p3.CREATIONDATETIME, 6,2) || '/' || SUBSTR(p3.CREATIONDATETIME, 3,2) AS NO_FORM,
    p.PMBOMCODE AS NO_BARCODE,
    p.SYMPTOM,
    p3.REMARKS,
    p2.LONGDESCRIPTION AS PENGGUNA,
    p4.CREATIONUSER AS NAMA_DIBUAT,
    a4.MENUDESCR AS JABATAN_DIBUAT,
    p.CREATIONUSER AS NAMA_DITERIMA,
    a6.MENUDESCR AS JABATAN_DITERIMA,
    u2.LONGDESCRIPTION AS NAMA_KEPALA_USER,
    u2.SEARCHDESCRIPTION AS JABATAN_KEPALA_USER,
    u3.LONGDESCRIPTION AS NAMA_KEPALA_DIT,
    u3.SEARCHDESCRIPTION AS JABATAN_KEPALA_DIT,
    SUBSTR(p3.ENDDATE, 1, 10) AS TGL_FORM
FROM
    PMBREAKDOWNENTRY p
LEFT JOIN PMBOM p2 ON p2.CODE = p.PMBOMCODE 
LEFT JOIN DEPARTMENT d ON d.CODE = p2.DEPARTMENTCODE 
LEFT JOIN PMWORKORDER p3 ON p3.PMBREAKDOWNENTRYCODE = p.CODE 
LEFT JOIN PMWORKORDERACTIVITYSPARES p4 ON p4.PMWORKORDDLTPMWORKORDERCODE = p3.CODE 
LEFT JOIN UNITOFMEASURE u ON u.CODE = p4.QUANTITYUOMCODE
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p3.ABSUNIQUEID AND a.FIELDNAME = 'ApprovalDeptUserCode'
LEFT JOIN USERGENERICGROUP u2 ON u2.CODE = a.VALUESTRING AND u2.USERGENERICGROUPTYPECODE = 'HED'
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = p3.ABSUNIQUEID AND a2.FIELDNAME = 'ApprovalDeptDITCode'
LEFT JOIN USERGENERICGROUP u3 ON u3.CODE = a2.VALUESTRING AND u3.USERGENERICGROUPTYPECODE = 'DIT'
LEFT JOIN ABSUIINITIALMENU a3 ON a3.USERUSERID = p4.CREATIONUSER 
LEFT JOIN ABSUIMENU a4 ON a4.CODE = a3.MENU4CODE
LEFT JOIN ABSUIINITIALMENU a5 ON a5.USERUSERID = p.CREATIONUSER 
LEFT JOIN ABSUIMENU a6 ON a6.CODE = a5.MENU4CODE 
WHERE
    NOT p4.IDINTDOCUMENTPROVISIONALCODE IS NULL
    AND p3.CODE = 'BWO24001278'
GROUP BY
    p3.CODE,
    d.LONGDESCRIPTION,
    p.CODE,
    p.PMBOMCODE,
    p.SYMPTOM,
    p3.REMARKS,
    p2.LONGDESCRIPTION,
    p3.CREATIONDATETIME,
    p3.ENDDATE,
    p4.CREATIONUSER,
    p.CREATIONUSER,
    u2.LONGDESCRIPTION,
    u3.LONGDESCRIPTION,
    a4.MENUDESCR,
    a6.MENUDESCR,
    u2.SEARCHDESCRIPTION,
    u3.SEARCHDESCRIPTION