SELECT 
	BALANCE.ITEMTYPECODE,
	BALANCE.DECOSUBCODE01,
	BALANCE.DECOSUBCODE02,
	BALANCE.DECOSUBCODE03,
	BALANCE.DECOSUBCODE04,
	BALANCE.DECOSUBCODE05,
	BALANCE.DECOSUBCODE06,
	BALANCE.DECOSUBCODE07,
	BALANCE.DECOSUBCODE08,
	BALANCE.WHSLOCATIONWAREHOUSEZONECODE,
	BALANCE.WAREHOUSELOCATIONCODE,
	BALANCE.QUALITYLEVELCODE,
	BALANCE.LOTCODE,
	BALANCE.ELEMENTSCODE,
	BALANCE.BASEPRIMARYQUANTITYUNIT,
	BALANCE.BASESECONDARYUNITCODE,
	BALANCE.BASESECONDARYQUANTITYUNIT,
	BALANCE.CREATIONDATETIME,
	SALESORDER.CODE,
	SALESORDER.CONFIRMEDDUEDATE,
	SALESORDERDELIVERY.CONFIRMEDDELIVERYDATE,
	BALANCE.PROJECTCODE,
	PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE 
FROM
	(
		(
			(
				DB2ADMIN.BALANCE BALANCE
			FULL OUTER JOIN DB2ADMIN.SALESORDER 
       SALESORDER ON
				BALANCE.PROJECTCODE = SALESORDER.CODE
				AND 
       BALANCE.COMPANYCODE = SALESORDER.COMPANYCODE
			)
		LEFT OUTER JOIN 
       DB2ADMIN.ELEMENTS ELEMENTS ON
			BALANCE.ELEMENTSCODE = ELEMENTS.CODE
			AND 
       BALANCE.COMPANYCODE = ELEMENTS.COMPANYCODE
		)
	LEFT OUTER JOIN 
       DB2ADMIN.PRODUCTIONDEMAND PRODUCTIONDEMAND ON
		ELEMENTS.ENTRYDOCUMENTNUMBER = PRODUCTIONDEMAND.CODE
		AND 
       ELEMENTS.COMPANYCODE = PRODUCTIONDEMAND.COMPANYCODE
	)
LEFT OUTER JOIN DB2ADMIN.SALESORDERDELIVERY SALESORDERDELIVERY ON PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE = SALESORDERDELIVERY.SALESORDERLINESALESORDERCODE
	AND PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE = SALESORDERDELIVERY.SALESORDERLINEORDERLINE
WHERE
	BALANCE.PROJECTCODE = 'EXP2400294'
ORDER BY
	BALANCE.ELEMENTSCODE
	
	
SELECT EXTERNALITEM FROM ITXVIEW_STICKER is2 WHERE PROJECTCODE = 'EXP2400294' AND PRODUCTIONORDERCODE = '00171123' AND ELEMENTS = '0025717000301'