SELECT
	BALANCE.ITEMTYPECODE,
	BALANCE.DECOSUBCODE01,
	BALANCE.DECOSUBCODE02,
	BALANCE.DECOSUBCODE03,
	BALANCE.DECOSUBCODE04,
	BALANCE.DECOSUBCODE05,
	BALANCE.DECOSUBCODE06,
	BALANCE.DECOSUBCODE07,
	BALANCE.DECOSUBCODE08,
	BALANCE.DECOSUBCODE09,
	BALANCE.DECOSUBCODE10,
	BALANCE.WHSLOCATIONWAREHOUSEZONECODE,
	BALANCE.WAREHOUSELOCATIONCODE,
	BALANCE.QUALITYLEVELCODE,
	BALANCE.LOTCODE,
	BALANCE.ELEMENTSCODE,
	BALANCE.PROJECTCODE,
	BALANCE.BASEPRIMARYQUANTITYUNIT,
	BALANCE.BASESECONDARYUNITCODE,
	BALANCE.BASESECONDARYQUANTITYUNIT,
	BALANCE.CREATIONDATETIME,
	SALESORDER.CODE,
	SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE,
	SALESORDER.EXTERNALREFERENCE,
	SALESORDER.CONFIRMEDDUEDATE,
	ELEMENTS.ENTRYDOCUMENTNUMBER,
	PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE,
	PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE,
	SALESORDERDELIVERY.CONFIRMEDDELIVERYDATE,
	ITXVIEWMUTASIQCF_GKJ.TRANSACTIONDATE,
	ITXVIEWKK.EXTERNALITEM,
	ITXVIEWKK.ITEMDESCRIPTION
FROM
	(
		(
			(
				(
					(
						DB2ADMIN.BALANCE BALANCE
					FULL OUTER JOIN 
       DB2ADMIN.SALESORDER SALESORDER ON
						BALANCE.PROJECTCODE = SALESORDER.CODE
						AND 
       BALANCE.COMPANYCODE = SALESORDER.COMPANYCODE
					)
				LEFT OUTER JOIN 
       DB2ADMIN.ELEMENTS ELEMENTS ON
					BALANCE.ELEMENTSCODE = ELEMENTS.CODE
					AND BALANCE.COMPANYCODE = ELEMENTS.COMPANYCODE
				)
			LEFT OUTER JOIN 
       DB2ADMIN.PRODUCTIONDEMAND PRODUCTIONDEMAND ON
				ELEMENTS.ENTRYDOCUMENTNUMBER = PRODUCTIONDEMAND.CODE
				AND 
       ELEMENTS.COMPANYCODE = PRODUCTIONDEMAND.COMPANYCODE
			)
		LEFT OUTER JOIN 
       DB2ADMIN.SALESORDERDELIVERY SALESORDERDELIVERY ON
			PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE = SALESORDERDELIVERY.SALESORDERLINESALESORDERCODE
			AND 
       PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE = SALESORDERDELIVERY.SALESORDERLINEORDERLINE
		)
	LEFT OUTER JOIN 
       DB2ADMIN.ITXVIEWMUTASIQCF_GKJ ITXVIEWMUTASIQCF_GKJ ON
		BALANCE.ELEMENTSCODE = ITXVIEWMUTASIQCF_GKJ.ITEMELEMENTCODE
		AND 
       BALANCE.COMPANYCODE = ITXVIEWMUTASIQCF_GKJ.COMPANYCODE
	)
LEFT OUTER JOIN 
       DB2ADMIN.ITXVIEWKK ITXVIEWKK ON
	BALANCE.LOTCODE = ITXVIEWKK.PRODUCTIONORDERCODE
	AND ELEMENTS.ENTRYDOCUMENTNUMBER = ITXVIEWKK.DEAMAND
	AND 
       BALANCE.COMPANYCODE = ITXVIEWKK.COMPANYCODE
ORDER BY
	BALANCE.ELEMENTSCODE