SELECT DISTINCT
    s.CREATIONUSER AS MKT,
    TRIM(p.SUBCODE01) || '-' ||
    TRIM(p.SUBCODE02) || '-' ||
    TRIM(p.SUBCODE03) || '-' ||
    TRIM(p.SUBCODE04) || '-' ||
    TRIM(p.SUBCODE05) || '-' ||
    TRIM(p.SUBCODE06) || '-' ||
    TRIM(p.SUBCODE07) || '-' ||
    TRIM(p.SUBCODE08) AS ITEM,
    s.CODE AS SALESORDER,
    CASE
        WHEN p2.LONGDESCRIPTION IS NULL THEN s2.ITEMDESCRIPTION
        ELSE p2.LONGDESCRIPTION
    END || ' ' ||
    COALESCE(s.INTERNALREFERENCE, COALESCE(s2.INTERNALREFERENCE, '')) AS ITEMDESCRIPTION,
    TRIM(p.SUBCODE05) AS NO_WARNA,
    p.DESCRIPTION AS LOT,
    PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE,
    p.CODE AS DEMAND,
    s.REQUIREDDUEDATE AS DEL_INTERNAL,
    s.CONFIRMEDDUEDATE AS DEL_ACTUAL,
    p.ABSUNIQUEID AS ABSUNIQUEID_DEMAND,
    s.ABSUNIQUEID AS ABSUNIQUEID_SALESORDER,
    s.ORDPRNCUSTOMERSUPPLIERCODE,
    s2.ORDERLINE,
    p.ITEMTYPEAFICODE,
    p.SUBCODE01,
    p.SUBCODE02,
    p.SUBCODE03,
    p.SUBCODE04,
    p.SUBCODE05,
    p.SUBCODE06,
    p.SUBCODE07,
    p.SUBCODE08,
    p.SUBCODE09,
    p.SUBCODE10,
    a2.VALUEBOOLEAN AS FIRSTLOT,
    a3.VALUESTRING AS AKJAKW,
    CAST(po.CREATIONDATETIME AS DATE) AS TGL_BUKA_KK
FROM PRODUCTIONDEMAND p
LEFT JOIN (
    SELECT DISTINCT PRODUCTIONDEMANDCODE, PRODUCTIONORDERCODE
    FROM PRODUCTIONDEMANDSTEP
) PRODUCTIONDEMANDSTEP ON PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE = p.CODE
LEFT JOIN SALESORDERLINE s2 ON s2.SALESORDERCODE = p.ORIGDLVSALORDLINESALORDERCODE AND s2.ORDERLINE = p.ORIGDLVSALORDERLINEORDERLINE 
LEFT JOIN SALESORDER s ON s.CODE = p.ORIGDLVSALORDLINESALORDERCODE
LEFT JOIN PRODUCT p2 ON p2.ITEMTYPECODE = p.ITEMTYPEAFICODE 
                    AND p2.SUBCODE01 = p.SUBCODE01 
                    AND p2.SUBCODE02 = p.SUBCODE02 
                    AND p2.SUBCODE03 = p.SUBCODE03 
                    AND p2.SUBCODE04 = p.SUBCODE04 
                    AND p2.SUBCODE05 = p.SUBCODE05 
                    AND p2.SUBCODE06 = p.SUBCODE06 
                    AND p2.SUBCODE07 = p.SUBCODE07 
                    AND p2.SUBCODE08 = p.SUBCODE08 
                    AND p2.SUBCODE09 = p.SUBCODE09 
                    AND p2.SUBCODE10 = p.SUBCODE10
LEFT JOIN ADSTORAGE a1 ON a1.UNIQUEID = p.ABSUNIQUEID AND a1.FIELDNAME = 'OriginalPDCode'                    
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = s2.ABSUNIQUEID AND a2.FIELDNAME = 'FirstLot'
LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = s2.ABSUNIQUEID AND a3.FIELDNAME = 'KainAKJ'
LEFT JOIN PRODUCTIONORDER po ON po.CODE = PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE
WHERE 
    p.ORIGDLVSALORDLINESALORDERCODE = 'DOM2500758'
    AND p.PROGRESSSTATUS <> 6
    AND p.ITEMTYPEAFICODE = 'KFF'
    AND (
        a1.VALUESTRING IS NULL-- asli (bukan salinan)
        OR p.CREATIONUSER IN ('kukuh.bayu','yogi.rahmansyah')-- salinan tapi hanya 2 user ini
        )
    AND NOT PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE IS NULL
    AND COALESCE(SUBSTR(s.CODE, 1, 3), '') IN (
        'EXP', 'DOM', 'SAM', 'SME', 'REP',
        'RPE', 'RFD', 'DMB', 'TBG', 'RBG',
        'OPN', 'MNB'
    )