SELECT
	count(*) AS ROLL,
	s2.PRODUCTIONORDERCODE
FROM
	STOCKTRANSACTION s2
WHERE
	(s2.ITEMTYPECODE = 'KGF' OR s2.ITEMTYPECODE = 'KFF')
	AND s2.PRODUCTIONORDERCODE = '00157423'
GROUP BY
	s2.PRODUCTIONORDERCODE