SELECT
	SUM(BASEPRIMARYQUANTITYUNIT) AS QTY_READY,
	SUM(BASESECONDARYQUANTITYUNIT) AS QTY_READY_2
FROM
	BALANCE b
WHERE
	PROJECTCODE = 'EXP2400214'
	AND TRIM(DECOSUBCODE02) || '-' || TRIM(DECOSUBCODE03) = 'R11-22081'
	AND LOGICALWAREHOUSECODE = 'M031'
	
SELECT
	SUM(BASEPRIMARYQUANTITYUNIT) AS QTY_READY,
	SUM(BASESECONDARYQUANTITYUNIT) AS QTY_READY_2
FROM
	BALANCE b
WHERE
	PROJECTCODE = 'EXP2400214'
	AND TRIM(DECOSUBCODE02) || '-' || TRIM(DECOSUBCODE03) = 'R11-22081'
	AND LOGICALWAREHOUSECODE = 'M031'
	
SELECT
	SUM(BASEPRIMARYQUANTITYUNIT) AS QTY_READY,
	SUM(BASESECONDARYQUANTITYUNIT) AS QTY_READY_2
FROM
	BALANCE b
WHERE
	PROJECTCODE = 'EXP2400214'
	AND TRIM(DECOSUBCODE02) || '-' || TRIM(DECOSUBCODE03) = 'F3T-22062'
	AND LOGICALWAREHOUSECODE = 'M031'
	
SELECT
	SUM(BASEPRIMARYQUANTITYUNIT) AS QTY_READY,
	SUM(BASESECONDARYQUANTITYUNIT) AS QTY_READY_2
FROM
	BALANCE b
WHERE
	PROJECTCODE = 'EXP2400214'
	AND TRIM(DECOSUBCODE02) || '-' || TRIM(DECOSUBCODE03) = 'F3T-22062'
	AND LOGICALWAREHOUSECODE = 'M031'
	
SELECT
	SUM(BASEPRIMARYQUANTITYUNIT) AS QTY_READY,
	SUM(BASESECONDARYQUANTITYUNIT) AS QTY_READY_2
FROM
	BALANCE b
WHERE
	PROJECTCODE = 'EXP2400214'
	AND TRIM(DECOSUBCODE02) || '-' || TRIM(DECOSUBCODE03) = 'DKF-19106'
	AND LOGICALWAREHOUSECODE = 'M031'