SELECT 
    p.DLVSALESORDERLINEORDERLINE,
    TRIM(p.CODE) AS DEMANDCODE,
    trim(i2.ITEMTYPEAFICODE) AS ITEMTYPEAFICODE,
    trim(i2.SUBCODE01) AS SUBCODE01, 
    trim(i2.SUBCODE02) AS SUBCODE02,
    trim(i2.SUBCODE03) AS SUBCODE03, 
    trim(i2.SUBCODE04) AS SUBCODE04, 
    trim(i2.SUBCODE05) AS SUBCODE05,
    trim(i2.SUBCODE06) AS SUBCODE06,
    trim(i2.SUBCODE07) AS SUBCODE07,
    trim(i2.SUBCODE08) AS SUBCODE08,
    trim(i2.SUBCODE09) AS SUBCODE09,
    trim(i2.SUBCODE10) AS SUBCODE10,
    i.WARNA AS WARNA
FROM PRODUCTIONDEMAND p 
LEFT JOIN ITXVIEWBONORDER i2 ON i2.SALESORDERCODE = p.ORIGDLVSALORDLINESALORDERCODE AND i2.ORDERLINE = p.ORIGDLVSALORDERLINEORDERLINE 
LEFT JOIN ITXVIEWCOLOR i ON i.ITEMTYPECODE = i2.ITEMTYPEAFICODE 
                        AND i.SUBCODE01 = i2.SUBCODE01 
                        AND i.SUBCODE02 = i2.SUBCODE02 
                        AND i.SUBCODE03 = i2.SUBCODE03 
                        AND i.SUBCODE04 = i2.SUBCODE04 
                        AND i.SUBCODE05 = i2.SUBCODE05 
                        AND i.SUBCODE06 = i2.SUBCODE06 
                        AND i.SUBCODE07 = i2.SUBCODE07 
                        AND i.SUBCODE08 = i2.SUBCODE08 
                        AND i.SUBCODE09 = i2.SUBCODE09 
                        AND i.SUBCODE10 = i2.SUBCODE10
LEFT JOIN USERGENERICGROUP USERGENERICGROUP ON p.SUBCODE05 = USERGENERICGROUP.CODE 
WHERE p.ORIGDLVSALORDLINESALORDERCODE = 'OPN2500537'
GROUP BY 
    p.DLVSALESORDERLINEORDERLINE,i2.SUBCODE01,i2.SUBCODE02,i2.SUBCODE03,i2.SUBCODE04,i2.SUBCODE05,i2.SUBCODE06,i2.SUBCODE07,i2.SUBCODE08,i2.SUBCODE09,i2.SUBCODE10,i2.ITEMTYPEAFICODE,i.WARNA,p.CODE
