SELECT * FROM 
(SELECT 
    PRODUCTIONORDERCODE,
	MIN(GROUPSTEPNUMBER) AS GROUPSTEPNUMBER,
    INITIALUSERPRIMARYQUANTITY,
    INITIALUSERSECONDARYQUANTITY
FROM 
    VIEWPRODUCTIONDEMANDSTEP 
WHERE 
	PRODUCTIONORDERCODE = '00160270' 
GROUP BY
	PRODUCTIONORDERCODE,
    INITIALUSERPRIMARYQUANTITY,
    INITIALUSERSECONDARYQUANTITY)
ORDER BY 
	GROUPSTEPNUMBER ASC