SELECT
	* 
FROM
	ROUTINGSTEP 
	
	
SELECT ROUTINGNUMBERID,* FROM PRODUCTIONDEMAND p  WHERE CODE = '00273209'

 
SELECT  
	p.SUBCODE02,
	p.SUBCODE03,
    TRIM(r.OPERATIONCODE) AS OPERATIONCODE,
    TRIM(r.LONGDESCRIPTION) AS DESCRIPTION 
FROM
    PRODUCTIONDEMAND p
LEFT JOIN ROUTINGSTEP r ON r.ROUTINGNUMBERID = p.ROUTINGNUMBERID 
LEFT JOIN OPERATION o ON o.CODE = r.OPERATIONCODE 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = o.ABSUNIQUEID AND a.FIELDNAME = 'AlurProses'
WHERE 
    p.CODE = '00273209' 
    AND 
    a.VALUESTRING = '2'
ORDER BY
    r.SEQUENCE ASC
    
 
SELECT SUBCODE02,
	SUBCODE03,
	FIRSTUSERGRPCODE,
	SECONDUSERGRPCODE,
	SUBCODE06,
	OPERATIONCODE,
	LONGDESCRIPTION 
FROM (
SELECT DISTINCT 
	r.SEQUENCE,
	p.SUBCODE02,
	p.SUBCODE03,
	p.FIRSTUSERGRPCODE,
	p.SECONDUSERGRPCODE,
	p.SUBCODE06,
	r.OPERATIONCODE,
	r.LONGDESCRIPTION 
FROM
	PRODUCT p
LEFT JOIN ROUTINGSTEP r ON r.ROUTINGSUBCODE01 = p.FIRSTUSERGRPCODE AND r.ROUTINGSUBCODE02 = p.SECONDUSERGRPCODE AND r.ROUTINGSUBCODE03 = p.SUBCODE06
LEFT JOIN OPERATION o ON o.CODE = r.OPERATIONCODE 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = o.ABSUNIQUEID AND a.FIELDNAME = 'AlurProses'
WHERE
	p.ITEMTYPECODE = 'KFF' AND a.VALUESTRING = '2'
--	AND p.SUBCODE02 = 'HJY'
--	AND p.SUBCODE03 = '20124'
	)
GROUP BY 
	SUBCODE02,
	SUBCODE03,
	FIRSTUSERGRPCODE,
	SECONDUSERGRPCODE,
	SUBCODE06,
	OPERATIONCODE,
	LONGDESCRIPTION 
ORDER BY
	SEQUENCE ASC