SELECT
	ITXVIEW_SUBDETAIL_EXIM2.CODE,
	ITXVIEW_SUBDETAIL_EXIM2.PROVISIONALCODE,
	ITXVIEW_SUBDETAIL_EXIM2.EXTERNALREFERENCE,
	ITXVIEW_SUBDETAIL_EXIM2.LOTCODE,
	ITXVIEW_SUBDETAIL_EXIM2.ITEMELEMENTCODE,
	ITXVIEW_SUBDETAIL_EXIM2.JML_KG,
	ITXVIEW_SUBDETAIL_EXIM2.JML_YD,
	ITXVIEW_SUBDETAIL_EXIM2.JML_GW,
	ITXVIEW_SUBDETAIL_EXIM2.FOC_KG,
	ITXVIEW_SUBDETAIL_EXIM2.QUALITYREASON,
	ITXVIEW_SUBDETAIL_EXIM2.WIDTH,
	ITXVIEW_SUBDETAIL_EXIM2.EXTERNALITEM,
	ITXVIEW_SUBDETAIL_EXIM2.PROJECTCODE
FROM
	DB2ADMIN.ITXVIEW_SUBDETAIL_EXIM2 ITXVIEW_SUBDETAIL_EXIM2
WHERE
	ITXVIEW_SUBDETAIL_EXIM2.PROVISIONALCODE = 'GSP2400016' AND
	ITXVIEW_SUBDETAIL_EXIM2.LOTCODE = '00155091' AND
	ITXVIEW_SUBDETAIL_EXIM2.EXTERNALREFERENCE = '24100293IRS - 01' AND
	ITXVIEW_SUBDETAIL_EXIM2.EXTERNALITEM = 'HJY-18402' AND
	ITXVIEW_SUBDETAIL_EXIM2.PROJECTCODE = 'EXP2400397'
ORDER BY
	ITXVIEW_SUBDETAIL_EXIM2.LOTCODE,
	ITXVIEW_SUBDETAIL_EXIM2.ITEMELEMENTCODE