WITH BASEDATA AS (
	SELECT
		r.RECIPESUBCODE01,
		r.SEQUENCE,
		r.GROUPNUMBER,
		r.GROUPTYPECODE,
		CASE
			WHEN RIGHT(TRIM(r.RECIPESUBCODE01), 1) = 'D' THEN '1'
			WHEN RIGHT(TRIM(r.RECIPESUBCODE01), 1) = 'R' THEN '2'
			ELSE '1'
		END AS SUFFIXTYPE,
		r.RECIPESUFFIXCODE,
		r.SUBCODE01,
		r.SUBCODE02,
		r.SUBCODE03,
		CASE
			WHEN r.CONSUMPTION = 0 THEN NULL
			ELSE r.CONSUMPTION
		END AS CONSUMPTION,
		CASE
			WHEN GROUPTYPECODE = '100' THEN TRIM(r.COMMENTLINE)
			ELSE COALESCE(TRIM(r.SUBCODE01), '') || '-' || COALESCE(TRIM(r.SUBCODE02), '') || '-' || COALESCE(TRIM(r.SUBCODE03), '')
		END AS KODE,
		CASE
			WHEN RIGHT(TRIM(r.RECIPESUBCODE01), 1) = 'D' THEN 1
			WHEN RIGHT(TRIM(r.RECIPESUBCODE01), 1) = 'R' THEN 3
		END AS RECIPE_NUMBER,
		CASE
		    WHEN LEFT(TRIM(r.RECIPESUFFIXCODE), 3) = '250' THEN REPLACE(SUBSTR(TRIM(r.RECIPESUFFIXCODE), 4), '-', '')
		    ELSE REPLACE(TRIM(r.RECIPESUFFIXCODE), '-', '')
		END AS SUFFIX_NORM
	FROM
		RECIPECOMPONENT r
	LEFT JOIN RECIPE r2 ON r2.SUBCODE01 = r.RECIPESUBCODE01	AND r2.SUFFIXCODE = r.RECIPESUFFIXCODE
	LEFT JOIN ADSTORAGE a ON a.UNIQUEID = r2.ABSUNIQUEID AND a.FIELDNAME = 'RCode'
	WHERE
		r.RECIPESUBCODE01 IN ('25086/251053L/D', '25086/251053L/D')
		AND (
		    CASE
		        WHEN LEFT(TRIM(r.RECIPESUFFIXCODE), 3) = '250' THEN REPLACE(SUBSTR(TRIM(r.RECIPESUFFIXCODE), 4), '-', '')
		        ELSE REPLACE(TRIM(r.RECIPESUFFIXCODE), '-', '')
		    END
		) IN ('17867D','17867DS1','17867DS2','17867DS3','17867DS4','17867DS5','17867DS6','17867DS7')
		AND (
				(SUBSTR(a.VALUESTRING, 1, 2) = 'OB'	AND GROUPTYPECODE IN ('001', '100')
			)OR 
			(
				ITEMTYPEAFICODE = 'DYC' AND GROUPNUMBER < 20)
			)
),
CHECK_EXIST AS (
	SELECT
		MAX(CASE WHEN RECIPE_NUMBER = 1 THEN 1 ELSE 0 END) AS HAS_1,
		MAX(CASE WHEN RECIPE_NUMBER = 3 THEN 1 ELSE 0 END) AS HAS_3
	FROM
		BASEDATA
),
BASE AS (
	SELECT
		RECIPESUBCODE01,
        SEQUENCE,
        GROUPNUMBER,
        GROUPTYPECODE,
        SUFFIXTYPE,
        RECIPESUFFIXCODE,
        SUFFIX_NORM,
        SUBCODE01,
        SUBCODE02,
        SUBCODE03,
        CONSUMPTION,
        KODE,
        RECIPE_NUMBER
	FROM
		BASEDATA
UNION ALL
	SELECT
		'-'  AS RECIPESUBCODE01,
        2    AS SEQUENCE,
        NULL AS GROUPNUMBER,
        '2'  AS GROUPTYPECODE,
        '2'  AS SUFFIXTYPE,
        '-'  AS RECIPESUFFIXCODE,
        '-'  AS SUFFIX_NORM,
        '-'  AS SUBCODE01,
        '-'  AS SUBCODE02,
        '-'  AS SUBCODE03,
        NULL AS CONSUMPTION,
        '-'  AS KODE,
        2    AS RECIPE_NUMBER
	FROM
		ITXVIEW_KOSONG,
		CHECK_EXIST
	WHERE
		HAS_1 = 1
		AND HAS_3 = 1
),
PIVOTED AS (
	SELECT
		RECIPESUBCODE01,
		RECIPE_NUMBER,
		KODE,
		SEQUENCE,
		GROUPNUMBER,
		GROUPTYPECODE,
		SUFFIXTYPE,
		MAX(CASE WHEN SUFFIX_NORM = '17867D'   THEN CONSUMPTION END) AS LAB,
		MAX(CASE WHEN SUFFIX_NORM = '17867DS1' THEN CONSUMPTION END) AS ADJ1,
		MAX(CASE WHEN SUFFIX_NORM = '17867DS2' THEN CONSUMPTION END) AS ADJ2,
		MAX(CASE WHEN SUFFIX_NORM = '17867DS3' THEN CONSUMPTION END) AS ADJ3,
		MAX(CASE WHEN SUFFIX_NORM = '17867DS4' THEN CONSUMPTION END) AS ADJ4,
		MAX(CASE WHEN SUFFIX_NORM = '17867DS5' THEN CONSUMPTION END) AS ADJ5,
		MAX(CASE WHEN SUFFIX_NORM = '17867DS6' THEN CONSUMPTION END) AS ADJ6,
		MAX(CASE WHEN SUFFIX_NORM = '17867DS7' THEN CONSUMPTION END) AS ADJ7
	FROM
		BASE
	GROUP BY
		RECIPESUBCODE01,
		RECIPE_NUMBER,
		KODE,
		GROUPNUMBER,
		SEQUENCE,
		GROUPTYPECODE,
		SUFFIXTYPE
),
FINALDATA AS (
	SELECT
		P.RECIPESUBCODE01,
		P.RECIPE_NUMBER,
		ROW_NUMBER() OVER (ORDER BY P.SUFFIXTYPE, P.RECIPE_NUMBER,	P.GROUPNUMBER, P.SEQUENCE, P.KODE) AS FLAG,
		P.KODE || 
		CASE
			WHEN LAB IS NULL AND P.GROUPTYPECODE = '001' THEN ' (NEW)'
			WHEN COALESCE(LAB, ADJ1, ADJ2, ADJ3, ADJ4, ADJ5, ADJ6, ADJ7) IS NULL AND P.GROUPTYPECODE = '001' THEN ' (REMOVED)'
			ELSE ''
		END AS KODE,
		P.SEQUENCE,
		P.GROUPNUMBER,
		P.SUFFIXTYPE,
		P.LAB,
		P.ADJ1,
		P.ADJ2,
		P.ADJ3,
		P.ADJ4,
		P.ADJ5,
		P.ADJ6,
		P.ADJ7,
		CASE
			WHEN LAB IS NULL
			AND P.GROUPTYPECODE = '001' THEN 'NEW'
			WHEN COALESCE(LAB, ADJ1, ADJ2, ADJ3, ADJ4, ADJ5, ADJ6, ADJ7) IS NULL
				AND P.GROUPTYPECODE = '001' THEN 'REMOVED'
				ELSE ''
			END AS STATUSDYC
		FROM
			PIVOTED P
)
SELECT
	*
FROM
	FINALDATA
WHERE
	FLAG = 1
ORDER BY
	RECIPE_NUMBER,
	FLAG,
	SUFFIXTYPE,
	SEQUENCE,
	GROUPNUMBER,
	KODE