SELECT
--	i.ABSUNIQUEID_SALESORDERLINE,
	COALESCE(SUBSTRING(
        ad.OPTIONS, 
        POSITION(';' || a.VALUESTRING || '=' IN ad.OPTIONS) + LENGTH(a.VALUESTRING) + 2,
        POSITION(';' IN SUBSTRING(ad.OPTIONS, POSITION(';' || a.VALUESTRING || '=' IN ad.OPTIONS) + LENGTH(a.VALUESTRING) + 2)) - 1
    ), '-') || ' | ' || rd.VALUEDATE || ' | ' || dr.VALUESTRING  AS REVISI_HEADER1,
    COALESCE(SUBSTRING(
        ad2.OPTIONS, 
        POSITION(';' || a2.VALUESTRING || '=' IN ad2.OPTIONS) + LENGTH(a2.VALUESTRING) + 2,
        POSITION(';' IN SUBSTRING(ad2.OPTIONS, POSITION(';' || a2.VALUESTRING || '=' IN ad2.OPTIONS) + LENGTH(a2.VALUESTRING) + 2)) - 1
    ), '-') || ' | ' || rd2.VALUEDATE || ' | ' || dr2.VALUESTRING AS REVISI_HEADER2,
    COALESCE(SUBSTRING(
        ad3.OPTIONS, 
        POSITION(';' || a3.VALUESTRING || '=' IN ad3.OPTIONS) + LENGTH(a3.VALUESTRING) + 2,
        POSITION(';' IN SUBSTRING(ad3.OPTIONS, POSITION(';' || a3.VALUESTRING || '=' IN ad3.OPTIONS) + LENGTH(a3.VALUESTRING) + 2)) - 1
    ), '-') || ' | ' || rd3.VALUEDATE || ' | ' || dr3.VALUESTRING AS REVISI_HEADER3,
    COALESCE(SUBSTRING(
        ad2.OPTIONS, 
        POSITION(';' || a4.VALUESTRING || '=' IN ad4.OPTIONS) + LENGTH(a4.VALUESTRING) + 2,
        POSITION(';' IN SUBSTRING(ad4.OPTIONS, POSITION(';' || a4.VALUESTRING || '=' IN ad4.OPTIONS) + LENGTH(a4.VALUESTRING) + 2)) - 1
    ), '-') || ' | ' || rd4.VALUEDATE || ' | ' || dr4.VALUESTRING AS REVISI_HEADER4,
    COALESCE(SUBSTRING(
        ad2.OPTIONS, 
        POSITION(';' || a5.VALUESTRING || '=' IN ad5.OPTIONS) + LENGTH(a5.VALUESTRING) + 2,
        POSITION(';' IN SUBSTRING(ad5.OPTIONS, POSITION(';' || a5.VALUESTRING || '=' IN ad5.OPTIONS) + LENGTH(a5.VALUESTRING) + 2)) - 1
    ), '-') || ' | ' || rd5.VALUEDATE || ' | ' || dr5.VALUESTRING AS REVISI_HEADER5,
--    REVISI LINE
    COALESCE(SUBSTRING(
        l_ad.OPTIONS, 
        POSITION(';' || aa.VALUESTRING || '=' IN l_ad.OPTIONS) + LENGTH(aa.VALUESTRING) + 2,
        POSITION(';' IN SUBSTRING(l_ad.OPTIONS, POSITION(';' || aa.VALUESTRING || '=' IN l_ad.OPTIONS) + LENGTH(aa.VALUESTRING) + 2)) - 1
    ), '-') || ' | ' || l_rd.VALUEDATE || ' | ' || l_dr.VALUESTRING  AS REVISI_LINE1,
    COALESCE(SUBSTRING(
        l_ad2.OPTIONS, 
        POSITION(';' || aa1.VALUESTRING || '=' IN l_ad2.OPTIONS) + LENGTH(aa1.VALUESTRING) + 2,
        POSITION(';' IN SUBSTRING(l_ad2.OPTIONS, POSITION(';' || aa1.VALUESTRING || '=' IN l_ad2.OPTIONS) + LENGTH(aa1.VALUESTRING) + 2)) - 1
    ), '-') || ' | ' || l_rd2.VALUEDATE || ' | ' || l_dr2.VALUESTRING AS REVISI_LINE2,
    COALESCE(SUBSTRING(
        l_ad3.OPTIONS, 
        POSITION(';' || aa2.VALUESTRING || '=' IN l_ad3.OPTIONS) + LENGTH(aa2.VALUESTRING) + 2,
        POSITION(';' IN SUBSTRING(l_ad3.OPTIONS, POSITION(';' || aa2.VALUESTRING || '=' IN l_ad3.OPTIONS) + LENGTH(aa2.VALUESTRING) + 2)) - 1
    ), '-') || ' | ' || l_rd3.VALUEDATE || ' | ' || l_dr3.VALUESTRING AS REVISI_LINE3,
    COALESCE(SUBSTRING(
        l_ad2.OPTIONS, 
        POSITION(';' || aa3.VALUESTRING || '=' IN l_ad4.OPTIONS) + LENGTH(aa3.VALUESTRING) + 2,
        POSITION(';' IN SUBSTRING(l_ad4.OPTIONS, POSITION(';' || aa3.VALUESTRING || '=' IN l_ad4.OPTIONS) + LENGTH(aa3.VALUESTRING) + 2)) - 1
    ), '-') || ' | ' || l_rd4.VALUEDATE || ' | ' || l_dr4.VALUESTRING AS REVISI_LINE4,
    COALESCE(SUBSTRING(
        l_ad2.OPTIONS, 
        POSITION(';' || aa4.VALUESTRING || '=' IN l_ad5.OPTIONS) + LENGTH(aa4.VALUESTRING) + 2,
        POSITION(';' IN SUBSTRING(l_ad5.OPTIONS, POSITION(';' || aa4.VALUESTRING || '=' IN l_ad5.OPTIONS) + LENGTH(aa4.VALUESTRING) + 2)) - 1
    ), '-') || ' | ' || l_rd5.VALUEDATE || ' | ' || l_dr5.VALUESTRING AS REVISI_LINE5,
    CASE
		WHEN (a.VALUESTRING IS NOT NULL) OR (a2.VALUESTRING IS NOT NULL) OR (a3.VALUESTRING IS NOT NULL) OR (a4.VALUESTRING IS NOT NULL) OR (a5.VALUESTRING IS NOT NULL) THEN 'REVISI'
		WHEN (rd.VALUEDATE IS NOT NULL) OR (rd2.VALUEDATE IS NOT NULL) OR (rd3.VALUEDATE IS NOT NULL) OR (rd4.VALUEDATE IS NOT NULL) OR (rd5.VALUEDATE IS NOT NULL) THEN 'REVISI'
		WHEN (dr.VALUESTRING IS NOT NULL) OR (dr2.VALUESTRING IS NOT NULL) OR (dr3.VALUESTRING IS NOT NULL) OR (dr4.VALUESTRING IS NOT NULL) OR (dr5.VALUESTRING IS NOT NULL) THEN 'REVISI'
		WHEN (aa.VALUESTRING IS NOT NULL) OR (aa1.VALUESTRING IS NOT NULL) OR (aa2.VALUESTRING IS NOT NULL) OR (aa3.VALUESTRING IS NOT NULL) OR (aa4.VALUESTRING IS NOT NULL) THEN 'REVISI'
		WHEN (l_rd.VALUEDATE IS NOT NULL) OR (l_rd2.VALUEDATE IS NOT NULL) OR (l_rd3.VALUEDATE IS NOT NULL) OR (l_rd4.VALUEDATE IS NOT NULL) OR (l_rd5.VALUEDATE IS NOT NULL) THEN 'REVISI'
		WHEN (l_dr.VALUESTRING IS NOT NULL) OR (l_dr2.VALUESTRING IS NOT NULL) OR (l_dr3.VALUESTRING IS NOT NULL) OR (l_dr4.VALUESTRING IS NOT NULL) OR (l_dr5.VALUESTRING IS NOT NULL) THEN 'REVISI'
    END AS REVISI    
FROM
	ITXVIEWBONORDER i
-- REVISI HEADER NAME
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = i.ABSUNIQUEID_SALESORDER AND a.FIELDNAME = 'RevisiC'
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = i.ABSUNIQUEID_SALESORDER AND a2.FIELDNAME = 'Revisi2'
LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = i.ABSUNIQUEID_SALESORDER AND a3.FIELDNAME = 'Revisi3'
LEFT JOIN ADSTORAGE a4 ON a4.UNIQUEID = i.ABSUNIQUEID_SALESORDER AND a4.FIELDNAME = 'Revisi4'
LEFT JOIN ADSTORAGE a5 ON a5.UNIQUEID = i.ABSUNIQUEID_SALESORDER AND a5.FIELDNAME = 'Revisi5'
-- WHO REVISI HEADER NAME
LEFT JOIN ADADDITIONALDATA ad ON ad.ENTITYNAME = 'SalesOrder' AND ad.NAME = 'RevisiC'
LEFT JOIN ADADDITIONALDATA ad2 ON ad2.ENTITYNAME = 'SalesOrder' AND ad2.NAME = 'Revisi2'
LEFT JOIN ADADDITIONALDATA ad3 ON ad3.ENTITYNAME = 'SalesOrder' AND ad3.NAME = 'Revisi3'
LEFT JOIN ADADDITIONALDATA ad4 ON ad4.ENTITYNAME = 'SalesOrder' AND ad4.NAME = 'Revisi4'
LEFT JOIN ADADDITIONALDATA ad5 ON ad5.ENTITYNAME = 'SalesOrder' AND ad5.NAME = 'Revisi5'
-- REVISI HEADER DATE
LEFT JOIN ADSTORAGE rd ON rd.UNIQUEID = i.ABSUNIQUEID_SALESORDER AND rd.FIELDNAME = 'Revisi1Date'
LEFT JOIN ADSTORAGE rd2 ON rd2.UNIQUEID = i.ABSUNIQUEID_SALESORDER AND rd2.FIELDNAME = 'Revisi2Date'
LEFT JOIN ADSTORAGE rd3 ON rd3.UNIQUEID = i.ABSUNIQUEID_SALESORDER AND rd3.FIELDNAME = 'Revisi3Date'
LEFT JOIN ADSTORAGE rd4 ON rd4.UNIQUEID = i.ABSUNIQUEID_SALESORDER AND rd4.FIELDNAME = 'Revisi4Date'
LEFT JOIN ADSTORAGE rd5 ON rd5.UNIQUEID = i.ABSUNIQUEID_SALESORDER AND rd5.FIELDNAME = 'Revisi5Date'
-- REVISI HEADER DETAIL
LEFT JOIN ADSTORAGE dr ON dr.UNIQUEID = i.ABSUNIQUEID_SALESORDER AND dr.FIELDNAME = 'RevisiN'
LEFT JOIN ADSTORAGE dr2 ON dr2.UNIQUEID = i.ABSUNIQUEID_SALESORDER AND dr2.FIELDNAME = 'DRevisi2'
LEFT JOIN ADSTORAGE dr3 ON dr3.UNIQUEID = i.ABSUNIQUEID_SALESORDER AND dr3.FIELDNAME = 'DRevisi3'
LEFT JOIN ADSTORAGE dr4 ON dr4.UNIQUEID = i.ABSUNIQUEID_SALESORDER AND dr4.FIELDNAME = 'DRevisi4'
LEFT JOIN ADSTORAGE dr5 ON dr5.UNIQUEID = i.ABSUNIQUEID_SALESORDER AND dr5.FIELDNAME = 'DRevisi5'
--------------------------------------------------------------------------------------------------
-- REVISI LINE NAME
LEFT JOIN ADSTORAGE aa ON aa.UNIQUEID = i.ABSUNIQUEID_SALESORDERLINE AND aa.FIELDNAME = 'RevisiC'
LEFT JOIN ADSTORAGE aa1 ON aa1.UNIQUEID = i.ABSUNIQUEID_SALESORDERLINE AND aa1.FIELDNAME = 'RevisiC1'
LEFT JOIN ADSTORAGE aa2 ON aa2.UNIQUEID = i.ABSUNIQUEID_SALESORDERLINE AND aa2.FIELDNAME = 'RevisiC2'
LEFT JOIN ADSTORAGE aa3 ON aa3.UNIQUEID = i.ABSUNIQUEID_SALESORDERLINE AND aa3.FIELDNAME = 'RevisiC3'
LEFT JOIN ADSTORAGE aa4 ON aa4.UNIQUEID = i.ABSUNIQUEID_SALESORDERLINE AND aa4.FIELDNAME = 'RevisiC4'
-- WHO REVISI HEADER NAME
LEFT JOIN ADADDITIONALDATA l_ad ON l_ad.ENTITYNAME = 'SalesOrderLine' AND l_ad.NAME = 'RevisiC'
LEFT JOIN ADADDITIONALDATA l_ad2 ON l_ad2.ENTITYNAME = 'SalesOrderLine' AND l_ad2.NAME = 'RevisiC1'
LEFT JOIN ADADDITIONALDATA l_ad3 ON l_ad3.ENTITYNAME = 'SalesOrderLine' AND l_ad3.NAME = 'RevisiC2'
LEFT JOIN ADADDITIONALDATA l_ad4 ON l_ad4.ENTITYNAME = 'SalesOrderLine' AND l_ad4.NAME = 'RevisiC3'
LEFT JOIN ADADDITIONALDATA l_ad5 ON l_ad5.ENTITYNAME = 'SalesOrderLine' AND l_ad5.NAME = 'RevisiC4'
-- REVISI LINE DATE
LEFT JOIN ADSTORAGE l_rd ON l_rd.UNIQUEID = i.ABSUNIQUEID_SALESORDERLINE AND l_rd.FIELDNAME = 'Revisi1Date'
LEFT JOIN ADSTORAGE l_rd2 ON l_rd2.UNIQUEID = i.ABSUNIQUEID_SALESORDERLINE AND l_rd2.FIELDNAME = 'Revisi2Date'
LEFT JOIN ADSTORAGE l_rd3 ON l_rd3.UNIQUEID = i.ABSUNIQUEID_SALESORDERLINE AND l_rd3.FIELDNAME = 'Revisi3Date'
LEFT JOIN ADSTORAGE l_rd4 ON l_rd4.UNIQUEID = i.ABSUNIQUEID_SALESORDERLINE AND l_rd4.FIELDNAME = 'Revisi4Date'
LEFT JOIN ADSTORAGE l_rd5 ON l_rd5.UNIQUEID = i.ABSUNIQUEID_SALESORDERLINE AND l_rd5.FIELDNAME = 'Revisi5Date'
-- REVISI LINE DETAIL
LEFT JOIN ADSTORAGE l_dr ON l_dr.UNIQUEID = i.ABSUNIQUEID_SALESORDERLINE AND l_dr.FIELDNAME = 'Revisid'
LEFT JOIN ADSTORAGE l_dr2 ON l_dr2.UNIQUEID = i.ABSUNIQUEID_SALESORDERLINE AND l_dr2.FIELDNAME = 'Revisi2'
LEFT JOIN ADSTORAGE l_dr3 ON l_dr3.UNIQUEID = i.ABSUNIQUEID_SALESORDERLINE AND l_dr3.FIELDNAME = 'Revisi3'
LEFT JOIN ADSTORAGE l_dr4 ON l_dr4.UNIQUEID = i.ABSUNIQUEID_SALESORDERLINE AND l_dr4.FIELDNAME = 'Revisi4'
LEFT JOIN ADSTORAGE l_dr5 ON l_dr5.UNIQUEID = i.ABSUNIQUEID_SALESORDERLINE AND l_dr5.FIELDNAME = 'Revisi5'
WHERE 
	i.SALESORDERCODE = 'DOM2500778'