SELECT
	x.PRODUCTIONDEMANDCODE,
	x.PRODUCTIONORDERCODE,
	s.LOTCODE,
	COUNT(s.ITEMELEMENTCODE) AS JML
FROM
	DB2ADMIN.ITXVIEWKK x
LEFT OUTER JOIN DB2ADMIN.STOCKTRANSACTION s ON
	x.PRODUCTIONORDERCODE = s.ORDERCODE
WHERE
	s.TEMPLATECODE = '120'
	AND s.ITEMTYPECODE = 'KGF' 
	AND x.PRODUCTIONORDERCODE ='00174521'
GROUP BY
	x.PRODUCTIONDEMANDCODE,
	x.PRODUCTIONORDERCODE,
	s.LOTCODE