SELECT
	SUM(CASE 
			WHEN INSPEK.KGPAKAI > 0 THEN 1 
			ELSE 0 
		END) AS TOTMC
FROM
	ITXVIEWKNTORDER
LEFT OUTER JOIN DB2ADMIN.PRODUCTIONDEMAND ON PRODUCTIONDEMAND.CODE = ITXVIEWKNTORDER.PRODUCTIONDEMANDCODE
LEFT OUTER JOIN DB2ADMIN.ADSTORAGE ON ADSTORAGE.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID	AND ADSTORAGE.NAMENAME = 'MachineNo'
LEFT OUTER JOIN DB2ADMIN.ADSTORAGE AD6 ON AD6.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD6.FIELDNAME = 'StatusOper'
LEFT OUTER JOIN DB2ADMIN.ADSTORAGE AD8 ON AD8.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND AD8.FIELDNAME = 'StatusMesin'
LEFT OUTER JOIN ( 
		SELECT 
			COUNT(WEIGHTREALNET ) AS KGPAKAI,
			DEMANDCODE 
		FROM 
			ELEMENTSINSPECTION
		WHERE 
			ELEMENTITEMTYPECODE='KGF' 
			AND COMPANYCODE='100'
		GROUP BY 
			DEMANDCODE
		) INSPEK ON INSPEK.DEMANDCODE = ITXVIEWKNTORDER.PRODUCTIONDEMANDCODE	
WHERE
	PRODUCTIONDEMAND.ITEMTYPEAFICODE = 'KGF'
	AND (PRODUCTIONDEMAND.PROGRESSSTATUS = '0'
		OR PRODUCTIONDEMAND.PROGRESSSTATUS = '1'
		OR PRODUCTIONDEMAND.PROGRESSSTATUS = '2'
		OR AD6.VALUESTRING = '1')
	AND ITXVIEWKNTORDER.PROGRESSSTATUS IN('2', '6')
	AND AD8.VALUESTRING IN('0', '1')
	AND ITXVIEWKNTORDER.ORIGDLVSALORDLINESALORDERCODE = 'OPN2500456'
	AND CONCAT(CONCAT(CONCAT(RTRIM(ITXVIEWKNTORDER.SUBCODE01), ' '), 
		CONCAT(RTRIM(ITXVIEWKNTORDER.SUBCODE02), 
		RTRIM(ITXVIEWKNTORDER.SUBCODE03))), 
		CONCAT(' ', RTRIM(ITXVIEWKNTORDER.SUBCODE04))) = 'CVC F3C25033 L02'