SELECT 
		bl.*,
		SALESORDER.CODE, 
		SALESORDER.EXTERNALREFERENCE,
		SALESORDER.ORDPRNCUSTOMERSUPPLIERCODE,
		ITXVIEWAKJ.LEGALNAME1,
		ITXVIEWAKJ.ORDERPARTNERBRANDCODE,
		ITXVIEWAKJ.LONGDESCRIPTION
	FROM 
	(SELECT
		SUM(b.BASEPRIMARYQUANTITYUNIT) AS BERAT,
		SUM(b.BASESECONDARYQUANTITYUNIT) AS YD,
		COUNT(b.BASESECONDARYQUANTITYUNIT) AS ROLL,
		b.LOTCODE,
		b.PROJECTCODE,
		b.ITEMTYPECODE,
		b.DECOSUBCODE01,
		b.DECOSUBCODE02,
		b.DECOSUBCODE03,
		b.DECOSUBCODE04,
		b.DECOSUBCODE05,
		b.DECOSUBCODE06,
		b.DECOSUBCODE07,
		b.DECOSUBCODE08,
		b.BASEPRIMARYUNITCODE,
		b.BASESECONDARYUNITCODE,
		b.WHSLOCATIONWAREHOUSEZONECODE,
		b.WAREHOUSELOCATIONCODE,
		b.ELEMENTSCODE
	FROM 
		BALANCE b 
	WHERE 
		(b.ITEMTYPECODE='FKF' OR b.ITEMTYPECODE='KFF') AND b.LOGICALWAREHOUSECODE='M031' 
		AND (TRIM(b.WHSLOCATIONWAREHOUSEZONECODE) LIKE '%Y%' OR 
		TRIM(b.WHSLOCATIONWAREHOUSEZONECODE) LIKE '%Z%' OR 
		TRIM(b.WHSLOCATIONWAREHOUSEZONECODE) LIKE '%W%' OR 
		TRIM(b.WHSLOCATIONWAREHOUSEZONECODE) LIKE '%X%')
	GROUP BY 
		b.ITEMTYPECODE,b.DECOSUBCODE01,
		b.DECOSUBCODE02,b.DECOSUBCODE03,
		b.DECOSUBCODE04,b.DECOSUBCODE05,
		b.DECOSUBCODE06,b.DECOSUBCODE07,
		b.DECOSUBCODE08,b.PROJECTCODE,b.LOTCODE,
		b.BASEPRIMARYUNITCODE,b.BASESECONDARYUNITCODE,
		b.WHSLOCATIONWAREHOUSEZONECODE,b.WAREHOUSELOCATIONCODE,b.ELEMENTSCODE) bl 
LEFT OUTER JOIN	DB2ADMIN.SALESORDER SALESORDER ON bl.PROJECTCODE = SALESORDER.CODE
LEFT OUTER JOIN DB2ADMIN.ITXVIEWAKJ ITXVIEWAKJ ON SALESORDER.CODE=ITXVIEWAKJ.CODE 
LEFT JOIN PRODUCTIONDEMAND p ON p.ITEMTYPEAFICODE = bl.DECOSUBCODE01
							AND p.ITEMTYPEAFICODE = bl.ITEMTYPECODE
							AND p.SUBCODE01 = bl.DECOSUBCODE01
							AND p.SUBCODE02 = bl.DECOSUBCODE02
							AND p.SUBCODE03 = bl.DECOSUBCODE03
							AND p.SUBCODE04 = bl.DECOSUBCODE04
							AND p.SUBCODE05 = bl.DECOSUBCODE05
							AND p.SUBCODE06 = bl.DECOSUBCODE06
							AND p.SUBCODE07 = bl.DECOSUBCODE07
							AND p.SUBCODE08 = bl.DECOSUBCODE08
							AND p.DLVSALORDERLINESALESORDERCODE = SALESORDER.CODE
WHERE 
	(bl.ITEMTYPECODE='FKF' OR bl.ITEMTYPECODE='KFF')
	AND NOT bl.PROJECTCODE IS NULL 
	AND NOT bl.PROJECTCODE = ''