SELECT
  q2.LINE,
  q.PRODUCTIONORDERCODE,
  LISTAGG('''' || a.valueint || '''', ',') AS STEPNUMBER,
  LISTAGG(TRIM(q.OPERATIONCODE), ', ') AS OPERATIONCODE
FROM
  QUALITYDOCUMENT q
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = q.ABSUNIQUEID AND a.FIELDNAME = 'GroupStepNumber'
LEFT JOIN QUALITYDOCLINE q2 ON q2.QUALITYDOCUMENTHEADERLINE = q.HEADERLINE
              AND (TRIM(q2.CHARACTERISTICCODE) = 'WHITENESS'
                OR TRIM(q2.CHARACTERISTICCODE) = 'YELLOWNESS'
                OR TRIM(q2.CHARACTERISTICCODE) = 'TINT')
              AND NOT q2.VALUEQUANTITY = 0
WHERE
  q.PRODUCTIONORDERCODE = '00153320'
  AND q2.LINE = 11
GROUP BY
  q2.LINE,
  q.PRODUCTIONORDERCODE
  
SELECT 
	LISTAGG(TRIM(SUBCODE01)) AS RCODE,
	LISTAGG(TRIM(SUFFIXCODE)) AS RCODESUFFIX,
	LISTAGG(TRIM(PRODRESERVATIONLINKGROUPCODE) || ' = ' || DECIMAL(LR, 5,2), ', ') AS LR,
	LISTAGG(TRIM(PRODRESERVATIONLINKGROUPCODE) || ' = ' || TRIM(SUBCODE01) || '-' || TRIM(SUFFIXCODE), ', ') AS SUFFIX,
	LISTAGG(TRIM(PRODRESERVATIONLINKGROUPCODE) || ' = ' || TRIM(LONGDESCRIPTION), ', ') AS LONGDESCRIPTION,
	LISTAGG(TRIM(PRODRESERVATIONLINKGROUPCODE) || ' = ' || TRIM(SHORTDESCRIPTION), ', ') AS SHORTDESCRIPTION,
	LISTAGG(TRIM(PRODRESERVATIONLINKGROUPCODE) || ' = ' || TRIM(SEARCHDESCRIPTION), ', ') AS SEARCHDESCRIPTION
  FROM (
    SELECT 
      DISTINCT 
      p.PRODRESERVATIONLINKGROUPCODE,
      p.PICKUPQUANTITY AS LR,
      p.SUBCODE01,
      p.SUFFIXCODE,
      r.LONGDESCRIPTION,
      r.SHORTDESCRIPTION,
      r.SEARCHDESCRIPTION
    FROM 
      PRODUCTIONRESERVATION p 
    LEFT JOIN RECIPE r ON r.SUBCODE01 = p.SUBCODE01 AND r.SUFFIXCODE = p.SUFFIXCODE 
    LEFT JOIN VIEWPRODUCTIONDEMANDSTEP v ON v.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND v.GROUPSTEPNUMBER = p.GROUPSTEPNUMBER
    WHERE	
      p.PRODUCTIONORDERCODE = '00153320'  
--	  AND 
--	  CASE 
--	    WHEN v.STEPTYPE = 3 THEN p.GROUPSTEPNUMBER IN ('110')
--	    ELSE p.STEPNUMBER IN ('110')
--	  END 
--	  AND p.ITEMNATURE = 9
--	  AND SUBSTR(p.SUBCODE01, 1,2) = 'SC' 
GROUP BY
  p.PRODRESERVATIONLINKGROUPCODE,
  p.PICKUPQUANTITY,
  p.SUBCODE01,
  p.SUFFIXCODE,
  r.LONGDESCRIPTION,
  r.SHORTDESCRIPTION,
  r.SEARCHDESCRIPTION)