SELECT * FROM SYSIBMADM.LOCKWAITS LW

SELECT * FROM SYSIBMADM.APPLICATIONS WHERE APPL_STATUS = 'UOWWAIT'

SELECT 
	APPLICATION_HANDLE,
    STMT_TEXT
FROM SYSIBMADM.MON_CURRENT_SQL
--WHERE APPLICATION_HANDLE = <holder_id>;