SELECT
	SALESDOCUMENT.COMPANYCODE,
	SALESDOCUMENT.PROVISIONALCOUNTERCODE,
	SALESDOCUMENT.PROVISIONALCODE,
	ITXVIEW_SUBPACKINGLIST_EXIM2.DESC_OF_GOODS,
	ITXVIEW_SUBPACKINGLIST_EXIM2.PROVISIONALCODE,
	ITXVIEW_SUBPACKINGLIST_EXIM2.PROVISIONALDOCUMENTDATE,
	ITXVIEW_SUBPACKINGLIST_EXIM2.EXTERNALREFERENCE,
	ITXVIEW_SUBPACKINGLIST_EXIM2.EXTERNALITEM,
	ITXVIEW_SUBPACKINGLIST_EXIM2.LOTCODE,
	ITXVIEW_SUBPACKINGLIST_EXIM2.NO_ORDER,
	ITXVIEW_SUBPACKINGLIST_EXIM2.DECOSUBCODE02,
	ITXVIEW_SUBPACKINGLIST_EXIM2.DECOSUBCODE03,
	ITXVIEW_SUBPACKINGLIST_EXIM2.ITEMDESCRIPTION,
	ITXVIEW_SUBPACKINGLIST_EXIM2.COMPANYCODE,
	ITXVIEW_SUBPACKINGLIST_EXIM2.WIDTH
FROM
	DB2ADMIN.SALESDOCUMENT SALESDOCUMENT
LEFT OUTER JOIN DB2ADMIN.ITXVIEW_SUBPACKINGLIST_EXIM2 ITXVIEW_SUBPACKINGLIST_EXIM2 ON SALESDOCUMENT.PROVISIONALCODE = ITXVIEW_SUBPACKINGLIST_EXIM2.PROVISIONALCODE
	AND SALESDOCUMENT.COMPANYCODE = ITXVIEW_SUBPACKINGLIST_EXIM2.COMPANYCODE
WHERE 
	SALESDOCUMENT.PROVISIONALCODE = 'PED2400320'
ORDER BY
	ITXVIEW_SUBPACKINGLIST_EXIM2.DESC_OF_GOODS
	
	
SELECT
	ITXVIEW_SUBDETAIL_EXIM2.CODE,
	ITXVIEW_SUBDETAIL_EXIM2.PROVISIONALCODE,
	ITXVIEW_SUBDETAIL_EXIM2.EXTERNALREFERENCE,
	ITXVIEW_SUBDETAIL_EXIM2.LOTCODE,
	ITXVIEW_SUBDETAIL_EXIM2.ITEMELEMENTCODE,
	ITXVIEW_SUBDETAIL_EXIM2.JML_KG,
	ITXVIEW_SUBDETAIL_EXIM2.JML_YD,
	ITXVIEW_SUBDETAIL_EXIM2.JML_GW,
	ITXVIEW_SUBDETAIL_EXIM2.FOC_KG,
	ITXVIEW_SUBDETAIL_EXIM2.QUALITYREASON,
	ITXVIEW_SUBDETAIL_EXIM2.COMPANYCODE,
	ITXVIEW_SUBDETAIL_EXIM2.WIDTH
FROM
	DB2ADMIN.ITXVIEW_SUBDETAIL_EXIM2 ITXVIEW_SUBDETAIL_EXIM2
WHERE
	ITXVIEW_SUBDETAIL_EXIM2.LOTCODE IN ('00171512',                       
'00171513',                           
'00172572',                           
'00171514',                           
'00171515',                           
'00172600',                           
'00172602',                           
'00170802',                           
'00170803',                           
'00171510',                           
'00171511',                           
'00172568',                           
'00172569',                           
'00170810',                           
'00170808',                           
'00172799',                           
'00170804',                           
'00170805',                           
'00170806')
	AND ITXVIEW_SUBDETAIL_EXIM2.EXTERNALREFERENCE = 'Athleta FA/HO25 LA Sample Yardage Request'
	AND ITXVIEW_SUBDETAIL_EXIM2.PROVISIONALCODE = 'PED2400320'
ORDER BY
	ITXVIEW_SUBDETAIL_EXIM2.LOTCODE,
	ITXVIEW_SUBDETAIL_EXIM2.ITEMELEMENTCODE
	
SELECT
	ITXVIEW_GRANDTOTAL_PACKINGLIST_EXIM2.PROVISIONALCODE,
	ITXVIEW_GRANDTOTAL_PACKINGLIST_EXIM2.JML_ROLL,
	ITXVIEW_GRANDTOTAL_PACKINGLIST_EXIM2.JML_BALES,
	ITXVIEW_GRANDTOTAL_PACKINGLIST_EXIM2.JML_KG,
	ITXVIEW_GRANDTOTAL_PACKINGLIST_EXIM2.JML_YD,
	ITXVIEW_GRANDTOTAL_PACKINGLIST_EXIM2.JML_GW,
	ITXVIEW_GRANDTOTAL_PACKINGLIST_EXIM2.ITEMTYPEAFICODE,
	ITXVIEW_GRANDTOTAL_PACKINGLIST_EXIM2.PROVISIONALCOUNTERCODE
FROM
	DB2ADMIN.ITXVIEW_GRANDTOTAL_PACKINGLIST_EXIM2 
       ITXVIEW_GRANDTOTAL_PACKINGLIST_EXIM2
WHERE 
	ITXVIEW_GRANDTOTAL_PACKINGLIST_EXIM2.PROVISIONALCODE = 'PED2400320'