SELECT
    COUNT(ise.COUNTROLL) AS ROLL,
    SUM(ise.QTY_KG) AS QTY_SJ_KG,
    SUM(ise.QTY_YARDMETER) AS QTY_SJ_YARD,
    inpe.PROJECT,
    ise.ADDRESSEE,
    ise.BRAND_NM,
    ise.ALLOCATIONCODE
FROM
    ITXVIEW_SURATJALAN_EXIM2A ise 
LEFT JOIN ITXVIEW_NO_PROJECTS_EXIM inpe ON inpe.PROVISIONALCODE = ise.PROVISIONALCODE 
WHERE 
    ise.PROVISIONALCODE = 'ESP2400686'
    AND ise.ALLOCATIONCODE = '000000939486'
    -- AND (ise.QUALITYREASONCODE <> 'FOC' OR ise.QUALITYREASONCODE IS NULL)
GROUP BY 
    inpe.PROJECT,ise.ADDRESSEE,ise.BRAND_NM,ise.ALLOCATIONCODE
    
    
SELECT
    COUNT(ise.COUNTROLL) AS ROLL,
    SUM(ise.QTY_KG) AS QTY_SJ_KG,
    SUM(ise.QTY_YARDMETER) AS QTY_SJ_YARD,
    inpe.PROJECT,
    ise.ADDRESSEE,
    ise.BRAND_NM,
    ise.ALLOCATIONCODE
FROM
    ITXVIEW_SURATJALAN_EXIM2A ise 
LEFT JOIN ITXVIEW_NO_PROJECTS_EXIM inpe ON inpe.PROVISIONALCODE = ise.PROVISIONALCODE 
WHERE 
    ise.PROVISIONALCODE = 'ESP2400686'
    AND ise.ALLOCATIONCODE = '000000939486'
    AND ise.QUALITYREASONCODE = 'FOC' 
GROUP BY 
    inpe.PROJECT,ise.ADDRESSEE,ise.BRAND_NM,ise.ALLOCATIONCODE