CREATE OR REPLACE PROCEDURE DB2ADMIN.SP_REFRESH_ITXTEMP_SCHEDULE_KNT()
LANGUAGE SQL
SPECIFIC DB2ADMIN.SP_REFRESH_ITXTEMP_SCHEDULE_KNT
BEGIN ATOMIC

  -- Hapus data dari tabel utama
  DELETE FROM DB2ADMIN.ITXTEMP_SCHEDULE_KNT;

  -- Masukkan data dari tabel staging
  INSERT INTO DB2ADMIN.ITXTEMP_SCHEDULE_KNT (
    KDMC,
    PRODUCTIONDEMANDCODE,
    STATUSMESIN,
    ESTIMASI_SELESAI,
    SUBCODE01,
    SUBCODE02,
    SUBCODE03, 
    SUBCODE04,
    TGL_START,
    TGLDELIVERY,
    TGLMULAI 
  )
  SELECT 
    KDMC,
    PRODUCTIONDEMANDCODE,
    STATUSMESIN,
    ESTIMASI_SELESAI,
    SUBCODE01,
    SUBCODE02,
    SUBCODE03, 
    SUBCODE04,
    TGL_START,
    TGLDELIVERY,
    TGLMULAI
  FROM DB2ADMIN.ITXTEMP_SCHEDULE_KNT_STAGING;

END;