CREATE OR REPLACE PROCEDURE DB2ADMIN.SP_REFRESH_SCHEDULE_KNT_ALL()
LANGUAGE SQL
SPECIFIC DB2ADMIN.SP_REFRESH_SCHEDULE_KNT_ALL
BEGIN
   ATOMIC
DELETE
FROM    DB2ADMIN.SCHEDULE_KNITING_ALL;


INSERT
   INTO    DB2ADMIN.SCHEDULE_KNITING_ALL (
       LANGGANAN,
       KATEGORI,
       PROJECT,
       ORIGINAL_PDCODE,
       ARTICLE_CODE,
       UKURAN_MESIN,
       TOTAL_QTY,
       MACHINE,
       TOTAL_MACHINE,
       STD_QTY_PERMACHINE,
       CAPACITY_PERDAY,
       QTY_PRODUC_YESTERDAY,
       PERSENTASE_TARGET,
       PRODUCED,
       BELUM_RAJUT,
       PERSENTASE_SETELAH_PROD,
       ESTIMATED_COMPLETED,
       ESTIMATED_DELIVERY,
       DELIVERY_ACTUAL,
       SUBCODE01,
       SUBCODE02,
       SUBCODE03,
       SUBCODE04
   )
SELECT
   LANGGANAN,
   KATEGORI,
   PROJECT,
   ORIGINAL_PDCODE,
   ARTICLE_CODE,
   UKURAN_MESIN,
   TOTAL_QTY,
   MACHINE,
   TOTAL_MACHINE,
   STD_QTY_PERMACHINE,
   CAPACITY_PERDAY,
   QTY_PRODUC_YESTERDAY,
   PERSENTASE_TARGET,
   PRODUCED,
   BELUM_RAJUT,
   PERSENTASE_SETELAH_PROD,
   ESTIMATED_COMPLETED,
   ESTIMATED_DELIVERY,
   DELIVERY_ACTUAL,
   SUBCODE01,
   SUBCODE02,
   SUBCODE03,
   SUBCODE04
FROM    DB2ADMIN.SCHEDULE_KNITING_ALL_STAGING;

END;

