SELECT
	TRIM(p.CODE) AS CODE,
    COALESCE(TRIM(p.RESOURCECODE), 'NO RESOURCE') AS NAMA_MESIN,
    TRIM(p.HALLNOCODE) AS DEPT,
    p.LONGDESCRIPTION,
    p.SEARCHDESCRIPTION 
FROM
	PMBOM p
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p.ABSUNIQUEID 
WHERE 
	a.FIELDNAME = 'StatusMesin' 
	AND a.NAMEENTITYNAME = 'PMBoM' 
	AND VALUEBOOLEAN = 1
	AND p.HALLNOCODE = 'LAB'
ORDER BY 
	p.HALLNOCODE ASC, p.RESOURCECODE ASC
	
	
SELECT * FROM PMBREAKDOWNENTRY WHERE PMBOMCODE = 'BRSBL000000001' 
AND STATUS = '1'
	
	
SELECT
    TRIM(p.CODE) AS CODE,
    TRIM(p.PMBOMCODE) AS PMBOMCODE,
    COALESCE(TRIM(p3.RESOURCECODE), 'NO RESOURCE') AS NO_MESIN,
    TRIM(p.SYMPTOM) AS SYMPTOM,
    TRIM(p2.ASSIGNEDTOUSERID) AS ASSIGNEDTOUSERID,
    TRIM(p2.REMARKS) AS REMARKS,
    p2.STARTDATE,
    p2.ENDDATE,
    CASE
    	WHEN p.STATUS  = 1 THEN 'OPEN'
    	WHEN p.STATUS  = 2 THEN 'IN PROGRESS'
    	WHEN p.STATUS  = 3 THEN 'CLOSED'
    	WHEN p.STATUS  = 4 THEN 'SUSPENDED'
    END AS STATUS,
    p.CREATIONDATETIME 
FROM
    PMBREAKDOWNENTRY p 
LEFT JOIN PMWORKORDER p2 ON p2.PMBREAKDOWNENTRYCODE = p.CODE 
LEFT JOIN PMBOM p3 ON p3.CODE = p.PMBOMCODE
WHERE
    p.PMBOMCODE = 'FINBC000000001'
ORDER BY
	p.CREATIONDATETIME DESC