SELECT 
    p.PRODUCTIONORDERCODE, p.PRODUCTIONDEMANDCODE, p.GROUPSTEPNUMBER, p.OPERATIONCODE, p.LONGDESCRIPTION, p.PROGRESSSTATUS, wc.LONGDESCRIPTION AS DEPT, p.WORKCENTERCODE
FROM PRODUCTIONDEMANDSTEP p
LEFT JOIN WORKCENTER wc ON wc.CODE = p.WORKCENTERCODE
WHERE 
	p.PRODUCTIONORDERCODE = '00035010' AND p.PRODUCTIONDEMANDCODE = 
	(p.PROGRESSSTATUS = '2' OR p.PROGRESSSTATUS = '3') 
	AND p.GROUPSTEPNUMBER = ( SELECT MAX(GROUPSTEPNUMBER) FROM PRODUCTIONDEMANDSTEP WHERE PRODUCTIONORDERCODE = '00035578'  AND (PROGRESSSTATUS = '2' OR PROGRESSSTATUS = '3') )
ORDER BY p.GROUPSTEPNUMBER ASC