WITH KAINAKJ AS (
  SELECT 
    s2.SALESORDERCODE,
    s2.ORDERLINE,
    a3.VALUESTRING
  FROM 
    SALESORDERLINE s2
  LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = s2.ABSUNIQUEID AND a3.FIELDNAME = 'KainAKJ'
  WHERE 
    a3.VALUESTRING IN ('0', '2')
)
SELECT DISTINCT 
  TRIM(p2.PRODUCTIONORDERCODE) AS PRODUCTIONORDERCODE,
  LISTAGG(TRIM(p.CODE), ', ') AS PRODUCTIONDEMAND,
  a.VALUESTRING AS NOMOR_MESIN,
  p.PROGRESSSTATUS,
  a2.VALUESTRING AS ORIGINALPDCODE,
  s.TEMPLATECODE,
  LISTAGG(TRIM(s.CODE), ', ') AS CODE,
  k_akj.VALUESTRING AS KAINAKJ,
  SUM(a3.VALUEDECIMAL) AS BRUTO
FROM 
  PRODUCTIONDEMAND p 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p.ABSUNIQUEID AND a.FIELDNAME = 'DYEMachineNoCode'
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = p.ABSUNIQUEID AND a2.FIELDNAME = 'OriginalPDCode'
LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = p.ABSUNIQUEID AND a3.FIELDNAME = 'OriginalBruto'
LEFT JOIN SALESORDER s ON s.CODE = p.ORIGDLVSALORDLINESALORDERCODE 
LEFT JOIN KAINAKJ k_akj ON k_akj.SALESORDERCODE = s.CODE AND k_akj.ORDERLINE = p.ORIGDLVSALORDERLINEORDERLINE
LEFT JOIN (
        SELECT
            DISTINCT PRODUCTIONDEMANDCODE,
            PRODUCTIONORDERCODE
        FROM
            PRODUCTIONDEMANDSTEP p2 
    ) p2 ON p2.PRODUCTIONDEMANDCODE = p.CODE 
LEFT JOIN PRODUCTIONORDER p3 ON p3.CODE = p2.PRODUCTIONORDERCODE
WHERE 	
  a.VALUESTRING IS NOT NULL
  AND NOT p.PROGRESSSTATUS = '6'
  AND (TRIM(p.CREATIONUSER) = 'yogi.rahmansyah' OR a2.VALUESTRING IS NULL)
  AND s.TEMPLATECODE IN ('DOM', 'EXP', 'SME', 'SAM', 'REP', 'RPE', 'OPN', 'DMB', 'MNB', 'TBG', 'RBG')
  AND p2.PRODUCTIONORDERCODE IS NOT NULL
  AND NOT p3.PROGRESSSTATUS = '6'
GROUP BY 
  p2.PRODUCTIONORDERCODE,
  a.VALUESTRING,
  p.PROGRESSSTATUS,
  a2.VALUESTRING,
  s.TEMPLATECODE,
  k_akj.VALUESTRING
	
	 
SELECT DISTINCT 
    ipkk.PRODUCTIONORDERCODE,
--    ipkk.PRODUCTIONDEMANDCODE,
    CASE
        -- BELUM BAGI KAIN
        WHEN 
            MAX(CASE WHEN OPERATIONCODE = 'BAT1' AND STATUS_OPERATION = 'Entered' THEN 1 ELSE 0 END) = 1
            AND 
            SUM(CASE WHEN OPERATIONCODE IN ('DYE1','DYE2','DYE3','DYE4','DYE5','DYE6') 
                     AND STATUS_OPERATION <> 'Entered' THEN 1 ELSE 0 END) = 0
        THEN 'BELUM BAGI KAIN'
        -- SUDAH BAGI KAIN
        WHEN 
            MAX(CASE WHEN OPERATIONCODE = 'BAT1' AND STATUS_OPERATION IN ('Progress','Closed') THEN 1 ELSE 0 END) = 1
            AND 
            SUM(CASE WHEN OPERATIONCODE IN ('DYE1','DYE2','DYE3','DYE4','DYE5','DYE6') 
                     AND STATUS_OPERATION <> 'Entered' THEN 1 ELSE 0 END) = 0
        THEN 'SUDAH BAGI KAIN'
        -- SELESAI (semuanya closed)
        WHEN 
            MAX(CASE WHEN OPERATIONCODE = 'BAT1' AND STATUS_OPERATION = 'Closed' THEN 1 ELSE 0 END) = 1
            AND 
            SUM(CASE WHEN OPERATIONCODE IN ('DYE1','DYE2','DYE3','DYE4','DYE5','DYE6') 
                     AND STATUS_OPERATION <> 'Closed' THEN 1 ELSE 0 END) = 0
        THEN 'SELESAI'
        -- Kondisi lain dianggap tidak normal
        ELSE 'TIDAK NORMAL'
    END AS STATUS_BAGI_KAIN
FROM 
    ITXVIEW_POSISI_KARTU_KERJA ipkk
WHERE 
    ipkk.PRODUCTIONORDERCODE = '00227075'
--    AND ipkk.PRODUCTIONDEMANDCODE = '00387124'
    AND ipkk.OPERATIONCODE IN ('BAT1','DYE1','DYE2','DYE3','DYE4','DYE5','DYE6')
GROUP BY 
    ipkk.PRODUCTIONORDERCODE,
    ipkk.PRODUCTIONDEMANDCODE;
   
SELECT
*,
    COALESCE(DEPT, OPERATIONCODE) || ' - ' || LONGDESCRIPTION AS STATUS_TERAKHIR
FROM
    ITXVIEW_POSISI_KARTU_KERJA
WHERE
    PRODUCTIONORDERCODE = '00224432'
    AND NOT STATUS_OPERATION = 'Closed'
ORDER BY
    STEPNUMBER ASC
--LIMIT 1
