WITH RAJUT AS (
    SELECT 
        PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE,
		PRODUCTIONDEMAND.SUBCODE01,
		PRODUCTIONDEMAND.SUBCODE02,
		PRODUCTIONDEMAND.SUBCODE03,
		PRODUCTIONDEMAND.SUBCODE04,
        b.LOGICALWAREHOUSECODE,
        SUM(b.BASEPRIMARYQUANTITYUNIT) AS QTY_RAJUT_READY
    FROM(
        SELECT DISTINCT 
            p.ORIGDLVSALORDLINESALORDERCODE,
            p.SUBCODE01,
            p.SUBCODE02,
            p.SUBCODE03,
            p.SUBCODE04
        FROM
            PRODUCTIONDEMAND p 
        WHERE
            p.ITEMTYPEAFICODE = 'KGF'
            ) PRODUCTIONDEMAND
    LEFT JOIN BALANCE b ON b.DECOSUBCODE01 = PRODUCTIONDEMAND.SUBCODE01 
                        AND b.DECOSUBCODE02 = PRODUCTIONDEMAND.SUBCODE02 
                        AND b.DECOSUBCODE03 = PRODUCTIONDEMAND.SUBCODE03 
                        AND b.DECOSUBCODE04 = PRODUCTIONDEMAND.SUBCODE04
                        AND b.PROJECTCODE = PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE 
    AND 
        LOGICALWAREHOUSECODE = 'M021'
    GROUP BY
        PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE,
		PRODUCTIONDEMAND.SUBCODE01,
		PRODUCTIONDEMAND.SUBCODE02,
		PRODUCTIONDEMAND.SUBCODE03,
		PRODUCTIONDEMAND.SUBCODE04,
        b.LOGICALWAREHOUSECODE
),
BOOKING_BLM_READY1 AS (
    SELECT 
        PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE,
		PRODUCTIONDEMAND.SUBCODE01,
		PRODUCTIONDEMAND.SUBCODE02,
		PRODUCTIONDEMAND.SUBCODE03,
		PRODUCTIONDEMAND.SUBCODE04,
        b.LOGICALWAREHOUSECODE,
        SUM(b.BASEPRIMARYQUANTITYUNIT) AS QTY_RAJUT_READY
    FROM(
        SELECT DISTINCT 
            p.ORIGDLVSALORDLINESALORDERCODE,
            p.SUBCODE01,
            p.SUBCODE02,
            p.SUBCODE03,
            p.SUBCODE04
        FROM
            PRODUCTIONDEMAND p 
        WHERE
            p.ITEMTYPEAFICODE = 'KGF'
            ) PRODUCTIONDEMAND
    LEFT JOIN BALANCE b ON b.DECOSUBCODE01 = PRODUCTIONDEMAND.SUBCODE01 
                        AND b.DECOSUBCODE02 = PRODUCTIONDEMAND.SUBCODE02 
                        AND b.DECOSUBCODE03 = PRODUCTIONDEMAND.SUBCODE03 
                        AND b.DECOSUBCODE04 = PRODUCTIONDEMAND.SUBCODE04
                        AND b.PROJECTCODE = PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE 
    AND 
        LOGICALWAREHOUSECODE = 'M021'
    GROUP BY
        PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE,
		PRODUCTIONDEMAND.SUBCODE01,
		PRODUCTIONDEMAND.SUBCODE02,
		PRODUCTIONDEMAND.SUBCODE03,
		PRODUCTIONDEMAND.SUBCODE04,
        b.LOGICALWAREHOUSECODE
)
SELECT DISTINCT
    LISTAGG( DISTINCT TRIM(p.PRODUCTIONDEMANDCODE),',') as DEMAND_KFF,
    (p2.ORIGDLVSALORDERLINEORDERLINE) AS ORDERLINE,
    p2.ORIGDLVSALORDLINESALORDERCODE AS NO_ORDER,
    TRIM(p2.SUBCODE02) || '-' || TRIM(p2.SUBCODE03) AS HANGER,
    i.WARNA,
    p2.ITEMTYPEAFICODE,
    p2.SUBCODE01,
    p2.SUBCODE02,
    p2.SUBCODE03,
    p3.SUBCODE04 AS VARIAN,
    r.ORIGDLVSALORDLINESALORDERCODE AS PROJECTCODE_RAJUT,
    r.QTY_RAJUT_READY,
    r1.ORIGDLVSALORDLINESALORDERCODE AS PROJECTCODE_BOOKING_BLMREADY1,
    r1.QTY_RAJUT_READY AS QTY_BOOKING_BLMREADY1,
    r2.ORIGDLVSALORDLINESALORDERCODE AS PROJECTCODE_BOOKING_BLMREADY2,
    r2.QTY_RAJUT_READY AS QTY_BOOKING_BLMREADY2,
    r3.ORIGDLVSALORDLINESALORDERCODE AS PROJECTCODE_BOOKING_BLMREADY3,
    r3.QTY_RAJUT_READY AS QTY_BOOKING_BLMREADY3,
    r4.ORIGDLVSALORDLINESALORDERCODE AS PROJECTCODE_BOOKING_BLMREADY4,
    r4.QTY_RAJUT_READY AS QTY_BOOKING_BLMREADY4,
    r5.ORIGDLVSALORDLINESALORDERCODE AS PROJECTCODE_BOOKING_BLMREADY5,
    r5.QTY_RAJUT_READY AS QTY_BOOKING_BLMREADY5,
    r6.ORIGDLVSALORDLINESALORDERCODE AS PROJECTCODE_BOOKING_BLMREADY6,
    r6.QTY_RAJUT_READY AS QTY_BOOKING_BLMREADY6,
    r6.ORIGDLVSALORDLINESALORDERCODE AS PROJECTCODE_BOOKING_BLMREADY7,
    r6.QTY_RAJUT_READY AS QTY_BOOKING_BLMREADY7,
    ibn.ONLY_PROJECTCODE AS PROJECTCODE_READY1,
    a2.VALUESTRING AS ADDITIONALDATA1,
    a3.VALUESTRING AS ADDITIONALDATA2,
    a4.VALUESTRING AS ADDITIONALDATA3,
    a5.VALUESTRING AS ADDITIONALDATA4,
    a6.VALUESTRING AS ADDITIONALDATA5,
    a7.VALUESTRING AS ADDITIONALDATA6
FROM
    PRODUCTIONDEMANDSTEP p 
LEFT JOIN PRODUCTIONDEMAND p2 ON p2.CODE = p.PRODUCTIONDEMANDCODE 
LEFT JOIN SALESORDER s2 ON s2.CODE = p2.ORIGDLVSALORDLINESALORDERCODE 
LEFT JOIN SALESORDERLINE s3 ON s3.SALESORDERCODE = p2.ORIGDLVSALORDLINESALORDERCODE 
						   AND s3.ORDERLINE = p2.ORIGDLVSALORDERLINEORDERLINE 
LEFT JOIN PRODUCTIONRESERVATION p3 ON p3.ITEMTYPEAFICODE = 'KGF' AND p3.ORDERCODE = p2.CODE 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p2.ABSUNIQUEID AND a.FIELDNAME = 'OriginalPDCode'
LEFT JOIN ADSTORAGE a2 ON a2.UNIQUEID = p2.ABSUNIQUEID AND a2.FIELDNAME = 'ProAllow'
LEFT JOIN ADSTORAGE a3 ON a3.UNIQUEID = p2.ABSUNIQUEID AND a3.FIELDNAME = 'ProAllow2'
LEFT JOIN ADSTORAGE a4 ON a4.UNIQUEID = p2.ABSUNIQUEID AND a4.FIELDNAME = 'ProAllow3'
LEFT JOIN ADSTORAGE a5 ON a5.UNIQUEID = p2.ABSUNIQUEID AND a5.FIELDNAME = 'ProAllow4'
LEFT JOIN ADSTORAGE a6 ON a6.UNIQUEID = p2.ABSUNIQUEID AND a6.FIELDNAME = 'ProAllow5'
LEFT JOIN ADSTORAGE a7 ON a7.UNIQUEID = p2.ABSUNIQUEID AND a7.FIELDNAME = 'ProAllow7'
LEFT JOIN ITXVIEWCOLOR i ON i.ITEMTYPECODE = p2.ITEMTYPEAFICODE 
                        AND i.SUBCODE01 = p2.SUBCODE01 
                        AND i.SUBCODE02 = p2.SUBCODE02 
                        AND i.SUBCODE03 = p2.SUBCODE03 
                        AND i.SUBCODE04 = p2.SUBCODE04 
                        AND i.SUBCODE05 = p2.SUBCODE05 
                        AND i.SUBCODE06 = p2.SUBCODE06 
                        AND i.SUBCODE07 = p2.SUBCODE07 
                        AND i.SUBCODE08 = p2.SUBCODE08 
                        AND i.SUBCODE09 = p2.SUBCODE09 
                        AND i.SUBCODE10 = p2.SUBCODE10
LEFT JOIN RAJUT r ON r.ORIGDLVSALORDLINESALORDERCODE = p2.ORIGDLVSALORDLINESALORDERCODE 
                AND r.SUBCODE01 = p3.SUBCODE01
                AND r.SUBCODE02 = p3.SUBCODE02
                AND r.SUBCODE03 = p3.SUBCODE03
                AND r.SUBCODE04 = p3.SUBCODE04
LEFT JOIN BOOKING_BLM_READY1 r1 ON r1.ORIGDLVSALORDLINESALORDERCODE = a2.VALUESTRING 
                AND r1.SUBCODE01 = p3.SUBCODE01
                AND r1.SUBCODE02 = p3.SUBCODE02
                AND r1.SUBCODE03 = p3.SUBCODE03
                AND r1.SUBCODE04 = p3.SUBCODE04
LEFT JOIN BOOKING_BLM_READY1 r2 ON r2.ORIGDLVSALORDLINESALORDERCODE = a3.VALUESTRING 
                AND r2.SUBCODE01 = p3.SUBCODE01
                AND r2.SUBCODE02 = p3.SUBCODE02
                AND r2.SUBCODE03 = p3.SUBCODE03
                AND r2.SUBCODE04 = p3.SUBCODE04
LEFT JOIN BOOKING_BLM_READY1 r3 ON r3.ORIGDLVSALORDLINESALORDERCODE = a4.VALUESTRING 
                AND r3.SUBCODE01 = p3.SUBCODE01
                AND r3.SUBCODE02 = p3.SUBCODE02
                AND r3.SUBCODE03 = p3.SUBCODE03
                AND r3.SUBCODE04 = p3.SUBCODE04
LEFT JOIN BOOKING_BLM_READY1 r4 ON r4.ORIGDLVSALORDLINESALORDERCODE = a5.VALUESTRING 
                AND r4.SUBCODE01 = p3.SUBCODE01
                AND r4.SUBCODE02 = p3.SUBCODE02
                AND r4.SUBCODE03 = p3.SUBCODE03
                AND r4.SUBCODE04 = p3.SUBCODE04
LEFT JOIN BOOKING_BLM_READY1 r5 ON r5.ORIGDLVSALORDLINESALORDERCODE = a6.VALUESTRING 
                AND r5.SUBCODE01 = p3.SUBCODE01
                AND r5.SUBCODE02 = p3.SUBCODE02
                AND r5.SUBCODE03 = p3.SUBCODE03
                AND r5.SUBCODE04 = p3.SUBCODE04
LEFT JOIN BOOKING_BLM_READY1 r6 ON r6.ORIGDLVSALORDLINESALORDERCODE = a7.VALUESTRING 
                AND r6.SUBCODE01 = p3.SUBCODE01
                AND r6.SUBCODE02 = p3.SUBCODE02
                AND r6.SUBCODE03 = p3.SUBCODE03
                AND r6.SUBCODE04 = p3.SUBCODE04
LEFT JOIN ITXVIEW_BOOKING_NEW ibn ON ibn.SALESORDERCODE = p2.ORIGDLVSALORDLINESALORDERCODE AND ibn.ORDERLINE = p2.ORIGDLVSALORDERLINEORDERLINE 
WHERE
    p.OPERATIONCODE = 'BAT1'
    AND p.PROGRESSSTATUS IN ('0', '1')
    AND a.VALUESTRING IS NULL
    AND CAST(p2.CREATIONDATETIME AS DATE) > '2024-01-01' 
    AND p2.ITEMTYPEAFICODE = 'KFF'
    AND p2.PROGRESSSTATUS = '2'
    AND NOT p2.ORIGDLVSALORDLINESALORDERCODE IS NULL
    AND p3.ITEMTYPEAFICODE = 'KGF'
    AND s2.TEMPLATECODE IN ('CWD', 'CWE', 'DOM', 'EXP', 'REP', 'RFD', 'RFE', 'RPE', 'SAM', 'SME', 'OPN')
    AND s3.LINESTATUS = '1'
--    AND p2.ORIGDLVSALORDLINESALORDERCODE = 'EXP2500175'
GROUP BY
	p2.ORIGDLVSALORDERLINEORDERLINE,
    p2.ORIGDLVSALORDLINESALORDERCODE,
    p2.ITEMTYPEAFICODE,
    p2.SUBCODE01,
    p2.SUBCODE02,
    p2.SUBCODE03,
    i.WARNA,
    p3.SUBCODE04,
    r.ORIGDLVSALORDLINESALORDERCODE,
    r.QTY_RAJUT_READY,
    r1.ORIGDLVSALORDLINESALORDERCODE,
    r1.QTY_RAJUT_READY,
    r2.ORIGDLVSALORDLINESALORDERCODE,
    r2.QTY_RAJUT_READY,
    r3.ORIGDLVSALORDLINESALORDERCODE,
    r3.QTY_RAJUT_READY,
    r4.ORIGDLVSALORDLINESALORDERCODE,
    r4.QTY_RAJUT_READY,
    r5.ORIGDLVSALORDLINESALORDERCODE,
    r5.QTY_RAJUT_READY,
    r6.ORIGDLVSALORDLINESALORDERCODE,
    r6.QTY_RAJUT_READY,
    ibn.ONLY_PROJECTCODE,
    ibn.QTY_ALOKASI_BRUTO,
    a2.VALUESTRING,
    a3.VALUESTRING,
    a4.VALUESTRING,
    a5.VALUESTRING,
    a6.VALUESTRING,
    a7.VALUESTRING
   
    
SELECT 
	PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE,
	PRODUCTIONDEMAND.SUBCODE01,
	PRODUCTIONDEMAND.SUBCODE02,
	PRODUCTIONDEMAND.SUBCODE03,
	PRODUCTIONDEMAND.SUBCODE04,
    SUM(b.BASEPRIMARYQUANTITYUNIT) AS QTY_RAJUT_READY
FROM(
    SELECT DISTINCT 
        p.ORIGDLVSALORDLINESALORDERCODE,
        p.SUBCODE01,
        p.SUBCODE02,
        p.SUBCODE03,
        p.SUBCODE04
    FROM
        PRODUCTIONDEMAND p 
    WHERE
        p.ITEMTYPEAFICODE = 'KGF'
        ) PRODUCTIONDEMAND
LEFT JOIN BALANCE b ON b.DECOSUBCODE01 = PRODUCTIONDEMAND.SUBCODE01 
                    AND b.DECOSUBCODE02 = PRODUCTIONDEMAND.SUBCODE02 
                    AND b.DECOSUBCODE03 = PRODUCTIONDEMAND.SUBCODE03 
                    AND b.DECOSUBCODE04 = PRODUCTIONDEMAND.SUBCODE04
                    AND b.PROJECTCODE = PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE 
					AND b.LOGICALWAREHOUSECODE = 'M021'
WHERE
    PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE  = 'SME2500244'
	AND PRODUCTIONDEMAND.SUBCODE01  = 'T'
	AND PRODUCTIONDEMAND.SUBCODE02 = 'DKF'
	AND PRODUCTIONDEMAND.SUBCODE03 = '25017'
	AND PRODUCTIONDEMAND.SUBCODE04 = 'D01'
GROUP BY
    PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE,
	PRODUCTIONDEMAND.SUBCODE01,
	PRODUCTIONDEMAND.SUBCODE02,
	PRODUCTIONDEMAND.SUBCODE03,
	PRODUCTIONDEMAND.SUBCODE04
    
SELECT 
    b.PROJECTCODE,
    b.DECOSUBCODE01,
    b.DECOSUBCODE02,
    b.DECOSUBCODE03,
    b.DECOSUBCODE04,
    b.LOGICALWAREHOUSECODE,
    SUM(b.BASEPRIMARYQUANTITYUNIT) AS QTY_RAJUT_READY
FROM(
    SELECT DISTINCT 
        p.ORIGDLVSALORDLINESALORDERCODE,
        p.SUBCODE01,
        p.SUBCODE02,
        p.SUBCODE03,
        p.SUBCODE04
    FROM
        PRODUCTIONDEMAND p 
    WHERE
        p.ITEMTYPEAFICODE = 'KGF'
        ) PRODUCTIONDEMAND
LEFT JOIN BALANCE b ON b.DECOSUBCODE01 = PRODUCTIONDEMAND.SUBCODE01 
                    AND b.DECOSUBCODE02 = PRODUCTIONDEMAND.SUBCODE02 
                    AND b.DECOSUBCODE03 = PRODUCTIONDEMAND.SUBCODE03 
                    AND b.DECOSUBCODE04 = PRODUCTIONDEMAND.SUBCODE04
                    AND b.PROJECTCODE = PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE 
					AND b.LOGICALWAREHOUSECODE = 'M021'
WHERE
	b.PROJECTCODE = 'EXP2500175'
    AND b.DECOSUBCODE01 = 'TCX'
    AND b.DECOSUBCODE02 = 'DKF'
    AND b.DECOSUBCODE03 = '19106'
    AND b.DECOSUBCODE04 = 'D03'
GROUP BY
    b.PROJECTCODE,
    b.DECOSUBCODE01,
    b.DECOSUBCODE02,
    b.DECOSUBCODE03,
    b.DECOSUBCODE04,
    b.LOGICALWAREHOUSECODE
    
    
-- DELIVERY GREIGE BON ORDER 1
SELECT
    *
FROM 
	ITXVIEWBONORDER i
WHERE 
    i.SALESORDERCODE = 'EXP2500175'
    AND 
--    AND i.ORDERLINE = '40'
    
-- DELIVERY GREIGE BON ORDER 2 3  
SELECT 
    a7.VALUEDATE AS TGLRENCANA,
    a8.VALUEDATE AS TGLPOGREIGE
FROM(
    SELECT DISTINCT 
        p.ORIGDLVSALORDLINESALORDERCODE,
        p.SUBCODE01,
        p.SUBCODE02,
        p.SUBCODE03,
        p.SUBCODE04,
        p.ABSUNIQUEID
    FROM
        PRODUCTIONDEMAND p 
    WHERE
        p.ITEMTYPEAFICODE = 'KGF'
        ) PRODUCTIONDEMAND
LEFT JOIN BALANCE b ON b.DECOSUBCODE01 = PRODUCTIONDEMAND.SUBCODE01 
                    AND b.DECOSUBCODE02 = PRODUCTIONDEMAND.SUBCODE02 
                    AND b.DECOSUBCODE03 = PRODUCTIONDEMAND.SUBCODE03 
                    AND b.DECOSUBCODE04 = PRODUCTIONDEMAND.SUBCODE04
                    AND b.PROJECTCODE = PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE
LEFT JOIN ADSTORAGE a7 ON a7.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a7.FIELDNAME = 'RMPReqDate'
LEFT JOIN ADSTORAGE a8 ON a8.UNIQUEID = PRODUCTIONDEMAND.ABSUNIQUEID AND a8.FIELDNAME = 'RMPGreigeReqDateTo'
AND 
    LOGICALWAREHOUSECODE = 'M021'
WHERE
	b.PROJECTCODE = 'DOM2500360'
	AND b.DECOSUBCODE01 = 'CX'
	AND b.DECOSUBCODE02 = 'SJS'
	AND b.DECOSUBCODE03 = '13068'
	AND b.DECOSUBCODE04 = 'H05'
	AND b.LOGICALWAREHOUSECODE = 'M021'
GROUP BY
    a7.VALUEDATE,
    a8.VALUEDATE 
 
   
-- DELIVERY KAIN JADI (AKTUAL)
SELECT DISTINCT 
	CASE 
        WHEN s2.CONFIRMEDDELIVERYDATE IS NULL THEN s.CONFIRMEDDUEDATE
        ELSE s2.CONFIRMEDDELIVERYDATE 
    END AS ACTUAL_DELIVERY
FROM
	ITXVIEWBONORDER i
LEFT JOIN SALESORDERDELIVERY s2 ON s2.SALESORDERLINESALESORDERCODE = i.SALESORDERCODE AND s2.SALESORDERLINEORDERLINE = i.ORDERLINE 
LEFT JOIN SALESORDER s ON s.CODE = s2.SALESORDERLINESALESORDERCODE
WHERE 
	i.SALESORDERCODE = 'DOM2500360'
	AND i.ORDERLINE = '40'
GROUP BY
	i.SUBCODE02,
	i.SUBCODE03,
	s2.CONFIRMEDDELIVERYDATE,
	s.CONFIRMEDDUEDATE
	
-- GRIEGE NEEDS
SELECT 
    SUM(USERPRIMARYQUANTITY) AS QTY_BRUTO,
    MAX(USERPRIMARYUOMCODE) AS UOMCODE,
    MAX(i.ORIGDLVSALORDLINESALORDERCODE),
    MAX(i.ORIGDLVSALORDERLINEORDERLINE) 
FROM 
	ITXVIEWKGBRUTOBONORDER2 i 
WHERE 
    i.ORIGDLVSALORDLINESALORDERCODE ='DOM2500360'
    AND i.ORIGDLVSALORDERLINEORDERLINE= '40'
    GROUP BY
    i.ITEMTYPE_DEMAND,
    i.SUBCODE01,
    i.SUBCODE02,
    i.SUBCODE03,
    i.ORIGDLVSALORDERLINEORDERLINE,
    i.ORIGDLVSALORDLINESALORDERCODE