-- DAFTAR BARANG
SELECT
	TRIM(s.DECOSUBCODE01) || '-' ||
    TRIM(s.DECOSUBCODE02) || '-' ||
    TRIM(s.DECOSUBCODE03) || '-' ||
    TRIM(s.DECOSUBCODE04) || '-' ||
    TRIM(s.DECOSUBCODE05) || '-' ||
    TRIM(s.DECOSUBCODE06) AS KODE_BARANG,
    p.LONGDESCRIPTION AS NAMA_BARANG,   
	s.USERPRIMARYUOMCODE AS UNIT
FROM
    STOCKTRANSACTION s
LEFT JOIN PRODUCT p ON p.ITEMTYPECODE = s.ITEMTYPECODE 
                    AND p.SUBCODE01 = s.DECOSUBCODE01 
                    AND p.SUBCODE02 = s.DECOSUBCODE02 
                    AND p.SUBCODE03 = s.DECOSUBCODE03 
                    AND p.SUBCODE04 = s.DECOSUBCODE04 
                    AND p.SUBCODE05 = s.DECOSUBCODE05 
                    AND p.SUBCODE06 = s.DECOSUBCODE06
RIGHT JOIN BALANCE b ON b.ITEMTYPECODE = p.ITEMTYPECODE
					AND b.DECOSUBCODE01 = p.SUBCODE01 
					AND b.DECOSUBCODE02 = p.SUBCODE02 
					AND b.DECOSUBCODE03 = p.SUBCODE03 
					AND b.DECOSUBCODE04 = p.SUBCODE04 
					AND b.DECOSUBCODE05 = p.SUBCODE05 
					AND b.DECOSUBCODE06 = p.SUBCODE06
WHERE
    s.ITEMTYPECODE ='SPR'
    AND s.DECOSUBCODE01 = 'DIT' 
--    AND TRIM(s.DECOSUBCODE01) || '-' ||
--        TRIM(s.DECOSUBCODE02) || '-' ||
--        TRIM(s.DECOSUBCODE03) || '-' ||
--        TRIM(s.DECOSUBCODE04) || '-' ||
--        TRIM(s.DECOSUBCODE05) || '-' ||
--        TRIM(s.DECOSUBCODE06)  = 'DIT-NETWK-LOC-SWITCH-UNIFI-SW24'
    AND (s.TEMPLATECODE = '101' OR s.TEMPLATECODE = 'OPN' OR s.TEMPLATECODE = 'QCT' OR s.TEMPLATECODE = '201' OR s.TEMPLATECODE = '098')
    AND (s.TRANSACTIONDATE) BETWEEN '2024-01-10' AND '2024-01-13'
GROUP BY
	s.DECOSUBCODE01,
    s.DECOSUBCODE02,
    s.DECOSUBCODE03,
    s.DECOSUBCODE04,
    s.DECOSUBCODE05,
    s.DECOSUBCODE06,
    p.LONGDESCRIPTION,
    s.USERPRIMARYUOMCODE
  
-- STOK AWAL
SELECT 
	floor(SUM(s.USERPRIMARYQUANTITY)) AS STOK_AWAL
FROM 
	STOCKTRANSACTION s
WHERE
	s.ITEMTYPECODE ='SPR'
    AND s.DECOSUBCODE01 = 'DIT' 
    AND TRIM(s.DECOSUBCODE01) || '-' ||
        TRIM(s.DECOSUBCODE02) || '-' ||
        TRIM(s.DECOSUBCODE03) || '-' ||
        TRIM(s.DECOSUBCODE04) || '-' ||
        TRIM(s.DECOSUBCODE05) || '-' ||
        TRIM(s.DECOSUBCODE06)  = 'DIT-NETWK-LOC-SWITCH-UNIFI-SW24'
    AND (s.TEMPLATECODE = '101' OR s.TEMPLATECODE = 'OPN' OR s.TEMPLATECODE = 'QCT')
--    AND (s.TRANSACTIONDATE) BETWEEN '2024-01-10' AND '2024-01-12'
    AND (s.TRANSACTIONDATE) = '2024-01-10' 
    
-- STOK MASUK
SELECT 
	floor(SUM(s.USERPRIMARYQUANTITY)) AS MASUK
FROM 
	STOCKTRANSACTION s
WHERE
	s.ITEMTYPECODE ='SPR'
    AND s.DECOSUBCODE01 = 'DIT' 
    AND TRIM(s.DECOSUBCODE01) || '-' ||
        TRIM(s.DECOSUBCODE02) || '-' ||
        TRIM(s.DECOSUBCODE03) || '-' ||
        TRIM(s.DECOSUBCODE04) || '-' ||
        TRIM(s.DECOSUBCODE05) || '-' ||
        TRIM(s.DECOSUBCODE06)  = 'DIT-NETWK-LOC-SWITCH-UNIFI-SW24'
    AND (s.TEMPLATECODE = '101' OR s.TEMPLATECODE = 'OPN' OR s.TEMPLATECODE = 'QCT')
    AND (s.TRANSACTIONDATE) > '2024-01-11' AND (s.TRANSACTIONDATE) <= '2024-01-13'
    
-- STOK KELUAR
SELECT 
	floor(SUM(s.USERPRIMARYQUANTITY)) AS KELUAR
FROM 
	STOCKTRANSACTION s
WHERE
	s.ITEMTYPECODE ='SPR'
    AND s.DECOSUBCODE01 = 'DIT' 
    AND TRIM(s.DECOSUBCODE01) || '-' ||
        TRIM(s.DECOSUBCODE02) || '-' ||
        TRIM(s.DECOSUBCODE03) || '-' ||
        TRIM(s.DECOSUBCODE04) || '-' ||
        TRIM(s.DECOSUBCODE05) || '-' ||
        TRIM(s.DECOSUBCODE06)  = 'DIT-NETWK-LOC-SWITCH-UNIFI-SERVERSW48'
    AND (s.TEMPLATECODE = '201' OR s.TEMPLATECODE = '098')
    AND (s.TRANSACTIONDATE) >= '2024-01-10' AND (s.TRANSACTIONDATE) <= '2024-01-13'