-- MASTER BARANG DIT YANG ADA DIBALANCE
SELECT
    TRIM(SUBCODE01) || '-' ||
    TRIM(SUBCODE02) || '-' ||
    TRIM(SUBCODE03) || '-' ||
    TRIM(SUBCODE04) || '-' ||
    TRIM(SUBCODE05) || '-' ||
    TRIM(SUBCODE06) AS KODE_BARANG,
    LONGDESCRIPTION,
    SHORTDESCRIPTION,
    SEARCHDESCRIPTION 
FROM
    PRODUCT p
RIGHT JOIN BALANCE b ON b.ITEMTYPECODE = p.ITEMTYPECODE
					AND b.DECOSUBCODE01 = p.SUBCODE01 
					AND b.DECOSUBCODE02 = p.SUBCODE02 
					AND b.DECOSUBCODE03 = p.SUBCODE03 
					AND b.DECOSUBCODE04 = p.SUBCODE04 
					AND b.DECOSUBCODE05 = p.SUBCODE05 
					AND b.DECOSUBCODE06 = p.SUBCODE06
WHERE
    p.ITEMTYPECODE = 'SPR'
    AND p.SUBCODE01 = 'DIT'

-- TRANSAKSI HISTORY
SELECT
	s.TRANSACTIONNUMBER,
	s.TRANSACTIONDATE AS TGL,
	s.TRANSACTIONTIME AS WAKTU,
	p.LONGDESCRIPTION AS NAMA_BARANG,
	floor(SUM(s.USERPRIMARYQUANTITY)) || ' ' || s.USERPRIMARYUOMCODE AS QTY,
	s.USERPRIMARYUOMCODE AS SATUAN,
	CASE
		WHEN s.TEMPLATECODE = '101' THEN 'MASUK 101'
		WHEN s.TEMPLATECODE = 'OPN' THEN 'MASUK OPN'
		WHEN s.TEMPLATECODE = 'QCT' THEN 'MASUK QCT'
		WHEN s.TEMPLATECODE = '201' THEN 'KELUAR 201'
		WHEN s.TEMPLATECODE = '098' THEN 'KELUAR 098'
	END AS TRANSAKSI,	
	CASE
		WHEN s.ORDERCODE IS NULL THEN s.TEMPLATECODE
		ELSE s.TEMPLATECODE || ' - ' || s.ORDERCODE
	END	AS ORDERCODE_TEMPLATE
FROM
	STOCKTRANSACTION s
LEFT JOIN PRODUCT p ON p.ITEMTYPECODE = s.ITEMTYPECODE 
					AND p.SUBCODE01 = s.DECOSUBCODE01 
					AND p.SUBCODE02 = s.DECOSUBCODE02 
					AND p.SUBCODE03 = s.DECOSUBCODE03 
					AND p.SUBCODE04 = s.DECOSUBCODE04 
					AND p.SUBCODE05 = s.DECOSUBCODE05 
					AND p.SUBCODE06 = s.DECOSUBCODE06
WHERE
	s.ITEMTYPECODE ='SPR'
	AND s.DECOSUBCODE01 = 'DIT' 
	AND TRIM(s.DECOSUBCODE01) || '-' ||
		TRIM(s.DECOSUBCODE02) || '-' ||
		TRIM(s.DECOSUBCODE03) || '-' ||
		TRIM(s.DECOSUBCODE04) || '-' ||
		TRIM(s.DECOSUBCODE05) || '-' ||
		TRIM(s.DECOSUBCODE06)  = 'DIT-NETWK-LOC-SWITCH-UNIFI-SW24'
	AND (s.TEMPLATECODE = '101' OR s.TEMPLATECODE = 'OPN' OR s.TEMPLATECODE = 'QCT' OR s.TEMPLATECODE = '201' OR s.TEMPLATECODE = '098')
	AND (s.TRANSACTIONDATE) BETWEEN '2024-01-10' AND '2024-01-11'
GROUP BY
	s.TRANSACTIONNUMBER,
	s.TRANSACTIONDATE,
	s.TRANSACTIONTIME,
	p.LONGDESCRIPTION,
	s.USERPRIMARYUOMCODE,
	s.TEMPLATECODE,
	s.ORDERCODE
ORDER BY
	s.TRANSACTIONNUMBER,
	s.TRANSACTIONDATE,
	s.TRANSACTIONTIME 
ASC

-- MINIMUM STOCK
SELECT SAFETYSTOCK  FROM ITEMWAREHOUSELINK WHERE ITEMTYPECODE = 'SPR' 
                                AND SUBCODE01 = 'DIT' 
                                AND SUBCODE02 = 'NETWK' 
                                AND SUBCODE03 = 'LOC' 
                                AND SUBCODE04 = 'RJ45'
                                AND SUBCODE05 = '-' 
                                AND SUBCODE06 = 'PLASTIC'
                                AND LOGICALWAREHOUSECODE = 'M231'
