SELECT * FROM SYSCAT.INDEXES WHERE tabname = 'STOCKTRANSACTION'

CREATE INDEX CREATIONDATETIME ON DB2ADMIN.SALESORDER(CREATIONDATETIME);



1. PLANTINVOICE.BUYERIFOTCCUSTOMERSUPPLIERCODE
2. PLANTINVOICE.TERMSOFPAYMENTCODE
3. PLANTINVOICE.CONTRACTNOCODE
4. PLANTINVOICE.CODE
5. SALESORDER.PAYMENTCUSTOMERUNIQUEID
6. SALESORDER.PAYMENTCUSTOMERCODE
7. SALESORDER.CREATIONUSER
8. SALESORDERDELIVERY.DELIVERYDATE
9. PRODUCTIONDEMAND.ORIGDLVSALORDLINESALORDERCODE
10. PRODUCTIONDEMAND.ORIGDLVSALORDERLINEORDERLINE
11. PRODUCTIONDEMAND.SUBCODE01
12. PRODUCTIONDEMAND.SUBCODE02
13. PRODUCTIONDEMAND.SUBCODE03
14. PRODUCTIONDEMAND.SUBCODE04
15. PRODUCTIONDEMAND.SUBCODE05
16. PRODUCTIONDEMAND.SUBCODE06
17. PRODUCTIONDEMAND.SUBCODE07
18. PRODUCTIONDEMAND.SUBCODE08
19. PRODUCTIONDEMAND.SUBCODE09
20. PRODUCTIONDEMAND.SUBCODE10
21. ORDERITEMORDERPARTNERLINK.INACTIVE
22. PRODUCTIONRESERVATION.RELATEDCMPBILLOFMATSUBCODE02 
23. PRODUCTIONRESERVATION.RELATEDCMPBILLOFMATSUBCODE03 
24. PRODUCTIONRESERVATION.RELATEDCMPBILLOFMATSUBCODE04
25.
26.