SELECT
	*
FROM
	RECIPE r
WHERE 
	SUBCODE01 = '22078/240583D/D' AND SUFFIXCODE = '25012127D'
	
SELECT
	TRIM(r.GROUPNUMBER) AS GROUPNUMBER,
	TRIM(r.GROUPTYPECODE) AS GROUPTYPECODE,
	TRIM(r.SEQUENCE) AS SEQUENCE,
	TRIM(r.SUBSEQUENCE) AS SUBSEQUENCE,
	TRIM(r.ITEMTYPEAFICODE) AS ITEMTYPEAFICODE,
	TRIM(r.SUBCODE01) AS SUBCODE01,
	TRIM(r.SUBCODE02) AS SUBCODE02,
	TRIM(r.SUBCODE03) AS SUBCODE03,
	TRIM(r.SUFFIXCODE) AS SUFFIXCODE,
	TRIM(r.COMMENTLINE) AS COMMENTLINE,
	COALESCE(TRIM(p.LONGDESCRIPTION), TRIM(r2.SHORTDESCRIPTION)) AS LONGDESCRIPTION,
	TRIM(r.CONSUMPTIONTYPE) AS CONSUMPTIONTYPE,
	TRIM(r.COMPONENTUOMCODE) AS COMPONENTUOMCODE,
	TRIM(r.CONSUMPTION) AS CONSUMPTION
FROM
	RECIPECOMPONENT r
LEFT JOIN PRODUCT p ON p.ITEMTYPECODE = r.ITEMTYPEAFICODE 
					AND p.SUBCODE01 = r.SUBCODE01 
					AND p.SUBCODE02 = r.SUBCODE02 
					AND p.SUBCODE03 = r.SUBCODE03
LEFT JOIN RECIPE r2 ON r2.ITEMTYPECODE = r.ITEMTYPEAFICODE 
					AND r2.SUBCODE01 = r.SUBCODE01 
					AND r2.SUFFIXCODE = r.SUFFIXCODE 
WHERE 
	r.RECIPENUMBERID = '176917'
	
SELECT
	*
FROM
	RECIPECOMPONENT r2
LEFT JOIN PRODUCT p ON p.ITEMTYPECODE = r2.ITEMTYPEAFICODE 
					AND p.SUBCODE01 = r2.SUBCODE01 
					AND p.SUBCODE02 = r2.SUBCODE02 
					AND p.SUBCODE03 = r2.SUBCODE03
WHERE
	r2.RECIPEITEMTYPECODE = 'RFF'
	AND r2.RECIPESUBCODE01 = 'SC3301'
	AND r2.RECIPESUFFIXCODE = '001'
