SELECT 
  INSERT_TIMESTAMP,
  SUBSTR(STMT_TEXT, 1, 4000) AS STMT_TEXT,
--  TOTAL_ACT_TIME AS TOTAL_EXECUTION_TIME_MS,
--  DECIMAL(TOTAL_ACT_TIME / 1000.0, 10, 3) AS TOTAL_EXECUTION_SEC,
  RIGHT('0' || CAST(INT(TOTAL_ACT_TIME / (1000*60*60)) AS VARCHAR(2)), 2) || ':' ||
  RIGHT('0' || CAST(INT(MOD(TOTAL_ACT_TIME / (1000*60), 60)) AS VARCHAR(2)), 2) || ':' ||
  RIGHT('0' || CAST(INT(MOD(TOTAL_ACT_TIME / 1000, 60)) AS VARCHAR(2)), 2) AS TOTAL_EXECUTION_TIME_HMS,
  TOTAL_CPU_TIME,
  NUM_EXECUTIONS,
  STMT_TYPE_ID,
  (DECIMAL(TOTAL_CPU_TIME / TOTAL_ACT_TIME, 10, 3)) AS CPU_RATIO,
  DECIMAL(TOTAL_ACT_TIME / 1000000.0, 18, 3) AS TOTAL_SEC,
  DECIMAL((TOTAL_ACT_TIME / NUM_EXECUTIONS) / 1000000.0, 18, 3) AS AVG_SEC_PER_EXEC
FROM TABLE(MON_GET_PKG_CACHE_STMT(NULL, NULL, NULL, -2)) AS S
--WHERE STMT_TEXT LIKE '%ITXTEMP_SCHEDULE_KNT_STAGING%'
ORDER BY TOTAL_ACT_TIME DESC
FETCH FIRST 1000 ROWS ONLY;


SELECT 
    APPLICATION_NAME,
    STMT_TEXT,
    ACTIVITY_STATE,
    DECIMAL(TOTAL_ACT_TIME/1000000.0,10,2) AS TOTAL_SEC,
    DECIMAL(LOCK_WAIT_TIME/1000000.0,10,2) AS LOCK_WAIT_SEC
FROM TABLE(MON_GET_ACTIVITY(NULL, -2)) AS A
WHERE ACTIVITY_STATE <> 'IDLE'
ORDER BY TOTAL_ACT_TIME DESC;


-- mencari query yg paling banyak hit nya, lebih dari 50. database sqlsrv nya di offlinekan dulu
SELECT APPLICATION_NAME, COUNT(*) AS TOTAL_HIT
FROM TABLE(MON_GET_CONNECTION(NULL,-2))
GROUP BY APPLICATION_NAME
--WHERE APPLICATION_NAME LIKE '%GEROBAK%'
