MERGE INTO PURCHASEORDER p3
USING (
	SELECT 
		p.CODE AS PURCHASEORDERCODE,
		SUM(p2.PRICE) - SUM(FLOOR(a.VALUEDECIMAL * 0.02)) AS TOTAL
	FROM 
		PURCHASEORDER p
	LEFT JOIN PURCHASEORDERLINE p2 ON p2.PURCHASEORDERCODE = p.CODE 
	LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p2.ABSUNIQUEID AND a.FIELDNAME = 'FakturPajak'
	WHERE 
		p.TEMPLATECODE = 'BYL'
	  	AND p.ORDERCATEGORYCODE IN ('IAO', 'IEO', 'IJO', 'IKA', 'IKJ', 'IKP', 'IKX', 'IPO', 'IRO')
	  	AND p.CODE = 'BYL2500032'
	GROUP BY 
		p.CODE
) AS t
ON p3.CODE = t.PURCHASEORDERCODE
WHEN MATCHED THEN
	UPDATE SET p3.ONORDERTOTALAMOUNT = t.TOTAL;
 