-- RESERVATION LINK GROUP
SELECT
	q2.LINE,
	q.PRODUCTIONORDERCODE,
	LISTAGG('''' || a.valueint || '''', ',') AS STEPNUMBER,
	LISTAGG(TRIM(q.OPERATIONCODE), ', ') AS OPERATIONCODE
FROM
	QUALITYDOCUMENT q
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = q.ABSUNIQUEID AND a.FIELDNAME = 'GroupStepNumber'
LEFT JOIN QUALITYDOCLINE q2 ON q2.QUALITYDOCUMENTHEADERLINE = q.HEADERLINE
							AND (TRIM(q2.CHARACTERISTICCODE) = 'WHITENESS'
								OR TRIM(q2.CHARACTERISTICCODE) = 'YELLOWNESS'
								OR TRIM(q2.CHARACTERISTICCODE) = 'TINT')
							AND NOT q2.VALUEQUANTITY = 0
WHERE
	q.PRODUCTIONORDERCODE = '00129303'
	AND q2.LINE = 11
GROUP BY
	q2.LINE,
	q.PRODUCTIONORDERCODE
	
	
-- WHITENESS, TINT, YELLOWNESS
SELECT
	q2.LINE,
  	q.PRODUCTIONORDERCODE,
  	LISTAGG(TRIM(q.OPERATIONCODE) || ' = ' || DECIMAL(q2.VALUEQUANTITY, 5,2), ', ') AS YELLOWNESS,
    q2.CHARACTERISTICCODE	
FROM
	QUALITYDOCUMENT q  
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = q.ABSUNIQUEID AND a.FIELDNAME = 'GroupStepNumber'
LEFT JOIN QUALITYDOCLINE q2 ON q2.QUALITYDOCUMENTHEADERLINE = q.HEADERLINE 
                AND (TRIM(q2.CHARACTERISTICCODE) = 'WHITENESS'
				OR TRIM(q2.CHARACTERISTICCODE) = 'YELLOWNESS'
 				OR TRIM(q2.CHARACTERISTICCODE) = 'TINT')
                AND NOT q2.VALUEQUANTITY = 0						
WHERE
	q.PRODUCTIONORDERCODE = '00123175'
	AND (q2.LINE = 11 OR q2.LINE = 12 OR q2.LINE = 13)
 	AND TRIM(q2.CHARACTERISTICCODE) = 'WHITENESS'
GROUP BY
	q2.LINE,
	q.PRODUCTIONORDERCODE,
	q2.CHARACTERISTICCODE  
    
-- LR
SELECT 
  LISTAGG(TRIM(PRODRESERVATIONLINKGROUPCODE) || ' = ' || DECIMAL(LR, 5,2), ', ') AS LR,
  LISTAGG(TRIM(PRODRESERVATIONLINKGROUPCODE) || ' = ' || TRIM(SUBCODE01) || '-' || TRIM(SUFFIXCODE), ', ') AS SUFFIX,
  LISTAGG(TRIM(PRODRESERVATIONLINKGROUPCODE) || ' = ' || TRIM(LONGDESCRIPTION), ', ') AS LONGDESCRIPTION,
  LISTAGG(TRIM(PRODRESERVATIONLINKGROUPCODE) || ' = ' || TRIM(SHORTDESCRIPTION), ', ') AS SHORTDESCRIPTION,
  LISTAGG(TRIM(PRODRESERVATIONLINKGROUPCODE) || ' = ' || TRIM(SEARCHDESCRIPTION), ', ') AS SEARCHDESCRIPTION
FROM (
  SELECT 
    DISTINCT 
    p.PRODRESERVATIONLINKGROUPCODE,
    p.PICKUPQUANTITY AS LR,
    p.SUBCODE01,
    p.SUFFIXCODE,
    r.LONGDESCRIPTION,
    r.SHORTDESCRIPTION,
    r.SEARCHDESCRIPTION
  FROM 
    PRODUCTIONRESERVATION p 
	LEFT JOIN RECIPE r ON r.SUBCODE01 = p.SUBCODE01 AND r.SUFFIXCODE = p.SUFFIXCODE 
	LEFT JOIN VIEWPRODUCTIONDEMANDSTEP v ON v.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE AND v.GROUPSTEPNUMBER = p.GROUPSTEPNUMBER
  WHERE	
    p.PRODUCTIONORDERCODE = '00129303' 
    AND
    CASE 
    	WHEN v.STEPTYPE = 3 THEN p.GROUPSTEPNUMBER  IN ('218')
    	ELSE p.STEPNUMBER  IN ('218')
    END    
    AND p.ITEMNATURE = 9
    AND SUBSTR(p.SUBCODE01, 1,2) = 'SC' 
  GROUP BY
  	v.steptype,
    p.PRODRESERVATIONLINKGROUPCODE,
    p.PICKUPQUANTITY,
    p.SUBCODE01,
    p.SUFFIXCODE,
    r.LONGDESCRIPTION,
    r.SHORTDESCRIPTION,
    r.SEARCHDESCRIPTION)
	
SELECT
--	r.GROUPNUMBER, r."SEQUENCE",
--  TRIM(r.SUBCODE01) || '-' || TRIM(r.SUBCODE02) || '-' || TRIM(r.SUBCODE03) AS DYC,
  CASE
    WHEN p.LONGDESCRIPTION IS NULL THEN r.COMMENTLINE 
    ELSE p.LONGDESCRIPTION
  END AS LONGDESCRIPTION,
  r.CONSUMPTION
FROM
  RECIPECOMPONENT r
LEFT JOIN PRODUCT p ON p.ITEMTYPECODE = r.ITEMTYPEAFICODE 
          AND p.SUBCODE01 = r.SUBCODE01
          AND p.SUBCODE02 = r.SUBCODE02
          AND p.SUBCODE03 = r.SUBCODE03
WHERE
  r.RECIPESUBCODE01 = 'SC2301'
  AND r.RECIPESUFFIXCODE = '001'
ORDER BY 
  r.GROUPNUMBER, r."SEQUENCE" ASC