SELECT
	p2.ORIGDLVSALORDLINESALORDERCODE,
	TRIM(p2.SUBCODE02) AS SUBCODE02,
	TRIM(p2.SUBCODE03) AS SUBCODE03,
	p3.LONGDESCRIPTION,
	p.*
FROM
	PRODUCTIONRESERVATION p
LEFT JOIN (
        SELECT
            DISTINCT PRODUCTIONDEMANDCODE,
            PRODUCTIONORDERCODE
        FROM
            PRODUCTIONDEMANDSTEP PRODUCTIONDEMANDSTEP
    ) PRODUCTIONDEMANDSTEP ON PRODUCTIONDEMANDSTEP.PRODUCTIONORDERCODE = p.PRODUCTIONORDERCODE 
LEFT JOIN PRODUCTIONDEMAND p2 ON p2.CODE = PRODUCTIONDEMANDSTEP.PRODUCTIONDEMANDCODE 
LEFT JOIN ADSTORAGE a ON a.UNIQUEID = p2.ABSUNIQUEID AND a.FIELDNAME = 'OriginalPDCode'
LEFT JOIN PRODUCT p3 ON p3.ITEMTYPECODE = 'DYC'	
					AND p3.SUBCODE01 = p.SUBCODE01
					AND p3.SUBCODE02 = p.SUBCODE02
					AND p3.SUBCODE03 = p.SUBCODE03
WHERE 
	p.CREATIONDATETIME >= (CURRENT_TIMESTAMP - 1 MONTHS)
	AND p.ITEMTYPEAFICODE = 'DYC'
	AND (
        a.VALUESTRING IS NULL-- asli (bukan salinan)
        OR p.CREATIONUSER IN ('kukuh.bayu','yogi.rahmansyah')-- salinan tapi hanya 2 user ini
        )
    AND p.PROGRESSSTATUS = '0'
    AND p.WAREHOUSECODE = 'M510'